### ISSUE TITLE
SkyBlocks in NETHER

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#10]
Currently, we can only have one skyworld (according to the plugin and everything).

But... it would be nice to be able to link multiple worlds together, i.e. so an island would form (protected by world-guard etc.) in nether, once you build the portal on your skyblock.

I haven't quite figured out, what you would do on an island in a sea of lava, but still, suggestions are welcome.

**Comment by woolwind** [comment]
well you wouldn't mine a lot of quartz or glowstone.  you could camp there and hunt ghasts, which would be guaranteed to  fall into the lava. No shortage of lava, perhaps some challenges requiring you to build out your nether island - obsidian challenge, yielding quartz for example.  but the explorer challenge would become nigh on impossible.

**Comment by rlf** [comment]
Going to bump this, as I just thought of something we COULD do.

The problem with nether is, that we want there to be reasons to go there, and if we just make an island in there, floating over lava, we only supply a very limited number of resources to the player when he gets there.

Also, ghast-spawning will be a pain, and wither skeletons wont spawn, unless there happens to be a nether-fortress in the seed under that island.

If we solve #421 and #469 we will already have a hook into the "spawning event", which means we can also consider controlling spawning in the "skyworld-nether".

That, in turn, means, we can allow spawning of wither skeletons under certain conditions (say on netherbrick in a certain pattern), and not just in nether-fortresses.

Reg. resources, I suggest, that we change the nether island when-ever a block is broken.
Say the player breaks a netherrack or quartz-ore, we form 1-3 (1 highest probability, 3 lowest, perhaps depending on the size of the nether-island) new blocks under or at the sides of the island.

This way, the nether-island will get sort of a prison-feel, where you can have an endless mine, and also a farm-place for withers (without having to find a nether-fortress). Also, with lava in the bottom, and an island hanging, odds are Ghasts will spawn in abundance - perhaps we can make this dependent on the nether-island-level.

Just some thoughts - really, input IS needed.

**Comment by MeddlingMoose** [comment]
I was just coming here to suggest Nether Islands! They've been something I've been craving for a couple of years now :P

Really for me the whole point of a nether island would be based off the same ideas as the regular Skyblock challenge, which is limited resources, work with what you have, etc. The main issue with having just a default nether world currently is that players will go and hunt in the nether for limitless netherrack, soul sand, gravel, lava, and quartz. Players find that it's easier to build their bases out of quartz and netherbrick than to mine the cobble...

If Nether Islands do get implemented what I would hope for would be islands floating above a nether void, and maybe something equivalent to a cobblestone generator and infinite water source for netherrack and lava. I think it would also be fun to see a branch of nether related challenges. Maybe things like Ghast hunter (getting x amount of tears), fortress builder (getting x amount of nether bricks). Just fun things to encourage players to go into the nether.

Getting things like quartz, soulsand, and glowstone could be a random output of the netherrack generator using third party plugins like [OtherDrops](http://dev.bukkit.org/bukkit-plugins/otherdrops/)

With the issue of Nether Fortresses needing to be in the seed of the world is there any way that this can be done using a world generator like multiverse? Or is that creating more work than is needed? That way each island region would have it's own one or two chunks of Nether Fortress for blaze and wither skeletons to spawn. Maybe even having something like a separate Fortress island apart from the users main nether island...

Just thinking out loud, hope some of the ideas are of use :)

**Comment by rlf** [comment]
The thing is, if we change the mechanics of minecraft, to allow players to get extra material in nether, it won't really be uSkyBlock at all.

The idea is, to get materials either by utilizing knowledge of the game-mechanics (i.e. where slimes spawn, how cobble forms, where squids spawn, how to get a gold-farm flowing, how to grow mushrooms etc.)

Meaning, I don't think we should change on that, but we COULD change the spawning in nether, i.e. so we check the sorrounding when any mob is spawned, and change it (with a probability) to a wither-skeleton if the bricks below him is formed of netherbrick.

Also, we could try to make the island grow on block-breaks, that would be a simple, but powerful way to allow farming, without making it too easy.

**Comment by csorrows** [comment]
I think the block spawning is a very cleaver way to expand when lack of materials is present such as this environment. As I have seen from past additions, I'm sure this would be a very good option and would be taken to it's full capacity. I've always wanted to enable the nether but when doing so, it gives the players almost limitless resources. I say go for it!

**Comment by rlf** [comment]
Part of the v2.5 release - closing this
