### ISSUE TITLE
Problem with official minecraft item names

### ISSUE THREAD

**Issue by Adam4CZ** [rlf/uSkyBlock#1001]
```
[15:26:39 INFO]: Name: uSkyBlock
[15:26:39 INFO]: Version: 2.7.0-SNAPSHOT
[15:26:39 INFO]: Description: Ultimate SkyBlock v2.7.3-alpha22-6-g1b4143f-1b4143-dev
[15:26:39 INFO]: Language: en (en)
[15:26:39 INFO]:   State: d=128, r=64, i=3, p=3, n=true, awe=false
[15:26:39 INFO]: Server: CraftBukkit git-Spigot-283de8b-aa522c9 (MC: 1.11.2)
[15:26:39 INFO]:   State: online=true, bungee=true
[15:26:39 INFO]: ------------------------------
[15:26:39 INFO]: Vault 1.5.6-b49 (ENABLED)
[15:26:39 INFO]: WorldEdit 6.1.5;4651611 (ENABLED)
[15:26:39 INFO]: WorldGuard 6.1.3-SNAPSHOT;c904242 (ENABLED)
[15:26:39 INFO]: Multiverse-Core 2.5-b715 (ENABLED)
[15:26:39 INFO]: Multiverse-Portals 2.5-b737 (ENABLED)
[15:26:39 INFO]: Multiverse-NetherPortals 2.5-b707 (ENABLED)
[15:26:39 INFO]: ------------------------------
```
For some items I have problem with their name. In `challenges.yml` I use e.g. **CRAFTING_TABLE** for my _displayItem_ and when I look to /challenges on the server the item has barrier texture (my _lockedDisplayItem_). If I try **WORKBENCH** instead **CRAFTING_TABLE** it is ok. But why? I am using official minecraft item name. Where can I find your item name list if you do not use official names?
This problem I have with some other items (WOODEN_PICKAXE, GOLDEN_PICKAXE, STONEBRICKS:2, ...) and this problem is also in _requiredItems_ (item is replaced by barrier again).
I want to use item names because the file is better with them (for orientation, editing etc.).

Part of _challenges.yml_ [here](http://pastebin.com/D2KGghrL).
In game: ![2017-03-16_15 53 31](https://cloud.githubusercontent.com/assets/15090021/24002640/90ef0d28-0a61-11e7-8c39-9114a6a6f523.png)

**Comment by dutchy1001** [comment]
As far I know item names used are form [here](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#WORKBENCH)

"Workbench" is to official name used

**Comment by Adam4CZ** [comment]
Ah, ok. Thanks. I used item names from original minecraft wiki (e.g. for [crafting table](http://minecraft.gamepedia.com/Crafting_Table)), so for workbench is "crafting_table"

**Comment by dutchy1001** [comment]
Those pages are not official maintained by Mojang.

**Comment by Adam4CZ** [comment]
Ok, not official, but also in game it is **crafting_table**, not _workbench_.

**Comment by Adam4CZ** [comment]
I have another problem. If I need in _requiredItems_ the sapling on the island, the name (**SAPLING:0:1**) is not recognized, but the **6:0:1** is recognized.

**Comment by rlf** [comment]
`requiredItems` when using `onIsland` challenges is a bit weird.

Most blocks in Minecraft uses a different data-value than the corresponding item-ids (inventory items).

Meaning, if you want to test a sapling, the data-values indicate more than just the type (see http://minecraft.gamepedia.com/Data_values#Saplings).

The same goes for items that can have an orientation.

Odds are, the SAPLING item-name corresponds to a different block-id than 6 in Spigot, i.e. you need to write `SAPLING_BLOCK:0:1` or similar if you don't want to use the item id.

**Comment by Adam4CZ** [comment]
I tested how it behaves and I found, that `SAPLING` work fine only for OAK sapling (`SAPLING:0:1`) but not for the other sapling (`SAPLING:<1-5>:1`). Some for the IDs (`6:<1-5>:1`). Do you now why?

**Comment by Adam4CZ** [comment]
Ok, sorry. I tested `SAPLING` again and it works. Maybe because I used another listing for `requiredItems` (one by one in differend rows, not in one row). So, it works. Thanks again.
