### ISSUE TITLE
chalenges broken

### ISSUE THREAD

**Issue by trinium112221122** [rlf/uSkyBlock#1003]
everytime i got to challenges it says reward unknown also u dont need the items to complete the challenes

vault v1.5.5
we 6.1
wg 6.1
mv core and portals 2.5-b699
mv nether portals 2.5-b675

**Comment by dutchy1001** [comment]
closed, not following the template (half the output of **_/usb version_** i missing

**Comment by trinium112221122** [comment]
dm fixed it was a broken version of essentials
