### ISSUE TITLE
USkyBlock, problem /is invite 

### ISSUE THREAD

**Issue by cacophonie** [rlf/uSkyBlock#1004]
_Please paste the output from `/usb version` below_

paste it here please (replace this text)
http://www.noelshack.com/2017-13-1490978586-versionusb.png

_What steps will reproduce the problem?_
1. Instal USkyBlock in your server
2. Instal permission ex with this perm :  http://www.noelshack.com/2017-13-1490978563-permissionusb.png
3. Do /is invite name
4. And will say u have not the perm

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

(Not following the template will result in closing the issue.)

**Comment by dutchy1001** [comment]
This should work if you have the correct permission.
You have **usb.island.invite** which is wrong.
You need **_usb.party.invite_** to make it work correct.

**Comment by cacophonie** [comment]
Hey !

Oh yes, thank u dude !
U are realy good and fast for reply :)

Have a nice day, good bye
