### ISSUE TITLE
/is spawn

### ISSUE THREAD

**Issue by cacophonie** [rlf/uSkyBlock#1005]
_Please paste the output from `/usb version` below_
```
http://www.noelshack.com/2017-13-1491038344-usbver.png

_What steps will reproduce the problem?_
1. Is not a problem, but i don't know how to set the /is spawn.


_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

(Not following the template will result in closing the issue.)

**Comment by dutchy1001** [comment]
use the Multiverse command to set spawn to a different location ( I think essentials spawn  command should work to).

**Comment by cacophonie** [comment]
Thanks for ur reply,

i did it with Multiverse, when u dead respawn in the world Skyworld, but in the config multiverse i put other world.
I think Multiverse is leting USkyBlock /is spawn, work and then multiverse will work if /is spawn is not activ

**Comment by dutchy1001** [comment]
there is an option in the config
```
  extras:
    # [true/false] If true, return players that don't have an island (this includes players removed from a party while offline), to the server spawn when they login.
    # NOTE: Requires EssentialsSpawn or another plugin with the "/spawn" command
    sendToSpawn: false
```
This setting let you choose to either spawn in the skyworld or the default spawn when joining the server were uSkyblock is installed. This can be the default "world" in most cases.

Set this to **true** to let players spawn in an other world.

**Comment by cacophonie** [comment]
So what can u do for set the /is spawn in other world & other worlds

**Comment by cacophonie** [comment]
I did it, but when he die, the player respawn in the /is spawn :/

**Comment by dutchy1001** [comment]
I'm not sure this is due that you have set a respawn world in the MV>Worlds config.
The way it should work is:
- when the "sendToSpawn" is set **false** you respawn in the skyworld
- when the "sendToSpawn" is set **true** you respawn in the main server spawn

This has been working correct for a long time.

**Comment by cacophonie** [comment]
Yes, i forget the /usb reload... x'D

Thank u very mutch Dutchy :)

**Comment by dutchy1001** [comment]
happens to us all, lol.
Glad it's sorted
