### ISSUE TITLE
[Suggestion] Custom/Empty Nether world generator

### ISSUE THREAD

**Issue by BLLaZZeR** [rlf/uSkyBlock#1008]
I've been using Cleanroom generator with MvCore to create Empty Nether but after changing SpawnSize or Default Biome in config file ( probably anything linked with MvCore),  generator is overwrited with default skyworld_nether settings.  New generated terrain looks like default skyworld_nether, same with restarted island. 
Could you implement something like Empty Nether generator or add option to set custom rooftop and lava floor ?

**Comment by rlf** [comment]
See https://github.com/rlf/uSkyBlock/wiki/SkyGrid, esp. the use of `chunk-generator`.
