### ISSUE TITLE
Usb Level IS

### ISSUE THREAD

**Issue by cacophonie** [rlf/uSkyBlock#1012]
_Please paste the output from `/usb version` below_

http://www.noelshack.com/2017-14-1491581984-usbver.png

How can i setup for have this :
[IslandLevel][Grade] PlayerName :  Blabla
[952][Admin] Cacophonie : Hi

U know what i mean ?

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

(Not following the template will result in closing the issue.)

**Comment by rlf** [comment]
What you are looking for, is placeholder support, depending on the plugins you already have in play, we might already support it. But perhaps not in the version you are using.

**Comment by cacophonie** [comment]
I am using PermissionEx.

I have actualy -> [Admin] Cacophonie : blabla.
And i want -> [MyIsLevel] [Admin] Cacophonie : blabla.

U know what i mean ?
