### ISSUE TITLE
Plugin not loading.

### ISSUE THREAD

**Issue by Staticflame** [rlf/uSkyBlock#1013]
_Please paste the output from `/usb version` below_
Unknown command, Type /help for help.
also all commands fail /Is or anything will not work.

_What steps will reproduce the problem?_
1. we had the original server it ran on but we are moving servers
2.we just pasted all server files into the new dedicated server we own now
3.Uskyblock failed to work / Doesent want to install again? 
4. we are currently running Spignot ( alwayse had it without problems)

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: https://pastebin.com/peAVX7CK  - tried to /plm load with plugin manager 

Please help us :D!

**Comment by UnioDex** [comment]
What are your Java, Spigot and uSkyBlock versions?

**Comment by mikroskeem** [comment]
> Unsupported major.minor version 52.0

Please use Java 8.
