### ISSUE TITLE
Island life-cycle events in the API (purge, delete)

### ISSUE THREAD

**Issue by YannicHock** [rlf/uSkyBlock#1015]
_Please paste the output from `/usb version` below_
```
2.7.2
```
I do not have any bugs to report. I have a wish for a future update in the API of your Plugin.
So, I'm a Developer for a Skyblock-Server with about 200 Players in maintime. We like your Plugin to much to create our own. But our map is increasing to much. It gets way to big in way to less time. And your purge function does delete the placed blocks on the different Islands, but your Plugin does not have the ability to recreate a new Island on that spot, with a new owner. So I would like to develop a 3rd Party Plugin which deletes all inactiv Islands in a specific timeperiod AND edit your lasIslandConfig.yml in a way that the empty spots can be refilled. 

Enough of my story.
For that kind of Plugin I would need an event triggered when /usb purge INT has gone through all Island and a method which returns a list of all island-locations found by your purge function.
And I would need an event fired when an island is deleted by the /usb island delete NAME command. And a method which returns the location of that, deleted Island.

With best wishes _BOOM_21
Your Plugin is the best, would be so greatfull if these things would be added to the API.

**Comment by Atompilzsammler** [comment]
Hello BOOM21

As i understand the /purge command right. Every island  with an inaktiv player will be deleted from the player folder/yaml and will be stored in the orphans.yml. If a new player create an island the postions from the orphans.yml will be used. In that way the purged island will be replaced with the starting island, so all old placed blocks will be removed. U dont need to delete them with an 3rd-party programm.

I hope u understand my bad english. :+1: 

With best wishes Atompilz5ammler

PS: Our server loves that plugin too, best Skyblock-plugin out there
