### ISSUE TITLE
TopTen List doesn't refresh / isn't getting updated

### ISSUE THREAD

**Issue by Ishidres** [rlf/uSkyBlock#1016]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.7.2
Description: Ultimate SkyBlock v2.7.2-45f756-430
Language: en (en)
 State: d=128, r=64, i=308, p=542, n=true, awe=false
Server: CraftBukkit git-Spigot-6c9b0a1-de5c261 (MC: 1.8.8)
 State: online=false, bungee=false
------------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1;no_git_id (ENABLED)
WorldGuard 6.1 (ENABLED)
Multiverse-Core 2.5.0-SNAPSHOT-b725 (ENABLED)
------------------------------------
```

_What steps will reproduce the problem?_
So my problem is, that the TopTen-Island list isn't getting updated. That means for example, it doesn't refresh, when an island gets deleted, when I'm removing blocks on the island, so the level should go down, ...

Also, I have auto-refresh enabled in config and set to about 5 min.
Whatever, my config: https://pastebin.com/AmgcvjJX

Does anyone know what the problem could be?

Would be really glad about some help :smile: !

Best wishes,
Ishidres

**Comment by Atompilzsammler** [comment]
As i know the island levels will beupdated if the /is info command has be used. After that the updated island level will be shown on /is top

**Comment by Ishidres** [comment]
Thanks for the response, but if a staff member removes a player's island or the player restarts their island, how should they do /is info? If the island is removed, they don't even have an island to do /is info on.

Isn't there a way to auto-refresh every island every **_x_** minutes?

Best wishes,
Ishidres

**Comment by Ishidres** [comment]
I would be **very** happy about a response to my question! :)

**Comment by UnioDex** [comment]
Can you try it with the latest alpha version?

**Comment by Ishidres** [comment]
I tried, but unfortunately it didn't change anything. :disappointed:
Any other idea of the problem?

**Comment by Ishidres** [comment]
bump

**Comment by rlf** [comment]
Sorry the late reply Ishidres, but buth dutchy1001 and I have too much going on elsewhere, to keep the high standard we used to on supporting uSkyBlock. There are some known issues reg. top ten, esp. when ppl leave islands or islands are abandoned or deleted. Currently we don't have a clear work-around. But I can try to describe the logic, so you might be able to find one your self.

An island score is only calculated/updated when a player belonging to the island is executing `/is info` or `/is level` - or the autoRefresh is executed *while a member of the island is online*.

Once the score has been updated, it will be used in the next top-10 generation.
Results from executing the top-10 commands are usually cached (unless you are OP), so you might not see the effect of changes imediately.

Hope this helps you in getting further with this issue.

**Comment by Ishidres** [comment]
Thanks a lot for this helpful reply.
`(Ticket is now closed.)`

**Comment by Ishidres** [comment]
Hello,
sorry, if I have to do a late answer, but you said:

> ...the autoRefresh is executed **while a member of the island is online**.

If I understand it correctly, it only recalculates the island level of an island if the member of the island is online to prevent crash. But is there a way to recalculate all the islands even if some island members are offline or just recalculate one special island level with a command?

I hope you can answer me one more time :smiley:!

Best wishes,
**Ishidres**

**Comment by Ishidres** [comment]
bump

**Comment by rlf** [comment]
If you execute `/is info <playername>` as OP, it will recalculate the score.
