### ISSUE TITLE
Bug ProtectionRange

### ISSUE THREAD

**Issue by cacophonie** [rlf/uSkyBlock#1019]
_Please paste the output from `/usb version` below_

http://www.noelshack.com/2017-16-1492432045-usbversion.png

_What steps will reproduce the problem?_
1. Create an is with island ->     protectionRange: 128
2. Setup the config to ->     protectionRange: 256
3. Reload the serveur, go on your IS, and is not 256x256 but 128x128 :c..

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

(Not following the template will result in closing the issue.)

**Comment by Ishidres** [comment]
Line 36, in your config.yml:
`distance: 128`
Change it to **256**.
I think it should work now.
