### ISSUE TITLE
[Suggestion] Delete all regions on an island if /is restart or /usb is delete

### ISSUE THREAD

**Issue by Atompilzsammler** [rlf/uSkyBlock#1023]
_Please paste the output from `/usb version` below_
```
paste it here please (replace this text)
```

_What steps will reproduce the problem?_
1. It would be nice if all regions which where create on the island will be delete if the owner restarts the island or if an admin delete the island or if the island will be overide with a new island.
2.
3.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

(Not following the template will result in closing the issue.)

**Comment by rlf** [comment]
The implications of introducing that, will lead to a lot of fuss (from server owners that do not intend this to happen). I suggest you make a small plugin, and listen for the event when an island is deleted, and then do the region cleanup your self.
