### ISSUE TITLE
In some help commands (/usb ?, /is ?) the apostrophes are not shown

### ISSUE THREAD

**Issue by Leomixer17** [rlf/uSkyBlock#1024]
In some help commands like /usb ? or /is ?, even if in language files the apostrophes are doubled, it aren't shown.

30.04 15:01:45 [Server] INFO Name: uSkyBlock
30.04 15:01:45 [Server] INFO Version: 2.7.3-alpha22
30.04 15:01:45 [Server] INFO Description: Ultimate SkyBlock v2.7.3-alpha22-9687ae-457
30.04 15:01:45 [Server] INFO Language: it (it)
30.04 15:01:45 [Server] INFO State: d=256, r=112, i=5, p=5, n=true, awe=true
30.04 15:01:45 [Server] INFO Server: Paper git-Paper-1082 (MC: 1.11.2)
30.04 15:01:45 [Server] INFO State: online=true, bungee=true
30.04 15:01:45 [Server] INFO ------------------------------
30.04 15:01:45 [Server] INFO Vault 1.5.6-b49 (ENABLED)
30.04 15:01:45 [Server] INFO WorldEdit 6.1.5;4651611 (ENABLED)
30.04 15:01:45 [Server] INFO WorldGuard 6.1.3-SNAPSHOT;c904242 (ENABLED)
30.04 15:01:45 [Server] INFO FastAsyncWorldEdit 17.04.29-f8579bd-677-12.6.7 (ENABLED)
30.04 15:01:45 [Server] INFO Multiverse-Core 2.5.0-SNAPSHOT-b725 (ENABLED)
30.04 15:01:45 [Server] INFO Multiverse-NetherPortals 2.5.0-SNAPSHOT-b714 (ENABLED)
30.04 15:01:45 [Server] INFO ------------------------------

_What steps will reproduce the problem?_
1. Select a language that have apostrophes
2. Do /usb ? or /is ? selecting a page where there is an apostrophe

**Comment by rlf** [comment]
More specific please, language in use, and term where it doesn't work.
If you use non-released .po files, please pastebin those as well, and note where they are located in your install.

**Comment by Leomixer17** [comment]
example:
http://www.mediafire.com/view/jcskpm721wcro9k/Pannello%20Aiuto%20uSkyBlock.PNG
https://pastebin.com/fHwuddSX
lines 563 and 606

**Comment by Leomixer17** [comment]
@rlf This happens only in help commands, and even if you use ony one `'`

**Comment by rlf** [comment]
I'll take a look then

**Comment by rlf** [comment]
Woah dude, that was quite a fix - not sure I got em all.

The problem was inconsistent use of `'` - everywhere they are used in translations, they need to be used with doubles (since gettext ends up using Javas MessageFormat for formatting).

Additionally the commands where translated twice (normally, you should use `marktr` first, if you use `tr` later).

The above commit should fix (most of) this problem.

**Comment by Leomixer17** [comment]
Thank you

**Comment by Leomixer17** [comment]
Unfortunately still doesn't work

**Comment by rlf** [comment]
Should work in v2.7.5 - unless I've missed a command. Could you be more specific about what command and how you try to change the translation?

**Comment by Leomixer17** [comment]
@rlf for example /usb island ?, and I've changed the translation with Poedit

**Comment by rlf** [comment]
Could you paste/hastebin your it.po file? And I'll see if I can reproduce it in my environment?

**Comment by rlf** [comment]
Ye, I've missed a lot of those admin commands (they are instantiated differently than the rest).

**Comment by Leomixer17** [comment]
https://pastebin.com/rBpTGgfu

**Comment by Leomixer17** [comment]
With /is command, with double `'` works

**Comment by rlf** [comment]
Checkout this one https://github.com/rlf/uSkyBlock/releases/download/v2.7.5-201807172117/uSkyBlock-bukkit1.12.jar should work with them all (unless I'm still missing some).

**Comment by Leomixer17** [comment]
All works
