### ISSUE TITLE
Sponge version of uSkyBlock

### ISSUE THREAD

**Issue by mikroskeem** [rlf/uSkyBlock#1028]
As previous issue asking similiar thing got closed, I think I could ask this in properly formatted question.

Are there any plans to port uSkyBlock to [Sponge](https://www.spongepowered.org/) server platform? Since Sponge is getting more popular, it seems to be good idea to start a port of uSkyBlock for it.

// enhancement (?)

**Comment by rlf** [comment]
No, not at the moment, the main contributors have stopped working on uSkyBlock - but feel free to do it your self.
