### ISSUE TITLE
Add Challenge

### ISSUE THREAD

**Issue by cacophonie** [rlf/uSkyBlock#1029]
_Please paste the output from `/usb version` below_

§7Version: §b2.7.2
§7Description: §bUltimate SkyBlock v2.7.2-45f756-430
§7Language: §bfr (fr)
§9  State: d=768, r=128, i=875, p=1 004, n=true, awe=false
§7Server: §eCraftBukkit git-Spigot-de459a2-51263e9 (MC: 1.10.2)
§9  State: online=false, bungee=false
§7------------------------------
§7§dVault §f1.5.6-b49 §7(N/A§7)
§7§dWorldEdit §f6.1.7-SNAPSHOT;3682-41de204 §7(N/A§7)
§7§dWorldGuard §f6.1.3-SNAPSHOT;c904242 §7(N/A§7)
§7§dAsyncWorldEdit §f2.3.2 §7(N/A§7)
§7§dMultiverse-Core §f2.5-b719 §7(N/A§7)
§7§dMultiverse-Portals §f2.5.0-SNAPSHOT-b748 §7(N/A§7)
§7§dMultiverse-NetherPortals §f2.5.0-SNAPSHOT-b714 §7(N/A§7)
§7------------------------------

Hi, i have actualy my challenge like this =>
http://www.noelshack.com/2017-20-1494970488-challengepage1.png

-----
Im asking u to know if i add challenge like this (circle black = a challenge) [Is for exemple] =>
![image](https://cloud.githubusercontent.com/assets/26771939/26129442/86f683fa-3a90-11e7-959b-fd9365552dd2.png)

Did the guy have completed all challenge (All the page 1) will be reset challenge or just need to work the new challenge aded ?

(Not following the template will result in closing the issue.)

**Comment by rlf** [comment]
https://github.com/rlf/uSkyBlock/wiki/challenges.yml

**Comment by cacophonie** [comment]
I know how to create challenge.
Im just asking, if a Guy have finish all challenge (group, or ligne what u want) and if it add a challenge to the first ligne of challenge gui, did the challenge of the 8 other ligne will be reset ? Or just claimed, and when he will need do the new challenge, all will be unlocked and complated, like he do it (because he have do it)

**Comment by rlf** [comment]
I honestly don't get what you are trying to ask, but I bet you can try it out, if you just put in some challenges in the `challenges.yml` file, to test it out.

**Comment by cacophonie** [comment]
Okay it's ok i have test it on a server test.

Juste how can i up the default range for the challenge with "OnIsland" please ?
