### ISSUE TITLE
IronGolem as requiredEntity doesn't work

### ISSUE THREAD

**Issue by Adam4CZ** [rlf/uSkyBlock#1033]
_Please paste the output from `/usb version` below_
```
 Name: uSkyBlock
 Version: 2.7.0-SNAPSHOT
 Description: Ultimate SkyBlock v2.7.3-alpha23-44151f-dev
 Language: en (en)
   State: d=128, r=64, i=5, p=3, n=true, awe=false
 Server: CraftBukkit git-Spigot-6629162-c7920f4 (MC: 1.12-pre5)
   State: online=true, bungee=true
 ------------------------------
 Vault 1.5.6-b49 (ENABLED)
 WorldEdit 6.1.5;4651611 (ENABLED)
 WorldGuard 6.2.1-SNAPSHOT;9e88d1a (ENABLED)
 Multiverse-Core 2.5.0-SNAPSHOT-b725 (ENABLED)
 Multiverse-Portals 2.5.0-SNAPSHOT-b748 (ENABLED)
 Multiverse-NetherPortals 2.5.0-SNAPSHOT-b714 (ENABLED)
 ------------------------------
```

_What steps will reproduce the problem?_
I have problem with the IronGolem as requiredEntity in my challenge. I want to check if there are 16 villagers and 2 iron golem on island but the challenge count only villagers and the golems aren't in challenge requirements. I have tried `IronGolem`, `Iron_Golem`, `VillagerGolem`, `Villager_Golem` etc.. (also with ' ' and also with capital letters) and nothing works (btw. variants without underline causes errors).

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* from challenges.yml: https://pastebin.com/raw/MGu1VNGp
* screenshot: http://i.imgur.com/sTNE1SJ.png

**Comment by rlf** [comment]
The correct name of the Iron Golem entity, is `VILLAGER_GOLEM`, not `IRON_GOLEM`.

**Comment by Adam4CZ** [comment]
@rlf I have tried also VILLAGER_GOLEM and doesn't work and causes errors.

>  I have tried IronGolem, Iron_Golem, VillagerGolem, Villager_Golem etc.. (also with ' ' and also with capital letters) and nothing works (btw. variants without underline causes errors).
