### ISSUE TITLE
Plugin doesn't work.....

### ISSUE THREAD

**Issue by Blazingfighter3** [rlf/uSkyBlock#1035]
_Please paste the output from `/usb version` below_

https://gyazo.com/a7b61fe00fc4e6dbd87fe78882488aab

_What steps will reproduce the problem?_
1.I don't understand what you mean
2.I don't understand what you mean
3.I don't understand what you mean

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

(Not following the template will result in closing the issue.)

I don't understand this template, sorry.

My plugin just gives errors when trying to use the command /is when you are default rank.

**Comment by Adam4CZ** [comment]
So, where is the error log? Paste them to pastebin.com and paste link here.
