### ISSUE TITLE
How to remove a player from TopTen List?

### ISSUE THREAD

**Issue by Ishidres** [rlf/uSkyBlock#1038]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.7.2
Description: Ultimate SkyBlock v2.7.2-45f756-430
Language: en (en)
 State: d=128, r=64, i=308, p=542, n=true, awe=false
Server: CraftBukkit git-Spigot-6c9b0a1-de5c261 (MC: 1.8.8)
 State: online=false, bungee=false
------------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1;no_git_id (ENABLED)
WorldGuard 6.1 (ENABLED)
Multiverse-Core 2.5.0-SNAPSHOT-b725 (ENABLED)
------------------------------------
```

_What steps will reproduce the problem?_
When an admin deletes the island of a player or a player leaves their island, the topten scoreboard won't update, which means the island level of the players' island is still shown.

How can I fix this?
How can I remove the player from the topten list, because using /usb topten **will only update the scores if the players are online**.

Best wishes,
Ishidres

**Comment by Ishidres** [comment]
nobody? :cry:

**Comment by Ishidres** [comment]
**Please, please help me! :cry: :disappointed:**

**Comment by rlf** [comment]
`/is info <playername>` as OP
