### ISSUE TITLE
BUG w/ the command /is perm

### ISSUE THREAD

**Issue by Bakalexis** [rlf/uSkyBlock#1055]
Name: uSkyBlock
 Version: 2.7.3-alpha23
 Description: Ultimate SkyBlock v2.7.3-alpha23-44151f-458
 Language: fr (fr)
   State: d=160, r=80, i=66 130, p=118 729, n=false, awe=true
 Server: CraftBukkit git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)
   State: online=true, bungee=true
 ------------------------------
 Vault 1.5.6-b49 (ENABLED)
 WorldEdit 6.1.5;4651611 (ENABLED)
 WorldGuard 6.0.0-beta-04.1544- (ENABLED)
 FastAsyncWorldEdit 17.09.17-917d3f3-898-16.5.16 (ENABLED)
 Multiverse-Core 2.5-b699 (ENABLED)
 ------------------------------

1. Join an island
2. Do /is perm <name of someone on island> <island permission>
3. Done without using permissions system

**Comment by Bakalexis** [comment]
I checked the last code version and i was not able to see where the plugin is asking for permission from island in PermCommand

**Comment by DarkObscurity** [comment]
If you do not use a permission system it uses the permissions definded in the plugin.yml wich you can find by opening the .jar file with a archive program like winrar

**Comment by Bakalexis** [comment]
The fact is that i'm using PermissionsEx and it is configured for disallow the command /is perm by default
