### ISSUE TITLE
When player jump in the world end he die and don't teleporting to your island, but teleporting to bedrock block with no island!

### ISSUE THREAD

**Issue by lucasnsimao** [rlf/uSkyBlock#1058]
_Please paste the output from `/usb version` below_
Name: uSkyBlock
Version: 2.7.2
Description: Ultimate SkyBlock v2.7.2-45f756-430
Language: en (en)
  State: d=128 r=64 I=6 p=6 n=true awe=false
Server: 
  State: CraftBukkit git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
-----------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1;no_git_id (ENABLED)
WorldGuard 6.1 (ENABLED)
Multiverse-Core 2.5-b699 (ENABLED)

_What steps will reproduce the problem?_
1.When player jump in the end of world he die and teleporting to bedrock block not in your island!

LOG:
[13:15:32 INFO]: [uSkyBlock] Enabling uSkyBlock v2.7.2
[13:15:32 INFO]: [uSkyBlock] 2 schematics loaded.
[13:15:32 INFO]: [uSkyBlock] §7Name: §buSkyBlock
§7Version: §b2.7.2
§7Description: §bUltimate SkyBlock v2.7.2-45f756-430
§7Language: §ben (en)
§9  State: d=128, r=64, i=6, p=6, n=true, awe=false
§7Server: §eCraftBukkit git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
§9  State: online=false, bungee=false
§7------------------------------
§7§dVault §f1.5.6-b49 §7(N/A§7)
§7§dWorldEdit §f6.1;no_git_id §7(N/A§7)
§7§dWorldGuard §f6.1 §7(N/A§7)
§7§dMultiverse-Core §f2.5-b699 §7(N/A§7)
§7------------------------------
[13:15:34 INFO]: [uSkyBlock] Hooked into Vault Economy
[13:15:34 INFO]: [uSkyBlock] Hooked into Vault Permissions
[13:15:41 INFO]: [WorldGuard] Region data changes made in 'skyworld_nether' have been background saved
[13:15:41 INFO]: [WorldGuard] Region data changes made in 'skyworld' have been background saved

(Not following the template will result in closing the issue.)

**Comment by UnioDex** [comment]
WorldGuard config > Disable Void Damage > False
