### ISSUE TITLE
is create pushing an error

### ISSUE THREAD

**Issue by brenybeast** [rlf/uSkyBlock#106]
So I updated from v2.0.1-RC1.17 to v2.0.1-RC1.27, I deleted and set up the configs again as it mentioned,

Now when players run /is create it errors - http://pastebin.com/rS7E32WG

Sorry if this is an error on my end, i've backed up the server to the last working version as i can't seem to fix it on my end.

Thank you,
- BrenyBeast

**Comment by rlf** [comment]
`/usb delete`  has been moved in under the `/dev island delete` along with remove and other island related commands.
