### ISSUE TITLE
Server close

### ISSUE THREAD

**Issue by Christian3g** [rlf/uSkyBlock#1065]
_Please paste the output from `/usb version` below_

https://user-images.githubusercontent.com/40437451/41672966-ad958734-74bb-11e8-9aa9-fbac9cb42084.png

_What steps will reproduce the problem?_
1. My server close when i die efter i put the uskyblock plugin on.
2. How to do so if u die u go to spawn

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
https://pastebin.com/sbtjgc5q

(Not following the template will result in closing the issue.)

**Comment by BlackBeltPanda** [comment]
Your Essentials' spawn.yml file seems to be corrupt. Try deleting it from the Essentials plugin folder and reset your spawn point with "/setspawn".
