### ISSUE TITLE
Bug counting players in islands

### ISSUE THREAD

**Issue by Bakalexis** [rlf/uSkyBlock#1068]
Name: uSkyBlock
Version: 2.7.3-alpha23
Description: Ultimate SkyBlock v2.7.3-alpha23-44151f-458
Language: fr (fr)
State: d=160, r=80, i=75 520, p=230 003, n=false, awe=true
Server: CraftBukkit git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)
State: online=true, bungee=true
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.5;4651611 (ENABLED)
WorldGuard 6.0.0-beta-04.1544- (ENABLED)
FastAsyncWorldEdit 17.09.17-917d3f3-898-16.5.16 (ENABLED)
Multiverse-Core 2.5-b699 (ENABLED)

1. Join an island (with invite request)
2. Disconnect
3. The owner have to kick the player who joined when disconnected
4. The player is still shown on the island menu and counted as an active player

(The player is kicked out of the island sometimes when he reconnect, but this cause bugs)

There is a funny fact here, 'cause I have a lot of active players and some island just dropped the player count under 0 (like -18/8) or above (9/8), the player limit is 8 but it is showing negative number of players or impossible numbers.

I haven't seen any issues report for this in 2.7.4 version.

**Comment by rlf** [comment]
You are not using 2.7.4 version.

**Comment by Bakalexis** [comment]
Ok, but is the problem solved in 2.7.4 ?

**Comment by Lmmb74** [comment]
Shouldn't you try with the latest version first?

**Comment by rlf** [comment]
Give a way to reproduce, and I'll answer you.
I.e. be specific, what commands are executed, in what order, and how do you see it.
Note: Bukkit 1.8 isn't supported anymore (only 1.12+)

**Comment by Bakalexis** [comment]
Just, join an island, then you have to disconnect.
The leader of the island need to is kick the player.
The island counter is not updated if the player isn't connected when he's kicked out the island.

**Comment by rlf** [comment]
What is your `config.yml`? Esp. what sort of `playerdb` do you have configured?

**Comment by rlf** [comment]
Unable to reproduce
