### ISSUE TITLE
MVdWPlaceholderAPI integration not working with latest release of MVdWPlaceholderAPI 

### ISSUE THREAD

**Issue by Lakebighead** [rlf/uSkyBlock#1079]
_Please paste the output from `/usb version` below_
( I can't use commands due to the plugin being broken. But it is the very very recent update released (Uskyblock-bukkit1.13) 
```
paste it here please (replace this text)
```

_What steps will reproduce the problem?_
1. I have no idea?
2. Commands won't work
3. Probably the placeholder (It is also updated to the max version)

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: https://pastebin.com/TrDAppF9
Edit: there is also this: https://pastebin.com/SUQuAT2M
(Not following the template will result in closing the issue.)

**Comment by Lakebighead** [comment]
Here is my config.yml
https://pastebin.com/8CjrYrfa

**Comment by Lakebighead** [comment]
I updated my plugin back to 1.12 and 2.7.5 (latest) and the MVdWPlaceholderAPI plugin was working for a few hours then crashed my server completely. (I have also reset my configs)
https://pastebin.com/ef5UHmUJ
https://pastebin.com/QvDNGbVg

**Comment by Lakebighead** [comment]
Just saying my server is only 1.12.2

**Comment by Lakebighead** [comment]
Sorry for another reply but I started by server up an hour later. It worked. Some commands are functional.
https://pastebin.com/E9T9kAXq
/usb reload doesn't work and you can take stuff out of the "/is" menu section

**Comment by rlf** [comment]
Just disable the placeholder integration in the config.yml file, and get on without the placeholder support for now.

**Comment by rlf** [comment]
My focus is on 1.13 - so I won't get to this any time soon

**Comment by Muspah** [comment]
Fixed in 0e5fdbf
