### ISSUE TITLE
uSkyblock - When I create island it shutdown the server

### ISSUE THREAD

**Issue by lantien1** [rlf/uSkyBlock#1081]
https://youtu.be/iJwNoVsAY-M

**Comment by rlf** [comment]
Could you provide the output from usb version? And the server liga (pastebin) please

**Comment by TobiasLP** [comment]
I have the same Error:
When I create an island, it takes a little while and the server crashes.

server logs:
https://pastebin.com/cd8nW0LH

/usb version:
http://prntscr.com/kmbwtz

**Comment by SgtLegoTown** [comment]
by any chanche are you using the emptyworldgenerator ? that gives this error and closes down the server can you provide me with this information if you are using the old emptyworldgenerator i advice to switch too : VoidGenerator-1.3.1.jar

**Comment by rlf** [comment]
Update your version of Spigot, that error is a known error, that were fixed quite a long time ago.
