### ISSUE TITLE
[Suggestion] Add Block limits to "/is limts"

### ISSUE THREAD

**Issue by Andro609** [rlf/uSkyBlock#1082]
Title says it all really...

Add Hopper limit, if set, to readout of "/is limits"

(It's a number that's really important to farming/technical players, but doesn't appear anywhere but in the config file.)

Not sure what other limits there are.. maybe villager trading status, as well ?

**Comment by rlf** [comment]
It's added now, but the "blocklimits" are lazy loaded, so it might not be visible until it's "ready".
