### ISSUE TITLE
Error occurred while enabling uSkyBlock v2.7.6-RC3 (Is it up to date?)

### ISSUE THREAD

**Issue by NGaming** [rlf/uSkyBlock#1085]
**Hello
The Plugin dont load! I have this Plugins:**
https://i.imgur.com/UOEHgCG.png
**And this is the Error Code**
https://pastebin.com/6GxGUzAe
**Please Help me Fast!**

**Comment by rlf** [comment]
Install Vault above v1.5 - as that is required, please

**Comment by NGaming** [comment]
rlf isnt working, i have installed v1.5, 1.5.5, 1.5.6 noting works, i have the same error
