### ISSUE TITLE
Asyncworledit

### ISSUE THREAD

**Issue by Lakebighead** [rlf/uSkyBlock#1091]
_Please paste the output from `/usb version` below_
```
https://gyazo.com/77abe2811710247171422cd1e668dc51
```

_What steps will reproduce the problem?_
1. Uhh asyncworldedit is bugging lmao
2. 
3. 

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: https://pastebin.com/KzqmKtT0

(Not following the template will result in closing the issue.)

**Comment by SgtLegoTown** [comment]
could you do a complete paste of the usb v output i included a example 👍 

https://pastebin.com/WKMtVi2L

**Comment by rlf** [comment]
AsyncWorldEdit isn't supported in the latest versions. Since they haven't yet released a version that works with WorldEdit 7.0.0+

**Comment by Muspah** [comment]
Please create a new issue when the problem still persists on recent builds :)
