### ISSUE TITLE
WorldGuard 6.0 Notification

### ISSUE THREAD

**Issue by AsteriskDotHack** [rlf/uSkyBlock#1092]
_Please paste the output from `/usb version` below_
- I can't do anything within the server, i always get a worldguard 6.0 notification. However i am using the 1.13 jar and iv tried both 1.12 and a 1.13 snapshot of worldguard.

Console response to usb v:
27.08 09:35:24 [Server] INFO [09:35:24 INFO]: Command is currently disabled!

_What steps will reproduce the problem?_
1. Typing anything related to the plugin

**Comment by SgtLegoTown** [comment]
this sounds to me as a permission issue can you type usb v in console ndn paste that or do you have logs of the error that occurs ? you have to provide us with a bit more inmformation then this

**Comment by Muspah** [comment]
We're already on WorldGuard 7.0.0, please create a new issue when the problem still persists on recent builds :)
