### ISSUE TITLE
Question - NukkitX Support

### ISSUE THREAD

**Issue by NycuRO** [rlf/uSkyBlock#1093]
Hello guys and sorry because i don't use exemple for complete this issue, but it's not actually a issue, and a request.

Much much people like MCBE *MCPE*, and i am the person who like too. This plugin is actually for bukkit, from where i see.

NukkitX is a Software Java for MCPE, with API ALMOST SAME with Bukkit and i can ask if you want add support and for them.

Much plugins have support NukkitX too because it's really easy to convert functions and others, like:

LuckPerms: https://github.com/lucko/LuckPerms
FAWE: https://github.com/boy0001/FastAsyncWorldedit

And others.

You don't need re-copy all code and addapt for them, you can create a mechanism like FAWE to addapt command and others, and where you can't, it's easy to port.

You can find project here: https://github.com/NukkitX/Nukkit

Thanks so much because you read this issue and thank you for all your support :) 

Glad, NycuRO.

**Comment by rlf** [comment]
Sorry, but no. I'm not going to put effort into supporting Nukkit anytime soon. Nor Sponge or Forge.,

**Comment by NycuRO** [comment]
Why not?
