### ISSUE TITLE
Sand and Gravel are not falling in uSkyBlock

### ISSUE THREAD

**Issue by GothicGirl9888** [rlf/uSkyBlock#1097]
```
uskyblock v2.7.2
```
1.If I place a Block of sand or gravel at any block, it doesnt fall it just disappears
2.When I place a normal Block after that,the Block of Sand or Gravel replaces the normal Block
3. I checked the config file of Worldguard but nothing is there, as well with the uSkyBlock config files

**Comment by BlackBeltPanda** [comment]
Are you using FastAsyncWorldEdit?

**Comment by SgtLegoTown** [comment]
can you pls past the output of your /usb v that provides a lot of information

**Comment by DeadIntermediate** [comment]
I tried to replicate the issue with falling sand just disappearing. I seem to have no issue I am on running on 1.13.1 on spigot.

**Comment by Muspah** [comment]
You're issue is one of the older ones on this repository and we've pushed new updates to [SpigotMC.org](https://www.spigotmc.org/resources/uskyblock-revived.66795/). Please open a new issue if the problem still persists in the latest version.
