### ISSUE TITLE
Error on mobs on fire

### ISSUE THREAD

**Issue by MCRakaan** [rlf/uSkyBlock#1099]
Please paste the output from `/usb version` below
Name: uSkyBlock
Version: 2.7.5-SNAPSHOT
Description: Ultimate SkyBlock v2.7.6-RC5-e5c0c5
Language: en (en)
State: d=128, r=64, i=14, p=12, n=true, awe=false
Server: Paper git-Paper-235 (MC: 1.13.1)
State: online=true, bungee=true
Vault 1.6.7-b${env.TRAVIS_BUILD_NUMBER} (ENABLED)
WorldEdit 7.0.0-SNAPSHOT;3860-2521a9a (ENABLED)
WorldGuard 7.0.0-SNAPSHOT;1744-8e819f7 (ENABLED)
Multiverse-Core 2.6.0-b738 (ENABLED)

What steps will reproduce the problem?
1. spawn any monster
2.set it on fire

https://pastebin.com/kSCTBUbn

**Comment by Jupiterbe** [comment]
Temp fix!
in the config
Set:
visitors:
  fire-damage: false  (on true it gives a error)

For the dev! FIX IT!
mob is seen as visitor!

**Comment by Muspah** [comment]
This bug is introduced in the commit associated with #1057 and only occurs if options.protection.visitors.monster-damage is enabled in the config file.

Testing changes to fix this atm.
