### ISSUE TITLE
Sign-based shop

### ISSUE THREAD

**Issue by Lukas0610** [rlf/uSkyBlock#110]
Maybe you could implement a shop with signs.

I need it for my server, because we want to have a shop for SkyBlock.

The shop isn't in the SkyBlock world and is should not give the player items because we use MultiInv.
You could create a database and insert all items a user bought.

**Comment by dutchy1001** [comment]
There are plugins to use signs for shops, Essentials has it build-in and more are available on the bukkit pages.
I never have used MultiInv but I use Multiverse-Inventories which let you connect worlds you can and can't share items between the worlds. 
As of now I dont see why we should add an other shop, we have already the use for "Chest Command GUI" which support a shop aswell.

**Comment by rlf** [comment]
Agree with Dutchy on this one - closing the issue.
