### ISSUE TITLE
uSkyblock GUI Interferring with UltraPermissions Plugin

### ISSUE THREAD

**Issue by DeadIntermediate** [rlf/uSkyBlock#1102]
_Please paste the output from `/usb version` below_
```
https://pastebin.com/st2tQff0

_What steps will reproduce the problem?_
1. Typing the command in game "/uperms"
2.
3.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log:  Don't have one but here is a link to a gif I made to show.
https://media.giphy.com/media/9JjXri2DImu2N5Wl5A/giphy.gif

(Not following the template will result in closing the issue.)

**Comment by ziez456** [comment]
Same very annoying!

**Comment by TheRobLP** [comment]
> Same very annoying!

Yes, indeed. But as it seems BlackBelt will fix it since he labeled it as a bug. Thanks in advance for that :-)

**Comment by Muspah** [comment]
Spotted this issue while doing other refactoring. It seems like PR #1224 might fix this, but I'm unable to do testing with UltraPermissions because it's premium. Any feedback is appreciated when version 2.8.4 is released.

**Comment by Muspah** [comment]
If anyone is able to test this, the latest SNAPSHOT builds _should_ be working fine: https://www.uskyblock.ovh/downloads/master/uSkyBlock/uSkyBlock-2.8.4-SNAPSHOT.jar

Please don't run it on a production server.
