### ISSUE TITLE
Challenges not appearing and console error.

### ISSUE THREAD

**Issue by redfalcon5** [rlf/uSkyBlock#1107]
_Please paste the output from `/usb version` below_
v2.7.6-RC3
Vault v1.7.1-b91
WE v7.0.0 snapshot
WG v7.0.0 snapshot
Multiverse-core v2.6.0-b738
Multiverse-portals v2.5.2 snapshot-b766
Multiverse-netherportals v2.5.2 snapshot-b729
Spigot v1.13.1

_What steps will reproduce the problem?_
1.Join skyblock world
2.Click Challenges in /is gui
3.Nothing appears and error message in console.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: https://pastebin.com/tN9hmhRt

(Not following the template will result in closing the issue.)

**Comment by SpectreDonut** [comment]
Could you please tell us how you fixed this? a lot of people are having the same problem.
