### ISSUE TITLE
the world is not creating

### ISSUE THREAD

**Issue by Bobbbe** [rlf/uSkyBlock#1116]
_Please paste the output from `/usb version` below_
v2.7.6-201809101626 
paste it here please (replace this text)
uSkyBlock depends on WorldEdit >= v7.0 but only vunspecified was found!
 but i have FAWE v18.10.26-94d5028-2069 !!! 
[WorldGuard] Loading WorldGuard v7.0.0-SNAPSHOT;0dc5781
[uSkyBlock] Loading uSkyBlock v2.7.6-201809101626
[Multiverse-Portals] Enabling Multiverse-Portals v2.5.2-SNAPSHOT-b766
[WorldGuard] Enabling WorldGuard v7.0.0-SNAPSHOT;0dc5781
[Multiverse-NetherPortals] Enabling Multiverse-NetherPortals v2.5.2-SNAPSHOT-b729

_What steps will reproduce the problem?_
1.
2.
3.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

(Not following the template will result in closing the issue.)

**Comment by BlackBeltPanda** [comment]
#1117
