### ISSUE TITLE
Prevention of Lure Scams

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#112]
If servers have lava damage enabled in their WorldGuard config, many players will scam others to tpa to them and kill them upon acceptance with lava, or perhaps using other methods. There should be an option that gives visiting players a sort of invincibility when they are in other island regions.

**Comment by rlf** [comment]
That should be tied with the pvp setting then, so pvp allows lava-damage to visitors, but non-pvp disallows it?

**Comment by TheMattVid** [comment]
I agree completely with taking this approach. I would also include having non-pvp disallow fall damage, as well, because that's another primary method for stealing the items of visitors.

**Comment by rlf** [comment]
But, fall damage IS a pivotal part of managing an island.
Additionally, preventing fall damage would allow players to cheat (i.e. get a visitor to get somewhere, then tp to him).

**Comment by rlf** [comment]
Also, no-one should use tpa on sky, they should rather be using `/is warp` since that one guarantess a "safe location".

**Comment by TheMattVid** [comment]
If an island has progressed to the point where there's an entire lower platform, chances are that the island owner has created his own convenient way to get to that platform. For my server, I was planning on making /is warp a privilege for players who have advanced further, but I still want to allow other players to have visitors before they have reached this point. There's also the possibility that islands that have a warp want to put it in their shop and keep the rest of the island off-limits, but if they have a friend who wants to visit the rest of the island, they can conveniently be tpa'ed to somewhere else on the island. For that reason, /tpa is going to be a fundamental part of my server that all players have access to. I understand your concern with lumping it into the entire non-pvp option, but if you can give this an option of it's own, I would appreciate it a ton.

**Comment by rlf** [comment]
These requests could be made into something more "flexible", if we simply allowed for the island world-guard region to have "extra" flags - that way, you could do a `-g NONOWNERS invinsible allow`.

I will, how-ever, look into adding it to USB.

Btw. lure-scams with fall damage won't do much harm, since the person being lured could just use /back?
