### ISSUE TITLE
Invited players can use /makeleader to take over island

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#113]
The command /makeleader can be used by invited players to make themselfs island leader.
The orginal owner can still kick that player of the island.
The orginal owner can't invite  a player after as he is not the leader now.(he can use the /makeleader to take controle again)
The kicked player cant go back to the island(after being kicked), but is still classed as leader.
Worldguard setting is set to the orginal owner but the greeting and farewell messages are set to the player that used /makeleader(aslong the orginal owner hasn't used /makeleader again).
After the kicked player makes a new island the greeting and farewell message are still set to the previous island so both islands have the same message(untill someone else uses /makeleader on the island.

**Comment by rlf** [comment]
Ouch. should be fixed ASAP.

**Comment by rlf** [comment]
Should be fixed - please verify.

**Comment by rlf** [comment]
I'm not sure whether the fix is enough - since the scenario described seems that we have multiple "issues" hidden in the "leadership-management" of an island.

**Comment by dutchy1001** [comment]
tested and fixed in the latest release.
