### ISSUE TITLE
Bringing up the maven repository back

### ISSUE THREAD

**Issue by Banbeucmas** [rlf/uSkyBlock#1137]
Since the original one has died out, should we consider reopening it? 
Will be a lot easier for 3rd party plugins to hook and work with.

**Comment by Muspah** [comment]
Absolutely, but it might be a better idea to do something like CodeMC.org instead of self-hosting something, seeing the current state of the project and @rlf vanishing.

**Comment by Muspah** [comment]
See https://github.com/uskyblock/uskyblock-repo
