### ISSUE TITLE
Challenges not working

### ISSUE THREAD

**Issue by Alchemi1963** [rlf/uSkyBlock#1139]
_Please paste the output from `/usb version` below_
```
Vault 1.7.1-b91 (ENABLED)
WorldEdit 7.0.0-beta-01;8975469 (ENABLED)
WorldGuard 7.0.0-beta01;01dfebe (ENABLED)
Multiverse-Core 2.6.0-b738 (ENABLED)
Multiverse-Portals 2.5.2-SNAPSHOT-b766 (ENABLED)
Multiverse-NetherPortals 2.5.2-SNAPSHOT-b729 (ENABLED)
```

_What steps will reproduce the problem?_
1. /is
2. Clicking on the challenges
3. /challenges

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: https://pastebin.com/g7vGCL1V

**Comment by Muspah** [comment]
This should be fixed in [the latest version from SpigotMC.org](https://www.spigotmc.org/resources/uskyblock-revived.66795/). Please open a new issue if the problem still persists in the latest version.
