### ISSUE TITLE
Option for players to build on an island without losing their own

### ISSUE THREAD

**Issue by hgreatrex** [rlf/uSkyBlock#1145]
FEATURE REQUEST
Hi, 

We run skyblock non competitively, so our players would like to be able to help build on another island without losing their own build.   Reading back through the threads, was this feature ever implemented?  

For example, we would like
**The option to allow a player to be a "member/builder" on a permission-specified number of islands
The option to allow a player to be an "owner" of a permission-specified number of islands**

Relevant threads.
https://github.com/rlf/uSkyBlock/issues/104
https://github.com/rlf/uSkyBlock/issues/138

Sorry if this is a basic question, it's been a while since I dug into the uskyblock yml files.

Thanks!

**Comment by BlackBeltPanda** [comment]
This feature has been present for quite some time, now. Simply use "/is trust <playerName>" to "trust" a player, allowing them to build on your island without being a part of your island party.

**Comment by hgreatrex** [comment]
Thanks!

Dr Helen Greatrex
Associate Research Scientist
Financial Instrument Sector team
International Research Institute for Climate and Society
Columbia University, New York
