### ISSUE TITLE
Deleted island , No new island is getting created there

### ISSUE THREAD

**Issue by ziez456** [rlf/uSkyBlock#1147]
_Please paste the output from `/usb version` below_
```
paste it here please (replace this text)
```

_What steps will reproduce the problem?_
1. Deleting an island in the configs and players
2. Empty space also removed region
3. When new island is created it goes completely somewhere esle

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

(Not following the template will result in closing the issue.)

**Comment by Muspah** [comment]
Regarding step #1, are you just removing the player and island related yaml-files from disk to remove an island or via the (admin) commands like /usb island?

**Comment by ziez456** [comment]
> Regarding step #1, are you just removing the player and island related yaml-files from disk to remove an island or via the (admin) commands like /usb island?

Via the files

**Comment by Muspah** [comment]
It sounds like you're trying to do something unsupported by directly modifying the playerfiles. Please try again using the built-in commands (/usb island) to delete islands. That should trigger the correct code to add the location as an orphan and re-use it later.
