### ISSUE TITLE
everytime i make a sb, my server crash

### ISSUE THREAD

**Issue by epicgamer918492838984828482749274927** [rlf/uSkyBlock#1152]
_Please paste the output from `/usb version` below_
```
paste it here please (replace this text)
```

_What steps will reproduce the problem?_
1.
2.
3.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

(Not following the template will result in closing the issue.)

ok so everytime i do the command to make the skyblock world, i get crashed. i use plug pocketmine and idk if its compatible with that or not.

sry if i have bad grammar, im currently rushing through.

**Comment by BlackBeltPanda** [comment]
This is not a PocketMine plugin.
