### ISSUE TITLE
BİGGG BUG!

### ISSUE THREAD

**Issue by successed** [rlf/uSkyBlock#1155]
usb version : http://prntscr.com/mcv392

BUG! : https://media.discordapp.net/attachments/411564947391119363/539116969647931392/unknown.png

**Comment by pepek112** [comment]
Use English or write any comment about Your problem

**Comment by successed** [comment]
> Use English or write any comment about Your problem

check img, island team buggy...

**Comment by pepek112** [comment]
Config pls, And traslate file

**Comment by pepek112** [comment]
On Clear Uskyblock Group counter working well...
Check twice Your config mate

![Imgur](https://i.imgur.com/hzHUSHW.png)
