### ISSUE TITLE
İS RESET BUG!

### ISSUE THREAD

**Issue by successed** [rlf/uSkyBlock#1156]
_Please paste the output from `/usb version` below_
http://prntscr.com/mcv392

_What steps will reproduce the problem?_
1. when a player refreshes the island
2. command and chat sending of all players is blocked.
3. Players are falling into the gap during the regeneration of the island.
4, players are not going on the spawn.

**Comment by SpectreDonut** [comment]
I have the same problem.

**Comment by Muspah** [comment]
I can't reproduce in [the latest version from SpigotMC.org](https://www.spigotmc.org/resources/uskyblock-revived.66795/). Please open a new issue if the problem still persists in the latest version.

**Comment by successed** [comment]
> I can't reproduce in [the latest version from SpigotMC.org](https://www.spigotmc.org/resources/uskyblock-revived.66795/). Please open a new issue if the problem still persists in the latest version.

i have 1.14.2, not 1.13

**Comment by Muspah** [comment]
There's no stable uSkyBlock build for 1.14.2 at the moment, sorry.

**Comment by successed** [comment]
> There's no stable uSkyBlock build for 1.14.2 at the moment, sorry.

Update.

**Comment by Muspah** [comment]
I don't have a magic wand, sorry. A few methods we really need to support 1.14 (like regenerating chunks) are not implemented at the moment in CraftBukkit so we have to wait or create our own implementation. Dependencies are not always up2date (or stable, like MV-netherportals 3.0.0) and a lot of other things.......

You're welcome to PR changes to support 1.14 and help speed up the process. Please PR to the Bukkit-1.14 branch 😊
