### ISSUE TITLE
Could not pass event InventoryClickEvent

### ISSUE THREAD

**Issue by ekul361** [rlf/uSkyBlock#116]
Hello, I am on 1.8 and I have been trying to get this error fixed; I have uSkyBlock v2.0.1-SNAPSHOT-411e57 I believe the latest version, here is a full error list.
```
01.01 18:17:00 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[spigot.jar:git-Spigot-f2cd9c3]
01.01 18:17:00 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
01.01 18:17:00 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
01.01 18:17:00 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_65]
01.01 18:17:00 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_65]
01.01 18:17:00 [Server] INFO at us.talabrek.ultimateskyblock.event.MenuEvents.guiClick(MenuEvents.java:22) ~[?:?]
01.01 18:17:00 [Server] INFO at us.talabrek.ultimateskyblock.SkyBlockMenu.onClick(SkyBlockMenu.java:1066) ~[?:?]
01.01 18:17:00 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:245) ~[spigot.jar:git-Spigot-f2cd9c3]
01.01 18:17:00 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:643) ~[spigot.jar:git-Spigot-f2cd9c3]
01.01 18:17:00 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-f2cd9c3]
01.01 18:17:00 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-f2cd9c3]
01.01 18:17:00 [Server] INFO Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'island' in plugin uSkyBlock v2.0.1-SNAPSHOT-411e57
01.01 18:17:00 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
01.01 18:17:00 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:528) [spigot.jar:git-Spigot-f2cd9c3]
01.01 18:17:00 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:625) [spigot.jar:git-Spigot-f2cd9c3]
01.01 18:17:00 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-f2cd9c3]
01.01 18:17:00 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:684) [spigot.jar:git-Spigot-f2cd9c3]
01.01 18:17:00 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_65]
01.01 18:17:00 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_65]
01.01 18:17:00 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-f2cd9c3]
01.01 18:17:00 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:9) [spigot.jar:git-Spigot-f2cd9c3]
01.01 18:17:00 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:31) [spigot.jar:git-Spigot-f2cd9c3]
01.01 18:17:00 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1577) [spigot.jar:git-Spigot-f2cd9c3]
01.01 18:17:00 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [spigot.jar:git-Spigot-f2cd9c3]
01.01 18:17:00 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [spigot.jar:git-Spigot-f2cd9c3]
01.01 18:17:00 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f2cd9c3]
01.01 18:17:00 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[spigot.jar:git-Spigot-f2cd9c3]
01.01 18:17:00 [Server] INFO org.bukkit.event.EventException
01.01 18:17:00 [Server] INFO [18:17:00 ERROR]: Could not pass event InventoryClickEvent to uSkyBlock v2.0.1-SNAPSHOT-411e57
01.01 18:17:00 [Server] INFO [18:17:00 INFO]: [uSkyBlock] [uSkyBlock] Creating player island..
```
Please help, Thank you in advance.

**Comment by 0ProGamer0** [comment]
Same thing

**Comment by rlf** [comment]
Could you describe what you are doing when it happens?

**Comment by rlf** [comment]
It seems to be happening when you click the `/is create` button (the grass block in the UI).

I would guess it's caused by players not having the appropriate permission to create islands.
They need the `usb.island.create` permission in order to create islands.

**Comment by ekul361** [comment]
Well I have already had that permission in, but It has the same error, but if I do the command it says:
02.01 07:03:45 [Server] INFO [07:03:45 ERROR]: null
02.01 07:03:45 [Server] INFO [07:03:45 INFO]: [uSkyBlock] [uSkyBlock] Creating player island...
In the Console.

**Comment by dutchy1001** [comment]
could you post a full log so we can see what plugins and their versions are loaded plz.

**Comment by ekul361** [comment]
02.01 07:03:45 [Server] INFO ... 14 more
02.01 07:03:45 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-f2cd9c3]
02.01 07:03:45 [Server] INFO at us.talabrek.ultimateskyblock.command.IslandCommand.onCommand(IslandCommand.java:59) ~[?:?]
02.01 07:03:45 [Server] INFO at us.talabrek.ultimateskyblock.command.common.AbstractCommandExecutor.onCommand(AbstractCommandExecutor.java:21) ~[?:?]
02.01 07:03:45 [Server] INFO at us.talabrek.ultimateskyblock.command.common.CompositeUSBCommand.execute(CompositeUSBCommand.java:105) ~[?:?]
02.01 07:03:45 [Server] INFO at us.talabrek.ultimateskyblock.command.island.RequirePlayerCommand.execute(RequirePlayerCommand.java:31) ~[?:?]
02.01 07:03:45 [Server] INFO at us.talabrek.ultimateskyblock.command.island.CreateCommand.doExecute(CreateCommand.java:22) ~[?:?]
02.01 07:03:45 [Server] INFO at us.talabrek.ultimateskyblock.uSkyBlock.createIsland(uSkyBlock.java:1090) ~[?:?]
02.01 07:03:45 [Server] INFO at us.talabrek.ultimateskyblock.uSkyBlock.getLastIsland(uSkyBlock.java:573) ~[?:?]
02.01 07:03:45 [Server] INFO Caused by: java.lang.NullPointerException
02.01 07:03:45 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
02.01 07:03:45 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:528) [spigot.jar:git-Spigot-f2cd9c3]
02.01 07:03:45 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:625) [spigot.jar:git-Spigot-f2cd9c3]
02.01 07:03:45 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-f2cd9c3]
02.01 07:03:45 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:684) [spigot.jar:git-Spigot-f2cd9c3]
02.01 07:03:45 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_65]
02.01 07:03:45 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_65]
02.01 07:03:45 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-f2cd9c3]
02.01 07:03:45 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-f2cd9c3]
02.01 07:03:45 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-f2cd9c3]
02.01 07:03:45 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:940) [spigot.jar:git-Spigot-f2cd9c3]
02.01 07:03:45 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1105) [spigot.jar:git-Spigot-f2cd9c3]
02.01 07:03:45 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:643) ~[spigot.jar:git-Spigot-f2cd9c3]
02.01 07:03:45 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-f2cd9c3]
02.01 07:03:45 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-f2cd9c3]
02.01 07:03:45 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin uSkyBlock v2.0.1-SNAPSHOT-411e57
02.01 07:03:45 [Server] INFO [07:03:45 ERROR]: null
02.01 07:03:45 [Server] INFO [07:03:45 INFO]: [uSkyBlock] [uSkyBlock] Creating player island...

From my first post, I have only changed a few permissions.

**Comment by dutchy1001** [comment]
What I ment was to post (plz use pastebin at http://pastebin.com/) a full log, meaning from server start to end.

**Comment by ekul361** [comment]
oh yes sorry did not read it right at first
http://pastebin.com/qRWGyFxb

**Comment by dutchy1001** [comment]
Your version of WorldGuard(5.9.1) is out of date, use this link 
http://builds.enginehub.org/job/worldguard?branch=versions%2Fspigot1.8-6.x 
I got the 1477 (3 weeks old)but you can try the newer ones too

you got an old version of "multverse" too, go to the link for the latest dev build http://ci.onarandombox.com/job/Multiverse-Core/692/
(this isnt that important but I just mention it)

Update the WG first and see if that fixes the problem

**Comment by ekul361** [comment]
Well first test of this, no error this time only crashes the server when click the /is create. When I do the command also it crashes the server

**Comment by ekul361** [comment]
here is the error I am getting when it crashes.
http://pastebin.com/yG1Zp4PH

**Comment by rlf** [comment]
Do you use the skyworld as the exclusive world?

In that case, try adding the following to your bukkit.yml file:
```
worlds:
  skyworld:
    generator: uSkyBlock
```

**Comment by rlf** [comment]
Some of the logs here indicate, that it's the same issue as reported in #106 - Please try a version of USB that includes that fix - and re-test.

**Comment by ekul361** [comment]
Thank you, fixed now :D, Do you think you can help me with a little something else.
I was wondering with the Schematics to change the Spawn point?

**Comment by rlf** [comment]
The spawn point for schematics is the closest chest found near the bedrock on the island.

So, the bedrock and chest decide.
