### ISSUE TITLE
BUG island create (when trying change schematic)

### ISSUE THREAD

**Issue by SLDDL** [rlf/uSkyBlock#1160]
_Please paste the output from `/usb version` below_
vault 1.5.6-b49 (N/A)

WorldEdit 7.0.0-SNAPSHOT;3944-ee8602b (N/A)

WorldGuard 7.0.0-SNAPSHOT;1756-015f192 (N/A)

FastAsyncWorldEdit 1.0 (N/A)

Multiverse-Core 3.0.0-SNAPSHOT-b758 (N/A)

Multiverse-Portals 3.0.0-SNAPSHOT-b785 (N/A)

Multiverse-NetherPortals 3.0.0-SNAPSHOT-b745 (N/A)
paste it here please (replace this text)
ault 1.5.6-b49 (N/A)

WorldEdit 7.0.0-SNAPSHOT;3944-ee8602b (N/A)

WorldGuard 7.0.0-SNAPSHOT;1756-015f192 (N/A)

FastAsyncWorldEdit 1.0 (N/A)

Multiverse-Core 3.0.0-SNAPSHOT-b758 (N/A)

Multiverse-Portals 3.0.0-SNAPSHOT-b785 (N/A)

Multiverse-NetherPortals 3.0.0-SNAPSHOT-b745 (N/A)

_What steps will reproduce the problem?_
1.idk
2.idk
3.idk

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin
https://pastebin.com/Rw2DJ9Hw
(Not following the template will result in closing the issue.)

**Comment by SLDDL** [comment]
( can you help me plz )

**Comment by Muspah** [comment]
Can you try it using the latest build from this repository: https://oss.pellegrom.pt/snapshots/uSkyBlock/uSkyBlock-20190328-1-ec2a672.jar

That should include changes to fix your WorldEdit vectoring problems. We're unable to push updates to SpigotMC resources unfortunately.

**Comment by Muspah** [comment]
For anyone finding this issue somewhere in the future:

https://www.spigotmc.org/resources/uskyblock-revived.66795/
