### ISSUE TITLE
Fix support for fawe

### ISSUE THREAD

**Issue by CanExiOne** [rlf/uSkyBlock#1169]
I am not using template because it's not needed here. Simply when using uSkyBlock with newest fawe it says that uSkyBlock depends on worldedit 7.0 but there is different version on the server (1.13.95). I can go through by changing fawe version in its plugin.yml but it's not ideal and even after this uSkyBlock don't work.

I have attached logs, it's something about worldedit vectors or schematic. I haven't tried to use plain worldedit and I would prefer to not have to :).

[latest.log](https://github.com/rlf/uSkyBlock/files/3122088/latest.log)

**Comment by Muspah** [comment]
Hi,

There are a few things going on here. FAWE changes the WorldEdit versioning on the included WE package. That makes it harder to detect the WE version your server is running. I'm trying to create a workaround in the way uSkyBlock checks it's requirements to disable checking the WorldEdit version when FAWE is present.

The issues in you're logfile should be fixed simply by using the latest version from https://www.spigotmc.org/resources/uskyblock-revived.66795/.

**Comment by catterz** [comment]
Is there a workaround for this? I have had FAWE installed on my server for a while and trying to install uSkyBlock today, but getting the message "uSkyBlock depends on WorldEdit >= 7.0 but only v1.13.108 was found!"

As with OP, I'd rather not roll back to WE to get things going.

**Comment by CanExiOne** [comment]
There is workaround but I don't know if it breaks something. Open your fawe file with winrar, 7zip or whatever you are using and edit plugin.yml, look for ``"version: "`` and just put 7.0 in there. I may be wrong because I don't remember it perfectly :).

**Comment by Muspah** [comment]
Hi all,

It's not real FAWE support, but it should disable the WorldEdit-check if FAWE is present and allow you to use uSkyBlock with FAWE's built-in WorldEdit.

I've done some testing locally without any problems, but if someone wants to test it on their server, there is a pre-compiled version available for download here: https://oss.pellegrom.pt/snapshots/uSkyBlock/uSkyBlock-20190513-1-aac47c6.jar

Tested with the latest WorldGuard devbuild from BukkitDev: https://dev.bukkit.org/projects/worldguard/files/2663455

Thanks!

**Comment by BlackBeltPanda** [comment]
Tested working for about a month with no issues on my public server. =)

**Comment by Muspah** [comment]
Nice to hear, thanks BlackBelt!

**Comment by Muspah** [comment]
Nice to hear, thanks BlackBelt!
