### ISSUE TITLE
Adding Name, Lore and Enchanments for reward items

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#118]
A possibility to add a name, lore and enchantment to a reward item.
EG. 
```yml
278:1 efficiency:1; durability:1; fortune:1; name:&4Gigadrill; lore:The drill that &npierces the heavens
```
which is a diamond pickaxe with enchantments, name and lore

**Comment by rlf** [comment]
Is the above format compliant with the essentials kit format?

**Comment by dutchy1001** [comment]
I did add the "semicolon" to separate each, but without it it the same as essentials.

**Comment by rlf** [comment]
After some investigation into this, we decided to NOT make this change, since we would essentially re-implement the Essentials Kit concept.

Instead, this can be accomplished by either using Essentials kits (or other plugins that support lore etc.), and adding a command to the reward section.

I.e.
```
reward:
  commands:
    - console:kit {player} awesomenamedkit
```

**Comment by dutchy1001** [comment]
As rlf already explained this can be done through Essentials and ChestCommandGUI.
I will add a section on my pages (soon) "how to".
