### ISSUE TITLE
Exception when completing challenge with offline player

### ISSUE THREAD

**Issue by catterz** [rlf/uSkyBlock#1188]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.7.7-SNAPSHOT
Description: Ultimate SkyBlock v2.7.7-SNAPSHOT-a09f6a5
Language: en (en)
State: d=128, r=64, i=12, p=15, n=true, awe=true
Server: Paper git-Paper-493 (MC: 1.13.2)
State: online=true, bungee=false
------------------------------
Vault 1.7.2-b107 (ENABLED)
WorldEdit 1.13.113 (WRONG-VERSION)
WorldGuard 7.0.0-beta-03;e51a220 (ENABLED)
FastAsyncWorldEdit 1.13-breaking (ENABLED)
Multiverse-Core 3.0.0-SNAPSHOT-b760 (ENABLED)
Multiverse-Portals 3.0.0-SNAPSHOT-b788 (ENABLED)
Multiverse-NetherPortals 3.0.0-SNAPSHOT-b747 (ENABLED)
------------------------------
```

_What steps will reproduce the problem?_
1. Have two players on an island
2. One of the players should be offline
3. Complete the Wool Collector challenge (might work on any challenge, but this is what happened on my server)

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: https://pastebin.com/jyt63cwr

_Description_
When completing a challenge the exception shown in the pastebin was given and the online player was not given any rewards. The challenge was not marked as complete, but the items were taken from the inventory.

The player id shown on Line 32 is an offline player, not the named player that completed the challenge. The bug indicates that uSkyBlock may be trying to access an offline player on the main server thread. The exception is actually thrown by LuckPerms, but they advise to contact the original calling author and inform them that the application is attempting to load an offline player on a synchronous thread which should be avoided.

**Comment by Muspah** [comment]
Thanks for your report! They're right, Bukkit#getOfflinePlayer() is called from the main thread, and that's not ideal indeed. It feels a bit strange to me that Luckperms is not only complaining about it but also cancelling the event tho.

I'll take a further look into it tomorrow morning, it's 1AM over here and I really need some sleep now :)

**Comment by catterz** [comment]
Thanks and don't worry, I know the feeling!

In the meantime I'm attempting to workaround by enabling: `vault-unsafe-lookups: true` in the LuckPerms config.yml (I don't have a player online at the moment to retest this though so can't confirm if it works - the description of the setting implies it should).

[This issue on the LuckPerms Github](https://github.com/lucko/LuckPerms/issues/1150) explains a bit more about the birth of that setting and the reasoning behind it.

**Comment by Muspah** [comment]
I understand why they're advising not to do lookups this way and they have a valid point, but actually throwing an exception made me raise my eyebrow for a second, especially at 1am in the morning, lol. Found out that I'm [not the only one](https://github.com/NLthijs48/AreaShop/issues/441#issuecomment-468966856) 👼 

If uSkyBlock is the only plugin creating this exception on your server, you could temporarily change the suggested LuckPerms setting to get things "working" again, or remove the permission reward from the challenge config to prevent uSkyBlock from making this calls. I will take a look into the actual "bug" and see if there's a quick fix, there's a lot of older code like this in USB that needs refactoring.

**Comment by catterz** [comment]
My player has confirmed that changed the LuckPerms `vault-unsafe-lookups` setting to true has resolved the problem. This is the only use case on my server right now that causes it and there aren't too many challenges that have permission nodes so I'll leave the LuckPerms setting enabled.

I'll keep an eye on here in case you confirm whether it's something that can be resolved quickly.

**Comment by catterz** [comment]
I'm no plugin coding expert, so please forgive if this is a silly suggestion. Could the ChallengeLogic.java file skip giving player permissions if they are offline and then perhaps an EventHandler can listen for the Spigot PlayerJoinEvent and run something similar to the onMemberJoinedEvent (ie. loop through and compare challenges to check if any new permission nodes need to be applied).

**Comment by Muspah** [comment]
Absolutely not a silly suggestion, or at least one of the same things that I was thinking of as workarounds for now 😉. We're doing the same for inventory clears for example.

**Comment by Muspah** [comment]
https://www.spigotmc.org/resources/uskyblock-revived.66795/update?update=279927 :)

**Comment by Muspah** [comment]
It should work with every WorldGuard update that includes the new Vectoring-system from WorldEdit, which is every version that you've used to run uSkyBlock 2.7.7. I'm just linking to the latest sort-of stable build to prevent complaints from people using really old or unstable builds from Enginehub ;)

**Comment by catterz** [comment]
I'm getting a new exception with this update which I wasn't getting before: https://pastebin.com/kuq0g75K

Would you like me to raise it as a separate issue?

**Comment by Muspah** [comment]
Hmm, strange, gimme a sec.

**Comment by catterz** [comment]
Sorry, I could have given a bit of background. I have a script that runs every couple of minutes and executes /usb topten (or /is top - I forget which) so that I can update a leaderboard on my server.

**Comment by Muspah** [comment]
No problem! Should be fixed now: https://www.spigotmc.org/resources/uskyblock-revived.66795/update?update=279965

**Comment by catterz** [comment]
I have updated now and so far so good. Thanks for your support! I will close this issue for now.

**Comment by Muspah** [comment]
Good to hear, thanks for the feedback!
