### ISSUE TITLE
Rightclicking obsidian with an empty bukkit doens't work anymore

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [rlf/uSkyBlock#119]
It says "Turning the obsidian back to lava..." but both the obsidian and the bukkit disappears when rightclicking.

**Comment by woolwind** [comment]
works correctly for me just now, with RC1.38

**Comment by rlf** [comment]
There are some weird client-update issues in the current spigot-build, which is influenced when-ever a plugin alters the world... we think those are the reason for that weird behaviour.

**Comment by rlf** [comment]
Also, if you have water flowing into the obsidian, the behaviour is somewhat erratic.

**Comment by TheOnlyRealTGS** [comment]
Also using v2.0.1-RC1.38

**Comment by TheOnlyRealTGS** [comment]
@rlf Just tried to remove the water, same result

**Comment by TheOnlyRealTGS** [comment]
@rlf If you have time, you can test it on my server right now :)

**Comment by rlf** [comment]
No need @TheOnlyRealTGS we are aware of this "bug" - but not much we can do about it :(

**Comment by TheOnlyRealTGS** [comment]
Okay then.

**Comment by rlf** [comment]
Do you have it regardless of the blocks around the obsidian?
I.e. if you have solid blocks all around (or air), does it still bug?

Because, then I could try to "remove all flowing materials adjacent to the obsidian", before replacing it.

**Comment by TheOnlyRealTGS** [comment]
Just tested, no blocks were touching the obsidian, same result

**Comment by pickledrange** [comment]
just tested this on v2.0.1-RC1.46
right clicking obby with no blocks/water nearby gave me a bucket of lava AND turned the obby into lava on the ground (which started spreading and causing damage)

**Comment by TheOnlyRealTGS** [comment]
Could you send a screenshot of your test setup @pickledrange ?

**Comment by pickledrange** [comment]
what do you mean?

**Comment by TheOnlyRealTGS** [comment]
A screenshot of the obsidian and the blocks around it

**Comment by rlf** [comment]
Just did some testing as well.
It works very rarely - we need to try to improve it at least.

**Comment by dutchy1001** [comment]
agree this is buggy works sometimes but not all the time

**Comment by TheOnlyRealTGS** [comment]
Okay, I'm glad I'm not the only one having issues.

**Comment by rlf** [comment]
Fixed in https://github.com/rlf/uSkyBlock/releases/tag/v2.0.1-RC1.49

**Comment by dutchy1001** [comment]
Every time it makes obsidian I get the lava back, also tested to exploid it when more then 1 obsidian block is near and that doesnt give the lava back then, which is correct.

**Comment by pickledrange** [comment]
Also tested working. closed
