### ISSUE TITLE
Builds of uSkyBlock

### ISSUE THREAD

**Issue by MultiBallMC** [rlf/uSkyBlock#1194]
_Please paste the output from `/usb version` below_
```
uskyblock v2.7.2```

_What steps will reproduce the problem?_
1.Can I descompilate the plugin with eclipse?
2.If the answer is "YES" what libraries do I need to put

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

(Not following the template will result in closing the issue.)

**Comment by BlackBeltPanda** [comment]
Why would you need to decompile the plugin? You posted this on the plugin's open source repository. Just clone it.
The plugin uses Maven, so all dependencies are taken care of as long as you convert it to a Maven project in Eclipse.

**Comment by MultiBallMC** [comment]
I want to chante de /is to /sb. And how do I change eclipse to Maven?

**Comment by BlackBeltPanda** [comment]
If you just want to be able to use "/sb" or "/skyblock" instead of "/is", you can add an alias in the server's "commands.yml" file: https://bukkit.gamepedia.com/Commands.yml

That would probably be much easier for you.

**Comment by MultiBallMC** [comment]
I want to descompile. Say how pls

**Comment by BlackBeltPanda** [comment]
You're literally posting on the repository, containing all of the source code for the plugin. There is no need to decompile it. Just install Maven and clone the repo.

**Comment by Muspah** [comment]
Decompiling the source from the JAR-files uploaded to SpigotMC resources is possible with every Java 8 decompiler. The source isn't obfuscated. But as BlackBelt mentioned, you're posing on the repository containing the code for uSkyBlock. There is no need to decompile if the source is publicly available ;)

**Comment by MultiBallMC** [comment]
Muspah when I put the builds, dependencies and convert to a MAVEN project, said that PACKAGE don't exist, what do I do?

**Comment by Muspah** [comment]
Convert to Maven project? It already is a Maven project ;)

**Comment by MultiBallMC** [comment]
Muspah in eclipse the projest I put into a Maven project and then I put the build.
