### ISSUE TITLE
uSkyBlock wont work, I'm using the required WorldGuard version.

### ISSUE THREAD

**Issue by EnderBro123** [rlf/uSkyBlock#1195]
Whatever ">=" means, I'm using WorldGuard 7.0.0.

![2019-06-16_09 43 16](https://user-images.githubusercontent.com/51277766/59566912-2f160600-901b-11e9-8d03-1b9fbc042338.png)

I wont use the plugin if this doesn't get fixed.

**Comment by Muspah** [comment]
All the required dependencies and versions are mentioned on SpigotMC:

https://www.spigotmc.org/resources/uskyblock-revived.66795/update?update=279927

That should work :)

**Comment by EnderBro123** [comment]
> All the required dependencies and versions are mentioned on SpigotMC:
> 
> https://www.spigotmc.org/resources/uskyblock-revived.66795/update?update=279927
> 
> That should work :)
> 
> ">=" is the "greater than or equal" operator, meaning 7.0.0 or greater.

WorldGuard link is broken.

**Comment by Muspah** [comment]
> WorldGuard link is broken.
Tnx, will change the URL. Looks like the removed the older RC versions while uploading new ones, so the URLs broke.
