### ISSUE TITLE
Unable to find safe-home location on my island.

### ISSUE THREAD

**Issue by FestivalSpanker** [rlf/uSkyBlock#1198]
_Please paste the output from `/usb version` below_
![2019-06-18_14 47 26](https://user-images.githubusercontent.com/51969841/59711030-41896e80-91d8-11e9-8359-32e3c9ff7036.png)

_What steps will reproduce the problem?_
1. install plugin as usual
2. create an island using /island
3. wait for it to finish creating island. 

_If you have any log-files, please paste them to https://pastebin.com/vKx2xhgY
* server-log: link-to-pastebin https://pastebin.com/QJf2Vfqa

I cannot get to my island I only just repeatedly get this error.

**Comment by Muspah** [comment]
Look's like there is something going wrong with WorldEdit, this is not directly related to uSkyBlock as far as I can see now. Could you try to re-install the latest 1.13 WorldEdit version from BukkitDev?
