### ISSUE TITLE
is kick/remove does not remove from party if typed nick all lowercase

### ISSUE THREAD

**Issue by YouHaveTrouble** [rlf/uSkyBlock#1199]
There are no errors in console for this one.

I'm running uSkyBlock 2.7.5 on 1.12.2 with worldedit 6.1.9 and worldguard 6.2.2

Example:

/is remove AllLowerCase - removes player from the group and sends them to spawn
/is remove alllowercase - only sends player to spawn, does not remove player from island group

This is really confusing and may cause problems when player wants to kick someone from their island and it doesn't work

_What steps will reproduce the problem?_
1. Fresh install uSkyBlock
2. Invite someone with Uppercase and lowercase letters in their name
3. Try kicking/removing them from the party by typing their name with all lowercase characters

No log files, since there's literally nothing there.

usb v output

```
>  Name: uSkyBlock
>  Version: 2.7.5
>  Description: Ultimate SkyBlock v2.7.5
>  Language: en (en)
>    State: d=128, r=64, i=3, p=5, n=true, awe=false
>  Server: Paper git-Paper-1615 (MC: 1.12.2)
>    State: online=false, bungee=false
>  ------------------------------
>  Vault 1.5.6-b49 (ENABLED)
>  WorldEdit 6.1.9;caf0ad9 (ENABLED)
>  WorldGuard 6.2.2-SNAPSHOT;8eeab68 (ENABLED)
>  ------------------------------
```

**Comment by Muspah** [comment]
Hi YouHaveTrouble,

The latest builds of uSkyBlock are for 1.13.2 only and can be found on https://www.spigotmc.org/resources/uskyblock-revived.66795/. Older builds are unsupported unfortunately, sorry.
