### ISSUE TITLE
Cant break or place blocks

### ISSUE THREAD

**Issue by DutchCheese** [rlf/uSkyBlock#1205]
_Please paste the output from `/usb version` below_
version 2.8.1
Vault, Worldedit, Worldguard enabled!
_What steps will reproduce the problem?_
1. The right command :)
2.
3.

I cant Place or destroy blocks and cant open chests in a skyblock...
uskyblock should automatically create regions right?

**Comment by Muspah** [comment]
Yes, USB creates WorldGuard regions for every island that is generated. Can you post the output of the server logfile for me please? Are WG regions getting created by USB but without the right flags, or nothing at all?

Your name implies that you're Dutch, if writing in Dutch is easier for you, dan mag dat natuurlijk ook, ik spreek ook Nederlands ;)

**Comment by DutchCheese** [comment]
oh mooi haha, naja, ik heb de plugin verwijderd en weer in de plugin folder gezet, en toen was het gelukt. nu maakt hij steeds een region bij, maar de return to lobby (van de skyblock) doet het niet, weet je waarom? :)


solution (that worked for me):

**-  shut down the server
- remove plugin,
- open server,
- put plugin in the plugin folder
-  / rl**

**Comment by Muspah** [comment]
Please, please, please don't reload the server but restart it. Reloading breaks more than it fixes, not only with USB but also with a lot of other plugins.

Help me even, welke return to lobby bedoel je precies?

**Comment by DutchCheese** [comment]
oh, sorry, wist niet dat reload het meer sloopt, ben nieuw met servers.

maar de knop met  een Grass logo waarmee je naar de soort tutorial gaat over hoe je een eiland moet beginnen.

**Comment by Muspah** [comment]
Geen probleem, was meer in het algemeen mocht er iemand meelezen, het is nogal tricky en heeft een hoop onverwachte bijwerkingen.

Ah, de return to spawn inderdaad. Doet hij in zijn geheel niks of kom je op een onverwachte plek uit?

**Comment by DutchCheese** [comment]
ik kom uit op telkens uit op mijn eiland.

**Comment by Muspah** [comment]
Mogelijk dat er in eerste instantie toch iets niet lekker ging met de WorldGuard koppeling, waardoor er een island is gegenereerd op de locatie waar normaliter de spawn geplaatst wordt. Kom je wel op de X 0, Z 0 coordinaten uit?

**Comment by DutchCheese** [comment]
ik kom niet op die coordinaten, misschien allebei de plugins herinstalleren

en dan gebruik ik nooit meer /rl 😂

**Comment by Muspah** [comment]
Je server is nog leeg verders? Je zou anders ook even de skyworld en skyworld_nether kunnen verwijderen tijdens het herinstalleren, en de mappen "islands" en "players" leeg kunnen gooien in de plugins/uSkyBlock/ map.

**Comment by DutchCheese** [comment]
oke, ik zal kijken, dankjewel!

**Comment by Muspah** [comment]
Ah zo, nee ik bedoelde leeg in de zin van, er hebben nog geen spelers gebouwd o.i.d. Anders is een reset van de eilanden uitvoeren een beetje lullig natuurlijk ;)

**Comment by DutchCheese** [comment]
ooh, nee hoor, alleen ik om te testen
