### ISSUE TITLE
USB config EUX allows inventory placement; does not work

### ISSUE THREAD

**Issue by OpalMoonstride** [rlf/uSkyBlock#1206]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.8.1
Description: Ultimate SkyBlock v2.8.1-0bf4825
Language: en (en)
State: d=128, r=64, i=1, p=1, n=true, awe=false
Server: CraftBukkit git-Spigot-d05d3c1-7ffb2a2 (MC: 1.14.3)
State: online=true, bungee=false
[Server thread/INFO]: ------------------------------
Vault 1.7.2-b107 (ENABLED)
WorldEdit 7.0.0;214af8a (ENABLED)
WorldGuard 7.0.1-beta-01;14e7525 (ENABLED)
Multiverse-Core 4.0.0-b766 (ENABLED)
Multiverse-Portals 4.0.0-b799 (ENABLED)
Multiverse-NetherPortals 4.0.0-b757 (ENABLED)
```

_What steps will reproduce the problem?_
1. Install
2. type /usb config
3. drag items into inventory

https://paste.ubuntu.com/p/PzJzh6xNTW/

![image](https://user-images.githubusercontent.com/39387146/61239146-37da2480-a70c-11e9-9bfe-6cca202b4c7c.png)

**Comment by OpalMoonstride** [comment]
Have I forgotten to install a dependency for the plugin? I have a freshly installed server, and would like to use uSkyBlock, but if the uis don't work I am concerned about what else may be broken.

**Comment by Muspah** [comment]
Hi,

Sorry for letting you wait, the uSkyBlock team is really limited in size at the moment and we have to do the work in our spare time. I'm not sure about the config menu, I would recommend editing the config yml files directly for now, that should work to get you up and running.
