### ISSUE TITLE
/is home doesn't like carpet

### ISSUE THREAD

**Issue by woolwind** [rlf/uSkyBlock#122]
if my home is in my house on the wood floor, all is fine, but if I set the home on the carpeted area, /is home puts me on top of the roof.

**Comment by rlf** [comment]
Haha, nice.
So, it should accept torches etc. as "empty" - currently it requires 2 blocks of air.

Will try to fix. Low prio.

**Comment by rlf** [comment]
Fixed in https://github.com/rlf/uSkyBlock/releases/tag/v2.0.1-RC1.46

**Comment by pickledrange** [comment]
Tested working ok v2.0.1-RC1.46
