### ISSUE TITLE
inconsistency in challenges.yml

### ISSUE THREAD

**Issue by marcbal** [rlf/uSkyBlock#1221]
In the challenge `monsterfarm`, the reward text says `4 redstone ore, 4 iron ore, beetroot-seeds and 1 flint`, but doesn’t actually include beetroot seed in the reward : 
https://github.com/rlf/uSkyBlock/blob/88a2378c70ac4ab983a2e3b7abc56cdcdd9081ba/uSkyBlock-Core/src/main/resources/challenges.yml#L488

Maybe remove the beetroot from the text or add it in the `items` list

**Comment by Muspah** [comment]
Good point, will include it, thanks!

**Comment by Muspah** [comment]
Given the fact that other challenges are already rewarding beetroot seeds (homeowner and potatofarmer), I've removed the "beetroot-seeds" part from the text.
