### ISSUE TITLE
Plugin Dosen't work correctly

### ISSUE THREAD

**Issue by xbom** [rlf/uSkyBlock#1222]
_Please paste the output from `/usb version` below_
https://pastebin.com/Xv3bdSym

_What steps will reproduce the problem?_
1. Install the plugin
2. start the console and see the console errors
2. do /island and create a island (dosen't work)

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log:  https://pastebin.com/g42Vk7P4

**Comment by Muspah** [comment]
You're running FAWE for 1.13 on a 1.14 server? That's not going to work. All the recommended dependency versions are listed here: https://www.spigotmc.org/resources/uskyblock-revived.66795/update?update=291626

**Comment by xbom** [comment]
thank you, bro  ♥

**Comment by Muspah** [comment]
No problemo, sis ❤️
