### ISSUE TITLE
Hoppers break as soon as they pick up items

### ISSUE THREAD

**Issue by SkyCrafterYT** [rlf/uSkyBlock#1223]
Whenever you connect a hopper to a container of any sort- (Furnace, Chest, Dropper, anything) the hopper will break as soon as it picks up an item. Any hopper connected to a hopper going into a container will also break as soon as it picks up an item. 

_`/usb version` below_
```
Name: uSkyBlock
Version: 2.8.3
Description: Ultimate SkyBlock v2.8.3-685d633
Language: en (en)
State: d=128, r=64, i=1, p=1, n=true, awe=false
Server: CraftBukkit git-Spigot-798ea6a-2012f1e (MC: 1.14.4)
State: online=true, bungee=false
 ------------------------------
 Vault 1.7.2-b107 (ENABLED)
WorldEdit 7.0.1;61bc012 (ENABLED)
WorldGuard 7.0.1-SNAPSHOT;556b638 (ENABLED)
Multiverse-Core 2.5-b719 (ENABLED)
```

_What steps will reproduce the problem?_
When I take uSkyblock out and leave WorldGuard- the problem continues. I, then, delete the WG files and restart. The glitch is gone! I insert uSkyblock and completely delete the files so it can generate new ones- and the glitch persists.

So it seems to happen whenever I have WorldGuard and uSkyblock together; No idea why!

_[latest.log](https://pastebin.com/Y0E9Kmmz)_

(Not following the template will result in closing the issue.)

EDIT:
With fresh new files (regenerating files for ALL my plugins and getting new world files), I created a brand new island and used hoppers connected to a container on my island and they worked fine. I tried it on the spawn island- and the glitch persisted. It appears like WorldGuard is protecting me from the glitch in this case? 

EDIT EDIT:
I can confirm that glitch does not happen in WorldGuard protected areas after resetting the files for uSkyblock and WorldGuard. I did also slightly edit the uSkyblock files to add a new island and enable the default SMP island. 

That did not affect the glitch at all. Not sure if the glitch is caused by uSkyblock or WorldGuard now. This whole thing seemed to start with uSkyblock and/or WorldGuard. I'm going to close this thread now- but if I come up with anything else that suggests uSkyblock is the cause of this glitch and it becomes worse again, I will open another issue thread. 

Until then, I hope I never see any of you on these pages.

**Comment by Muspah** [comment]
The only part where we touch hoppers should be the island limits. Just re-open this issue if you encounter the problem again please :)
