### ISSUE TITLE
Custom island : Could not find a safe chest

### ISSUE THREAD

**Issue by damienbunlet** [rlf/uSkyBlock#1227]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.8.5
Description: Ultimate Skyblock v2.8.5-3cb4083
Language: fr (fr)
  State: d=1 024, r=512, i=1, p=1, n=true, awe=false
Server: CraftBukkit git-Spigot-065a373-763e560 (MC: 1.14.4)
  State: online=true, bungee=false
------------------------------
Vault 1.7.2-b107 (ENABLED)
WorldEdit 7.0.1;61bc012 (ENABLED)
WorldGuard 7.0.1-SNAPSHOT;556b638 (ENABLED)
Multiverse-Core 4.1.0-b775 (ENABLED)
Multiverse-Portals 4.1.0-b805 (ENABLED)
Multiverse-NetherPortals 4.1.0-b763 (ENABLED)
------------------------------
```

_What steps will reproduce the problem?_
1. Create a schematic of a new island contain 1 Bedrock and 1 Chest closest to bedrock, with WorldEdit.
2. Stop the server.
3. Remove "skyworld" and "skyworld_nether" files at the root of the server and "completion","islands" and "players" files in /plugins/uSkyBlock.
4. Follow instruction in the Wiki "Custom Island" to create a new custom island.
5. Restart the server.
6. Connect to server and create an island.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: https://pastebin.com/6QapA3Pq

Today, I will create a custom island for my server, so I decide to follow instructions in the Wiki. After this, I will test if the server create the island. It take few minutes because there are many programs open on my computer and when that was finished I have message telling me could not find a safe chest. I had to put myself in creative in my spawn world and skyblock world to be able to teleport next to my island.

I see that the bedrock is obsolete so that's why it doesn't work ?

I set the height for islands spawn to 63, my chest is at 83 and the block of bedrock is at 78. Is the difference between the spawn height of island and the chest that is taken into account nowadays ?

While waiting for an answer, I wish you a good day.

**Comment by damienbunlet** [comment]
Hey,

I find the issue.
When I saved the schematic of my custom Island, I stayed at the lowest layer and so the distance between the chest and the origin of schematic was greater than 15 blocks. So I try this morning to change the origin of my schematic and now I don't have any problems, I spawn near my chest.

I suggest to modify the wiki to specify that the place you stand at the time of copy your island is the same place where spawn and there must be a chest nearby.

**Comment by Muspah** [comment]
Hi Damien,

Thank you for taking the time to open an issue. Good to hear that you were able to find a work-around. The wiki needs some extra attention indeed. I'm going to add a Task label to this issue as a reminder to dig into the code that locates chests to see if there's a way to make this process easier and more adaptive.

Simon
