### ISSUE TITLE
Add member-protection to island

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#123]
Along with all the other in-built protections, we should have something along the lines of faction-member protection, i.e. making sure members can't hurt each other (regardless of pvp-setting).

**Comment by rlf** [comment]
Fixed in https://github.com/rlf/uSkyBlock/releases/tag/v2.0.1-RC1.49

Members can now not hurt each other (regardless of where they are in the skyworld).

**Comment by dutchy1001** [comment]
I cannot hurt my party members now, normal visitors can be hurt. 
This is fixed and can be closed.
