### ISSUE TITLE
Challenge complete contains challenge id, not name.

### ISSUE THREAD

**Issue by fjeddy** [rlf/uSkyBlock#1237]
```
Name: uSkyBlock
Version: 2.8.5
Description: Ultimate SkyBlock v2.8.5-3cb4083
State: d=128, r=64, i=23, p=24, n=true, awe=false
Language: nb_no (nb_NO)
Server: Paper git-Paper-195 (MC: 1.14.4)
State: online=true, bungee=true
------------------------------
Vault 1.7.2-b107 (ENABLED)
WorldEdit 7.0.1-SNAPSHOT;4563-c8cf0d8 (ENABLED)
Multiverse-Core 4.1.0-b775 (ENABLED)
WorldGuard 7.0.1-SNAPSHOT;1947-aa41378 (ENABLED)
------------------------------
Multiverse-NetherPortals 4.1.0-b763 (ENABLED)
```

_What steps will reproduce the problem?_
1. Complete a challenge.

_What happens?_
When a user complete a challenge, there is two messages. One is sent directly to the player who completed the challenge, and another is sent to everyone on the server.

`You have completed Carrot Farmer.`
`player has completed the carrotfarmer challenge.`

See the difference? For the personal message, the challenge name is used, but for the broadcast message sent to everyone, it uses the "id" of the challenge instead of it's name.

**Side note** How can I disable just one or both of these messages? I kind of want everyone to get the challenge completed message, but I don't see the need to send a separate, almost identical one to the player who performed the challenge.

**Comment by Muspah** [comment]
![image](https://user-images.githubusercontent.com/43544407/129558380-18818b29-04f3-4ada-8982-81c34cc43c49.png)
The broadcast to everyone uses the displayName too, the broadcast to other island members uses the identifier at the moment.
