### ISSUE TITLE
WG Region rename

### ISSUE THREAD

**Issue by pickledrange** [rlf/uSkyBlock#124]
I just noticed after doing /rg list that a handful of my regions have renamed to the coordinates. On testing with version  v2.0.1-RC1.41 i had 1 player that was named [player]island. when the player joined the game, the WG region was renamed to his coordinates. not sure if this is an intentional change (for when multiple players own an island) or an unintentional change somewhere but thought id point it out.

    choppedliversisland:
        min: {x: 948.0, y: 0.0, z: -52.0}
        flags: {pvp: deny, farewell: §d** You are leaving a protected island area. (ChoppedLivers),
            vehicle-destroy: deny, greeting: §d** You are entering a protected island area. (ChoppedLivers),
            entity-item-frame-destroy: deny, entity-painting-destroy: deny}
        max: {x: 1052.0, y: 255.0, z: 52.0}
        priority: 100
        type: cuboid
        owners:
            players: [choppedlivers]
        members: {}

**Comment by pickledrange** [comment]
Just catching up on skype i see its intentional. Closed

**Comment by dutchy1001** [comment]
lol
