### ISSUE TITLE
USB install only 30%

### ISSUE THREAD

**Issue by wotnurwasfrage** [rlf/uSkyBlock#1244]
_Please paste the output from `/usb version` below_
```
Gives no output... Its the latest from 1.13.x spigot site - v2.7.6-RC3 stand in logs
The uSkyBlock-bukkit1.13.jar has 1175504Bytes
```
i use:
spigot 1.13.2
worldedit-bukkit-7.0.0.jar
worldguard-bukkit-7.0.0.jar
Multiverse-Core-2.5.jar
vault latest
_What steps will reproduce the problem?_
1. usb is enabled in /plugins, but no cmd works
2. skyworld dont generate
3. in usb folder be only player and island folder, and the confiq.yml

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

https://pastebin.com/P0X38uGC

(Not following the template will result in closing the issue.)

i use usb 1.8 by many years, but the newer version i dont bring to start :(

**Comment by Muspah** [comment]
You're using an outdated version of uSkyBlock, which isn't compatible with (at least) recent WorldEdit-builds. The latest uSkyBlock build for 1.13.2 is 2.7.9-SNAPSHOT, available for download on SpigotMC.org: https://www.spigotmc.org/resources/uskyblock-revived.66795/history

Newer builds for 1.14.x _should_ work on 1.13.2 Spigot, but it's unsupported.
