### ISSUE TITLE
2.8.7 fails to load translations. 2.8.3 is fine

### ISSUE THREAD

**Issue by i9hdkill** [rlf/uSkyBlock#1246]
log error:
https://pastebin.com/3qSG8Uhx

Broken version: https://github.com/rlf/uSkyBlock/commit/acce636e1fec1a0a298f56ac37a230085ca57be4

I am using a self compiled 2.8.3 version, but don't knwo the commit hash. But that version works

**Comment by Muspah** [comment]
Thanks for the report, I will look into it when possible somewhere in the following days. Quick heads-up, the snapshot versions, especially the current one for MC1.15, are untested and not suitable for production.

**Comment by Muspah** [comment]
Did a quick test on our server running the latest snapshot build switching the language to Deutsch, because you're location in your profile is set to Germany. I'm unable to reproduce the issue this way. What locale did you specify in your config.yml?

**Comment by i9hdkill** [comment]
de. But same results with en

**Comment by Muspah** [comment]
Thanks, please let me know if you find anything. Otherwise, could you give it a try with our builds from Travis: https://www.uskyblock.ovh/downloads/master/uSkyBlock/uSkyBlock-2.8.7-SNAPSHOT.jar

**Comment by i9hdkill** [comment]
Jip, 2.8.7 is fine. Guess my custom build got somehow messed up or didn't built correctly
