### ISSUE TITLE
Introduce party-chat for USB

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#125]
Since we already have methods supporting "notifying the party and logging the action" for an island, it should be quite simple to introduce an island chat-feature for just the island-party.

Not sure we want this, but, we can! :D

**Comment by pickledrange** [comment]
personally i dont have a need for it. i have global and local setup on my server. 200 block radius is local and can only be seen within. i also have mcMMO which has its own party chat. so would need to be careful of overlapping commands and obviously permission nodes to disable it on servers that dont want to use 1 or other

**Comment by rlf** [comment]
I'll close this - you have a point - USB shouldn't ALSO be a chat-client.

**Comment by MaRoTheTroLLeR** [comment]
It should have island chat... i have 100+ players in my skyblock server and they are spamming alot things like give me stone or something. just listen for the chat event and if it starts with @ you know xD
so, it will be @message for party chat.

**Comment by dutchy1001** [comment]
There are a good few plugins that can sort a party chat, some might be outdated but still work fine in MC 1.8
[KataParty](http://dev.bukkit.org/bukkit-plugins/kataparty/)
[ChatParty](http://dev.bukkit.org/bukkit-plugins/chatparty/)
[Parties](https://www.spigotmc.org/resources/parties.3709/)
to just name a few

A recommended plugin to use is [McMMO](http://dev.bukkit.org/bukkit-plugins/mcmmo/), this not only enhances the game play but their party chat is well advanced.

**Comment by MaRoTheTroLLeR** [comment]
I didnt view the plugin but. The players will probably need to create a party with another plugin so, they can chat together without spamming the chat. Also to use 2 plugins for the same thing is not good at all. I recommend this feature and i will probably code it and pull request it soon if the developer is not going to make it.

**Comment by dutchy1001** [comment]
Just wondering how you see this as "use 2 plugins for the same thing" as I wont see it that way. uSkyblock doesnt have a chat option so 2 plugins that do the same is not the case here. You will need 2 plugins as long it isnt added.

Dont get me wrong, I do like the idea and if you make a pull request for it I would support it, just our devs will have to look at the code and approve it.

As long it doesnt create other bugs I dont think it will be a problem.
