### ISSUE TITLE
Unable to change biomes

### ISSUE THREAD

**Issue by SilkPenny** [rlf/uSkyBlock#1251]
_Please paste the output from `/usb version` below_
```
Name: uSkyblock
Version: 2.8.7
Description: Ultimate Skyblock v2.8.7-73e1fc4
Language: en (en)
Server: Paper git-Paper-62 (MC: 1.15.1)
Vault 1.7.2-b107
WorldEdit 7.1.0-SNAPSHOT;4825-8e55131 (ENABLED)
WorldGuard 7.0.2-SNAPSHOT;bf2593e
Multiverse-Core 4.1.0-b775 (ENABLED)
Multiverse-Portals 4.1.0-b805 (ENABLED)
Multiverse-NetherPortals 4.1.0-b763 (ENABLED)
```

_What steps will reproduce the problem?_
1. Type /island biome (biome)
2. "You do not have permission to change your biome to that type."
3.

Server not yet opened and I am op'ed.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_

https://pastebin.com/1YB4bLZ4

(Not following the template will result in closing the issue.)

**Comment by Muspah** [comment]
Biome permissions aren't given to operators by default, you should be able to change biomes if you give you/your group/your parent group the correct permissions for the biomes.

See
https://github.com/uskyblock/uSkyBlock/blob/master/uSkyBlock-Core/src/main/resources/plugin.yml#L171

**Comment by SilkPenny** [comment]
Thank you for your speedy response!

**Comment by Hydre41** [comment]
Hi, i didn't understand where i can change this ? which file pls ? because we have the same problem.... impossible to change of biome
thanks
