### ISSUE TITLE
People can build on other peoples islands?

### ISSUE THREAD

**Issue by NXxEpicXCreeperxX** [rlf/uSkyBlock#1263]
There was a template to fill out, i cant find it now,
anyway people can build on other peoples islands?
anyway to fix this? recent issue lately

**Comment by Muspah** [comment]
There should be WorldGuard-regions protecting the islands. Please provide us with a server logfile, the output of /usb version, and in this specific case, can you check the output of /rg info on islands?

**Comment by NXxEpicXCreeperxX** [comment]
https://gyazo.com/dccd2c496b343f85acd45a01d4dcb8ff
 
Version:" 1.7.2


Startup log:
https://pastebin.com/uxV3wLvi

**Comment by NXxEpicXCreeperxX** [comment]
Yes, the /rg info shows a region auto made
but for some reason people can place on other peoples islands which is weird

**Comment by NXxEpicXCreeperxX** [comment]
its been off and on, seems to have stopped now but ill u know if happens again

**Comment by Muspah** [comment]
Mhm, might be an issue with WorldGuard. We're still 1.15.2 at the moment tho, running USB on 1.16.1 is unsupported until we're able to release an update.

**Comment by NXxEpicXCreeperxX** [comment]
Okay sorry Thanks for letting me know!
Love your profile pic btw!

**Comment by Muspah** [comment]
Haha no problem, let me know if you find any information about the issue thought, might be a good heads-up for what we can expect in 1.16.1!

**Comment by fjeddy** [comment]
Running on 1.16.1 with WorldGuard, using the latest WG version specific for 1.16.1 tho, not experiencing any issues with build permissions or WorldGuard flags and islands.

**Comment by Muspah** [comment]
A new version build for MC 1.16 has been released in July, it works with the latest WorldEdit and WorldGuard versions from BukkitDev and should handle region permissions correctly. If you're still experiencing issues, please let me know or create a new issue.

https://www.uskyblock.ovh/downloads/release/uSkyBlock/uSkyBlock-2.8.9.jar
