### ISSUE TITLE
yaml error reading an island file

### ISSUE THREAD

**Issue by woolwind** [rlf/uSkyBlock#127]
Getting continual series of these errors in server log:

[00:08:50] [Craft Scheduler Thread - 1147/WARN]: [uSkyBlock] [uSkyBlock] Error reading island t
org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 1, column 19:
    0,-110.yml:  level: 0

full stacktraces here: http://pastebin.com/gAKjNeDV

island file looks exactly like others, not sure what it is barfing on: http://pastebin.com/B8euihFK

**Comment by woolwind** [comment]
sigh, as soon as you post a problem you realize what you were dong wrong. :-p

**Comment by rlf** [comment]
A missing `- ` perhaps? :D
