### ISSUE TITLE
Nether portals not working anymore after updating from paper 1.15.2 to 1.16.3

### ISSUE THREAD

**Issue by marcbal** [rlf/uSkyBlock#1271]
After updating my server to 1.16.3 (and all my plugin to latest version), players on my server reported that the nether is not accessible anymore. The nether world is still loaded and the teraforming is still working too. The problem seems to come from the portals only.
I didn’t change the configuration of the plugins. I already checked the configuration of multiverse, especially about nether portals and stuff. I also tried with the last dev builds of Multiverse-*, but without success.

_Please paste the output from `/usb version` below_
```
16:45:06 Name: uSkyBlock
16:45:06 Version: 2.8.9
16:45:06 Description: Ultimate SkyBlock v2.8.9-a693011
16:45:06 Language: fr (fr)
16:45:06 State: d=200, r=80, i=430, p=503, n=true, awe=false
16:45:06 Server: Paper git-Paper-191 (MC: 1.16.3)
16:45:06 State: online=true, bungee=true
16:45:06 ------------------------------
16:45:06 Vault 1.7.3-b131 (ENABLED)
16:45:06 WorldEdit 7.2.0-SNAPSHOT+5359-ea1a512 (ENABLED)
16:45:06 WorldGuard 7.0.4-SNAPSHOT+2070-8dee2ad (ENABLED)
16:45:06 Multiverse-Core 4.1.0-b775 (ENABLED)
16:45:06 Multiverse-Portals 4.1.0-b805 (ENABLED)
16:45:06 Multiverse-NetherPortals 4.1.0-b763 (ENABLED)
16:45:06 ------------------------------
```

_What steps will reproduce the problem?_
1. Update your server from 1.15.2 to 1.16.3
2. Enter into a nether portal that used to work on 1.15.2
3. Notice that it doesn’t work anymore

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: https://pastebin.com/PXy5uQsV There is not error message, just here to show the startup, maybe there is a plugin known to prevent nether portal usage.

**Comment by Muspah** [comment]
Is allow-nether=false in server.properties ?

https://www.spigotmc.org/threads/uskyblock-revived.369774/page-22#post-3941261

**Comment by marcbal** [comment]
Yes it is on `false`, for the same reason it was for the people on the link you put 

Ok so it works with `true` (so the problem is solved) but sadly the server generated a useless nether world for my spawn world.

Suggestion : put a warning in the console if nether is enabled in plugin config but disabled in server.properties ?

Thanks for your replay anyway :)
