### ISSUE TITLE
bug: commands don't work

### ISSUE THREAD

**Issue by demiena** [rlf/uSkyBlock#1273]
_Please paste the output from `/usb version` below_
```
I can't paste the output because commands do nothing.
```

_What steps will reproduce the problem?_
1.Just type in a command.
2.Notice how it doesn't even display anything? Weird.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: I don't want to do the log right now because I don't know how to check logs.

(Not following the template will result in closing the issue.)

**Comment by demiena** [comment]
fix your mod. I can't even use it.

**Comment by BlackBeltPanda** [comment]
Is there an error in the log when it tries to load the plugin? Can't exactly help if you don't provide any information.

**Comment by demiena** [comment]
let me see

**Comment by demiena** [comment]
oh it says "is it up to date?"

**Comment by BlackBeltPanda** [comment]
Are you using Spigot, Paper, or another server type? Also, which server version are you using?

**Comment by demiena** [comment]
im running spigot, 1.13 release

**Comment by BlackBeltPanda** [comment]
Which version of uSkyBlock are you using?

**Comment by demiena** [comment]
latest version

**Comment by BlackBeltPanda** [comment]
Assuming by latest version you mean 2.8.9, then that's your problem. 2.8.9 is only designed to work on MC 1.16+.

**Comment by demiena** [comment]
im not on revived version btw.

**Comment by BlackBeltPanda** [comment]
Okay, then I'll ask again: What version of uSkyBlock are you using?
