### ISSUE TITLE
I can't create an island

### ISSUE THREAD

**Issue by doggobot-owner** [rlf/uSkyBlock#1274]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.8.8
Description: Ultimate Skyblock v2.8.8-bdd3090
Language: en (en)
  State: d=128, r=64, i=2, p=2, n=true, awe=true
Server: Paper git-Paper-261 (MC: 1.16.4)
  State: online=true, bungee=true
-----------------------------
FastAsyncWorldEdit 1.16-434;49052d7 (WRONG-VERSION)
WorldGuard 7.0.5-SNAPSHOT+2079-664ab18 (ENABLED)
FastAsyncWorldEdit 1.16-434;49052d7 (ENABLED)
-----------------------------
```

_What steps will reproduce the problem?_
1. /is
2. *create an island*
3. "Unable to find a safe home-location on your island!"

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: none

(Not following the template will result in closing the issue.)

Description: I can not create an island, im trying to create it, being teleported to an EMPTY place, or not being teleported at all with error "Unable to find a safe home-location on your island!"

**Comment by doggobot-owner** [comment]
UPD (Log): https://pastebin.com/qVzCdT0i

**Comment by Muspah** [comment]
Seems like there are changes in the FAWE api. The quickest fix for now is to disable FAWE (I would recommend AsyncWorldEdit, but that's a premium plugin on SpigotMC).

**Comment by doggobot-owner** [comment]
nvm i used iridium
