### ISSUE TITLE
Cannot change back to ocean biome

### ISSUE THREAD

**Issue by Matthew021750** [rlf/uSkyBlock#1276]
_Please paste the output from `/usb version` below_
```
paste it here please (2.8.9)
```

_What steps will reproduce the problem?_
1./is b ocean
2. "you do not have permission to change your biome to that type."

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

(Not following the template will result in closing the issue.)

**Comment by Muspah** [comment]
Sounds like the user executing doesn't have the right permission: usb.biome.ocean
