### ISSUE TITLE
Unowned island message WE

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#128]
When a island owner is removed from his/her island but the island is not deleted, the WorldGuard greeting/farewell message isnt updated. 

The player can create a new island and both will have the same greeting/farewell message. Could the old island message be updated to "unowned island"?

**Comment by rlf** [comment]
Yes, but... isn't this a bit weird?

To have "ghost-islands" out there?

I assume this can only happen using `/usb island remove`?

**Comment by dutchy1001** [comment]
indeed, but the admins can do the command and forget they only removed the player.

**Comment by rlf** [comment]
Fixed in RC1.61

**Comment by BlackBeltPanda** [comment]
Working great for me. I get the "abandoned island" notification when I enter an island region that has no owners. =)

**Comment by rlf** [comment]
Noted.

**Comment by BlackBeltPanda** [comment]
Yeah, I would get the region the player is in, check to make sure the region's entry flag starts with "You are entering a protected island region", then delete it like normal. This assumes it's not still stored somewhere, in which case you could look it up; not sure which would be better performance-wise. =)

**Comment by rlf** [comment]
I'd probably lookup the island-yml, and make sure the member list was empty before deleting.

Would make sense.

**Comment by BlackBeltPanda** [comment]
That would probably be the best method. Wasn't sure if the .yml for the island was kept or not. =)

**Comment by rlf** [comment]
Fixed in v2.1.3

**Comment by dutchy1001** [comment]
this is fixed too
