### ISSUE TITLE
Is it possible to configure messages?

### ISSUE THREAD

**Issue by Treppenhaus** [rlf/uSkyBlock#1280]
Probably sorry for asking, but am i dumb or is there no messages file (like messages.yml, messages.lang or something)
I looked into the code and it seems like all messages are hardcoded Strings.

Im a bit confused because i used (the old version of) uSkyblock some time ago but i thought it would be possible to edit the messages in a file.

pls correct me if i'm wrong. If there isnt, i'd like to make one.

**Comment by Treppenhaus** [comment]
i just noticed there is a language option in config.yml

**Comment by Muspah** [comment]
There's a language option in the config.yml indeed, and the strings are managed in PO-files (GNU Gettext): https://github.com/uskyblock/uSkyBlock/tree/master/uSkyBlock-Core/src/main/po

Overriding translations is possible by creating your own PO-file and placing it into plugins/uSkyBlock/i18n/locale.po: https://github.com/uskyblock/uSkyBlock/blob/master/po-utils/src/main/java/dk/lockfuglsang/minecraft/po/I18nUtil.java#L165
