### ISSUE TITLE
Guardians do not spawn in deep ocean biome in place of other water mobs

### ISSUE THREAD

**Issue by waseric** [rlf/uSkyBlock#1282]
_Please paste the output from `/usb version` below_
```

Name: uSkyBlock
Version: 2.9.0
Description: Ultimate SkyBlock v2.9.0-7cf840c
Language: en (en)
State: d=128, r=48, i=447, p=481, n=true, awe=true
Server: Paper git-Paper-119 (MC: 1.17.1)
State: online=true, bungee=true
------------------------------
Vault 1.7.3-b131 (ENABLED)
FastAsyncWorldEdit 1.17-63;ca1744a (WRONG-VERSION)
WorldGuard 7.0.6-beta1+0b66f3e (ENABLED)
FastAsyncWorldEdit 1.17-63;ca1744a (ENABLED)
Multiverse-Core 4.3.0-b846 (ENABLED)
Multiverse-NetherPortals 4.2.1-b786 (ENABLED)

and

Name: uSkyBlock
Version: 2.9.0-SNAPSHOT
Description: Ultimate SkyBlock v2.9.0-SNAPSHOT-a0b10e5
Language: en (en)
State: d=128, r=48, i=459, p=492, n=true, awe=true
Server: Paper git-Paper-780 (MC: 1.16.5)
State: online=true, bungee=true
------------------------------
Vault 1.7.3-b131 (ENABLED)
FastAsyncWorldEdit 1.16-734;78acb85 (WRONG-VERSION)
WorldGuard 7.0.5+3827266 (ENABLED)
FastAsyncWorldEdit 1.16-734;78acb85 (ENABLED)
Multiverse-Core 4.3.0-b846 (ENABLED)
Multiverse-NetherPortals 4.2.1-b786 (ENABLED)

```

_What steps will reproduce the problem?_
1.  Create a large aquarium, full island 96x96 dimensions with any wall, all blocks are water source blocks.
2.  Cover with prismarine roof, set biome to deep_ocean; leave, come back, confirm biome is effective (island wide)
3.  Observe squids, dolphins spawning, never any guardians.

No errors on console.
We have not been able to see the guardian spawn behavior in 1.16 (with any 1.16 compatible version of plugin).
From reading of SpawnEvents.java (and associated helpers), the issue is not immediately obvious.  Instance of WaterMob still seems a valid test compared to 1.12, as does the isPrismarineRoof function.

Setting up a test environment to poke at it more closely is on my to-do list (and has been for months).  Logging issue for visibility.

**Comment by Muspah** [comment]
I've heard this issue multiple times indeed, but I'm unable to reproduce unfortunately. Running on Airplane build #56 for MC1.17.1:

![2021-07-30_13 09 02](https://user-images.githubusercontent.com/43544407/127651139-dc228e7f-d9c1-423d-b108-e298a551eb41.png)

**Comment by waseric** [comment]
I'm sorry I missed that.  I will close here and continue over there.  I can't remember now why I ended up ending on this  repo as "primary."  Good to know it works for you on Airplane.  I'll do some more isolation before I open over there.  Thanks

**Comment by Muspah** [comment]
It's not a problem, no worries. We've done additional testing on other Spigot servers (Spigot/Paper/et cetera) in the past, but I'm unable to reproduce the issue on a basic server. If you have any additional steps to reproduce, please open a new issue and let me know! :)
