### ISSUE TITLE
How to change language

### ISSUE THREAD

**Issue by qyczq** [rlf/uSkyBlock#1296]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.9.0
Description: Ultimate SkyBlock v2.9.0-7cf840c
Language: pl (pl)
State: d=128, r=64, i=2, p=2, n=false, awe=false
Server: Purpur git-Purpur-1423 (MC: 1.17.1)
State: online=false, bungee=false
------------------------------
Vault 1.7.3-b131 (ENABLED)
WorldEdit 7.2.7+9f3e795 (ENABLED)
WorldGuard 7.0.6+1cff55f (ENABLED)
Multiverse-Core 4.3.1-b861 (ENABLED)
------------------------------
```

_What steps will reproduce the problem?_
1. How to change language to language that is not on the list /usb lang
2. I am from Poland and i want to have plugin in polish.
3. Is there any chance that i would translate the plugin for you?

**Comment by oiuv** [comment]
There's a language option in the config.yml indeed, and the strings are managed in PO-files (GNU Gettext): https://github.com/uskyblock/uSkyBlock/tree/master/uSkyBlock-Core/src/main/po

Overriding translations is possible by creating your own PO-file and placing it into plugins/uSkyBlock/i18n/locale.po: https://github.com/uskyblock/uSkyBlock/blob/master/po-utils/src/main/java/dk/lockfuglsang/minecraft/po/I18nUtil.java#L165
