### ISSUE TITLE
Player Islands being overwritten!

### ISSUE THREAD

**Issue by dniym** [rlf/uSkyBlock#130]
I am not sure what is causing this but occasionally a player will create an island and it will overwrite an existing island.    Both players can build on the island.   If either player does /is restart the island is deleted but the player that was added has to /is leave then /is restart to fix it..

This is all I see in the logs:
04.01 10:05:06 [Server] INFO [10:05:06 INFO]: New protected region created for DannyPhanny's Island by chandlerpl

this has happened twice to the same player, and now he is receiving the message: (Cannot send chat message) when he tries to chat...    None of the player chat seems to be showing up in the console either.

**Comment by rlf** [comment]
The chat problem is not likely to be uSB related, but the island sharing most likely is.

Can you please provide both players .yml files, as well as the island in question?

**Comment by dniym** [comment]
the chat problem wasn't uSkyblock at all, player had chat toggled off clientside!

at the time of this report I had already had the player do /is leave /is restart so that he could continue playing, as soon as this happens again I will get the requested files!

**Comment by dutchy1001** [comment]
As we cant get the needed log files I will close this issue. 
If it happens again and you get the needed (log) files you can reopen or open a new issue.
