### ISSUE TITLE
How2UseNether?

### ISSUE THREAD

**Issue by dniym** [rlf/uSkyBlock#131]
Is there any trick to getting the nether to work with skyblock?   I understand it's just a nether world but portaling from a sky island does not seem to work at all.

I can do /world skyworld_nether and appear there
and i can create a nether portal from the spawn world and it will work.   But not from a player island or my own.

**Comment by dutchy1001** [comment]
Click the link to see how to add and use the nether http://debocraft.x10.mx/skyblock/troubleshoot.html#nether
