### ISSUE TITLE
Improve spawn-position for alternative schematics

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#132]
Currently, USB finds the first available spot near the chest nearest the bedrock on the schematic.

It would be (even more) awesome, if it first tried the blocks "in front" of the chest, regardless of island orientation.

**Comment by rlf** [comment]
Fixed in https://github.com/rlf/uSkyBlock/releases/tag/v2.0.1-RC1.54 (the first spot that is tested for spawn, is the one in front of the chest).

**Comment by BlackBeltPanda** [comment]
Worked great for me on multiple island schematics. =)
