### ISSUE TITLE
Can't remove members

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [rlf/uSkyBlock#134]
Everybody is set to being the owner of the islands now.
This needs to be fixed asap, also, is there a way to get the old members back?
EDIT: Idea, isn't it always the first player in the "players: []" list who is the creator of the island?

**Comment by TheOnlyRealTGS** [comment]
Also, if you do "/island leave" as the owner of the island you get the message "Stop kicking yourself"

**Comment by rlf** [comment]
a) Can you be more specific - what does "everybody is set to being the owner" mean? How is it manifesting in the usage of the island commands?

b) Ye, the leader can't leave the island, before passing over the leadership (never could, never should).

**Comment by rlf** [comment]
and c) what version of skyblock are you currently using?

**Comment by TheOnlyRealTGS** [comment]
There's no member's in the wg regions
I created a build from the code 2 days ago.

**Comment by rlf** [comment]
Usually, there should be a "latest" release build available under https://github.com/rlf/uSkyBlock/releases.

Please share the island.yml, player.ymls and world-guard region for the island in error.

**Comment by TheOnlyRealTGS** [comment]
I actually checked that page but got a error. It works now though.
I can't seem to find a "island.yml" and "player.yml"
The problematic island is now deleted, but that shouldn't matter because this is the case for all islands.
```
    -2090,-2970island:
        min: {x: -2142.0, y: 0.0, z: -3022.0}
        flags: {pvp: deny, greeting: §d** You are entering a protected island area. (D3m0nicHamst3r),
            farewell: §d** You are leaving a protected island area. (D3m0nicHamst3r),
            entry: allow, entity-item-frame-destroy: deny, entity-painting-destroy: deny}
        max: {x: -2038.0, y: 255.0, z: -2918.0}
        priority: 100
        type: cuboid
        owners:
            players: [d3m0nichamst3r, slenderkitten]
        members: {}
```
Also just realized that it says the owner in the greeting flag.

**Comment by rlf** [comment]
The island-yml files also (usually) contain the owner.
I still haven't figured out what this issue-report is about.

Could you please tell me, what you mean with "everybody is set to being the owner of the islands now".

**Comment by TheOnlyRealTGS** [comment]
As you can see in the WorldGuard file, every player is set to owner.
When one of my players tried to remove his members, it denied him with the reason, that "you can't remove owners" or something. I suspect this could be because everybody is set to being owner of the island in the WG file?

**Comment by rlf** [comment]
No - that is just the way USB uses WG - it set's all members as owners of the WG region, but still control the access to various commands on a member/owner basis.

So, this issue is about "one of your players" trying to "remove members" - how did he try to do that?

**Comment by TheOnlyRealTGS** [comment]
Oh okay.
But it's really simple: a player creates a island and adds a few members. Then he wanted to leave the island so he tried to remove the members, but it told him that he wasn't allowed to do that.

**Comment by rlf** [comment]
So, did he do `/is remove <name>` or `/is kick <name>` or exactly what did he execute?
And what did he get in response?
And is there any log-entries in the server-log?

Because, what you describe, should be supported (in the latest build at least).

**Comment by TheOnlyRealTGS** [comment]
He tried both. 
And he got a message denying him it (can't remember it).
And the only log is this: [14:29:02] [Server thread/INFO]: chrisbuild124 issued server command: /is kick amman_kiani
No errors.

**Comment by dutchy1001** [comment]
Is this issue just on the 1 island (from chrisbuild124) or do other players have the same issue?

**Comment by TheOnlyRealTGS** [comment]
Only one player complained, but I guess it's for everyone. Haven't tested on the new build though.

**Comment by dutchy1001** [comment]
It would be nice to know if it is happening to more then just the 1 island as it could be an isolated insident then.

**Comment by TheOnlyRealTGS** [comment]
I'll try to do some more testing then.

**Comment by TheOnlyRealTGS** [comment]
Okay got a player to create a new island and invite 2 people. When he did _/is kick_ one of the members names, he got this message:
[https://s3.amazonaws.com/f.cl.ly/items/2H2b3H0p3i0O371g3w3s/Image%202015-01-17%20at%209.55.00%20PM.png]
