### ISSUE TITLE
Command and Permission rewards

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#135]
Server version: git-Spigot-081dfa5-ba8f630
uSkyBlock version: 2.0.1-SNAPSHOT-ceade5

Command rewards are run by the player so things that require console commands, like adding the player to a specific group, don't work. Would be awesome to have the option to run the command as console.

Also, trying to add multiple permissions doesn't seem to work.
Using:
"permission: test.1
permission: test.2"
Only rewards the "test.2" permission, but using:

"permission:
- test.1
- test.2"
Rewards the permissions:
"[test.1, " and "test.2]"

**Comment by rlf** [comment]
Just prepend with either `op:` or `console:`.

I.e.
```
  commands:
  - "op: me are the GOD of things"
 - "console: give {party} aweseomestuff 32"
```

Reg. the permission setting, isn't that expected behaviour? I think we don't support multiple permissions currently.

**Comment by rlf** [comment]
If you want to add multiple permissions, separate them with spaces.
```
  permission: "test.1 test.2
```
Would give you what you need.

**Comment by rlf** [comment]
Closing issue

**Comment by BlackBeltPanda** [comment]
Great, thanks =)
Just submitted a PR with a quick edit to the challenges.yml to include the info. =)
