### ISSUE TITLE
Lots of lag with ObsidianToLava option

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#136]
Server version: git-Spigot-081dfa5-ba8f630
uSkyBlock version: 2.0.1-SNAPSHOT-ceade5

Getting a lot of lag from the OnClickOnObsidian Interact event.
![Timings](http://i.gyazo.com/6045e723ef1460767a5de7a2c39613b3.png)

**Comment by rlf** [comment]
Thanks - I will take a look at it.

**Comment by rlf** [comment]
I haven't been able to reproduce even remotely the behaviour you posted above.
Only way I can see that happening, is someone standing and holding down their mousebutton.
Also, this is supported by the 191.1K count, an average of 25.10ms for doing that thing, is expected (it does quite some things).

**Comment by BlackBeltPanda** [comment]
So it would be possible to generate this lag by just holding down the mouse button?

**Comment by rlf** [comment]
Since we test on "block-interact-event", and we do a lot of testing (to make sure it's not a portal being clicked), yes, if you hold it down on an obsidian block.
But note, a bug was fixed earlier, with regard to the obsidial to lava feature - so that might have "fixed" this issue as well.

**Comment by BlackBeltPanda** [comment]
Seems to be a lot better now. =)
