### ISSUE TITLE
/usb command can leave island corrupted (empty member-list)

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#140]
Server version: git-Spigot-081dfa5-ba8f630
uSkyBlock version: 2.0.1-SNAPSHOT-ceade5

Getting a lot of these errors popping up in my logs:
http://pastebin.com/raw.php?i=GQ6aihzj

**Comment by rlf** [comment]
Same root-cause as #141 and #142 - islands with empty member-lists.

**Comment by rlf** [comment]
@BlackBeltPanda has anyone tried to edit the island.yml files manually?

**Comment by BlackBeltPanda** [comment]
The island.yml files haven't been manually edited, no.

**Comment by rlf** [comment]
Ok, that leaves some of the /usb commands corrupting the island-files, or, possibly one of the concurrency-issues. I'll try to make the island-data more robust - but all in all, the root-cause of these messages is a corrupt island.yml file (no islands should have no members) - and if they do, no-one should access that islands menu.

**Comment by rlf** [comment]
Can you provide some information as to how to reproduce this?

I.e. "have a player have an island, use /usb island remove <player>, and then have the player use the is menu".

**Comment by BlackBeltPanda** [comment]
Removing the player from the island reverted their "/is" menu to the "start a new island" menu.
However, they still remain an owner of the region at that island:
![](http://i.gyazo.com/6951414bb0d53b3757589f44af71a3c1.png)

**Comment by rlf** [comment]
That sounds like a bug - and a hint at what might be causing the issue.
I assume you used `/usb island remove blackbeltpanda`?

**Comment by rlf** [comment]
Should be fixed in RC1.61

**Comment by BlackBeltPanda** [comment]
Removing the player seems to work now:

![](http://i.gyazo.com/9737545f2675a0323de8ae3a3721cf35.png)
