### ISSUE TITLE
Could not pass event PlayerQuitEvent to uSkyBlock

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#141]
Server version: git-Spigot-081dfa5-ba8f630
uSkyBlock version: 2.0.1-SNAPSHOT-ceade5

Getting a lot of these errors in my logs:
http://pastebin.com/raw.php?i=VvSFaDp4

**Comment by rlf** [comment]
Duplicate of #140 - closing this for now
