### ISSUE TITLE
Could not pass event InventoryClickEvent to uSkyBlock

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#142]
Server version: git-Spigot-081dfa5-ba8f630
uSkyBlock version: 2.0.1-SNAPSHOT-ceade5

Getting a lot of these errors in my logs:
http://pastebin.com/raw.php?i=jSrAPibX

**Comment by rlf** [comment]
This is caused by the same problem as issue #141.
It seems you have somehow gotten invalid island-configs - perhaps after the failing `/dev register` commands or similar.

**Comment by rlf** [comment]
Handled in #140.
