### ISSUE TITLE
/dev register <player> deleted island

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#143]
Server version: git-Spigot-081dfa5-ba8f630
uSkyBlock version: 2.0.1-SNAPSHOT-ceade5

One of my staff members was attempting to register an island from a banned player to one of the islands' party members.
After issuing the "/dev register <player>" command, the island was deleted. There's no error. Here's the excerpt from the logs:
Zzyzzyzzx issued server command: /dev register CaptainCherone
[uSkyBlock] [uSkyBlock] Cleared island in 7.106 seconds
[uSkyBlock] [uSkyBlock] New protected region created for CaptainCherone's Island by Zzyzzyzzx

My guess is since the player was a member of the island, it tried to delete their pre-existing island, which would have been the same island they were being registered to.

**Comment by rlf** [comment]
Yes, that is the normal behaviour - but it also tests if it's the same Island.

Here is the code extract:
```
 if (pi.getHasIsland()) {
            Location oldLoc = pi.getIslandLocation();
            if (newLoc != null && oldLoc != null
                    && !(newLoc.getBlockX() == oldLoc.getBlockX() && newLoc.getBlockZ() == oldLoc.getBlockZ()))
            {
                uSkyBlock.getInstance().deletePlayerIsland(pi.getPlayerName());
            }
        }
```
So, the only way it could happen, is, if the bedrock isn't at the same location as the island - which it should be.

**Comment by rlf** [comment]
Not sure what we can do about this issue - without some reproducible behaviour.

**Comment by BlackBeltPanda** [comment]
It hasn't happened since; what about adding an additional check to make sure the player isn't an owner of the island's region?

**Comment by rlf** [comment]
Well, region handling and island deletion is done separate places - but I guess that would be a solution.
At least, if the "compare the two locations" doesn't work, we need a better approach regardless.

**Comment by rlf** [comment]
Should be fixed in RC1.61

**Comment by dutchy1001** [comment]
No further info and possible fix in RC1.61

closing for now
