### ISSUE TITLE
Error at island restart

### ISSUE THREAD

**Issue by houtblok** [rlf/uSkyBlock#144]
I am getting an error at /island restart. It says An internal error has uncurred and I am using spigot 1.7 - 1.8

**Comment by rlf** [comment]
Is it anything along these lines?
http://pastebin.com/jPkdDM7y

**Comment by houtblok** [comment]
I have pastebin link here:
http://pastebin.com/u4avi5PJ

**Comment by houtblok** [comment]
Ah it works right now, I was using worldguard 5.9 and that one was not compatible. Can you make it compatible with 5.9 or is that impossible? Because some of my plugins are not working with 6.0

**Comment by rlf** [comment]
Rejected
