### ISSUE TITLE
Broadcast completion still broadcasts when set to false

### ISSUE THREAD

**Issue by houtblok** [rlf/uSkyBlock#145]
I set my broadcastCompletion to false but it still broadcasts in chat. Here is my config:

options:
  general:
    maxPartySize: 4
    worldName: skyworld
    spawnSize: 250
    cooldownInfo: 30
    cooldownRestart: 600
    lastIslandX: -770
    lastIslandZ: 1320
  island:
    schematicName: yourschematicname
    distance: 110
    removeCreaturesByTeleport: true
    height: 120
    chestItems: 79:2 360:1 81:1 327:1 40:1 39:1 361:1 338:1 323:1
    addExtraItems: true
    extraPermissions:
      smallbonus: 4:32 320:5
      mediumbonus: 50:16 327:1
      largebonus: 3:10 12:10
    protectWithWorldGuard: false
    protectionRange: 150
    allowPvP: deny
    allowIslandLock: false
    useOldIslands: false
    useIslandLevel: true
    useTopTen: true
  extras:
    sendToSpawn: false
    obsidianToLava: true
  challenges:
    allowChallenges: true
    broadcastCompletion: false
    broadcastText: '&6'
    ranks: Easy Medium Hard Master
    requirePreviousRank: true
    rankLeeway: 1
    challengeColor: '&e'
    finishedColor: '&2'
    repeatableColor: '&a'
    enableEconomyPlugin: true
    challengeList:
      cobblestonegenerator:
        description: Create a cobblestone generator and mine 64 cobblestone.
        rankLevel: Easy
        type: onPlayer
        requiredItems: 4:64
        takeItems: true
        itemReward: '334:3'
        permissionReward: none
        rewardText: 3 leather
        currencyReward: 10
        xpReward: 30
        repeatable: true
        repeatItemReward: '334:1'
        repeatRewardText: 1 leather
        repeatCurrencyReward: 5
        repeatXpReward: 10
      applecollector:
        description: Collect 2 apples from trees.
        rankLevel: Easy
        type: onPlayer
        requiredItems: '260:2'
        takeItems: true
        itemReward: 6:0:2 6:1:2 6:2:2 6:3:2
        rewardText: 2 of each kind of sapling
        currencyReward: 10
        xpReward: 30
        permissionReward: none
        repeatable: true
        repeatItemReward: 6:0:1 6:1:1 6:2:1 6:3:1
        repeatRewardText: 1 of each kind of sapling
        repeatCurrencyReward: 5
        repeatXpReward: 10
      wheatfarmer:
        description: Create a wheat farm and harvest 64 units of wheat
        rankLevel: Easy
        type: onPlayer
        requiredItems: 296:64
        takeItems: true
        itemReward: '3:5'
        rewardText: 5 dirt
        currencyReward: 10
        xpReward: 30
        permissionReward: none
        repeatable: true
        repeatItemReward: '3:1'
        repeatRewardText: 1 dirt
        repeatCurrencyReward: 5
        repeatXpReward: 10
      cactusfarmer:
        description: Create a cactus farm and harvest 64 cacti
        rankLevel: Easy
        type: onPlayer
        requiredItems: 81:64
        takeItems: true
        itemReward: '12:10'
        rewardText: 10 sand
        currencyReward: 15
        xpReward: 30
        permissionReward: none
        repeatable: true
        repeatItemReward: '12:1'
        repeatRewardText: 1 sand
        repeatCurrencyReward: 1
        repeatXpReward: 10
      sugarfarmer:
        description: Create a sugar cane farm and refine 64 units of sugar
        rankLevel: Easy
        type: onPlayer
        requiredItems: 353:64
        takeItems: true
        itemReward: 3:5 82:15
        rewardText: 5 dirt and 15 clay blocks
        currencyReward: 15
        xpReward: 30
        permissionReward: none
        repeatable: true
        repeatItemReward: '82:2'
        repeatRewardText: 2 clay blocks
        repeatCurrencyReward: 5
        repeatXpReward: 10
      melonfarmer:
        description: Create a melon farm and harvest 128 slices of melon
        rankLevel: Easy
        type: onPlayer
        requiredItems: 360:128
        takeItems: true
        itemReward: '3:5'
        rewardText: 5 dirt
        currencyReward: 15
        xpReward: 30
        permissionReward: none
        repeatable: true
        repeatItemReward: '3:2'
        repeatRewardText: 2 dirt blocks
        repeatCurrencyReward: 5
        repeatXpReward: 10
      pumpkinfarmer:
        description: Create a pumpkin farm and harvest 64 pumpkins
        rankLevel: Easy
        type: onPlayer
        requiredItems: 86:64
        takeItems: true
        itemReward: '3:5'
        rewardText: 5 dirt
        currencyReward: 15
        xpReward: 30
        permissionReward: none
        repeatable: true
        repeatItemReward: '3:2'
        repeatRewardText: 2 dirt blocks
        repeatCurrencyReward: 5
        repeatXpReward: 10
      shroompicker:
        description: Create a mushroom farm and collect 64 red and 64 brown mushrooms
        rankLevel: Easy
        type: onPlayer
        requiredItems: 39:64 40:64
        takeItems: true
        itemReward: '110:1'
        rewardText: 1 mycelium block
        currencyReward: 15
        xpReward: 30
        permissionReward: none
        repeatable: true
        repeatItemReward: '110:1'
        repeatRewardText: 1 mycelium block
        repeatCurrencyReward: 5
        repeatXpReward: 10
      novicebuilder:
        description: Reach island level 20 (/island level).
        rankLevel: Easy
        type: islandLevel
        requiredItems: 20
        takeItems: false
        itemReward: 257:1 3:5
        rewardText: 1 iron pickaxe and 5 dirt
        currencyReward: 50
        xpReward: 50
        permissionReward: none
        repeatable: false
        repeatItemReward: ''
        repeatRewardText: ''
        repeatCurrencyReward: 0
        repeatXpReward: 0
      monsterslayer:
        description: Kill monsters and collect 64 rotten flesh, 32 skeleton bones, 32 string, 32 arrows, 16 gunpowder, 5 spider eyes
        rankLevel: Medium
        type: onPlayer
        requiredItems: 367:64 287:32 289:16 262:32 352:32 375:5
        takeItems: true
        itemReward: 331:16 15:5 318:1
        rewardText: 16 redstone dust, 1 flint, and 5 iron(ore)
        currencyReward: 75
        xpReward: 75
        permissionReward: none
        repeatable: true
        repeatItemReward: 331:2 15:1 318:1
        repeatRewardText: 2 redstone dust, 1 flint, and 1 iron(ore)
        repeatCurrencyReward: 15
        repeatXpReward: 15
      expertfarmer:
        description: 'Harvest 64 units of the following: wheat, sugar, melon, carrots,
          potatoes, pumpkin'
        rankLevel: Medium
        type: onPlayer
        requiredItems: 360:64 353:64 296:64 392:64 391:64 86:64
        takeItems: true
        itemReward: 331:16 351:3:1 383:90:1 383:92:1 383:93:1
        rewardText: 16 redstone dust, 1 cocoa bean, 1 spawn egg(chicken,cow,pig)
        currencyReward: 75
        xpReward: 75
        permissionReward: none
        repeatable: true
        repeatItemReward: 351:3:1 383:90:1 383:92:1 383:93:1
        repeatRewardText: 1 cocoa bean, 1 spawn egg(chicken,cow,pig)
        repeatCurrencyReward: 20
        repeatXpReward: 20
      fisherman:
        description: Make a fishing pond, then catch and cook 10 fish
        rankLevel: Medium
        type: onPlayer
        requiredItems: '350:10'
        takeItems: true
        itemReward: 331:16 15:5 351:5
        rewardText: 16 redstone dust, 5 inksac, 5 iron (ore)
        currencyReward: 75
        xpReward: 75
        permissionReward: none
        repeatable: true
        repeatItemReward: 331:2 15:1 351:1
        repeatRewardText: 2 redstone dust, 1 inksac, 1 iron (ore)
        repeatCurrencyReward: 15
        repeatXpReward: 15
      lumberjack:
        description: Create a tree farm and collect 16 oak, birch, jungle, and spruce logs
        rankLevel: Medium
        type: onPlayer
        requiredItems: 17:0:16 17:1:16 17:2:16 17:3:16
        takeItems: true
        itemReward: 331:16 15:5 383:98:1
        rewardText: 16 redstone dust, 5 iron (ore), 1 wolf spawn egg
        currencyReward: 75
        xpReward: 75
        permissionReward: none
        repeatable: true
        repeatItemReward: 331:2 15:1
        repeatRewardText: 2 redstone dust, 1 iron (ore)
        repeatCurrencyReward: 15
        repeatXpReward: 15
      cookielover:
        description: Make 128 cookies and a bucket of milk
        rankLevel: Medium
        type: onPlayer
        requiredItems: 335:1 357:128
        takeItems: true
        itemReward: 331:16 15:5
        rewardText: 16 redstone dust, 5 iron (ore)
        currencyReward: 75
        xpReward: 75
        permissionReward: none
        repeatable: true
        repeatItemReward: 331:2 15:1
        repeatRewardText: 2 redstone dust, 1 iron (ore)
        repeatCurrencyReward: 15
        repeatXpReward: 15
      adeptbuilder:
        description: Reach island level 100 (/island level).
        rankLevel: Medium
        type: islandLevel
        requiredItems: 100
        takeItems: false
        itemReward: '49:10'
        rewardText: 10 obsidian blocks
        currencyReward: 50
        xpReward: 50
        permissionReward: none
        repeatable: false
        repeatItemReward: ''
        repeatRewardText: ''
        repeatCurrencyReward: 0
        repeatXpReward: 0
      homeowner:
        description: Build a house that contains at least 1 door, bed, bookshelf, crafting table, furnace, window, and torch.
        rankLevel: Medium
        type: onIsland
        requiredItems: 26:1 58:1 20:1 64:1 61:1 47:1 50:1
        takeItems: false
        itemReward: 84:1 2267:1 22:10
        rewardText: 1 jukebox, 1 music disk, 10 lapis lazuli blocks
        currencyReward: 100
        xpReward: 100
        permissionReward: none
        repeatable: false
        repeatItemReward: ''
        repeatRewardText: ''
        repeatCurrencyReward: 0
        repeatXpReward: 0
      netherportal:
        description: Build a nether portal on your island and activate it.
        rankLevel: Hard
        type: onIsland
        requiredItems: 49:10 90:1
        takeItems: false
        itemReward: '276:1'
        rewardText: 1 diamond sword
        currencyReward: 100
        xpReward: 100
        permissionReward: none
        repeatable: false
        repeatItemReward: ''
        repeatRewardText: ''
        repeatCurrencyReward: 0
        repeatXpReward: 0
      pearlcollector:
        description: Collect 15 enderpearls from endermen
        rankLevel: Hard
        type: onPlayer
        requiredItems: '368:15'
        takeItems: true
        itemReward: 266:5 369:1
        rewardText: 5 gold ingots and 1 blaze rod
        currencyReward: 50
        xpReward: 100
        permissionReward: none
        repeatable: true
        repeatItemReward: 266:1 369:1
        repeatRewardText: 1 gold ingot and 1 blaze rod
        repeatCurrencyReward: 15
        repeatXpReward: 15
      slimefarmer:
        description: Collect 40 slimeballs from slimes
        rankLevel: Hard
        type: onPlayer
        requiredItems: '341:40'
        takeItems: true
        itemReward: 266:5 388:1
        rewardText: 5 gold ingots and 5 emeralds
        currencyReward: 50
        xpReward: 100
        permissionReward: none
        repeatable: true
        repeatItemReward: '331:8'
        repeatRewardText: 8 redstone dust
        repeatCurrencyReward: 15
        repeatXpReward: 15
      baker:
        description: Bake 5 cakes and 5 pumpkin pies
        rankLevel: Hard
        type: onPlayer
        requiredItems: 354:5 400:5
        takeItems: true
        itemReward: 266:5 264:1
        rewardText: 5 gold ingots and 1 diamond
        currencyReward: 50
        xpReward: 100
        permissionReward: none
        repeatable: true
        repeatItemReward: '15:1'
        repeatRewardText: 1 iron (ore)
        repeatCurrencyReward: 15
        repeatXpReward: 15
      explorer:
        description: Make 1 map, compass, clock and collect 64 netherrack, 16 soulsand, and 1 ghast tear
        rankLevel: Hard
        type: onPlayer
        requiredItems: 87:64 88:16 370:1 358:1 345:1 347:1
        takeItems: true
        itemReward: 27:32 66:256 264:1 383:98:1
        rewardText: 256 rails, 32 powered rails, 1 ocelot spawn egg, 1 diamond
        currencyReward: 100
        xpReward: 100
        permissionReward: none
        repeatable: true
        repeatItemReward: '15:1'
        repeatRewardText: 1 iron (ore)
        repeatCurrencyReward: 20
        repeatXpReward: 20
      expertbuilder:
        description: Reach island level 250 (/island level).
        rankLevel: Hard
        type: islandLevel
        requiredItems: 250
        takeItems: false
        itemReward: 264:1 3:20 12:20
        rewardText: 1 diamond, 20 dirt, and 20 sand
        currencyReward: 150
        xpReward: 150
        permissionReward: none
        repeatable: false
        repeatItemReward: ''
        repeatRewardText: ''
        repeatCurrencyReward: 0
        repeatXpReward: 0
      woolcollector:
        description: Collect 5 of every color of wool
        rankLevel: Master
        type: onPlayer
        requiredItems: 35:0:5 35:1:5 35:2:5 35:3:5 35:4:5 35:5:5 35:6:5 35:7:5 35:8:5 35:9:5 35:10:5 35:11:5 35:12:5 35:13:5 35:14:5 35:15:5
        takeItems: true
        itemReward: 264:2 2262:1 2263:1 2261:1 383:91:1 388:5
        rewardText: 2 diamonds, 5 emeralds, 3 music disks, 1 sheep spawn egg
        currencyReward: 200
        xpReward: 200
        permissionReward: none
        repeatable: true
        repeatItemReward: 388:1 383:91:1
        repeatRewardText: 1 emerald, 1 sheep spawn egg
        repeatCurrencyReward: 20
        repeatXpReward: 20
      maestro:
        description: Craft a jukebox and collect all music discs
        rankLevel: Master
        type: onPlayer
        requiredItems: 2256:1 2257:1 2258:1 2259:1 2260:1 2261:1 2262:1 2263:1 2264:1 2265:1 2266:1 2267:1 84:1
        takeItems: true
        itemReward: 264:3 388:10
        rewardText: 3 diamonds and 10 emeralds
        currencyReward: 200
        xpReward: 200
        permissionReward: none
        repeatable: true
        repeatItemReward: '266:1'
        repeatRewardText: 1 gold ingot
        repeatCurrencyReward: 20
        repeatXpReward: 20
      emeraldcollector:
        description: Collect 50 emeralds
        rankLevel: Master
        type: onPlayer
        requiredItems: '388:50'
        takeItems: true
        itemReward: '264:2'
        rewardText: 2 diamonds
        currencyReward: 200
        xpReward: 200
        permissionReward: none
        repeatable: true
        repeatItemReward: '266:2'
        repeatRewardText: 2 gold ingots
        repeatCurrencyReward: 20
        repeatXpReward: 20
      topchef:
        description: Collect 1 of every kind of cooked or crafted edible food (no raw food, zombie flesh, or super golden apples)
        rankLevel: Master
        type: onPlayer
        requiredItems: 393:1 297:1 354:1 366:1 350:1 320:1 357:1 322:0:1 396:1 282:1 400:1 364:1
        takeItems: true
        itemReward: 264:2 2257:1 2258:1 2260:1 383:96:1 388:5
        rewardText: 2 diamonds, 3 music discs, 1 mooshroom spawn egg, and 5 emeralds
        currencyReward: 200
        xpReward: 200
        permissionReward: none
        repeatable: true
        repeatItemReward: 266:1 383:96:1 388:1
        repeatRewardText: 1 gold ingot, 1 mooshroom spawn egg, 1 emerald
        repeatCurrencyReward: 20
        repeatXpReward: 20
      skylord:
        description: Get an island level of 1000
        rankLevel: Master
        type: islandLevel
        requiredItems: 1000
        takeItems: false
        itemReward: '264:1'
        rewardText: '1 diamond, &eTitle: &a[&2SkyLord&4+&a]&f'
        currencyReward: 250
        xpReward: 250
        permissionReward: titlemanager.title.skylordplus skyblockserver.endaccess
        repeatable: false
        repeatItemReward: ''
        repeatRewardText: ''
        repeatCurrencyReward: 0
        repeatXpReward: 0

**Comment by dutchy1001** [comment]
This is a very old config (v1.0.8 or before), in the new config the Challenges and lastislandX/Z are in a separate .yml file.
Rename this config to let a new one(s) be generated (so you have a backup to add your values back).

As soon you regenerated the new config(s) stop the server again,dont let any player make a new island or restart, as you need to alter some settings. 
Values that need altering are:
1) the spawnSize: 250 default is set to 150 (see below)
2) height is set to 120, default is 150. You need to set this back to 120 or your island have different heights which can cause trouble.
3) protectionRange: 150 default is 105

You need to set your "distance" setting to 250 as your previous "spawnSize" is overruled by Worldguard. 
Your "protectionRange: 150" is set here to 150, this will clash with the defaut "distance: 110" as we now are dependend on "WorldGuard" (but you just set this to 250 so that will be ok then).  You can then set your "protectionRange" to max 250 or a few blocks lower (recommended 245, lower then this is always good). Always make sure that your "protectionRange" is the same or smaller then the "distance" now. This is to avoid overlapping of WG regions. 

The next thing you need to set (if the file doesnt excist yet) is the lastIslandX and lastIslandZ in the lastIslandConfig.yml (see the values on your old config).

All this needs to be set while the server is turned off.

Now you can  open the "challenges.yml" to set the setting to broadcast to false then and other settings you might have set different then the orginal. 
This can be done while the server is online and do a /usb reload command. 

When you have all this done and set, the challange broadcast should be turned off.

This is probably why you had a few errors going on, hope this will help you. let me/us know so we can close this issue.

------ I DO RECOMMEND TO MAKE A FULL SERVER BACKUP FIRST.-------



is here 250, default is 150 (this is absolete as we now have WorldGuard v6 settings).

**Comment by rlf** [comment]
Rejected
