### ISSUE TITLE
1.7.10 Working?

### ISSUE THREAD

**Issue by 0ProGamer0** [rlf/uSkyBlock#146]
So I was just wondering if there is any working 1.7.10 uSkyBlock. I don't want to switch my SkyBlock server fully 1.8. Also by what I mean "working" is that I have tested most of them, only found one but it was one of the more earlier versions. Players were getting randomly kicked from there island and in some other versions challenges and island levels never worked because of some inventory click. 
Thanks.

**Comment by dutchy1001** [comment]
The updates we make are for Craftbukkit/Spigot 1.8. 
The version you need is uSkublock v2.0.0-beta, the orginal from Talabrek. There is a link on my website (through Curse) that will redirect you to that version. http://debocraft.x10.mx/skyblock/#troubleshoot All known bugs and their fix can also be found on that site.
