### ISSUE TITLE
Player island overwritten :\

### ISSUE THREAD

**Issue by dniym** [rlf/uSkyBlock#147]
Player joined and created an island, it took over another players island it seems.   When the schematic was loaded part of a tree remained as well as a wooden platform under the island.

Player who took over island:
http://pastebin.com/tuq3VYmY

Player who previously owned the island:
http://pastebin.com/i9H7Gqpm

Listed as an island member, was not invited by the takover player.
http://pastebin.com/T51RwDvc

Island Yml
http://pastebin.com/fbyWqn8E

**Comment by dutchy1001** [comment]
what versions of uSkyblock, WorldEdit, WorldGuard and Vault do you use? (plz dont answer with "the latest", version numbers plz)

**Comment by dniym** [comment]
Worldguard 6.0.0
uSkyBlock v2.0.1
Vault: Version 1.4.1-b436
WorldEdit v6.0;3342-78f975b9

**Comment by dutchy1001** [comment]
uSkyblock has many versions starting with v2.0.1 whicj one?

**Comment by dniym** [comment]
[uSkyBlock] Loading uSkyBlock v2.0.1-SNAPSHOT-0bb162

**Comment by dutchy1001** [comment]
your uSkyblock is outdated, update to the latest version https://github.com/rlf/uSkyBlock/releases/latest

**Comment by dniym** [comment]
After upgrading to the version you linked me to, as well as the latest one via the spigot page...
I get the following error on startup.
http://pastebin.com/9THaz65x
The GUI does not work typing /is just shows the textual command.

**Comment by dutchy1001** [comment]
You didnt upgrade to the version I linked you to.
All plugins use version numbers, obvious the higher the number the newer the file.

**Comment by dniym** [comment]
Clicking the link you gave me takes me to this page:
http://prntscr.com/5s6lei

I click uSkyBlock.jar  and save the file -> 283kb 
upload it to my server -> http://prntscr.com/5s6mhg  283.48kb

I restart the server and the version reported is:
http://pastebin.com/9CAx3yjc
[uSkyBlock] Loading uSkyBlock v2.0.1-SNAPSHOT-ceade5

Is there somewhere else I should be getting the file besides the large button that says uSkyBlock.jar?

**Comment by rlf** [comment]
Your "challenges.yml" is outdated - move it out of the way, and reload the plugin.
Then manually merge the changes you've made to the "old one".
