### ISSUE TITLE
TopTen Party?

### ISSUE THREAD

**Issue by turnerd10** [rlf/uSkyBlock#149]
With the old uSkyBlock plugin it showed the leader, and then party members in the top ten list. But it only seems to show the island leaders now, can the party members be re-added?

**Comment by rlf** [comment]
Not sure that was the case before - but it sort of make sense (though that list can be quite long).

Any suggestions as to how that should be "formatted"?

**Comment by turnerd10** [comment]
Well, before it had the island owner as it is now, and then after it (Party member 1, Part Member 2, etc)
So for example
# 1: turnerd10 (rif) - Island level 300

**Comment by rlf** [comment]
So, some will take up place for 8 names, and others will just be 1?
I will take a look at it...

**Comment by rlf** [comment]
Fixed in https://github.com/rlf/uSkyBlock/releases/tag/v2.0.1-RC1.58

**Comment by BlackBeltPanda** [comment]
Working =)

![](http://i.gyazo.com/c88ce5ca974aa8bcaa8945ecfb6a71d1.png)

**Comment by woolwind** [comment]
this looks good in chat, but the holo scoreboard display centers each line now instead of left justify, which is hard to read

**Comment by rlf** [comment]
So, create a ticket for the creator of holo-scoreboard, and make him support left-justifying texts...
