### ISSUE TITLE
Failed to Create Island

### ISSUE THREAD

**Issue by NightRiider** [rlf/uSkyBlock#150]
I made a schematic and there is a bedrock block on it and put it in the uskyblock/schematics folder edited the config and put the schematic name set useoldislands false but when I try to create an island I get an error saying Could not pass event InventoryClickEvent to uSkyblock http://puu.sh/ey1rb/a181ef5c22.png
Please help, thanks

**Comment by NightRiider** [comment]
This is the error it leaves http://pastebin.com/nzR2V0wG

**Comment by rlf** [comment]
Please update to a newer version (411 is quite old) - and please include more stack-trace in the log (the ones you include, doesn't help much).

Requirements for the schematic:
a) ONE bedrock block
b) A Chest withing 15 blocks of the bedrock

**Comment by rlf** [comment]
Closing issue - @NightRiider - if you still want it, please reopen
