### ISSUE TITLE
Swampland / Mooshroom Biomes

### ISSUE THREAD

**Issue by dniym** [rlf/uSkyBlock#151]
Setting swampland or mooshroom biomes does not seem to cause the special monsters to spawn, I realize that swampland slimes should only spawn if the moon phase is right but i've tried leaving it set and cant seem to get them to spawn at all.   Is there any specific set of circumstances that must be met for this to work?    Likewise I can never seem to get mooshrooms to spawn or any other natural animal after changing the biome via the plugin.

**Comment by dutchy1001** [comment]
Your right with the spawning of the slimes that you need to wait till the right "moon" phase but you have to make a platform (something like 40x40) between the height level 54-70 (without looking this up for the exact levels). The spawning from other natural animals is default MC and can take a long time.

**Comment by dniym** [comment]
if you dont mind me asking....   I cant seem to find where in the source the correct phase is...   I've built a platform at the height suggested and slimes spawned ONCE...   but after months of checking (minecraft time) i cant seem to get them to spawn again..  I dont see anywhere that it actually causes a slime to spawn.

**Comment by dutchy1001** [comment]
Spawning is Minecraft default, we havent set anything to do that different.

**Comment by rlf** [comment]
The location, space and lightning is key to getting Slimes to spawn.
I am one of the purists  - so I don't use Biomes for "cheating" ;) I simply build "scanning-platforms" on chunk-boundaries at y=39 - to locate a slime-chunk, and then make a slime-farm there :D
