### ISSUE TITLE
Importing from wesley27/uSkyBlock

### ISSUE THREAD

**Issue by spellegrom** [rlf/uSkyBlock#153]
Hi,

Is there an importer available for player files from https://github.com/wesley27/uSkyBlock? The only big difference looks to be the usage of UUIDs in stead of player names in the UUIDPlayerInfo.

Thanks!

**Comment by rlf** [comment]
No, currently there are not.
And, unfortunately, it's not the only difference.

**Comment by spellegrom** [comment]
Thanks for your reply, it was a bit more indeed. I've made some changes myself to get our playerfiles converted, but it's not worth a PR at the moment.
