### ISSUE TITLE
Players can't /is restart

### ISSUE THREAD

**Issue by vladutelu** [rlf/uSkyBlock#154]
Every time I do /is restart,it tells me he was an internal error!Why is that?

**Comment by dutchy1001** [comment]
plz tell us the versions you use of USB and all the dependencies

**Comment by vladutelu** [comment]
I am using the latest version,Vault 1.4.1 and Spigot 1.7/1.8

**Comment by dutchy1001** [comment]
Sorry but those version you gave aren't good enough info. "The "latest" can be anything and is it Spigot 1.7 or Spigot 1.8?
What about WorldEdit and WorldGuard?

**Comment by rlf** [comment]
... and "an internal error" usually means there is also a stack-trace in the server-log, that would be most beneficial

**Comment by rlf** [comment]
Closing since we haven't heard back from @vladutelu
