### ISSUE TITLE
Players don't get items as reward after completing challenges

### ISSUE THREAD

**Issue by Lahemees47** [rlf/uSkyBlock#155]
Players don't get items as rewards for completing challenges, only XP.

Error: http://paste.ubuntu.com/9733097/

**Comment by rlf** [comment]
Sounds like a config issue, please post (pastebin) your challenges.yml, and info on the challenge that is problematic.

**Comment by Lahemees47** [comment]
challenges.yml: http://paste.ubuntu.com/9786087/

I haven't touched that, it shouldn't be the cause of that problem.

**Comment by rlf** [comment]
Do you have econ enabled?

**Comment by rlf** [comment]
The place where the error occurs looks like this:
```
        player.sendMessage("\u00a7eCurrency reward: " + ChatColor.WHITE + this.DECIMAL_FORMAT.format(reward.getCurrencyReward() * rewBonus) + " " + VaultHandler.getEcon().currencyNamePlural() + "\u00a7a (+" + this.DECIMAL_FORMAT.format((rewBonus - 1.0) * 100.0) + "%)");
```
The only way this can give a NPE (from the lines above it), is if getEcon() is null.

**Comment by Lahemees47** [comment]
I don't have any economy plugins installed, if that's what you mean. I changed enableEconomyPlugin to false on challenges.yml, but the problem still remains the same.

**Comment by rlf** [comment]
Should be fixed now, someone please verify on v2.0.1-RC1.65

**Comment by Lahemees47** [comment]
.jar version of v2.0.1-RC1.65 would be preferable, thanks in advance: https://github.com/rlf/uSkyBlock/releases/tag/v2.0.1-RC1.65

**Comment by dutchy1001** [comment]
Working for me when "enableEconomyPlugin: false" is set. I dont get the currency reward but it still does broadcast the message I get currency. The currency "lore" is gone from the chalenges explanation.

**Comment by Lahemees47** [comment]
Confirmed, it's working now. Thank you!
