### ISSUE TITLE
Can't change island biome?

### ISSUE THREAD

**Issue by AppleTechMedia** [rlf/uSkyBlock#156]
When I go into the uSkyBlock GUI, I hover over the icon and it tells me 'You can't change the biome' even though I'm opped. I am using v2.0.1-RC1.54. Thanks!

**Comment by dutchy1001** [comment]
I think there is still some work to be done on the biomes. If you change the biome and go to spawn and back it will be changed. For your players they need either usb.biome."biomeName" or usb.biome.* to make it work.

**Comment by dutchy1001** [comment]
Closing the issue as I just tested this on my own test server and works as explained above.
