### ISSUE TITLE
Trade Message

### ISSUE THREAD

**Issue by xGamingDudex** [rlf/uSkyBlock#157]
Could we add a config option to what message is displayed when a player tries to pick up someone else's items? Currently it says "You can only trade in spawn", but we have disabled the trade in spawn too, so the statement doesn't apply to our server. Something like "Trading is not allowed" would fit better, though it probably depends from server to server, so a config option to change this message would be quite useful.

**Comment by rlf** [comment]
Agreed - I will add this

**Comment by rlf** [comment]
Fixed in v2.0.1-RC1.65

**Comment by dutchy1001** [comment]
loot message adjusted and working
