### ISSUE TITLE
uSkyBlock crashes the server

### ISSUE THREAD

**Issue by vladutelu** [rlf/uSkyBlock#158]
I am using the v2.0.1-RC1.38 version of SkyBlock,Spigot 1.8,Vault 1.5.2,WorldEdit 6.0 and WorldGuard 6.0.0 beta 4.When I join the server,it crashes!I checked,and uSkyBlock is the problem because it works fine without it!Do you have a stable version of it?

**Comment by dutchy1001** [comment]
Update to the latest version RC1.54 
https://github.com/rlf/uSkyBlock/releases/latest

**Comment by rlf** [comment]
Fixed in https://github.com/rlf/uSkyBlock/releases/tag/v2.0.1-RC1.58 (actually already in 1.56)

**Comment by dutchy1001** [comment]
no comment since so I asume fixed

**Comment by dutchy1001** [comment]
no more answer so closing this
