### ISSUE TITLE
commands not working

### ISSUE THREAD

**Issue by woolwind** [rlf/uSkyBlock#161]
loaded RC1.56 and no commands work except /island which brings up the menu.  clicking on the home icon or the level icon does nothing.  typing /is level or /is home brings up the help text and nothing happens

**Comment by rlf** [comment]
No help in console?

**Comment by woolwind** [comment]
nada.

**Comment by rlf** [comment]
Sounds really weird - I'm having no issues along those lines on my server.
Could you please paste-bin your server-log from "startup" till "error".

**Comment by woolwind** [comment]
I tried again and got the same results. logs here http://pastebin.com/UmKAWnxd
I logged in and issued several commands which show in the log, but just get the help text back in-game with no errors to console.  Was there some config format change between RC 38 and now?

**Comment by dutchy1001** [comment]
@woolwind 
Your Vault is way outdated. Your version is vault v1.2.25 from Apr 13, 2013. Update to Vault 1.4.1 or higher. 

Multiverse-portals can be updated to v2.5-b710 but not as important as Vault

**Comment by dutchy1001** [comment]
When going through your config I see 2 sets of "skyworld's" and "skyblock's" worlds, are you trying to run 2 worlds with skyblock plugin?

**Comment by woolwind** [comment]
huh, how did I miss vault. I'll go do that. 
there is one skyworld and one skyblock (and one nether and end)  those messages have been a mystery to me.

**Comment by dutchy1001** [comment]
have you set the "serverproperties" to skyblock?

**Comment by woolwind** [comment]
it was totes Vault, working now   ~blush~

**Comment by woolwind** [comment]
by server.properties - you mean the level name? yes

**Comment by dutchy1001** [comment]
so this issue can be closed?
