### ISSUE TITLE
Island Top Loading?

### ISSUE THREAD

**Issue by Disorbs** [rlf/uSkyBlock#162]
So idk if we need a perm for island members to show up on is top but its not showing others
besides mine and i already did /dev topten to reload the list and still doesn't update others
island level up there so am i missing a perm?

uSkyblock v2.0.1-RC1.56

**Comment by rlf** [comment]
Players don't get listed on the top-ten before they manually do a `/is info` or `/is level`.

**Comment by rlf** [comment]
Additionally, the top-list is only generated once every X minutes (options.island.topTenTimeout), defaut is 7 minutes.
