### ISSUE TITLE
WG __global__ build deny - and /is level <island>

### ISSUE THREAD

**Issue by wesley27** [rlf/uSkyBlock#167]
Not sure if this was taken out in a recode, or somehow bugged, but on my server people were able to build past their island region. No, this didn't count for their island level, and no, they still can't build on other islands. But they shouldn't be able to build outside their island, on the space in between. That's supposed to be free space, or they build bridges with pistons. To fix this I had to set the __global__ region to build deny. This was automatic in the original plugin. 

Also, maybe this is just an issue on my end, but I could not check the island level of other players. I could check my own. When I did /is level <player> it just sent me the message explaining the command usage.

**Comment by rlf** [comment]
We've discussed the __global__ build deny thing, but haven't put it into the code - since we feel that is something the server-owners should decide - but, given all the other stuff we do, we might as well do that also :D

I'll look into the /is level command, you are right, it should definitely allow for checking out others - that is a bug introduced in the command refactoring.

**Comment by dutchy1001** [comment]
The "build: deny" Was 1 of the options I have mentioned very early in the process of adding but as rlf said we desided against it.
As for the level command, I do agree others should be able to do /level [player] but I would like that with a permission, so server owners can decide who can and cant.

**Comment by rlf** [comment]
Ofc. you want that - because having a command, that has one permission for no-arg and an other for 1 arg is "easy" - just to make my life harder ... grr :D I'll look into this eventually.

**Comment by dutchy1001** [comment]
lol

**Comment by dutchy1001** [comment]
if it's easier to have it just as 1 perm adding it to the excisting one then so be it. If server owners asking about it it will be a concideration then.

**Comment by woolwind** [comment]
not asking for it, but I see  permission patterns of  foo.self and foo.other here and there

**Comment by rlf** [comment]
Other places it's just `foo` and `foo.other`...

**Comment by rlf** [comment]
Fixed in v2.0.1-RC1.65

**Comment by dutchy1001** [comment]
"/is level [player]" works without an error No need for separate perms for now untill it's been asked for

Closing now. If more needs to be done with the "Build: deny" region we will hear that then. For now I think server owners can easily set this themself.
