### ISSUE TITLE
"/usb reload" not reloading config (or at least part of it)

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#170]
Spigot version: b1e6da1-17962f6
uSkyBlock version: 2.0.1-RC2

I changed the Obsidian to Lava feature to "true" in my config and ran the command, "/usb reload". I received a notification stating the configuration was reloaded, but the changes didn't take affect; the feature was still disabled.

**Comment by dutchy1001** [comment]
Some reloads do some don't. I've notest this with a few plugins, I think it's more an Craftbukkit/Spigot issue then plugin issue. In case of doubt I always do a server restart (Hopefully I'm wrong and rlf sees from what point it's not reloading).

**Comment by rlf** [comment]
Some of the configs concerning, esp. event-handlers etc. aren't reloaded on /usb reload, only on plugin reload.

**Comment by rlf** [comment]
Should be (might be) fixed in v2.1.0

**Comment by dutchy1001** [comment]
All working for me on last release

**Comment by BlackBeltPanda** [comment]
Half-worked:
Changed "obsidianToLava" to "false" and reloaded. Change applied.
Changed "obsidianToLava" back to "true" and reloaded. Change didn't apply.

**Comment by BlackBeltPanda** [comment]
Working =)
