### ISSUE TITLE
Island deleting and restarts not working

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#171]
Spigot version: b1e6da1-17962f6
uSkyBlock version: 2.0.1-RC2

Tried "/is restart" and "/usb island delete <name>"
"/is restart" teleported the player to spawn but did not delete/recreate the island.
"/usb island delete <name>" did nothing except return the message "Removing <player>'s island"

**Comment by rlf** [comment]
Sounds like a regression  - introduced in 816252c4b5c6adefaa10b612be4d21528f409b3a - I did test it on my setup, but apparently it's not as robust as it should be (perhaps a delay between teleport and USB logic will do the trick).

**Comment by dutchy1001** [comment]
I cant reproduce this

**Comment by BlackBeltPanda** [comment]
Feel free to try out "/is restart" on my server:
play.pandacraft.org

**Comment by dutchy1001** [comment]
I will later today

**Comment by dutchy1001** [comment]
After being on the BlackbeltPanda's server I can confirm his issue. What I dont understand is that it's only on his server (as fas as we know).
After making the command /is restart you are teleported to spawn, then the command seems to be canceled and nothing else happens. Going back to the island with /is h or with the GUI option brings you back on the same island as it was when you did the command /is restart.

My feeling says this is caused by something else then usb, but we do need to find out what then as it's very annoying.

Wild guess, do you have "skript" on your server making commands that when players join "spawn"?

**Comment by BlackBeltPanda** [comment]
I do have Skript, but nothing executing when players use go to spawn.
The issue only started happening when I updated to 2.1.1 from 2.0.1-RC2.

**Comment by dutchy1001** [comment]
and when you put 2.1.1 back the problem is gone?

on your server now

**Comment by rlf** [comment]
I changed the order in which stuff happens, might be the reason.

**Comment by dutchy1001** [comment]
wanna make a "private£ test build reverting that and see?

**Comment by rlf** [comment]
Seems that the changes introduced in 816252c4b5c6adefaa10b612be4d21528f409b3a means, that the player is "tried" teleported home instantly, instead of 10 ticks later.
It most likely is the cause of this, I will re-introduce the "extra-delay".

**Comment by rlf** [comment]
We need to be able to reproduce this, in order for me to fix it with any confidence.
Any suggestions?

**Comment by rlf** [comment]
I still haven't been able to reproduce this, but I haven't forgotten you @BlackBeltPanda

**Comment by rlf** [comment]
Could you re-test with the latest GitHub version?

**Comment by BlackBeltPanda** [comment]
Still not working in 2.1.7.
Nothing happens after the player is teleported to spawn.

**Comment by BlackBeltPanda** [comment]
Still not working in 2.1.9.
Nothing happens after the player is teleported to spawn.

**Comment by rlf** [comment]
And the island is still not reset? if he uses /is h afterwards?
I' trying to figure out, whether it's because the "spawn" takes too long, so it's not in effect before the home-teleport, or if it's simply some commands that are not executed.

What values are you using for distance/protectionRange?

**Comment by dutchy1001** [comment]
Could you check on your server for my WorldGuard region file and post that. If no region file is there that might be the cause of not restarting.

**Comment by rlf** [comment]
I have introduced some additional "error-checking" on deleteIsland in v2.1.10 - please re-test.

**Comment by dylanweb2** [comment]
This does happen on my server too!

**Comment by BlackBeltPanda** [comment]
Still not working in v2.1.10.
distance: 320
protectionRange: 160

**Comment by dutchy1001** [comment]
were at v2.1.17 already

**Comment by dylanweb2** [comment]
Dutchy... I've been using the 1.8 without any flaws...

**Comment by dutchy1001** [comment]
dylan you have the same as BBP then with resetting the islands?

**Comment by dylanweb2** [comment]
Yes... The older build was great. Newest build works fine except for the island resetting.

**Comment by BlackBeltPanda** [comment]
Dutchy, region file looks fine. =)

**Comment by dutchy1001** [comment]
So from what version did this happen? I cant reproduce this on my testserver and therefore very difficult to fix, we do hope it's fixed in v2.1.17

@BlackBeltPanda 
ok, all islands regions are present then?

**Comment by BlackBeltPanda** [comment]
Yes, all regions appear to be present. The bug seems to affect every user. Will update again once I've tested 2.1.17 and the latest version of Spigot.

**Comment by dutchy1001** [comment]
I know were you live no :)  lol


    -340,-110island:
        min: {x: -392.0, y: 0.0, z: -162.0}
        max: {x: -288.0, y: 255.0, z: -58.0}
        members: {}
        flags: {entry: allow, greeting: §d** You are entering §bdutchy1001's §disland.,
            pvp: deny, entity-painting-destroy: deny, entity-item-frame-destroy: deny,
            farewell: §d** You are leaving §bdutchy1001's §disland.}
        owners: {}
        type: cuboid
        priority: 100

This my one, only the order is different, shouldnt make a different (owners and members).

we wait till you update and i'll be back on the server

**Comment by dutchy1001** [comment]
if you test on a TEST SERVER with all the island, you can as test delete all entrees in the WorldGuard/worlds/skyworld/region.yml and then do the command /usb island protectall which add all the regions again, this can cause some lag but only have to do it once. 

Dont forget to backup always

**Comment by BlackBeltPanda** [comment]
No luck with uSkyBlock 2.1.17 on Spigot d0d1d87-15e81cf.
However, when I was teleported to spawn a bedrock block appeared there. O.o
!(http://i.gyazo.com/db4b68fd4b49e95b23d33f98feea4d18.png)

I'll try the test server, Dutchy.

**Comment by rlf** [comment]
LOL - that is the "if spawn-location is empty, place a bedrock" code :)
Seems that somehow it doesn't recognize/load/get the right skyworld as skyworld.
Weird.

**Comment by rlf** [comment]
Ok, @BlackBeltPand here is what I'd like you to do.
Somehow get hold of a v2.1.17 release, then do the following steps (in order).
`/usb debug setlevel FINE`
`/usb debug enable`
`/is restart`
.. do what-ever else is failing atm.
`/usb debug flush`
`/usb debug disable`

Then go to your `/uSkyBlock/logs` folder, and pastebin the log-files located there.

Hopefully it will shed some light on the problem.

**Comment by BlackBeltPanda** [comment]
K, here's the log:
http://pastebin.com/raw.php?i=DtCqn37P

**Comment by rlf** [comment]
Thanks for the logs - there is definitely something wrong there - I will get back to you when I figure out what :D

**Comment by rlf** [comment]
Aaaah, I found the bug. Fix incoming (in a bit)

**Comment by rlf** [comment]
Ok, the bug was, that when the World-Edit regen task didn't have stuff to do, it simply bailed out, and thus didn't execute the "next task in line" - i.e. no homeTeleport or all the other stuff.
Should be fixed in v2.1.18. Please re-test and get back to me.

**Comment by BlackBeltPanda** [comment]
Making progress. Only part of the island was deleted.
Tested with uSkyBlock v2.2 on Spigot d0d1d87-15e81cf.
Before:

![](http://i.gyazo.com/09fc4c56365e23d3a10abdfc08af5ac3.png)

After:

![](http://i.gyazo.com/de1e84275cf4722f6fd8080ccad16f55.png)

Debug log:
http://pastebin.com/raw.php?i=SUzTaE6h

**Comment by rlf** [comment]
Hmm, I really tested that extensively...
Not sure whether that is caused by chunks not being loaded or something... but weird.
Btw. how do you experience the above? Is that "while it is being restarted"? 
Because, then your client will be out of sync (you need to do /spawn and /tp back for your client to update).

**Comment by rlf** [comment]
Took some math-crunching, and in the end it was easy. Should be fixed in v2.2-HF1.

(When using modulo to do math, stuff get's weird for negative values).

**Comment by BlackBeltPanda** [comment]
It seems to be working fine in v2.3 =)
The bedrock also stopped appearing at spawn, lol.

**Comment by dutchy1001** [comment]
Been on your server and lost all my stuf because the restart worked, Woohoo finaly.

Bedrock only appears if there is no spawnbuild.
