### ISSUE TITLE
Non-Hostile Mob No Lava Damage

### ISSUE THREAD

**Issue by rocky143** [rlf/uSkyBlock#172]
I am testing the latest version of uSkyblock and as of now, non-hostile mobs are still not taking any lava damage. I have the pvp option in config set to allow and visitor setting to protect from lava damage to false "fire-damage: false". Here is my test config: http://pastebin.com/v9ueqefn

And here is the image of WorldGuard flags from in game: http://i.imgur.com/MCzrMPS.png

Any help would be appreciated, thank you.

**Comment by rlf** [comment]
Could you please provide information about WG version, WE version and also what the `__global__` region has of flags?

**Comment by rocky143** [comment]
Never mind, I updated WorldGuard, WorldEdit and the issue has been resolved.

**Comment by dutchy1001** [comment]
thx for letting us know you resolved it.

Out of curiosity what WE and WG did you use?

**Comment by rocky143** [comment]
WorldEdit: http://builds.enginehub.org/job/worldedit/6700
WorldGuard: http://builds.enginehub.org/job/worldguard/6699
I have tested this with even having pvp flag to deny pvp and it still worked.

**Comment by dutchy1001** [comment]
lol I ment the old versions before update

**Comment by rocky143** [comment]
Not too sure about exact version number, I deleted the files. But I am sure it was WG 6.0 and WE 6.0

**Comment by dutchy1001** [comment]
well sorted so thx for letting us know.

(last message as this is closed)
