### ISSUE TITLE
Corners Intersect the Spawn Region

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#173]
I have my island size, distances, and spawn size currently set to the defaults.

This has eliminated islands at (0,0), (110,0), (0,110), (-110,0) and (0,110) like it should.

The problem is that islands at the corners are still created: (110,110), (-110,110), (110,-110) and (-110,-110).

When you think about it, the corners of these islands would intersect the corners of the spawn region.

The spawn region would stretch out from (-75,-75) to (75,75) while those islands would definitely be crossing well past, more toward the 60's, leading to an overlap of more than 10x10 on each corner.

**Comment by rlf** [comment]
Depends on your definition of the varios distances :)
110,110 is 155 blocks from the spawn-center.
There is no guarantee of "non-overlapping-regions", and we don't create a "spawn-region" either.
So it's entirely up to the server-owner, to set those values as besat suits his server, and then make sure the spawn-region is correctly "structured", or the spawnSize is adjusted accordingly.

**Comment by rlf** [comment]
But... we could eliminate those islands as well, since what we do currently, is just to check whether the center of the "new island" is within the spawnSize distance of 0,0.

We could change that to checking all 4 corners of the island as well.

**Comment by dutchy1001** [comment]
I think, if it's not to much hassle then, to include the corners with the check so we dont have more confusing server owners. As you said, the corner is 155 away so technically correct. 

Low priority for me.

**Comment by rlf** [comment]
Will do (easily done).

**Comment by TheMattVid** [comment]
I don't use the center of the skyworld for my spawn, but the only reason why I decided to report this is because if someone did want to use the full 150 distance for their spawn, this would be a problem that they might encounter.

**Comment by dutchy1001** [comment]
I understand your point Matt, at first i didnt think it could be an issue but you nailed it there with " if someone did want to use the full 150 distance for their spawn"

**Comment by dutchy1001** [comment]
Fixed

![2015-01-29_14 30 06](https://cloud.githubusercontent.com/assets/5569980/5959146/8992aede-a7c3-11e4-9aaf-853bce769c98.png)

Orange = spawnSize
Red = island size
Green = players building area
Blue = adjusted size to compensate the "distance" between islands and spawn
