### ISSUE TITLE
Add Events for the API

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#174]
Since the top-10 is only periodically updated (when someone invokes the top-ten command), and an island score is only calculated when the owner "checks", there is no need for 3rd party integrators to poll our API all the time (as the current API dictates).

We should introduce some events, that are fired when relevant.

See http://dev.bukkit.org/bukkit-plugins/scoreboardstats/tickets/299-re-introducing-uskyblock-support/#comments

**Comment by rlf** [comment]
For this to truly work, we should introduce an ability to periodically update/re-calculate the score.
And then fire the events accordingly.

**Comment by rlf** [comment]
Fixed in v2.1.3

**Comment by dutchy1001** [comment]
how do I test this?

**Comment by rlf** [comment]
You don't - but I guess the author of Scoreboards did :D
