### ISSUE TITLE
Island Swapping

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#175]
The following is a feature request.

Sometimes players like having their own islands, but would enjoy to have island neighbors who are other active players or who are their friends. The thing is, there is no way to reliably have your island placed next to the island of a friend (unless, perhaps, they create their islands one after another.) For this reason, I think island swapping would be a great feature to have. A player sends an island swap request to another player who he wants to swap island positions with. The other player can then accept or reject that proposal. Once the other player has accepted, all players are teleported to spawn, the islands are swapped, and then I guess the players are automatically teleported back to their new island location. Naturally, the command needs to have a cool-down to prevent servers from lagging, which would be configurable in the uskyblock config file. The thing is, the command shouldn't count as being "used" unless a successful island swap happens. In this case, the cool-down would only occur for players who have just successfully swapped islands.

The only thing that makes this idea slightly questionable is that some servers might not be able to handle island swaps if one of the players has built a monstrous island. For this reason, I guess another setting in the config could be "true/false, if set to true, island swaps will revert islands to the original schematic".

Thoughts?

**Comment by rlf** [comment]
I think this a good suggestion - though not easily done - and the performance penalty on the server will be substantial - so no matter the cooldown, the procedure will most likely make most servers lag.

But, will keep it in mind.

**Comment by dutchy1001** [comment]
you can swap islands with the commands "/usb island remove name" and "/usb island register name" this will not bring the island with them but the most easiest option to get friends next to eachother.

In the short run I dont see a feature of complete island swapping due to the complexity of the code and/or the lag it could cause.

**Comment by rlf** [comment]
Let's close it - no way this will ever be feasible with ther performance currently displayed by WE and copy/replacing.

**Comment by dutchy1001** [comment]
agreed
