### ISSUE TITLE
No Skyworld Spawn Should Allow 0,0 Island

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#176]
The following is a feature request.

I was thinking that perhaps if spawn size in skyworld is set to 0, an island is allowed to spawn at (0,0) coordinate.

Also, this next comment is sort of a feature request and sort of a question: If I decrease the spawn size in the config file, will islands form where they previously weren't allowed? If not, I think they should be able to.

**Comment by rlf** [comment]
It's more of a "possibly bug report" and a "perhaps feature request".

The "algorithm" for selecting a new island location follows this pattern:
```
IF valid-orphan-island EXIST use it
ELSE
  find-next-location based on the lastIsland recorded
```
In other words - no, if you change the spawnSize (in any direction), it will ONLY have an effect if you also reset the `lastIslandConfig.yml` file - but if you do, it should include all valid locations.

Note: If you ever change the `distance`, existing islands most likely will get corrupted.

Reg. the 0,0 coordinate, you are right. It should be a valid spawn-point, if spawnSize is set to 0.

**Comment by rlf** [comment]
Should be fixed in v2.1.6

**Comment by TheMattVid** [comment]
If I decrease my spawn size to zero, calculate where bedrock should mathematically go and assign people to have an island based off of the bedrock, will it function as a regular island? In other words, in this scenario can is be restarted, occupied in a future situation if it is orphaned, etc?

**Comment by rlf** [comment]
Not sure I understand your question.
What are you trying to do?

**Comment by TheMattVid** [comment]
I haven't done anything yet, but I'm saying that I generated the skyworld on my server with the spawn size kept at the default. If I wanted to "undo" this, could I set the spawn size to 0 and manually place bedrock and assign players at the coordinates that they would have appeared if the spawn size was set to 0 from the very beginning?

**Comment by dutchy1001** [comment]
First off, it's not recommended to change the spawnSize after your world has islands in it (I havent tested this yet but i will soon)

If spawnSize is set from the beginning at 0(zero) it would create the first island at the same distance from 0,0 (zero, zero) as the distance is set in the config for (as you probably guess) island-distance.

So the first island location will be 0,100 second at 100,0 third 0,-100 and fourth -100,0 There still wont be an island at 0,0 (I did test that earlier this evening)

**Comment by TheMattVid** [comment]
0 is quite literally nothing. No spawn. Not a single block is dedicated to spawn. I don't see how this would interfere with the islands. If islands are 100 by 100, then the center of the island is 0,0 and the corners are at the fifties. You are correct in saying that the islands with 0 and 100 in their coordinates are 100 from the center, but this still leaves an island-sized hole in the middle of the skyworld that can be filled with an island, both visually and mathematically speaking.

**Comment by TheMattVid** [comment]
I created my own visual representation. Since the default island size is an odd number, the results were island centers that were technically not exactly on a .0 coordinate. http://i.imgur.com/ocyGDlz.png

**Comment by rlf** [comment]
@TheMattVid You are correct - in theory - But all the logic that determines an island-position, is based on the "last-position", and initially, that position is 0,0.

We could change it - but, tbh. I don't think it worth the hazzle.
If I find an easy fix - I will do this, otherwise, it's just a "small feature" allowing server owners to add a minimal spawn later :D

**Comment by dutchy1001** [comment]
We keep this in mind and if there is a day we dont have bugs to fix we will look back into it. 
I dont think this has a high priority and were having other bugs(more important ones) to deal with.
