### ISSUE TITLE
Too much going on in onEnable

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#180]
When enabling the plugin (Since v2.1.5ish), we use too much CPU.
Not sure what is happening - but:
a) It should be investigated
b) We should try to make timings like the below actually help us (get some names instead of $1).

http://timings.aikar.co/?url=9851982
http://timings.aikar.co/?url=9851547

**Comment by Wazez** [comment]
Can also confirm this bug on startup. Server lags way too much.
