### ISSUE TITLE
OutOfBounds on `/usb purge`

### ISSUE THREAD

**Issue by Samistine** [rlf/uSkyBlock#181]
If you do "/usb purge" without specifying  a number it throws an outofbounds error, just check the args length, and tell the player to specify args

**Comment by rlf** [comment]
Fixed in v2.1.8 - as well as some better error-message

**Comment by woolwind** [comment]
still seeing this in 2.2.0

**Comment by rlf** [comment]
Yup, I fixed it, and then re-introduced it... too much going on these days.

**Comment by dutchy1001** [comment]
when doint the command /usb purge without any arguments will just give the help info on screen now. No more console error.

fixed in v2.2-HF2
