### ISSUE TITLE
Increasing max party size has no affect on existing data

### ISSUE THREAD

**Issue by Samistine** [rlf/uSkyBlock#182]

**Comment by rlf** [comment]
Well, the party size is very tricky.
And it always has been.
True, that the "default party size" from the config.yml is only used when a player create an island.
But... on top of that, if one of the members of an island has special permissions, they can increase that islands maxSize (it can never decrease).

Even though the behaviour is weird - I recognize, that at least it could "update" the islands when the default value increase as well.

**Comment by rlf** [comment]
Fixed in v2.1.8 - will take effect on /is h

**Comment by dutchy1001** [comment]
not sure how to test this, but adding players to the member list in the config(manual added and then /usb reload) and then use /is top to see gives all the members from the island. This can be more then the max 8 as the permissions will let you have. However the max group number in the "party gui" stays on 8. 
This probably the wrong way of testing this..... but it didnt give any error in console for having more members

**Comment by rlf** [comment]
Closing for now.
