### ISSUE TITLE
WorldGuard protects all island when create

### ISSUE THREAD

**Issue by luu02** [rlf/uSkyBlock#184]
Whenever one of my players goes on and makes an island, It create another region. How can I prevent this from happening so my players can open their chest and edit their terrain without me having to delete the region

**Comment by rlf** [comment]
You cant.

Seems like you are using the wrong version of WorldGuard - since they should be added to the region, and have permissions.

May I ask what versions you are using?
Spigot, uSkyBlock, WG, WE

**Comment by luu02** [comment]
I'm running Spigot 1.8, WG 6.0 beta (since it said WG 6 was required to run the plugin) WE 6 and uskyblock v2.0.1-RC1.38. I see that there are newer versions of uskyblock. Should I load those?

**Comment by rlf** [comment]
Would be a good idea. Since a lot has changed.

**Comment by rlf** [comment]
Btw. if you in any way mess with the world-guard regions the plugin creates - you will get a hell of a lot of problems - meaning, the plugin won't work, and players will spawn islands in the middle of others islands etc.

**Comment by luu02** [comment]
Ok, would that fix the island not being protected by a region?

**Comment by rlf** [comment]
It most definitely will. If you stop deleting the *protection-regions* created by the plugin, the islands will be protected. Yes.

**Comment by luu02** [comment]
Wait so if i delete the protection region. it will protect it? I dont want it to be protected so that people can break stuff and access their chest

**Comment by dutchy1001** [comment]
If your deleting the WG region flags you basicly break use of the protection of the plugin which can probably cause all different kinds of other bugs. It is not intended to be played the way you explain here. 

To be honest I dont think many players will appreciate that whenever they have build up something, the next time they login all their work is destroyed, I wouldn't and I would think twice to even come back to your server then (but that is my opinion).

**Comment by luu02** [comment]
The problem is that the region wouldnt even let then build or do anything in their island

**Comment by dutchy1001** [comment]
They would if their added to the party system.

**Comment by rlf** [comment]
... and if you are using the right version of WG - earlier versions require the USE flag, the 6.0 version doesn't

**Comment by rlf** [comment]
Closing this, as @luu02 has obviously misunderstood what the plugin does.

**Comment by luu02** [comment]
So I was able to fix it after having to update the plugin. thanks for all the help!

**Comment by dutchy1001** [comment]
yw
