### ISSUE TITLE
Severe concurrency issue with accessing the island files

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#185]
Not sure how this is happening, but it's possible to get corrupt island files somehow.

Seems to be caused by the top-10 generation, combined with other sorts of access to the island-yml file.

Work-around - keep the files loaded.

**Comment by rlf** [comment]
Might have been resolved in v2.1.16 - but more testing is required.

**Comment by rlf** [comment]
I think most of the island and player-data access needs to be made thread-safe.

It doesn't seem to be that yet, and the playerInfo is still stored in the uSkyBlock class (part of #5 )

**Comment by TheMattVid** [comment]
Is topten gone until this is fixed? The island top command seems to be missing from 2.1.17. I updated from 2.0.1 to 2.1.17. In the prior version, there was a list of about 4 islands in the topten. Execution of "/dev topten" following the update results in an error message that the list is empty. Between the update, the only thing I did was delete the config file, clean generate it, and reenter my preferences.

**Comment by rlf** [comment]
The top ten command now correctly "respects" the settings is the config.yml file (it didn't before), if you want it, just enable it.

There has been some concurrency improvements made, so I suggest grabbing v2.1.18 once that is ready for download.

**Comment by rlf** [comment]
Closing this issue - seems to be fixed for now.
