### ISSUE TITLE
Obsidian conversion is error !

### ISSUE THREAD

**Issue by Lucia-** [rlf/uSkyBlock#187]
Obsidian show after 10 seconds to 10 seconds after the conversion, but still can not be converted

this is bug ?

http://i.imgur.com/7guEFey.png

**Comment by rlf** [comment]
No, you get one try every 10 seconds?
Or perhaps I don't understand your question?

**Comment by rlf** [comment]
aah, got it, yes, that is an error.

**Comment by Lucia-** [comment]
sorry my english is bad :(

**Comment by rlf** [comment]
Fixed in v2.1.17 (will be ready in 5-10 minutes).

**Comment by Lucia-** [comment]
thx ~!

**Comment by Lucia-** [comment]
omg this is not fixed .. why?

**Comment by dutchy1001** [comment]
lava to obsidian and back goes fine for me too
