### ISSUE TITLE
Please help with the GUI menu

### ISSUE THREAD

**Issue by wd-craft** [rlf/uSkyBlock#189]
Prompt where it is possible to configure, or rather translate into another language (Russian), all messages in the menu?
I found faёl config, but it can be edited only 2 cell!
Where you can configure the other?
I also would like to know what code should be inserted that would happen as you have in the GUI menu. Number of players 1 of 4.
Still do not work and the level of achievement of the island. ispravte :)

**Comment by rlf** [comment]
Duplicate of #30
