### ISSUE TITLE
/is restart broken?

### ISSUE THREAD

**Issue by dylanweb2** [rlf/uSkyBlock#190]
I run a 1.7.10 server using uSkyblock and when ever I try and restart my island I get an error.

This happened after updating uSkyblock to the latest version.

**Comment by dutchy1001** [comment]
these versions are not for 1.7.xx

**Comment by rlf** [comment]
For 1.7, only use the releases that ends in `-compat`.

**Comment by dylanweb2** [comment]
Actually I am using the latest build on my 1.7.10 server. Everything works except challenges which I don't care about. The island restarting is working as well!

**Comment by dutchy1001** [comment]
Actually at the time you created the issue there was no compatible stable version for 1.7.10 and using "the latest" doesnt say much as the last few days many releases has been brought out. 
Use the new version for 1.7.10 from here http://dev.bukkit.org/bukkit-plugins/uskyblock/. Challenges work for me (and others).

**Comment by dylanweb2** [comment]
The 2.2 release on Spigot. I rather those builds cause it's less buggier and has more features.

**Comment by dutchy1001** [comment]
files are the same on spigot and bukkit only bukkit hosts the 1.7 version aswell
