### ISSUE TITLE
Player not able to edit his own island

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [rlf/uSkyBlock#194]
So a player could not edit his own island. I checked with WG and there were no region there, and he created it when the plugin were using the old SB protection. I got him to do /is restart, and it created a new island, but only replaced the blocks the schematic used, so parts of his old island were still there.

He was not able to edit it still, so I tried doing /usb island delete "player" and got him to restart his island again. A new WG region was created, and he could edit his island.

**Comment by rlf** [comment]
Some of this is fixed in v2.2-HF1, but the root-cause of players dissappearing from their region is freaking weird. I have tried to make the WG-detection-and-update region code more robust.

**Comment by dutchy1001** [comment]
I have not come across the error of not being able to edit (build or break) on an island.

**Comment by TheOnlyRealTGS** [comment]
@dutchy1001 Pretty sure this only occurs on imported islands.

**Comment by dutchy1001** [comment]
That depends on how you import the island. If you import an island to a location on the map has there been an island before or do you just paste it "somewere" in the map?
When an island is present do you make sure the "bedrock" block is in the exact location?
Does an imported island have more then1 bedrock block?
When you import does the size of that island fit into the region that is set in the config?

All these things can trow the plugin-protection into a mess.

**Comment by TheOnlyRealTGS** [comment]
I simply did this when I upgraded months ago: Replaced the jar file

**Comment by dutchy1001** [comment]
so you updated the jar, you didnt import anything as it was already there.

From what version to what version did you update then? Our releases are not "months" old it must be from older versions then.

**Comment by TheOnlyRealTGS** [comment]
I found out the project was alive, and updated from an old beta.

**Comment by dutchy1001** [comment]
I'm sorry but gonna say it blunt

Is it so difficult to type out version numbers, I'm really guessing in the dark to find a solution but heyho we have nothing better to do.

**Comment by rlf** [comment]
Sounds like severely corrupt island data.
Usually, uSB will create a WG region (if none exists) on login (or first invocation of the /is command).

If that didn't happen, odds are, uSB doesn't know about "his island".

We will add some info to the future /usb analyze command, that hopefully will shed some light on these situations.

**Comment by TheOnlyRealTGS** [comment]
>Is it so difficult to type out version numbers, I'm really guessing in the dark to find a solution but heyho we have nothing better to do.

I don't have the version anymore, I remember it was a beta build (2.0 or something) which was the first to introduce the GUI menu.
Then I just downloaded a version from Spigot.

> Usually, uSB will create a WG region (if none exists) on login (or first invocation of the /is command).

But what if the player created an island (when the plugin used the old protection) before WG was required? Because, all the issues I've had so far with this bug, is for islands with no WG region.

>Sounds like severely corrupt island data.
Ideally, I would like to reset because of the "hacky" upgrade from the old plugin, to prevent these bugs, but resets are never popular :(

**Comment by dutchy1001** [comment]
Atleast you gave more info of were we can work with, I understand now that you updated from usb v2.0.0-beta. This was the first gui version after usb v1.0.8. What version have you now?

No matter if the island was created on the default "old" protection, the old protection has been removed off the plugin and replaced by WG. WG was already added to the plugin in v2.0.0-beta by the previous developer and was superior to the "buildin" protection.

How many island do we talk about?
Does every island still has it's bedrock?
Compare to your old config are the default value's the same (EG. spawnSize, distance, height, etc etc)

**Comment by TheOnlyRealTGS** [comment]
@dutchy1001 
>usb v2.0.0-beta. This was the first gui version after usb v1.0.8. 
Yeah, probably one of those. It was made by the original creator AFAIK.
I have https://github.com/rlf/uSkyBlock/releases/tag/v2.2-HF2

**Comment by dutchy1001** [comment]
Sorted some of the stuff and you learned a few tricks, let us know how you get on.

World aint corrupt but messed up with the co-ords due to config value's not corrected at update.

**Comment by TheOnlyRealTGS** [comment]
>World aint corrupt but messed up with the co-ords due to config value's not corrected at update.

About that, afai can see, this has been possible for 3 days, and I have been using the default configs, protection settings since I started.

But only time will tell if there's more islands out there with no WG region.

**Comment by dutchy1001** [comment]
closing this as we know now what is going on.
