### ISSUE TITLE
Error creating island

### ISSUE THREAD

**Issue by Deathinflames** [rlf/uSkyBlock#195]
Hello, first id like to give a big thanks to rlf for maintaining this awesome plugin!

We recently updated from v2.1.9 to v2.2, and now we are receiving the following in the console when new players attempt to create an island: http://pastebin.com/bcvx8KjH

CraftBukkit version git-Spigot-d0d1d87-15e81cf (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT (last updated 1/26/15 9:17PM MST)
WorldEdit v6.0;3342-78f975b9
WorldGuard v6.0.0-beta-05.1569-

**Comment by dutchy1001** [comment]
Which uSkyblock did you use as there are 2 versions, 1 for 1.7.9/10 and 1 for 1.8. there both v2.2.

Check that pls and make sure you have the right version.

**Comment by rlf** [comment]
It's a bug. We'll look into releasing a hot-fix later this evening.

**Comment by rlf** [comment]
Should be fixed in v2.2-HF1

**Comment by Deathinflames** [comment]
Thank you rlf! The people on my server are absolutely ecstatic about this plugin. Brand new people are once again able to create islands. I was scanning the logs this morning and i noticed this, i am not sure if it is related. 

The following error happened when a brand new player joined the server, typed /is, and created an island via the GUI, this is on version v2.2-HF1: http://pastebin.com/LCkLRwy3

**Comment by dutchy1001** [comment]
The error you see in the log is caused when a player clickes on the "head" (join an island) in the begin menu and no invite has been send. This is not related to the issue above (and wont harm). Still it has to be looked into.

**Comment by Deathinflames** [comment]
Thank you for the quick reply dutchy1001! I had a feeling it was harmless, i remember seeing a similar error in v2.0.0.

**Comment by rlf** [comment]
Still an error - created #202 - closing this.
