### ISSUE TITLE
top ten busted

### ISSUE THREAD

**Issue by woolwind** [rlf/uSkyBlock#196]
release 2.2

enabled topten per instructions on spigot page - this is what I get:

>is top
[14:33:44 INFO]: Displaying the top 10 islands:
[14:33:44 INFO]: # 1 (1403.27): null [null, null]
[14:33:44 WARN]: Exception in thread "Craft Scheduler Thread - 30" 
[14:33:44 WARN]: org.apache.commons.lang.UnhandledException: Plugin uSkyBlock v2.2 generated an exception while executing task 87
>       at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
>       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>       at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
>       at us.talabrek.ultimateskyblock.island.IslandLogic.displayTopTen(IslandLogic.java:135)
>       at us.talabrek.ultimateskyblock.island.IslandLogic$1.run(IslandLogic.java:154)
>       at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
>       at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
>       ... 3 more
>

**Comment by dutchy1001** [comment]
do you have a "null" .yml file in the island folder, if so delete that

**Comment by woolwind** [comment]
I did, but I reverted uskyblock so will have to retest when I can swap the new one back in.

**Comment by dutchy1001** [comment]
ok, hotfix on the way for adding the UseTopTen: true back in the config with a few more small internal fixes

**Comment by rlf** [comment]
I've made uSB ignore `null.yml` and `0,0.yml` as island files.

**Comment by dutchy1001** [comment]
this is fixed
