### ISSUE TITLE
Mod bypassprotection

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#197]
The current bypassprotection(usb.mod.bypassprotection)  perm is absolete, we need a new one to bypass the WG locked islands for moderators/admins

**Comment by BlackBeltPanda** [comment]
Should also bypass the inability to use other players' portals. =)

**Comment by rlf** [comment]
Fixed (in v2.3-SNAPSHOT) for portals. Not sure we can fix it for WG entry/deny.

**Comment by rlf** [comment]
Fixed, long time ago. Not possible to fix the WG part. Closing for now.
