### ISSUE TITLE
Ability to create multiple Islands | Request

### ISSUE THREAD

**Issue by trulywitty** [rlf/uSkyBlock#199]
I'm aware you are a busy person. But yet another request.
I believe that being able to create multiple island would be a great feature that no other skyblock plugin has. For example you have island one with a JungleIsland.schematic but you want Island two to have a SwampBiome.schematic and you can make custom ones or have two of the same island or both default. and have perms set for lets say donators to be able to create a extra island or two. Just to keep you're players more active ect. Like a main gui That has a Island 1 Two, three,four in a chest like Icon and when you click on it it takes you to the default gui when you do /is regularly.

Fell free to ask for clarification I myself am not the best at explaining.

**Comment by rlf** [comment]
I get the wish - but the implications are not easily handled.
Every aspect of the plugin would have to change, from challenges, to parties to even the simplest commands.

We currently have support for "different-starting-island-schematic" controlled with permission nodes - so we already have some of it.

What we could do (and am considering), is options for allowing players to not get his "personal" island cleared when accepting an invite - and to track challenge/completion on a per-island basis.

This way, a player can "jump-between" islands, not sharing inventory, and not sharing challenges - so you can go work on a friends island, and then return to your own afterwards. See #104
