### ISSUE TITLE
"/is unlock" not unlocking the island.

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#200]
Version:

![](http://i.gyazo.com/5998142b41274000ffa3168bbe648a4c.png)

When a player attempts to unlock their island, the region flag for entry remains at "DENY".

Before using "/is lock":

![](http://i.gyazo.com/72f9c1bb1a7e337c561ab96dba2728aa.png)

After using "/is lock":

![](http://i.gyazo.com/67bff58e519d7c26229e02aad7044499.png)

After using "/is unlock":

![](http://i.gyazo.com/863ecfe05358610ad1c6b8eb39d34e11.png)

**Comment by rlf** [comment]
Does it say the right things to the player? Does it claim to lock/unlock?

**Comment by dutchy1001** [comment]
I can confirm this issue. It does say the right things as the lock and unlock message
![2015-01-28_20 24 32](https://cloud.githubusercontent.com/assets/5569980/5946185/c2343fe8-a72b-11e4-8213-3a05fde4d106.png)

.

**Comment by rlf** [comment]
Seems that the world-guard region has to be added back.
Should be fixed in the latest snapshot (2f8807b)

**Comment by BlackBeltPanda** [comment]
Still not working in 2f8807b

**Comment by dutchy1001** [comment]
I confirm this too

**Comment by rlf** [comment]
Typo in the code - should be fixed with the above commit. I'll let you know when a release is ready for testing.

**Comment by rlf** [comment]
Should be fixed in the SNAPSHOT version containing a1416f0

**Comment by BlackBeltPanda** [comment]
Working =)

**Comment by dutchy1001** [comment]
yes for me working too
