### ISSUE TITLE
Error when clicking "join an island" for new players.

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#202]
When a "new player" clicks on the "join island" (grass) icon in the GUI the pastebin below happens.

http://pastebin.com/LCkLRwy3

See #195

**Comment by rlf** [comment]
Fixed in latest v2.3-SNAPSHOT (ec97160) - we will refactor the menu-system Soon(tm) - also to enable translations.

**Comment by dutchy1001** [comment]
no more error in console, fixed
