### ISSUE TITLE
/is create cause lag

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#203]
On my server, we get lag when players invoke /is create.
Not sure what part is causing it, but it needs to be addressed.
![mcmyadmin_fallout](https://cloud.githubusercontent.com/assets/503044/5957480/664bd0e4-a7ba-11e4-9914-1153db82aef7.jpg)

**Comment by rlf** [comment]
Related to #114

**Comment by Wazez** [comment]
Can also confrim massive lag and tps drops on the 2 latest skyblock builds when doing /is create and /is restart

**Comment by rlf** [comment]
Related to #180.

Fixed in v2.2-HF2

**Comment by rlf** [comment]
Since I reported it, closing this.
