### ISSUE TITLE
ability to force recalculation for named islands

### ISSUE THREAD

**Issue by Nightwolf3218** [rlf/uSkyBlock#205]
Currently, it seems that the plugin does not support the ability to force an island's level to be recalculated.  With the update to 1.8 and new blocks, we have decided to modify the block values, block limits, and diminishing return scale points on our server to increase the challenge.  However, we have a few islands where the players have not logged onto the server in a while (but we don't want to delete these islands) and it would be nice to have a way to target these islands and force the island level to be calculated based on the new values for purposes of accurately updating /istop.  This would allow updating specific islands that are on /istop with much higher island level values than what they would now have under the new levelConfig.yml values we have implemented.

Maybe a command like /island lcalc <playername> or /island lcalc <regionname>.

**Comment by rlf** [comment]
Fixed in latest v2.3-SNAPSHOT (ec97160) - requires `usb.admin.island` (or OP).

**Comment by dutchy1001** [comment]
Working fine but as #208 when player.yml is present but no island it trows an error out, pastebin on 208

**Comment by rlf** [comment]
Fixing the outstanding error in #208. Closing this.
