### ISSUE TITLE
Animals can still be killed when pushed into lava by visitor

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#206]
When a player "visits" (by warp or tp/tpa) an other players island he can still puch an animal into the lava and get it killed. He still isn't able to pickup the loot.

**Comment by rlf** [comment]
Goes for all the DamageEntityByBlock events.

**Comment by rlf** [comment]
Btw. I think this should be allowed...
Otherwise, players can't make lava-trap-farms.

**Comment by rlf** [comment]
We need to decide, whether this should be allowed or blocked.
If we have to block it, we will effectively disable using lava-blade for mob-farming.

**Comment by TheMattVid** [comment]
I vote allow it.

**Comment by rlf** [comment]
Closing this for now then.
