### ISSUE TITLE
can't clear orphan list

### ISSUE THREAD

**Issue by woolwind** [rlf/uSkyBlock#207]
/dev orphan clear says it's clearing the list, but does nothing.  Nothing in the server log except the note that I ran the command.

**Comment by rlf** [comment]
It's cleared - it's just not saved... sigh

**Comment by rlf** [comment]
Actually . that is intended behaviour - I recognize, it's not expected - but the /usb orphan command has 4 commands, one of which is save. Nothing is saved until that command is invoked.
These issues relate to #95 .

**Comment by woolwind** [comment]
doing /usb orphan list  again shows it is not cleared. so how did you mean intended behavior?

incidentally, editing the file to clear it and doing /usb reload also doesn't help

**Comment by rlf** [comment]
what about doing `/usb orphan clear` followed by `/usb orphan save` ?

**Comment by woolwind** [comment]
that does it, thanks
