### ISSUE TITLE
/is level error

### ISSUE THREAD

**Issue by Wazez** [rlf/uSkyBlock#208]
Error when running /is level: http://paste.md-5.net/raw/novimojuqu

Version 2.2

**Comment by dutchy1001** [comment]
plz follow the guide line with info we need to post an issue on the bukkit page or here in the wiki

**Comment by rlf** [comment]
Fixed in 32f638a (next v2.3-SNAPSHOT)

**Comment by dutchy1001** [comment]
tested and working with v2.2-HF4

**Comment by dutchy1001** [comment]
When there is a player.yml in the folder but not an island it will still trow this error out.
