### ISSUE TITLE
No /is top?

### ISSUE THREAD

**Issue by AppleTechMedia** [rlf/uSkyBlock#209]
Whenever I type in /is top, it just shows me the /is command help. Was this command removed from the plugin, or is this a bug?

**Comment by TheMattVid** [comment]
I'm still running 2.1.17, so I don't know if it's a problem with the old versions, but I have this same problem. When I told rlf about the problem 4 days ago, he said "The top ten command now correctly "respects" the settings is the config.yml file (it didn't before), if you want it, just enable it." but I cannot seem to find the place in the config that enables and disables the top ten's functionality. Rlf, if this is fixed just by updating to the latest version, please let me know.

**Comment by dutchy1001** [comment]
This is fixed

The latest fix (v2.3-HF2) is available here, on BukkitGev and on Spigot.

**Comment by TheMattVid** [comment]
Thanks, dutchy!

**Comment by AppleTechMedia** [comment]
Thanks :)
