### ISSUE TITLE
Option to Make Island Cool Downs Apply to Both /is restart and /is create

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#211]
Although a cool-down prevents island dupes with /is restart, it is still possible for players to get infinite items with the following process:
1. Player A is in a party with Player B.
2. Player A leaves Player B's island.
3. Player A does /is create
4. Player A harvests items.
5. Player A gives items to Player B at spawn.
6. Player A rejoins Player B's island.
7. Repeat steps 2-6 infinitely.

Obviously, I can stop the problem by preventing all kinds of trading on the server, including chestshops, but I don't wish to do so. For this reason, I would like there to at least be an option to have island creation included in the cool-down with island restarting. This means that if one of the two commands is used, the cool-down is activated for both commands simultaneously. This would help to stop a lot of the island duping that players have the potential to use.

**Comment by dutchy1001** [comment]
I see your point here and agree this can be stopped by an /is create cooldown too.

**Comment by rlf** [comment]
Or, just let is create use the is restart cooldown. Accepted.

**Comment by rlf** [comment]
Should be fixed in v2.2-HF4

**Comment by dutchy1001** [comment]
new restart message telling the amount of secounds to wait works. It does need a full sever restart when changing in the config while server runs.
(no biggy for me) 

Fixed
