### ISSUE TITLE
/is top and /usb topten causing error

### ISSUE THREAD

**Issue by rocky143** [rlf/uSkyBlock#214]
Hello, I have recently update to the last version of uSkyBlock v2.2-HF2 and while I did "/is top". Nothing happened for a new seconds and than it causing this error: http://pastebin.com/Pc1QxFeX
Same thing happened with "/usb topten" as well.

**Comment by rlf** [comment]
Please provide the version info from /usb version as well.

**Comment by rlf** [comment]
The error-trace you provided indicates, that you have islands that have no leaders - might be some corrupt islands - but I will accept this bug-report, and make the above error go away (you might still want to look into the leader-less islands).

**Comment by rlf** [comment]
Should be fixed in v2.2-HF4

**Comment by dutchy1001** [comment]
When removing a player with the command "/usb island remove [name] from an island their name is not removed from the island.yml as leader. When  the command /is top or /usb topten is executed it keeps their name in the top ten list. 
When manual remove from the name from the island.yml it keeps value but without a name. 
Removing the name and add { } in it's place it will give me the "code" i presume, see pic

![2015-02-02_20 02 09](https://cloud.githubusercontent.com/assets/5569980/6008294/6ef3a0b2-ab18-11e4-957e-41587c8b9578.png)

**Comment by rlf** [comment]
Hmm, not sure it will "go well", since the code might assume there's always a leader to an island.

Will look into whether we can "null-out" the leader on `/usb island remove`.

**Comment by rlf** [comment]
Just to clarify - the above screen dump is AFTER you manually edited the island.yml file, right?

**Comment by dutchy1001** [comment]
no this was after i used the command "/usb island remove [playername]" and is still in the latest (HF9b) present.

**Comment by rlf** [comment]
Hmm, ok, so `/usb island remove leader` should actually null-out the leader of the island - even though this is sort of an "invalid-state" for the plugin.

I will try to make the change - then we need to test what explodes by it.

**Comment by dutchy1001** [comment]
topten has been worked on with many changes and fixes.

If problem still occurs reopen the issue or create a new one.
