### ISSUE TITLE
calculateScore is sync. (causing some lag when calculating score).

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#215]
The calcuate score (invoked when autoRefreshScore > 0) calculates the island level in a synchroneous way.
It only calculates one island per tick - but still, for some servers, this is causing lag.

We need to further divide the calculation of island score into smaller tasks.

**Comment by Wazez** [comment]
Hey I also have this lag. Which version can I downgrade to temporarily without breaking uSkyBlock?

**Comment by rlf** [comment]
Fixed in v2.2-HF4.
Test:
* Set autoRefreshScore to something low (i.e. 1 or 2)
* Enable timings `/timings on` (Spigot only)
* Play with more than 1 online in skyworld for several minutes, and notice whether any lag occurs.
* Execute `/timings paste`
* Analyze output from uSkyBlock - values in the red (30-40ms) is acceptable, as long as the Pct. is low, values above 100ms will (potentially) introduce server-lag.

**Comment by dutchy1001** [comment]
autoRefreshScore was set to 2.
here is the timings report:
http://timings.aikar.co/?url=10021602

**Comment by rlf** [comment]
Seems to be as good as it gets, currently...
