### ISSUE TITLE
[Error] Could Not Pass Event IbnventoryClickEvent To Uskyblock vv2.2-HF2

### ISSUE THREAD

**Issue by rivalsurvival** [rlf/uSkyBlock#216]
Hi, I've Been Trying To Fix This Error Where When You CLick On The Challenge Item In The GUI Which I Believe It Was Caused By 1.7 Spigot So I Need To Update To 1.8 But Is There A Alternative Way To Fix This? Here Is My Pastebin Log From Server Start To End.
http://pastebin.com/Vs71iXPh

**Comment by rivalsurvival** [comment]
Any Way I Could Fix This Without Updating?

**Comment by dutchy1001** [comment]
You could try and use Vault 1.4.1 as the new Vault you use (v1.5.0-b28) has 1.8 items inplemented which are not (official) on your server.

**Comment by rlf** [comment]
Rejecting Any Issue Written In CamelCase or Title Case Through And Through (I'm A Grumpy Old Man, Deal With It)
