### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [rlf/uSkyBlock#217]
Timings are interesting:
![image](https://cloud.githubusercontent.com/assets/3297866/5989806/153d3d10-a994-11e4-85ee-a195279e6915.png)

**Comment by rlf** [comment]
Yes, for now, you should disable the options.island.autoRefreshScore by giving it a value of 0.

It's due to the island-level calculations being done too often now. and it takes more than a tick to complete for large islands.

**Comment by rlf** [comment]
Duplicate of #215

**Comment by TheOnlyRealTGS** [comment]
Okay.
