### ISSUE TITLE
More Customization to Number of Party Members 

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#218]
It would be great if I could specifically pick different numbers of island party numbers for separate ranks.

**Comment by rlf** [comment]
Already supported.
Though currently hardcoded.
```
usb.extra.party1 = partySize of 5
usb.extra.party2 = partySize of 6
usb.extra.party3 = partySize of 7
usb.extra.partysize = partySize of 8
```

**Comment by rlf** [comment]
Actually, looking through the code, this should be "fixed", so we instead use something along the lines of the `extraPermissions` section.

Perhaps enhance that section, so the items get their own line, and the partySize another.

**Comment by dutchy1001** [comment]
the way I read this is that normal players have a max of 4 in the party and a donator 8 in his party, as example then.

To get this the same way as the extrapermissions is a good idea.

**Comment by rlf** [comment]
Also, change the partysize perm to party4.
