### ISSUE TITLE
Enderpearl damage is ignored (counts as member-damage)

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#220]
I am using uSkyblock 2.2 HF2.

One of my players used an ender pearl to get on top of his mob grinder located on his own island. He did not take damage and he got the message "you cannot hurt island members".

**Comment by dutchy1001** [comment]
I get this too when trowing enderpearls

**Comment by rlf** [comment]
Ok, ender-pearl-damage is projectile damage (apparently), will look into handling this.

**Comment by rlf** [comment]
Should be fixed in v2.2-HF9 - ready for test

**Comment by dutchy1001** [comment]
fixed
