### ISSUE TITLE
AllowChallenges Ignored

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#221]
I gave my players the permission node to use challenges, but allowchallenges is set to false in the challenge file. They are still able to use challenges.

**Comment by rlf** [comment]
I think currently, the allowChallenges in the config-file has no effect - should probably be fixed...

**Comment by rlf** [comment]
Should be fixed in v2.2-HF9 - ready for test

**Comment by dutchy1001** [comment]
fixed
