### ISSUE TITLE
Can't use the commands: /c or /is

### ISSUE THREAD

**Issue by xGoldenPandax** [rlf/uSkyBlock#222]
Hey there for some reason i can't use /c command with uskyblock plugin which should display the challenges
I ment /is level sorry for the misunderstanding

heres there error: http://pastebin.com/TpkVWMKW

**Comment by dutchy1001** [comment]
What are the permissions given? 
Do they have permissions? 
Does it work for when players are in OP mode?

With only little information to go on and just the error bit from console, it's hard to see what's going on, plaz read the wiki "how to post an issue/bug" on the main page.

**Comment by rlf** [comment]
a) Log says you are running 1.7 - that is important info.
b) Log says it's not a uSkyBlock issue, but rather something with your chat-control - possibly something with color-codes.
