### ISSUE TITLE
Dev Reload Treats Owners Like Visitors

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#224]
When using the command /dev reload, some of my players were treated like visitors on their own island, in the sense that they could not pick up items. It's only fixed if players go to spawn then return to their island.

**Comment by rlf** [comment]
This sounds really weird.
All though - I think the work-around sounds sensible as well.
It really depends on what has changed during the `/usb reload`.
Not sure this will get any love from me...

**Comment by TheMattVid** [comment]
The thing I changed when this happened was a few of the challenge rewards.

**Comment by rlf** [comment]
If you find a way to reproduce it consistently - I'll have a look - until then, use `/usb reload` with care, esp. since you have no idea what happens to the data-model while players are "using" it.

**Comment by dutchy1001** [comment]
I cant reproduce this "glitch" and havent heard any more about it from other server owners.

if problem occurs again reopen or create a new issue.
