### ISSUE TITLE
/dev reload doesn't load last island

### ISSUE THREAD

**Issue by woolwind** [rlf/uSkyBlock#225]

**Comment by woolwind** [comment]
I've had to hand-fiddle it to fix issues and it currently requires stopping the world and editing while down.

**Comment by rlf** [comment]
The whole lastIsland handling is subject to #5 and is currently scattered all around the plugin.
Should be refactored into a coherent class instead.

**Comment by dutchy1001** [comment]
is this still an issue or can this be closed?

If not, would a manual "save" command help here to save any progress before an autosave?

**Comment by dutchy1001** [comment]
been a long time since there was anu input, closing this for now.
