### ISSUE TITLE
1.7 server and WG 6.0

### ISSUE THREAD

**Issue by MineTheCube** [rlf/uSkyBlock#226]
Hi,

Version of my plugins:
- uSkyblock v2.2 for 1.7.10
- WorldGuard 6.0 Beta 5
- WorldEdit 5.6.2
- Vault 1.4.1-b436
- Spigot 1.7.9 R0.2 (with 1.8 protocol)

Problem:
- uSkyblock (1.7 version) seems not able to handle worldguard 6.0, as I have error on startup and when uskyblock have to use worldguard api (lock/create/delete island..)

Logs:
- On startup: http://pastebin.com/raw.php?i=dcezd1R2
- On click on "lock island": http://pastebin.com/raw.php?i=TZUD2HyF

Note that uSkyblock is compatible with UUID, but not WorldGuard 5.9. So what about updating it to WG 6.0 (for 1.7 servers) ?

Please fix that as soon as possible, because my server is closed while this cannot be fixed.
And I can't update my server to 1.8, many plugins aren't ready yet.

**Comment by dutchy1001** [comment]
Why dont you use WG 5.9 then? This is why we did put it as dependend. I'm not sure if WorldEdit plays nice with WorldGuard with the different versions you use. I would either have them both v5 or v6 not a mix.

**Comment by MineTheCube** [comment]
Because WorldGuard 5.9 doesn't use UUID at all..

**Comment by dutchy1001** [comment]
uSkyblock works independend from the WG UUID,

**Comment by MineTheCube** [comment]
Yes but I just want a 1.7 server compatible with UUID..

And currently uSkyblock supports UUID but use WG 5.9 that doesn't..

**Comment by dutchy1001** [comment]
We will look into to make it compatible and have 1 version supporting both, just dont know the timescale it takes atm.

**Comment by MineTheCube** [comment]
Okay thanks, I wouldn't want to bother you as much, but I don't understand why you still use WG 5.9 as it doesn't use UUID.

And I forgot to say, thanks for your awesome jobs :)

**Comment by dutchy1001** [comment]
It has to do with the different use of flags, dont ask me exact how as rlf is the dev that does the coding.

thx for the thumbs up.

**Comment by rlf** [comment]
We are looking into making the uSkyBlock releases support both older and newer versions of WG and WE ... it requires some tweaking though.

**Comment by MineTheCube** [comment]
Okay, thanks a lot.

I was thinking of an easier way to support UUID (with WG 5.9): a command like "/is update" which update the region where the player is member.

Well, do as you want :)

**Comment by MineTheCube** [comment]
Is there any ETA for supporting 1.7 server with WG6.0 ?

Because my server is closed for the time being.. :/

**Comment by rlf** [comment]
Soon?
Support is already in v2.2-HF7 - but there seems to be some issues we still need to get working...

**Comment by MineTheCube** [comment]
Well, does this version really work on 1.7.10 servers ?
I see "Game version: 1.8.1" on bukkit download page...

**Comment by rlf** [comment]
Well, try it. Currently I think we have an issue on runtime with WG 5.9 - but we don't block it anymore - since we are working on being backward compatible.

**Comment by MineTheCube** [comment]
I've done some testing, I use v2.2-HF9b and it works great on 1.7.10. No error on startup, neither during runtime !

I'm using WG 6 beta 5, WorldEdit 6.0, Vault 1.4.1-b436 on Spigot 1.7.10 with 1.8 protocol hack.

**Comment by rlf** [comment]
Thank you. Closing this for now then.
