### ISSUE TITLE
WorldGuard names do not update to a changed username

### ISSUE THREAD

**Issue by Turbotailz** [rlf/uSkyBlock#227]
Versions:

uSkyblock - v2.2-HF1
WorldEdit - 6.0
WorldGuard - 6.0

Problem:

I have just had someone log on who has changed their name. They are teleported to their island when they type /is home, but they can't do anything on the island. I have checked the WorldGuard config and everything is still set to their old username (I thought we'd be dealing with UUIDs here, to be honest). 

Looks like I will have to change these names manually myself.

**Comment by TheOnlyRealTGS** [comment]
Can confirm this - you can fix this by looking up old user names, using the API:
http://wiki.vg/Mojang_API

**Comment by TheOnlyRealTGS** [comment]
Actually, see my comment over at the other ticket: https://github.com/rlf/uSkyBlock/issues/231#issuecomment-73238974

**Comment by rlf** [comment]
Seems we have some issues with WorldGuard and uSkyBlock with UUID - we are looking into it.

**Comment by rlf** [comment]
Closing this, as it seems it can be handled in #231 from now
