### ISSUE TITLE
How to restore deleted skyblock island?

### ISSUE THREAD

**Issue by AppleTechMedia** [rlf/uSkyBlock#230]
Some commands went weird, and one of my player's island got deleted. How can I restore it?

**Comment by AppleTechMedia** [comment]
Some commands went weird, and one of my player's island got deleted. How can I restore it?

**Comment by dutchy1001** [comment]
from a backup?

**Comment by AppleTechMedia** [comment]
Is that the only way? Because I haven't made a backup..

**Comment by dutchy1001** [comment]
I believe so.
