### ISSUE TITLE
How to change skyworld default spawnpoint

### ISSUE THREAD

**Issue by AppleTechMedia** [rlf/uSkyBlock#233]
I was wondering if there was a way for me to change the default Skyblock spawnpoint to a different location?

**Comment by TheMattVid** [comment]
It's currently set up so that the spawn point is in front of the chest.

**Comment by dutchy1001** [comment]
Do you mean on the island or the default world spawn?

Both of these spawns are hardcoded in the plugin and are not easy to change without knowing how to code.

**Comment by rlf** [comment]
Depends.
The skyworld spawn point is only set, if the world doesn't already have a spawn point.
So, you should be able to use "normal ways" of adjusting the skyworld spawn point.

I.e. `/mvm set spawn`.

If you are talking about the "island-spawn-point", it is as @TheMattVid said above. In front of the chest nearest the bedrock, facing the chest.

**Comment by TheOnlyRealTGS** [comment]
Actually, this is really annyoing for people who have their SB spawn in another world. It would be great if you guys could add a option to let MultiVerse handle it.

**Comment by dutchy1001** [comment]
When using EssentialsSpawn or any plugin the support the /spawn command and have the confidg setting "sendToSpawn" set to true, it should bring you to the default spawn world (this can be set in multiverse). If you set this setting to false you should stay in the Skyworld.

**Comment by TheOnlyRealTGS** [comment]
Thing is, my spawn is in a other inventory group from MultiInv, so that's a bad idea - In a month or so I'll reset everything and move the spawn to skyworld - but it would atleast be nice if you could define which world the player should spawn in.

**Comment by rlf** [comment]
Well, currently, that is the way it works.
```yml
sendToSpawn: true
```
Will send the players to `/spawn` - where as `false` will send them to the the spawn point of the skyworld.

If you want other behaviour - try to describe what that behaviour should be - and we will look into it.

**Comment by TheOnlyRealTGS** [comment]
What I was thinking was a option:

´´´
sendToSpawnWorld: "skyworld"
´´´

**Comment by dutchy1001** [comment]
just change it to "false" should do it

**Comment by TheOnlyRealTGS** [comment]
But my /spawn is not set to the skyworld's spawn, it's set in another world.
Also, it is false.
