### ISSUE TITLE
Can you release a 1.7 and 1.8 version every time you update?

### ISSUE THREAD

**Issue by dylanweb2** [rlf/uSkyBlock#237]
Can you release a 1.7 and 1.8 version every time you update, there are many of us out here a ton of us who are dependent on the 1.7 version uSkyBlock and it would be awesome if a release of both version came out on each update.

**Comment by dutchy1001** [comment]
We are working on a joint version so we only have to update 1. This proves to be a bit more difficult due to the different working of WorldGuard v5.* and v6.*

**Comment by dylanweb2** [comment]
Oh awesome! good luck!

**Comment by rlf** [comment]
Just an update - we now have something that compiles under wg5/6 and we5/6 - unfortunately - wg6 seems to have breaking changes, meaning, a version that runs with both WG5 and WG6 is not easily obtained - we are still investigating this issue though.

**Comment by ProsperCraft** [comment]
Why would we need worldguard 5? 

Worldguard 6 works great on 1.7.10.

**Comment by dylanweb2** [comment]
It's not worldguard. It's world edit which doesn't work with 1.7.10

**Comment by ProsperCraft** [comment]
WorldEdit (6.0;3342-78f975b9)

I am running WorldEdit 6.0

**Comment by ProsperCraft** [comment]
Apparently you can run 1.8 uskyblock on 1.7.10 after you install all of the updated plugins.

**Comment by ProsperCraft** [comment]
v2.2-HF9b for 1.8 works fantastic on 1.7.10, here are my plugin versions.

uSkyBlock v2.2-HF9b
Vault (1.4.1-b436)
WorldEdit (6.0;3342-78f975b9),
WorldGuard (6.0.0-beta-05.1569-)

**Comment by dutchy1001** [comment]
I've updated the wiki nd the bukkit page to the new requierments needed for both versions of CraftBukkit/Spigot.

It seems to work now, closing this topic.
