### ISSUE TITLE
Island Invite Expirations

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#238]
Someone sent me an island invite on my server, and it lasted for hours if I didn't respond. It should go away in 5 minutes max automatically.

**Comment by rlf** [comment]
Yes, we have talked about this - and we will most likely implement this eventually.

**Comment by woolwind** [comment]
I had a problem with a player who couldn't invite someone new because old invitations stayed open I think till the log position wraps around

**Comment by rlf** [comment]
No, they stay active forever, or until it's removed by using the `/is party` command

**Comment by rlf** [comment]
... or the server is restarted...

**Comment by rlf** [comment]
Part of v2.2-HF8

**Comment by dutchy1001** [comment]
Working in v2.2-HF9b ( just needs adjusting the time from 100(5 seconds to 600 (30seconds) for the default setting).
