### ISSUE TITLE
Player Death

### ISSUE THREAD

**Issue by DogsPaw** [rlf/uSkyBlock#239]
When a player dies, they are taken off their island, spawn on a piece of bedrock with random XZ Coords Y=0
If they run /is again. It takes them back to their Island.

Deaths that have returned this:
Jumping into Void
Hostile Mob murder
/Suicide
/Kill

**Comment by rlf** [comment]
The coordinates are not random, they depend on your settings and your worlds.
If `sendToSpawn` is false, they are ported to the "spawn-location" of the skyworld - and this should initially be at 0,island-height,0.
If `sendToSpawn` is true, they are returned to `/spawn`.

**Comment by DogsPaw** [comment]
spawnSize: 150
I don't actually use a Spawn in the SkyWorld, I have another world dedicated for it. It's putting players at several XZ Coordinates though. It changes everyday. It was putting them first at X1200 Y0 Z700, so we put a sign near it saying to just run /is until we could fix it. It then moved to another location after that. NOW, it just drops you into the Void until you run the /is command, the respawn point is UNDER random player owned Islands. I will change my sendToSpawn: false to True, I'm just letting you know it's getting weird on Player Deaths. I just tried it, the Island it spawned me under to fall was created a few days ago. I restarted about a week ago and have about 300 Islands+ generated so it's spawning me way away from the empty Spawn Area.

**Comment by rlf** [comment]
Ok, that sounds genuinely weird.
What versions are you having? (`/usb version` if you have a current release).

**Comment by DogsPaw** [comment]
2.2 HF7 5a33a9 dev

**Comment by dutchy1001** [comment]
have you ever used the "setspawn" command of multiverseor essentials to relocate the spawn manual?
You can reset it with the command "/mvsetspawn or /setspawn" , just stand on the location x=0 y=150/120(depending on your island height) z=0

**Comment by DogsPaw** [comment]
I have done both commands in my Spawn world. I was going to change the spawn area built into uskyblock to 0. But I already had islands generated and with how easy it is to corrupt islands, I left it alone.

**Comment by dutchy1001** [comment]
the player island generated arent on the 0 (zero) location, no player island will be set there. you can still d o the command "/mvsetspawn" in the skyworld as that only set the spawn for that world. Incase the default spawn is set in an other world it will overrule the MV spawn of skyworld and spawn players into your default world.

Using "sendToSpawn: false" will keep them in the skyworld, when set to "sendToSpawn: true" it will use the /spawn command (or on death) default location in your case in the other world. 
You have to have EssentialsSpawn.jar or any other plugin that uses the /spawn command.

**Comment by rlf** [comment]
It sounds like you might have some other plugins active - since "random spawning players" isn't default behaviour for either Multiverse, Essentials or uSkyBlock.

**Comment by rlf** [comment]
Either that, or one of your players (or plugins) changes the skyworlds spawn location at various intervals/times - making it seem to be random.

**Comment by DogsPaw** [comment]
Switched the sendtospawn to true and nobody has reported issues. This can be closed.
