### ISSUE TITLE
Corrupted island file?

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#242]
Spigot version: d0d1d87-15e81cf
uSkyBlock version: v2.2-HF7-5a33a9-dev

Receiving the following error:
http://pastebin.com/raw.php?i=inJAhxkK

The island file:
http://pastebin.com/raw.php?i=4yi4kG62

This has occurred at least a few times over the span of 2 hours with different islands.

**Comment by rlf** [comment]
Run `/usb import fix-leader-uuid` on the v2.2-HF7 or later release.

**Comment by BlackBeltPanda** [comment]
Worked, thanks. =)
