### ISSUE TITLE
/is info for admins

### ISSUE THREAD

**Issue by drtshock** [rlf/uSkyBlock#244]
Would be nice to have /is/usb info so admins can check info of the island they are on but not owner of.

**Comment by dutchy1001** [comment]
that's already there, /usb info [name]

when on the island you already had a message from WG what island your on.

**Comment by drtshock** [comment]
Oh nice! In that case, you should add it to the page I found while looking for documentation, unless there's a new one. 
http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/commands-and-permissions/

**Comment by dutchy1001** [comment]
yes that page needs an update, unfortunattely I haven't had the chance to add it.
It will be there tonight as some stage.

**Comment by rlf** [comment]
If you execute the `/usb help` command or `/is help` as OP, it will tell you all the relevant permissions as well.
