### ISSUE TITLE
Non-Party Player Booting

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#245]
It would be nice if we had an /is boot command to kick players off an island who are just visiting and not part of the party. I know lock and ban are also methods to deal with this, but this third option would also be very useful for island owners.

**Comment by dutchy1001** [comment]
agreed

**Comment by rlf** [comment]
Should it have a `/is bootall` sibling then :) To get all non-members off the island.

**Comment by dutchy1001** [comment]
I think per player is enough as sometimes it is just 1 player that annoys lol

**Comment by rlf** [comment]
Shouldn't you then just use `/is ban <player>`? Since booting him will just bring him back soon?

Nvm. I get it - esp. when some idiot goes AFK in the middle of a building project or similar.

**Comment by rlf** [comment]
Ready for test in v2.2-HF10, the `/is kick` command now works for non-members as well.

**Comment by dutchy1001** [comment]
tested and working on HF10a
