### ISSUE TITLE
Double Island Leaving Messages

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#248]
When you leave a player's island region, you get two messages instead of one. I am having this problem using HF7.

**Comment by TheMattVid** [comment]
It seems that one is caused by exiting the region and the other is caused by movement outside of the region. For example, if you walk outside an island region, the two messages pop up in a row. If you teleport out of a region, the first message will pop up immediately, but the second one won't appear until you move following the teleport.

**Comment by rlf** [comment]
Sounds like a WG issue tbh. Unless uSkyBlock accidentially has made more than one overlapping regions. Could you test that? `/rg info` within the island.

**Comment by TheMattVid** [comment]
Yeah, only one region. The problem only applies to leaving islands. Not entering. I will give my spawn region a name and see if I get a similar issue. If I do, I will report the problem to WorldGuard.

**Comment by TheMattVid** [comment]
I have confirmed it. This is a WorldGuard issue and I will report the bug there.
