### ISSUE TITLE
Messages turn gray to white halfway through /is top

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#249]
On the top island list, every island is listed with a green rank number, a gray level number, and the reset of the message is supposed to be gray.This seems to happen right after the second party member. For example, on an island with two people, the end bracket is white. On an island with three people, the comma after the second name, the third name, and the close bracket is white. The trend continues with 4: comma after second name, third name, fourth name, and close bracket is white.

**Comment by rlf** [comment]
Can you post a screendump. I've seen it in other plugins as well - but would like to avoid it in uSkyBlock.

**Comment by TheMattVid** [comment]
![whitenames](https://cloud.githubusercontent.com/assets/10250080/6154283/79660f3a-b1f8-11e4-9ed6-eeb2965beec2.png)

**Comment by TheMattVid** [comment]
Also, the names of the people with prefixes are supposed to be white because I chose to end the prefixes with the white color code. Everything else, including the bracket at the end of juliacanada, the names, and commas are supposed to be gray, but are not showing up as such.

**Comment by rlf** [comment]
So, the plugin should make sure to color-code it's own "text", when-ever a name or display-name has been inserted. We will look into this.

**Comment by dutchy1001** [comment]
I havent notest diferent color in my list since they are yellow.

Fixed in HF13e. (if it still happens to you TheMattVid let us know and we open the issue again)
