### ISSUE TITLE
can't create or reload island

### ISSUE THREAD

**Issue by Yselith** [rlf/uSkyBlock#253]
Hello,

I get error when trying you create island, it's on 1.7.10 server. It don't work with the 1.7.9 uSkyblock version but work prefectly with 1.8.1. *-*

Version: 2.2-HF4
Description: Ultimate SkyBlock v2.2_for_1.7.10

Server: Cauldron-MCPC-Plus git-Cauldron-MCPC-Plus-1.7.10-1.1240.06.213 (MC: 1.7.10)

Name: Vault
Version: 1.4.1-b436

Name: WorldEdit
Version: 6.0;3342-78f975b9

Name: WorldGuard
Version: 6.0.0-beta-03.1514-
http://pastebin.com/0Y22jQpt

**Comment by dutchy1001** [comment]
Plz follow this guideline to post an issue. Click [here] (https://github.com/rlf/uSkyBlock/wiki#how-to-post-an-issue)

**Comment by Yselith** [comment]
usb version is not working, like all usb command apparently. I edited the first topic.

**Comment by dutchy1001** [comment]
update uSkyblock to v2,2-HF9b 
Update Vault to 1.5.x

these versons should work with the 1.7.9/10 servers but can(dont have to) give some errors with worldguard.

**Comment by Yselith** [comment]
Thank you, it's working for the moment. But if i try to sleep, i enter directly go out of the bed, i get the world guard island message: Entering then Living island.
