### ISSUE TITLE
Some performance soft spots

### ISSUE THREAD

**Issue by drtshock** [rlf/uSkyBlock#255]
It's causing lag processing the joins because it iterates over the entire yaml file that's in memory until it finds a match :(
https://github.com/rlf/uSkyBlock/blob/1bc8f05bfed5306083f135d3afe3facd8d288696/src/main/java/us/talabrek/ultimateskyblock/uuid/FilePlayerDB.java#L29

There also appears to be some issues with the level command as you can see http://timings.aikar.co/?url=10211068

We're running 2.3.0-SNAPSHOT (not sure which specific build).

**Comment by dutchy1001** [comment]
your still on an older build, update to v2.2-HF9b, if it still happens then let us know

**Comment by rlf** [comment]
Reg. the iterating being the cause of the lag - it shouldn't be, since the config is read into memory.
If you see the same behaviour on the latest official release (v2.2-HF9b as of this writing), please update the issue.

**Comment by drtshock** [comment]
We're running that now. We have 2.3.0-SNAPSHOT on one of our skyblock servers and 2.2-HF9b on our other one (not sure how 2.2 is newer than 2.3 but ok). I'll monitor them throughout the day and get back to you guys via this ticket later.

**Comment by drtshock** [comment]
Actually, right away it's just horrible http://timings.aikar.co/?url=10225399. Server has only been up for a few minutes.

**Comment by dutchy1001** [comment]
At the time of releasing we weren't sure what format we should use for version numbers, hence the odd one out here.

**Comment by drtshock** [comment]
server running the hot fix hasn't gone above 15 tps in 2 hours. server running 2.3.0-SNAPSHOT has been better http://timings.aikar.co/?url=10227041

**Comment by DogsPaw** [comment]
What else are you running? I've run Skyblock world's over 15GB in size and it's never lagged for me. I reset a little over 2 weeks ago and I'm back up to 2.6GB for the world file. Not running any AntiLag plugin either. I haven't dropped below 15TPS.

**Comment by drtshock** [comment]
@DogsPaw you should take a look at the timings to see what we are running as well as what is taking up so much of each tick.

**Comment by DogsPaw** [comment]
You're saying you haven't gone above 15 TPS. I have 60 players on right now with 8GB free of the 20GB assigned with 20TPS. I'm having zero lag. Which is more than enough to keep me satisfied. With 10K chunks loaded.

If it was seriously making me lag, I'd check timings and everything else to make sure. Core protect plugin causes some lag spikes occasionally due to everything being logged. But that's isolated to a specific area.

**Comment by rlf** [comment]
Continuing this issue in #247

**Comment by rlf** [comment]
Reg. the 15 TPS comment, and the timings reported above.
I would take a look at your AlphaChest plugin.
I severely doubt uSkyBlock is to blame.
