### ISSUE TITLE
Not removing player from region?

### ISSUE THREAD

**Issue by DogsPaw** [rlf/uSkyBlock#256]
![screenshot 2015-02-13 16 08 41](https://cloud.githubusercontent.com/assets/10334634/6197473/c93e1cf2-b39a-11e4-89d5-6245798c0288.png)
![screenshot 2015-02-13 16 08 47](https://cloud.githubusercontent.com/assets/10334634/6197474/c93fbdd2-b39a-11e4-976e-00f8c1bc0109.png)

This player removed the person from his Island, but the player managed to get back on and was able to break blocks. There is no logs of him being kicked, but he's not apart of the Island, but he's still in the region.

WorldGuard: #1583
uSkyBlock: 2.2-HF9b

**Comment by DogsPaw** [comment]
My error: WorldGuard: #1583

**Comment by rlf** [comment]
Sounds like an exception occurred when he kicked him from his island.
Do you have any server-logs from the time of the reported incident?

**Comment by dutchy1001** [comment]
this error is not happening in v2.3, region is updated when player has (/is leave) left the island or has been kicked (/is kick name) by the  island owner.

If still happening, reopen the issue.
