### ISSUE TITLE
Manual Cool-Down Bypass

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#257]
The player island cool-downs with island creation and restarting has been going smoothly and wonderfully. The only problem is that occasionally, I know that the person has a genuine reason to restart or leave an island. Can you add a dev/usb command that resets the creation/restarting cool-down for an individual player?

**Comment by rlf** [comment]
We already have a permission override - but as I understand you, you want a "cooldown-reset-command" in the `/usb` segment - sounds like an idea.

**Comment by TheMattVid** [comment]
Yes, you have understood correctly.
