### ISSUE TITLE
Drop Protection Stopped Working For One Particular Player

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#260]
On one particular player's island, whose protection region is still, there, every player now has the ability to pick up items. This problem is not on any other island. I will see if a restart fixes it, but for now, it's a cause for concern.

**Comment by rlf** [comment]
It seems the island in question, might be within the specified "spawnSize" in the config file.

That way, all players can pickup items.

**Comment by TheMattVid** [comment]
Good insight. My world generated before the corners thing was fixed. I suppose simply decreasing the spawn size and reloading the server will fix this. I will get back to you.

**Comment by TheMattVid** [comment]
Ok, I finally got around to testing this. I decreased the spawn size from the default to 0. The problem is still occurring, but still only near the spawn region. Is it possible that the "spawn size" option only applies to the initial generation of the skyworld?

**Comment by rlf** [comment]
No.
But the logic about spawn is, that players can only pickup stuff on their own island, or stuff they dropped them selves, or when they are within the spawnSize from 0,0.

Is this concerning all his items? Or is it just some? Do the items still have a lore saying something like `Dropped by: R4zorax`?

**Comment by TheMattVid** [comment]
During the test, I would go to random islands and drop items onto that island toward another person who doesn't own the island. So, just to reiterate, neither myself nor the other tester was a member on the islands we were testing on. The other tester also didn't have any permissions that would let him pick up on every island. That other person would be able to pick it up, but only in what seemed to be close to what the spawn region was initially set to. I did some tests to see what coordinates worked and didn't work. Pass means players couldn't pick up the items and fail means they could. Fail means they picked up the items.
x,y
-105,105 Pass
-95,95 Fail
-105,90 Fail
-110,-105 Pass
-75,115 Fail
-15,-230 Pass
-170,0 Pass

**Comment by dutchy1001** [comment]
As you see there is a patern going on, islands with 1 of the value below 105 fails, and islands with 105 or higher value passes.

Is spawn set to 100??

**Comment by rlf** [comment]
Sounds like the spawnSize is still set to 100. Did you try restarting the server after you changed the value?

**Comment by TheMattVid** [comment]
Alright. Previously when I reloaded, I just did a plugin reload. A server reload fixed it.

Not sure if it is another bug, but perhaps the spawn size is not a complete square. The previous coordinate tests were done when the spawn size was 150 (even though I did not know that the 0 hadn't overwritten the 150 yet). As you can see, the coordinates -105.105 and -110,-105 successfully prevented other players from picking up items, even though it was technically in the spawn region. A spawn region of size 150 is supposed to go from -150,-150 to 150,150, but this data leads me to believe that the spawn region is not included from the "100,100"s to the "150,150"s. This means that it is possible that the spawn region is shaped like a plus sign instead of a full square. This probably won't have consequences for anyone, but I thought this might be useful information

**Comment by dutchy1001** [comment]
As the initial issue is solved or corrected I will close this. 

In regarding to the last message I have recreate a spawn and new island around it which were auto adjusted at distance between the island and all started on the border of the given spawn size.
![2015-01-29_14 30 06](https://cloud.githubusercontent.com/assets/5569980/6485985/a0b6817c-c27f-11e4-8e53-2a2dac23f354.png)

Orange = spawnsize
Red = island size
Green = protected region size
Blue = adjusted area
