### ISSUE TITLE
/is info and /is level to have separate permissions

### ISSUE THREAD

**Issue by Nightwolf3218** [rlf/uSkyBlock#262]
I am not sure if I am missing something or not.

I am wanting to be able to stop my users from using /is info because it gives too much information (we don't want our players to be able to easily see that much information about where the island levels are coming from).  However, I do want players to have access to /is level.  Do these commands have separate permissions so that I can deny access to one command and not the other or is it the same permission like I think it is?  If it is the same permission for both commands, would it be possible to split these two commands to have separate permissions or a way to configure this command not to be available?

**Comment by rlf** [comment]
Currently, you are right - same command.
But we can add an additional permission to the use of `/is info`.

**Comment by dutchy1001** [comment]
An easier way of doing is to add to the global region the "blocked-cmd: [/is info]" flag. This should stop any command added to that list for the skyworld.

**Comment by Nightwolf3218** [comment]
Thanks.  I think the permission addition would be a great idea.

@dutchy1001  Thank you for reminding me we can do this.  I totally forgot about being able to do it this way despite that we use this exact same thing for  a number of other commands in some of our other worlds.

**Comment by rlf** [comment]
Just remember to include all the aliasses as well (skyblock, sb, island, is).

**Comment by Nightwolf3218** [comment]
@rlf Thanks a lot, I totally missed skyblock and sb

**Comment by dutchy1001** [comment]
tested in HF12b working.

closed
