### ISSUE TITLE
Challenge limitation with more then 8 challenges are in a rank

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#263]
When more then 8 challenges are present it wont go to the next row. It acceps 9 challenges per row even that there are only 8 spots left, the 9th will not show and can only be completed with chat commands. Having more then 9 challenges it will error in console after the command /c or /challenges is given. (see chat with wesley in spigot)

**Comment by rlf** [comment]
> Error trace: http://pastebin.com/ksKffpba
> Here's my full challenges.yml: http://pastebin.com/5C7LTk0s

**Comment by Seadragon91** [comment]
Whats about making one inventory per rank?
The first 9 slots would be reserved for the plugin, that has 3 items in the middle.
[backward][rank name][forward]
You would have 45 slots left for challenges and I think that are enough...

**Comment by rlf** [comment]
Depends - for those that have less than 8 challenges per rank, it's "less hassle" to find your challenges when they are all shown in one picture.

I think a "better" way, would be to enforce max 8 challenges per rank - and then just "teach" server-owners to introduce more ranks.

**Comment by rlf** [comment]
Easy work around is avoid having more challenges per rank.
Since we have a lot of higher priorities right now - I "reject" this issue for now (we'll keep it in mind, when/if we give the GUI an overhaul later).
