### ISSUE TITLE
Bans, and other things, are stored by names, not UUIDs

### ISSUE THREAD

**Issue by drtshock** [rlf/uSkyBlock#273]
Island bans are stored via name in the StringList banned.list. They should be stored by UUIDs. This is also true for island members and probably for others that I didn't see in a quick check.

**Comment by rlf** [comment]
No. We convert the names to new ones when a player changes name.
This is by design. So not a bug.

**Comment by drtshock** [comment]
Why not just save by UUID instead of having to check if a player changes names each time they join? Seems like a ton of extra overhead that isn't necessary as evident in https://github.com/rlf/uSkyBlock/issues/255.

**Comment by rlf** [comment]
Do you have a question?
Or do you just question the reasoning? or the correctness of the solution?

I had a post on the Spigot forums, asking for input/feedback for the way we chose to handle UUID here - and in that thread - it seemed like the most viable solution.

The data-model this plugin uses is heavily reliant on names, and not on UUIDs. Changing to UUID would either mean an immense complexity increase in most operations, or a rather severe performance hit. We decided to keep the relational data on the name, and then just maintain that relation when a name-change was detected.

If you have any constructive criticism, or even better, design solutions - I'd be happy to discuss them.

We deemed the "keep track of name-changes" would be sufficient to get uSkyBlock to "support UUID" - and then take the relational-data "hit", when we move to an SQLite/MySQL backed data-model.
