### ISSUE TITLE
How do you do to have multiple islands?

### ISSUE THREAD

**Issue by alepalma** [rlf/uSkyBlock#274]
I've seen the config and I'm not sure I get it. What I understood from the config file is that you can change the default island with a schematic you want, and items in the chest you want etc... What I was wondering if there's a way to make more than one island, because I want to assign an island to each rank

For example
Default--> island_default.schematic ; items in chest: 3 10 11
Iron--> island_iron.schematic ; items in chest 3 10 11 15 17
Gold--> island_gold.schematic ; items in chest 3 10 11 15 17 18

and so on and so on. This is just an example of what i would like to be able to do ( IDK if i m already able to) with of course all the specifiactions already included in the uSkyBlock config>island section

Thank You very much!

**Comment by dutchy1001** [comment]
I'll explain this tomorrow how to, just to tired now to make a long post

**Comment by dutchy1001** [comment]
As this is not really an issue that has to be fixed I will close the this. However I will put a link to the DevBukkit page with an explanation so everybody can use this.
Click [here](http://dev.bukkit.org/bukkit-plugins/uskyblock/#c120) to go to the explanation.
