### ISSUE TITLE
[Suggestion] make onIsland challenge distance configurable

### ISSUE THREAD

**Issue by wesley27** [rlf/uSkyBlock#277]
Hello again, just a suggestion, something I had changed in my version that I believe you changed again. For onIsland challenges, apparently all the required blocks/items need to be within 10 blocks of the player.

I have challenges that involve having lots of certain blocks on your island, sort of like building milestones. Many times, all those blocks don't fit within 10 blocks of the player. So, it would be really useful if, rather then that distance for onIsland challenges being set to 10, if it was configurable in the config.

**Comment by rlf** [comment]
It already is.
See https://github.com/rlf/uSkyBlock/blob/master/src/main/resources/challenges.yml#L506
