### ISSUE TITLE
can't use the island level or challenges.

### ISSUE THREAD

**Issue by xGoldenPandax** [rlf/uSkyBlock#278]
I used the island level box first then tried challenges but nothing happened

http://pastebin.com/J2GqGg8S

**Comment by dutchy1001** [comment]
It looks like you have Vault v1.5.2 on a 1.7 server. Use the Vault 1.4.1 as the newer version has 1.8 items that it cant find in 1.7.9/10

**Comment by xGoldenPandax** [comment]
Thank you i changed it and it works great thank you so much :+1:
