### ISSUE TITLE
Problem with schematics

### ISSUE THREAD

**Issue by alepalma** [rlf/uSkyBlock#281]
Hello again (hehe)

I've been experimenting issues with schematics lately. The thing is on my server I have 8 ranks (including default) and a island schematic assigend to each one. The proble is that it loads only three of the schematics. We will call the ranks 1 2 3 4 5 6 7 and 8. This is how schematics are loaded

island_default.schematic (setted as default island): loaded only by rank 1 (default rank)
island_member.schematic (corresponds to the schematic for rank 2): loaded only by rank 2 3 4
island_sponsor.schematic (corresponds to the schematick for rank 5): loaded only by ranks 5 6 7 8

What shall I do? Please help!!!

Thank You very much!

**Comment by dutchy1001** [comment]
A bit of reading on your part on the forums wont hurt. I resently posted a big explanation how to use multiple schematics with custom items.
Read [here](http://dev.bukkit.org/bukkit-plugins/uskyblock/?page=2#c120) on the DevBukkit forum or [here](http://www.spigotmc.org/threads/uskyblock.38300/page-28#post-566446) on the Spigot forum, both are the same post.

**Comment by alepalma** [comment]
dutchy, I m the one who asked before! I m the one about the iron and gold ranks! What I did not find in your explanation is how to solve this problem: I have 8 ranks and 8 schematics! Each one assigned to each rank, i did put the permission usb, but yet, only 3 out 8 schematics are loaded!

**Comment by dutchy1001** [comment]
If each rank has the right permission they should get the island the permission tells it to give. If the permission plugin mixes this up then you could "negate" the other islands for that rank.

* - -usb.schematic.island_iron
* - usb.schematic.island_gold

this way it cancels the iron_island and adds the gold_island (look at the - infront of iron)
This shouldnt be necessary (in most cases then).

**Comment by alepalma** [comment]
ohhhhhhhhhh right! i forgot about the inheritance!
