### ISSUE TITLE
Request: Inventory clear configuration

### ISSUE THREAD

**Issue by FelitonC** [rlf/uSkyBlock#282]
This could be a low priority thing in all terms of the word, but every time a user generates and island their inventory is cleared, causing an annoyance. I simply request that there be a true or false option in the config for your one line of code in the island generation in terms of clearing their inventory when they create an island or not. (IslandGenerator.java) Thanks!

**Comment by dutchy1001** [comment]
That setting is added in v2.2-HF11 and above.
You can now choose between keeping or clearing, each separate, of Inventory, Armor and Enderchest.
