### ISSUE TITLE
/is create command isn't working!

### ISSUE THREAD

**Issue by alepalma** [rlf/uSkyBlock#283]
I cannot use the /is create command! It opens up the /island help or howevver you want to call it! It won't let me create an island. And it doesn't seem to be any error on the console when I do /is create, or /is and click on the grass.

Please help!!!
Thank you!!

**Comment by dutchy1001** [comment]
do you have the permission usb.island.* or usb.island.create? OP should be able to anyway. If not there should be an error in console

**Comment by alepalma** [comment]
well now it's working heheh stupid me!

**Comment by dutchy1001** [comment]
no
