### ISSUE TITLE
rename player takes too long time

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#285]
Reported by http://www.spigotmc.org/members/therealmccoy1234.44339/

Error from Player logging in after Name-changing:

http://pastebin.com/UdDwJJBd

then 16 minutes after the player logged in:
[10:39:26 INFO]: Renamed player Cedi9991 to EpicZz in 978.32 seconds

See http://www.spigotmc.org/threads/uskyblock.38300/page-29#post-576041

**Comment by rlf** [comment]
Additionally, the stacktrace reported above, most likely stems from the player actually trying to access uSkyBlock, while the rename is taking place.

**Comment by drtshock** [comment]
Extreme timings on name changes http://www.spigotmc.org/go/timings?url=10477488

Please do not tell me this is Alphachest's fault. That is completely separate from this project.

**Comment by rlf** [comment]
v2.2-HF13d

**Comment by dutchy1001** [comment]
Renamed my name in all the files to pretend I had changed my name

![2015-04-13_11 01 04](https://cloud.githubusercontent.com/assets/5569980/7113543/c0c4d25e-e1cc-11e4-86b9-6dac1a883599.png)
Log from console [here](http://pastebin.com/ndaPuJfD)
This updated all the files in the uSkyblock folder (island, player and uuid.yml)

looks great, but then I did it a second time, same as the first time and got this error in console

Second try [here](http://pastebin.com/VMF869gD)
Third try [here](http://pastebin.com/1x9LLJcc)

Both second and third time didnt give me the message in chat like the first time (It took 0.02 seconds ....).
This updated the player file and the UUID.yml but NOT the island file

The region on the first time wasnt altered (I forgot about that) but on the third time when I did alter it, it didnt update to my new name.

**Comment by rlf** [comment]
The exceptions you got, was caused by you accidentially breaking the data when trying to test it.

```
Caused by: java.lang.IllegalStateException: Member test2002 has a different UUID than CraftPlayer{name=dutchy1001}
        at us.talabrek.ultimateskyblock.island.IslandInfo.renamePlayer(IslandInfo.java:429) ~[?:?]
```
Something that cannot occur in Bukkit (to my knowledge).

**Comment by rlf** [comment]
Acknowledged, nice testing Dutchy

**Comment by dutchy1001** [comment]
your welcome

**Comment by dutchy1001** [comment]
Tested again and now fully working with v2.3-HF2f
