### ISSUE TITLE
delete issue when player is on island or offline

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#288]
When deleting an island while the player is still on it it will kick the player for flying. After relog in the player falls in the void. and dies.
When deleting an island while player is offline and last location is on the island player falls in the void and dies.

**Comment by rlf** [comment]
Fixed in v2.2-HF12c.
Online players will get send to spawn when removed from an island (or the island is deleted).
Offline players will get send to spawn, when they login to the skyworld, without an island, and flying.

**Comment by dutchy1001** [comment]
online remove from island will send to spawn, Fixed
online delete will kick for flying after loggin will spawn at skyworld falling to void
offline delete, after loggin will spawn at skyworld falling to void
(tested with HF13e)

**Comment by rlf** [comment]
Might be performance intensive for large servers (keep an eye on @mcraftpete)

**Comment by dutchy1001** [comment]
When removing a party member while online he/she will be teleported to spawn, which is OK.

When removing a party member while offline the party member will stay on the island as visitor (but cant break block or open chests) after the next login, which is fine too by me.

When the island is deleted while the party member is offline, he/she falls to the void on the next login.
* this also adds some strange issue. The original location of the owner of the deleted island will now not be able to have the same location as that is now set to the "party member". This party member can still do "/island home" command or use the GUI for it and then will be teleported to the deleted island but will fall to the void (due to no island there now) again. The player file tells us that party member "has" an island while the "orphan.yml" has the same location to create a new island. The party member can then execute the command "/is restart" and an island will be created at the old location.

**Comment by rlf** [comment]
I think we need to "revisit" what the `/usb island` manipulation commands does and what they should do.

Currently, the `/usb island delete` doesn't "kick-out" members, it simply removes the island.
I think the idea (originally) was, that if someone had cheated in some way, you could "clean-out" the island, and then paste in an old one, without having to mess with the party-configuration etc. But I doubt that will work now anyway.

So, the `/usb island delete` should basically do a remove on each members first, then a deleteIsland.
