### ISSUE TITLE
Teleport delay

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#289]
When players do /island home command they are instantly teleported to the island home location. This way players can avoid death due falling of an island or in any other situation that will damage the player.
To avoid this "cheating" a delay in teleport would be an option. A config option would be the best so server owners can deside to leave it on or off.

**Comment by DogsPaw** [comment]
Essentials does this. Just saying if you want a quicker work around.

**Comment by dutchy1001** [comment]
as far I know this doesnt apply for usb

**Comment by rlf** [comment]
`/is spawn`, `/is warp` and `/is home`.

**Comment by wesley27** [comment]
Also needs a permission for administrators, for whom the delay will not take effect

**Comment by rlf** [comment]
We already have one (that might be re-usable); `usb.mod.bypassprotection`

**Comment by dutchy1001** [comment]
Teleport delay works, but the calculation is way off. I set it to 1 (thinking this is seconds) but it took about 50 seconds before i got teleported to the island.

**Comment by rlf** [comment]
Most likely, wesley forgot that the "Bukkit-timers" counts in ticks (20 ticks per second), instead of seconds...

**Comment by dutchy1001** [comment]
Timer is fixed in v2.3-HF2b
