### ISSUE TITLE
Extraordinary tick expenditure for uSkyBlock

### ISSUE THREAD

**Issue by Jimpachnet** [rlf/uSkyBlock#290]
It looks like uSkyBlock spents too much ticks on e.g. the  OnPlayerInteractEvent. Is there a possibility to improve the performance? http://fs1.directupload.net/images/150227/ydwr436o.jpg show

**Comment by DogsPaw** [comment]
Someone opened something like this awhile ago which I can't find. It wasn't a big deal for me until I hit 70 players. USkyBlock went up to 400% in some player ticks.

One of the things they said you could try is changing the top ten refresh from 20 to 0.

**Comment by rlf** [comment]
The top-ten refresh is tied to some other events - not the 4 mentioned in the above post.
We do our best to keep uSkyBlock performant - and will try to look into whether those can be improved - but we most likely need more info, since we are not seeing the same issue in our test-environment.

**Comment by rlf** [comment]
Btw. 2 of those PlayerNameChange is related to #231

**Comment by DogsPaw** [comment]
http://timings.aikar.co/?url=10362012
http://timings.aikar.co/?url=10361375

I didn't really notice a heavy hit on the Server though. No one was complaining of Lag, I wasn't having any lag. As you can possible see from the Timings, I run no AntiLag plugins. Since you guys don't see anything on your testing rigs, might as well give you any information I can get from what I see.

**Comment by rlf** [comment]
The above commit tries to address this issue.
It is - however - not easily done - nor guaranteed to work.

Please retest with v2.2-HF13c - and let me know how it performs.

*Note:* The above fix, will invalidate any island-bans the player had before the name-change, unless you run `/usb import update-islands` first.

**Comment by dutchy1001** [comment]
there have been many improvements made over the last 2 months.
The new pre release v2.3HF6 works a lot better sinse the time this issue was made.
If this still is an issue let us know. Closing this for now
