### ISSUE TITLE
purge calculation erratic

### ISSUE THREAD

**Issue by woolwind** [rlf/uSkyBlock#291]
I've been testing with a copy of my world. I  tested purge with increasingly larger argument for number of days. I expected the number of islands identified to purge to go down as the required days of inactivity increases, but ... not so much.

I unpacked the tarball freshly before each test, so it is starting with the same world state.  I started the world in October so there are no islands with more than 200 days inactivity. Running uSkyBlock v2.2-HF9b

>dev purge 30
[20:31:39 INFO]: Marking all islands inactive for more than 30 days.
[20:32:23 INFO]: [uSkyBlock] Done scanning - found 304 candidates for purging.

>dev purge 60
[20:37:08 INFO]: Marking all islands inactive for more than 60 days.
[20:37:57 INFO]: [uSkyBlock] Done scanning - found 254 candidates for purging.
[
>dev purge 200
[21:01:41 INFO]: Marking all islands inactive for more than 200 days.
[21:02:30 INFO]: [uSkyBlock] Done scanning - found 302 candidates for purging.

>dev purge 300
[21:05:29 INFO]: Marking all islands inactive for more than 300 days.
[21:06:17 INFO]: [uSkyBlock] Done scanning - found 299 candidates for purging.

**Comment by rlf** [comment]
See #243

**Comment by woolwind** [comment]
I did see it, and it looked like it was about different issues. My purges did in fact work correctly, best I could tell. islands removed, island files deleted.

**Comment by rlf** [comment]
We think so, since we are seeing extreme responsetimes of that call at times.

**Comment by woolwind** [comment]
I've redone the purgescan for my own system to check file timestamp (instead of getLastPlayed()) of the island and all the players and also be sure to check the leader if they aren't listed as a member as happens in older islands. It is behaving as I expect it to on my system. Let me know if you want a pull request for it.

**Comment by rlf** [comment]
By all means - pull request! (less tedious work for me)

**Comment by woolwind** [comment]
When I tried it on our real server, i found that something had gone in and touched the timestamps on the island files just the other day, so I had to modify it to rely only on player file timestamps. Works fine, so I'll push that version.

**Comment by dutchy1001** [comment]
With the updated purge system in v2.4.5 is there any improvement for bigger servers? As our test server only have a limited amount of island I would like to hear from the original poster plz
