### ISSUE TITLE
/is top issue

### ISSUE THREAD

**Issue by Disorbs** [rlf/uSkyBlock#295]
So I've said this before but seems to be ignored or missed but my /is top
list looks really messy when you have "8 party" enabled and it showing
the entire Island Members with their Ranks and Nicks like shown below and i was
wondering if you can add an option to only Show the Island Leader on the
/is top and no Nicks/Ranks showing like the old Version unless its something
on my end then please let me know what it could be, thanks

how it looks:
http://i.gyazo.com/2fbe1160255a4ec04afb35147333bd57.png

**Comment by rlf** [comment]
Fixed in v2.2-HF13d - just change the value of the new config.yml setting (`topTenShowMembers`)

**Comment by dutchy1001** [comment]
not working in test (HF13e), tried /usb reload and server restart.

**Comment by rlf** [comment]
Did you get this working in v2.3 dutchy?

**Comment by rlf** [comment]
Also @Disorbs  - consider setting the useDisplayNames (https://github.com/rlf/uSkyBlock/blob/master/src/main/resources/config.yml#L158) to false - that way, the top-ten will not have all those LONG names displayed.

**Comment by dutchy1001** [comment]
yes, working fine now in v2.3

**Comment by Disorbs** [comment]
useDisplayNames is set to false tho?

**Comment by dutchy1001** [comment]
topTenShowMembers: false - doesnt show any party members
topTenShowMembers: true - shows party members

useDisplayNames: false - shows the prefix/suffixes with color and the displayname in yellow;
useDisplayNames : true - doesnt show ant prefix/suffix and the displayname in yellow;

**Comment by dutchy1001** [comment]
I close this as all options are now working as it should and I see no further issue in this.
