### ISSUE TITLE
Cant create island

### ISSUE THREAD

**Issue by Ghisted** [rlf/uSkyBlock#296]
When i do /island create it says an internal error has occurred. Also if you could please skype me about this issue it'd make it much easier for me: Ghisted1

**Comment by wesley27** [comment]
Can you give us a stacktrace from the console? Pastebin the errors that come up?

**Comment by dutchy1001** [comment]
You can also have a quick read [here](https://github.com/rlf/uSkyBlock/wiki#how-to-post-an-issue) please

**Comment by rlf** [comment]
@Ghisted I've seen your messages - don't ever PM anyone with an issue - this is the right approach - might as well dip into the community for feedback/help/discussion - might also help someone else this way.

**Comment by Ghisted** [comment]
World Guard, World Edit, and Vault are fully updated. When im in the server I do /island create and it says I do not have permission to use that command. When I do that same command in the console It only shows this: http://pastebin.com/Q9Kfdy4V

**Comment by dutchy1001** [comment]
If you cant give us version numbers we cant help. 
Sharing you log as above is really not helping as the info we need is in the other lines above and below that line.
Either post a FULL serverlog from start to error or I close this issue.

**Comment by Ghisted** [comment]
I'm not going to deal with this im just switching skyblock plugins

**Comment by dutchy1001** [comment]
I'm sorry you feel this way but what you expect us to do? To get help you have to share information or we cant help as simple as.

**Comment by Ghisted** [comment]
"Also if you could please skype me about this issue it'd make it much easier for me: Ghisted1"
If you would just do that I could explain much better.

**Comment by dutchy1001** [comment]
Why is it so difficult just to list the info we ask? 
We spend our free time to help many server owners that can provide info we need. 
Every server is different and that's the reason why we need the info, this is also a chech so we know you have the right plugins and versions (telling us we use "the latest" is not valid as many plugins can get updated hours earlier of posting)

PS. I dont care if a server is in offline mode or online mode, this not for us to judge on.

I'm sorry but i only use skype for my family.

**Comment by xtoolbearx** [comment]
ok can someone help me with this same issue
uskyblock version - v 2.3
Minecraft version - 1.8.1
Spigot version - c3c767f-33de3
vault version - 1.5.2-b33
Worldedit version - 5.6

same issue as listed I type /is create and it says internal error has occurred please help...

**Comment by Ghisted** [comment]
What I did was look for the latest build for vault WE and WG and updated to that then it started working

-----Original Message-----
