### ISSUE TITLE
Not creating Config Files

### ISSUE THREAD

**Issue by xtoolbearx** [rlf/uSkyBlock#297]
I place the jar into my plugins and reload but it does not create the config folders and does not work in-game

**Comment by wesley27** [comment]
When you say "reload," do you mean you are typing /reload on your server console? If so, that's the problem. You need to actually stop your server and restart it to generate and load the plugin.

If you are restarting it, are there any errors in your console or server log? If so, please pastebin them and show us.

**Comment by dutchy1001** [comment]
You can also have a quick read [here](https://github.com/rlf/uSkyBlock/wiki#how-to-post-an-issue) please

**Comment by dutchy1001** [comment]
No input for a while, solved I supose.
