### ISSUE TITLE
Support UUID

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#3]
Currently, the uSkyBlock plugin doesn't correctly handle players.
Too many places rely on the username, instead of the UUID.

This should be fixed.

**Comment by rlf** [comment]
Fixed in RC1.60 - Our strategy for UUID is ... creative.

**Comment by dutchy1001** [comment]
This can be testen when we can change usernames.

**Comment by TheOnlyRealTGS** [comment]
Hi, name changing is tomorrow, and it seems like you're still storing player files as their names - does USB fully support UUIDS? 
You can also see a players name history using the mojang api: http://wiki.vg/Mojang_API

**Comment by rlf** [comment]
Yes, we think so :) (#227 aside that is)

**Comment by TheOnlyRealTGS** [comment]
Nice, I can confirm this ticket can be closed :)

**Comment by TheOnlyRealTGS** [comment]
Actually wait, is this error important? http://pastebin.com/xZ2nuutd

**Comment by rlf** [comment]
I would say - not much we can do about it - since it seems to be Bukkit that has trouble coping with the Bukkit.getOfflinePlayer(String) method...
But since it can happen - we should probably handle it.

**Comment by TheOnlyRealTGS** [comment]
Okay

**Comment by dutchy1001** [comment]
Think the UUID is working now so closing this
