### ISSUE TITLE
[i18n] Configurable Language aka i18n aka Localization

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#30]
Many have asked to add language files.
I do like this idea to be added but at a later stage.
Low priority

**Comment by Kalorte** [comment]
<3

**Comment by rlf** [comment]
Starting to look into this now - will develop this on the i18n branch, based on GNU gettext.

**Comment by EvilOlaf** [comment]
Looking forward for this.

**Comment by rlf** [comment]
We have an initial version on the i18n branch - but we are currently looking into improving the translation process. Esp. reg. challenges and UI menus.

**Comment by rlf** [comment]
i18n is now supported.
But we still need to document how to do it.

Take a look at the keys.pot and the da.po files in the repository.

**Comment by Zendrex** [comment]
Any details/documentation on how to edit keys.pot and da.po properly. Im still relatively new to plugin development so re-compiling this plugin is a bit more tricky then other more simple ones for me. :P

**Comment by rlf** [comment]
I know - and I apologize - the complexity of compiling this plugin is introduced by using GNU Gettext for supporting translations.

It's a far better alternative to almost every other there exists out there - but it comes at a cost.

If you google "po" "mo" and "gettext" editors, you should get a fair amount of suitable options.

Compiling in a Linux environment is piece of cake - but in a Windows environment takes some tweaking.

**Comment by ArtSolist** [comment]
Hi ) Help me , I'm from Ukraine . After the transfer of the file keys.pot, where it needs to be put ? Do you have a manual for the localization of your plugin ?

**Comment by rlf** [comment]
Unfortunately no, we are still working on it.

**Comment by dutchy1001** [comment]
Non of the added languages are showing on my screen, no errors in console

Changed the config to the different language options we have with no luck.
Using  v2.3-HF4b

**Comment by dutchy1001** [comment]
The i18n system is now fully working
