### ISSUE TITLE
B Listed as an Alias for Banning

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#303]
B is allocated to biome changing, but listed under banning as well under the command list.

Also, I don't feel like opening a new issue for it, but I feel like /is biome <biome> should spit out an error if an invalid biome is typed in.

**Comment by rlf** [comment]
https://github.com/rlf/uSkyBlock/releases/tag/v2.3-HF1a

Ignoring the biome comment - that "functionality" seems to have been that way for ages.

**Comment by dutchy1001** [comment]
B is used for biome, trying to use /is b name isnt working.

issue fixes
