### ISSUE TITLE
"Flexible" Config Files

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#305]
Since open issues are supposed to represent a to-do list, I decided to include this on here. Even though I know you have this in the back of your mind, I submitted this anyway. Basically, this is the highly-awaited option of the time when we will no longer have to regenerate and manually copy over existing config files in order to update the jar. This is top priority and it will make everyone's lives 1000 times easier as soon as it's added.

**Comment by wesley27** [comment]
Regen and merge existing config files with new, updated ones.

**Comment by dutchy1001** [comment]
As I have discuss this with rlf a while back, the reason some configs are regenerated are due to some limitation on bukkit's side. 
For this reason the backup folder is created so nothing will be lost while doing an update.

**Comment by rlf** [comment]
Well, you wrote a lot, but you still failed to convey exactly what you'd like?

We currently have a rathter flexible config-file system (compared to Bukkit-default) at least.

a) We "merge" the existing config files (challenges, config) with the ones we provide (the existing settings win).
b) We "backup" existing into the `backup` folder.
c) We "overwrite/force" the levelConfig (as the only one) to ensure we can tweak stuff.

What exactly are you missing in this setup?

**Comment by rlf** [comment]
https://github.com/rlf/uSkyBlock/releases/tag/v2.3-HF1a

**Comment by TheMattVid** [comment]
I was just referring to the ability to update a jar file without having to manually transfer over the config files line by line. Maybe I'm out of the loop, but I assumed that this still needed to be added, since the homepage still said this in regard to config files:

"Note: Config files might change quite a bit, so before installing the plugin, please move existing config files aside, and manually merge them after the plugin has "installed" it's own versions.

We are working on a feature, that will do this automatically - but until that is released, please follow the above procedure."

I was referring to said feature.

**Comment by dutchy1001** [comment]
The referance you mentioned is atleast a month old, If you had updated every release we did then you would have notest that this was added in previous releases.

**Comment by TheMattVid** [comment]
The homepage that I refer to is https://github.com/rlf/uSkyBlock and it is listed under the "config-files" section. I have not been reading the descriptions to every update, so I did not realize this was implemented, so please understand my lack of knowledge regarding this topic. If this works properly, then I suppose this may be closed.
