### ISSUE TITLE
Null Error on /is warp

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#308]
This is a null error that resulted from someone trying the command /is warp. I assume the problem is because a player name wasn't specified.
http://pastebin.com/bByrPjUE

I don't think it causes any issues, but I assume that anything that causes a string of errors should be reported.

**Comment by rlf** [comment]
Sounds like an old bug. Sorry to ask you this again, but what version are you using?

**Comment by rlf** [comment]
Duplicate of #300

**Comment by TheMattVid** [comment]
V2.3 from 8 days ago. I guess that's considered slightly outdated. I thought this sounded very different from #300, but if the root of the issue is the same, glad to see it is fixed.

**Comment by dutchy1001** [comment]
this should be fixed with the latest build
