### ISSUE TITLE
Eastern-most row of blocks didn't reset on a mega island

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#309]
I have a guy who made a mega island reset it. The eastern-most row of those blocks did not get included in the reset, even though they are in the island protection region before and after the reset. If you don't believe me, I have a screenshot. I am too busy to post it now, but I will provide it upon request.

**Comment by rlf** [comment]
Only a 1 block wide row?

**Comment by rlf** [comment]
Reproduced this - will fix while fixing the `/is restart` issue.

**Comment by dutchy1001** [comment]
restarts clearing region now, just takes a bit more time depending on the size of the island (which I can live with).

**Comment by dutchy1001** [comment]
this is fixed in v2.3-HF2b

If there are still block a relog or world tp will fix this.
