### ISSUE TITLE
/is level dosn't recalculate island level

### ISSUE THREAD

**Issue by Belegalgar** [rlf/uSkyBlock#311]
Greetings,

I've an issue with /is level command.

server: spigot 1.8.3 ( This server is running CraftBukkit version git-Spigot-529ff99-7f52bd6 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT) )
uSkyBlock: [uSkyBlock] Loading uSkyBlock v2.3-HF1a
WorldEdit: [WorldEdit] Loading WorldEdit v6.0.2-SNAPSHOT;3364-1209e484
WorldGuard: [WorldGuard] Loading WorldGuard v6.0.0-SNAPSHOT.1584-
Vault: [Vault] Loading Vault v1.5.3-b37

If I run /is level my island level isn't recalculated (even if I have usb.admin.island). I will always get the "old" island level from config.

If I want to know my island level I have to do /is info which works fine.

Maybe this is caused due to separation of /is info and /is level in

https://github.com/rlf/uSkyBlock/blob/60ea2ff05db817b3dae4abde5d20f2bb042995bb/src/main/java/us/talabrek/ultimateskyblock/command/island/LevelCommand.java

Specially removing

IslandScore score = plugin.recalculateScore(player, playerInfo.locationForParty());

after

        if (shouldRecalculate) {
            plugin.getServer().getScheduler().runTaskLater(plugin, new Runnable() {
                @Override
                public void run() {
                    try {

After re-adding the line back to the code /is level just updates fine again.

                @Override
                public void run() {
                    try {
                    	IslandScore score = plugin.recalculateScore(player, playerInfo.locationForParty());                    	
                        plugin.fireChangeEvent(new uSkyBlockEvent(player, plugin, uSkyBlockEvent.Cause.RANK_UPDATED));
                    } catch (Exception e) {
                        uSkyBlock.log(Level.SEVERE, "Error while calculating Island Level", e);
                    }
                    plugin.getServer().getScheduler().scheduleSyncDelayedTask(plugin, showInfo, 10L);
                }

**Comment by rlf** [comment]
Sounds likely

**Comment by manercraft** [comment]
Please fix /is level
Beacause /is info = freeze, rollback, lag

**Comment by wesley27** [comment]
@Belegalgar So are you saying that you added the last code you posted in to your issue, to the if (shouldRecalculate) clause in the LevelCommand.java? And this fixed it? Please let me know.

That would be interesting, as the level command alone never had that method exact clause, that clause was part of the info command and was moved over to the new InfoCommand file.

**Comment by Belegalgar** [comment]
I've only readded one line:

IslandScore score = plugin.recalculateScore(player, playerInfo.locationForParty());

full method is:

    public boolean getIslandLevel(final Player player, final String islandPlayer, final String cmd) {
        PlayerInfo info = plugin.getPlayerInfo(islandPlayer);
        if (info == null || !info.getHasIsland() && !plugin.getIslandInfo(info).isParty()) {
            player.sendMessage("\u00a74That player is invalid or does not have an island!");
            return false;
        }
        final PlayerInfo playerInfo = islandPlayer.equals(player.getName()) ? plugin.getPlayerInfo(player) : plugin.getPlayerInfo(islandPlayer);
        final boolean shouldRecalculate = player.getName().equals(playerInfo.getPlayerName()) || player.hasPermission("usb.admin.island");
        if (shouldRecalculate) {
            plugin.getIslandLogic().loadIslandChunks(playerInfo.getIslandLocation(), Settings.island_radius);
        }
        final Runnable showInfo = new Runnable() {
            @Override
            public void run() {
                if (player.isOnline()) {
                    player.sendMessage("\u00a7eInformation about " + islandPlayer + "'s Island:");
                    if (cmd.equalsIgnoreCase("level")) {
                        player.sendMessage(String.format("\u00a7aIsland level is %5.2f", plugin.getIslandInfo(playerInfo).getLevel()));
                    }
                }
            }
        };
        if (shouldRecalculate) {
            plugin.getServer().getScheduler().runTaskLater(plugin, new Runnable() {
                @Override
                public void run() {
                    try {
                    	IslandScore score = plugin.recalculateScore(player, playerInfo.locationForParty());                    	
                        plugin.fireChangeEvent(new uSkyBlockEvent(player, plugin, uSkyBlockEvent.Cause.RANK_UPDATED));
                    } catch (Exception e) {
                        uSkyBlock.log(Level.SEVERE, "Error while calculating Island Level", e);
                    }
                    plugin.getServer().getScheduler().scheduleSyncDelayedTask(plugin, showInfo, 10L);
                }
            }, 1L);
        } else {
            showInfo.run();
        }
        return true;
    }

Now island level/sore is always recalculated if the island owner uses /is level.
Bevor island level only updates when player uses /is info.

**Comment by wesley27** [comment]
Okay, was just making sure that's what I thought you said. Nice of you to report the bug and fix it for us :)

**Comment by manercraft** [comment]
@wesley27 
The releases to remove bugs come quickly?

**Comment by wesley27** [comment]
@manercraft Usuaully, this one will be fixed in a minute.

**Comment by wesley27** [comment]
Ready to test, but as tested by reporter should be working; fixed.

**Comment by manercraft** [comment]
@wesley27 
I download that?
Can give me a link?
Sorry, but I know not well github
