### ISSUE TITLE
Config option to limit protection to player island regions.

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#312]
Would be great to have an option in the configuration to disable built-in skyblock protections in regions that are not player islands. Having a PvP arena, mob arena, etc. in the same world can be tricky at the moment and generally requires disabling certain types of protection like mob damage.

**Comment by rlf** [comment]
We currently have 2 sort of "protections", one that checks that you are on your own island (i.e. allowing creepers to explode, killing animals etc.), and one that protects you when you are visitor on anothers island (blocking fire/projectile/mob damage).

I guess, if we tweak it a bit, we could "allow all" in the spawn-region, that way, you would be able to make your arenas withing the spawnSize.

**Comment by wesley27** [comment]
You could also have a separate world for your spawn and your skyblock islands; this is how I do it. In my opinion it's easier to have all the islands in one place and all the server parts in another, that way they never clash.

**Comment by rlf** [comment]
Too complex, and not a core-feature of the uSkyBlock plugin - closing it for now.
