### ISSUE TITLE
New Player Creates island - already member at island that cant kick

### ISSUE THREAD

**Issue by mcraftpete** [rlf/uSkyBlock#313]
Basically `sometimes` a new player to server joins and creates an island , on an odd occasion on creating there is already another player `added` to there island and not someone they added , like they already existed , I can confirm by doing /seen the player doesn't exist as we reset the /seen to only show players from last 3 months active , so this mysterious player has been added , sometimes you can /is kick and it will remove and sometimes /is kick gives 'an internal error has occurred' ,leaving new player with someone else on island they cant remove  same as cant restart or leave or join someone elses they are literally stuck , I have been getting a few of these lately and could show you the island info and player data of players this happened to if it helps , but I got feeling its just data and wont reveal much , do you have any clue what could cause it ?
I would add that when I look in the `mysterious` players player folder it says hasisland:true and the location is the same location as the new player that created the island.
I can post more information as I discover it , I do have quite a few players experiencing this and it seems to be mostly new players joining.

**Comment by mcraftpete** [comment]
Just to add that I can do /region info where the island is and can see the 2 players , I attempted to do /region removeowner islandname username  to see if I could get the old player of the region and then adjust the island and player folders but I receive a wg error `Failed to remove owners: Unable to resolve the names braddeath21'  which I would say is likely to be why island kick doesn't work on this player the command is likely failing when it gets to the region , I cant puzzle why a player cannot be removed from a region like this , the player brandeath21 is the mysterious player that likely used the server a long time ago but not recently in the last 3 months.

**Comment by rlf** [comment]
Might be an issue with WG then.
Does the server-log give any clues?

**Comment by rlf** [comment]
Also, sounds like a purge of player-files are in order... But don't do it until you have v2.3-HF1

**Comment by mcraftpete** [comment]
I didn't see anything in the logs , I will wait until server not so busy tomorrow and upgrade 2o v2.3HF1a , is a the right one as its the only 1 I think I could see ?

**Comment by rlf** [comment]
Sounds right.

**Comment by mcraftpete** [comment]
ok so I now have v2.3 must be HF1 but doesn't say but I can see a pre-release HF1a but didn't use that one , so after restart I immediately see a player try to kick another from their island , I quickly went to island to see as you can get much detail from /is info player except blocks etc , I see the player didn't kick from the island I was using commandspy and player definitely typed it correctly , player logged out I assume after realizing they couldn't kick the player so I checked the island from island folder and the player trying to kick was leader and can kick was true but player definitely didn't kick, was still in wg and island data.
I can only see further as and when players try to do kicks so am watching commandspy and will update more as I see it , I see another player use makeleader and then leaving their island so must of worked.

**Comment by rlf** [comment]
In-game, `/usb island info <name>` should show some extended info about the island.

**Comment by mcraftpete** [comment]
ee the details so that player definitely wasn`t kicked , I updated to the V2.3 HF1a just to be sure and seen another kick attempt since which also failed , I think the ppl that are trying kicks are ones that have `rogue` players listed on their islands , a purge may be a good thing to try , so it will remove their player data , any islands they belong to , wg regions added to and if last 1 on island delete the island ? What will happen if a player is part of 2 islands for instance which I have seen which must have been bugged from previous versions before you took over

**Comment by rlf** [comment]
Not sure.

Wait with the purge - I think it will actually try to delete the islands. And not what you want.

Perhaps we need a new feature here... a "remove all members + player-files older than X" - instead of the island.

**Comment by mcraftpete** [comment]
ok , do new islands auto form to the closest location  ? if so will there be a way to delete the islands at some point ? Allowing that the map is getting bigger and bigger im not sure what the limits are here ?
Do you mean to literally leave the islands where they are and just delete the player data , so there would be no way to remove these and possible regions at later date or will it remove wg at time of player removal ?

**Comment by rlf** [comment]
It sounds like your data is severely fubared. Esp. the way that players are registered as part of existing islands. Can you post (pastebin) the island and the WG-region for one of the islands with a "wrong-player" added to the island?

**Comment by mcraftpete** [comment]
player to do this I now have 1 , I cant puzzle it out myself but it is what it is.
beamng was new player to server , never been on before and created himself an island , on creation it had 2 other players already listed as members nateybob5 and pigs_domain , nateybob5 has not been on server for more then 6 months pigs_domain was on 2 days earlier but already had his own island.
beamng  : http://pastebin.com/Jt3PkSNT
nateybob5 : http://pastebin.com/wk3aY5rf
pigs_domain : http://pastebin.com/QBtCYRtA
island 7260,-5390 : http://pastebin.com/4GSGDqEG
island 4730,-990 : http://pastebin.com/UFiu9rBU

This has happened to mostly new players , as you will see pigs_domain is on 2 islands , have no clue what relation he has to the new beamng island tohave been added to it.
Let me know what other information you need :)

**Comment by dutchy1001** [comment]
Have you done a purge before with a previous version?
Have a check into your "orphan.yml" if there are islands listed and a new player is getting one of those allocated, it might be that when on that "old" island location "members" are still listed in a region file that should have been deleted.

Compare some of those islands in the orphan.yml and the "WorldGuard" regions if they still exist. This might be a big job if not all regions are updated to the co-ords format to find out wich island belongs to what region.

If any of the region files still exist from the "orphan.yml" it will update the region to the new player but will keep the already existing members (these regions should be deleted then).

**Comment by mcraftpete** [comment]
Hi,
Yes we attempted a purge when you came to my server but stopped it as it didn't seem to work , I checked orphans.yml and this is empty.
lastisland config is this..
options:
  general:
    lastIslandX: 5390
    lastIslandZ: 8250
Its pretty tricky and as you know our database is large , I was wondering if there would be a way to look for members that are in more then 1 island , this might help some , as I am pretty sure each tiem we have this the player that is added to new island already has another.

**Comment by dutchy1001** [comment]
it was a shot that wasnt mentioned yet. Unfortunattely not the case.

**Comment by rlf** [comment]
Given the other issues you are having @mcraftpete , I'd say we need some better tools for diagnosing your condition.
I fear what we are seeing is just symptoms popping up, of some sort of "data-corruption" in the uSkyBlock data-model on your server.

Since we still haven't made a SQL solution, all data is stored in yml-files, and the "referential integrity" of these can quite easily be broken, esp. when a lot of stuff is going on.

Let's hope we can diagnose it, and perhaps even fix it when we get some better #193 tools.

**Comment by dutchy1001** [comment]
no further input or signs of this happening again
