### ISSUE TITLE
Internal error has occurred when /is create typed 

### ISSUE THREAD

**Issue by xtoolbearx** [rlf/uSkyBlock#316]
uskyblock version - v 2.3
Minecraft version - 1.8.1
Spigot version - c3c767f-33de3
vault version - 1.5.2-b33
Worldedit version - 5.6

I type /is create and it says internal error has occurred please help...

**Comment by dutchy1001** [comment]
Update WE to v6, no mention of WorldGuard

**Comment by xtoolbearx** [comment]
WorldGuard Version 5.9 il try updating world edit

**Comment by xtoolbearx** [comment]
its still giving the error

**Comment by dutchy1001** [comment]
Use v6 for both versions, don't mix v5 and v6, or it will error everytime.

**Comment by xtoolbearx** [comment]
this will sound stupid but i cant find version 6 of worldguard only 5.9

**Comment by xtoolbearx** [comment]
never mind found it

**Comment by xtoolbearx** [comment]
I think now im having a worldguard issue can you still help its not working at all

**Comment by xtoolbearx** [comment]
ok its all working now

**Comment by dutchy1001** [comment]
Extracting the worldgaurd jar is not good as you will break ot then. You can download the WorldGuard  package in RAR format and that needs to be extracted so the jar can be used. If you just download the jar from [here](http://builds.enginehub.org/job/worldguard?branch=master) there is nothing to extract, just copy past it into your plugins folder.

**Comment by xtoolbearx** [comment]
whoops sorry that's what i meant lol
