### ISSUE TITLE
Challenges: resetInHours

### ISSUE THREAD

**Issue by Belegalgar** [rlf/uSkyBlock#317]
Greetings,

we have a problem with resetInHours option in Challenges.

server: spigot 1.8.3 ( This server is running CraftBukkit version git-Spigot-529ff99-7f52bd6 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT) )
uSkyBlock: [uSkyBlock] Loading uSkyBlock v2.3-HF1a
WorldEdit: [WorldEdit] Loading WorldEdit v6.0.2-SNAPSHOT;3364-1209e484
WorldGuard: [WorldGuard] Loading WorldGuard v6.0.0-SNAPSHOT.1584-
Vault: [Vault] Loading Vault v1.5.3-b37

In /c GUI tool-tip shows correctly: Repeatable in X hours...
BUT if a player use /c c <challenge> challenge will complete anyway (if the player has all required items).

In method tryCompleteOnPlayer of class ChallengeLogic i can't see any logic which checks resetInHours - or do i miss sth. ?

    private boolean tryCompleteOnPlayer(Player player, String challengeName) {
        Challenge challenge = getChallenge(challengeName);
        PlayerInfo playerInfo = skyBlock.getPlayerInfo(player);
        ChallengeCompletion completion = playerInfo.getChallenge(challengeName);
        if (challenge != null && completion != null) {
            StringBuilder sb = new StringBuilder();
            boolean hasAll = true;
            List<ItemStack> requiredItems = challenge.getRequiredItems(completion.getTimesCompletedSinceTimer());
            for (ItemStack required : requiredItems) {
                required.setItemMeta(null);
                if (!player.getInventory().containsAtLeast(required, required.getAmount())) {
                    sb.append(" \u00a74" + (required.getAmount() - getCountOf(player.getInventory(), required))
                            + " \u00a7b" + VaultHandler.getItemName(required));
                    hasAll = false;
                }
            }
            if (hasAll) {
                if (challenge.isTakeItems()) {
                    player.getInventory().removeItem(requiredItems.toArray(new ItemStack[requiredItems.size()]));
                }
                giveReward(player, challenge);
                return true;
            } else {
                player.sendMessage("\u00a7eYou are the following items short:" + sb.toString());
            }
        }
        return true;
    }

(sorry, currently i haven't tried to fix this. perhaps checking with completion.isOnCooldown() with return false and a message to the player after

    ChallengeCompletion completion = playerInfo.getChallenge(challengeName);

could provide a fix.)

**Comment by rlf** [comment]
It's a common mistake, the reset isn't the time until the challenge can be completed again, it's the time until the challenge can be completed again __with the lower amount of items__.

I.e. you can complete repeatable challenges multiple times, but it will require more and more items.
