### ISSUE TITLE
Ticks

### ISSUE THREAD

**Issue by darkdragonxxxx** [rlf/uSkyBlock#318]
Some things causing a lot of crash's for some players near the players causing these things (challenges and making a new island). http://prntscr.com/6hqfcv

**Comment by dutchy1001** [comment]
can you give a list of dependend plugin list and version numbers (use the command "/usb version") and plz dont use "I have the latest"

**Comment by darkdragonxxxx** [comment]
http://prntscr.com/6i4t87
http://prntscr.com/6i4tbr

**Comment by dutchy1001** [comment]
update your Vault to 1.5.x

**Comment by darkdragonxxxx** [comment]
http://prntscr.com/6iab3b
http://prntscr.com/6iabac
I did /restart

**Comment by dutchy1001** [comment]
plz post a full log of the console print from a full restart (stop server and then restart). Both tiny pics is very unclear as they are 2 different versions.

**Comment by darkdragonxxxx** [comment]
Looks like it's fixed now.
New thing though, If there isn't a way to do this could there be one please.
I want to have hostile mobs enabled but creepers keep exploding so could you add a config to disable this please.

**Comment by DogsPaw** [comment]
WorldGuard/Essentials can do that.

**Comment by rlf** [comment]
Closing this for now.
