### ISSUE TITLE
Unable to use uSkyblock with spigot 1.8.3

### ISSUE THREAD

**Issue by fatdog66** [rlf/uSkyBlock#319]
Hi !

I get this error: http://pastebin.com/0skQjEub

/is don't open island menu
/c don't open challenge menu

Plugin not work :(

Version list:

spigot: git-Spigot-beb883d-234e607 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
WE: WorldEdit v6.0.2-SNAPSHOT;3369-2db5d8b1
WG: WorldGuard v6.0.0-SNAPSHOT.1589
Vault: Vault v1.5.3-b37
uSkyblock: Ultimate SkyBlock v2.3-HF1a-7-g2d03c1b-2d03c1-dev (compilled 10 min ago)

Thx for your help

**Comment by rlf** [comment]
Don't compile the plugin your self - you have a non-released version of the plugin, and that doesn't work atm.

**Comment by fatdog66** [comment]
ho, ok. I have tested before compiling with the release and i have the same issue, i return to the release and i retry to solve my problem. Thx
