### ISSUE TITLE
uskyblock gui able to pull out items using ctrl+left click

### ISSUE THREAD

**Issue by bfoxeh** [rlf/uSkyBlock#320]
If you [ctrl]+[left click] on an item in the GUI inventory that represents a button, the item will enter the players inventory essentially giving them unlimited of the represented block.

**Comment by dutchy1001** [comment]
I have tried to replicate this on my test server but what I try it's not giving the items. 

Can you give us details as what versions you use (dont say the latest).

**Comment by bfoxeh** [comment]
Sorry, I found the cause, was a third party mod called inventory tweaks. I disabled it and uskyblock is working awsome.

**Comment by dutchy1001** [comment]
thx for letting us know
