### ISSUE TITLE
Creeper damage configuration per island?

### ISSUE THREAD

**Issue by c0wg0d** [rlf/uSkyBlock#325]
It would be nice if there were an option for players to turn on creeper damage on their island.  Some of our players like more of a challenge, but many do not.

**Comment by dutchy1001** [comment]
These can be set in the config at the "protection" settings

**Comment by c0wg0d** [comment]
Sorry, I forgot about these options.  However, this seems to be a global setting?  Or is it possible for some players to have creeper damage and some not?

**Comment by dutchy1001** [comment]
only a global setting
