### ISSUE TITLE
Lag for top-ten generation

### ISSUE THREAD

**Issue by manercraft** [rlf/uSkyBlock#326]
Hello !
Your plugin uskyblock generate big lag on my server
Timings: http://timings.aikar.co/?url=10643630
Version des plugins: http://prntscr.com/6jiu0l
Please help me :(

**Comment by manercraft** [comment]
Up :(

**Comment by dutchy1001** [comment]
sorry for a late response but our dev's are busy with their real life (school and work) atm, be patients and they will reply.

**Comment by manercraft** [comment]
It was not nasty
Just to know if the problem was known or not ^^

**Comment by dutchy1001** [comment]
didnt say it was, just wanted you to know we didnt ignore your post. :)

**Comment by rlf** [comment]
Seems your server isn't powerful enough to enable periodic top-ten generation.

Make sure `autoRefreshScore` is 0 (https://github.com/rlf/uSkyBlock/blob/master/src/main/resources/config.yml#L83)

Possibly, increase the `topTenTimeout`, and if that fails, disable topTen.

**Comment by rlf** [comment]
Closing this issue, it's related to #247 (will be resolved by that issue).
