### ISSUE TITLE
Issue on build

### ISSUE THREAD

**Issue by Darkool** [rlf/uSkyBlock#327]
Hi i get this error, when I try to build

--- exec-maven-plugin:1.3.2:exec (default) @ uSkyBlock ---
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 21.889s
Finished at: Sun Mar 22 04:23:26 CET 2015
Final Memory: 8M/121M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec (default) on project uSkyBlock: Command execution failed. Cannot run program "git" (in directory "C:\Users\Brayan\Desktop\DESCOMPILADOS\uSkyBlock-master\target"): CreateProcess error=2, El sistema no puede encontrar el archivo especificado -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Using NB 8.0

**Comment by dutchy1001** [comment]
the current build has issue's. Dev's are working on it to add some features. This is the reason you cann't build atm

**Comment by Darkool** [comment]
There is already release date for the new version?

**Comment by dutchy1001** [comment]
A new release will be posted on the Bukkit pages or Spigot when it's ready.
