### ISSUE TITLE
is level

### ISSUE THREAD

**Issue by Disorbs** [rlf/uSkyBlock#328]
so for some reason it looked like it was either changed from /is level to /is info or
/is level just wont update it?, it only updates when doing /is info but most members know
to do /is level is there a way to fix/change this back? thanks

version: 2.3-HF1a

**Comment by Disorbs** [comment]
apperently causes a bit of lag when doing /is info unless its something else

http://timings.aikar.co/?url=10652638

**Comment by dutchy1001** [comment]
the /is level and /is info will be fixed in the next update, we are aware of this already.
See #311

**Comment by dutchy1001** [comment]
closing this as it should be fixed
