### ISSUE TITLE
Changing Biome Type

### ISSUE THREAD

**Issue by Schneiderism** [rlf/uSkyBlock#329]
I'm trying to let players change their islands to certain biome types, but no matter what I try, it always says they can't use the different types. I've tried the permission nodes

- usb.biome."PLAINS"
- usb.biome.PLAINS
and as a last ditch effort:
-usb.biome.*

Despite my efforts, nothing works. What am I doing wrong?

[Edit: It says the biome type is unknown. I copied the biome names from the setup page {http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/commands-and-permissions/} exactly as they are.]

**Comment by dutchy1001** [comment]
Can you tell me what version of USB you use, the dependend plugin versions and the command used to change the biome?

When using Group Manager the node should be:
`- usb.biome.[biomename]` like `- usb.biome.plains` or `- usb.biome.*`
I would not use capital letters, but not sure that would make a differance.

Other perm plugins might do it slightly different.

**Comment by Schneiderism** [comment]
* Using version: 2.3-HF1
* Using command: "/island biome Forest" but I also tried to get it to work through "/island biome" and then clicking the forest item to change it.

**Comment by Schneiderism** [comment]
Anyone have any idea as to what is wrong?

**Comment by dutchy1001** [comment]
I asked what versions you use, so far only 1 you mentioned is the usb version, what about the dependend plugins and spigot?

**Comment by Schneiderism** [comment]
I'm sorry, I misunderstood what you needed. Here you are:

This server is running CraftBukkit version git-Spigot-26dfd01-5cb9b70

Plugins (46): CoreProtect, dynmap, ClockworkPlanter, WorldEdit, HorseStats, Essentials, ClearLag, BetterLeads, Buycraft, LavaFurnace, Chairs, EasyHome, WorldGuard, Brewery, InfiniteDispensersAndDroppers, UUIDChecker, SignEdit, WorldGuard_FlyStop, RottenFlesh2Leather, EssentialsChat, iConomy, PermissionsEx, TreeAssist, OPLock, Vault, CBWrapper, EssentialsSpawn, CustomEnchantments, MassiveCore, ExpBank, ChestShop, SignURLs, InfChests, PlotMe, BackPacks, SilkSpawners, Factions, DynmapPlotMe, PlotMe-DefaultGenerator, Multiverse-Core, Shopkeepers, Multiverse-Inventories, Multiverse-Portals, uSkyBlock, ShowCaseStandalone, Multiverse-NetherPortals

**Comment by dutchy1001** [comment]
maybe read this [section](https://github.com/rlf/uSkyBlock/wiki#how-to-post-an-issue) will clear it up. I didnt ask for all your plugins, just the dependend plugins USB uses and there versions. 

What version is this "git-Spigot-26dfd01-5cb9b70" 1.7/1.8 ??

Use the command "/usb version" to see what versions you have, give me those plz.

**Comment by Schneiderism** [comment]
Sorry for the confusion on my end. Here's what the command returned

Name: uSkyBlock
Version: 2.3-HF1a
Description: Ultimate SkyBlock v2.3-HF1a-2e2dfe-dev

CraftBukkit git-Spigot-26dfd01-5cb9b70 (MC: 1.8.3)

Name: Vault
Version: 1.5.3-b37

Name: WorldEdit
Version: 6.0;3342-78f975b9

Name: WorldGuard
Version: 6.0.0-beta-05.1569

**Comment by dutchy1001** [comment]
So now we can rule out that the plugins are out of date. That leaves then a permission fault in PermissionsEx. 
I will start my own test server and double check this, I use Group-Manager myself , but if you have OP then you should be able to do it on yourt own island, can you check this? Remember players need to go to spawn and back to let the biome take affect.

**Comment by Schneiderism** [comment]
As an OP it still says I can't do it, even though it's my island. You think it may be PEX?

**Comment by dutchy1001** [comment]
As OP you should have all the perms, 

In your first message you said you tried ```-usb.biome.*```, having the - direct at the USB means sometimes to negate, meaning "not allowed" check this if that is corrected. 
You can also try giving yourself ```- usb.*``` (see the space between - and usb).
try this as OP and as normal player. 
Last resort is to send me your server address and I can visit you.(I'm on UK time)

**Comment by Schneiderism** [comment]
The dash being right next to it was a typo, there's a space in my permsissions. If it helps you figure it out any, it gives me this when I try to use the "Change Island Biome" from the '/island" menu [Even as an OP]:
![2015-03-31_15 44 56](https://cloud.githubusercontent.com/assets/11036216/6930980/33bd5796-d7bd-11e4-920a-309e5281ba7c.png)

And this when I try to click on it anyway [Also as an OP]:
![2015-03-31_15 45 17](https://cloud.githubusercontent.com/assets/11036216/6930988/4507e8f4-d7bd-11e4-8f4c-764527f5d768.png)

**Comment by Schneiderism** [comment]
Update: I gave myself the "usb.biome.* " permission node and it finally gave me access to it without OP. However, I don't want them to have access to the biome like Mushroom, but negating it doesn't work right, even when I give the "- -usb.biome.mushroom".  I'll use the wildcard if I need to, but I really don't want them to have the End and Mushroom biomes.

**Comment by dutchy1001** [comment]
atleast your getting somewere now. As i can confirm now that it is most likely a permission problem, just have to find out were. Are there any conflicting nodes maybe?? Can you post the pex config? (use the [bukkit](http://dev.bukkit.org/bukkit-plugins/uskyblock/) PM's if you like)

**Comment by Schneiderism** [comment]
I actually figured it out. It didn't save the negative permission as I had thought. Using the wildcard node and negative permissions, I've gotten it to work. Thank you so much for all your help throughout this endeavor!
