### ISSUE TITLE
onIsland = range 10 blocks

### ISSUE THREAD

**Issue by manercraft** [rlf/uSkyBlock#330]
When one chooses on Island must be in around 10 blocks, possible to add a config rangeblock to put in the challenge to change this? To do all over the island?

**Comment by dutchy1001** [comment]
This can be set in the challenges config. 
If you look in the challenges config (line 560 using notepad++) you see "raduis: 12", change the value to your liking. Incase this isnt on a "onIsland" challange you can add it with a value you like.

**Comment by manercraft** [comment]
Thank !
