### ISSUE TITLE
GUI Does nothing

### ISSUE THREAD

**Issue by aguy867** [rlf/uSkyBlock#331]
Server: Spigot 1.8.0
uSkyblock: uSkyBlock v2.3-HF1a 
Worldedit: 6.0
Worldguard: 6.0
Vault: 1.5.2

When I do /sb, and it opens up the GUI, and click on an item, it does nothing.

**Comment by dutchy1001** [comment]
there are many versions od worldedit/guard that are v6, can you be more specific as with build numbers? Spigot has been updated to 1.8.3 I suggest you do too, Vault is v1.5.3 now

**Comment by rlf** [comment]
It sounds like a permission issue, or perhaps a conflicting plugin.
Do you have a server-log? It might explain what is wrong.

**Comment by rlf** [comment]
No answer from reporter - closing
