### ISSUE TITLE
Convert challenge.yml version 7 in version 8

### ISSUE THREAD

**Issue by manercraft** [rlf/uSkyBlock#332]
Hello, with the update, my challenge.yml has been reset in version 8
I have install an older version of plugin for keep my custom challenge.yml

But I would like to be on the latest version (bug fix), how for convert and keep the actual config ?

**Comment by dutchy1001** [comment]
When updating the challanges.yml will be saved in a backup folder were the configs are. You can copy the challenges back into the updated one, just dont copy the "version" from the old challenges.yml or it will reset again.

**Comment by manercraft** [comment]
Thank :+1: !

**Comment by dutchy1001** [comment]
yw
