### ISSUE TITLE
Linked Nether Portals

### ISSUE THREAD

**Issue by Schneiderism** [rlf/uSkyBlock#333]
Is there a way to make it so nether portals are island-specific? As in my island creates a nether portal that takes me back and forth, but doesn't link up with Joe's portal? Seperate nether islands per say

**Comment by Schneiderism** [comment]
Is there a way to make it so nether portals are island-specific? As in my island creates a nether portal that takes me back and forth, but doesn't link up with Joe's portal? Seperate nether islands per say

**Comment by dutchy1001** [comment]
Have you had a look at this page [here](https://github.com/rlf/uSkyBlock/wiki/Nether-and-uSkyBlock)

**Comment by Schneiderism** [comment]
Does this create a protection zone around the island in the nether

**Comment by dutchy1001** [comment]
It creates a normal nether as you would have for survival, there are no islands there. Portals should be protected by USB so only the island owner or party members can make use of it.
