### ISSUE TITLE
Island region created at spawn

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#334]
uSkyBlock version: v2.3-HF1c-b79d59-dev
Server version: git-Spigot-35348a5-ee6d0fa
Vault version: 1.5.3-b37
WorldEdit version: 6.0.2-SNAPSHOT;3361-173f8323
WorldGuard version: 6.0.0-SNAPSHOT.1590-

Today an island region was created at spawn, removing the spawn region. No island was pasted and nothing at spawn was deleted. The island region was "0,0island".
The player who was given ownership already owned another island. Using "/dev goto <player>" teleported me to their original island. The coordinates in their player file were also for their original island. A second member of the new island region at spawn had no island set in their player file.

Looking in the islands file, I found 3 separate files for "0,0island".
"0,0island.bak" was empty
"0,0.yml.err": http://pastebin.com/raw.php?i=N52es7k7
"0,0.yml": http://pastebin.com/raw.php?i=mThpPwti

My config: http://pastebin.com/raw.php?i=0WsWGFYA
The new region owner's player file: http://pastebin.com/raw.php?i=gSaRvgAQ

Looking at my logs, it seems this happened right after I reset my nether and end worlds. Not sure if that could have anything to do with it. Here's what I found in the log that seems like it could have caused the issue: http://pastebin.com/raw.php?i=UC7MFSvV

**Comment by rlf** [comment]
Sounds like, somehow, the player managed to fire an `/is restart` before his data was fully loaded.

A "fix" would be to just block `/is restart` when this happens...

**Comment by dutchy1001** [comment]
Is this still an issue or was it a 1 time error? As no further is known about it and not has happend again I assume this can be closed.
If needed it can be reopend.
