### ISSUE TITLE
extra-menus

### ISSUE THREAD

**Issue by LihP** [rlf/uSkyBlock#335]
The extra-menus only appear to work if I choose "SIGN" as the item and It will only open the island_help.yml, all other items will do nothing and changing the file it opens has no effect.

Here is my config:
http://pastebin.com/3sMzAzzR

[13:16:51 INFO]: Name: uSkyBlock
[13:16:51 INFO]: Version: 2.3-HF1a
[13:16:51 INFO]: Description: Ultimate SkyBlock v2.3-HF1a-2e2dfe-dev
[13:16:51 INFO]: ------------------------------
[13:16:51 INFO]: Server: CraftBukkit git-Spigot-c5492f8-cf5a502 (MC: 1.8)
[13:16:51 INFO]: ------------------------------
[13:16:51 INFO]: Name: Vault
[13:16:51 INFO]: Version: 1.5.3-b37
[13:16:51 INFO]: ------------------------------
[13:16:51 INFO]: Name: WorldEdit
[13:16:51 INFO]: Version: 6.0;3342-78f975b9
[13:16:51 INFO]: ------------------------------
[13:16:51 INFO]: Name: WorldGuard
[13:16:51 INFO]: Version: 6.0.0-beta-05.1569-
[13:16:51 INFO]: ------------------------------

[13:17:11 INFO]: [ChestCommands] 
[13:17:11 INFO]: Version: 3.1
[13:17:11 INFO]: Developer: filoghost
[13:17:11 INFO]: Commands: /chestcommands help

**Comment by dutchy1001** [comment]
Have you followed the guide for using Chest Command GUI? Click [here](https://github.com/rlf/uSkyBlock/wiki/The-use-of-3rd-party-plugins#chest-command-gui) for the guide.
Make sure you have the permissions setup for Chest Command GUI so each player/rank can use it. 

This is an example from the perms a rank/player needs (this is taken from my test server and works)
```
  g:groupmanager_default:
    permissions:
    - groupmanager.notify.self
    - usb.island.create
    - usb.island.sethome
    - usb.island.challenges
    - usb.party.join
    - chestcommands.command.open
    - chestcommands.open.island_help.yml
    - chestcommands.open.perks.yml
    - chestcommands.open.donor.yml
    - scavenger.scavenge
```
These nodes can be used either in the global or world config in GroupManager (if you use an other permission plugin look on their site how to add them in the right format).

For your basic setup you need minimal:
*  - chestcommands.command.open
* - chestcommands.open.island_help.yml

That some items dont work is just trial and error. For example "skull" wont work but 397 does, were 397 is a skull (skelleton head). Yet again 397:3 (steve head) wont work (I have tried chest, 397(skull),256 (iron shovel) 383(spawn egg) with no hassle using your "17" section of the config).

If an item name wont work try the item ID even then sometimes an item doesnt work (guess this is a MC limitation then).

Let me know how you get on now you have more info how too.

**Comment by LihP** [comment]
Hey, thanks for the quick and detailed reply. I have been using chestcommands for some time so I understand the perms required and they are already in place, but I did just fix my problem.
The issue was because the displayitem: was not surrounded in apostrophes, after doing that I now get the chat confirmation in green and I can use any item. I just regenerated my config to check the default extra-menus and they do not include apostrophes.

  extra-menus:
    # [integer 0-17] The slot your new menu will appear in.
    7:
      # [String] The title of your menu.
      title: '§a§lBuy Perks'
      # [String] The item to be displayed. Note, this must be an item not used elsewhere in the menu.
      displayItem: CHEST
      # [string] List of commands to run when player clicks your menu.
      commands:
       - 'chestcommands open perks'
      # [string] Description of what your menu does.
      lore:
       - '§fVisit the perk shop to buy'
       - '§fspecial abilities for your'
       - '§fisland and character, as well'
       - '§fas titles and more.'
       - '§e§lClick here to open the shop!'

**Comment by dutchy1001** [comment]
I have also notest that in my island_help.yml are 2 mistakes, due to the update to 1.8, some items are not showing.
These items are at location 1-5 I changed that to 324 (wooden_door, numbers needed as it wont accept text format) and location 2-3 I changed that to MAP (wich accept text).

Not sure the apostrophes were the issue but if it works it works :). 
Thx for letting us know the result you got

**Comment by LihP** [comment]
Yeah I noticed and customized the island_help, thanks for pointing them out.

I think your right it was not the apostrophes, I had it working before I renamed the config to generate a new one and check the defaults. Now I am back to the same problem with and without the apostrophes. Super weird, I cannot work out why it worked or what I did differently.

**Comment by dutchy1001** [comment]
atleast you know in what direction you need to look. I have notest that not all items work to use in the GUI, special portal related. But for example skull 144 wont work at all while skull 397 (numbers only) does work. 
I agree there is some weird things going on in that case.

**Comment by LihP** [comment]
I am testing with the 256 shovel as that is the item I used when it worked but I cannot get anything unless I use the sign and that just gives me the island_help.yml. 
https://drive.google.com/file/d/0BxilLZQHdwZbbzhpU3B1N0phak0/view?usp=sharing

**Comment by dutchy1001** [comment]
whe  I tested this It worked, What version of Chest Command GUi are you using?

I'm in the process of setting up a server for server owners to show them things work, I will include your shovel on spot 17 aswell then.

**Comment by LihP** [comment]
I am using 3.1 the latest, I really don't understand how I got it to work once and cannot seem to do it again. I have tried with the default config as OPed and deOPed with perms. I did notice that when I first got the plugin I clicked the chest and enderchest and nothing happened, I would expect them to give the chat message .yml not found in red like chest command does when you try to open a menu that doesn't exist. I am not sure how else to test it, if you have any suggestions I am willing to try, please let me know how your setup test goes.

**Comment by dutchy1001** [comment]
As long the .yml files provided in the extra-files rar are in the menu folder from ChestCommand GUI then they should work.
Does the sign work before you create your island??(meaning the first small menu with only 3 options (grass, head and sign))
Also check the nodes incase you made a typo.

**Comment by LihP** [comment]
Hey, yeah the sign works in the first menu before an island is created. I think that is the only reason it continues to work in the second menu because as you see in the video if I use a sign as the item I can change the command to anything I like and it will always open the island_help.yml. I do have the ymls in the menu folder of chestcommands, but the strange thing is when I managed to get it working it would also say in chat when they where missing like chestcommands does.

**Comment by dutchy1001** [comment]
I have tested this now with many items.
I know that data value's are not suported as those items didnt even showed in the GUI. 
Items like "stone, grass, sand" work normal with names, Items like "wooden_door, fish, skull, iron_shovel" needs a number value to work (DIamond worked both ways numbers and text).

In all of these cases the island_help.yml opens as it should. I tested that the sign in the first menu and after creating an island menu worked, using the same island_help.yml on different menu's is possible. 
If it works for the "sign" then it should work for the other items too.

Maybe post the issue at the Chest Command GUI page is an option, as I'm out of ideas for it.

**Comment by rlf** [comment]
This seems to be due to the somewhat limited "gui-implementation" currently used in uSkyBlock.

Basically, you can't reuse already used "icons" for menus.

Sorry about that - but we haven't gotten around to refactoring the menu yet - since we are considering moving completely to a "ChestCommands GUI" based UI (instead of the mix we have now).

**Comment by LihP** [comment]
Thanks for the information, I am happy to say the problem appears to be fix. I tested a previous version of chestcommands, version v3.0.8 and the extra-menus worked with the various items that I tried. I then moved the v3.1 jar back into the plugins folder and delete 3.0.8 and it also worked. I have no idea why I had this problem, no changes where made to the uskyblock config or other plugins added or removed during these tests. If I figure out what causes the issue I will get back to you.

**Comment by dutchy1001** [comment]
thx for letting us know.

**Comment by LihP** [comment]
Alright so after a few restarts it stopped working again, I wish I could understand what is causing this.

**Comment by rlf** [comment]
1.8 changed some stuff regarding what will work as "items in a container". That is why we had to change some stuff. I.e. "water" and "lava" can't be used anymore either.

**Comment by dutchy1001** [comment]
I've been on your server but cant find the skyblock server as lots is going on lol. I do think it's not a usb issue but more a Chest Command GUI issue or maybe a combination of a few things.

**Comment by LihP** [comment]
@rlf I remember when it changed , I had to replace portal blocks and fire items from menus. 
Solved it, I worked out the cause. The extra-menus appear to only work for me when I am in the island world, sorry for not seeing this patten before now, I feel stupid. Please ignore the fact that the shop_menu.yml looks just like my island_help.yml, I just copied it and removed an item for testing purposes. https://drive.google.com/file/d/0BxilLZQHdwZbb3l3dlF0WFlkaGs/view?usp=sharing


@dutchy1001 The server is hidden until testing is complete, we are hoping for solution to the to other issue I posted, https://github.com/rlf/uSkyBlock/issues/336 because we don't want players to experience this void glitch. I would really like to add a delay between the island creation and the player teleport just to see if it helps, that or some how force reload the chunks.

**Comment by dutchy1001** [comment]
I have updated the uSkyblock_extra.rar with all items showing now for the spigot 1.8.x versions

**Comment by LihP** [comment]
Can we make this as open because we solved why I was having trouble but the problem is not solved.
The issue is only being able to use the extra-menu items when you are in the island world, for anyone who has the config option "extras.sendToSpawn: true" will probably be using another world for spawn and the extras menu items will not work for them and no warning is given to the player as to why.

**Comment by LihP** [comment]
Here you got dutch, just before I got to bed, this is why signs work, line 947 https://github.com/rlf/uSkyBlock/blob/master/src/main/java/us/talabrek/ultimateskyblock/SkyBlockMenu.java

**Comment by dutchy1001** [comment]
Both links have nothing to do with your problem, the first link was a leftover from old code and is now removed, the second is a fallback value in case no displayItem has been supplied for 1 of the menus we use.

I'm almost sure it's a permission issue from ChestCommandGUI plugin or PEX.
You have experience with ChestCommandGUI, make a menu for the spawn world in your test server, that way you can test the .yml files that they work in your spawnworld.

**Comment by LihP** [comment]
Hey, sorry I had a few beers when I left that message. I didn't look at the code for very long.
Here are the reason I feel its not related to permissions but I could be wrong.
1. OP should be able to access it if permissions where the problem.
2. We use global perms, not per world so as it works in the island world it should work in all.
3. One of the extra-menu items (bedrock) doesn't open a menu and simply runs the command spawn and this acts the same, cannot be clicked unless your in the island world.
4. The shop menu can be accessed via the command /shop while in spawn or any word, but the shop menu will not open via the island menu unless you are in the island world.

Just to save my sanity, do you have a server that I can visit to see a extra-menu work outside of the island world?

**Comment by rlf** [comment]
One question.
Why would you have the island-custom menu work outside the skyworld?
I think we previously had an issue, where it were explicitly asked for it not to work outside, but I might be wrong.

**Comment by rlf** [comment]
Btw. please describe your issue, instead of trying to understand the code.
The piece of code you highlighted above is pure awesomeness - and I'll be happy to walk you through it :)

The reason we use Vault, and include the world, is for servers with a multi-world setup, and permission per world superperm implementation.
I.e. perhaps some players will have `/fly` permission in one world, and not in the rest.

**Comment by LihP** [comment]
Thanks for the reply, the code is good, just I was demonstrating the issue with @dutchy1001 on our test server and I said I would try to find the cause. I should have waited till the next day as I had been out at a party and was in no fit state to be online, sorry.
I can understand the reason for world checking and I assume its not the cause if vault checks for global perms as well.

All the regular menu items appear to check the world and give the player a message when they are not in the island world, but the extra menus just become un-clickable and to not explain to the user as to why. The reason we would like them to work is for consistency and user experience, we currently use 2 extra items which open the shop menu and the other teleports to spawn. I am trying to think of a scenario that would cause a problem when using the extra-menus in all worlds, for example if the admin setup the extra menu to run a island command, from my brief look at the code, island commands check the world before they execute so that shouldn't cause an issue. It would be nice to have the option or at least a message to the user as to why the menu item is not working. Cheers!

**Comment by dutchy1001** [comment]
A few things are getting mixed up and getting my head around how to explain took a while too.

The sign in the "create first island" menu only execute the command:
* /chestcommands open island_help

from here ChestCommandGUI takes over and USB has nothing to do with it then. The netherstar what takes you back to the usb menu is only a command (/is) what you normally use to open the island menu.
If ChestCommandGUI isnt installed it just doesnt do anything besides give you a message that it is an invalid command or similar.

The shop menu's in the "main island menu" (the chest and enderchest) only execute the command:
* /chestcommands open perk
* /chestcommands open donor

from were ChestCommandGUi takes over again and leaves USB alone.

So i guess we need to look into ChestCommandGUI and see were the prob is then

**Comment by rlf** [comment]
No problem Lihp :)

The places where most "havoc" can be made by allowing the extra-menus, is shops/vip-shops with multi-worlds and multi-inventories...

Suddenly, they might be able to sell dirt (which is expensive in sky) for highprices from a survival world (where they should be in abundance).

I get your point though - that we should probably inform the user when clicking the items (perhaps even include a tooltip).

**Comment by dutchy1001** [comment]
due to many servers are using bungecoord now most is separated anyway, if they use a single server setup the server owner needs to keep an eye on it themselfs

**Comment by LihP** [comment]
That would be great, thanks. Would it even be possible to add a config option like the example below:

  extra-menus:
    '7':
      title: §a§lIsland shop
      displayItem: CHEST
      requireIslandWorld: true     <<<<<<<<<<<<<<
      commands:
      - chestcommands open shop-menu
      lore:
      - §fOpen the shop menu
      - §fBuy and sell items
      - §e§lType §a/shop

**Comment by rlf** [comment]
Hi again.
I took one more sip of the code - and I think I might be understanding the confusion now.

First off, the VaultHandler is a left-over from days past - I doubt it is really needed, but nevertheless, it's there.

The extra-menus is a babylonian tower of overcomplicated architecture - but at the same time, quite flexible.

The `VaultHandler.checkPerm(player, perm, world)` will just ensure the player either has the global perm, or at least a world-specific perm.

It's ONLY used (how-ever) by uSkyblock, to figure out what command should be executed.
I.e.
```
commands:
  - '[!donor.perk]say {player} You do not have access to VIP area, purchase it here!'
  - '[donor.perk]chestcommands perk.shop'
```
Once the skyblock plugin actually has chosen what to execute, it executes it according to the rules for that particular player (meaning they require permissions, unless the command is pre-pended with either `op:´ or `console:`).

This way, you should be able to control access to various functions by using a per-world permission system.

Now to the "problem" - since we assume any permissions is setup correctly in the skyworld, that is what we use as base for our "command-filtering".
Which might be a bad idea.
If we were to change the world-lookup from the skyworld, to what-ever world the player happens to be in, we would introduce some added flexibility.

Also, if possible, I will try to add a message if the execution of the command fails - but not sure we can always rely on the return-code from `performCommand`.

**Comment by LihP** [comment]
Thanks for solving it, that all sounds perfect to me, hope its easy to implement!

**Comment by dutchy1001** [comment]
I got a bit wiser too here

**Comment by rlf** [comment]
@LihP What I wrote above is already implemented.

The only thing that might be changed (needs changing), is whether the world used for "permission checks" should be the skyworld or the world the player is in.

**Comment by LihP** [comment]
I am back from my time away, I am using 2.3-HF3b and we are finding the new features great and I also updated to the most recent version of 1.8.0 and the reset has not failed yet. All that is missing is the ability to use the extra-menus outside of the island world :)

**Comment by dutchy1001** [comment]
I'll see what for solution we can make it for the world check and welcome back.

**Comment by LihP** [comment]
Thanks, can we set the status to open?

**Comment by dutchy1001** [comment]
is this still an issue or can this be closed.

**Comment by rlf** [comment]
Still open, the skyworld is still used for executing commands, not the "current-player-world".

**Comment by dutchy1001** [comment]
It took a bit but finally you should be able to use it in any world now. Up to a server owner to block commands that are not allowed in a world.
