### ISSUE TITLE
Issue with i18n

### ISSUE THREAD

**Issue by Darkool** [rlf/uSkyBlock#338]
Hello, I can't compilate uskyblock, because 
I need this libraries:
import org.xnap.commons.i18n.I18n;
import org.xnap.commons.i18n.I18nFactory;

and maven doesn't work, can you help me please?

**Comment by rlf** [comment]
Maven should work - it does for me - and it is what you need to get those dependencies.

If you insist on not using maven, you still need both GNU Gettext, and the commons for java (https://code.google.com/p/gettext-commons/wiki/Tutorial) to compile the project successfully with i18n support.

**Comment by Darkool** [comment]
I get this error:

BUILD FAILURE
------------------------------------------------------------------------
Total time: 28.079s
Finished at: Tue Apr 07 16:29:59 CEST 2015
Final Memory: 8M/124M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec (default) on project uSkyBlock: Command execution failed. Cannot run program "git" (in directory "C:\Users\xxxx\uSkyBlock-master\target"): CreateProcess error=2, System can't find especific file -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by rlf** [comment]
It's because the pom.xml requires git in order to correctly tag the release.

Try commenting out lines 138-218 (https://github.com/rlf/uSkyBlock/blob/master/pom.xml#L218), or simply install git (and make it available in the PATH).

**Comment by Darkool** [comment]
Thanks a lot, Fixed ;)

**Comment by Darkool** [comment]
A little question, menu.yml, for translations works? or isn't finished yet
