### ISSUE TITLE
Could not pass event PlayerPortalEvent

### ISSUE THREAD

**Issue by Deathinflames** [rlf/uSkyBlock#339]
Scanning through the logs this morning, i noticed these two issues. I am not sure if this was already fixed in v2.3-HF1a, v2.3-HF1b, v2.3-HF1c, or v2.3-HF2a, but i just wanted to report it as i didn't see 
any open tickets with these 2 issues.

http://pastebin.com/jXWxtKMV

http://pastebin.com/61bcJasw

Thank you for the continued support!

This server is running CraftBukkit version git-Spigot-dbe012b-63e28b1 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

Ultimate SkyBlock v2.3-b3ca9e-dev (Stability release, released on Mar 2)

**Comment by rlf** [comment]
Fixed in #301 Duplicate
