### ISSUE TITLE
/is kick = An internal error

### ISSUE THREAD

**Issue by manercraft** [rlf/uSkyBlock#340]
When I execute command: /is kick <player>
The commands send a error
Screen: http://prntscr.com/6qtsgw
Version of my plugins: http://prntscr.com/6qttiz

**Comment by rlf** [comment]
Internal errors always leads to log-entries in the server-log, can you provide them as well please?

**Comment by dutchy1001** [comment]
I cant reproduce this using v2.3HF2a

**Comment by manercraft** [comment]
@rlf http://pastebin.com/90bWkDTA
@dutchy1001 Ok I test

**Comment by manercraft** [comment]
Work in v2.3HF2a
New bug:
Teleportation comhttp://prntscr.com/6qveyimand:
http://prntscr.com/6qveyi (palyer on my server)
In english:  
The /is h has work 5 minutes after typing the command but really 5 minutes

5 seconds = 5 minutes

**Comment by dutchy1001** [comment]
yes we are aware of this, det it to 0 (zero) for the time being

**Comment by dutchy1001** [comment]
The initial issue is resolved with the new version (v2.3-HF2a) and secondary bug is known.
closing this issue.
