### ISSUE TITLE
Does the ocean biome allow guardians to spawn?

### ISSUE THREAD

**Issue by c0wg0d** [rlf/uSkyBlock#342]
I asked this in a closed issue about biome changes but got no response.  Do guardians spawn when you switch to the ocean biome?  If not, is there any way to get an ocean monument biome selection so people can collect prismarine shards?

**Comment by dutchy1001** [comment]
I'm sorry about that, but I've been away a few days and/or it got lost as it was in a closed issue you posted it.
All mob spawn are default Minecraft, I supose in that case that ocean mobs should spawn then but it never got tested yet. It might be the spawn conditions that can hold it back as you are on a small area but I'm not sure about that.

**Comment by c0wg0d** [comment]
So it's most likely based on the seed and is the luck of the draw based on your island location then?  That seems unfortunate, but understandable.  Can anyone else confirm that this is the case?

**Comment by rlf** [comment]
Yes, We don't mess with the seed info (not sure if that is possible at all).

The same applies for getting slimes to spawn (you need to find the naturally-occurring slime-chunks on your island, below level 39).

**Comment by rlf** [comment]
Currently working on adding a DEEP_OCEAN biome, where squids spawning below a PRISMARINE block will be turned into Guardians.

Note: The spawn frequency of squids are not even close to the spawn-frequency of Guardians in a monument - but at least this way it will be possible to farm prismarine.

**Comment by dutchy1001** [comment]
Guardians spawn in deep water with the prismarine block on top, working and tested in v2.5.7
