### ISSUE TITLE
Players can set island warp location to anywhere (other player's islands, spawn, etc.)

### ISSUE THREAD

**Issue by c0wg0d** [rlf/uSkyBlock#343]
See title.

**Comment by dutchy1001** [comment]
The meaning of the warp command is to set were visitors can warp too on the island (if you allow playershops or something, or just to show of the island), it's not ment to to set your warp to a location anywere in the world or server. For those kinds of warps you need a separate plugin.

**Comment by rlf** [comment]
I think that is exactly what the original poster is about.

We (apparently) don't limit the location when setting the warp, just check the permissions, so owner A of island A can set a warp on another players island.
Circumventing banning etc.

**Comment by dutchy1001** [comment]
Sorry if i misunderstood this issue, I get it now lol

**Comment by dutchy1001** [comment]
Your only allowed to set warp on your own island/region now.

This is fixed in v2.3-HF2b
