### ISSUE TITLE
If you have more than 4 challenge ranks, how do you get to the next page of challenges?

### ISSUE THREAD

**Issue by c0wg0d** [rlf/uSkyBlock#345]
Is there a way to show more than 4 ranks of challenges on one page?  I'd like to just show all of them at once.

At the top it says "Challenge Menu 1/2" but I don't know how to get to the next page.

**Comment by dutchy1001** [comment]
You can click on the dirt/iron block to go to the main menu and the gold/diamond block to go to the next page.

**Comment by c0wg0d** [comment]
Can you please say that somewhere on the challenges documentation?  It doesn't say it anywhere that I could find.

**Comment by dutchy1001** [comment]
very true to that, I will add this when I get the time for it
