### ISSUE TITLE
Cannot register player to island

### ISSUE THREAD

**Issue by c0wg0d** [rlf/uSkyBlock#347]
Using Spigot 1.8.3, zPermissions 1.3, and uSkyblock 2.3-HF1a.

I have the permission usb.admin.register but I am unable to use the command:

/usb island register zilory

It says You do not have access

If I am opped it works, but I shouldn't need that if I have the permission.

**Comment by rlf** [comment]
We are currently discussing this.

Currently, you also need `usb.admin` and `usb.admin.island` to use that command.

We will soon(tm) remove the need for the `usb.admin.island` permission.

**Comment by dutchy1001** [comment]
Without the need of the perm "usb.admin.island" or OP the perms work again.

fixed in v2.3HF2b
