### ISSUE TITLE
Confirmation when leaving a island or restarting

### ISSUE THREAD

**Issue by LihP** [rlf/uSkyBlock#350]
To prevent mistakes it would be nice to require a repeat of the command or and extra argument when restarting or leaving.
Example
/island leave
[Chat] WARNING, this will delete all your items, please give your island members the items and confirm by typing /island leave confirm

My grammar sucks but you get the point, thanks.

**Comment by rlf** [comment]
Good suggestion. Should be implemented (not the first time we get this request).

**Comment by dutchy1001** [comment]
Conformation command works to let the island restart but after it's restarted it teleports you to the spawn again. 

 It also gives the message that you will be teleported in 5 seconds(depending on config setting, mine was default). Dont think that should be there as restart is taking a few secods anyway.

**Comment by rlf** [comment]
That is an error - I thought I found them all, apparently at least one was left

**Comment by dutchy1001** [comment]
this is working properly in v2.3HF7i

Closed
