### ISSUE TITLE
Safe teleport locations

### ISSUE THREAD

**Issue by LihP** [rlf/uSkyBlock#351]
public boolean isSafeLocation(final Location l) {
        if (l == null) {
            return false;
        }
        final Block ground = l.getBlock().getRelative(BlockFace.DOWN);
        final Block air1 = l.getBlock();
        final Block air2 = l.getBlock().getRelative(BlockFace.UP);
        return ground.getType().isSolid() && !air1.getType().isSolid() && !air2.getType().isSolid();
    }

I think I worked out why you can spawn in lava with the home command, lava is a none-solid block so air1 and air2 will return true in the above function. See this video for an example:
https://drive.google.com/file/d/0BxilLZQHdwZbekFrZGQxaUxnS2s/view?usp=sharing
I also worked out if the getSafeHomeLocation() function cannot find a save location it still teleports the player to an invalid location, this can be observed if you remove all blocks below and above the location, the player will spawn above the void. It's hard to solve this as I guess you don't want to spend too much time looping though locations, would be easy if all schematics included the bedrock like the default one does because you could focus your check on that X any Z and test for a valid Y or try  bukkits getHighestBlockAt(location) first.
See this video for an example, I move the location1 block back so the leaf blocks above are no longer vaild locations:
https://drive.google.com/file/d/0BxilLZQHdwZbNjNqbENIcTgwMHc/view?usp=sharing
Also the location needs to be centred on the block, might be just 2.3-HF2c as I don't recall noticing that before, might help with the glitchy island restarts https://github.com/rlf/uSkyBlock/issues/336 as you spawn kinda in the chest and if you place a full block above the chest it pushes you to the left.

[12:04:12 INFO]: Name: uSkyBlock
[12:04:12 INFO]: Version: 2.3-HF2c
[12:04:12 INFO]: Description: Ultimate SkyBlock v2.3-HF2c-9f6263-dev
[12:04:12 INFO]: ------------------------------
[12:04:12 INFO]: Server: CraftBukkit git-Spigot-c5492f8-cf5a502 (MC: 1.8)
[12:04:12 INFO]: ------------------------------
[12:04:12 INFO]: Name: Vault
[12:04:12 INFO]: Version: 1.5.3-b37
[12:04:12 INFO]: ------------------------------
[12:04:12 INFO]: Name: WorldEdit
[12:04:12 INFO]: Version: 6.0;3342-78f975b9
[12:04:12 INFO]: ------------------------------
[12:04:12 INFO]: Name: WorldGuard
[12:04:12 INFO]: Version: 6.0.0-beta-05.1569-

Hope it helps, thanks!

**Comment by rlf** [comment]
With the "normal" grief-prevention, visitors won't take damage when put in lava...

But I get your point, we can improve the safelocation-locator to include some checks of that sort.
Including water-drowning traps.

**Comment by dutchy1001** [comment]
save teleport is partly working in v2.3-HF3b

When there is no save teleport location I ended on top of the tree of a default island.
When the tree has been removed and lava has been placed on it's place it will teleport you to the unsafe home location. In this case you end up in lava again.

**Comment by rlf** [comment]
I just adjusted the `isSafeLocation` method - but the code for finding a "safe-spot" will fallback to the original location if no safe location is found...

And it only searches along the Y-axis for a safe spot, should probably be changed.

**Comment by LihP** [comment]
Spawning in liquids appears to be fixed. But like you mentioned above only the y-axis is checked and if all blocks are removed above and below the player will spawn in mid air and fall into the void making it impossible to get to the island.

**Comment by dutchy1001** [comment]
think this is fixed now, if not reopen an issue.

Closing it for now.
