### ISSUE TITLE
Solution to destroying the lava source block

### ISSUE THREAD

**Issue by LihP** [rlf/uSkyBlock#352]
I love the obisidan back to lava feature but I have been trying to prevent another possible mistake. If a player accidental places a block in their lava source block. If anyone has any ideas please share them, for now I have just created a warning and help guide.

	public void placeBlock(BlockPlaceEvent event)  {
		if (event.getBlockReplacedState().getType() == Material.STATIONARY_LAVA){
			event.getPlayer().sendMessage(Hey! Lava is important, if lose your lava read /help");
		}
	}

One of the problems I found is that when liquids stop flowing that are all considered Material.STATIONARY_LAVA and therefore if lava spreads 4 horizontal blocks this warning will pop up when a player places a block in any of those 4 blocks not just the source so I cannot cancel the event. I tried a few ways to detect the source by trying to update the blocks around the placed block and test if they become flowing lava or Material.LAVA, but it really didn't work out well, if any one has suggestions please share them. Thanks.

Sorry for making so many new issues at once, I am not expecting any quick response I respect you do this for free and have a life ;)

**Comment by rlf** [comment]
Good point.

And valid problems.

We have a shop, where you can buy a new bucket with lava - in the rare cases where people are downright suicidal :D

**Comment by rlf** [comment]
You could take a look at the data-value http://minecraft.gamepedia.com/Data_values#Water_and_Lava

The following code should be part of the next release ... perhaps...
```
    @EventHandler
    public void onLavaReplace(BlockPlaceEvent event) {
        if (event.getPlayer() == null || !plugin.isSkyWorld(event.getPlayer().getWorld())) {
            return; // Skip
        }
        if (event.getBlockReplacedState() != null
                && (event.getBlockReplacedState().getType() == Material.STATIONARY_LAVA ||
                event.getBlockReplacedState().getType() == Material.LAVA)
                && event.getBlockReplacedState().getRawData() == 0) {
            plugin.notifyPlayer(event.getPlayer(), tr("\u00a74It's a bad idea to replace your lava!"));
            event.setCancelled(true);
        }
    }
```

**Comment by rlf** [comment]
Not sure this is what we want though...
It effectively stops players from removing their lava by placing blocks over them, but, that might mean they'll die and lose their items...

**Comment by rlf** [comment]
Committed an awesome fix - hope it performs well.

**Comment by LihP** [comment]
Oh great solutions, I totally missed the data-value, that makes more sense to how the game controls the flow distance. I agree it would not be great to cancel it especially with setups where players can buy or obtain additional lava. Still nice to have the warning and perhaps configurable the error message. If not I can do this with my own plugin, an idea solution would be a short time for the user to type /undolava or something, maybe 20 seconds, we track the block location for that times and replace if the command is called. Might be too much effort, but just an idea.

Thanks again.

**Comment by rlf** [comment]
Well, now I made it so you can't replace "source-lava" blocks without using a bucket.

**Comment by dutchy1001** [comment]
this is working now with version v2.3-HF3b.

I do have concerns about this feature as players often place the lava by mistake and trying to clean up by placing quickly a block were the lava is placed or were it flows to. The future will show us i presume.

**Comment by rlf** [comment]
It should not block placing blocks on lava, unless it's a source-block.
I.e. you should be able to place blocks over flowing lava.

**Comment by dutchy1001** [comment]
yes placing a block above it is no problem or on flowing lava

**Comment by LihP** [comment]
Tested with the following version and works as expected. Only suggestion would be to allow customized messages, that would be useful in many areas of the plugin. Thanks again for the great solution!
[08:41:37 INFO]: Name: uSkyBlock
[08:41:37 INFO]: Version: 2.3-HF3b
[08:41:37 INFO]: Description: Ultimate SkyBlock v2.3-HF3b-5ee95f-dev
[08:41:37 INFO]: ------------------------------
[08:41:37 INFO]: Server: CraftBukkit git-Spigot-550ebac-7019900 (MC: 1.8)
[08:41:37 INFO]: ------------------------------
[08:41:37 INFO]: Name: Vault
[08:41:37 INFO]: Version: 1.5.3-b37
[08:41:37 INFO]: ------------------------------
[08:41:37 INFO]: Name: WorldEdit
[08:41:37 INFO]: Version: 6.0;3342-78f975b9
[08:41:37 INFO]: ------------------------------
[08:41:37 INFO]: Name: WorldGuard
[08:41:37 INFO]: Version: 6.0.0-beta-05.1569-

**Comment by dutchy1001** [comment]
In v2.4.x there is an option to toggle the lava protection.

```

    # Whether or not the plugin will try to protect the player from accidentally extinguishing lava
    protect-lava: true
```
