### ISSUE TITLE
Bad Performance in PlayerEvents::onClickOnObsidian

### ISSUE THREAD

**Issue by Brokkonaut** [rlf/uSkyBlock#353]
http://timings.aikar.co/?url=10816668

The method onClickOnObsidian is called very often and offers quite bad performance. This is caused by calling uSkyBlock::playerIsOnIsland which calls uSkyBlock::getPlayerInfo, that causes the player info to be saved (on every players block interaction!)

19:43:26 INFO: Name: uSkyBlock
19:43:26 INFO: Version: 2.3-HF1c
19:43:26 INFO: Description: Ultimate SkyBlock v2.3-HF1c-b79d59-dev
19:43:26 INFO: ------------------------------
19:43:26 INFO: Server: CraftBukkit git-Spigot-2f787bd-501372f (MC: 1.8.3)
19:43:26 INFO: ------------------------------
19:43:26 INFO: Name: Vault
19:43:26 INFO: Version: 1.5.3-b37
19:43:26 INFO: ------------------------------
19:43:26 INFO: Name: WorldEdit
19:43:26 INFO: Version: 6.0.2-SNAPSHOT;3370-58aac973
19:43:26 INFO: ------------------------------
19:43:26 INFO: Name: WorldGuard
19:43:26 INFO: Version: 6.0.0-SNAPSHOT.1591-
19:43:26 INFO: ------------------------------

PR: https://github.com/rlf/uSkyBlock/pull/354

**Comment by rlf** [comment]
Nice catch - and not only for obsidian, more or less every event accessing the playerinfo.
Accepted the pull-request, will be part of next release.

**Comment by rlf** [comment]
But... perhaps the updatePlayerInfo should actually only be called on Login?
I think I included it where I did, because I wasn't sure whether Mojang supported players changing names while being online.

**Comment by rlf** [comment]
https://github.com/rlf/uSkyBlock/releases/tag/v2.3-HF2d
