### ISSUE TITLE
Is it possible for players to see their island rank?

### ISSUE THREAD

**Issue by c0wg0d** [rlf/uSkyBlock#355]
In Talabrek's version, you could do /is level, and it would show not only your island level, but also what rank your island was.  It only seems to show what your island rank is now if you are in the top 10 islands.  Is there a permission other than usb.island.level that players need to be able to see this info, or is it no longer available?  Is there any way to add it back in?

**Comment by dutchy1001** [comment]
This is no longer available atm but I'll have a word with the main dev to see if he agrees to re-add this.

**Comment by rlf** [comment]
This was made as a performance improvement.
But I will consider adding it again (the data is available atm.)

**Comment by rlf** [comment]
https://github.com/rlf/uSkyBlock/releases/tag/v2.3-HF2d

**Comment by dutchy1001** [comment]
The command /is level is now showing the players rank
Tested in v2.3-HF2f and working
