### ISSUE TITLE
Askyblock converter

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#356]
We been asked (at the Spigot forum) for a converter from Askyblock to uSkyblock. 
I think this is a good idea (think we talked about it a good while ago but never got it realized).

I know Askyblock has a converter from uSkyblock to his, so why not the other way around.

**Comment by rlf** [comment]
Where can I find the uSkyblock -> ASkyblock converter? It might help with the creating of the inverse function.

**Comment by rlf** [comment]
https://github.com/tastybento/uablockconvert

**Comment by dutchy1001** [comment]
Find [here](http://dev.bukkit.org/bukkit-plugins/uablockconverter/) the link to uSkyblock to Askyblock converter.

Find [here](http://dev.bukkit.org/bukkit-plugins/islandworld-askyblock-converter/) a converter from another skyblock converter to maybe incorporate too (or 2 separate ones).

**Comment by rlf** [comment]
There has been an increased focus on getting this done.
But, we prioritize to move to a different data-model before we look into writing any converters - since the converters/importers needs to be rewritten, once we move to a DB-based backend.

Effectively, this issue depends on #406 #582 #540
