### ISSUE TITLE
Simplified Chinese

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#359]
Got this in a PM on Spigot:

> Sorry...have never use github...
> You can download Simplified Chinese language file at http://pan.baidu.com/s/1o6KF20U~
> 
> And any other particular .yml i will complet in this week or next week~

**Comment by rlf** [comment]
And as a comment on a PR.

**Comment by dutchy1001** [comment]
found 1 mistake so far

**Comment by dutchy1001** [comment]
As I went throught the file it seems I miss a few things
```
#: us/talabrek/ultimateskyblock/SkyBlockMenu.java:726
msgid ""
"§fWhen you teleport to your\n"
"§fisland you will be taken to\n"
"§fthis location.\n"
"§e§lClick here to change."
msgstr ""
"§f设置你传送会岛屿的坐标.\n"
"§e§l点击图标更改坐标."
```

There are 4 orginal line here but only 2 in chinees. There a few more like this. So before adding can you explain if this is ment to be or that there are still lines to translate?

I found a typo too
```
"§e/iosland setwarp§f设置岛屿传送点."
```
As we appreciate your work and effort to translate could you check over the file before we will add this to the plugin. 
If you use [pastbin](http://pastebin.com/) to repost the file I can then add it easier.

**Comment by gal499605076** [comment]
Sorry~ I'll check it again more clear~

**Comment by gal499605076** [comment]
"§f设置你传送会岛屿的坐标.\n"
mean : set an location what you will warp to in your island.

"§e§l点击图标更改坐标."
mean : click the icon to change the warp location.

**Comment by dutchy1001** [comment]
I just wondered that on some translations less lines were, if it's the same message with less lines then  we have no problems with it. 

Better to be sure then to change it after again.

Thx for the translation

**Comment by gal499605076** [comment]
There're less amount of words in Chinese translation, but what they mean won't change~

**Comment by dutchy1001** [comment]
Thx @gal499605076  Just wanted to be sure. Your translation is added to the bukkit page

**Comment by a08381** [comment]
Excuse me , I had just tried the release 'i18n test for zh_CN - take 2' , But it's still in English , I tried to modify en into zn_CN or zh_CN , but it still isn't work . Do I miss somethings ?

**Comment by dutchy1001** [comment]
@a08381 

you dont miss any, I have the same problem and notified our dev

**Comment by rlf** [comment]
Back from Paris - will try to take a look at it later to day.

**Comment by dutchy1001** [comment]
Language system will be changed due to many bugs it creates,

closed
