### ISSUE TITLE
hello please help me to plugins and the skyblock player can break the isula me and I did not invite me

### ISSUE THREAD

**Issue by deluxx001** [rlf/uSkyBlock#360]
hello please help me to plugins and the skyblock player can break the isula me and I did not invite me

**Comment by EvilOlaf** [comment]
Help yourself for some punctuation marks and more precise information including your server software as well as your uSkyBlock version.

**Comment by deluxx001** [comment]
version are Spigot 1.8 si server este pana la 1.7.x 1.8.x

**Comment by dutchy1001** [comment]
Can you plz do the command "/usb version" ingame or "usb version" in console and post that info here. If that command is not working update the server to v2.3-FH3

**Comment by deluxx001** [comment]
name uskyblock
version 2.2-hf9b
description ultimate skyblock v2.2-hf9b-8e30a8-dev
server Craftbukkit git-spigot-1645 mc 1.7.10
name vault
version 1.5.2-b33
name worldedit
version 5.6.2
name worldguard
version 5.9

**Comment by dutchy1001** [comment]
@deluxx001 

Update you uSkyblock version to the latest (v2.3HF3) from our bukkit site [here](http://dev.bukkit.org/bukkit-plugins/uskyblock/)

On our page you will find other link for the depended plugins, I recommend to update your WorldEdit and WorldGuard both to v6 preferable the dev-builds. 

If you have your server on Spigot 1.7.10 then you need to downgrade you Vault to v1.4.1. This is important for the right working of our plugin (you can read that on the bukkit site).
