### ISSUE TITLE
Challenges menu page 2 : an other way to open the 2nd page

### ISSUE THREAD

**Issue by zebigboss72** [rlf/uSkyBlock#361]
Hi,
Currently, players need to click on the diamond block to open the second challenge page. It's not intuitive, and a lot's of them didn't know there were more challenges.

Can you add a dedicated item for this task, as a book, in the challenge menu? I add a possible disposition on the image.
![challenge](https://cloud.githubusercontent.com/assets/12184142/7410984/0927ecec-ef34-11e4-81f1-5d25fe79c504.jpg)
Thank you for your attention,

zebigboss_72

**Comment by dutchy1001** [comment]
Thank you for the suggestion, I will talk to rlf and see if he agrees. I understand it's a bit unclear in the beginning if players dont know the option to go to the next page.

**Comment by rlf** [comment]
I've been considering it, but rejected it last time around, because we would loose room for one rank.

I think you are right though... So I will look into changing the "pagination" to your design (or similar).

**Comment by rlf** [comment]
Question: Would it help, if we simply added a tooltip to the rank-icons?

**Comment by zebigboss72** [comment]
I think a simple tooltip can help players to open the second page, but it's not enought clear. I'm really boring with the clarity of the menu. Maybe you can add a tooltip to the rank icon, until you change the pagination. 
I hope my opinion was helpfull, and thank you for the attention you give to this subject.

zebigboss_72

**Comment by rlf** [comment]
Tooltip and 2 more lines added in above commit - ready for test in v2.3-HF4d

**Comment by dutchy1001** [comment]
I do think with the picture showing the books (subject to change into a different icon) for previous and next page is a way forward.
It doesnt matter if you loose 1 row for a challenge as you can add as many pages you like that way and with a much clearer understanding.

**Comment by rlf** [comment]
I agree, but for now, we get 6 ranks, and tooltip for the next page.

For this to be made "nice", we need to have something like this:
```
if number-of-ranks <= 6 then
  show all ranks in one "menu"
else 
  show ranks in pages of 5, and reserve the bottom row for navigation
  if page == 1 then 
    only show "next page" navigation
  else if page == last then
    only show "previous page" navigation
  else
    show both "next" and "previous".
``` 
The current solution is an improvement, the above is not hard, but more complex, and is as such postponed till later.

**Comment by dutchy1001** [comment]
agreed

**Comment by dutchy1001** [comment]
paging works and a description is added, I keep in mind the option mentioned above.
