### ISSUE TITLE
Request: Prioritize online players in tab autocomplete

### ISSUE THREAD

**Issue by c0wg0d** [rlf/uSkyBlock#365]
I love the new tab complete on island warps using /is w <player>.

Would it be possible to prioritize online players when it fills out the player name?  Often times I want to go to somoene's island who is online and I have to type several characters of their name because we have so many islands.  Hopefully what I explained makes sense, if not I can clarify.

**Comment by rlf** [comment]
Sure, good suggestion.

**Comment by rlf** [comment]
On second thought - it might be quite performance intensive... I will take a look.

**Comment by dutchy1001** [comment]
online players are first for tab completion now
