### ISSUE TITLE
some bug about localize

### ISSUE THREAD

**Issue by kxjhwbb** [rlf/uSkyBlock#367]
SkyBlockMenu.java   line 163
Inventory menu = Bukkit.createInventory(null, 18, "\u00a79Island Group Members");
i think it should like:
Inventory menu = Bukkit.createInventory(null, 18, I18nUtil.tr("\u00a79Island Group Members"));

or the event.getInventory().getName().equalsIgnoreCase(I18nUtil.tr("\u00a79Island Group Members")) will not work.  and when the msgid “§9Island Group Members” set in localise file, player can move the icon in Inventory to their own inventory..

i think we should add a global check for the skyblock invertorys to prevent player from cheating..

**Comment by rlf** [comment]
True.

**Comment by dutchy1001** [comment]
I see that the code has changed to the suggested code in the first message.
Can this be closed or does it need a followup chat?
