### ISSUE TITLE
Suggestion : Allow warp creation when island reach a given level

### ISSUE THREAD

**Issue by zebigboss72** [rlf/uSkyBlock#373]
Hi,
I have a suggestion, so if you read this, give your opinion about it.

Do you think allow players to create their island warp when they reach a given level is a good idea?

example : 
Player A get an island level 392. If his island level is higher than 350, he can create his island warp. He create his island warp. Now, he decide to reduce is island level. He get an island level 258. His warp was deleted (because under the limit), and he can't create a new warp until his island reach the limit. 

Why this suggestion?
I think only good island need a warp.For me, players can go on other islands by using the /is warp, but only if the island get a good level, fully customizable. I think it's useless to allow warp creation when you get a bad island (level 15 by example), that's why i suggest this.
You can say "use the /tpa (name)" to go in someone's island, but i want players see my island everytime, when i'm connected or not. 

I hope you enjoy the idea,

zebigboss72

**Comment by rlf** [comment]
That is already doable (with the current challenges).
Just add a challenge that is completed on islandLevel, and add a permission as a reward, i.e. the `usb.island.warp` and `usb.extra.addwarp` permissions.

**Comment by rlf** [comment]
Closing in lack of further response from original poster
