### ISSUE TITLE
Is bedrock necessary?

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#376]
Looking through the code, it seems bedrock is used for getting the island location for registering a player to an island (uSkyBlock.devSetPlayerIsland) and for determining if an island is at a location (uSkyBlock.islandAtLocation).

Think it would be possible to accomplish both of these by looking for an island region at a location, getting coords from an island file at that location, some simple math using the island protection and size ranges from the config, or a combination of those?

**Comment by rlf** [comment]
Perhaps - but since there are no guarantee the region exists - especially when upgrading from older versions - it's not a reliable solution.

Why do you mind the bedrock?

**Comment by BlackBeltPanda** [comment]
It's just come up as a problem a few times. For example, there are block glitches that allow you to destroy bedrock which some of my players have used in the past and it created problems with the plugin determining there was an island there. I also like to give varying degrees of limited World Edit capabilities to donators but some World Edit commands allow removing the bedrock which causes issues again.

The World Edit thing is obviously something I can prevent, but the bedrock destruction glitches always seem to crop up, lol. Here's an example of one: https://www.youtube.com/watch?v=5GDykR2BLlc&feature=youtu.be

**Comment by rlf** [comment]
Since the bedrock is primarily (as you mentioned) used on admin commands, I guess an admin can easily put a bedrock there, before executing the command.

For island detection, bedrock is only one of many tests performed.

**Comment by BlackBeltPanda** [comment]
Yeah, that's what I've been doing.
Mainly just curious if there was a good way to test for islands without it. If bedrock isn't used in any player interaction outside of admin commands, replacing it when I need to run admin commands is no biggie. =)

**Comment by mcraftpete** [comment]
k , how would you know exactly where to put it , does it have to be in the exact same place as it was previously ? I have multiple on my islands as in lots of bedrock

**Comment by dutchy1001** [comment]
I would indeed put it on the same coords as it original was,\\
The reason behind this is that USB and WG have created the region sizes based upon these coords. IF you change the coords, in any direction, the whole region will or could change which then can cause problems to the island regions next to it.

The orginal coords can be found in the "players" folder int the "playersname".YML. The height (Y) is not as importand as the X and Z as it creates a region from top to bottom.
