### ISSUE TITLE
Flames and lava not working anymore

### ISSUE THREAD

**Issue by JG6521** [rlf/uSkyBlock#378]
hi, we are having really bad issues with are skyblock since the new update.. we have a lava issue where it wont kill animals, but will kill players & flame on bows will not work, we have looked into the files an cant find out why.. any info would be really helpful, thank you

**Comment by dutchy1001** [comment]
What version do you use and what are the depended plugin versions?
The protection system can be changed in the main config (near the bottom of the file)

**Comment by JG6521** [comment]
i will check with my head-admin/GOP and see what version and let you know

**Comment by rlf** [comment]
a) Flames on bows won't hurt anyone in your party, or on another island (this can be disabled, but only if PvP is ON).
b) Lava will always damage players on their own island (as well as animals).

**Comment by JG6521** [comment]
the GOP wont tell me all the plugin's we use as am only ranked admin, but we have had this problem for about 4-5 months now, lava will hurt people, but not animals, and for the flame part, even in pvp zone flame will not hurt anyone at all, this is kind of annoying and cant figure out what is causing the problems

**Comment by rlf** [comment]
Most likely AnimalProtect or something similar - perhaps even just the change in World-Guard.

**Comment by dutchy1001** [comment]
If the main Admin of your server will assist in this matter to solve it then let us know.
For now I will close this, but can reopen when the main admin post here or he can open a new issue
