### ISSUE TITLE
Request: Consistent challenges.yml configuration

### ISSUE THREAD

**Issue by c0wg0d** [rlf/uSkyBlock#379]
In bug #251 you added the option to put reward items each on a separate line, with probabilities.  I would like the ability to add items one per line for the requiredItems line and the repeatReward items line (that one may already be implemented, not sure).  I would also like the ability to put block/item names instead of the ID so it's easier to read.  For example:

<pre>
cobblestonegen:
  requiredItems:
  - cobblestone:64;+2
  displayItem: cobblestone
  reward:
    items:
    - leather:3
  repeatReward:
    items:
    - leather:1
</pre>

**Comment by c0wg0d** [comment]
Just to add more to this, if you use comments on the same line, uSkyblock will not properly parse the config and will throw an error unless you use quotes.

This works:
<pre>
items:
- '4:64' #64 cobblestone
</pre>
This breaks:
<pre>
items:
- 4:64 #64 cobblestone
</pre>

**Comment by rlf** [comment]
Doesn't sound like a "uSkyBlock issue", but rather a Bukkit issue.
We rely on the "built-in" Yaml support (which sucks big-time).

**Comment by c0wg0d** [comment]
Fair enough, but I'd still like to have requiredItems be on separate lines and be able to use Bukkit material names.

**Comment by dutchy1001** [comment]
Think this has been looked into and changed. Closing for now, if needed we can reopen this
