### ISSUE TITLE
Request: Disable all automatic purging.

### ISSUE THREAD

**Issue by Deathinflames** [rlf/uSkyBlock#380]
We would like to request the option to disable any and all automatic purging. We prefer to have all island purging to be done by hand via command instead of the plugin deciding whose islands it should be purging. We've tried setting purgeLevel to 1, however worldguard regions are still being removed, and islands that have a level higher than 1 are being overwritten. If possible, we would also like to request more detailed information on how the plugin is actually purging. What factors other than island levels is it taking into consideration when marking islands for purge? Thank you!

**Comment by dutchy1001** [comment]
If you dont want to use the purge system you can manual delete an island (I think the purge isnt optimal yet).
Use the command "/usb island remove <playername>"  to remove any party members (if there ofcourse) and use the command "/usb island delete <islandowner>". This should delete the island and region and add the location to the "orphan.yml" so it will be used again when a new player creates an island.
You can set in the "challenges.yml" if challenges are reset or not.

**Comment by Deathinflames** [comment]
We have actually been manually deleting islands via "/usb island remove/delete, however the purge system is still performing unauthorized purges based on user inactivity. This is the feature we would like to have disabled altogether.

**Comment by rlf** [comment]
What version are you using? And are you actually using uSkyBlock?

The reason I'm asking is, we don't have any "automatic purging".

**Comment by Deathinflames** [comment]
Output from /usb version: http://i.gyazo.com/954cb62ee66d9cbca1b35ac043c24676.png

I believe the issue occurred when updating to https://github.com/rlf/uSkyBlock/issues/243 awhile back. We only noticed an issue recently when new players were starting to have their islands generated where old islands used to exist, thus inheriting the old owner's materials. The old island owner is also in the new island owners party and is unable to be kicked.

Best way i can describe the issue is with a picture of our skyworld via DynamicMap with worldguard extension. http://embed.gyazo.com/694c60782f756c756eb95e1e840c0d30.png

Every single island within this world used to have a worldguard region.

This is the result for a new player: http://embed.gyazo.com/a649a114c4cebf9decdf574f30038d54.jpg

You can see our custom island schematic is placed right in the center of the old island. Worldguard regions for old islands are only re-created when those island owners login. I also have to mention that our skyworld is extremely old, we have used uSkyBlock since Talabrek first released it.

**Comment by rlf** [comment]
Well, the problem isn't "automatic purging" then, but rather that your island-data has been corrupted.

A possible "workaround" for now, would be to manually set the lastIslandConfig.yml to a (valid, aligned) position of a free-slot for an island.

At least that way, new islands won't take over old ones.

**Comment by Deathinflames** [comment]
Sorry, i had no other way to describe it, we will use the workaround. I am thinking a world wipe is necessary at this point though, sometimes its nice to start fresh.

**Comment by dutchy1001** [comment]
Is this issue solved by manual editing the "lastIslandConfig.yml" ?
if so let us know so we can close it.

**Comment by Deathinflames** [comment]
@dutchy1001 This did provide a temporary workaround, thank you, this ticket can be closed now.
