### ISSUE TITLE
how to setup uSkyBlock?

### ISSUE THREAD

**Issue by julesle123456789** [rlf/uSkyBlock#382]
How do I set it up once its in the server?

**Comment by dutchy1001** [comment]
How do you mean? did you read the [bukkit](http://dev.bukkit.org/bukkit-plugins/uskyblock/)  or [wiki](https://github.com/rlf/uSkyBlock/wiki) pages?
Watch the video on the bukkit page for an explanation.

**Comment by julesle123456789** [comment]
I mean like when I put it on my server how do I make it work/avtivate it

**Comment by dutchy1001** [comment]
In the video on the bukkit page it will explain what to do and what permissions your players need. Also on the page [commands & permissions](http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/commands-and-permissions/) you see what commands you need to start an island and which permissions are needed.

**Comment by julesle123456789** [comment]
but that isn't the problem the problem is in the begining how do I set it up?

**Comment by dutchy1001** [comment]
Quote from bukkit page:
>Just place the .jar in your plugins directory and (re)start the server. The skyblock world, config, and all other files are automatically generated.

Not sure what else you mean
