### ISSUE TITLE
The server has stopped responding!

### ISSUE THREAD

**Issue by JohOply** [rlf/uSkyBlock#383]
Hi

Since MC 1.8, your plugin seems be unstable (lag, crashes...)

I use Spigot 1.8.3-b422 and uSkyblock 2.3 then 2.3-HF3

http://pastebin.com/xHN0RsHL

Thanks in advance :)

**Comment by rlf** [comment]
Checkout the v2.3-HF6 release, the restart now takes a longer time to complete, but it should improve the impact on server-performance.

**Comment by mcraftpete** [comment]
Hi
The above is still the case , I also experience server lags crashes and more using latest version , it seems to be getting more and more unstable , its definitely usb each time as you can see the timings are way way higher then anything else.To make it worse I upgraded to latest version which means loads of players now have trusted players on their islands so I cant downgrade as they would not be able to remove them,
Please can you let us know some kind of update on performance /lag / crashes ?

**Comment by rlf** [comment]
Sorry for the late reply - I have been occupied elsewhere.

I will try to get some "uSkyBlock-time" squeezed in this weekend.

**Comment by dutchy1001** [comment]
many improvements have been made since, if still an issue I will reopen it
