### ISSUE TITLE
PVP deny/allow not changing WG world config after changing.

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#384]
When deciding to change the setting in the config from "AllowPVP: deny" to "AllowPVP:allow" only new islands are getting the new setting in the WG world config.
Would it be possible to have it change all the regions or maybe move it to the global region so only 1 needs changing.

**Comment by rlf** [comment]
v2.3-HF6

**Comment by dutchy1001** [comment]
there is a delay before the WG config is updated but it changes the setting as it should.

Fixed in HF6
