### ISSUE TITLE
Unhandled exception executing command 'is'

### ISSUE THREAD

**Issue by Deathinflames** [rlf/uSkyBlock#388]
Receiving an internal error when performing 'is create' on a fresh server with the versions of Vault, WorldEdit, WorldGuard, uSkyBlock listed in the link below.

Error: http://pastebin.com/vQhjNWCn
USB Version: http://i.gyazo.com/5c0662451442d74d5cbd02a2e5c37f6a.png
Plugins: http://i.gyazo.com/e9770efc36fa128e2f0954f9f2d00ab2.png

Going through GUI results in a successful island generation.

Also, sometimes when re-logging from the server, 'is home' will result in a "No Island.", but using the GUI will allow you to return to your island.

**Comment by dutchy1001** [comment]
Using the term" the latest" is not acceptable when if you do the command "usb version" in console or "/usb version" ingame tells you exactly what we like to know to help solving problems.

The "/is" issue is known but no fix has been made yet

**Comment by rlf** [comment]
We are aware of that bug, and am looking into fixing it.

**Comment by dutchy1001** [comment]
This should be fixed, I havent come across this in the later pre-releases.
Closing it for now, but if reoccur let us know.
