### ISSUE TITLE
Party and Biome view/override commands for admins

### ISSUE THREAD

**Issue by c0wg0d** [rlf/uSkyBlock#390]
I would really like the ability for admins/moderators to view who is in an island party without having to use worldguard commands, and also the ability to add/remove members from islands.

I would also like them to be able to view what biome is set for an island, as well as change the biome of any island.

Thank you for considering this feature request.

**Comment by rlf** [comment]
a) `/usb island info <player>`
b) Biome, not possible currently, except by using `/usb goto <player>` and checking F3.

b) sounds as a good feature request.

**Comment by dutchy1001** [comment]
this has been added in the versions after HF6d as far i know
