### ISSUE TITLE
Island Create and Spawn back bug

### ISSUE THREAD

**Issue by mac989898** [rlf/uSkyBlock#391]
is there a solution for the bug where everyone on my server when they create an island they are there on the island for about 3 seconds and then are just bounced back to spawn? I do have the plugin using the essentials spawn. Is this bug just going to have to be there for a while or is there a fix that i can do. (My server is 1.8)

**Comment by dutchy1001** [comment]
We are aware of this bug and we are looking into the issue.

**Comment by mac989898** [comment]
Thanks for the reply good luck trying to fix it.

**Comment by rlf** [comment]
The only reason we are currently porting the players in the first place, is the client-update-glitch, which might have been fixed in the latest Spigot releases.

We will take a stab (more) at it.

**Comment by mac989898** [comment]
@dutchy1001 is there a possibility there could be a bug fix version sent out that removes the teleportation after island creation and replaces it with text something like "Island Created! Type /is home To Go To Your Island!" Or are you guys close to fixing the bug?

**Comment by dutchy1001** [comment]
It looks like the next update will have that fixed.
A test version is in the "release" section on github (it's a pre-release so there could still be some other bugs present).

**Comment by mac989898** [comment]
Thanks so much =D

**Comment by dutchy1001** [comment]
Fixed in version HF6c
