### ISSUE TITLE
Players have "god" mode in my uSkyBlock world (probably misconfiguration)

### ISSUE THREAD

**Issue by sd92-sk** [rlf/uSkyBlock#393]
Hello! I'm having problems with my world where uSkyBlock is running. Players aren't hurt by lava, drown in water, fall damage, even falling deep into void wont do anything. However hostile mobs do deal damage.
When i lookup player with /whois command, it says he doesn't have any godmode or creative enabled.
On other worlds this isn't happening, only here.
I looked at configs of plugins MultiInv, MultiWorld, WG, WE, CreativeControl, Essentials, PermissionsEx and haven't noticed where such protection could be enabled.
I even put -essentials.gamemode.creative into skyworld so people shouldn't switch to it.

Server: CraftBukkit git-Spigot-1543 (MC: 1.7.9) (1.7.9-R0.3)
Ultimate SkyBlock v2.3-b3ca9e-dev
WorldEdit 6.0;3342-78f975b9
orldGuard 6.0.0-beta-02
Vault 1.4.1-b436

EDIT: I just updated to WorldEdit (6.1;no_git_id), WorldGuard (6.1), and the problem is finally solved!
You can keep this post, maybe it would help somebody.

**Comment by dutchy1001** [comment]
It was known that WG beta 02 had problems, glad you fixed it.
