### ISSUE TITLE
Chunk crash

### ISSUE THREAD

**Issue by Pixiio** [rlf/uSkyBlock#394]
Since yesterday our Skyblock server keeps crashing every now and then. Before a crash the server lags like hell and 1/2 minutes after that it crashes.

Spigot: 1.8.6
uSkyblock: V2.3-HF3
Crash log: http://pastebin.com/afPSa0Xw

Thanks alot.

**Comment by dutchy1001** [comment]
first i would upgrade spigot to 1.8.7.
Can you tell us the dependend plugins you use.

As you said "since yesterday" I presume before that it worked fine then. What plugins have you updated yesterday ??

**Comment by Pixiio** [comment]
Hi Dutchy,

Thanks for your fast reply.

These are the plugins we are using: http://pixsh.nl/i/7I59E.png
Also i've tryed Skyblock version v2.3-HF6b but the lag did increase since then. http://timings.aikar.co/?url=11706885

I did not update any plugins. I'm going to update to 1.8.7 now.

**Comment by dutchy1001** [comment]
you could check if 1 of the islands has a massive mob/animal farm build, that will cause some lag aswell sometimes

**Comment by Pixiio** [comment]
We have a MobLimiter http://www.spigotmc.org/resources/farm-limiter.1419/ and ClearLagg http://dev.bukkit.org/bukkit-plugins/clearlagg/ so i don't think so.

**Comment by dutchy1001** [comment]
We do know there are sometimes issue's with the lag but it's hard to figure out were it comes from.

**Comment by Seadragon91** [comment]
@Pixiio 
Chunk problems is a common problem in minecraft. Did you already tried to download the region that contains the chunk and tried to open it in mcedit, to look into it?

If you have still problems, I would suggest this tool.
https://github.com/Fenixin/Minecraft-Region-Fixer

Good luck.

**Comment by Pixiio** [comment]
Hey Seadragon,

Thanks for your answer, i think that helped.
Although we just crashed again: http://pastebin.com/2i8wZuYj

Please help.

**Comment by Pixiio** [comment]
Also the newest build laggs like hell: http://timings.aikar.co/?url=11735065

**Comment by Pixiio** [comment]
This build solved all of our issue's: https://github.com/rlf/uSkyBlock/releases/tag/v2.3-HF1c

**Comment by dutchy1001** [comment]
Weird that an older build fixed it. Glad it works noww
