### ISSUE TITLE
Translate menu.yml

### ISSUE THREAD

**Issue by LgRmael40** [rlf/uSkyBlock#395]
How to translate the file menu.yml

**Comment by dutchy1001** [comment]
Have a look at this page [here](http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/localization/).

**Comment by LgRmael40** [comment]
I am looking how to translate the GUI menu

**Comment by dutchy1001** [comment]
only to translate the GUI is not possible, we still working on the language system

**Comment by LgRmael40** [comment]
There is a means to translate without demand po

**Comment by LgRmael40** [comment]
???

**Comment by dutchy1001** [comment]
not at the moment

**Comment by dutchy1001** [comment]
As you cant do this atm and were still working on the language system I'm closing this issue.
