### ISSUE TITLE
Gray chat in skyworld only

### ISSUE THREAD

**Issue by ChiuChiuTrains** [rlf/uSkyBlock#396]
Hello uSkyBlock devs,

There seems to be an issue that I cannot replicate on my server. When players are in the skyworld their chat turns dark gray and they cannot see the global chat. Only players in global can see both the gray chat and the global chat. 

http://prntscr.com/7gvcyj <--- here is the screenshot of the chat.

Are there any ideas as to why this is happening? It never seemed to do this before and since it only applies to the skyblock world my assumption is it was caused by either uskyblock, the worldchat plugin or multiverse.

If you can explain why this is happening or at least rule out that it is not skyblock that would be greatly appreciated.

http://prntscr.com/7gvdyd <--- plugin list.

We are running spigot 1.8.7-R0.1 Snapshot

- ChiuChiuTrains

**Comment by ChiuChiuTrains** [comment]
Irrelevant issue to uskyblock sorry about that! :) 

=Solved=

**Comment by dutchy1001** [comment]
lol glad you sorted it
