### ISSUE TITLE
Include Leaving Islands and Kicked Island Members in /usb island info <player>

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#397]

**Comment by dutchy1001** [comment]
I'm sorry but closing this. 
To me it makes no sense  without any kind of explanation.

**Comment by TheMattVid** [comment]
The command already has a log of all players who have been invited to an island and who have joined an island. It would be convenient to see when a player has been kicked or has left probably for similar reasons to why it shows when they were invited or joined.

For example, when a player leaves an island, I can unlock the chests for the island owner so that the island owner gets the rights to the items in his chest. If the island owner kicked the player off, perhaps the player is entitled to some of the items included within his locked chests. The dates of these events also help to clear things up. I can compare the kick date to the player's last login date to justify the island owner's motivation for the kick.

**Comment by dutchy1001** [comment]
When a player is part of the party on an island the owner can open their chest(s). When that player is kicked of the island, for whatever reason, the owner can still open the chest of that player. If a player decides to leave the island, the island owner can still open that chest.

To add the comings and goings of players to an island can start to take up an immense data base on a server. 
For that reason I cannot see this implemented without the use of a MySQL (wich has been talked about) any time soon.

If you use alternative plugins to protect individual players chest then that is not for USB to log when the were last accessed/used, maybe to ask them to make a log that tells you that information.

I'm not sure if Prism plugin is still active but that can log anything including who last opend a chest (with date and time) and much more.

**Comment by TheMattVid** [comment]
I see your point about the large amounts of storage used by this. The chests thing was just an example, but I'm sure others could come up with other conveniences of this feature. This is not a high priority for me though. It was just an idea for a feature that could further enhance this plugin.

**Comment by rlf** [comment]
Currently the "island log" only holds the last 10 entries.

But we could add that (if it's not already present) to the /usb island info command
