### ISSUE TITLE
Chat for island members

### ISSUE THREAD

**Issue by MineTheCube** [rlf/uSkyBlock#398]
I **know** that there is already an issue talking about it, and it was rejected because someone wouldn't use it.
But for those who want an island chat ?

As rlf said, is would be quite easy to implement an island chat, moreover there is no plugin to achieve that.
So why not add this feature, only if it is enabled in config, with simple options like:
- chat-enabled: true/false
- chat-format: "&e%player&r: %message%"
- only-in-skyworld: true/false

**Comment by csorrows** [comment]
I don't think this feature is needed although I have seen quite a few players demanding I ask for it. So here is my +1

**Comment by dutchy1001** [comment]
Island chat is implemented

**Comment by csorrows** [comment]
My players will love that. I look forward to the next stable release. Thanks @dutchy1001 & @rlf !!

**Comment by rlf** [comment]
Just some notes:
a) the chat-format will be located in config.yml, options.party.chat-format
b) It is enabled by the permission usb.party.talk
c) It is invoked with /islandtalk, /istalk or /it
d) It sends messages to all online-members, regardless of which world they are in.

**Comment by csorrows** [comment]
That sounds like an awesome addition. As always you have taken an idea and went way beyond.

**Comment by dutchy1001** [comment]
that info will be on the new bukkit site and here in the wiki soon

**Comment by csorrows** [comment]
Thanks guys. You guys rock.
