### ISSUE TITLE
Config files should update when needed

### ISSUE THREAD

**Issue by pickledrange** [rlf/uSkyBlock#40]
When updating my plugin from version v2.0.1-R0.6 to version v2.0.1-R0.7 the additional information was not added to the config.yml or the challenges.yml

I don't know if this is supposed to happen or not but i'm sure players aren't going to want to (and/or remember to) delete the files to let the plugin regenerate the updates only to have to change their settings again

obviously not an issue for new servers but existing ones may have issues with files not updating.
Not sure what can be done about this

**Comment by rlf** [comment]
Fixed in v2.1.3

**Comment by dutchy1001** [comment]
tested this today and the "levelconfig" shows some weird merges, 
http://pastebin.com/QP2Adt9e <-- is pastebin what I get
http://pastebin.com/2rr3SXy9 <-- as it should be

All the value's like this '17:1-5': -1 or '18:0-3': 0 are now looking like 17:1-5: -1 or 18:0-3: 0 missing the ' 
Value 8 and 9 are totaly weird merged.

After fixing this manual it definitely changes the value's of those ID's
![2015-01-29_10 17 22](https://cloud.githubusercontent.com/assets/5569980/5956013/e0f2d834-a7a0-11e4-9eb1-b36bbe3dbb4e.png) Before the manual fix

![2015-01-29_10 19 07](https://cloud.githubusercontent.com/assets/5569980/5956019/eebfea38-a7a0-11e4-85a5-712e15f73176.png) After the fix

You can see there is a big differance in points, I lost 14.67 points. The Spruce logs are now gone of my listing as it reached the max deminishing points Oak is added while they were there to begin with.

**Comment by rlf** [comment]
Frakking Bukkit Yaml handling... should be put to sleep.
It seems the only "viable" way forward - is writing our own Yaml parser/writer - which just sucks.

**Comment by rlf** [comment]
Should be fixed in v2.2-HF4

**Comment by rlf** [comment]
**Note:** levelConfig.yml will allways overwrite the existing one, config.yml will allways try to be merged (removing comments). Any existing config files will be moved to the `/plugins/uSkyBlock/backup` folder.

**Comment by dutchy1001** [comment]
Backup of the yml's are saved in the backup folder and value's are not changed when merging. All good now.

Fixed
