### ISSUE TITLE
Performance issues, low TPS and high resource usage.

### ISSUE THREAD

**Issue by suedadam** [rlf/uSkyBlock#401]
http://timings.aikar.co/?url=11746947
uSkyblock is causing a lot of resource usage and lagging the server. 

let me know if you need any other information.

**Comment by mcraftpete** [comment]
Im pretty sure the devs are aware of this , I also have very high , in fact way higher readings then yours with much less players on , and it is also from skyblock , onjoin onleave and namechages etc , is restarts all causing a lot of lag , after a server restart with lots of ppl logging in the server almost dies for a while.

**Comment by mcraftpete** [comment]
http://timings.aikar.co/?url=11762591
my latest timings with a small 30 players online , the server used to be busy but is gradually dying due to lag and crashes , if you look at above report you will see skyblock is way in excess of what it should be for so few players.

**Comment by rlf** [comment]
It seems two of the "improvements" made earlier, clashes.
I.e. once will try to spin off the "player-rename" on login, and the other tries to avoid a concurrent modification.

Definitely something we need to look into.

**Comment by mcraftpete** [comment]
also players that have changed name on most recent version isn't working :( , just had 2 players today that changed name and nothing updated

**Comment by rlf** [comment]
With those timings, odds are, the code is executed, but is hanging.

I will try to prioritize this - and see if I can reproduce it.

**Comment by mcraftpete** [comment]
I would likely agree with it hanging , as we get lag spikes , can seem fine 1 minute then a massive lag , checking tps at time can be way into minus figures but then 15 seconds later back up to near 20

**Comment by mcraftpete** [comment]
![tps](https://cloud.githubusercontent.com/assets/5656426/8378376/cfe593ee-1c10-11e5-82dc-f48b9c5848c3.jpg)
example of onleave/onjoin where you see the clear spike in tps , when I do timings during that patch you can see skyblock looking pretty bad and no other plugins having any lag , but the low timings is actually in spikes making it feel pretty awful for a few seconds then fine for a while , above timings reports in earlier message up are average over that time , it definitely spikes badly.This is definitely since the most recent version.

**Comment by dutchy1001** [comment]
This is exactly what I been seeing that it hangs and then get beck to 20TPS
This is happening the last few days on my test server.
I know it's hard to see in my pastbin but as I'm bound to craftbukkit the timings are not working properly. 
http://pastebin.com/Fg2r2mTt
If you look through all the log you ssee the tps jumping from -60.01 back to 20 ( i seen -179 give and take a few numbers lol)

**Comment by rlf** [comment]
We hope to adress this issue with #406

**Comment by dutchy1001** [comment]
performance has been improved in later versions, if problem still exists open a new issue
