### ISSUE TITLE
Feature request - Ability for players to view trusted

### ISSUE THREAD

**Issue by mcraftpete** [rlf/uSkyBlock#402]
Hi,
I really like the new trusted feature , the only worry is players cant easily see who they have trusted if they don't remember , experience tells me I am open for griefing reports regular as players do this on plotme already , they add and forget , but on plotme they can at least view and staff can to and remove the culprits and teach the player about adding players.
So trut is a great feature but needs the info of whos trusted easily accessible,

**Comment by rlf** [comment]
Accepted

**Comment by rlf** [comment]
`/is trust` now shows who trusts you, and who you trust.
Note, a bug in < v2.4 makes the list a bit gibberish for some.
