### ISSUE TITLE
usb island delete player - not adding to orphans file

### ISSUE THREAD

**Issue by mcraftpete** [rlf/uSkyBlock#404]
Hi,
I would have assumed that when I run this command it will delete the player and the island , and the island would auto add to the list of orphans so it can be re-used.
I also notice that the blocks don't seem to render properly after a delete , they appear to be inplace to anyone around them but physically are not there , even reclogging they sometimes appear to still be there , is this a bug , is it that when someone else claism the island it will reset.
I am more curious at what point it resets the area and how much of the area is reset , I assume the whole 110 blocks area ?

**Comment by mcraftpete** [comment]
version usb2.3 - hf6d

**Comment by mcraftpete** [comment]
lol soz we 6.1.1 and wg 6.1.1

**Comment by rlf** [comment]
The rendering is a client-side glitch (Bukkit/Spigot apparently doesn't inform the client correctly, when chunk-data changes) - a `/spawn` followed with `/back` usually fixes it.

**Comment by mcraftpete** [comment]
is it suppose to add to the orphans file at the time of delete ?

**Comment by rlf** [comment]
We discussed it earlier, and yes, I think `delete´ should. But the whole orphan feature is somewhat buggy imo.

**Comment by mcraftpete** [comment]
Hi,
I worked with dutchy today and the reason this didn't complete an /usb island delete player , is that a lot of my islands do not have wg regions , so by running /usb island protect player first thi now works as intended , so it sets playerfile to hasisland false location 0 0 0 ,  it deletes wg region and island and adds it to the orphans list as intended :)

**Comment by dutchy1001** [comment]
glad to be of help

**Comment by dutchy1001** [comment]
This issue should work properly aslong the island has a WG region allocated to it. The iddue mentione here is working fine in that case.

closed
