### ISSUE TITLE
Way to Language change?

### ISSUE THREAD

**Issue by SamuelGold** [rlf/uSkyBlock#408]
Hello!
Is Language system works?
I change in config.yml:

language: nl

And restart server. Nothing happens, lang still is en on SkyBlock menu.
I try version v2.3-HF6d, thank you for any help.

**Comment by dutchy1001** [comment]
There are still some issue's we're working on with the language system so you have to bare with us. I have only managed to do 50% of the translation into dutch and hope to have some more time later this week.

**Comment by SamuelGold** [comment]
Thank you for the quick answer, so the language system still in development and does not work?
I try language: da, an it does not work also.

**Comment by rlf** [comment]
Language support is still in development.
We haven't gotten the plugin 100% translated to any particular language yet.
We have also some out-standing issues on the enablement of a language.

**Comment by SamuelGold** [comment]
Thank you,  if you have some free time, please try to fix it. My players like uSkyBlock, but translation is a real problem for them.

**Comment by dutchy1001** [comment]
The current language system will be changed to something else. No point to keep this open now.

Closed
