### ISSUE TITLE
Island Purge Command Not Working

### ISSUE THREAD

**Issue by MeddlingMoose** [rlf/uSkyBlock#409]
When I go to use the island purge command nothing really happens, uskyblock marks out all the islands that -should- be deleted... but then the server lags out, and crashes. Upon restarting the server the islands all still very much there, nothing has been purged.

Not sure what's causing the issue. Next time my server is empty I'll run the commond and see if I can get a crash log.

**Comment by dutchy1001** [comment]
We know there are some problems with the purge system.
You can manual delete islands for now with the "/usb island delete [name]" command (make sure they have an WG region).

**Comment by MeddlingMoose** [comment]
@dutchy1001 alright! Thanks, just wanted to make sure you guys were aware :) I will post the crash log as soon as I can.

**Comment by MeddlingMoose** [comment]
Hey again! I just went to delete a single island any things went a little haywire. The server didn't crash but we got down to 6tps. I reloaded the plugin quickly and everything recovered after that.

I know this isn't the same as a crash report, but I figured this timings report would help a little.
http://timings.aikar.co/?url=11907391

**Comment by dutchy1001** [comment]
thank you for your timings report, they do help us finding out issue's.

**Comment by rlf** [comment]
Fixed in v2.4.1
