### ISSUE TITLE
purge, admin commands & island help

### ISSUE THREAD

**Issue by JG6521** [rlf/uSkyBlock#410]
we have a problem with the purge, we have around 10,000 islands within a month, and most of them are inactive, is the anyway you can implement you can put in a auto purge maybe once a day where it clears the inactive islands as it will crash every time we try it, and can you make it where we can bypass the time when people restart islands so they dont have to wait 7 days for a new one? also 1 last thing, is it possible you can add more admin commands? the server we are running is aliacraft, been asked to ask by the head-admin, thank you for your time!

**Comment by dutchy1001** [comment]
I dont think an automated daily purge will be implemented, atleast not for now. We know that there are issue's (see #409 )with the purge system. However deleting them manual with "/usb island delete playername" is an alternative option for now.

The bypass for island restart can be set in the main config.yml (cooldownRestart: 30) this is in seconds. If it is set to 7 days then I assume the head-admin has set that for a reason (default is 30 seconds).

What kind of admin permissions are you looking for? Mixing mods and admins perms gives you all perms

**Comment by rlf** [comment]
I promoted this to a feature request - I always miss these sort of options on other plugins - and I guess we should take it into account, when trying to make the purge actually work.
Related to #406 and #409

**Comment by JG6521** [comment]
thanks for the replies, i will get back to my head-admin & let you know what he says :)

**Comment by rlf** [comment]
Commit 8bc7132419b697f7b707abb4be505cf0c8703264 brings us closer. Will add support for a cron-type of expression as well. For running it.

**Comment by rlf** [comment]
We now have an improved purge system, but no cron-expression yet.

**Comment by rlf** [comment]
Closing this, as the cron-part can easily be done by other means:
a) Either set up a scheduled task on the server (most admin interfaces allow this)
b) Setup http://dev.bukkit.org/bukkit-plugins/consolescheduler2/ to execute the purge command when wanted.
