### ISSUE TITLE
Configurable Delay for Island Invites

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#411]
When I mute disruptive players, they are still able to spam players with this command. I prefer not to ban players if I don't have to. A built-in command delay would be extremely useful.

**Comment by dutchy1001** [comment]
When muting a player they can still do (any) commands through chat, Just remove the "usb.party.create" for those players.
Personally I dont see this needed or the point for it.

**Comment by rlf** [comment]
I would suggest upgrading the mute to a tempban in that scenario.
Should stop the spamming quite fast...

**Comment by TheMattVid** [comment]
That's exactly what I did when this happened, dutchy. I negated that permission.

I suppose this feature is not very necessary, but it would be nice. I wouldn't mind if it was put on the bottom of the to-do list.
