### ISSUE TITLE
Island Invite not working

### ISSUE THREAD

**Issue by VizionStudiosMc** [rlf/uSkyBlock#412]
Hello when players try doing /island invite its keep saying they don't have permission but I check and they have the  permission because players was ably to type /is and get a island but they could not join or be invite to one my server ip is VizionMc.com if you like to see for your self.

**Comment by dutchy1001** [comment]
What permission did you give?
Been on your server but with no one else there I could not use /is invite [playername] as you cant invite yourself.

**Comment by dutchy1001** [comment]
Invite works on all my tests.

Closed
