### ISSUE TITLE
dev island protectall

### ISSUE THREAD

**Issue by mcraftpete** [rlf/uSkyBlock#413]
Hi,
Sorry to add another issue , but last week with dutchys help I ran /dev island protectall command.
At end of just over 3 hours it said 32,500 islands successfully protected or something along those lines.
I assumed at this point that all islands would now be protected.
However I am since finding lots of unprotected islands , if I read in the islands folder in skyblock to find the island matching with an area I stand to find the matching island owner and do /dev island protect playername  it protects it fine so its not like theres an issue with the player so for some reason protectall is not fully working.
is it possible to confirm whether it only does a certain amount , maybe it is only set to run 1000 or something ?

**Comment by mcraftpete** [comment]
I am currently re-running the command , on thinking about it 32,500 islands in 3 hours would of been coverting 180+ islands a minute 3 a second so I am pretty convinced it was incorrect , re-running in console is showing protected players island and listing many so I am fairly sure it was not completed.
So I will keep you posted :P

**Comment by rlf** [comment]
Thanks.
