### ISSUE TITLE
Mobs aren't spawning

### ISSUE THREAD

**Issue by FunnyMannyMC** [rlf/uSkyBlock#414]
Hey,
I have a problem, in my skyworld there aren't spawning any mobs, only like 1-2 mobs per night, maybe even not them. I don't know what's the problem, i have checked every plugin that can block mobs from spawning... but i can't find the problem.
uSkyblock version, worldguard/edit, vault & server version: http://gyazo.com/ca27923a72fc39cae117dac8b6c919ae

**Comment by dutchy1001** [comment]
We dont interfere with the default spawning of mobs (aggressive or passive). It sometimes takes a while before they spawn.

**Comment by FunnyMannyMC** [comment]
What to you mean by "It sometimes takes a while before they spawn."? The plugin has been on about 7-8 days. Can the other worlds somehow change the spawning on skyworld? Like maybe a lot of mobs spawn in the main world and then its like unbalanced and no mobs spawn in skyworld.

**Comment by dutchy1001** [comment]
All I can say is that we never altered anything in our code that has to do with the spawning of mobs. It's "vanilla" minecraft for the spawning.

Other worlds will not influence the mob spawning for the skyworld, it's something to do with the amount of loaded chunks and then the distance the spawn from a player.

**Comment by dutchy1001** [comment]
No further comments and mobs do spawn.

Closed
