### ISSUE TITLE
trust

### ISSUE THREAD

**Issue by voigtman** [rlf/uSkyBlock#417]
/island trust doesn't appear to be working

**Comment by dutchy1001** [comment]
This command is only in a pre-release present and not on the release on Spigot or bukkit yet.

**Comment by voigtman** [comment]
Ah, well bugger. I like that idea!

**Comment by dutchy1001** [comment]
It will be part of the next release as the testings for this command has been successful. 
If you cant wait get a pre-release but be aware there can be other bugs in those versions.

**Comment by dutchy1001** [comment]
closed
