### ISSUE TITLE
requiredEntities don't work

### ISSUE THREAD

**Issue by manercraft** [rlf/uSkyBlock#419]
Default challenge Villager and passif mobs don't work
"requiredEntities" don't detect

Version:
http://i.imgur.com/cxxt4ns.png

**Comment by manercraft** [comment]
It's fixed in v2.3-HF7b or v2.3-HF7c ?

**Comment by dutchy1001** [comment]
Sorry but due to the grammar I cant make out if it's a question or conformation that it's fixed. So far v2.3HF7c has many fixed done by our new team member Harry5573 so that is your best bet to try.

**Comment by dutchy1001** [comment]
no further input
