### ISSUE TITLE
Breeding Limit

### ISSUE THREAD

**Issue by Deathinflames** [rlf/uSkyBlock#421]
It would be extremely helpful if there was some sort of breeding limit option available in the config to help reduce lag due to excessive farms. Perhaps a feature where you can specify how many of each friendly entity a player can have on their island? Thank you!

**Comment by dutchy1001** [comment]
I think there are other plugins that can do that. If I find 1 I will post the link for you.

**Comment by rlf** [comment]
Was going to reject this - as I don't see it as a USB responsibility, but I can see the value added on this.

Will investigate what would be needed to have an animal / mob limit per island.

**Comment by rlf** [comment]
Been doing some investigation, and this is definitely doable.

Will be scheduled for next release

**Comment by rlf** [comment]
Fixed in 5803c60a43d55aebbd6ea153bcd9a2686dc9cef1

The breeding limit can be set both as default values:

    options.island:
        # Limits the spawning
        spawn-limits:
          # [true/false] if true, the limits below will limit spawning
          enabled: true
          # how many animals can be spawned within an island
          animals: 48
          # how many monsters can be spawned on an island
          monsters: 50
          # how many villagers can be spawned on an island
          villagers: 16

And as permission based values:

    donor-perks:
        usb.major.donor:
            animals: 100
            villagers: 48
            maxParty: 12

Have fun.

**Comment by Deathinflames** [comment]
Thank you so much for this implementation rlf!

**Comment by Andro609** [comment]
Using normal game mechanics it is possible to bypass all the limits set.
I can give detailed instructions on how if required, but it boils down to: mobs in unloaded chunks are not counted.
(with 'monsters', to prevent them from despawning you would need to TP away (hard to get useful results), or name-tag them...)

**Comment by rlf** [comment]
Necro of the century - we are aware of this, but deemed it was acceptable.
It's a "best effort" limit, only intended to help the server-owners not get too much lag (which you will get for active/loaded chunks with a lot of mobs in them).
As you say, doing this "correct", will be close to impossible to do in a performant manner.

**Comment by Andro609** [comment]
Sorry for the 'Necro'. I'm new to uSkyBlock. Was going to start new issue, but stumbled upon this and thought it would draw less end-user attention here.
