### ISSUE TITLE
update to 1.7.2

### ISSUE THREAD

**Issue by GhostReal** [rlf/uSkyBlock#424]
Hi, im ghostreal and I want to talk about uskyblock versions. what version of uskyblock supports craftbukkit 1.7.2? if there is not, please upload uSkyblock for 1.7.2

**Comment by dutchy1001** [comment]
the current version should work on Craftbukkit 1.7.2, you just need to adjust the depended plugins as mentioned [here](https://github.com/rlf/uSkyBlock/wiki/Installation) for 1.7.9/10.

I will mention that support for that CB version is limited.

**Comment by dutchy1001** [comment]
Older versions are not supported as this would take up to much time. It looks like that craftbukkit versions from before 1.7.9 are not working properly with our updated version. 

Closing this.
