### ISSUE TITLE
Flower Forest

### ISSUE THREAD

**Issue by voigtman** [rlf/uSkyBlock#425]
Hi guys,
The flower_forest biome option isn't changing the biome correctly - it sets it to ocean.

**Comment by dutchy1001** [comment]
go to spawn and back and it should be changed, just tested on last pre-release

**Comment by voigtman** [comment]
relogged and all still ocean.
Perhaps something has changed in the pre-release?

**Comment by dutchy1001** [comment]
can you give me all the info from /usb version

**Comment by voigtman** [comment]
Vault 
1.5.3-b37
WorldEdit
6.1;no_git_id
WorldGuard
6.0.0-beta-05.1569-

**Comment by dutchy1001** [comment]
I could invite you to the public test server and show you it's working normal (uskyblock.redirectme.net). 

I would say that the WG beta 5 isnt the greatest release they did, with the use of the dev builds I have no problems. Get dev builds [here](http://builds.enginehub.org/job/worldguard?branch=master)

**Comment by voigtman** [comment]
Thanks Dutchy, I'll come try it. I am updating to wg 6.1 the official release - after I test it first.

**Comment by voigtman** [comment]
hey the warning about changing your name and losing an island - is this only on the test server's version or all of them so far? i'd like to warn my players if I need to

**Comment by voigtman** [comment]
So the flower forest is setting. Ok, I shall test a few more things. ... This has really made me miss being a player even more. Thanks!

**Comment by dutchy1001** [comment]
this should be working,

Closed
