### ISSUE TITLE
2.3-HF7c Error creating island

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#426]
Got spammed with ~53MB of errors after updating to 2.3-HF7c. Happend after a player tried restarting their island. This is the truncated version:
http://pastebin.com/raw.php?i=6v9vCzYT

Versions:
uSkyBlock: 2.3-HF7c
Spigot: 1.8.7 git-Spigot-6d16e64-09ddd9b
WorldEdit: 6.1
WorldGuard: 6.1

**Comment by dutchy1001** [comment]
This happend in version HF6e, I have the same HF7c on the public test server (uskyblock.redirectme.net) and it's not happening.
Can you check "/usb version" and see if the right plugins are installed ( I know you know what your doing but just to be sure).

**Comment by BlackBeltPanda** [comment]
Yep; versions in "/usb version" match what I posted above:

uSkyBlockVersion: 2.3-HF7c
Description: Ultimate SkyBlock v2.3-HF7c-40f366-dev
------------------------------
Server: CraftBukkit git-Spigot-6d16e64-09ddd9b (MC: 1.8.7)
------------------------------
Name: Vault (ENABLED)
Version: 1.5.3-b37
------------------------------
Name: WorldEdit (ENABLED)
Version: 6.1;no_git_id
------------------------------
Name: WorldGuard (ENABLED)
Version: 6.1
------------------------------

**Comment by BlackBeltPanda** [comment]
Downgrading to 2.3-HF7b fixes the issue; seems to only occur for me in 2.3-HF7c.

**Comment by dutchy1001** [comment]
This is so wierd, i have the exact same spigot build but use dev build from [WE build 3382](http://builds.enginehub.org/job/worldedit?branch=master) and [WG build 1618](http://builds.enginehub.org/job/worldguard?branch=master) with no error when restarting. If it's because I use those "dev" builds i cant tell you.

**Comment by BlackBeltPanda** [comment]
Don't suppose you have a pastebin of the error you were getting? Would like to see if they originated from the same line.

**Comment by BlackBeltPanda** [comment]
Looking at it quickly, it looks like it failed to load the player's info when they tried restarting their island.

**Comment by dutchy1001** [comment]
Ofcourse I have a pastebin of the error
http://pastebin.com/qAtYqxYy
There not the exact same by the looks of it

**Comment by dutchy1001** [comment]
In my previous message I was wrong, not v2.3-HF6e but v2.3-HF7a was the one with the restart error

**Comment by dutchy1001** [comment]
If you look at your error log you see it starts with errors in the "AsyncWorldEdit" this might be the cause for you,

**Comment by BlackBeltPanda** [comment]
I believe the AsyncWorldEdit errors were a result of being passed a null player to check for build permissions against. I just quickly paste-binned the error without checking the whole thing since I was in a hurry, lol.

**Comment by dutchy1001** [comment]
Have you tried updating the WE and WG versions and see if the same errors persist?

**Comment by BlackBeltPanda** [comment]
Just tried updating to the latest 6.1.1 builds of WE and WG; didn't solve the problem.
