### ISSUE TITLE
2.3-HF7d breaks island level placeholder

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#428]
After updating to 2.3-HF7d, the island level placeholder used with plugins like FeatherBoard no longer works. This is the error: http://pastebin.com/raw.php?i=7tUmGa6T

Not sure if the placeholder was created in Featherboard or uSkyblock, so I figured I'd post the error in both places just in case.

**Comment by dutchy1001** [comment]
It might be due to trying to fix other bugs, I have some commands that aint working now (/usb goto name). 
I have informed our devs.

**Comment by BlackBeltPanda** [comment]
Ah, I just noticed "/usb goto <player>" isn't working for me, either.

**Comment by Harry5573** [comment]
Featherboard needs to update their hooks, they were using a ad method to get that placeholder data. As for the /usb goto, i will fix it.

**Comment by dutchy1001** [comment]
Does our  API have to be updated for this so featherboard can use that?

**Comment by dutchy1001** [comment]
I think this should be ok again, if not let me know and we open it again.

**Comment by BlackBeltPanda** [comment]
It's still occurring in hf8d but Featherboard probably needs to update how they get the data.

**Comment by dutchy1001** [comment]
Did you post on "featherboard's" [freshdesk](https://mvdwsoftware.freshdesk.com/support/home) to let him update the placeholder?

**Comment by BlackBeltPanda** [comment]
Yeah, he told me to use the latest version XD
I pointed him to hf8d but haven't had a response back yet.

**Comment by BlackBeltPanda** [comment]
Well, FeatherBoard dev's not being very helpful =/
https://i.gyazo.com/b31d481815a2e05328189c4cad5bac03.png

**Comment by dutchy1001** [comment]
just out of curiosity, if downgraded to HF3 does it work again? I could test it on a local test server but I dont have that plugin as it's a premium one.

**Comment by rlf** [comment]
It seems FeatherBoard (closed source) is accessing internal state from the uSkyBlock plugin.
That is bound to break (periodically).
We have made an API, which we prefer them using instead.
If you contact them, ask them if this is enough:
https://github.com/rlf/uSkyBlock/wiki/uSkyBlock-API
Otherwise we will be happy to expose what-ever they need in the API - so we can guarantee it won't break between releases.
