### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by KriticalPvP1** [rlf/uSkyBlock#429]
Hello,
When I give to the challenges nothing happens, this gets me into the console.
http://pastebin.com/4VmkeXDb
and when I give, / is top, shows me this.
http://gyazo.com/37b1fdaaffcd8750f395dded33704fd3

More errors:
http://pastebin.com/6auDY23y

I have Spigot 1.7.10 (1649)

Thx.

**Comment by dutchy1001** [comment]
Please read the info [here](https://github.com/rlf/uSkyBlock/wiki#how-to-post-an-issue) and [here](https://github.com/rlf/uSkyBlock/wiki#installation).
