### ISSUE TITLE
Party limit and warp issue

### ISSUE THREAD

**Issue by rocky143** [rlf/uSkyBlock#430]
Hello, 

I recently updated the plugin to version 2.3-HF7d and I came across 2 issues.
First one is party limit. With the usb.extra.partysize permission node, we used to be able to have up to 8 members in an island. Now, even as op and having the permission node usb.*, I can only have 4 members total.
https://i.gyazo.com/ce4be5d5c23e12f5f62228fc08ad420e.png

2nd one is not being able to warp to an offline player's island which we used to be able to. Now that does not work.

Thanks in advance.

**Comment by dutchy1001** [comment]
We are aware of some of the new issue's in the pre-release and the dev's are informed.

**Comment by rocky143** [comment]
Just a heads up, I tried the latest build v2.3-HF7f and warp issue is still there.
Also for party limits, whats happening at the moment is if permission usb.extra.partysize added before the player data file is created, it works or if the player data file is create before the player gets the permission node, it would not work.

**Comment by dutchy1001** [comment]
that might be the same reason then with the commands /usb goto and /usb kick because some work and some dont.

**Comment by rocky143** [comment]
It very well could be and my bad, its actually the island data file not player file.
I am seeing entry being added to it when player already has permission:
      maxPartySizePermission: 8
and for the user who got party permission after the creation of their island did not have that entry in their island data file.

Anyhow, I do not want to rush thing but I have a few suggestions to the newly trust system added.
1. Added permissions for it as for now, only op can use that feature and it works as of my testing.
2. Maybe only allow a person to be trusted on 1 island at a time or perhaps a configuration option to set that.
3. Even in future add permission support to allow bypass trust  limit. Could be a really good feature to give donors, e.g. usb.extra.trust1, usb.extra.trust2, etc..
4. A option to limit how many trusted members an island owner can have. We could use permissions for that as well. Would be great for donor perks!

Once again, thanks for all the dedication and hard work.
I will focus on adding new images on bukkit page once we get a more stable build and the new player trust system.

**Comment by dutchy1001** [comment]
I think there all linked together (but I cant tell as I cant code lol) so hopefully it's a small mistake/typo that can cause this behaviour.

As for your suggestions:
1) There is a permission for the "trust" feature (usb.island.trust), this gives a toggle to trust and untrust.
2) To limit or make it configurable in the config the amount that can be trusted is a good option to add.
3/4) These options are then a follow up of the first 2 then.

As last,
I'm thinking to revamp the bukkit website in total as we progressed so much in the last few months.

**Comment by rocky143** [comment]
Alright, I will think of a few new ideas as per the design we will stick with on bukkit and spigot.
Let me know via skype when you want me to start. Might take me a few days depending on when since I am contently working on updates on my server as of now.

**Comment by rocky143** [comment]
These issues are still there, donors can't add more then 4 people and you can't warp to offline players.

**Comment by rlf** [comment]
Fixed in https://github.com/rlf/uSkyBlock/releases/tag/v2.3-HF9e
