### ISSUE TITLE
v2.3-HF7f  "/is kick" error

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#433]
There seems to be an error with "/is kick": http://pastebin.com/raw.php?i=2MvC0F3n

**Comment by dutchy1001** [comment]
I think it has someting to do with the use of playernames that has changes, reason why /usb goto isnt working either. We will look into it.

**Comment by dutchy1001** [comment]
fixed in the the latest pre-release (v2.3-HF8d)
