### ISSUE TITLE
Island Biomes Partly Snowy

### ISSUE THREAD

**Issue by MeddlingMoose** [rlf/uSkyBlock#434]
Hi there,

It seems in the skyworld that some areas of player's islands are part snowy. They're either a taiga biome, extreme hills, or a beach biome. It's like the generator isn't working as expected.

It's only in certain chunks though, not the whole island.

Toggling the biome back to ocean fixes just one island though others continue to collect snow.

Thanks!
-Moose

Here's my versions:
uSkyblock: 2.3-HF3-9fc81a-dev
Server: CraftBukkit git-Spigot-3ccbe77-a6a57a9 (MC: 1.8.7)
Vault: 1.5.2-b33
WorldEdit: 6.0;3342-78f975b9
WorldGuard: 6.0.0-SNAPSHOT.1593-

Multiverse-Core: 2.5-b691

**Comment by dutchy1001** [comment]
I've notest this to that it not always id the default biome it should be. I will talk later today to our devs to see if they have a solution.

**Comment by MeddlingMoose** [comment]
@dutchy1001 thanks as always for the quick reply! Some players love the free snow haha :smile:

**Comment by csorrows** [comment]
I seem to recall a comment where this was stated as fixed. Please update @dutchy1001

**Comment by dutchy1001** [comment]
As far I know default biome is Ocean and should now be fixed. If not fixed we can reopen it again or create a new issue.

**Comment by csorrows** [comment]
Thanks @dutchy1001 for the update. My first island spawned completely in ocean and so is the surrounding world.
