### ISSUE TITLE
locked island & kick help

### ISSUE THREAD

**Issue by JG6521** [rlf/uSkyBlock#436]
where can we change it so staff can get to locked islands, and also can we get it where head-admin & admins can not be kicked from players islands? thanks :)

**Comment by dutchy1001** [comment]
You need to give the WG permission "worldguard.region.bypass.skyworld" to your moderators/admins to bypass the "entree" flag.
There isnt a bypass to be exempt from getting kicked of an island but I think that should be added, one of our devs could answer this to add.

**Comment by JG6521** [comment]
thank you so much.. yes it would be grate if they could that into the next update, maybe even add it for the admins also
