### ISSUE TITLE
Players invited to an island still have their homes set at 0 0 0

### ISSUE THREAD

**Issue by TobyMellor** [rlf/uSkyBlock#439]
This happens when a new player joins a friends existing island.
Their config doesn't update, and they spawn at 0 0 0. This also happens if the leader tries to update the island spawn in the /is menu.

Thanks.

**Comment by dutchy1001** [comment]
without the info of what versions you use or depended plugins it's hard to tell were the error comes from.

**Comment by swab201** [comment]
Server Version Spigot 1.8.8
Uskyblock Version: v2.3-HF7i
Vault
WorldEdit
WorldGuard 

is All bukkit Dev Lastest Version. 

I have same Issue. if i accpet the invite i m transper Badblock SIde

**Comment by dutchy1001** [comment]
@swab201 
v2.3HF7i is a pre-release and has bugs.
We need all version numbers as "we use latest" is something I cant work with due many updates or dev builds.

**Comment by dutchy1001** [comment]
this should be fixed in the the latest pre-release (v2.3-HF8d)
