### ISSUE TITLE
Lava & Flame, Please Help!

### ISSUE THREAD

**Issue by JG6521** [rlf/uSkyBlock#440]
hi, i left a issue here a while back about lava an flames not killing animals & mobs but it will kill players, someone said "The protection system can be changed in the main config (near the bottom of the file)" but we have had 4-5 people search the files to check, but we can't find the problem anywhere.

anything you could suggest please? thank you again..

**Comment by rlf** [comment]
As stated earlier by dutchy, we do not interfere with the lava/fire damage to animals - since we need that for a lot of farms.
It sounds like you have some other plugin enabled, that blocks fire damage to animals. Perhaps Animal Protect or some WGCustomFlag plugin?

**Comment by JG6521** [comment]
as soon as they head-admin comes online i will ask him what plugin's we use an note them here, maybe you will know a little more than what we will.. and yes its really annoying because we have to manually kill everything :( but thanks for the help :)

**Comment by JG6521** [comment]
so we have gone through the WG an nothing.. and we dont have anything like a animal protect plugin, feel really lost, pretty much tried everything
