### ISSUE TITLE
Request: Stop The Use Of WorldGuard And WorldEdit

### ISSUE THREAD

**Issue by oriamrm** [rlf/uSkyBlock#443]
Hi,
I'm UsingThe Plugin CompassNavigation, Wich Is Not Compaible With WorldGurd / WorldEdit 6.x. It's An AWESOME Plugin, And I Couldn't Find Any Replacement For It. Because uSkyBlock Is Using WorldEdit and WorldGuard on v6.x, I Can't Use It. So, If You Can, Please Stop Using WorldEdit and WorldGuard v6.x. I Would Greatly Appreciate It!

**Comment by dutchy1001** [comment]
uSkyblock is highly depended on WorldEdit and WorldGuard, I doubt removing those 2 depended plugins will happen.
You have more chance that CompassNavigation update their plugin to the latest WE and WG versions.
I also cant find a Bukkit link to this plugin so checking this for compatibility is not possible.

As this will not happen I will close this issue

**Comment by oriamrm** [comment]
Ok. Thanks Anyways
BTW Here is The CompassNavigation Link: https://www.spigotmc.org/resources/compass-navigation.7367/

**Comment by dutchy1001** [comment]
I do not see a reason why it would not be compatible with WE or/and WG. The plugin is not using it as a depended plugin. I think more that WG has changed some of their flags in the new version and looking up on the v6 pages should give you an answer then.
