### ISSUE TITLE
New Players Missing Island After Relogging

### ISSUE THREAD

**Issue by MeddlingMoose** [rlf/uSkyBlock#449]
uSkyblock Version: 2.3-HF7i
Description: Ultimate SkyBlock v2.3-HF7i-6cb0ec-dev

Server: CraftBukkit git-Spigot-3ccbe77-a6a57a9 (MC 1.8.7)

Vault
1.5.6-b49

WorldEdit
6.1;no_git_id (hope that's right... that's what /usb version is telling me)

WorldGuard
6.1

This morning I updated to uskyblock version 2.3-HF7i and so far things have been running smoothly. Though after the server doing it's daily restart at 12am newly joined players that had joined today and generated islands with the 2.3-HF7i version of uskyblock had their island homes reset to 0,0,0. They did still have their islands according to their player file in the uskyblock folder though so it was just a matter of teleporting to that spot in the world and getting them to set their home again which isn't devastating but if I'm not online it's hard to solve without teleporting to the coordinates.

Enjoying the dev updates though, great work! Love seeing the project being maintained again :)

**Comment by MeddlingMoose** [comment]
A quick update - any old player who restarts their island will be teleported back to 0,0,0 again once the server restarts. Their home just doesn't seem to be saved.

**Comment by MeddlingMoose** [comment]
Quick Update # 3 - It's been awhile since our server has restarted but players are still losing their island. I'm pretty certain it has to do with them leaving the game and coming back? I can't say for sure. Hope you guys are able to work something out : )

**Comment by rlf** [comment]
Please retest this with v2.4 - we've had to hunt a lot of bugs reg. island loading/saving.

**Comment by MeddlingMoose** [comment]
@rlf I just tested with the default island (no custom schematic) and everything seems to be working swell. With my usual custom island island though starter chests are still empty. But the major bug of not having an island seems to be resolved! Nice work.

**Comment by rlf** [comment]
We've included an "advanced" fix for your custom schematics.
Please read here http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/extras/#w-using-big-custom-islands-and-async-world-edit

**Comment by MeddlingMoose** [comment]
Awesome! Thanks a bunch for the quick reply :)

**Comment by rlf** [comment]
Pure luck... :D

**Comment by MeddlingMoose** [comment]
haha I get it :P 
But that's not too bad of a solution at all! Thankful you've implemented it :D

I suppose I can close this now!
