### ISSUE TITLE
cant make islands

### ISSUE THREAD

**Issue by dogbo** [rlf/uSkyBlock#451]
i can not make islands gives all players this error: https://gyazo.com/c0953b0b1871ea066d4936ed57a0c2e7
 here is the console log: http://pastebin.com/EyR9Nce8

**Comment by dutchy1001** [comment]
Same issue as #450 

READ THE "HOW TO REPORT A ISSUE OR BUG"

**Comment by dogbo** [comment]
Server Version Spigot 1.8.8
Uskyblock Version: v2.3-HF7i
Vault 1.5.6
WorldEdit 6.1
WorldGuard  6.0 Beta 5

**Comment by dutchy1001** [comment]
As you can see in your log there is something not right with your WorldEdit or WorldGuard. Post a full log from startup again plz. 
Make sure when you update a plugin to remove the older .jar as this can be the cause of what you experience.

**Comment by dutchy1001** [comment]
This is fixed (in other forum)
