### ISSUE TITLE
Nether Portals dont work

### ISSUE THREAD

**Issue by CaptainDwarf** [rlf/uSkyBlock#452]
i tried to go to nether but i cant , any help?

**Comment by dutchy1001** [comment]
Have you read this page [here](http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/extras/#w-adding-a-nether-world) or [here](https://github.com/rlf/uSkyBlock/wiki/Nether-and-uSkyBlock)

**Comment by dutchy1001** [comment]
I presuume after no further input this is resolved by reading the given pages.
