### ISSUE TITLE
[Feature Request] Permission node based island party size.

### ISSUE THREAD

**Issue by csorrows** [rlf/uSkyBlock#453]
I'm requesting a feature that allows you to set a permission for the leader of an island to have a different max island party size. This would work great for donor rank based servers. If the permission node is later removed, it would not allow anyone else to join until the party size is below the then current limit.

I think  'usb.maxparty.{number}' would be a great node to use.

EDIT: I see this request in  #218 but being hard coded it isn't as configurable. I have never seen this feature mentioned in any documentation. What are all the possible party size permission nodes? I'd hate to have to dig through the code to find them...

**Comment by dutchy1001** [comment]
There is already permission based party size  permissions, due to a bug there not working properly as far I know. This also the reason there not listed on the bukkit site. I'll add those nodes as soon this is fixed.

**Comment by csorrows** [comment]
Thanks @dutchy1001, you are always very helpful!

**Comment by rlf** [comment]
Fixed in a409214ce968f8a79c054fe0009394b9fbcad627

A new section added to the config.yml file:

    options.party.maxPartyPermissions:
      'usb.extra.partysize1': 5
      'usb.extra.partysize2': 6
      'usb.extra.partysize3': 7
      'usb.extra.partysize': 8

Any keys can be used as permission-nodes.

**Comment by csorrows** [comment]
I just visited this again. I must have missed your last comment before.
What do you mean by 'Any keys can be used as permission-nodes.'

**Comment by dutchy1001** [comment]
the permission "usb.extra.partysize1" allows you according to the default config to have 5 players on your island. If you change the 5 in the config to a 10 then the permission "usb.extra.partysize1" will allow you to have 10 players on your island. This way you can set 4 different island party sizes for different ranks/donor groups.

Hope this makes it more clear.

**Comment by csorrows** [comment]
Ah I got it. Thanks for the clarification =)

**Comment by rlf** [comment]
Also, you can add as many permission nodes, with differing values you like.
I.e.

    maxPartyPermissions:
        my:
          awesome:
             island: 100

Will grant up to 100 members on the players with the `my.awesome.island` permission.

**Comment by csorrows** [comment]
Ah ok, so it's fully customizable. You guys are the best!

**Comment by rlf** [comment]
We changed (added) this feature again.
Take a look at https://github.com/rlf/uSkyBlock/blob/master/src/main/resources/config.yml#L233

**Comment by csorrows** [comment]
Wow, you tied all the new added features together into one customizable permission node. What a wonderful solution. Thanks for this!
