### ISSUE TITLE
Players respawning at (0, 150, 0)

### ISSUE THREAD

**Issue by GiansCode** [rlf/uSkyBlock#455]
Whenever players die in the SkyWorld, they respawn on a Bedrock block at (0, 150, 0). However, when they die in any other world, they respawn at the correct spawn point. We're using EssentialsXSpawn, if that helps.

**Comment by csorrows** [comment]
This is not a uSkyBlock issue as it does not modify respawning.

**Comment by GiansCode** [comment]
Odd. Okay then. I just assumed so because it only happens in the world generated by uSkyBlock. Nonetheless, I'll look into it! Thanks!

**Comment by GiansCode** [comment]
Do you know how to fix it with Multiverse?

**Comment by dutchy1001** [comment]
I have to correct csorrow's answer here. 
As we do not modify how the respawning goes we do set the location (0, 150, 0), this can be altered when you made a spawn island and need the spawn at a different location on that island, do not alter this to a players island as that will give problems. 
Any plugin that has the command "/spawn" can be used, so Essentials or Multiverse are both supported.

You can find in the config.yml an option called:
```
  extras:
    sendToSpawn: false
```
When set to "false" it will let you stay in the "skyworld" spawning on the bedrock block (if you dont have an spawn island created).
When set to "true" it will spawn you were you have set the "/spawn" command to spawn the player, this could be in a different world then.

To explain why you spawn on a "bedrock" block after falling of the island or dying is simple. This way we can avoid falling into the void when there is no "spawn island".

Hope this makes it a bit more clear.
Let me know if this if fixed for you now so we can close the issue.

**Comment by GiansCode** [comment]
Thanks! It works! I can't believe I didn't see that!

**Comment by dutchy1001** [comment]
YW, so I can close this?

**Comment by GiansCode** [comment]
Yes. I'll open another one with a different issue

**Comment by csorrows** [comment]
I can't believe i missed that either. I thought there was a setting but upon scanning the config, i thought i was thinking about some other plugin because I didn't see it. Apparently you CAN override that with multiverse as I have done that before without changing that setting. I'm sorry for the miss-information. Thanks for clearing it up @dutchy1001!
