### ISSUE TITLE
Dropped by {playername} Item Issue

### ISSUE THREAD

**Issue by Stimulation** [rlf/uSkyBlock#458]
With no way to disable this? Could that be added if it isnt already!?!
![2015-09-08_19 07 02](https://cloud.githubusercontent.com/assets/12617064/9743180/e2f41c86-565c-11e5-8a7e-9c32808ef665.png)

**Comment by BlackBeltPanda** [comment]
Disable the player drop/pickup protection in the config.

**Comment by Stimulation** [comment]
Oh, I saw the protection but didn't think it added the lore, Thanks!

**Comment by dutchy1001** [comment]
did that do the trick? if so can this be closed?

**Comment by dutchy1001** [comment]
I presume this can be closed then
