### ISSUE TITLE
IllegalStateException on "/is"

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#459]
Version info:
Name: {0}
uSkyBlockVersion: 2.3-HF8a
Description: Ultimate SkyBlock v2.3-HF8a-1094bd-dev
Server: CraftBukkit git-Spigot-fdc1440-53fac9f (MC: 1.8.8)
Name: Vault (ENABLED)
Version: 1.5.6-b49
Name: WorldEdit (ENABLED)
Version: 6.1;no_git_id
Name: WorldGuard (ENABLED)
Version: 6.1

Error when typing "/is": http://pastebin.com/raw.php?i=Wh1QzZbv

**Comment by dutchy1001** [comment]
this was fixed in the next version
