### ISSUE TITLE
[Feature Request] Island or player setting to announce when people warp to your island

### ISSUE THREAD

**Issue by c0wg0d** [rlf/uSkyBlock#461]
Sometimes, people visit your island, and you have no idea, then all of a sudden they're standing in front of you.

Or perhaps you're showing someone around, and they leave without saying anything, and you find out they're no longer following after a while.

What if there was a notification system for every time someone warped to and from your island?  This could be an island setting or a setting that each player can decide if they want or not.  I think it would be better if each player could decide for themselves.

**Comment by csorrows** [comment]
I think this would be a great addition to the /island menu.

**Comment by rlf** [comment]
We could dig into the WG notify flags.
Sounds like something that should be added to the island-permission menu.

**Comment by csorrows** [comment]
I just spent some time digging through the WG Javadoc. I found this:

com.sk89q.worldguard.protection.flags.RegionGroupFlag 
    static boolean isMember(ProtectedRegion region, RegionGroup group, LocalPlayer player)  
 
I don't know if it would help, only thing I saw that has player && region info

**Comment by rlf** [comment]
I was thinking of `notify-enter` and  `notify-leave` from this page: http://wiki.sk89q.com/wiki/WorldGuard/Regions/Flags
But, it seems it only sends to ppl with permissions, no way to make it send to those owning the region.

Still, with WG events, it should be doable - perhaps with an optional dependency to WGRegionFlags.

**Comment by csorrows** [comment]
I'm not quite sure how that flag works but if it only sends to members of the region it might be a good starting point.

**Comment by rlf** [comment]
Been thinking of this one, and some things are easily done.
We can broadcast a message to all online members when a visitor *warps to your island*
Broadcasting a message when visitors *enters your island* is harder, and requires some additional plugins (i.e. WGCustomFlags).
Never the less, the first "option" is easily done, so let's just do that to begin with.

**Comment by csorrows** [comment]
Sounds like a solid path.

**Comment by rlf** [comment]
option a) is implemented in f7d2f69edd16edd570d3c71c9cd833b293b504a2

**Comment by rlf** [comment]
Ready for test in https://github.com/rlf/uSkyBlock/releases/tag/v2.3-HF9d.
Config node: 

    options.protection.visitors.warn-on-warp: true

**Comment by dutchy1001** [comment]
tested and working
