### ISSUE TITLE
Request!

### ISSUE THREAD

**Issue by ItzFrog** [rlf/uSkyBlock#462]
Hello dev's of uSkyblock. I want to thank you for bringing this plugin back. Anyways, are you able to remove world guard and just send the uSkyblock without the worldguard because I assume everyone else would like to keep worldguard. I ask this is because I am working on a gamemode and the only good skyblock plugin I like is uSkyblock. So would you guys be able to just delete the worldguard code of the plugin and send me the plugin without worldguard? It would really be appreciated, thanks.

**Comment by rlf** [comment]
No
