### ISSUE TITLE
Confusing messages in console.

### ISSUE THREAD

**Issue by csorrows** [rlf/uSkyBlock#463]
> 7Description: bUltimate SkyBlock v2.4-f9e9f6-dev
> 7Language: ben (en)
> 7------------------------------
> 7Server: eCraftBukkit git-Spigot-fdc1440-53fac9f (MC: 1.8.8)
> 7------------------------------
> 7Name: dVault (2ENABLED)
> 7Version: d1.5.6-b49
> 7------------------------------
> 7Name: dWorldEdit (4DISABLED)
> 7Version: d6.1;no_git_id
> 7------------------------------
> 7Name: dWorldGuard (4DISABLED)
> 7Version: d6.1
> 7------------------------------

I'm confused by the "DISABLED" on WE and WG. <s>Does it require the newest dev version?</s>

I noticed uSkyBlock loads before WE and WG. Should uSkyBlock force those to load first?

I'm afraid to actually test it with those messages.

**Comment by dutchy1001** [comment]
This has no impact on the game and cant be dismissed. As you said uSkyblock loads before WE and WG and for that reason it looks like there disabled. When you do after a start or restart the command "/usb version" ingame or "usb version" in console you will see that both are ENABLED.

**Comment by csorrows** [comment]
Thanks, I will ignore it.

**Comment by rlf** [comment]
It's because we print the version info during loading.
The DISABLED is more relevant when peoply invoke it manually.
