### ISSUE TITLE
IslandTalk enhancement.

### ISSUE THREAD

**Issue by csorrows** [rlf/uSkyBlock#464]
It would be a nice enhancement if it gave you an error if no other island members were online to hear your islandtalk message.

**Comment by rlf** [comment]
We did one better.
a) We added a new talk command, and changed the way the existing works.
b) `/islandtalk`, `/istalk` or `/it` will send a message to all players _within the island region_
c) `/partytalk`, `/ptalk` or `/pt` will send a message to your island members (regardless of where they are).
d) Both commands will have a couple of random messages, like `You're talking to your self` and similar when no-one is around.

Will be part of next release (v2.4.1)

**Comment by csorrows** [comment]
Ok, I'm speechless on this one (yea I know that does not sound possible for me). You have gone way further then I could have even requested or thought of. 

I do see one issue though. /pt is also used for /powertool on essentials. Maybe /ptk or something like that? Would suck to have to explain to everyone how to set aliases to make it work as intended.

**Comment by rlf** [comment]
`/pt`, `/partytalk` or `/ptalk` - you can use the bukkit.yml (or any of the plugins around that do this), to change the alias as you see fit.
