### ISSUE TITLE
Better spawn system

### ISSUE THREAD

**Issue by Scraapy** [rlf/uSkyBlock#466]
Could you make it so that instead of spawning on some other area of an island you can either set the spawn point, or you spawn at the highest point of the island above the bedrock. I'm using a custom island and I spawn on the very edge and you could very easily fall off the edge and die.

**Comment by rlf** [comment]
The spawn system already goes to quite some trouble finding a suitable spot.
If you spawn on the very edge, odds are, your schematic isn't configured correctly.

Read up on the wiki https://github.com/rlf/uSkyBlock/wiki/Custom-Island
Esp. reg. what constitutes the "center of the island".
If you want to test your schematic, copy it to `plugins/WorldEdit/schematics` and use the following commands in WE, and note where the island is relative to your position:

    //schem load <schematicnane>
    //paste

If you stand on the very edge, or the island is pasted besides you, that is the explanation of the weird spawn-point.

**Comment by Scraapy** [comment]
Thank you for the guide, I fixed this issue.
