### ISSUE TITLE
Ghasp! Ghasts!

### ISSUE THREAD

**Issue by voigtman** [rlf/uSkyBlock#469]
Sorry for my late entry,
According to the documentation the Nether island biome should not spawn ghasts, But (at least in 2.3 hf3) Ghasts spawn in abundance. I became a concern for near by noob islands...

**Comment by rlf** [comment]
We will tale A look at it along with the spawn limiting feature

**Comment by rlf** [comment]
Related to #421

**Comment by voigtman** [comment]
This reminds me, out of all the various servers we run, many of which utilize the same mob and lag control plugins (essentials, clearlag, wg) We have come across one issue that only affects the SkyBlock overworld where uskyblock runs. Every day, mobs of all kinds just stop spawning. They spawn just fine in the end and nether, but in the overworld after a good day of grinding, the mobs just dry up. I am suspecting uskyblock, but i havent really a way to test that. 

--
Sent from my iPhone 
--
Jason Houge
http://jasonhouge.com
http://instagram.com/jasonhouge


On Sep 17, 2015, at 4:40 PM, Razorax <notifications@github.com> wrote:

We will tale A look at it along with the spawn limiting feature

**Comment by rlf** [comment]
It's (unfortunately) not uSkyBlock, but Spigot and the spawn-logic.
AFAIK.

Spigot/Bukkit has an upper-limit on how many monsters can be spawned in each world, the algorithm only "limits" the natural spawning, not spawning from eggs and spawners.

To my recollection, it's something along these lines:

    mob-limit := (players in world * [monster-per-player]) / [active-chunks]

    active-chunks := loaded-chunks within [mob-spawn-range] of a player

    monster-per-player := bukkit.yml:spawn-limits.monsters

    mob-spawn-range := spigot.yml:world-settings.mob-spawn-range
    
This means, that without any mob-spawn-limiter-plugin active, someone running around on their own island, most likely triggers a spawn-pad or similar on the neigbouring island, which then fills up, and takes the spawn-count for that particular player.

I think we need to address these issues with #421 as well, but there is the explanation.
Not a direct uSkyBlock issue, but a side-effect of the Bukkit way to handle spawns, and the way uSkyBlock makes islands.

Solutions:
a) Make the islands spawn so far away from each other, there is no "cross-island-activation" (distance > protectionRange)
b) Install a mob-spawn-limiter like clearlag or what-ever
c) Increaste the spawn-limits.monsters (note: If other worlds on your server, players will have a hard time going out at night).

**References**

* http://www.minecraftforum.net/forums/support/server-support/server-administration/1913564-low-number-of-mobs-on-bukkit-server-help
* http://www.spigotmc.org/threads/mob-spawning-oddities-low-spawns.97/

**Comment by voigtman** [comment]
Well thats the thing. I am using clearlag, and what we're seeing is that there are 0 mobs anywhere in the overworld. They'll be running good all day and then an hour or two before the automatic restart - nothing. All mobs have been cleared and no new ones spawn. We have only a couple of very large mob farms and there's completely empty too. I'll keep looking for the cause. 

--
Sent from my iPhone 
--
Jason Houge
http://jasonhouge.com
http://instagram.com/jasonhouge


On Sep 18, 2015, at 1:52 AM, Razorax <notifications@github.com> wrote:

It's (unfortunately) not uSkyBlock, but Spigot and the spawn-logic.
AFAIK.

Spigot/Bukkit has an upper-limit on how many monsters can be spawned in each world, the algorithm only "limits" the natural spawning, not spawning from eggs and spawners.

To my recollection, it's something along these lines:

mob-limit := (players in world * [monster-per-player]) / [active-chunks]

active-chunks := loaded-chunks within [mob-spawn-range] of a player

monster-per-player := bukkit.yml:spawn-limits.monsters

mob-spawn-range := spigot.yml:world-settings.mob-spawn-range
This means, that without any mob-spawn-limiter-plugin active, someone running around on their own island, most likely triggers a spawn-pad or similar on the neigbouring island, which then fills up, and takes the spawn-count for that particular player.

I think we need to address these issues with #421 as well, but there is the explanation.
Not a direct uSkyBlock issue, but a side-effect of the Bukkit way to handle spawns, and the way uSkyBlock makes islands.

Solutions:
a) Make the islands spawn so far away from each other, there is no "cross-island-activation" (distance > protectionRange)
b) Install a mob-spawn-limiter like clearlag or what-ever
c) Increaste the spawn-limits.monsters (note: If other worlds on your server, players will have a hard time going out at night).

References

http://www.minecraftforum.net/forums/support/server-support/server-administration/1913564-low-number-of-mobs-on-bukkit-server-help
http://www.spigotmc.org/threads/mob-spawning-oddities-low-spawns.97/

**Comment by rlf** [comment]
Until now, uSkyBlock has not touched anything remotely close to the spawning of entities.
My bet would be, that Bukkit/Spigot not only has a per-world mob limit, but a server-wide one as well.

Does it follow any particular pattern reg. user-activity?

The above algorithm is known to cause trouble, when the loaded-chunks is kept artificially high, while the active-players drop.

I.e. if the numbers drop from 20 players to 10, but the active-chunks is kept at the same, the mob-limit is cut in half.

If you have clearlag, try `/lagg unloadchunks` when it happens, and see if it has any effect at all.

**Comment by rlf** [comment]
Fixed in 5803c60a43d55aebbd6ea153bcd9a2686dc9cef1
