### ISSUE TITLE
addExtraItems not work

### ISSUE THREAD

**Issue by donbubu** [rlf/uSkyBlock#471]
hi,
there are no extra items in chest after create or restart. i test it with default config and set the perm in groupmanager to usb.smallbonus.
no extra items in chest. addExtraItems is set to true (default conf).

```
Name: uSkyBlock
Version: 2.4
Description: Ultimate SkyBlock v2.4-f9e9f6-dev
Language: en (en)
------------------------------
Server: CraftBukkit git-Spigot-fdc1440-53fac9f (MC: 1.8.8)
------------------------------
Name: Vault (ENABLED)
Version: 1.5.6-b49
------------------------------
Name: WorldEdit (ENABLED)
Version: 6.1;no_git_id
------------------------------
Name: WorldGuard (ENABLED)
Version: 6.1 with custom flags plugin.
------------------------------
```

**Comment by rlf** [comment]
Are you using AsyncWorldEdit (AWE)?
http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/extras/#w-using-big-custom-islands-and-async-world-edit

**Comment by donbubu** [comment]
no, at least i test it only with worldguard, worldedit, uskyblock (both, 2.4 release and 2.4 dev v2.4.0-20150918), spigot 1.8.8, groupmanager, essentials 2, cleanroomgenerator, vault.
i read the advanced config settings for awe, that usb need a delay for finding the chest, but at first i want usb to work, thats why i test it with only this plugins.

**Comment by dutchy1001** [comment]
can you post the config, there might be a change that there is a fault in the configuring. If you dont use AWE then there is no need for the node to be added to this config.
When OP do you get the items?

**Comment by donbubu** [comment]
i test it with the generated config.
anytime before i made an update on the public server, i test it on my dev server.

**Comment by rlf** [comment]
Yes, that is one of the side-effects of the new perk-system, it caches the perk calculation for a time.

I see what you need here, and will try to change it.

**Comment by donbubu** [comment]
thank you, we use the extra items for our 3 islands. any player can select or change to one of a island and become the permission for a extra item. every island has its own extra items, so we can have a easy, medium and hard island schematic.
if you wanna take a look, i can post you the address.

**Comment by donbubu** [comment]
all work like a charm.
thanks for the nice work :)
