### ISSUE TITLE
English messages.properties

### ISSUE THREAD

**Issue by Scraapy** [rlf/uSkyBlock#476]
In the latest uSkyblock version 2.4.1, when trying to access the messages.properties with my sensible zip-program (I'm using a java decompiler, best thing I could use), I load up messages.properties and the messages_en.properties and nothing comes up.All of the other languages come up, but the english ones. I can't see it being the decompiler, because I'm sure if I used a zip-program it would show the same results. 

Link: https://gyazo.com/ccb259bbe16aa6399f6b3812e775c71b

**Comment by rlf** [comment]
The default language for uSkyBlock is english, that is why the message_en.properties is empty.

If you want to find the "key" to change/add to your own copy of messages.properties, I suggest looking into the https://github.com/rlf/uSkyBlock/blob/master/src/main/po/keys.pot
The keys in the properties corresponds to the `msgid`s (remember to escape all white space, and special characters). I'll update the Wiki page
