### ISSUE TITLE
Confused how to change messages

### ISSUE THREAD

**Issue by Scraapy** [rlf/uSkyBlock#478]
I'm playing around with the messages.properties and I'm trying to change a chat message, and I'm a bit confused on how to do it.

Using one of the menu changes in the wiki (Change\ Island\ Biome=Change \u00a7a\u00a7lBiome) I can change the text in a menu, but I'm trying to change a chat menu and I'm very confused on how to do it.

Trying to change this (\u00a7fDoing {0} is RISKY. Repeat the command within {1} seconds to accept!) making it just white (so I can play with it), but I don't know what to put before it like in the Change\ Island\... I don't get it.

**Comment by rlf** [comment]
I know, it's a bit hard to figure out.

This is the "pure" string:
`§eDoing §9{0}§e is §cRISKY§e. Repeat the command within §a{1}§e seconds to accept!`
I.e. the string you'd find in the `keys.pot` file.

You have to escape all spaces, and non-latin1 characters, meaning, to change formatting, this is what you should put in your `messages.properties`.
```
\u00a7eDoing\ \u00a79{0}\u00a7e\ is\ \u00a7cRISKY\u00a7e.\ Repeat\ the\ command\ within\ \u00a7a{1}\u00a7e\ seconds\ to\ accept!=Doing {0} is RISKY. Repeat the command within {1} seconds to accept!
```
Note that ALL spaces ' ' has to be escaped by `\`
