### ISSUE TITLE
Drops changed

### ISSUE THREAD

**Issue by brobon** [rlf/uSkyBlock#479]
Hey,
I`m running a 1.7.10 cauldron server. 
My problem is that the droped items like a filled up energy cell are empty after picking up again.

I have test it with this versions:
2.4.1
2.4
2.2 for 1.7.10
2.3

I have tried with version 2.0.0 and it works. BUT... it don t select a protection with worldguard now. (WG & WE 6.x)

**Comment by dutchy1001** [comment]
I'm sorry but I have no experience what so ever with Cauldron. Therefore I cant help you here.

**Comment by rlf** [comment]
Set `options.protection.item-drops` to `false`, and we shouldn't touch items dropped.
