### ISSUE TITLE
[Bug] Messages & Colons + Challenge Glass Panes

### ISSUE THREAD

**Issue by Scraapy** [rlf/uSkyBlock#481]
Any messages with the colon key in it will not work. My current text editor is Brackets by Adobe. 

#Challenge times completed (GUI)
\u00a7dTotal\ times\ completed:\ \u00a7f{0}=\u0aa7eTimes completed: {0}
![image](https://cloud.githubusercontent.com/assets/12485039/10059238/dc74bbb0-6217-11e5-93d9-aa32d3e5d987.png)

Also, where did the challenge glass panes go? Are these settings no longer used?
challengeColor: §e
finishedColor: §2
repeatableColor: §a

**Comment by rlf** [comment]
Not a bug, you need to escape it. put a `\` in front of the colon.
I.e.
```
\u00a7dTotal\ times\ completed\:\ \u00a7f{0}=\u00a7eTimes completed: {0}
```
The colors are still used, but only in the "command-line" mode of the challenges command.

We decided to change the challenge-menu, so now you get the displayItem of the challenge, to further pique your curiosity, and also help you locate that challenge you remember you were working on again.
