### ISSUE TITLE
fr.po

### ISSUE THREAD

**Issue by TheWura** [rlf/uSkyBlock#484]
Hi dutchy1001 !
I finished the translation in French. It is translated to 99%
Here is the link :
https://mega.nz/#!g58kjazb!CuzZxpmSLwFRDI_vVzAeXt8q0GyT3fRKjfBiF4qCHpY
http://pastebin.com/NXsdTckB

P.S :There are certainly some spelling mistakes. 
P.S : Sorry I can't  upload the file on github

**Comment by rlf** [comment]
Thank you very much.
Will be part of next release (in commit 2cc62ca7cf09fe6ac6b498912367e1a85dc76e95).

We will credit you for the translations.
Next time, just post it here - all the other ways leads to GitHub! :D
