### ISSUE TITLE
Error with a other plugin (conflict)

### ISSUE THREAD

**Issue by manercraft** [rlf/uSkyBlock#485]
Hello, i have last version and when i start my server, a error was generated
http://pastebin.com/NzNDRS2j

This plugin is a plugin of "tyrolienne", I don't kown what is it in english (i attach picture of it)
This plugin uses bats to spawn the ropes.

![usbversion](https://cloud.githubusercontent.com/assets/1338257/10117411/799638ca-6456-11e5-80e1-a0bb81b69b24.png)

![whatistyrolienne](https://cloud.githubusercontent.com/assets/1338257/10117409/4fcf04fe-6456-11e5-97b1-c27804ec7670.jpg)

Infos of this plugin:
Description (FR): http://www.bukkit.fr/topic/19188-tyroplugin-glissez-ou-montez-la-tyrolienne/
Download: http://www.bukkit.fr/files/file/180-tyroplugin/ Page of download or direct download http://www.bukkit.fr/files/download/180-tyroplugin/

**Comment by rlf** [comment]
This seems to happen, because the other plugin spawns entities before uSkyBlock has finished loading it's worlds through Multiverse-Core.

I will try to hold back the event-registration in uSkyBlock til that has happened, so we can avoid this sort of errors.
