### ISSUE TITLE
Default island value.

### ISSUE THREAD

**Issue by csorrows** [rlf/uSkyBlock#488]
I have not seen this posted nor do I know why I have not posted it prior to now.

If you use a large default island, it already has a higher level. I was thinking a command to set the island level 0 on a given island schematic, but thinking about it, it would be pretty complicated to handle. 

I guess I have no solution to offer, just the issue.

**Comment by dutchy1001** [comment]
As you already mention, this would pretty complicated to handle. The block value's are there already so I dont think this is possible.

**Comment by rlf** [comment]
I understand what you are trying to accomplish, but it wouldn't make sense in uSkyBlock.

The level of any given island, is the score divided by 1000, the score is calculated based on every block on that island (see `/is info`).
If we were to introduce a static "offset" to the score, the `/is info` would be weird, and players would be able to get negative scores (which frankly, will just break things).

I do see what your point is, but instead, I recommend configuring your way out of it.

*  From next release, you can set the `options.advanced.topTenCutoff` to a higher value, excluding islands of lower level to be shown on topTen
* You can set the `options.advanced.purgeLevel` to a higher value, to allow abandoned islands below that level to be purged when using `/usb purge <days>`
* You can edit the `challenges.yml` and increase the level for all the `islandLevel` challenges.

**Comment by csorrows** [comment]
I totally agree with you @rlf. I was thinking the same. I just wanted to see if maybe I was missing something. Thank you for taking the time. You guys rock.
