### ISSUE TITLE
Language spanish

### ISSUE THREAD

**Issue by HeertzMC** [rlf/uSkyBlock#491]
http://pastebin.com/gkSH3azp

Regards!

**Comment by dutchy1001** [comment]
thank you for your translation, we will add this with the next release.

**Comment by dutchy1001** [comment]
Here is a link to a new released version [v2.4.7](http://dev.bukkit.org/bukkit-plugins/uskyblock/files/29-uskyblock-v2-4-7/) including your translation.
Thanks again for your support and translation.
