### ISSUE TITLE
GUI for config

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#494]
Dutchy1001 mentioned this yesterday.

* Primary config (top of challenges.yml and most of config.yml)
* Some settings excluded (i.e. protectionRange, distance)

**Comment by csorrows** [comment]
I can not believe how far this project has gone and is going in such a short amount of time.  I mean I make it part of my after work ritual to read all the posts on this page everyday!

**Comment by rlf** [comment]
Part of v2.4.7 - as an **experimental feature!!!**

**Comment by dutchy1001** [comment]
test went very well, all settings that could be changed ingame are working
