### ISSUE TITLE
Bug: Creating new player config! repeatedly

### ISSUE THREAD

**Issue by voodootje0** [rlf/uSkyBlock#495]
![image](https://cloud.githubusercontent.com/assets/6852308/10224077/a7c1638c-685c-11e5-88b3-064df900ef7e.png)
I get this message the whole time and the plugin doesnt load.

![image](https://cloud.githubusercontent.com/assets/6852308/10224178/150414ee-685d-11e5-9c00-5bd3b2c6eadf.png)

Information:
![image](https://cloud.githubusercontent.com/assets/6852308/10224159/f685a654-685c-11e5-9a1f-503a19f60b30.png)

**Comment by rlf** [comment]
Could you please pastebin the whole server-log?

**Comment by rlf** [comment]
This seems to be caused by the rather buggy UUID support in uSkyBlock - esp. the renaming when a player changes name.

**Comment by dutchy1001** [comment]
I havent seen this happening since, issue's are made to improve the UUID are made so this can be closed.
