### ISSUE TITLE
Chat not working

### ISSUE THREAD

**Issue by VizionStudios** [rlf/uSkyBlock#497]
Could someone tell me how to get the new chat-format placeholders work with Essentials chat?

Server info:
02.10 12:42:45 [Server] INFO ------------------------------
02.10 12:42:45 [Server] INFO Version: 2.2.2
02.10 12:42:45 [Server] INFO Name: AsyncWorldEdit (ENABLED)
02.10 12:42:45 [Server] INFO ------------------------------
02.10 12:42:45 [Server] INFO Version: 6.1
02.10 12:42:45 [Server] INFO Name: WorldGuard (ENABLED)
02.10 12:42:45 [Server] INFO ------------------------------
02.10 12:42:45 [Server] INFO Version: 6.1;no_git_id
02.10 12:42:45 [Server] INFO Name: WorldEdit (ENABLED)
02.10 12:42:45 [Server] INFO ------------------------------
02.10 12:42:45 [Server] INFO Version: 1.5.6-b49
02.10 12:42:45 [Server] INFO Name: Vault (ENABLED)
02.10 12:42:45 [Server] INFO ------------------------------
02.10 12:42:45 [Server] INFO Server: CraftBukkit git-Spigot-76236cb-c373061 (MC: 1.8.8)
02.10 12:42:45 [Server] INFO ------------------------------
02.10 12:42:45 [Server] INFO Language: en (en)
02.10 12:42:45 [Server] INFO Description: Ultimate SkyBlock v2.4.6-31e0d8-dev
02.10 12:42:45 [Server] INFO Version: 2.4.6

**Comment by rlf** [comment]
Open essentials config `/plugins/Essentials/config.yml`
Find the chat section, and use the placeholders in the format.

I.e.
```
chat:
  format: '&8{SHORTWORLDNAME} &r{DISPLAYNAME}&9{uskyblock_island_level}:{uskyblock_island_rank}:&r {MESSAGE}'
``
