### ISSUE TITLE
FeatherBoard not working

### ISSUE THREAD

**Issue by VizionStudios** [rlf/uSkyBlock#498]
Just update to the lasted USkyblock and now my FeatherBoard Island level for FeatherBoard not working.

Server info:
02.10 12:42:45 [Server] INFO ------------------------------
02.10 12:42:45 [Server] INFO Version: 2.2.2
02.10 12:42:45 [Server] INFO Name: AsyncWorldEdit (ENABLED)
02.10 12:42:45 [Server] INFO ------------------------------
02.10 12:42:45 [Server] INFO Version: 6.1
02.10 12:42:45 [Server] INFO Name: WorldGuard (ENABLED)
02.10 12:42:45 [Server] INFO ------------------------------
02.10 12:42:45 [Server] INFO Version: 6.1;no_git_id
02.10 12:42:45 [Server] INFO Name: WorldEdit (ENABLED)
02.10 12:42:45 [Server] INFO ------------------------------
02.10 12:42:45 [Server] INFO Version: 1.5.6-b49
02.10 12:42:45 [Server] INFO Name: Vault (ENABLED)
02.10 12:42:45 [Server] INFO ------------------------------
02.10 12:42:45 [Server] INFO Server: CraftBukkit git-Spigot-76236cb-c373061 (MC: 1.8.8)
02.10 12:42:45 [Server] INFO ------------------------------
02.10 12:42:45 [Server] INFO Language: en (en)
02.10 12:42:45 [Server] INFO Description: Ultimate SkyBlock v2.4.6-31e0d8-dev
02.10 12:42:45 [Server] INFO Version: 2.4.6

**Comment by rlf** [comment]
Not our problem.
Take it up with Featherboard.
They seem to have integrated with internal state instead of our APIs, so when-ever we change something, they are likely to stop working with us.
