### ISSUE TITLE
Fix threading issues

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#5]
A lot of places in the code, state that is only relevant for a single invocation reg. the player (i.e. the menus) is stored on instance variables, that are ultimately shared between players (the plugin is a singleton).

This should be fixed, so local variable is used when-ever appropriate.

**Comment by rlf** [comment]
This is close to being complete - Still some orphan handling that might be the cause of some of the "players share island unintentionally" bugs we see.

**Comment by dutchy1001** [comment]
this is fixed as far I know
