### ISSUE TITLE
MVCore exception on importWorld

### ISSUE THREAD

**Issue by Minecraftgamer37** [rlf/uSkyBlock#501]
5.10 21:17:15 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
05.10 21:17:15 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-f94fe8f-d27e6d0]
05.10 21:17:15 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-f94fe8f-d27e6d0]
05.10 21:17:15 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-f94fe8f-d27e6d0]
05.10 21:17:15 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-f94fe8f-d27e6d0]
05.10 21:17:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-f94fe8f-d27e6d0]
05.10 21:17:15 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-f94fe8f-d27e6d0]
05.10 21:17:15 [Server] INFO at us.talabrek.ultimateskyblock.uSkyBlock$2.run(uSkyBlock.java:219) ~[?:?]
05.10 21:17:15 [Server] INFO at us.talabrek.ultimateskyblock.uSkyBlock.getSkyBlockWorld(uSkyBlock.java:353) ~[?:?]
05.10 21:17:15 [Server] INFO at us.talabrek.ultimateskyblock.uSkyBlock.getWorld(uSkyBlock.java:330) ~[?:?]
05.10 21:17:15 [Server] INFO at us.talabrek.ultimateskyblock.handler.MultiverseCoreHandler.importWorld(MultiverseCoreHandler.java:39) ~[?:?]
05.10 21:17:15 [Server] INFO java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.api.MultiverseWorld.setGenerator(Ljava/lang/String;)V
05.10 21:17:15 [Server] INFO [21:17:15 WARN]: [uSkyBlock] Task #6 for uSkyBlock v2.4.7 generated an exception

Using latest worldedit uskyblock and multiverse and worldguard and vault. Java 7 and spigot 1.8 latest

**Comment by rlf** [comment]
We can not use "latest version" for anything.
Please post output from `/USB version` and `/version MultiverseCore`.

**Comment by dutchy1001** [comment]
no further input, presume it fixed itself

**Comment by Minecraftgamer37** [comment]
It didnt fix itself all I did was downgrade the version of multiverse.

**Comment by dutchy1001** [comment]
can you give us the info when you do "/usb version" and your MV plugin version, if more then using Core the other versions are inportant too for me to see what is going wrong. As server log from startup is very handy too to see as it gives us a lot of info.

**Comment by rlf** [comment]
also, if we are not compatible with the latest official MVCore, we need to be.
