### ISSUE TITLE
exception when joining with active EchoPet pet

### ISSUE THREAD

**Issue by i9hdkill** [rlf/uSkyBlock#505]
Hi,
when spawning villagers through eggs on my island, I can exceed the spawn limit.

While doing this I get:
You don't have the permission to do that
but I can still spawn villager. (Even when the limit is reached)
Also I get this execption:
http://pastebin.com/MWzaULXL

No exeption when spawning an egg as OP.

Something is clashing with echopet.

Uskyblock: 2.4.4
EchoPet Build: 67
Shopkeepers: 1.63
Spigot 1.8.8

**Comment by dutchy1001** [comment]
Update to v2.4.7 and see if the issue still exist.

**Comment by i9hdkill** [comment]
Okay, got it wrong.

When joining with an active echopet pet (in my case a bat/slime) I get this exception:
http://pastebin.com/XP8svs7x
so echopet tries to spawn an pet and uskyblock tries to check if the limit i reached or not and that does/and should not work with echopet pets.
Not sure if echopet also breaks the counting mechanism.
I am still able to spawn as much villagers as I want.
Even the first villager gives an you do not have permissions to do that message.

**Comment by dutchy1001** [comment]
Have you tried with Echopet disabled?

**Comment by i9hdkill** [comment]
Tried to reproduce this on my testserver. Same plugins, same configs.
Removed echopet. (The join error is obviously gone) 
Still, it would be great if can ignore pets spawned by plugins to fix this error.
Limit is now working (Don't ask me how). Sry for bothering you^^ It probably was a missconfiguration in shopkeepers

**Comment by rlf** [comment]
Fixed in 7783f13c
