### ISSUE TITLE
World generation. 

### ISSUE THREAD

**Issue by brocker12345** [rlf/uSkyBlock#508]
I am running on this version: http://puu.sh/kFiRc/175f93df2e.jpg
Here is my /about info: http://puu.sh/kFiUF/303f840963.jpg

The plugin generates the world but its not it a void. Here is a screenshot: http://puu.sh/kFiX9/23d79fafc9.jpg

I have fixFlatland set to true in my config. I tried false and that didnt work ether.

Here is my plugin list: http://puu.sh/kFj30/c7fed9c034.png
Here is my config: http://pastebin.com/Mg67KQux

Hope you guys can help me!

**Comment by dutchy1001** [comment]
We never have tested this against a cauldron version (neither 1 of us is using this).
As I missed the Multiverse plugin you might want to add that and try again.

**Comment by brocker12345** [comment]
Should I generate it with Multiverse? Or just put it in the plugins folder and don't touch it?

**Comment by dutchy1001** [comment]
let the plugin do but it is a soft depend we use, wont hurt to try.

**Comment by brocker12345** [comment]
Ok, il do that now

**Comment by brocker12345** [comment]
And by plugin you mean Uskyblock?

**Comment by brocker12345** [comment]
Tried with Multiverse. That didnt work. I have also used it with MCPC+ and worked fine. Is it because of Kcauldron?

**Comment by dutchy1001** [comment]
yes uskyblock hooks into mv

**Comment by brocker12345** [comment]
I tried and it didnt work. So it is Kcauldron?

**Comment by dutchy1001** [comment]
yes it might be cauldron. as I said we never worked with it

**Comment by brocker12345** [comment]
Is there a way you can make it support Kauldron?

**Comment by brocker12345** [comment]
I mean everything works except the generation of the world

**Comment by dutchy1001** [comment]
you could try create an empty world with cleanroomgen and call it skyworld

**Comment by brocker12345** [comment]
Ok, il try that

**Comment by brocker12345** [comment]
Ok, thanks I got it!

**Comment by dutchy1001** [comment]
does that do the trick??

**Comment by brocker12345** [comment]
Yep

**Comment by dutchy1001** [comment]
closing as it is sorted
