### ISSUE TITLE
Island Selection - Feature Request

### ISSUE THREAD

**Issue by GiansCode** [rlf/uSkyBlock#510]
Hello there,

I was wondering if it would be possible to add a GUI where players can choose their island schematic when they start their island?

This should be permission based, so, if they have the permission for 3 schematics, only 3 will be in the GUI, if they have permission for 4, 4 will show up, and so on.

Thanks.

**Comment by csorrows** [comment]
I think this is a great idea.

**Comment by rlf** [comment]
We've already been discussing this for a while, and I think we will definitely implement it (eventually).

**Comment by dutchy1001** [comment]
Would be nice to have some input from the public to submit some islands. Size does matter, so don't go overboard.

**Comment by csorrows** [comment]
I would imagine this would be using user created content, not something ready-built. I do like the way you are going though @dutchy1001. A few more optional islands build in would be a great idea.

**Comment by dutchy1001** [comment]
It's nice to have the public have their input too, that means we listen to them as they listen to us. As thanks they will have their names mentioned on the sites.

**Comment by csorrows** [comment]
Yea, it was gone but i dont care. no worries lol

**Comment by dutchy1001** [comment]
With the great input for the submission of islands (NOT) I will close this issue as there is not much input.

closed
