### ISSUE TITLE
lockedDisplayItem

### ISSUE THREAD

**Issue by Adam4CZ** [rlf/uSkyBlock#511]
Versions: 
![usb versions](https://cloud.githubusercontent.com/assets/15090021/10429808/7e921202-70fb-11e5-850e-8cb10ac1028a.png)

I have problem with feature in v2.4.5 - <code>lockedDisplayItem</code>.
For locked challenges I want to have a stained glass pane (e.g. STAINED_GLASS_PANE:14) as in earlier versions. But even though I was allowed <code>displayItemForLocked</code> (you can see in my challenges.yml below), it is not working - challenges always have only <code>displayItem</code> even though it wasn't completed or it was locked.
![2015-10-12_16 13 13](https://cloud.githubusercontent.com/assets/15090021/10429911/5767c360-70fc-11e5-9a6d-7e4321668b28.png)

Part of challenges.yml: http://pastebin.com/raw.php?i=Gdq0HHGZ

Please, help me, I have tried almost everything.

**Comment by rlf** [comment]
It's a typo in the `challenges.yml`, the naming is `lockedDisplayItem` not `displayItemLocked`.

**Comment by Adam4CZ** [comment]
Oh, thanks! It works for locked challenges, but can I also set this for challenges that are not completed like in earlier versions?

btw. In default challenges.yml or on **dev.bukkit** is *displayItemForLocked*.

**Comment by rlf** [comment]
Yes, we made the documentation, and then changed it so it was the same for both challenges, and "default". My bad :)

**Comment by rlf** [comment]
You cannot set a different icon for completed/uncompleted currently.
We changed it - since we felt, that the icon gave more value as a "navigational item" for finding it again and again - and you have more need of locating when it's uncompleted, than you do once it is completed.

**Comment by Adam4CZ** [comment]
OK, thank you again!
I'm very glad that you continue in the development of this plugin. I love this project.

**Comment by dutchy1001** [comment]
Thx for bringing this to my attention, I have updated the bukkit.dev site to the right node.

**Comment by Adam4CZ** [comment]
You're welcome. Wiki here on **github** it's same, it's even older than dev.bukkit.

**Comment by dutchy1001** [comment]
Updated that aswell now
