### ISSUE TITLE
Support modded blocks

### ISSUE THREAD

**Issue by hunter688** [rlf/uSkyBlock#512]
Please add support for modded blocks:
<pre>
--- a/src/main/java/us/talabrek/ultimateskyblock/island/LevelLogic.java
+++ b/src/main/java/us/talabrek/ultimateskyblock/island/LevelLogic.java
@@ -37,7 +37,7 @@ public class LevelLogic {
     private static final Logger log = Logger.getLogger(CN);
 
     private static final Pattern KEY_PATTERN = Pattern.compile("(?<id>[0-9]+)([/:](?<sub>(\\*|[0-9]+|[0-9]+-[0-9]+)))?");
-    private static final int MAX_BLOCK = 255;
+    private static final int MAX_BLOCK = 4096;
     private static final int DATA_BITS = 4;
     private static final int MAX_INDEX = MAX_BLOCK << DATA_BITS;
     private static final int DATA_MASK = 0xf;
</pre>

**Comment by rlf** [comment]
Have you actually tested the above change?
Since that will require quite much more memory for each island calculation-score.

**Comment by hunter688** [comment]
Yes, im using this patch on my SkyTech server about 2 years (from 1.6.4)

**Comment by rlf** [comment]
Implemented previously since cfadd7b

**Comment by dutchy1001** [comment]
I guess the modded blocks are working as there is no further input.
Closing this for now.
