### ISSUE TITLE
Option to customize nether-island

### ISSUE THREAD

**Issue by Banbeucmas** [rlf/uSkyBlock#515]
I really love the new 2.5, i really want an option to have interact with nether island using the nether portal, basicly player will have 2 island at a time ( I also want to change the schematic on nether island also)

**Comment by rlf** [comment]
Not sure I get what you mean with "interact with the nether island"?

**Comment by Banbeucmas** [comment]
For default when we /is create, we will generate an island on the overworld
Now I want to make it able to go generate the island in overworld and nether (island sethome is in overworld) after that, player will build an nether portal and go to the nether island

That's why I said players can have 2 island at a time ( the overworld island and the nether island)

**Comment by Banbeucmas** [comment]
Opps, wrong button XD

**Comment by csorrows** [comment]
Github needs to move that button.

**Comment by csorrows** [comment]
I have not yet tried an alpha of 2.5 so I have not experienced how it works. I would assume you would create a portal to get to your nether island, is this not true?

**Comment by dutchy1001** [comment]
When using the new v2.5 it will automatic create the 2 islands in the "Overworld" and in the "Nether". As this is still in experimental stage many options still need looking into like for example the custom islands for the nether.
We need that basic first running smooth before we can add all other options.

**Comment by rlf** [comment]
I get it now. What you are suggesting, is more or less what we have already implemented in v2.5.

As dutchy states, there is (not yet) any way to override the default nether-island - since that has been carefully tailored to our needs :)

We will - ofc. allow customizations in the future.
Keeping this, but rephrasing it to suit the feature request of custom nether islands.

**Comment by rlf** [comment]
Very basic support will be part of next release.
Meaning, you can overwrite the provided nether schematic manually, and we won't "overwrite" it back.

**Comment by Banbeucmas** [comment]
Btw can you make the nether island and the overworld island connected by nether portals?

**Comment by rlf** [comment]
They should be, if you have the right plugins installed, and let uSkyBlock create the skyworld_nether.

**Comment by csorrows** [comment]
What are those right plugins. I am unable to use the portal in the overworld. Is multiverse-netherportals required?

**Comment by rlf** [comment]
Yes, and the scale of the netherworld MUST be set to 1.

Check out the wiki: https://github.com/rlf/uSkyBlock/wiki/Nether-and-uSkyBlock

But all this should be done automatically with v2.5 - provided you don't have a skyworld_nether, and have configured the plugin correctly.

**Comment by csorrows** [comment]
Yea i missed the netherportals part. Working good now. Thanks.

**Comment by dutchy1001** [comment]
Custom Island for the Nether is working as long they use the same schematic name provided in the uSkyblock/schematic folder (just keep a backup of your own custom nether island as it can be overwritten when updating the plugin).

Closing for now.
