### ISSUE TITLE
Unable to restart and obtain new island

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#518]
I had a player, BlazeFIRE776, attempt to create a new island after giving ownership of their island to another player, Woozypython8135. BlazeFIRE776 was unable to obtain a new island and was instead put back on the island he had given away. This created an instance where uSkyblock recognized him as the island owner but WorldGuard did not. This seems very similar to an issue I reported in the past of a player losing ownership of their island. I have more info this time:

Version info: http://pastebin.com/raw.php?i=CjXm8EEc
WorldGuard region info: http://pastebin.com/raw.php?i=KUiHdeJ9
Island info: http://pastebin.com/raw.php?i=kAJv3V7g
BlazeFIRE776 player info: http://pastebin.com/raw.php?i=bF0gqB7W
Woozypython8135 player info: http://pastebin.com/raw.php?i=Vf2Z2Zr2
Log of events related to BlazeFIRE776: http://pastebin.com/raw.php?i=FmS4Hv5T

**Comment by rlf** [comment]
Great info level.

It seems to most likely be tied to the fact, that Blazefire changed name.

**Comment by BlackBeltPanda** [comment]
I believe the last incident involved a name change, as well.

**Comment by rlf** [comment]
Since this (and quite many others) have been related to the way we currently handle UUID, I've introduced a label for it - so we can get a better grasp at how big the impact is.

**Comment by csorrows** [comment]
Pink? =P

**Comment by dutchy1001** [comment]
If this is still an issue in v2.6.8 then let us know, for now i will close this due to no further comments.
