### ISSUE TITLE
End Portal Issue

### ISSUE THREAD

**Issue by GiansCode** [rlf/uSkyBlock#519]
Hello.

I've got an issue where players can't go through End Portals that they create on their island. I've tried creating a world called skyworld_the_end, and that doesn't seem to fix it. The issue is with Multiverse-NetherPortals.

Here's the error: http://pastebin.com/5EzvSpxx 

I'm posting here because regular end portals work, just not their island one

**Comment by csorrows** [comment]
This has nothing to do with uSkyblock and is a Multiverse Issue. Have you linked the worlds together BOTH ways by following this? https://github.com/Multiverse/Multiverse-NetherPortals/wiki/Command-Reference

**Comment by GiansCode** [comment]
I did. However, the portals that were there first (the ones causing the issue) just had to be remade.

Thanks!

**Comment by dutchy1001** [comment]
You have to create The End world with the name skyworld_the_end and that should be enough to let them use the portals. No need for extra "linking" should be needed then.

I do understand that this is solved so going to close it. If not I can reopen it anytime.

**Comment by csorrows** [comment]
@dutchy1001 He was creating end portals on the islands, not in the nether. This situation DOES require linking AFAIK.

@GiansCode Glad you got it working. Cheers.

**Comment by dutchy1001** [comment]
Just tested this on the live server and after creating the "The End" world called "skyworld_the_end" (command = /mv create skyworld_the_end THEEND) I can use the END portal without having to link. I have MV-Netherportals installed too. No linking needed as I said before.

**Comment by csorrows** [comment]
Ok thanks for testing this dutchy. I have had issues in the past where they did not work until linked. Lots of reports online about it too. Maybe they have fixed it.
