### ISSUE TITLE
Option to have island region expandable

### ISSUE THREAD

**Issue by Banbeucmas** [rlf/uSkyBlock#520]
Like the title said, may be some API of /rg redefine works?
But one thing, can you do it without affecting the others island region

**Comment by dutchy1001** [comment]
As all island are created in the same way with the same sizes it will not be possible to make an option to have different sized island for different players.

**Comment by rlf** [comment]
Actually...
This could be a feature request.
We COULD keep `distance` fixed, and then perhaps make `protectionRange` depend on the perk system.
Not sure how this would handle resets/clearIslands or demotion (i.e. having a larger region, and then losing the privelege).

But, I'd rather allow for neighboring islands to easily be merged, i.e. by utilizing the trust system.

**Comment by csorrows** [comment]
So like set a "max" island size then allow them to use the part of that size they have the node for? That sounds like a great idea if that is what you meant.

**Comment by dutchy1001** [comment]
This would mean by default all islands are further away from each other. I think you waste a lot of worldspace then and making the skyworld unnecessary big. 
For servers that have Dynmap installed it would show most of the world empty or very big gaps inbetween which makes it unattractive for other players to join (this is only my own view on this).

**Comment by csorrows** [comment]
I do agree with your observations but still think it should be an option. I would more then likely use it but make the differences between the island sizes pretty small. By adding just a few more blocks to the dimensions, you actuality gain quite a bit more building space.
