### ISSUE TITLE
All players have same island

### ISSUE THREAD

**Issue by manercraft** [rlf/uSkyBlock#522]
Hello,
I have a big bug, all players on my server have the same island
Picture of version of plugins:
![usb version](https://cloud.githubusercontent.com/assets/1338257/10737985/6eab5888-7c15-11e5-9b4f-a058bb11fca2.png)

**Comment by rlf** [comment]
Please share the content of your config.yml and lastIsland.yml + the location of the shared island.

**Comment by manercraft** [comment]
I have change version for Stability Release v2.4.3

Config.yml https://drive.google.com/file/d/0BylX1J8Knyf5QVZqOUZfNDdXLTg/view
lastIslandConfig.yml https://drive.google.com/file/d/0BylX1J8Knyf5ZTJvQ1FmWkVpZW8/view

**Comment by manercraft** [comment]
For reset this plugin, i need to delete skyworld, lastIslandConfig, folder players, folder completion

**Comment by dutchy1001** [comment]
I need permission to see those files, cant you not use [pastebin](http://pastebin.com/)?

When doing a total reset you can delete the whole uSkyblock folder and the skyworld (I would not delete the skyworld if you have a spawn island setup, unless you saved that as a schematic).

**Comment by csorrows** [comment]
I would make a copy of the config.yml file before deleting the uSkyblock folder though if you don't want to redo it. =)

**Comment by dutchy1001** [comment]
I do agree with csorrows, I would make a total backup of the files. I normally do say this but forgot it this time.

**Comment by manercraft** [comment]
Config.yml http://pastebin.com/x5D2huQS
LastIsland http://pastebin.com/t80jbHtU

**Comment by manercraft** [comment]
I go backup file and delete forlder

**Comment by manercraft** [comment]
What version of plugin would you recommend

**Comment by manercraft** [comment]
I think is a bug with my schematic

**Comment by dutchy1001** [comment]
I would suggest the [v2.4.8](https://github.com/rlf/uSkyBlock/releases/tag/v2.4.8) and if you are start with a total fresh skyworld I would suggest to adjust the distance and protection setting so the value can be devided by 32 (distance 320 and protectionRange 256 (this for further updates)) you can set the spawnSize to 160 then.

**Comment by dutchy1001** [comment]
Is the chest within 15 blocks of the bedrock block on your schematic?

**Comment by csorrows** [comment]
Why divisible by 32? This makes quite a large gap between islands....

**Comment by manercraft** [comment]
I think is fixed, i missing bedrock block on my custom schematic

**Comment by manercraft** [comment]
I'm stupid

**Comment by csorrows** [comment]
Not stupid. Lots of people forget about the bedrock in their schematic.

**Comment by dutchy1001** [comment]
What csorrows said, it happens don't worry about it. Glad it's fixed.

I close this issue and if more problems arise just let us know.

**Comment by rlf** [comment]
@csorrows Divisible by 32, since we can then rely solely on regenerate instead of WorldEdit for clearing islands. Something that becomes required in v2.5, when we introduce nether-islands (WE regen is simply too slow, even with AWE-Premium).

**Comment by csorrows** [comment]
Yes, I have setup a plots plugin that uses regen. It's definitely the efficient light weight way to go. Barely any hit on resources. That's a great idea.

**Comment by csorrows** [comment]
So in other words, islands will be either 0 or 32 blocks apart if not further?

**Comment by dutchy1001** [comment]
both have to be set either the same or be able to be divided by 32 (or it wont create the nether or errors in console)

**Comment by rlf** [comment]
Unfortunately no csorrows - currently this is the "lay of the land":
```
+---+---+---+---+---+---+
|   |   |   |   |   |   |
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
|   |   |   |   |   |   |
+---+---O---+---I---+---I
|   |   |   |   |   |   |
|   |   |   |   |   |   |
+---+---+---+---+---+---+
|   |   |   |   |   |   |
|   |   |   |   |   |   |
+---+---I---+---I---+---+

        |<- d ->|<- d ->|
            |<- p ->|

O = Origin (0,0)
d = distance
p = protectionRange
```
Meaning, when we need to clear an island, we need the whole area we want to clear to be aligned with chunks (to avoid having to rely on WorldEdit).
Since the `protectionRange` is the "side of an island", the *radius* of the island is `protectionRange/2` - and for that to be aligned with chunks, both `distance` and `protectionRange` need to be divisible by 32.

Alternatively (as you sort of suggest), we should only use distance to clear regions - but currently we use the WG region defined by `protectionRange` for almost all "on-island" operations.

**Comment by csorrows** [comment]
Yes, that is exactly what I was suggesting. I missed the whole region thing. Thanks for the very clear explanation.

**Comment by rlf** [comment]
Well, as you stated earlier, if we were to "just use the distance", spacing between islands could be arbitrary, as long as the distance ensured no island would be able to build on a chunk that would be cleared by a neighboring island-reset. This is one of the thought I've had reg. optimizing the performance for `clearIsland`.

I.e.
```
  if island is chunk-aligned:
    clear all chunks within the island using world.regenerate (fast)
  else if island < chunk-aligned-bounding-box < distance:
    clear all chunks touched by the island using world.regenerate
  else
    clear inner-chunks using regenerate and
    clear border-regions using WorldEdit
```
The else clause is what we have to day, and since border-regions will be empty, when islands are chunk-aligned, that is the current requirement for v2.5

**Comment by csorrows** [comment]
Yes, Keep the requirement on sizing for distance and require it to be chunk aligned and full chunks. I feel his would satisfy the alignment requirement and allow spacing to be anything the owner wishes. As long as distance requires it to end at chunk borders, you can regenerate all chunks inside the distance area using world.regenerate. If the "spawn" area is the same size as the island distance setting or any multiple of and chunk aligned, all regions around it should also be chunk aligned.
