### ISSUE TITLE
Mypet

### ISSUE THREAD

**Issue by brunokcampos** [rlf/uSkyBlock#523]
I need pet not enter. World. Skyblock end block command player not enter items survivor game. Skyblock sorry my English is bad tanks for you help

**Comment by csorrows** [comment]
I'm not exactly sure what you mean by this, but I will try to help.

I think you mean you do not want pets to enter the skyblock world. As far as I know, this would have to be handled by the pet plugin so request per world settings from them.

To keep inventories separate per world, use multiverse-inventories found here: http://dev.bukkit.org/bukkit-plugins/multiverse-inventories/

Please reply if this does not solve your problem.

**Comment by dutchy1001** [comment]
After reading your other post here on [MyPet](https://github.com/xXKeyleXx/MyPet/issues/552) i understand you want to block pet access to the skyworld.

I been looking at the config for MyPet and cant find a "world" setting were to allow or disallow pets in all the worlds. 
The only thing I can suggest is to "negate" all the MyPet permissions in the skyworld.

As this is not a uSkyblock issue but more a MyPet issue i will close this.
