### ISSUE TITLE
FIX for Hoppers and OreGenerators / Cobble Generators

### ISSUE THREAD

**Issue by DTS-MC** [rlf/uSkyBlock#525]
Please add this code as a listener,

it has been tested
 @EventHandler
	     private void onBlockBreakOverHopper(BlockBreakEvent event) {
		 
		 if(event.getBlock().getRelative(BlockFace.DOWN).getType().equals(Material.HOPPER)) {
		     //Initialize a nice variable list here
		     Collection<ItemStack> stack = event.getBlock().getDrops();
		    
		     event.getPlayer().giveExp(event.getExpToDrop());
		     event.setCancelled(true);
		     Iterator<ItemStack> i = stack.iterator();
		     while(i.hasNext()) {
			 Hopper hoper = (Hopper) event.getBlock().getRelative(BlockFace.DOWN).getState();
			 hoper.getInventory().addItem(i.next());
		     }
		     event.getBlock().setType(Material.AIR);
		 }
	     }

**Comment by csorrows** [comment]
I'm currently learning Java. Am I reading this right and it places the item on break over a hopper directly into the hopper's inventory?

**Comment by rlf** [comment]
First off, this is not the way we do things.

If you want to add a feature, describe the feature you want added, and then you can possibly post a pull-request.

Keep in mind, that the code will impact all users, not just your little sandbox.

The above code:
a) Will only handle hoppers DIRECTLY beneath a broken block (i.e. not if it's two blocks below).
b) Will handle ALL block breaks, regardless of world, or reason (performance impact).
c) Will fail if the block wasn't broken by a player (event.getPlayer() is null).
d) Will fail if the block broken didn't produce any drops (i.e. using a wrong tool)
e) Will fail to do what is intended if the hopper is full.

And finally - why have this at all? Why not just let the hopper mechanics do it's thing normally?

**Comment by csorrows** [comment]
I did miss the point of even adding the code as I saw no reason for it. <confused>
