### ISSUE TITLE
Economy with PlayerPoints

### ISSUE THREAD

**Issue by maol3** [rlf/uSkyBlock#528]
I have Vault installed on my server and it is hooked into PlayerPoints. However, when one has completed a challenge, the player gains nothing in currency. No error in console or so, either. uSkyBlock doesn't seem to recognize it as an economy plugin.

https://gyazo.com/b9f254b2b0ed37cda48325afeee63eb9
https://gyazo.com/ecf2d8609880e4f295b3a65602def917
https://gyazo.com/9d3481958347c5fad9fc62b7a028acbe

**Comment by dutchy1001** [comment]
Your Vault and WG are both out of date. If you update Vault to [v1.5.6](http://dev.bukkit.org/bukkit-plugins/vault/files/52-vault-1-5-6/) and WorldGuard to [v6.1](http://dev.bukkit.org/bukkit-plugins/worldguard/files/46-world-guard-6-1/) or dev build from [here](http://builds.enginehub.org/job/worldguard?branch=master) (I use 1633 on my server) it might help to solve it. 
I haven't worked with PlayerPoints so I cant tell for sure. If Vault hooks into PlayerPoint then it should work, see if Vault also hooks into uSkyblock aswell in the log.

**Comment by maol3** [comment]
Updated both Vault and WorldGuard to latest version, no success. How can I see if Vault hooks into uSkyblock?

**Comment by dutchy1001** [comment]
Just checked and I thought it would be in the log, but I cant find it either

**Comment by maol3** [comment]
However, uSkyblock starts up at all. Doesn't that mean it hooks into Vault, because when Vault is unloaded, it doesn't even start at all, since it's depending on Vault.

**Comment by dutchy1001** [comment]
Which version are you using? the one on the bukkit page or on Spigot (is it on spigot??)

**Comment by rlf** [comment]
Have you disabled economy in your config.yml ?

**Comment by dutchy1001** [comment]
I'm thinking this is either a PlayerPoint-Vault issue or PlayerPoint is outdated, the last update was june 2014 and lots have changes since.
Dont think there is from our side anything we can do, unless our dev thinks of something briliant.

**Comment by rlf** [comment]
Well, I'm thinking it could be a timing issue, i.e. uSkyBlock registers with Vault before PlayerPoints does.

So, just to test, will `/usb reload` resolve the issue with currency?

**Comment by maol3** [comment]
That was very good guessed, /usb reload did resolve the problem. Is there any way to change the order that Vault registers uSkyblock and PlayerPoints?

**Comment by rlf** [comment]
Yes, I've made a more robust registering in 88f4b6f19cef9011f11f35a489d581b70492fab9 which will be available in the next release.

**Comment by csorrows** [comment]
From what I know, PlayerPoints is not registered as a default economy. The plugin must actually request playerpoints. Again, this is how I understand it.

**Comment by rlf** [comment]
Ready for test in v2.5

**Comment by maol3** [comment]
Nothing has changed, a reload is still required for enabling the economy. Thanks for the update though.

**Comment by rlf** [comment]
Well, we are sort of at an impasse then, we currently rely on Vault, and Vault exposes a way to get the economy provider - but we have no way of knowing, when/if an economy provider is going to register in Vault later.

I've added some delays, so it's at least possible to control when uSkyBlock "continues initialization".

**Comment by maol3** [comment]
The issue has been solved now.

Side-note: I can no longer do the cobblestonegenerator challenge, is that due to the change of challenges (per island instead of per player) or is it my fault? Haven't investigated it a lot.

**Comment by dutchy1001** [comment]
As default it should be set as "player" , as long you haven't set it to "island" then you should be able to complete it (first time). 
You can reset the challange with "/usb challenge [name] reset cobllestonegenerator" and see if you do it again.

If you mean you cannot do the challenge at all then there might be a mistake in the challenges config with the cobblestonegenerator section.

**Comment by rlf** [comment]
I did change the cobble stone challenge, to showcase the new `name` field for displaying in GUI.

**Comment by rlf** [comment]
Yup, that one stopped working... the GUI apparently don't like the new names (facepalm).

This is what happens when Dutchy don't get a chance to test the things I spew out ...

**Comment by dutchy1001** [comment]
Party or Minecraft, Party or Minecraft, Party or Minecraft, Party or Minecraft
The Party won

**Comment by dutchy1001** [comment]
the original issue has been fixed, if the "side-note" still occuers plz make a new issue.

closed
