### ISSUE TITLE
Block non-banned players from entering a locked island

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#529]
We currently block banned players from "flying or walking" to an island they have been banned from.

But, we don't block "visitors", not even when the island is locked (we just block them from using  `/is warp`).

We should block all visitors from visiting an island when it's locked (perhaps), though this will also mean no `/tpa` or similar, unless trusted, or island is unlocked.

**Comment by rlf** [comment]
This is more required with the new nether requirements, since we will get a lot more servers with `distance` = `protectionRange` - i.e. no space between islands, higher chance of "visitors from migration".

**Comment by csorrows** [comment]
I agree, this should be a thing.

**Comment by dutchy1001** [comment]
tested this on v2.5.3 working as expected now
