### ISSUE TITLE
[Bug] /is reset don't reset nether island.

### ISSUE THREAD

**Issue by voodootje0** [rlf/uSkyBlock#530]
When you type /is reset at your nether island the normal island will be reset. Than when you go to the nether island a new island is generated but the old placed blocks do exist.
![image](https://cloud.githubusercontent.com/assets/6852308/10861237/1078ca40-7f79-11e5-9afa-24294d1c6b07.png)

Using this version: https://github.com/rlf/uSkyBlock/releases/tag/v2.5

**Comment by rlf** [comment]
Could you please share the log as well, since that looks like the clearIsland hasn't been executed for the nether island - and most likely, the logs will tell us why.

**Comment by rlf** [comment]
Reproduced it. Investigating.

**Comment by rlf** [comment]
Ready for test in v2.5.1 release (next release)

**Comment by csorrows** [comment]
So the current release has an unstable nether island reset? I was hopping to put the current one on my dev server and test it out with my staff.

**Comment by voodootje0** [comment]
Thank you for fixing it, I wil test the next release when it's out.

**Comment by rlf** [comment]
v2.5 is still in state "pre-release" @csorrows - this is one of the reasons.

**Comment by csorrows** [comment]
Yes I understand that @rlf - I just thought it was further along then it was is all.
