### ISSUE TITLE
Island levels over 100 gets divided by 100

### ISSUE THREAD

**Issue by maol3** [rlf/uSkyBlock#531]
Describing it quite good in this video: https://www.youtube.com/watch?v=a2nwo6xsyHk
I don't think this ever has happened before the 2.5 release.

Server info: https://gyazo.com/96877e509a5139cda01be1b0a0ea979a

**Comment by rlf** [comment]
That seems like a purely cosmetic (i.e. swedish translation) issue.

The value isn't divided by 100, but the representation seems to add a ','.

What does the level say, if you use english? (`/usb lang en`).

**Comment by maol3** [comment]
Yeah, that is true. You're right. However, I translated '§aIsland level is {0,number,###.##}' to '§aSkyblock level är {0,number,###.##}'. Did I do that wrong?

**Comment by rlf** [comment]
Yes, but I don't have a clear answer to what the right way is :) 

Currently investigating. but the `,` means "group-separator" i.e. thousands separator - not sure how to change to `,` as a decimalSeperator - if it doesn't happen automagically.

**Comment by rlf** [comment]
I found a work-around - not sure what the implications will be.
It seems the numbers etc. are formatted according to the `Locale.getDefault()` Locale - but setting this, to the language set for uSkyBlock, will most likely have implications for all other plugins running on the server.

Alternatively, you can control this variable, by adding the following to your server-startup script:
```
-Duser.language=sv
```
Again, this approach will change more than just the uSkyBlock plugin.

I will push a change, where-in we set the default locale to the language active for uSkyBlock.

If we get some bugs reported on this, we will make it configurable whether to set it or not.

**Comment by rlf** [comment]
I changed this - by changing the thirdparty jar we use (gettext-commons), so that now correctly uses the locale of the translation.

Basically, what this means is, translators should still use the "default-formatting", i.e. `{0,number,0.##}` for swedish, danish, german etc. and the actual formatting will respect the Locale (i.e. use `,` instead of `.`).

**Comment by dutchy1001** [comment]
tested with different languages and working fine
