### ISSUE TITLE
Breaking blocks on Nether

### ISSUE THREAD

**Issue by maol3** [rlf/uSkyBlock#532]
If you are on another player's Nether island, you may not break blocks but when you attempt to do so, new blocks are being generated even if you don't have the permission to break blocks in the region.

I am running the latest pre-release.

**Comment by maol3** [comment]
And also, the block you are breaking (if you don't have permission), that is the block that will be generated as well. So if you're breaking a gravel block, only gravel blocks will spawn around the island (or vice versa).

**Comment by rlf** [comment]
We identified this, and have already fixed it in 86f18e63edf041a5786af2bc27cfaf710d1f9313

**Comment by maol3** [comment]
Sounds good. Anyway, an update for swedish: http://pastebin.com/akhsvPk8

**Comment by dutchy1001** [comment]
this is fixed.

closed
