### ISSUE TITLE
Multiple Islands & Region List Too Large

### ISSUE THREAD

**Issue by DrChiz** [rlf/uSkyBlock#536]
Hello,

On our current version of Skyblock, custom to our server, we can have up to 8 islands for an individual user to create and own (the number is determined by a permission node that we give to various level of donators). I was hoping this could be added to the plugin some time, and obviously things like if you make someone else the leader, it would remove one of your owned islands and add one to theirs, that kind of stuff. Each island has individual co-operative experiences on them too so while you share an island with Person X and Person Z, you may not want them on your second island, but instead want Person Y to be trusted there.

Also back in the day, this was 2013. Skyblock on minecraft multiplayer servers was relatively new. Ours was so popular that the WG region list was like 80k lines at the end, before we had to go custom and did that method and instead write the ownership into region/land files.

I want to use your plugin, very badly, as it seems almost perfect. But my concern is scalability. I know WG has gotten a lot better in recent addtions and we're on the latest and greatest for all 1.8 plugins and 1.8.8 spigot, so I'd really like to know if we'll run into the same issue we had back in 2013 with the WG region list being too large to read/parse through, which inevitably would end with the server crashing.

Thank you :)

**Comment by rlf** [comment]
That sounds like a topic for WG.
We've had quite many performance issues as well in the past - but are getting better.
We currently have some instability issues regarding name-changes and UUID - and for a server your size, that will most likely manifest it self.
Having multiple islands is currently not something we support (or plan to) - you can have one, but can be trusted on many.
The plugin relies very heavily on one player, one island, so adding more will not be a simple task.

**Comment by DrChiz** [comment]
So this plugin won't scale to a server of our size? Also I noticed the files are (name).yml but there's something called like uuid2name, is that converting them so it's easy to manage/look through names instead of UUIDs?

**Comment by rlf** [comment]
As I stated, the current UUID implementation is not very good, and yes, it tries to keep track of UUIDs to names.

It is on the todo list to get that part "right", and has a high priority, so we will look into that as some of the features for the next release.
