### ISSUE TITLE
Support custom .po files, and get rid of the .properties files

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#538]
We are seing some "noise" reg. the way we currently support "custom translations".

We are going to change this, to be purely .po based, and then support .po files in the plugin-data-folder instead of the .properties files.

**Comment by dutchy1001** [comment]
My tests were positive but I would like to see some other conformations as well, every language file can be different.

**Comment by dutchy1001** [comment]
this system is working from v2.5.5 

Closing for now.
