### ISSUE TITLE
Conversion utility for changing distance and protectionRange

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#539]
Currently, the only way to successfully change distance and protectionRange, is to restart everything (reset the world).

To support resizing from the plugin, we would have to move ALL islands, in a specific order, using WorldEdit.

This will be a very heavy task - but we should consider implementing it, if there's enough servers that want it (i.e. the only way they will be able to keep their islands, and enable skyworld-nether).

**Comment by MrFiliper** [comment]
When does it plan to add?

**Comment by rlf** [comment]
Not currently planned - depending on the need for it, versus priority of all the other tasks.

**Comment by csorrows** [comment]
I'm starting clean so I don't need this. I can expect though, owners would be upset having to start the world over.

Seems like a huge undertaking for both you are the poor servers though.

**Comment by MrFiliper** [comment]
Yes, it is very necessary for me. I can not delete 300 islands, of course I would be happy for the nether Islands.

**Comment by rlf** [comment]
You do understand, that it means you'll have to MOVE (like in WE-copy-paste) 300 islands?
Which IMO is not something you'll "just do" either.

**Comment by MrFiliper** [comment]
Therefore plan to add an option to the concert directly to the plugin?

**Comment by rlf** [comment]
Your google-translate skills good - are not
Understand you, I do not

**Comment by csorrows** [comment]
LOL @rlf

**Comment by MrFiliper** [comment]
Conversion Islands are planning to add to the plugin, or not?

**Comment by csorrows** [comment]
As @rlf said in the first post:
>This will be a very heavy task - but we should consider implementing it, if there's enough servers that want it (i.e. the only way they will be able to keep their islands, and enable skyworld-nether).

**Comment by dutchy1001** [comment]
After looking in to this it would be an immense job for the server and with that the server load would be unacceptable. 
For now this is put on the shelves (meaning it wont happen soon) till we can find a better solution.Restarting is still the best option for now.

**Comment by MrFiliper** [comment]
Thank you for your clear answer!

**Comment by dutchy1001** [comment]
As this is virtual almost impossible I will close this, if we come up with a solution we will open a new issue.
