### ISSUE TITLE
Make UUID the right way

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#540]
Our current UUID implementation has proved to be insufficient for a lot of users, and it's currently forcing us to do stuff during player-logon, we'd rather not do (introducing async loading, and concurrency issues).

We should change to a 100% UUID aware model, instead of the current "keeptrackofnamesandrenameonnamechange".

**Comment by vk2gpz** [comment]
what is the priority on this item? I'm thinking about modifying it to do this.

**Comment by rlf** [comment]
Related to #406 #582
