### ISSUE TITLE
Prevent players from flying into other player's island

### ISSUE THREAD

**Issue by timyboy12345** [rlf/uSkyBlock#543]
Hi there, I have VIP++'s given the /fly permission. But the problem is they now can fly into other players island, while it isn't allowed. Is there any way to prevent this from happening?

**Comment by dutchy1001** [comment]
As far I know when you give your players the command /fly this was always a possibility.
Players can on their turn "lock" the island with the /is lock command and unlock with the command /is unlock or use the GUI and click on the iron bars. This should block "flying visitors" from accessing other islands, trusted and party members still have access to the locked island their member off.
Players do need the permission usb.lock to have access to this command

**Comment by timyboy12345** [comment]
Owh, I didn't know that that takes care of it, thanks :p

**Comment by dutchy1001** [comment]
np closing this issue
