### ISSUE TITLE
[Idea] move cancels teleport

### ISSUE THREAD

**Issue by voodootje0** [rlf/uSkyBlock#547]
Hey dear,

When you type /is home and the teleport delay is 2 seconds you can move.
This is a big problem. When players has a waterpool on their /is home location and fall out of the world players will be alive. Please add an option when you move the teleport will be canceled.

- voodootje0

**Comment by voodootje0** [comment]
When can this be added, it's not to big to make and it is very annoying that players can fall their island and be still alive.

**Comment by csorrows** [comment]
@voodootje0, @rlf and @dutchy1001 do this for free and using their own personal time. Please be respectful and don't try to rush them.

**Comment by dutchy1001** [comment]
rlf already has this given the tag "reature request" meaning he will add this. In the meantime you can set the teleport delay to a longer time so when they fall it will take longer before they get to their island which will lead to their death in the void.

**Comment by voodootje0** [comment]
Hey @dutchy1001,

Sorry, I thought "Feature request" is only a idea and people can give their opinion, not that one of you will add any idea.

**Comment by rlf** [comment]
It means "not rejected, a request, might be implemented, eventually, if someone does it" :D

**Comment by dutchy1001** [comment]
Added and working from in v2.5.7
