### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by KriticalPvP1** [rlf/uSkyBlock#549]
Hello,
I need to change the language of uskyblock, but when put  /usb lang es in game or console show this: http://pastebin.com/RkPZFrd6 

Versions:

https://gyazo.com/19d12962fed2a6c2c08126d95398577a

**Comment by csorrows** [comment]
Have you tried changing it in the config?
1) Shutdown the server.
2) Open plugins/uSkyBlock/config.yml
3) Change:
># The language used in the plugin (en is default).
>language: en
To:
># The language used in the plugin (en is default).
>language: es
Restart server.

**Comment by rlf** [comment]
Try reading the output:
```
You do not have access
```
And perhaps do it as OP, or get the `usb.admin.lang` permission.

**Comment by KriticalPvP1** [comment]
@csorrows I put the language: es and i relaod the server but the server continue in english

**Comment by dutchy1001** [comment]
Update your uSkyblock version as the version you are using still had big bugs in the language system and didn't work properly, try the last version before the nether update. [Click here](https://github.com/rlf/uSkyBlock/releases/tag/v2.4.8) to download the v2.4.8

**Comment by csorrows** [comment]
@rlf I DID see the output. I figured it would be easier to help with the setting itself rather then the permission issue.

**Comment by rlf** [comment]
I missed it would was v2.3, Dutchy is correct in stating, that localization was sketchy back in that version.

**Comment by rlf** [comment]
Luv phone typing....

**Comment by KriticalPvP1** [comment]
When i put the v2.4.8 i put the " / is " command and I get this all the time .
![asdasd](https://cloud.githubusercontent.com/assets/12894358/11019884/e11fd9e6-860d-11e5-9a47-3258c285208f.png)

**Comment by dutchy1001** [comment]
That means you have a wrong depended plugin. Upgrade VAULT to v1.5.6

**Comment by KriticalPvP1** [comment]
i have the vault 1.5.6 but that error still dating

![sin titaaaulo](https://cloud.githubusercontent.com/assets/12894358/11020570/70410806-8623-11e5-8b2d-aeab07fde579.png)

**Comment by dutchy1001** [comment]
When I click on your link provided in the first message there is Vault version 1.4.1-b436. check if you dont have 2 vault jars in your plugins folder.

**Comment by KriticalPvP1** [comment]
I now have the old version of skyblock because the new version now don't work me

![1dffbcea077efe8c9f2e09e9d234b2bd](https://cloud.githubusercontent.com/assets/12894358/11022370/4356d822-865d-11e5-9a0a-f30d6b1c2fcc.png)

**Comment by dutchy1001** [comment]
With the updated Vault it should work. Updating your craftbukkit to 1.8.8 might help but not for sure (all 1.8 clients can still login when server is 1.8.8). 
If you put the v2.4.8 jar into the plugins folder delete (or relocate) the old one. restart the server and if it wont work post the full startup log, through pastebin, here so we can see were it goes wrong.

**Comment by KriticalPvP1** [comment]
I update to 1.8.8 and don't work, pastebin to startup log: http://pastebin.com/q2C7wXcJ

**Comment by rlf** [comment]
Did you try reading the output of that pastebin? My dear friend?

It says:
```
[05:15:52] [Server thread/WARN]: [uSkyBlock] Task #6 for uSkyBlock v2.5.3 generated an exception
java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.api.MultiverseWorld.setGenerator(Ljava/lang/String;)V
```
The logical conclusion would be, that the MultiverseCore isn't the right version - try updating that as well - and I think you will get further.

**Comment by KriticalPvP1** [comment]
Now show this error: http://pastebin.com/Kw3g8eEL

**Comment by dutchy1001** [comment]
You are using the es Spanish translation? This might be the cause atm of the last issue you have. there will be a fix for the language soon.

**Comment by dutchy1001** [comment]
update to [v2.5.6](https://github.com/rlf/uSkyBlock/releases/tag/v2.5.6) and see if the problem still exists.
