### ISSUE TITLE
[Question] Can I set spawn size to 0?

### ISSUE THREAD

**Issue by csorrows** [rlf/uSkyBlock#550]
Can I set:
>    # [integer] Area around 0,0 where islands will not be created to protect spawn.
    spawnSize: 320

To:
>    # [integer] Area around 0,0 where islands will not be created to protect spawn.
    spawnSize: 0

Will this cause any issues or will it just ignore the skyworld spawn all together?

**Comment by rlf** [comment]
Try it.
It should ignore it, but it might still skip 0,0 as an island location

**Comment by Adam4CZ** [comment]
I tried it, because I don't use skyworld spawn (Essentials), but bedrock at 0,0 didn't replaced by island. Around bedrock is free space without protection (<code>spawnSize: 0</code>) and islands began to form up far from bedrock (from config at 130,0 ; 0,130 etc. - <code>distance: 130</code>).

**Comment by dutchy1001** [comment]
That does make sense if island distance is set to 130 (for the nether version not a valid number). Spawn will then adjust itself to correct the size to fit islands nice around it. If you really want to use location 0,0 then you can try the command (within 15 blocks of the bedrock) "/usb island register [name]". Not sure if that can cause problems, but trying wont hurt.

**Comment by csorrows** [comment]
So I don't know if I am understanding this correctly @Adam4CZ. Are you saying that it still leaves an unused area the size of an island for the spawn area when it is set to 0?

**Comment by dutchy1001** [comment]
yes it does, just the middle of thre circle were the islands are build around (0,0).

**Comment by Adam4CZ** [comment]
@dutchy1001 I don't use nether island and for me is **32** high number for distance between island protects (I don't want that the island protects were "glued" to each other.), so I have <code>protectionRange: 125</code> and <code>distance: 130</code> (distance between protects is </code>5</code>).

@csorrows If I set <code>spawnSize: 0</code>, bedrock at 0,0 wasn't automatically replaced by island (maybe it would solve */usb island register [name]* that whote @dutchy1001 ). It's just free space for island in the middle of islands circle.

**Comment by dutchy1001** [comment]
That is ofcourse totally up to you.
But to come back to the orginal question, you can set the spawnsize to 0. It automatic adjust to the island distance and with that it build around the 0,0 location. 
As said before to use the command to fill in that 0,0 location with an island is again upto you.

**Comment by rlf** [comment]
The bedrock placed at 0,0 is placed when `spawnSize` > 0, and no spawn exist.

Unfortunately, we seem to have a bug, forcing the spawnSize to be atleast 50 blocks :(

I will go fix ASAP.

**Comment by csorrows** [comment]
Thanks rlf. Just seems weird having a void area in the middle of everything. I guess I could just make it my island so the others spawn around it.

**Comment by rlf** [comment]
Tested the above fix, and now it works (will be part of next release).
![2015-11-08_12 10 50](https://cloud.githubusercontent.com/assets/503044/11021686/4b18d384-864a-11e5-81bc-74c0d48431eb.png)

**Comment by csorrows** [comment]
OMG thats awesome!! Thanks man!

**Comment by dutchy1001** [comment]
I confirm this is working.
Spawn can be set to 0 (zero) and an island will occupy that location too
