### ISSUE TITLE
Sign Join

### ISSUE THREAD

**Issue by GiuseppeGroth** [rlf/uSkyBlock#553]
Hello

can you add 

sign commands

**Comment by csorrows** [comment]
Could you just use this: http://dev.bukkit.org/bukkit-plugins/command-signs/

**Comment by rlf** [comment]
We currently have no join command, only an `/island invite` and `/island accept`.
Can't think of a good way to get this to work with signs.

**Comment by dutchy1001** [comment]
The suggestion csorrows made looks to me the best solution, I dont think if an other plugin is available we should add it to our plugin

Closing this for now (it acan always be opened again or re-requested
