### ISSUE TITLE
nether 

### ISSUE THREAD

**Issue by MrFiliper** [rlf/uSkyBlock#560]
If i setup "distance: 400" and "protectionRange: 320", nether not generated. Please edit this, if setup 320 in protectionRange, nether will create. I cant change island distance to 320. I have 300 islands in the server.

**Comment by dutchy1001** [comment]
I explained yesterday that both value's need to be able to divide by 32 so 400 is not a valid number(remember 12.5??). This cant be changed.

**Comment by MrFiliper** [comment]
I thought only "protectionRange". Ok. Sorry, my mistake.
