### ISSUE TITLE
Permission for preventing players to fly into someone's island doesn't work

### ISSUE THREAD

**Issue by timyboy12345** [rlf/uSkyBlock#561]
So I've given everyone on the server the permission usb.lock. But it doesn't work, it still says 'You don't have acces to this command' How can I fix this? Because it's getting a little intense between the island owners...

**Comment by dutchy1001** [comment]
not sure what is causing that as when I set it and lock the island it works. What versions are you using??
Do "/usb version" and post the output here plz

**Comment by timyboy12345** [comment]
ehm... I get the help page. So this:
![schermafbeelding 2015-11-11 om 19 06 30](https://cloud.githubusercontent.com/assets/15676509/11098766/72018702-88a7-11e5-9d74-2e3f65d05792.png)

**Comment by dutchy1001** [comment]
if it shows you this page then you probably are not in OP mode or doesnt have the right permission. Op has all commands so if you can OP yourself then ypou should be able to see the "/usb version" command.
version 2.2-HF1 has the command /usb version, not before. Guess this means you need to do a massive update.

**Comment by timyboy12345** [comment]
And it doesn't work... the whole skyblock doesn't work.
HELP!!!! Older versions don't work either, HOW DO I FIX THIS??? When I do /island it just gives 
![schermafbeelding 2015-11-11 om 19 27 14](https://cloud.githubusercontent.com/assets/15676509/11099185/3b16db86-88aa-11e5-8e5a-19f27f7e9658.png)
And I can't do /island home or something like that. It doesn't give any errors. The only thing I can find about Uskyblock in the console is 
![schermafbeelding 2015-11-11 om 19 28 03](https://cloud.githubusercontent.com/assets/15676509/11099220/64f39494-88aa-11e5-96d7-38aac013d3bd.png)
How do I fix this? Or how can I get the menu back? I use spigot 1.8.8

**Comment by dutchy1001** [comment]
It means you are missing or using a wrong depended plugin. You havent read the page I linked in my previous message on "Bug report" or you would have seen we need:
* usb version
* Spigot/bukkit version
* WorldEdit version
* WorldGuard version
* Vault version
*multiverse vesion

if the command "/usb version" aint working then you have to do in manual by reading the log file.

After the info is posted we can help, not before.

**Comment by timyboy12345** [comment]
I want to use Uskyblock 2.5.3, so:

USB: 2.5.3
Spigot: 1.8.8
Worldedit: 6.0
Worldguard: 6.0
Vault: Vault-2
Multiverse: Multiverse-core-2.4

**Comment by dutchy1001** [comment]
ok there a few you need to update

* usb - fine
* spigot - fine
* WE - link to [v6.1](http://dev.bukkit.org/bukkit-plugins/worldedit/files/61-world-edit-6-1-up-to-mc-1-8-8/)
* WG - link to [v6.1](http://dev.bukkit.org/bukkit-plugins/worldguard/files/46-world-guard-6-1/)
* Vault - Vault 2 doesnt exist try this version [here](http://dev.bukkit.org/bukkit-plugins/vault/files/52-vault-1-5-6/)
* Multiverse - link to [v2.5](http://dev.bukkit.org/bukkit-plugins/multiverse-core/files/28-2-5-b699-beta/)
This is the main reason your usb didnt work. I use "dev" versions and links for these are on the [bukkit](http://dev.bukkit.org/bukkit-plugins/uskyblock/) page of the plugin.

**Comment by timyboy12345** [comment]
Thank you! The only problem is, /is lock still doesn't work. But the whole plugin finally works again!!!! And /usb version works to. It says I have 1.5.3, but when I do /is lock it still says "You don't have acces to this command!" So is this a bug? Or is there still something wrong, because I have all the latest versions of the plugins now, and I've got permission.

**Comment by dutchy1001** [comment]
"It says I have 1.5.3" from what?? (I presume Vault)

"You don't have acces to this command!" means the permission is not given or wrong. (usb.lock)
Check the permissions file. 
You can come and test it on our "show" server (uskyblock.redirectme.net)

**Comment by timyboy12345** [comment]
1.5.3 stands for Uskyblock version. And I just do **/pex group owner add usb.lock** and it adds the permission to my list (I've seen it in permissions.yml) but it still says **You don't have acces to this command!**

**Comment by rlf** [comment]
Ok, tbh I haven't read all the preceding text. But given the title, and the last couple of issues, I'll try to layout what works, and how it works.

Locking an island is done using the `/is lock` command, and this command is enabled by having:
a) `options.island.allowIslandLock: true` in the `config.yml` and
b) Having the permission node `usb.lock` and
c) Having the island-permission `canToggleLock` (given by the Group UI accessed from `/is`).

The locking works (prior to 2.5.3) by disallowing players to teleport to the island (i.e. using `/is warp <name>` or `/tpa`), and after 2.5.4 by also blocking players from entering the island by foot/flying.

If you get the `You don't have access to this command` either you have disabled island-locking in the `config.yml` file, or you do not have the `usb.lock` permission in the world from where you try to invoke the command.
