### ISSUE TITLE
error building skyblock

### ISSUE THREAD

**Issue by woolwind** [rlf/uSkyBlock#562]
the maven install is dying starting here:

[WARNING] Could not transfer metadata com.sk89q:worldguard:6.0.0-SNAPSHOT/maven-metadata.xml from/to Plugin Metrics (http://repo.mcstats.org/content/repositories/public): Failed to transfer file: http://repo.mcstats.org/content/repositories/public/com/sk89q/worldguard/6.0.0-SNAPSHOT/maven-metadata.xml. Return code is: 522 , ReasonPhrase:Origin Connection Time-out.

I'm getting complete packet loss trying to reach repo.mcstats.org - is it gone?

**Comment by Kagamul** [comment]
While I do get the same warning, I can build it without any errors. Could you maybe post the exact reason why the build failed? Usually it says something like [Build Failure]: something something

**Comment by woolwind** [comment]
maybe you have cached data? I haven't built this in a long time so don't have anything in maven cache to work with.


[INFO] ------------------------------------------------------------------------
[INFO] Building uSkyBlock-Core 2.5.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.mcstats.org/content/repositories/public/com/sk89q/worldguard/6.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.sk89q:worldguard:6.0.0-SNAPSHOT/maven-metadata.xml from/to Plugin Metrics (http://repo.mcstats.org/content/repositories/public): Failed to transfer file: http://repo.mcstats.org/content/repositories/public/com/sk89q/worldguard/6.0.0-SNAPSHOT/maven-metadata.xml. Return code is: 522 , ReasonPhrase:Origin Connection Time-out.
[WARNING] Failure to transfer com.sk89q:worldguard:6.0.0-SNAPSHOT/maven-metadata.xml from http://repo.mcstats.org/content/repositories/public was cached in the local repository, resolution will not be reattempted until the update interval of Plugin Metrics has elapsed or updates are forced. Original error: Could not transfer metadata com.sk89q:worldguard:6.0.0-SNAPSHOT/maven-metadata.xml from/to Plugin Metrics (http://repo.mcstats.org/content/repositories/public): Failed to transfer file: http://repo.mcstats.org/content/repositories/public/com/sk89q/worldguard/6.0.0-SNAPSHOT/maven-metadata.xml. Return code is: 522 , ReasonPhrase:Origin Connection Time-out.
Downloading: http://repo.mcstats.org/content/repositories/public/com/sk89q/spigot/bukkit-classloader-check/1.8-R0.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.sk89q.spigot:bukkit-classloader-check:1.8-R0.1-SNAPSHOT/maven-metadata.xml from/to Plugin Metrics (http://repo.mcstats.org/content/repositories/public): Failed to transfer file: http://repo.mcstats.org/content/repositories/public/com/sk89q/spigot/bukkit-classloader-check/1.8-R0.1-SNAPSHOT/maven-metadata.xml. Return code is: 522 , ReasonPhrase:Origin Connection Time-out.
[WARNING] Failure to transfer com.sk89q.spigot:bukkit-classloader-check:1.8-R0.1-SNAPSHOT/maven-metadata.xml from http://repo.mcstats.org/content/repositories/public was cached in the local repository, resolution will not be reattempted until the update interval of Plugin Metrics has elapsed or updates are forced. Original error: Could not transfer metadata com.sk89q.spigot:bukkit-classloader-check:1.8-R0.1-SNAPSHOT/maven-metadata.xml from/to Plugin Metrics (http://repo.mcstats.org/content/repositories/public): Failed to transfer file: http://repo.mcstats.org/content/repositories/public/com/sk89q/spigot/bukkit-classloader-check/1.8-R0.1-SNAPSHOT/maven-metadata.xml. Return code is: 522 , ReasonPhrase:Origin Connection Time-out.
Downloading: http://repo.mcstats.org/content/repositories/public/org/bukkit/bukkit/1.8.6-R0.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.bukkit:bukkit:1.8.6-R0.1-SNAPSHOT/maven-metadata.xml from/to Plugin Metrics (http://repo.mcstats.org/content/repositories/public): Failed to transfer file: http://repo.mcstats.org/content/repositories/public/org/bukkit/bukkit/1.8.6-R0.1-SNAPSHOT/maven-metadata.xml. Return code is: 522 , ReasonPhrase:Origin Connection Time-out.
[WARNING] Failure to transfer org.bukkit:bukkit:1.8.6-R0.1-SNAPSHOT/maven-metadata.xml from http://repo.mcstats.org/content/repositories/public was cached in the local repository, resolution will not be reattempted until the update interval of Plugin Metrics has elapsed or updates are forced. Original error: Could not transfer metadata org.bukkit:bukkit:1.8.6-R0.1-SNAPSHOT/maven-metadata.xml from/to Plugin Metrics (http://repo.mcstats.org/content/repositories/public): Failed to transfer file: http://repo.mcstats.org/content/repositories/public/org/bukkit/bukkit/1.8.6-R0.1-SNAPSHOT/maven-metadata.xml. Return code is: 522 , ReasonPhrase:Origin Connection Time-out.
Downloading: http://repo.mcstats.org/content/repositories/public/com/sk89q/worldedit/6.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.sk89q:worldedit:6.0.0-SNAPSHOT/maven-metadata.xml from/to Plugin Metrics (http://repo.mcstats.org/content/repositories/public): Failed to transfer file: http://repo.mcstats.org/content/repositories/public/com/sk89q/worldedit/6.0.0-SNAPSHOT/maven-metadata.xml. Return code is: 522 , ReasonPhrase:Origin Connection Time-out.
[WARNING] Failure to transfer com.sk89q:worldedit:6.0.0-SNAPSHOT/maven-metadata.xml from http://repo.mcstats.org/content/repositories/public was cached in the local repository, resolution will not be reattempted until the update interval of Plugin Metrics has elapsed or updates are forced. Original error: Could not transfer metadata com.sk89q:worldedit:6.0.0-SNAPSHOT/maven-metadata.xml from/to Plugin Metrics (http://repo.mcstats.org/content/repositories/public): Failed to transfer file: http://repo.mcstats.org/content/repositories/public/com/sk89q/worldedit/6.0.0-SNAPSHOT/maven-metadata.xml. Return code is: 522 , ReasonPhrase:Origin Connection Time-out.
Downloading: http://repo.mcstats.org/content/repositories/public/org/bukkit/bukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.bukkit:bukkit:1.8-R0.1-SNAPSHOT/maven-metadata.xml from/to Plugin Metrics (http://repo.mcstats.org/content/repositories/public): Failed to transfer file: http://repo.mcstats.org/content/repositories/public/org/bukkit/bukkit/1.8-R0.1-SNAPSHOT/maven-metadata.xml. Return code is: 522 , ReasonPhrase:Origin Connection Time-out.
[INFO] 
[INFO] --- exec-maven-plugin:1.3.2:exec (default) @ uSkyBlock-Core ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] uSkyBlock-API ...................................... SUCCESS [  1.355 s]
[INFO] po-utils ........................................... SUCCESS [  0.677 s]
[INFO] bukkit-utils ....................................... SUCCESS [  0.753 s]
[INFO] Ultimate Skyblock .................................. SUCCESS [  0.038 s]
[INFO] uSkyBlock-Core ..................................... FAILURE [01:18 min]
[INFO] uSkyBlock-AWE211 ................................... SKIPPED
[INFO] uSkyBlock-AWE311 ................................... SKIPPED
[INFO] uSkyBlock-AWE321 ................................... SKIPPED
[INFO] uSkyBlock-Plugin ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:21 min
[INFO] Finished at: 2015-11-10T11:53:18-05:00
[INFO] Final Memory: 23M/92M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec (default) on project uSkyBlock-Core: Command execution failed. Process exited with an error: 128 (Exit value: 128) -> [Help 1]

**Comment by i9hdkill** [comment]
Mc Stats repo is down since some days, yes

**Comment by csorrows** [comment]
Yes, I had issues building it as well as I don't have anything cashed. I did manage to get it built from someone else though.

**Comment by rlf** [comment]
It's not the mcstats repo that is down (the mcstats jar is currently also hosted in the uSkyBlock repo), it is the WorldEdit/WorldGuard repos that are down.

**Comment by csorrows** [comment]
To be honest, when I saw that repos were down I gave up right away. I did not even look to see which ones.

**Comment by rlf** [comment]
Just a quick lesson into maven-builds (ignore if you guys already know this).
All the jars we depend on (artifacts in Maven lingo), is expressed using the maven 3-component vector: groupid,artifactid and version.

Along side these "locators", we have a list of repositories, that maven can use to resolve/locate these artifacts.

Our own repo is on purpose listed as the last one, so every single artifact is tried against all the other repos, before it tries our own.

This way, we can put jars originally hosted by other repos in our own, to provide a "safe" fallback artifact for building.

This is what we've currently done for mcstats metrics etc.

Unfortunately, this means that the log-files are poluted when one of the repos are down (the warnings you are experiencing), also, maven won't re-try locating artifacts (within a certain time), that it has once deemed belonging to a specific place.

You can force a "re-download" by supplying maven with the `-U` argument, and suppress it by either using `-nsu` (no snapshot updates) or `-o` (offline).

The latter option ONLY works, if your local repo (`$HOME/.m2`) contains all the dependencies for the build.

When we deem a specific repository is "too unstable", we either find a new and more reliable one (i.e. the spigotmc.org repo), or, if the license permits us, put the jars into our own.

Hope this clears up the "building issue".
Closing this for now - since there's not much we can do about it anyway.
