### ISSUE TITLE
Missing bypass permission for using spawneggs

### ISSUE THREAD

**Issue by minoneer** [rlf/uSkyBlock#563]
Trying to use spawn eggs on other players islands results in a message "You can only use spawn-eggs on your own island." This is true even for admins with all bypass permissions. While the protection for players is useful, it makes support for staff tricky without a bypass permission.

**Comment by dutchy1001** [comment]
Agreed this is a bug and need to be fixed, Hopefully next update.

**Comment by csorrows** [comment]
Good solid protection tho right? =)
