### ISSUE TITLE
Challenges bug on 1.7.10

### ISSUE THREAD

**Issue by TehGreekGamerJIM** [rlf/uSkyBlock#564]
Hello there I am setting up a Skyblock server for my Network server but cant seem to make challenges to work I have touched NOTHING from the challenges.yml 

When doing /is and clicking the Challenges icon (Diamond Ore) it will do nothing.

Versions of WG WE Skyblock Vault and bukkit (spigot-1.7.10-SNAPSHOT-b1657)
http://prntscr.com/9290v4

**Comment by dutchy1001** [comment]
You got an to "new" vault version For server using v1.7.9/10 you need the Vault v1.4.1.

**Comment by TehGreekGamerJIM** [comment]
Alright thanks I will add the stated version

**Comment by TehGreekGamerJIM** [comment]
Well the thing now is that using the stated WG version it breaks up the regions
