### ISSUE TITLE
End not working

### ISSUE THREAD

**Issue by xSpeeddemon1** [rlf/uSkyBlock#565]
server version: CraftBukkit git-Spigot-5f38d38.18bb24 (MC: 1.8.8)
uSkyblock version: 2.4.7
WorldEdit version: 6.1;no_git_id
WorldGuard version: 6.1
Vault: 1.5.6-b49
Multiverse-Core: not in use

Nobody can't enter the End/create portals, but in the normal world it works fine

No errors / messages in console

worldguard is set to allow endportals

**Comment by dutchy1001** [comment]
You need to create a new End world for the skyblock just as the Nether. Call your End world "skyworld_theend" and the portals should get you there. To get back from the End world you either need to defeat the dragon or use the command "/is home" (if the permissions are shared to the world).

**Comment by xSpeeddemon1** [comment]
Thanks for the quick answer

**Comment by dutchy1001** [comment]
Yw

**Comment by rlf** [comment]
The end is not currently handled by uSkyBlock - but as dutchy states, the Multiverse-NetherPortals support default linking.

Alternatively you can link it manually.

I thought the default end world name would be `skyworld_the_end`

**Comment by csorrows** [comment]
Maybe you missed: 
>Multiverse-Core: not in use
