### ISSUE TITLE
command rewards not working

### ISSUE THREAD

**Issue by woolwind** [rlf/uSkyBlock#566]
I'm perhaps not getting the syntax right, the example in the default config doesn't seem to parse.
I want to issue a fancy named and enchanted item, but first tried debugging the the simpler command you see. It loads with no error, but no diamonds appear on completion. There is no error in console, it just doesn't happen.

      novicebuilder:
        description: Reach island level 15
	type: islandLevel
        requiredItems: '15'
        repeatable: false
	displayItem: 98
        reward:
          items: 257:1 3:5
          text: 1 iron pickaxe, 5 dirt
          currency: 50
          xp: 50
          commands:
          - console: give {party} diamond 32

**Comment by rlf** [comment]
The party tag is restricted to only work on members in sky related worlds on completion.

Also, `:` in yml file values are tricky.
Try escaping the value with ''

**Comment by woolwind** [comment]
ah, I'd tried '' but didn't quite get why they where there. I tried so many different ways
So, tadah, this worked:

          commands:
          - 'console: give {player} {display:{Name:"Magic Dirt"},ench:[{id:19,lvl:1}]}'
