### ISSUE TITLE
Problem with nether activate

### ISSUE THREAD

**Issue by MrFiliper** [rlf/uSkyBlock#567]
I have problém with nether. Nether was generated correctly, but nether island level doesnt work. If player have island with 50 level, nether was created too. But I set activation to level 100.

config.yml

nether:
  enabled: true

  # The distance to search for valid terra-form location.
  terraform-distance: 7
  activate-at:
    level: 100

**Comment by csorrows** [comment]
I talked about this awhile back with @dutchy1001 and we were unsure what the setting was supposed to do. I got busy with other aspects of my server and forgot about it, thanks for reminding me about the question. @rlf , what exactly is this setting for? I was thinking the same as @MrFiliper

**Comment by rlf** [comment]
The only thing the `activate-at` does, is to include the nether island in the level calculation, at that point.

The nether island is currently generated on island-generation time, i.e. when doing `/is create` or `/is restart`

**Comment by csorrows** [comment]
Ah, so it starts to add to the island level once the nether island has reached that level?

**Comment by dutchy1001** [comment]
no it adds level point when you reached lvl100 in the overworld.

**Comment by csorrows** [comment]
In other words, "Active nether island boost at overworld island level 100"
