### ISSUE TITLE
Make GUI fully configurable

### ISSUE THREAD

**Issue by Dienns** [rlf/uSkyBlock#568]
Hi,

I was told to make a GitHub issue about my suggestion.
I'd like to see more configuration, regarding design. The option to change the menu's title, block location (for example a 5 high menu with items centered), change commands when clicking on the blocks, change the messages & lores from the items in the menu etc etc. You get it.

I'd like to see this in a next update :dancer:

**Comment by rlf** [comment]
You need to be more specific than that - and also, I'd like to know why and what for you need it.

And formulations like "etc etc." is sort of hard to implement.

Be more specific please.

**Comment by csorrows** [comment]
I agree with being able to change the title of the uSkyblock menu to make it fit better with some servers. I don't know why I would want to move items around as we can already add stuff to the menu.

**Comment by rlf** [comment]
Also stating 

>  I'd like to see this in a next update :dancer: 

(I know, you probably tried :smile: ) is not really the best way to get things done.
Since you have absolutely no say in the "planning" of this project, it can sort of only be taken as being sort of rude... and mind you, both Dutchy and I are two grumpy old men :laughing:

**Comment by Dienns** [comment]
With "etc etc" i meant all stuff regarding design. I'd like to be able to customize messages, titles of menu's, position of menu items, commands executed on menu-item click, stuff like that.

**Comment by dutchy1001** [comment]
The messages text and other "named" menu's can all be changed already through the .po language files. This is why we have chosen this system. 
Yes I agree it is a bit more complicated then just an .yml language file but with this you CAN change any menu/text aspect of the plugin.
I think the documentation might not be totally up to date yet, but this system works (there is a bug atm but we are looking into this).

**Comment by rlf** [comment]
So, basically you want all the GUIs in uSkyBlock to be fully configurable?
While supporting translations.
I think the main menu could be configurable, and the challenges menu is already pretty much 100% configurable.
The permission menus and biome menus is a bit more tricky.

We have discussed this earlier, and we even considered binning the whole menu, and just using Chest Command GUI instead.
Unfortunately, currently, the UI is generated depending on a lot of state, so making it 100% configurable simply wasn't feasible. But worth considering again.

**Comment by i9hdkill** [comment]
chestcommands as an optional dependency would be a good alternative.
You could provide a template_gui.yml that we just have to put in /chestcommands/menu/
It's a waaay more flexible and easier to understand then those .po files
When chc is not installed, usky could fall back to it's own menu (how it's right now)

**Comment by Dienns** [comment]
I've thought about ChestCommands too, or CustomGUI or whatever. Only (possible) problem is, is there a list of commands I can get to bind to ChestCommands items to?

Something like /skyblock create {username} {type}

**Comment by csorrows** [comment]
chestcommands IS an optional dependency. It is used to add more links in the menu.

**Comment by Dienns** [comment]
Yes and how does one use it with ChestCommands? Pretty sure I asked kindly for a list of commands or somethin'.

**Comment by csorrows** [comment]
I'm not sure as I have not used that feature yet.

@dutchy1001 @rlf

**Comment by dutchy1001** [comment]
With Chestcommand GUI you can overwrite the "icons" in the main menu using the (by default) removed system (see [here](http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/the-config-changing/) and add the "extra-menu" section back to the config), you can add custom commands as explained on the [ChestCommand](http://dev.bukkit.org/bukkit-plugins/chest-commands/) GUI page. 
The only limitation here is that when using a "back" button/command it will revert back to the default USB menu.
The first icon on the first row is location "0", so the last icon on the first row is "8", the second row starts then with "9" etc. etc.
You can only change the main usb GUI, not the sub menu's.
For example:
You change the "party member" icon to open the island member settings, when going back to the main usb menu it will then be the default usb icons. Closing the GUI and reopening it again will give the ChestCommandGUI settings again.

Hope this makes the use of ChestCommandGUI a bit more clear.

**Comment by dutchy1001** [comment]
Then after an explanation how to use ChestCommandGUi with uSkybock it gets quiet and no replies.

Guess it's sorted then.
YW

**Comment by csorrows** [comment]
Thanks @dutchy1001!! (someone had to speak up)
