### ISSUE TITLE
API support for getCurrentIsland

### ISSUE THREAD

**Issue by csorrows** [rlf/uSkyBlock#569]
@rlf I'm talking with an add-on dev from Skript about creating hooks to Skript from uSkyblock. I'm not sure what info is available from the API. Can you list what they are?

**Comment by csorrows** [comment]
I'm sorry if this request was not acceptable. The dev said he has found how to get the info I wanted from uSkyblock to hook.

**Comment by rlf** [comment]
I don't think the "who's island a player is on" is currently available in the API, but we can add it.

The rest should be available.
And I do NOT recommend Skript to take it from our internal model (as it is bound to break in the future, eventually).

Hi-jacking this issue for the addition of "getCurrentIsland" to the API.

**Comment by csorrows** [comment]
Great thanks @rlf

**Comment by alaaemad15** [comment]
@rlf I used getMembers() to do it, so I don't need it right now

**Comment by alaaemad15** [comment]
I did not use the API for some of the features for example to get the island they are on i used worldguardhandler

**Comment by csorrows** [comment]
@rlf, could you also put island leader in the api?

**Comment by rlf** [comment]
Just to be clear, what information reg. island is needed?
And is it the island the player is currently "part of", or the island he is physically currently visiting?

**Comment by alaaemad15** [comment]
who's island a player is on would need getIslandAt(Location) and ownerOfIsland(String) for example

**Comment by csorrows** [comment]
So the idea is I'm adding a sidebar with info on it while in the skyblock world. I would like to add island owner, location, and level to this menu. With these hooks in Skript, this would make all of this possible.

**Comment by rlf** [comment]
Reopened. v2.5.5 should enable the lookup function for `IslandRank` of a location.
This should enable you to get the info you need.
Note: The `IslandRank` includes the `IslandLevel` that has methods for getting both leader and members.

**Comment by csorrows** [comment]
I let @alaaemad15 know about the updated resource. We will let you now if there are any issues. Thanks again man!

**Comment by dutchy1001** [comment]
This is added to the API as far I understand. If not reopen it.
