### ISSUE TITLE
Spawn

### ISSUE THREAD

**Issue by MrFiliper** [rlf/uSkyBlock#571]
How to set respawn world in skyworld? I set respawn world in multiverese, but does not work.

**Comment by dutchy1001** [comment]
'''extras:

    # [true/false] If true, return players that don't have an island (this includes players removed from a party while offline), to the server spawn when they login.
    # NOTE: Requires EssentialsSpawn or another plugin with the "/spawn" command
    sendToSpawn: false
'''
