### ISSUE TITLE
nether island under lava level

### ISSUE THREAD

**Issue by SgtLegoTown** [rlf/uSkyBlock#577]
if the island height is lowered to like 65 the nether island will perfectly spawn only under the lava level 
players have hot feed then

**Comment by rlf** [comment]
Yes, currently, we spawn the island at the "islandheight"/2 in nether.
Do you have any suggestions as to adjustments?
Like height/2 but min 32?

**Comment by SgtLegoTown** [comment]
32 lower then the island you mean ?

**Comment by SgtLegoTown** [comment]
like island is 120 and nether will be 88 nether height .. I can live with that :) still a detail it works as a charm

**Comment by dutchy1001** [comment]
Can it not be set solid in the nether, no matter what height the overworld is set, nether stays at YY??

**Comment by rlf** [comment]
Overworld is 0-255, nether is 0-127. That is why we say the nether-island is at "height"/2.

But... since we have the lava-ocean at 32, the "effective" height should be 32-120 ish.

So, we could make the logic something along the lines of:
````
  netherY = ((island-height)*255/(120-32)) + 32 
```

**Comment by SgtLegoTown** [comment]
what dutchy said wasn't that bad nethery = (FixedValue)

**Comment by dutchy1001** [comment]
aslong we dont have to swim in the lava it's fine fixed value or a +32 maybe +37 to leave a small gap is fine by me too

**Comment by SgtLegoTown** [comment]
call it we have a HotSpa.jar for uskyblock ?

**Comment by rlf** [comment]
Ye, sure, that's a simple solution, island height, and nether.height. Done, bought

**Comment by dutchy1001** [comment]
I presume this is added?
If added this can be closed.

**Comment by rlf** [comment]
Not added yet.

**Comment by csorrows** [comment]
Apparently it was bought on credit. @rlf is still making payments I guess... (in reference to rlf's prior comment)
