### ISSUE TITLE
Possible to have 2 islands in 2 different worlds?

### ISSUE THREAD

**Issue by matthijs110** [rlf/uSkyBlock#578]
Hello,

Is it possible to have an island on in the normal world? And have to have an NETHER island too, in the nether world?

So when a player uses the nether portal, they will go to their own island in the nether.

**Comment by rlf** [comment]
Yes

**Comment by matthijs110** [comment]
How can I do this?

**Comment by dutchy1001** [comment]
Try using versions above V2.5 and read any documentation, that might point you in the right direction.
On the [bukkit site](http://dev.bukkit.org/bukkit-plugins/uskyblock/) you can find most information.

**Comment by matthijs110** [comment]
I can't find the amount of islands per player. Nor the setting for the 2nd skyworld. Could you point me to the right direction a little more?

**Comment by dutchy1001** [comment]
You have only 1 island per world, 1 in the overworld and 1 in the nether. 
There is not a setting for a 2nd skyworld, as they are generated by the plugin. If settings are correct it creates a "skyworld" (this will always be created) and a "skyworld_nether" (this will be created when settings are correct). If you already have a skyworld_nether you might need to delete or rename this to let the new nether generate.
In the config is an option that you can turn the nether on or off (v2.5 - v2.5.3 default OFF, v2.5.4 and higher default ON).

**Comment by matthijs110** [comment]
And where do I apply the schematic for the Nether island?

**Comment by matthijs110** [comment]
I don't see the option for an second schematic. Where can I find that? Or how do I apply the 2nd schematic? (an nether island)

**Comment by dutchy1001** [comment]
The nether schematic is in the schematic folder of the uSkyblock folder. 
If you want a custom nether island name it the same as the original but make sure you have a backup of your custom island too.

**Comment by matthijs110** [comment]
Clear. Last question (I hope), is it possible to have custom items for the chest on the nether island?

**Comment by dutchy1001** [comment]
No, custom items cant be given in the default chest. 
Maybe through a "kit" in the first challenge is an option...

**Comment by matthijs110** [comment]
I have set it all up now, but I get this message:

![](http://puu.sh/lFBOH/b21b2b61dd.png)

**Comment by dutchy1001** [comment]
add MV-NetherPortals

**Comment by matthijs110** [comment]
I have that plugin installed..

**Comment by dutchy1001** [comment]
try this set of MV Plugins:
http://ci.onarandombox.com/job/Multiverse-Core/710/
http://ci.onarandombox.com/job/Multiverse-Portals/732/
http://ci.onarandombox.com/job/Multiverse-NetherPortals/701/
http://ci.onarandombox.com/job/Multiverse-Inventories/398/

This is whatI use myself

**Comment by matthijs110** [comment]
Thank you very much. Updating Multiverse-NetherPortals did the job. Works like a charm now :)
