### ISSUE TITLE
Island biome not changed

### ISSUE THREAD

**Issue by MrFiliper** [rlf/uSkyBlock#579]
I have 320x320 island protected area, but if player change biome, biome changes bad. On the island is all changed biome, but in the perhaps 50x50 area biome not changed. Please fix this.

**Comment by rlf** [comment]
Is the 50x50 area the spawn-area?

**Comment by MrFiliper** [comment]
No, it was random area.

**Comment by Latouth** [comment]
Have you relogged?
Minecraft stores the biome when you join.
If you relog and it's gone, ignore it.
When you log off, the cache of the world you were on disappears.

**Comment by MrFiliper** [comment]
Yes, i was relog game.
