### ISSUE TITLE
Unable to load USkyblock

### ISSUE THREAD

**Issue by R3IDO101** [rlf/uSkyBlock#580]
Hi,

I have all the plugins related to Uskyblock but unable to load the plugin i am on 1.8.8 can you assist me further? please

Thanks

R3IDO101

**Comment by dutchy1001** [comment]
What are all the related plugins and their version numbers? plz list them. (you can find that in the server log)

**Comment by R3IDO101** [comment]
World edit 6.1
World Guard 6.1
Uskyblock v2.5.3

is their anything else required to start Uskyblock?

**Comment by dutchy1001** [comment]
If you read the install notes on all pages available you would see that Vault is needed. 

I recommend also the use of Multiverse-core and Multiverse-NetherPortals (versions above 2.5)

**Comment by R3IDO101** [comment]
I have Vault installed so i don't know what to do next

**Comment by dutchy1001** [comment]
Can you post the (full) startup log?

**Comment by R3IDO101** [comment]
sorry i dont have the server anymore thanks anyways

**Comment by dutchy1001** [comment]
thx for letting us know.

**Comment by csorrows** [comment]
???
