### ISSUE TITLE
Nether problem

### ISSUE THREAD

**Issue by manercraft** [rlf/uSkyBlock#581]
Hello
When i go in nether, no portail spawn and no IslandNether spawn
But i have the new skyworld_nether

![us](https://cloud.githubusercontent.com/assets/1338257/11601679/0829699a-9ad5-11e5-93ec-54f5153ce393.png)

**Comment by dutchy1001** [comment]
update to v2.5.5 [here](https://github.com/rlf/uSkyBlock/releases), and see if the problem still happens.

**Comment by manercraft** [comment]
Same problem:
![us](https://cloud.githubusercontent.com/assets/1338257/11602908/4f632fa4-9ade-11e5-82d3-d79eb34dcfdb.png)

![2015-12-04_23 24 55](https://cloud.githubusercontent.com/assets/1338257/11602914/57c90d94-9ade-11e5-8af1-adf82182c50f.png)

**Comment by dutchy1001** [comment]
have you deleted the schematic from the uSkyblock schematic folder?

**Comment by manercraft** [comment]
No

**Comment by rlf** [comment]
The island isn't spawned when you go to nether, but when you create the island (i.e. `/is create` or `/is restart`).

We will probably change that in a future release - but for now, that is when it is created.

**Comment by dutchy1001** [comment]
would it be an idea to have the same bedrock block at location 0 0 as in the overworld? That way the can also create a nether spawn island at the right location if the want.

**Comment by dutchy1001** [comment]
no further input, closing this for now.
