### ISSUE TITLE
Add MySQL support?

### ISSUE THREAD

**Issue by matthijs110** [rlf/uSkyBlock#582]
Is it possible to add MySQL support to uSkyBlock?

It is easier to manage players and skyblocks in a MySQL database than storing it in files. It takes less MB's/GB's.

**Comment by dutchy1001** [comment]
We have talked about this in our dev chat's and were still not 100% sure as it require a lot of code changing.
One thin is for sure, it wont be added in the next update.

**Comment by matthijs110** [comment]
Well, nice to here you have talked about it though. Hope to see this feature in the future :+1:

**Comment by rlf** [comment]
Duplicate of #406
