### ISSUE TITLE
Party Permissions Problem with case-sensitive names

### ISSUE THREAD

**Issue by Reeferx7** [rlf/uSkyBlock#585]
Hello, i have a problem with party permissions, dont work.
![d0f21b81249b64bd16808c1e08f24e67](https://cloud.githubusercontent.com/assets/8740881/11614867/ff862b6e-9c57-11e5-9c87-36808084cace.gif)
I have many report from my players and i make some tests and i cant change permissions of party member. Also i see in permission menu the names is not case sensitive.
In this case in screenshot the real name is "ISTest" no "istest".

![89689dc4cb512964b3166826eb3c12b5f70c728c](https://cloud.githubusercontent.com/assets/8740881/11614874/7d9a2906-9c58-11e5-82da-a48360118df7.png)

**Comment by dutchy1001** [comment]
The player that is in the party group should have the permissions that are needed for doing the toggles in the "party GUI" Meaning, id the player , in this case ISTest, should have the permision(s) usb.biome.* or usb.biome.[biomename] to change the biomes. Samr counts for the warp toggle, ISTest needs the permisiion usb.island.warp and usb.extra.addwarp to be able to use the toggle.

let me know if this will solve the issue.

**Comment by Reeferx7** [comment]
I know that here my skyblock permissions:

    permissions:
    - usb.island.warp
    - usb.island.create
    - usb.island.sethome
    - usb.island.info
    - usb.island.topten
    - usb.lock
    - usb.party.create
    - usb.party.kick
    - usb.party.makeleader
    - usb.party.join
    - usb.mod.party
    - usb.island.ban
    - usb.island.challenges
    - usb.island.level
    - usb.biome.*

Already i try this with 2 op players too (party members)

**Comment by Reeferx7** [comment]
permissions:
    - usb.island.warp
    - usb.island.create
    - usb.island.sethome
    - usb.island.info
    - usb.island.topten
    - usb.lock
    - usb.party.create
    - usb.party.kick
    - usb.party.makeleader
    - usb.party.join
    - usb.mod.party
    - usb.island.ban
    - usb.island.challenges
    - usb.island.level
    - usb.biome.*

Here my skyblock permissions. Already i try with 2 players op (party members) and dont work.

**Comment by rlf** [comment]
Sounds likely

**Comment by rlf** [comment]
Please re-test this on v2.7.1 - since we changed to UUIDs for most things, this might not be an issue anymore.

**Comment by dutchy1001** [comment]
This should be fixed but cant be tested due to an other issue #940 
This will be closed
