### ISSUE TITLE
/is problem

### ISSUE THREAD

**Issue by SendYaPackin** [rlf/uSkyBlock#586]
Ok so in my server when attempting to do /is with the plugin and everything correctly installed, it doesn't pop up with a GUI instead it just said '/island [restart/sethome/info/level/lock/unlock/top/party' and that's all it does whenever I try and do the /is command or anything related to the commands with the plugin

**Comment by dutchy1001** [comment]
When that message comes up it means it is missing a depended plugin. Can you tell me what depended plugins you have installed and which versions they are.

**Comment by SendYaPackin** [comment]
Ok so I have WorldEdit(unknown), Vault(v1.5.6), WorldGuard(v6.1), Multiverse-Core(v2.4), Multiverse-Netherportals(v2.5).

**Comment by dutchy1001** [comment]
Multivers-Core is outdated and needs updating to 2.5.
With the other depended plugins it should work normaly. I would suggest to use the dev versions from [here](http://ci.onarandombox.com/) for any Multivers plugin.

**Comment by SendYaPackin** [comment]
Ok thank you :)
