### ISSUE TITLE
Adding a trust GUI similar as the party GUI or combined

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#587]
A request from Flarup (spigot forum) to add a similar system for permissions as the party GUI has.
Permission that are in mind for this are:
- build
- break
- open chest
- drop items
- pvp??

**Comment by rlf** [comment]
Not sure I get what permissions you are talking about?
Do you want USB to make a general permission GUI, using Vault?
Or are we only talking about expanding the party-permissions?
Or introducing an "island-permissions" menu?

**Comment by dutchy1001** [comment]
You can see this as expanding the party gui (/is party) with an addition for the "trusted players" with the toggles for the above  perms mentioned.
