### ISSUE TITLE
Schematic not working

### ISSUE THREAD

**Issue by xSpeeddemon1** [rlf/uSkyBlock#590]
So i tried to use a schematic i first tried it with my normal config then with a default one with nothing changed except the custom schematic name. Everytime i wannted to make a new Island/restart it teleported me away and said it's generating. but nothing happend if i reconneted somehow and did /is home i was on my new Island and it was the Schematic i selected. 

Error: http://pastebin.com/VmmPm5DJ
Version: http://pastebin.com/hViT9KTG
Changed default config: http://pastebin.com/QDgGSLs1
Schematic: http://www.mediafire.com/download/i0v5vx2tb5vod0x/brawlisland.schematic

If you need anything more please tell me

**Comment by dutchy1001** [comment]
Have you read this page [here](https://github.com/rlf/uSkyBlock/wiki/Custom-Island)?
Most issue's will be gone if you follow this guide.

**Comment by dutchy1001** [comment]
After testing your island I had the same issue you have.
The chest you need to place is an empty chest, not filled with the default items.
I redone the island with an empty chest and no errors are showing up for me, I also was tp'ed to the island after creation/restart.
The island I used is [here](https://mega.nz/#!6tlmjA4K!h9GPSyIUT2aihUr2YmHoUCRgSXeqVZ04xQLYD8AZ-rE).
The only thing I didnt get is spawning in the cave, but I did save the schematic while standing in the cave.

**Comment by xSpeeddemon1** [comment]
It works again thank you so much :*

**Comment by dutchy1001** [comment]
no prob. 

Closing this issue
