### ISSUE TITLE
Party members can't build or break on nether island

### ISSUE THREAD

**Issue by matthijs110** [rlf/uSkyBlock#591]
Hello,

Party members who go to the nether can't break or build on their nether island. Only the party leader can. (The owners are not updated in the WorldGuard region).

**Comment by rlf** [comment]
Please include info from `/usb version`

**Comment by matthijs110** [comment]
V2.5.3

**Comment by dutchy1001** [comment]
that is not the full output from /usb version. Either make a screenshot (f2) or copy it from the console.

I do confirm that aslo in v2.5.5 party members cant break blocks on the nether island.

**Comment by matthijs110** [comment]
I am sorry. I had nothing more than a mobile phone. Anyway. Here is my ```/usb version``` output.
![schermafbeelding 2015-12-14 om 16 08 59](https://cloud.githubusercontent.com/assets/4161158/11784565/4749de52-a27d-11e5-8e2d-5c59cb7c5d99.png)

**Comment by dutchy1001** [comment]
no worries, as I had the same issue and rlf knows my setup

**Comment by csorrows** [comment]
*kill confirmed*

**Comment by rlf** [comment]
Made some changes in v2.5.7 - please re-test this issue, and return to us.

**Comment by dutchy1001** [comment]
This is tested and fixed in v2.5.7
