### ISSUE TITLE
Admin/mod player challenge check

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#594]
Request to let admins/moderators/maintainers see the challenge GUI from any player with a command that brings the GUI up. 
Command in mind is "/usb challenge check [playername]" and permission node "usb.island.challenge.check".

On this screen a possability to add or remove challenges instead of using commands in chat.
This should also override the visual challenges so any challenge is visual (the enchant glow will show if the challenge is completed or not).

**Comment by rlf** [comment]
Just to be clear, when you say "add or remove" challenges, you mean "complete or clear"?
We could say, that left-clicking would mark them as complete, and right-clicking would clear them.

That way, it would be fairly simple to implement (I think).

**Comment by dutchy1001** [comment]
that sounds great with the left/right click.
