### ISSUE TITLE
Huge lag "WorldEditRegen" when clear an island

### ISSUE THREAD

**Issue by NivixX** [rlf/uSkyBlock#599]
Hello there are an huge lag when a player restart an island :/

1. create an island
2. do /is restart ( or join a party )

--> The server will lag for long because of an worldedit regen
there is the timings : http://timings.aikar.co/?url=14091134

I use uSkyblock v2.5.3 for Bukkit 1.7.9

Thank you for you help !

**Comment by rlf** [comment]
First of all, never make an issue, without including the output of `/usb version`.

Secondly, when-ever a plugin needs to change large chunks of the map, it's bound to introduce some performance intensive operations.

We use WorldEdit for this, and yes, that will have a performance impact.
If you want to avoid this, you can install AsyncWorldEdit - where you trade time for performance (it takes a longer time to restart an island, but the server is not being loaded as hard).

The above timings is not bad, not bad at all. We only use 120% of a tick, meanining we only "lag" the server for 60ms at a time.

**Comment by rlf** [comment]
Ready for test in v2.6.0 (use with caution).
