### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by SendYaPackin** [rlf/uSkyBlock#600]
I was going to see if there's a possibility that uSkyblock can cause server lag? Because I have been having lots of it.

**Comment by csorrows** [comment]
Low TPS or block lag or client lag? What are the symptoms? There are many types of lag and many different causes.

**Comment by csorrows** [comment]
To answer your uSkyBlock question, generally no, it does not cause lag on it's own.

**Comment by rlf** [comment]
It depends on a lot of things.

I would usually recommend (if you are using Spigot), to do `/timings on`
Then wait for like 10-15 minutes, and do `/timings paste`.

The resulting report will give you some hints.

**Comment by SendYaPackin** [comment]
Well I'm having some lag here and there with like 2+ players, just at random times, sometimes before world saves and sometimes just at random times. 
3.59%	   3.74%	 13.52 s	     1.87 ms	 1.0	       7.2k	    Full Server Tick
0.14%	 519.46%	  0.52 s	   259.73 ms	 0.0	       0.0k	    Task: RecalculateTopTen(Single)
0.23%	 171.85%	  0.86 s	    85.93 ms	 0.0	       0.0k	    Command: list
0.00%	  11.36%	  0.01 s	     5.68 ms	 0.0	       0.0k	    Task: uSkyBlock$7(Single)
0.00%	   9.04%	  0.00 s	     4.52 ms	 0.0	       0.0k	    World Save
0.00%	   5.25%	  0.00 s	     2.62 ms	 0.0	       0.0k	    Command: home
0.00%	   7.62%	  0.00 s	     3.81 ms	 0.0	       0.0k	    Command: timings
0.00%	   5.48%	  0.01 s	     2.74 ms	 0.0	       0.0k	    playerCommand
0.00%	  11.36%	  0.01 s	     5.68 ms	 0.0	       0.0k	    Task: uSkyBlock$7(Single)
Are any of these problems? Some of the pct Ticks showed up as Red and Yellow.
Server Load: 3.74%

**Comment by SendYaPackin** [comment]
Also my CPU hits 100% like seconds before the lag happens. And then it just stays that way until the lag is done.

**Comment by dutchy1001** [comment]
the timings you show here dies not really tell much, the original link would have been a lot more clear and will give a full picture. 
So plz post the link instead of a fragment of this timings.

**Comment by SendYaPackin** [comment]
http://timings.aikar.co/?url=14108935

**Comment by rlf** [comment]
The supplied sample is only 376 seconds long, and doesn't show any lagg (tps is high, load is low).

It does, however, indicate, that the Task: RecalculateTopTen(Single) is using more than it should.

Do you have any configuration of the autoRefreshScore?
Or do you use any scoreboards-plugins, that calls `/is top` periodically?

**Comment by SendYaPackin** [comment]
I did put in a new scoreboard (Featherboard) just yesterday but this happened before that.

**Comment by dutchy1001** [comment]
Not only is this probably a misconfiguration, also the use of wrong files is a big issue.
Copied from timings report:
* Spigot Version: d97e08b-880a532 (MC: 1.8.8)
* uSkyBlock v2.5.3-bukkit-1.7.9

**Comment by SendYaPackin** [comment]
So this is what is causing the lag? If so, what do I do?

**Comment by csorrows** [comment]
You are using the 1.7.9 version of uSkyBlock on a 1.8.8 server. Read what @dutchy1001 said above.

**Comment by SendYaPackin** [comment]
I couldn't find a 1.8.8 version of uSkyblock

**Comment by csorrows** [comment]
This should be for 1.8.8: https://github.com/rlf/uSkyBlock/releases/tag/v2.5.3

**Comment by SendYaPackin** [comment]
Well it came up as uSkyBlock(4).jar upon download so it might be

**Comment by csorrows** [comment]
Ok, I found what you did. You clicked the "1.7.9" release at the bottom of this page: https://www.spigotmc.org/resources/uskyblock.2280/update?update=52612
Instead, click the "download now" at the top right.

**Comment by dutchy1001** [comment]
All versions are called "uSkyBlock.jar" no matter what version 1.7.9 or 1.8.x. 
The files are available on 3 sites Github, Bukkit and Spigot so "I couldn't find it" is not our fault.
Reading your **uSkyBlock(4).jar** meaning there are 4 more of the same file, either in your download folder or in the plugin folder. If their in the plugin folder this will cause problems too if more then 1 uSkyBlock.jar is present.

**Comment by SendYaPackin** [comment]
Alright well I did exactly what you told me to do. I deleted the other files and downloaded a brand new file of uSkyblock but the lag still persists. Is it because of my memory? It's at 58% now currently.

**Comment by dutchy1001** [comment]
make a timings as before, let it run for at least 10/15 minutes and post that again.

**Comment by SendYaPackin** [comment]
http://timings.aikar.co/?url=14198636

**Comment by SendYaPackin** [comment]
So I got a comment back from my server host saying that it was your plugin because it used a lot of server resource and could of been my source of the server lag. So what do I do? Because my server is a Skyblock server and this is by far the best Skyblock plugin I've seen so far.

**Comment by dutchy1001** [comment]
From the timings report i can see that "Task: RecalculateTopTen(Single)" is indeed high, but what causes this to be so high??
Do you have a scoreboard plugin that requests every time the topten list? 
What is in the config set as refresh rate for the topten?

All those factors can cause this.
if you can post the config through pastebin (or simular) so we can check the settings. A fresh output of "/usb version" and maybe the startup log. All that info can help us find the issue.

**Comment by SendYaPackin** [comment]
No I do not have a scoreboard plugin installed.
Here's everything you requested in pastebin:
http://pastebin.com/DsY72UBJ

**Comment by rlf** [comment]
Most likely related to #604

**Comment by SendYaPackin** [comment]
So should I set the topTenTimeout lower in minutes? Or change something else to prevent it?

**Comment by dutchy1001** [comment]
What is it set in the config to autoRefreshScore?

**Comment by SendYaPackin** [comment]
5

**Comment by dutchy1001** [comment]
not much further input, if still occurs then let us know
