### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#601]
Version:
```
hello mom
```

Something is rotten

**Comment by csorrows** [comment]
I agree, it smells very bad in:
>here

**Comment by dutchy1001** [comment]
OK OK I will get a shower

**Comment by csorrows** [comment]
Thanks @dutchy1001 =O

**Comment by rlf** [comment]
Testing out a message template - so we wouldn't have to ALLWAYS say "please include the output from `/usb version`" - alas, it wasn't good enough for my taste

**Comment by csorrows** [comment]
OMG, that would be awesome if you got that working.
