### ISSUE TITLE
TopTen returns nicknames

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#602]
The TopTen returns players' nicknames instead of their actual usernames. "advanced.useDisplayNames" in the config doesn't seem to affect it; I have it set to "false". I suggest either making the TopTen utilize the "useDisplayNames" config option or have a separate config option to toggle between using displaynames or usernames.

In my particular case, I'm trying to use the TopTen players' names in the creation/updating of NPCs that act as a visible scoreboard in my server's spawn.

Version info:
Name: uSkyBlock
Version: 2.5.5
Description: Ultimate SkyBlock v2.5.5-041eb4-388
Language: en (en)
Server: CraftBukkit git-PaperSpigot-d709888-4ac2347 (MC: 1.8.8)
Name: Vault (ENABLED)
Version: 1.5.6-b49
Name: WorldEdit (ENABLED)
Version: 6.1.1-SNAPSHOT;3394-9a65bdb7
Name: WorldGuard (ENABLED)
Version: 6.1.1-SNAPSHOT.1629-0fcd42f
Name: AsyncWorldEdit (ENABLED)
Version: 3.2.2

**Comment by dutchy1001** [comment]
I think the issue is known already by rlf. 
Due to busy times of the year progress is slow. 
We hope to have some work done over the holidays.

Merry Christmas to you and your staff

**Comment by rlf** [comment]
useDisplayNames should take effect on the topten.
But only when it's "regenerated".
I will try to investigate this further - when I find the time.

**Comment by BlackBeltPanda** [comment]
#723
