### ISSUE TITLE
Use of challenge name

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#603]
When broadcasting the challenge complete message it will use the challenge file name, see [here](http://prntscr.com/9hreid), instead of the "custom" name given by the "name tag" in the challenges.yml (when hovering the mouse over the "blocked challenges" when using the command "/c" it also uses the file name(rank names are fine)).
Can this be changed so it broadcast the "custom name"?

**Comment by rlf** [comment]
Should be doable.

Can you list all the places where it's currently "the wrong name"? :smiling_imp:

**Comment by dutchy1001** [comment]
See example:
![2015-12-29_10 24 19](https://cloud.githubusercontent.com/assets/5569980/12033080/1cf8b2a4-ae17-11e5-80d3-a3cff6c0ba21.png)


![2015-12-29_10 24 30](https://cloud.githubusercontent.com/assets/5569980/12033066/f54ad76e-ae16-11e5-99ba-001a39660435.png)
Tried to find the location for the challenges GUI but got a bit confused were they are.

This will then also need to be changed in the messages
* [here](https://github.com/rlf/uSkyBlock/blob/a631155eebf29123ac12313d94f93908314e33a4/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/admin/AdminChallengeCommand.java#L33)
* [here](https://github.com/rlf/uSkyBlock/blob/a631155eebf29123ac12313d94f93908314e33a4/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/admin/AdminChallengeCommand.java#L47)
* [here](https://github.com/rlf/uSkyBlock/blob/15353e2aac345ea999b21d07bf40150772ac4479/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/challenge/ChallengeLogic.java#L129)
* [here](https://github.com/rlf/uSkyBlock/blob/15353e2aac345ea999b21d07bf40150772ac4479/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/challenge/ChallengeLogic.java#L326)
* [here](https://github.com/rlf/uSkyBlock/blob/15353e2aac345ea999b21d07bf40150772ac4479/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/challenge/ChallengeLogic.java#L344)

These lines  indicates that filling in the name will complete the challenge, those need to be able to use the above "tag name" to be completed too instead of the file name.
* [here](https://github.com/rlf/uSkyBlock/blob/a631155eebf29123ac12313d94f93908314e33a4/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/challenge/ChallengesCommand.java#L60)
* [here](https://github.com/rlf/uSkyBlock/blob/a631155eebf29123ac12313d94f93908314e33a4/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/challenge/ChallengesCommand.java#L61)

I tried to be exact with the entries in the code, but I probably will have missed a few.
