### ISSUE TITLE
Error could not pass event InventoryClickEvent when you turn on the translation

### ISSUE THREAD

**Issue by DeltaVetal26** [rlf/uSkyBlock#607]
Hi fellow servers!) The problem is this: when you change the config to uSkyBlock translation from EN to RU (Yes, I'm from Russia and here your plugin is popular)) and after restarting the server, changing the translation to my language, but now it is impossible to take anything from the chests and to make other things with creativity. In the console when executing each of my actions began to receive error could not pass event InventoryClickEvent , here is the full error on pastebin http://pastebin.com/rLCDiBd1 .If in the config to revert the translation back to English, the error disappears and everything works normally. But what I want is a running translation in my language. I don't know:( I would be very grateful for advice or help in solving this problem! P. S. errors in the text do not pay attention) server Version 1.7.10, the core KCauldron-1.7.10-1448.133-server , version WG - 6.0, WorldEdit - 6.0 , vault - 1.4.1

**Comment by rlf** [comment]
This is a known issue in one of the older releases.
Please post the output from `/usb version` as well, so I can see if it's the same error as we had for the French translation.

**Comment by rlf** [comment]
@dutchy1001 this might be a severe bug in our 1.7.9 release - the `/usb config` doesn't work (we know that), but apparently it also blocks all container interactions.

Could you test it out, and report any findings back?

**Comment by dutchy1001** [comment]
I have tried to reproduce some of this bit all is working for me, the ```/usb config``` included. Container blocks like the furnace, brewing stand and dropper all do what it suppose to do.
If I could have a copy of the Russian translation file I can test it with that enabled to see what happens. I tried the NL language (default in the plugin) but still it seems to work.

 I havent got a KCaulron setup so this is tested with spigot 1.7.9, see below the output of ```/usb version```

![2016-01-05_16 20 51](https://cloud.githubusercontent.com/assets/5569980/12120414/c9b04686-b3c8-11e5-9d77-e5c57e94a9c4.png)

**Comment by DeltaVetal26** [comment]
![3e369e0188](https://cloud.githubusercontent.com/assets/16554245/12135946/3d369d88-b475-11e5-8b89-4cd09fc13420.jpg)

**Comment by dutchy1001** [comment]
Thx for the ```/usb version``` output, but can you post the translation file you made plz? I can then test it and see if there are any mistakes made.

**Comment by DeltaVetal26** [comment]
Where you can pour translation? P. s here do not want to pour .zip archives and .po files

**Comment by dutchy1001** [comment]
copt the translation as you do a text file and paste it in [pastebin](http://pastebin.com/) (it's free).
I will then copy the text and save as .PO file

**Comment by DeltaVetal26** [comment]
http://pastebin.com/ifLkj75E

**Comment by dutchy1001** [comment]
The file gives by me similar errors. 
The file itself is OK, I presume a bug in the code of "custom" added .po files is causing the issue's.

**Comment by DeltaVetal26** [comment]
And when it might be fixed? In the new versions or will a separate patch?

**Comment by dutchy1001** [comment]
That all depends on the time our developer has.

**Comment by rlf** [comment]
Workaround: provde a translation for "Config:" in line 1203.

**Comment by dutchy1001** [comment]
not sure this is the solution, as I don't have any problems with the 1.8 version (v2.5.6). Is there any difference in the translation code between the 2 versions?

**Comment by rlf** [comment]
Someone, please verify whether this issue can be closed

**Comment by dutchy1001** [comment]
the test server been using en_GB for a while with no problems, to me it seems fixed with the later releases.
