### ISSUE TITLE
Biome with no monsters?

### ISSUE THREAD

**Issue by CocoCr33p3r** [rlf/uSkyBlock#608]
It would be really helpful if there would be a biome where hostile mobs wont spawn or any way to let players toggle the spawning of hostile mobs for only their own skyblock.
I know that there is a flag in WG that covers this, however you can only activate that with WE region select.
Ps. The only biome with no hostile mobs are mushroom biomes, but mooshrooms spawn there.
A no mobs or only friendly mobs would be awesome.

**Comment by voigtman** [comment]
mushroom biome

**Comment by CocoCr33p3r** [comment]
I wrote that aready by the Ps part. I dont want mooshrooms to spawn then

**Comment by voigtman** [comment]
You also wrote 
"A no mobs or only friendly mobs would be awesome" mooshrooms are friendlies. And it's a vanilla function that mushroom biome is monster free. I just tell my players to use slabs, lights or glass. 

I'm not a part of uskyblock's build team but I'm sure they'll be just ad confused by this request. It seems totally pointless. what sort of experience are you trying to provide for your players?

**Comment by CocoCr33p3r** [comment]
Well, i have this problem that hostile mobs spawn, even at 2 or 3 blocks away from a torch, and weirly enough it only happens on skyblocks and not in other worlds.
That's the reason why i came up with this request, i believe now that i shouldn't have made this request but shouldve created a ticket about that particular problem.
Hope this clears up a bit

**Comment by dutchy1001** [comment]
I'm not sure why it spawns hostile mobs even when the light level is higher then required. I will look into this on the test server.
As far I know were not having anything done to the vanilla code for spawning mobs.

**Comment by rlf** [comment]
We haven't but...
I guess we could introduce a biome with no mobs at all (what about golems? villagers?)
We could also, introduce a configurable "island age" before spawning monsters :D
But that would be a different issue.

**Comment by rlf** [comment]
> That's the reason why i came up with this request, i believe now that i shouldn't have made this request but shouldve created a ticket about that particular problem.

Closing this - unless someone has a good reason to introduce it.
