### ISSUE TITLE
Not working but met all requirements

### ISSUE THREAD

**Issue by halo4202** [rlf/uSkyBlock#609]
Hi yes i am running 1.8.8 Spigot on my servr i have the latest of all my plugins and Uskyblock (2.5.3)
whenever i do /is this happens
![2015-12-29_17 11 19](https://cloud.githubusercontent.com/assets/16587633/12162691/332a3614-b4cb-11e5-8a2b-164242a0781f.png)
and then i do /is restart or any other commands it says and i get the same thing

**Comment by dutchy1001** [comment]
That means you are missing or using a wrong version of a depended plugin.

List the versions of the depended plugins or paste a startup log, through [pastebin](http://pastebin.com/) as telling us "I have the latest" is not telling us anything.
Pls read this section [here](http://dev.bukkit.org/bukkit-plugins/uskyblock/#w-installation) and [here](http://dev.bukkit.org/bukkit-plugins/uskyblock/#w-bug-report)

**Comment by halo4202** [comment]
OK here is my Startup http://pastebin.com/XP9F32ti
i am running 1.8.8-R0.1-SNAPSHOT Spigot
Worldedit 6.1
WorldGuard v6.1
Vault v1.5.6-b49
Multiversecore v2.4-b527
uskyblock v2.5.3-bukkit-1.7.9
I was reading through the startup and found this dont know what it means http://pastebin.com/saxdMvdK
This error code also ran on start up
http://pastebin.com/jj2TNSgJ
(i am using the wolrd askyblock for a differant world not skyblock so the world is there but not the plugin)

**Comment by dutchy1001** [comment]
From this list I can see already a few simple mistakes that can be fixed by just reading the page properly. If you read the paragraphs I linked in my previous message then you can find them too.

**Comment by dutchy1001** [comment]
This [link](http://pastebin.com/saxdMvdK) is the info we keep asking so we can see if the right depended plugins are used.

**Comment by halo4202** [comment]
i try /usb version but it just says do /usb version for version

**Comment by dutchy1001** [comment]
Let me read it then for you.
You use:
Spigot **1.8.8**-R0.1-SNAPSHOT and use a uSkyblock version for uskyblock v2.5.3-bukkit-**1.7.9** which is the first fault.
In the paragraph's I linked you to it says:
Multiverse-Core (**versions above v2.5**) whily you use Multiversecore **v2.4**-b527.
Change them and it should work.

I'm sorry If I sound grumpy but it's really a simple reading issue (and I just woke up)

**Comment by csorrows** [comment]
There is nothing wrong with your reply @dutchy1001. The issues were quite obvious.

**Comment by dutchy1001** [comment]
After meeting on a server, not the test server (what the chance that would happen) I was told it was sorted.
