### ISSUE TITLE
GUI to choose a starting island

### ISSUE THREAD

**Issue by Banbeucmas** [rlf/uSkyBlock#610]
Just came up that idea when chatting with dutchy on test server, well this could be add to the island menu, disable could be doone by the config

what i am worried is it could affect the permission performance, *Since you might use the for loop to find the island permission of the player <ArrayList> lol

**Comment by voigtman** [comment]
+1 for this idea!
I currently do this already. It took some doing but it is possible with what's already available.
![image](https://cloud.githubusercontent.com/assets/12475929/12265948/d9349f34-b905-11e5-90f5-5d477cb6254d.png)

**Comment by BlackBeltPanda** [comment]
I've also done this on my server by dynamically adding/removing the permission nodes for starting islands. Would be great if this was handled by USB and could be utilized in "/is restart". =)

**Comment by dutchy1001** [comment]
I've seen the islands you added @BlackBeltPanda, some are very big and that can cause some performance issue's (the time to spawn the island).  I do like the one with the small sand island next to it.
Could I suggest that we get some schematics of our users what they would like to see added for when this option will become available?
An exaplmes:
http://i.imgur.com/K1a1o5f.png (mega hard core)

**Comment by rlf** [comment]
Hmm, you have a point @BlackBeltPanda , we need to allow for `/is restart` to show the create UI again then...

**Comment by dutchy1001** [comment]
if the /is restart and /is create brings up the GUI then implementing a multi island choice will not be that far away to add.

**Comment by rlf** [comment]
Ye, but currently we don't have a `/is delete´, and subsequently `/is restart` has no UI.

**Comment by dutchy1001** [comment]
I dont mind the add of a ```/is delete``` command as long with a conformation

**Comment by voigtman** [comment]
I've set mine up with a custom command
/selfdestruct
then a message appears to say:
  !!!! WARNING !!!! SELF DESTRUCT SEQUENCE ACTIVATED.
  YOU MUST ENTER YOUR CONFIRMATION WITHIN THE NEXT 30 SECONDS.
  THIS CANNOT BE UNDONE! ||| repeat ||| THIS CANNOT BE UNDONE!
  
  TO CONFIRM TYPE:&f /selfdestruct-confirm
  TO DEACTIVE TYPE:&f /abort
  
  SELF DESTRUCT WILL AUTOMATICALLY CANCEL AFTER 30 SECONDS.
  COUNT DOWN BEGINS NOW

Then is counts down in which time the player must confirm or abort. If at the end of the count down, the player hasn't decided, it automatically aborts. It adds some fun and seriousness to the game. If you were to add it to the gui - it should be a redstone block (don't push the red button!)

**Comment by dutchy1001** [comment]
lol I like the way you used ```/selfdestruct```

**Comment by voigtman** [comment]
<- grew up on Star Trek :D

**Comment by dutchy1001** [comment]
I still dream of Seven of Nine

**Comment by voigtman** [comment]
lol

**Comment by voigtman** [comment]
maybe, as a matter of confirmation - it could be added to the gui as a sort of mini-game... click the red wool and it goes through three screens all filled with green wool but 1 moving block of red (top left, bottom right, middle) and by doing this, they confirm their demise. Which brings me to #616. currently, when a player destroys or restarts their island - it kills their main island leaving the others intact. people like this as they can destroy their ugly noob builds while preserving their later stage shops and such.. This gives them the opportunity to rebuild in their now more refined stile and aesthetic. I would suggest this remain true if 616 is to be realized. Also, if there isn't already a measure in the coding, that player's island should respawn in same place as their last island stood.

**Comment by rlf** [comment]
well, if we do the island merge, I think restart should be done for the combined island.
That is what is meant by restart tbh.

Reg. respawning, restart is a clean-slate, but at the same position.

**Comment by rlf** [comment]
this is implemented, closing

**Comment by voigtman** [comment]
Woohoo!
