### ISSUE TITLE
Add Golems to spawn-limits

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#611]
Currently we only have animals, monsters and NPCs - Golems fall outside of any of these categories.

Should have their own category (snowman + iron golems) or be included in animals.

**Comment by Disorbs** [comment]
this is meant for spawners tho not natural spawning.

**Comment by rlf** [comment]
Huh?
With spawners I assume you mean "iron golem farms"? Which is "natural spawning".

**Comment by Disorbs** [comment]
we have natural spawning off, its only on for eggs or spawners.

**Comment by rlf** [comment]
Well, our limits are imposed on both.

**Comment by dutchy1001** [comment]
Tested and working in v2.6.1
