### ISSUE TITLE
Requested Features

### ISSUE THREAD

**Issue by voigtman** [rlf/uSkyBlock#615]
Hello R4z and Dutchy!
I'm here with a few requested features / changes.
1: Islands that can be conjoined.
We offer island expansions through our buycraft to players who want to build on a space larger than we initially offer. This has a few benefits for the player and server. 1 players are able to keep their builds and continue being challenged by adding on more space to develop. 2 it generates a little revenue to support hosting the server. We have run into a few issues in doing this for our players, namely with the worldguard regions. Currently we have to bloat our WG regions by adding enveloping regions which adds confusion for players who became accustomed to using the /is command for everything. We've talked about this before in a pm - a good example of how this would work can be found in a plots plugin. You asked why I didn't go that route - and the simple answer is - it's not uSkyBlock!  Everything would have been a /plot command and I love the way USB handles everything else. 

2: AddOn more support for admins. My current build for my server is 2.4.6. I will not be upgrading to the 2.5 versions as it would be detrimental to my server as we're already pretty well established. I don't expect you would go back to this version and make any updates I request - I'll just have to live with that. However I do have plans to add it to a new server idea I've come up with after playing with it on the test server and on another server owner's setup. 
Admin support requested:
A: Give Admins a perm that prevents players from kicking them off of their island is /is kick playername
B: Allow admins to have a command to trust players on any island (ie /usb island trust).

3: Please change how uSkyBlock handles WorldGuard. What I mean with this is (at least in my version) an island's WG region is fully updated anytime a player does /is trust, biome, etc. Since not all w/g functions are handled through USB, I allow players to have access to /rg flag...  (For instance - /rg flag 0,100island lightning deny) When a player changes something with the /is command these flags are reset and the region size is also reset without the player realizing it leaving them surprised when something they thought was protected gets harmed. Manually adjusting he WG region size matters for our server as it's how we're able to permit players to fill in the gap between their added islands. When their region gets reset it locks them out of their added island spaces.

Thats about all I can think of at the moment.  Have a great day guys and thanks so much for your dedication to this project! we love you here at VMC!

**Comment by rlf** [comment]
Hi @voigtman 
First off, let's mark this as a discussion, and then maybe spin/spawn off any issues we end up deeming is relevant to add.

We discussed 1. earlier (in PM) - I think it's worth considering (added #616).

Not entirely sure why you chose to stay on 2.4.6, what is it in 2.5 that blocks you from updating?

Reg. 2a) See #617.
Reg. 2b) See #618

Reg. 3 - that is not likely to happen - at least we plan to move more and more over to using the WG regions, which would enable us to realise #616.

Just as a discussion, is the parent cleared as well? Because, otherwise, you could make a "parent-region" to the island, and control all the flags etc. there?
That way, the resizing of the "island-region" is not important, since the "parent-region" controls building permissions etc.

**Comment by voigtman** [comment]
hi @rlf 
Parent? I'm not sure I follow as islands spawn with only 1 region on them. We've resorted to adding a second region which causes some trouble as players they get accustomed to doing everything with their /is commands. Some players have found benefit in having multiple regions, however several have not.

I've chosen to stay on 2.4.6 because it's been very stable except for the discussed topic. We have no need for the new nether as my current nether has already well established builds and players wouldn't be too pleased with a reset. We have our own way of dealing with protections in the nether that help build the economy as well. Having several nether worlds would be a bit much here... At least on this particular skyblock. I have plans to open a second. We also have our own method of giving players guardians, so again another feature that's not necessary for us. We like to wait for a version to establish itself as being very stable before we make a change, and every time I do update I have to redo all the work I put into making #610 possible on my server. 

Thanks for the other updates - you're going to make me update after all... I just know it.

**Comment by dutchy1001** [comment]
A "parent" region will apply to all regions that revere to this, the flags in this region will not change (unless you change the "parent") but the flags added separate to the region can be updated then.

In your case you merge 2 or 3 or 4 islands together wich will be the"parent" region while custom flags can then be added/changed/removed by the players.

**Comment by voigtman** [comment]
I try to keep things like this as simple as possible for my players... 1 region to adjust is better than one on each island plus a parent, (the only way they can adjust their other regions currently is with the /rg command). The biggest question I keep getting asked is how can they adjust the biomes of their other spaces, and the answer I tell them is to modreq and i'll do it. the players would rather not have to use /rg for their islands, but would like to stick with /is. Are you saying I should make the envelope a slave to their islands? I ask because I currently have no way to add them to their island's trusted list and this means they really only have 1 island they command with /is.

**Comment by rlf** [comment]
Something along these lines:
```
/rg define voigtman
/rg setpriority voigtman 200

/rg setparent 110,110island voigtman
/rg setparent -110,-110island voigtman

/rg flag voigtman ice-melt deny
```
That way, the user would have to simply use `/rg <playername>` instead of the abstract name assigned by uSkyBlock.

The hierarchy would be:
```
+ voigtman [prio=200]
  +- 110,110island [prio=100]
  +- -110,-110island [prio=100]
```

**Comment by voigtman** [comment]
I don't suppose there would be a way to set this up to do this automatically on first island creation, would there?

**Comment by rlf** [comment]
Not currently, esp. since we don't know what size of the "parent region" you'd like, or what islands to "merge".
