### ISSUE TITLE
Player command to view Island Animal Count

### ISSUE THREAD

**Issue by Deathinflames** [rlf/uSkyBlock#621]
Hello!

We would like to request a command that will allow island owners the ability to check the entity count of their island so that they know when they are reaching the "spawn-limits:". Thank you!

**Comment by rlf** [comment]
We should also include it in the "island level tooltip" in the menu.

**Comment by Deathinflames** [comment]
That would be great, thank you for considering our request! :)

**Comment by dutchy1001** [comment]
Tested and working with v2.6.1
