### ISSUE TITLE
Island Party challenge rewards feature

### ISSUE THREAD

**Issue by Nightwolf3218** [rlf/uSkyBlock#622]
I am not sure if this is something I am missing or if it is something that we would need added.  We have titles and sometimes other rewards linked to challenge completion.  While we love the idea of the single challenge list for the islands to help balance the economy between single person and large group islands, one issue we have ran into is being able to distribute these permissions based rewards.  I would like a way to have a reward be given to all members of an island and not just the person completing the challenge.

Example of what I mean:

Island has players A, B, and C on.  Currently, only players A and B are online.  Player B completes the SkyLord challenge (island having 1000 levels).  At this point, we need all members of the island to receive the permission for the SkyLord title.  This means giving it to A, B, and C so that they can all now wear the SkyLord title.

This would also be useful if it could give out items and other things as well for rewards and not just things like permissions which would be easier since it doesn't matter if they are offline.

I could see this broken into maybe two stages of development if you choose to implement this feature.

First would be the ability to just set a island party reward where it would pull the list of members and go through doing the reward command.  This would work for things like permissions.

Second would be implementing a reward delivery queue so it would cache offline players and their rewards to be received and run the commands the next time they log in.  (Not sure if this would be possible, just an idea).

Another possible issue I can see related to the permissions as rewards would be new players joining an already well established island.  Not sure if this is something that can be remedied or not.  But if an island has a ton of challenges already done and a new player joins, they would also miss out on any permission based reward given through the challenge system and this would require staff to manually handle these.

Thank you for your consideration of these issues/feature requests,
Nightwolf3218

**Comment by Nightwolf3218** [comment]
One thing I would recommend for the new player joining an island is maybe have this set as an optional configuration in the config file or as a command that a staff member can run (permission based) that would check the challenge rewards for the island and give them to that player (for the island group rewards).

Again, thanks for taking the time to consider this,
NIghtwolf3218

**Comment by dutchy1001** [comment]
I like the idea of sharing the rewards/permissions between party members (not including trusted players for this).
I would suggest this only if the challenges config is set to ```challengeSharing: island``` as when set to ```player``` each will get the reward anyway when they individual complete a challenge .

I'm not sure if it's possible atm to store rewards/permissions for offline player with our .yml format.

I don't think for newly added members after a good few challenges are completed that they should be entitled to previous rewards, this wouldn't be fair to other players.
Optional you can set some side challenges through using a "quests" plugin to obtain previously rewarded permissions.

A downfall on this is when players only join an island to gain the extra permissions and then leave a party to start their own island with the extra permissions gained from the reward (only items are reset on restart). A restart cant delete the permissions given as this is for each server different. This can add an advantage/abuse over other players that started on their own without these extra's.

**Comment by rlf** [comment]
Is it something along these lines you look for?
https://github.com/rlf/uSkyBlock/wiki/commands-in-config

I.e. 
```
commands:
          - op:effect {party} 10
```

The `{party}` only works for online players in sky-related worlds.
So we probably need some new tag for your use-case.

Reg. "rewarding to offline players on login", I don't see that as likely.
Neither rewarding players when joining.
As in most other MMO games, you only get rewarded for stuff you participate in, not stuff your party did before you joined.

**Comment by Nightwolf3218** [comment]
Something like the {party} would be perfect if it could also include offline players in that list.  For our server and use, the main purpose we use it for is extra permissions for things that are mostly harmless such as unique titles.

Queuing commands for Offline players:
I just added this in case some servers might have a use for this and wanted to do more than just add perms to a player.  Thankfully, adding perms to a player that is offline shouldn't be a problem (at least not for the permission plugin we use) but it is having a flag that will recognize and iterate through those players as well.  I could see this being utilized to give larger special rewards to an island party for completing some special and hard challenge and would hate for members to miss out but to me, the first issue of just being able to apply permissions to all island members (including offline ones) is the main goal of this post.

For giving new players perks up to current challenge level:
I can see where new players joining an island to get perks could be abused which is why I would recommend adding this as an option in the config file to have it turned on or maybe as an in-game command to help staff update a player.  On our server, this wouldn't be game changing because it is mostly for special titles.  At one point we had an issue with nether portals sometimes allowing access to the end, so we used challenges to add a dummy perm to players when they earned the challenge to get the end portal via a challenge and checked to make sure they had that perm before allowing them access to the end (though this issue has finally been fixed through plugin updates and no longer needed).  I realize that depending on how a server is using challenge rewards though, this could definitely be a major point of abuse so I can only say that it should only be implemented if it can have an off switch to help prevent abuse on other servers where this could cause more harm.


Once more, thank you all for your time in reading and considering this.  I love this plugin and look forward to all the changes and updates you guys are making.  Great work.

Nightwolf3218

**Comment by rlf** [comment]
Well, we already have a feature, that will clear the player-inventory when they join the skyworld (used when players do `/is restart` and then goes offline).

We could probably introduce something similar for the `{all}` tag.

**Comment by rlf** [comment]
Just re-read the code, it seems that using `{party}` should work regardless of whether they are online or not.

**Comment by dutchy1001** [comment]
No further input on this and I think it's added/working as should.
