### ISSUE TITLE
Vehicle can destroy and minecraft with chest

### ISSUE THREAD

**Issue by MrFiliper** [rlf/uSkyBlock#624]
First, minecart with chest, visited players can open this chest. Bug?

Secondly, if default setting vehicle-destroy none, in worldguard __global__ region, minecart cant break with cactus. if i set vehicle-destroy allow, minecraft can break with cactus, but visited players can break the minecart. Please fix this. Thanks.

**Comment by rlf** [comment]
Please provide info from `/usb version` please.

**Comment by MrFiliper** [comment]
Version 2.5.0-SNAPSHOT (sky)
WorldEdit: 6.1;no_git_id
WorldGuard: 6.1
AsyncWorldEdit: 2.2.2

**Comment by dutchy1001** [comment]
In a previous message I already said to update to v2.5.7

**Comment by MrFiliper** [comment]
Yes, but to previous message. I didnt know that here.

**Comment by dutchy1001** [comment]
I presume that after you seen the first post to update to v2.5.7 you would not have posted 2 days later with the same "old" version. This might aswell be fixed as many issue's came from the language bug.

**Comment by rlf** [comment]
@dutchy1001 can you reproduce this?
As far as I understand MrGoogleTranslate, it's something along the lines of "minecarts with chests can be accessed by visiting players" - if that is the case, I assume it's a WG bug.

The "secondly" part seems to be, that he wants us to allow breaking vehicles on cactii, but block player breaking? Not sure how to respond to that.

**Comment by dutchy1001** [comment]
I can confirm the use of a minecart with chest by visitors. 

The second part if you set "vehicle-destroy allow" that will mean that all mechanics what is "allowed" can be done. If this is break by cactus or break by visitor that doesn't matter, break is break. I dont think WG can make a difference in that, it's allow all or deny all (me thinks).

**Comment by rlf** [comment]
A bug-report exists on WG:
http://dev.enginehub.org/youtrack/issue/WORLDGUARD-3585
