### ISSUE TITLE
Percentages on rewards/repeatrewards

### ISSUE THREAD

**Issue by i9hdkill** [rlf/uSkyBlock#626]
Hi,
right now our server uses default challenges, so some of our players complained about some challenges, especially about sugar farmer.

The repeatreward tooltip says you get 4 dirt which is wrong.

https://github.com/rlf/uSkyBlock/blob/a5b58f232d15d29aa001666c8084e9693675b87a/uSkyBlock-Core/src/main/resources/challenges.yml#L292

>repeatReward:
          text: 4 dirt
          items:
          - '3:4'
          - '{p=0.05}3:4'
          currency: 10
          xp: 10

You don't get the 4 guranteed dirt but instead you have the chance to get 4 dirt (0.05)
Not sure if it's a bug that you don't get the guranteed item if there is the same item defined as percentage. (In this case) or it's intended.
But if it's intended >- '{p=0.05}3:4' should do it and not both:
>items
- '3:4'
- '{p=0.05}3:4'

**Comment by dutchy1001** [comment]
As far I know the way I made it is that you get the 4 dirt guaranteed and have a 5% change to get 4 extra. (I will check this tomorrow)

The challenges are subject to change by the server owner, I left the rewards low on purpose. 
I just made sure it gives out rewards that are needed in future challenges.
I did mention in the release notes on bukkit that the rewards are very basic and can be changed to the server owners liking.

**Comment by i9hdkill** [comment]
>The challenges are subject to change by the server owner, I left the rewards low on purpose
Yeah, I know but I want to let you know that this would NOT work: (you don't get the 4 dirt)
- '3:4'
- '{p=0.05}3:4'

but this works:
- '3:4'
- '{p=0.05}21:4'  <---not identical item id compared to the guaranteed item)

**Comment by rlf** [comment]
Yup, that is a known "limitation", the data-model behind the scenes calculates the probability of each "item-type", so you can't have the item type multiple times.

**Comment by rlf** [comment]
But, given that this seems like a legit use-case, I should probably fix that "data-model bug"

**Comment by dutchy1001** [comment]
I just tested this and as soon I "comment" the ```'{p=0.05}3:4'``` it gives out the 4 dirt from the repeat reward.

**Comment by dutchy1001** [comment]
tested this with pre release v2.5.8 and is giving correct rewards now when the % reward is given.

**Comment by dutchy1001** [comment]
No more input from the OP so guess my previous answer was sufficient enough.
