### ISSUE TITLE
Maven "POM is missing, no dependency information available"

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#627]
Trying to build against the USB API.
Using the maven information here: https://github.com/rlf/uSkyBlock/wiki/uSkyBlock-API
I'm getting an artifact missing error in my pom.xml and a POM is missing error when compiling my plugin.
Has the repo information changed? I've tried different versions of USB in the dependency information, including "2.5.5".

**Comment by rlf** [comment]
The API doesn't change version as often as the plugin.
I.e. the version is only "bumped" when there are changes to the API.

The latest version of the API is v2.5.5 - but it seems you are right, the maven repository hasn't had any updates to the API for a while.

I will investigate and get back to you.

**Comment by BlackBeltPanda** [comment]
Great, thanks. =)

**Comment by rlf** [comment]
It seems the GitHub way we deploy the artefacts stopped working.
I'm working on a solution, where I can publish the jars in the OSSRH (to get it to maven-central).
Unfortunately, this will take some time.

**Comment by rlf** [comment]
I pushed the v2.6.2 and v2.6.4 to "our maven repo", so it should be available there as:
```
<dependency>
    <groupId>com.github.rlf</groupId>
    <artifactId>uSkyBlock-API</artifactId>
    <version>2.6.4</version>
</dependency>
```
and this repository.
```
        <repository>
            <!-- Our repo is last - so we can put in fallback artifacts when the other repos are down -->
            <id>uSkyBlock-mvn-repo</id>
            <url>https://raw.github.com/rlf/uSkyBlock/mvn-repo/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <releases>
                <enabled>true</enabled>
            </releases>
        </repository>
```

**Comment by dutchy1001** [comment]
I presume this is fixed

closed
