### ISSUE TITLE
Nether island region isn't updated when using "orphan" location

### ISSUE THREAD

**Issue by BLLaZZeR** [rlf/uSkyBlock#629]
Hey, I'm having issue with changing ownership of the nether island to another player, after reclaiming an orphan.

When player from first island leaves to join to second island then next player who claim orphan from first island doesn't claim nether island as well. Region is still claimed by first player who already left.
![usb ver](https://cloud.githubusercontent.com/assets/16800432/12455321/66705eba-bf9b-11e5-81e0-7935d3da8412.JPG)

**Comment by dutchy1001** [comment]
I saw the conversation you had with SgtLegoTown on the server, I will test this tonight and come back to it.

**Comment by dutchy1001** [comment]
After testing this, when creating an island that uses an "orphan" location the nether is indeed not updated. When that player does a command that triggers the WG to reload/save (EG. /is trust [player]) it will chnage the Nether region to the new owner. This can be used as temporally fix for now till we can  fix the issue.

**Comment by rlf** [comment]
Please re-test this on v2.5.8 - I cannot reproduce it in my setup.

**Comment by BLLaZZeR** [comment]
Tested and works fine now. Thanks!

**Comment by rlf** [comment]
It's aye ok for you to close issues :D
