### ISSUE TITLE
How to "Separate" the money using MV Inventories

### ISSUE THREAD

**Issue by PinoyLifeCraft** [rlf/uSkyBlock#633]
Hellow guys i like to ask on how to separate the money on uskyblock, if the player has X money in spawnpoint then if they go in the uskyworld then they have there X money like 1M money :disappointed:

**Comment by rlf** [comment]
It's not an issue for uSkyBlock - you should probably ask this kind of question on the MV forums.

Multiverse-Inventories have a ton of issues with regards to economy.
It simply only uses Vault to save the balance when players change "realm", and re-create the balance when the come back.

That means, that if you for instance uses Essentials for the economy, players can transfer money cross-realm if they have access to `/pay`.

That being said, you would probably do something along these lines:
```
/mvinv group
```
This will enter into a dialogue with you, where you are allowed to make a new inventory group, and select what shares it has.

Let's say you call that group for `skyworld` and add `skyworld` and `skyworld_nether` worlds to it.
Make sure to use the `all` for shares.

To enable the `currency` share, simply do `/mvinv toggle currency`.

Please note, if you stand in one of the worlds when you "reset the groups", you will lose your inventory.

**Comment by dutchy1001** [comment]
There is a way to do this with MV-inventories but very poorly documented. 

As R4zorax already said, you use the interface from Multiverse-Inventories ```/mvinv group``` to separate the worlds in groups, see [groups.yml](http://pastebin.com/BQnzHDMa) for an example (I do recommend the use of the commands and NOT edit the groups.yml by hand).

To have then the economy separated, you need to add the following to the "main" config.yml (exactly as I did with the spacing between the lines):
```
  # You must specify optional shares you wish to use here or they will be ignored.
  # The only built in optional share is "economy"
  use_optionals:

  - economy 
```

See my own example [here](http://pastebin.com/mrxQb4NH)

Each group as shown in the groups.yml will have it's own economy then.

**Comment by i9hdkill** [comment]
You shouldn't use MV inventories at all. 
No uuid support and major flaws. Split your server to have a seperated skyblock server.
When it comes to performance it's better anyway.
Because of the missing uuid should be a no brainer anyway.
The way how mv inventories handles eco and inventories is kinda ugly.

**Comment by dutchy1001** [comment]
I appreciate your input but for our test server we only have 1 server, no bungee setup, so this was the easiest way for me to do. We have only a few worlds (world, world_nether, world_the_end, skyworld, skyworld nether). I really dont need it but if I open the overworld on our server at least skyworld has it's own eco.

If you know a better way with single server setup I would love to know this.

**Comment by rlf** [comment]
There is some branches of MV-Inv on GitHub that seems to have UUID support - not sure how stable they are though.

**Comment by dutchy1001** [comment]
The way I explained is the only way I know to separate economy in non bungee server and known to work for me. If others want to use it it's up to them ofcourse, but atleast there is a way.

**Comment by dutchy1001** [comment]
We can still talk about this when closed as it's not a uSkyblock issue.
