### ISSUE TITLE
SkyGrid play-mode

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#634]
we had a discussion about introducing a skygrid-inspired play-style into the plugin.

I will take a look at what is required.

**Comment by itismejoey** [comment]
Yassss! I told dutchy today that I would love to see this feature. We were adding this feature on our server (MCFriends) and I was going to hand code it myself. However, using a plugin that my players are already familiar with would work perfectly!

If you have any questions or need any testing on a live public server, we will be honored to be the one!

**Comment by rlf** [comment]
Haha, hold the horses - just looking into it now.

But, thinking it should be fairly easy to incorporate into the uSkyBlock "eco-system".

The "big question" right now, is to whether to make it "centrally configured" or allow a mix of skygrid and "normal islands" in the same world.

The score of a skygrid island will be quite high compared to a "normal" one.

**Comment by dutchy1001** [comment]
I would suggest to disable the score when using skygrid

**Comment by itismejoey** [comment]
I would say centrally configured. 

Agreed dutchy

**Comment by rlf** [comment]
As you might have noticed, we decided against cooking the SkyGrid into the uSkyBlock plugin, but added support for custom world generators instead.

Please read this post https://github.com/rlf/uSkyBlock/wiki/SkyGrid
