### ISSUE TITLE
Add pagination to /usb config

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#635]
Our config.yml now takes up more than 5 pages.
Time to add pagination.

**Comment by dutchy1001** [comment]
A redo for the challenges paging isn't bad either to do, many are still confused how to get to the next page.
Adding this at the bottom with a "next page" (green wool) a "previous page" (red wool) and in the middle a "close" (nether star) button maybe is an idea. Blocks can be arrows by using heads of course too.

**Comment by rlf** [comment]
Seems like a separate issue :)

**Comment by BlackBeltPanda** [comment]
New pagination's working great for me in v2.6.1. =D
