### ISSUE TITLE
improve pagination of challenge gui

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#636]
Dutchy keeps saying that the pagination of the challenge gui is hard to get.

We need to redo it.

**Comment by rlf** [comment]
Suggestion: It's unlikely that we will need more than 9 pages, meaning we could reserve the top-most (or bottom most) row as an index row.

Use written book (item id 387) as page-navigation (item-count 1-9), and Book and quill (item id 386) for the current page.

Tooltips show what page it is.
Acceptable?

**Comment by dutchy1001** [comment]
Sorry for keep giving ya more work :)
I suggest the bottom row for this.
The rest is clear and acceptable 
Will the tooltip(s) be customizable?

**Comment by rlf** [comment]
Don't think so, if we "auto-generate" the index, it should't be configurable.

Adding "pages" to the ranks are bound to cause trouble for the average server-admin.

**Comment by dutchy1001** [comment]
If not configurable, will it be translatable with the GetText?

**Comment by dutchy1001** [comment]
Paging works fine now with a better GUI
