### ISSUE TITLE
Lag continuous uSkyBlock

### ISSUE THREAD

**Issue by EverMineServer** [rlf/uSkyBlock#639]
Hi I'm having trouble with your plugin: lag and crash continues.
Here is the timing: http://timings.aikar.co/?url=14672898
I'm writing because I'm looking for weeks that the problem but I can't find it, I hope you can help me. Best regards.

**Comment by rlf** [comment]
Known issue, related to #401 #540

**Comment by rlf** [comment]
Please re-test with https://github.com/rlf/uSkyBlock/releases/tag/v2.5.11

**Comment by EverMineServer** [comment]
Whit the version that you suggested me.
http://timings.aikar.co/?url=14680276
You are improving :)

**Comment by rlf** [comment]
Fixed (for the most part) in v2.6.0 (use with caution).
