### ISSUE TITLE
Disable Chest Items

### ISSUE THREAD

**Issue by Time6628** [rlf/uSkyBlock#641]
I was wondering if you could add an option to disable adding items to the chest. I have a schematic that has all the items in it(some of the items cannot be adding to the list already in the config because they have metadata like Forestry Bees) and whenever create an island with it, the chest is empty, but when I paste the schem all the items are there. I think this may be helpful for modded skyblock servers :smile_cat:

**Comment by dutchy1001** [comment]
As we clear inventory on create and restart the items have to be added through the config. You might be able to add items through kits given at first challenge or use the "extra-commands" (in the config) to give a kit on creation/restart.

**Comment by Time6628** [comment]
Yes but the problem is that forestry bee's cannot be given via id. They have a lot of data tags that go with them. 
For example:
A normal Meadows princess has the id 4952, but that id gives you a blank bee.
In order to get an actually meadows princess, you have to give it the correct datatag:
```({MaxH: 20, NA: 0 as byte, Health: 20, IsAnalyzed: 1 as byte, Genome: {Chromosomes: [{UID1: "forestry.speciesMeadows", UID0: "forestry.speciesMeadows", Slot: 0 as byte}, {UID1: "forestry.speedSlowest", UID0: "forestry.speedSlowest", Slot: 1 as byte}, {UID1: "forestry.lifespanShorter", UID0: "forestry.lifespanShorter", Slot: 2 as byte}, {UID1: "forestry.fertilityNormal", UID0: "forestry.fertilityNormal", Slot: 3 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 4 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 5 as byte}, {UID1: "forestry.toleranceNone", UID0: "forestry.toleranceNone", Slot: 7 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 8 as byte}, {UID1: "forestry.boolFalse", UID0: "forestry.boolFalse", Slot: 9 as byte}, {UID1: "forestry.flowersVanilla", UID0: "forestry.flowersVanilla", Slot: 10 as byte}, {UID1: "forestry.floweringSlower", UID0: "forestry.floweringSlower", Slot: 11 as byte}, {UID1: "forestry.territoryAverage", UID0: "forestry.territoryAverage", Slot: 12 as byte}, {UID1: "forestry.effectNone", UID0: "forestry.effectNone", Slot: 13 as byte}]}})
```
WorldEdit however, does copy the bee from the schematic.

**Comment by dutchy1001** [comment]
Am I right to assume your on KCauldron??

**Comment by rlf** [comment]
Just change the following in your `config.yml`:
```
options:
  island:
    chestItems: ''
    addExtraItems: false
```

**Comment by Time6628** [comment]
My config is:
```
    # [item list] The list of items to place in the chest when a player starts a new island. ITEM_ID:HOW_MANY.
    # default is 2 ice, 1 watermelon, 1 cactus, 1 lava bucket, 1 red & brown mushroom, 1 pumpkin seed, 1 sugar cane, 1 sign.
    chestItems: ''

    # [true/false] If true, add extra items to a chest when a player starts a new island. (for donors and special players)
    addExtraItems: false
```
And it still will not put the items from the schem into the chest D:

**Comment by rlf** [comment]
Ahh, you are right, we clear the chest then.

**Comment by rlf** [comment]
I see no reason to actually clear the chest inventory - and I think for your use, if we just don't do that, any items from the schematic will be available in the chest.

**Comment by dutchy1001** [comment]
So chests are not cleared on create/restart in coming versions? This brings a lot of opportunity extra with the custom islands.

**Comment by Time6628** [comment]
Cool beans. :smiley_cat:

**Comment by rlf** [comment]
Ready for test in v2.6.0 (use with caution).

**Comment by Time6628** [comment]
Tested with 2.6.0. Seems to reset the entire skyworld and no /is commands work xD

**Comment by rlf** [comment]
Sounds like a configuration issue.
But, as it's still a pre-release, it might contain erradic behaviour.

**Comment by dutchy1001** [comment]
Working for me with v2.6.1
