### ISSUE TITLE
Nether islands

### ISSUE THREAD

**Issue by MrFiliper** [rlf/uSkyBlock#644]
I have problém with nether islands. In the config i set:

distance: 416
protectionRange: 320

Create nether world with name skyworld_nether, in the config set scale to 1.0 and generator set to uSkyBlock. Next I restart server. If I go the nether portal, portal was created, but island not.

Whats the problém?

/ubs version - uSky 2.5.0-SNAPSHOT, Vault - 1.5.6, WorldGuard - 6.1 and WorldEdit - 6.1

**Comment by dutchy1001** [comment]
You created or the plugin created the nether world??

Do a proper output from /usb version plz, either screen shot or full startup log. (use pastebin for log)

**Comment by MrFiliper** [comment]
Log: http://pastebin.com/93FgFZmy

USB:
[17:21:49 INFO]: Name: uSkyBlock
[17:21:49 INFO]: Version: 2.6.0
[17:21:49 INFO]: Description: Ultimate SkyBlock v
[17:21:49 INFO]: Language: cs (cs)
[17:21:49 INFO]: ------------------------------
[17:21:49 INFO]: Server: CraftBukkit git-Spigot-d
[17:21:49 INFO]: ------------------------------
[17:21:49 INFO]: Vault 1.5.6-b49 (ENABLED)
[17:21:49 INFO]: WorldEdit 6.1;no_git_id (ENABLED
[17:21:49 INFO]: WorldGuard 6.1 (ENABLED)
[17:21:49 INFO]: AsyncWorldEdit 2.2.2 (ENABLED)
[17:21:49 INFO]: Multiverse-Core 2.5-b699 (ENABLE
[17:21:49 INFO]: Multiverse-NetherPortals 2.5-b67
[17:21:49 INFO]: ------------------------------

I try create world manuály and plugin too. But, nether generated and islands not.

**Comment by dutchy1001** [comment]
The plugin generates the worlds you dont have to, by doing so you will not get the right setting for a world. If the settings are set right in the config then there is no problem and the plugin generates the world for you. If it's not generating the world something isnt right and it will not work

**Comment by MrFiliper** [comment]
uSkyBlock config looks fine. Please try it.

`
# The language used in the plugin (en is default).
language: cs
options:
  general:

    # [integer] The max number of players allowed in a single party. (including the leader)
    maxPartySize: 4

    # [integer] The time in seconds before a player can use the /island info command again. (note: cooldowns are reset when the plugin is reloaded)
    cooldownInfo: 60

    # [integer] The time in seconds before a player can use the /island restart command again.
    cooldownRestart: 2592000

    # [integer] The time in seconds before a player can use the /island biome command again.
    biomeChange: 180

    # [integer] The number of milliseconds between the same notification is sent to the player.
    # This is used when events are triggered heavily - i.e. item-pickup-prevention, damage-prevention etc.
    maxSpam: 2000

    # [string] The name of the skyblock world, will be automatically generated if it doesn't exist.
    worldName: skyworld

    # [integer] Area around 0,0 where islands will not be created to protect spawn.
    spawnSize: 416
  island:

    # [integer] The y-coordinate (height) where islands are spawned.
    height: 83

    # [integer] The number of blocks between islands.
    distance: 416

    # [integer] The size of the protective region for each island. Can't be higher than 'distance'
    # and MUST be divisible by 32 if you intend to use nether.
    protectionRange: 320

    # [filename] The schematic to use for island generation.
    # Put your schematic in the 'uSkyBlock/schematics' folder, you don't need to add the '.schematic' part below.
    schematicName: defaultisland

    # [true/false] If true, remove all hostile mobs when a player teleports back to their island.
    removeCreaturesByTeleport: false

    # [item list] The list of items to place in the chest when a player starts a new island. ITEM_ID:HOW_MANY.
    # default is 2 ice, 1 watermelon, 1 cactus, 1 lava bucket, 1 red & brown mushroom, 1 pumpkin seed, 1 sugar cane, 1 sign.
    chestItems: 50:1 0:1 0:1 79:1 79:1 79:1 0:1 0:1 50:1 297:1 0:1 0:1 0:1 327:1 0:1 0:1 0:1 297:1 0:1 362:1 0:1 6:1 6:1 6:1 0:1 361:1 0:1

    # [true/false] If true, add extra items to a chest when a player starts a new island. (for donors and special players)
    addExtraItems: false

    # [integer] The delay in seconds before teleporting to an island. Affects /is home, /is warp, /is spawn
    islandTeleportDelay: 0

    # Allow PvP on the island
    allowPvP: deny

    #[true/false] Allow players to completely lock their islands so non-party members can't enter. (locking still requires permission usb.lock)
    allowIslandLock: true

    # [true/false] If true, use island levels/ranks (/island info) - may have a slight impact on performance
    # Set to false if you have performance issues
    useIslandLevel: true

    # [true/false] Whether or not /is top should be available.
    useTopTen: true

    # [integer] The time in minutes for how often the top-ten list will be re-generated when doing /is top
    topTenTimeout: 20

    # [integer] The time in minutes for refreshing/recalculating the score for players on their island
    # set to 0 to disabled
    autoRefreshScore: 60

    # [true/false] Whether or not to include island-members on the top-ten scoreboard
    topTenShowMembers: true

    # [true/false] Whether or not to try and fix flat-land issues when players join the server
    # Note: will make the PlayerJoin event take longer.
    fixFlatland: false

    # The format used in /islandtalk chat messages
    chat-format: '&9SKY &r{DISPLAYNAME} &f>&d {MESSAGE}'

    # How many entries to remember in the island-log
    log-size: 10

    # Limits the spawning
    spawn-limits:

      # [true/false] if true, the limits below will limit spawning
      enabled: false

      # how many animals can be spawned within an island
      animals: 48

      # how many monsters can be spawned on an island
      monsters: 50

      # how many villagers can be spawned on an island
      villagers: 16

      # how many snowmen and iron-golems can be spawned on an island
      golems: 5

    # [permission] The name of the permissions to check if extra items are added to the chest, you can change these or add more
    # Only checked if 'addExtraItems' is set to true.
    # [permission:item list] The list of extra items to add to the chest, will only be added if the player has the permission. ITEM_ID:HOW_MANY
    # When granting the permission, prefix it with "usb." so the full permission to add would be usb.smallbonus
    extraPermissions:
      smallbonus: 4:16 320:5
      mediumbonus: 50:16 327:1
      largebonus: 3:5 12:5
      giantbonus: 2:1 110:1
      extremebonus: 352:8 263:4
      donorbonus: 261:1 262:32 272:1
  extras:

    # [true/false] If true, return players that don't have an island (this includes players removed from a party while offline), to the server spawn when they login.
    # NOTE: Requires EssentialsSpawn or another plugin with the "/spawn" command
    sendToSpawn: true

    # [true/false] If true, a player can right-click on a block of obsidian on their island while holding an empty bucket to remove the obsidian and fill the bucket with lava. This is useful for people that accidently
    # turn their lava into obsidian with a bad cobblestone generator design. Will only work on the player's island and if there are no other obsidian blocks nearby (so can't be used on portals).
    obsidianToLava: false

  # Contains flags for enabling PROTECTION of various mechanics.
  protection:

    # Whether or not, items dropped on the ground should be limited to party-members.
    item-drops: true

    # If true, only creepers targeting party-members will explode
    creepers: true

    # Whether or not the plugin will try to protect the player from accidentally extinguishing lava
    protect-lava: true

    # Whether or not portalling to the nether roof should be blocked.
    nether-roof: true
    visitors:

      # Protect visitors from trampling your crop
      trampling: true

      # Protect against visitors attacked animals
      kill-animals: true

      # Protect against visitors attacking monsters
      kill-monsters: true

      # Protect from shearing
      shearing: true

      # Protect from villager-trading
      villager-trading: true

      # Whether or not visitors are protected from fall damage
      fall: true

      # Whether or not visitors are protected from fire damage (incl. lava)
      fire-damage: true

      # Whether or not visitors should be allowed to drop items
      item-drops: true

      # Warns online members when a player visits the island.
      warn-on-warp: true

      # Whether or not to actively block banned players from entering an island (by walking/flying).
      block-banned-entry: true

      # Whether or not visitors can use portals (default: false)
      use-portals: false
  party:

    # The number of ticks before an invite timeouts (20 ticks per sec.)
    invite-timeout: 600

    # The format used in /partytalk chat messages
    chat-format: '&9PARTY &r{DISPLAYNAME} &f>&b {MESSAGE}'

  # This section provide some performance tweaking configs
  advanced:

    # If true, display-name is looked up (might be performance intensive).
    useDisplayNames: false

    # [number] The threshold for purging islands.
    # any island with a level above this, is spared.
    purgeLevel: 10

    # [seconds] The number of seconds for confirming a command by
    # re-executing it (/is leave, /is restart).
    confirmTimeout: 10

  # Section about restarting your island (or accepting an invite).
  restart:

    # Clears the player's inventory on island create/restart
    clearInventory: true

    # Clears the player's armor on island create/restart
    clearArmor: true

    # Clears the player's enderchest on island create/restart
    clearEnderChest: true

    # [ticks] The number of ticks to wait, before porting the player back
    # on /is restart or /is create (default: 40)
    teleportDelay: 20

    # [true/false] Whether or not the player should be auto teleported to the island when it's ready
    teleportWhenReady: true

    # list of commands to execute after island-creation
    # i.e.
    # - me Jumps with &ajoy
    extra-commands: []

# List of selections for /is create and /is restart
island-schemes:
  uSkyBlockDefault:
    permission: usb.island.create
    name: Default
    displayItem: SAPLING
    extraItems: ''
    maxPartySize: 4
    animals: 48
    monsters: 50
    villagers: 16
    golems: 5
  uSkyBlockSkySMP:
    permission: usb.schematic.skysmp
    name: SkySMP
    displayItem: GRASS
confirmation:

  # [true/false] Whether to require confirmation (i.e. repeating the command twice).
  is leave: true

  # [true/false] Whether to require confirmation (i.e. repeating the command twice).
  is restart: true
asyncworldedit:

  # Supports disabling the detection of AWE
  enabled: true

  # Show progress to the user every 5 seconds
  progressEveryMs: 5000

  # Or 20pct (what-ever comes first)
  progressEveryPct: 20
  watchDog:

    # The maximum time to wait for AWE paste to complete (2m, 3m20s, etc.)
    timeout: 5m

    # The number of ms between each heartbeat
    heartBeatMs: 2000
worldguard:
  entry-message: true
  exit-message: true
nether:
  enabled: true
  terraform-enabled: true

  # The distance to search for valid terra-form location.
  terraform-distance: 7
  height: 75
  lava-level: 32
  activate-at:
    level: 100
  schematicName: uSkyBlockNether

  # The probability of forming blocks
  terraform:
    NETHERRACK:
    - '{p=0.7}NETHERRACK'
    - '{p=0.15}NETHERRACK'
    - '{p=0.05}QUARTZ_ORE'
    - '{p=0.05}SOUL_SAND'
    QUARTZ_ORE:
    - '{p=0.50}QUARTZ_ORE'
    - '{p=0.10}QUARTZ_ORE'
    SOUL_SAND:
    - '{p=0.70}SOUL_SAND'
    - '{p=0.10}SOUL_SAND'
    GRAVEL:
    - '{p=0.60}GRAVEL'
    - '{p=0.10}GRAVEL'
    - '{p=0.05}SOUL_SAND'
    GLOWSTONE:
    - '{p=0.85}GLOWSTONE'
    - '{p=0.15}GLOWSTONE'
  spawn-chances:
    enabled: true
    wither: 0.2
    skeleton: 0.1
    blaze: 0.2
tool-menu:
  enabled: false
  tool: SAPLING
  commands:
    CHEST: island
    BEDROCK: island spawn
    WORKBENCH: challenges

# DO NOT TOUCH THE FIELDS BELOW
version: 43
`

And multiverse world.yml

`  skyworld_nether:
    ==: MVWorld
    hidden: 'false'
    alias: ''
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '8.0'
    respawnWorld: ''
    allowWeather: 'true'
    difficulty: EASY
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
      currency: '-1'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 0.0
      y: 0.0
      z: 0.0
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NETHER
    seed: '-415676779997991075'
    generator: uSkyBlock
    playerLimit: '-1'
    allowFlight: 'true'`

This generate plugin.

**Comment by MrFiliper** [comment]
uSkyBlock config is here: http://pastebin.com/HLEmhmXH But, it looks fine.

And multiverse world.yml too: http://pastebin.com/xLWgMifY

This generate plugin.

**Comment by dutchy1001** [comment]
> I try create world manuály

is were it goes wrong, let the plugin do it's job, not you
You need delete the skyworld_nether and restart the server. If you already have a skyworld all island in there will not have an nether island untill they restart, if it works at all that way. Mostly both worlds need to be created at the same time, that is the best senario you can get.

**Comment by MrFiliper** [comment]
And if I have one world more than the nether world, nether islands will not work ?!

**Comment by dutchy1001** [comment]
I don't get that answer.

**Comment by MrFiliper** [comment]
Please tell my more about this problem. R4? You dont have answer?

**Comment by rlf** [comment]
It seems to me, if I understand your English correctly, that you expected the nether-island to be generated on portal creation.

This is not the case.

The nether-island is generated when the overworld-island is generated, i.e. on `/is create` or `/is restart`.

If nether is deactivated due to some misconfiguration, uSkyBlock will write this in your server-log.

If nether is enabled, you should be able to see the nether-island, once you create a new island, after the enablement of the nether.

**Comment by MrFiliper** [comment]
Can create commnd, when player hasnt island. Nether island created? Or, if player go to portal, and player hasnt nether island, generate it?

**Comment by dutchy1001** [comment]
I'm almost to scared to ask, but what is the server address so I can see myself what is going on....

**Comment by MrFiliper** [comment]
skyblock[.]woblex[.]cz

**Comment by dutchy1001** [comment]
Ok we found the cause, BIG WASTE OF TIME, 
If you compile yourself then tell us that from the start.
Unless using provided jars i will not give any help anymore.

**Comment by rlf** [comment]
Just visited your server MrFiliper. And I now know what your issue is.

As stated above, the nether island is not created on teleport creation.
We are how-ever considering adding a "generate missing nether islands" to the admin commands.

The only issue you seems to be having, can be summarized in this sentence:
"Nether islands are not generated on teleport creation, meaning existing islands won't have a nether island". Which is 100% true - as stated in the various release notes since v2.5.
