### ISSUE TITLE
Can´t install uSkyblock

### ISSUE THREAD

**Issue by Cavilos** [rlf/uSkyBlock#645]
Hey, I also have an problem. I get an error when i try to start my Server. [http://pastebin.com/HpzV1yk4](url)

I clean the Server only upload Vault, MV, Worldedit, Worldguard and uSkyBlock from all the newest version. 

The complete log: [http://pastebin.com/3HRDnmKD](url) 

I hope you can help me

**Comment by dutchy1001** [comment]
so instead of waiting to an answer on bukkit you start here now
