### ISSUE TITLE
Task #7572 for uSkyBlock v2.6.1 generated an exception

### ISSUE THREAD

**Issue by swan201** [rlf/uSkyBlock#647]
2.6.1 have some error?

http://pastebin.com/BjnvfXmA

**Comment by rlf** [comment]
First off, thank you for an issue-report that is both short, and precise!
With `/usb version` incorporated.
If only every reporter did as you.

Question: Do you have nether enabled?

**Comment by BlackBeltPanda** [comment]
Fixed for me in the latest commit. =)

**Comment by dutchy1001** [comment]
Closing this as BlackBeltPanda already tested this.
