### ISSUE TITLE
Restart GUI not displaying on "/is restart" command

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#650]
In v2.6.1, restarting an island using "/is restart" doesn't display the island selection GUI for my players. Using the main "/is" GUI to restart the island does. Most of my experienced players use commands instead of the GUI so they don't get a chance to see the selection menu.

**Comment by dutchy1001** [comment]
the GUI doesnt show up when using the command /is restart, for now it works from the main GUI /is and click the podzol block.You need to click twice the "schematic" block 1 to select, 2 to confirm.

**Comment by rlf** [comment]
If you use commands, you can supply the schematic as 3rd argument.
It supports tab-completion as well.
```
/is restart - will give you the default island (options.island.schematicName)
/is restart TheBigOne - will give you TheBigOne, provided you have permissions for it
```

**Comment by rlf** [comment]
I personally, dislike too many GUIs popping up, when I use commands :)
But we could change so `/is restart` shows the UI, instead of executing the default schematic.

If there's a general wish for this to happen?

**Comment by dutchy1001** [comment]
I am "for" to have the ```/is restart``` opening the restart GUI. This will stop the confusion on how to get a different island then default.

**Comment by BlackBeltPanda** [comment]
The confusion with my players seems to be how to properly set their island schematic. I noticed today that several players have been doing the following:

1. Open /is GUI
2. Select Restart Island
3. Select Island Schematic
4. Close menu and run "/is restart"
5. Complain that their island didn't change

They seem to be under the impression that restarting with the command after selecting the island is what they're supposed to do. O.o

**Comment by dutchy1001** [comment]
You could add an extra lore (but it didnt look as nice in my oppinion) to the description or change the "countdown" line with the translation system as I just did
![2016-03-05_16 43 05](https://cloud.githubusercontent.com/assets/5569980/13548857/9ef45d6c-e2f1-11e5-94cd-b6f5d8d7eeb7.png)

**Comment by rlf** [comment]
v2.6.4

**Comment by dutchy1001** [comment]
The command /is restart will bring up the island GUI now.

**Comment by BlackBeltPanda** [comment]
Working great, thank you! =)
