### ISSUE TITLE
Order option for island selection GUI

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#651]
Would be great if there was an option to specify which schematic icon would appear in which slot in the island schematic selection GUI. Since I have schematics for each rank on my server it looks off when the schematics are not in the same order as my ranks. Alternatively, loading them in the same order they appear in the config.yml file would work, as well.

**Comment by dutchy1001** [comment]
I know what your saying, and you have a point there with the amount of islands you got lol. 
It would be nice to have it custom setup.

**Comment by rlf** [comment]
They are currently ordered on their schematic name.
This is done, because we also support schematics just dropped in the folder.
If you want them orderered, just rename the schematics to your need.

**Comment by BlackBeltPanda** [comment]
I'm not sure how I could rename mine without confusing my players. I'd have to do something like:
"avip, bgenin, chunin, djonin, etc." instead of "vip, genin, chunin, jonin, etc."

Also, in regards to the default schematics (SkySMP, uSkyBlockNether, and default), is there any way to prevent those from displaying automatically in the GUI?

**Comment by dutchy1001** [comment]
you could number them:
10 - vip
11 - genin
12 - chunin
13- jonin
next rank will then:
20 - vip
21 - genin
22 - chunin
23- jonin
this way you could set 10 ranks with each 10 islands

**Comment by BlackBeltPanda** [comment]
I'll try that, thanks. =)

**Comment by rlf** [comment]
Reg. the "default schematics", for now, just remove them

Reg. ordering etc. I think I will allow you to re-order them in the `island-schemes` section.
Just not sure how to go about that, but I'll find a way :D

**Comment by rlf** [comment]
Btw. please tell me you do not have more than 51 schematics! (Not really keen on making a pagination for that screen).

**Comment by BlackBeltPanda** [comment]
Thanks =)
I only have about 22 schematics =P

**Comment by rlf** [comment]
Related issue #669

**Comment by rlf** [comment]
Part of v2.6.2 (for 1.9)

**Comment by BlackBeltPanda** [comment]
Ordering and disabling island schematics in the selection GUI is working great for me in the latest version. =D

**Comment by dutchy1001** [comment]
This can now be closed then as I can confirm it working properly too
