### ISSUE TITLE
Random NullPointerException in ChunkSnapShotTask

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#652]
Seeing this pop up in my console randomly in v2.6.1: http://pastebin.com/raw/frtAwHz3

**Comment by swan201** [comment]
same this issue https://github.com/rlf/uSkyBlock/issues/647

**Comment by BlackBeltPanda** [comment]
Ah, I didn't see that report. Since rlf was asking on that one, I have the uSkyBlock nether disabled in my config.

**Comment by rlf** [comment]
Ok, marking as duplicate of #647
