### ISSUE TITLE
Checking if player have island or in an island or is a member of an island

### ISSUE THREAD

**Issue by Banbeucmas** [rlf/uSkyBlock#655]
I checked the Api but found out there is nothing about checking player has an island or not, may be consider adding this to the api

like

hasIsland(); //return boolean
isLeader(); // return boolean

**Comment by rlf** [comment]
I think we can do it a bit better.

Let's introduce a public interface for `IslandInfo`, and expose that in the API.
See https://github.com/rlf/uSkyBlock/blob/master/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/island/IslandInfo.java

**Comment by Banbeucmas** [comment]
Found it, you mean this method?


    public boolean isLeader(Player player) {
        return isLeader(player.getName());
    }

**Comment by rlf** [comment]
Part of v2.6.4 - see http://rlf.github.io/uSkyBlock/apidocs/us/talabrek/ultimateskyblock/api/uSkyBlockAPI.html

**Comment by dutchy1001** [comment]
Has anyone tested this API feature yet??
