### ISSUE TITLE
How to customise the Language for uSkyBlock

### ISSUE THREAD

**Issue by PinoyLifeCraft** [rlf/uSkyBlock#658]
Hellow guyz its just an Question on :
How to customise my uSkyBlock translation because i see fail  message like :
Trying to complete challenge &aCobble Stone Generator
You have complete the &aCobble Stone Generator challenge!
Player has complete the &aCobble Stone Generator challenge!
-----The color code :cry: !!!!-----
and i like to custom it with my own message :pray:  Please

**Comment by dutchy1001** [comment]
Depending on your version this will be fixed in the next release.

**Comment by PinoyLifeCraft** [comment]
But how about the custom messages with our own Creations this will be so awesome if this happen like the other plugins it support locale..... right?

**Comment by dutchy1001** [comment]
You can customize any text i the plugin through the "gettext" system. An explanation can be found [here](http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/localization/) on bukkit.

**Comment by PinoyLifeCraft** [comment]
My god i really don't know that?
and i don't understand it sorry :disappointed_relieved:

**Comment by dutchy1001** [comment]
What don't you understand about it?
Get the program with the provided link, get the files from the provided links and start translating/customising the lines.
This is a better and more robust system then a messages.yml, even the menu's can be translated this way.

**Comment by PinoyLifeCraft** [comment]
Sorry don't be angry ok i will try it :fearful:

**Comment by dutchy1001** [comment]
no worries I'm not angry, why should I?
Have a good read through it and maybe Google some things you don't understand. When using the right program (recommended PoEditor, it's free) you will see it's very easy to do.

**Comment by PinoyLifeCraft** [comment]
How about [THIS](https://github.com/rlf/uSkyBlock/wiki/Custom-Messages) i don't know this i try everything i know still not worki

**Comment by dutchy1001** [comment]
All the info you need is in the page I linked in my previous message. The page you mentioned is outdated and is now deleted. 
It's really simple, follow these steps:

1. Download PoEditor from [here](http://poedit.net/)
2. Install PoEditor
3. Download the orginal text from [here](https://raw.githubusercontent.com/rlf/uSkyBlock/master/uSkyBlock-Core/src/main/po/keys.pot) and "save as" **keys.pot**
4. Open your just installed PoEditor and browse to the location you saved the keys.pot file  
 * (click **File** -> **new from POT/PO file...**)
5. Follow instruction in PoEditor to start translating

**Comment by PinoyLifeCraft** [comment]
How do i download the step 3 :question:

**Comment by dutchy1001** [comment]
Ok I made it easier for you, you can download from [here](https://www.dropbox.com/s/ttd9aijslmkrmf7/keys.pot?dl=0) (each update will need a new key.pot file as text will be updated with new entries or deleted lines).

Normaly you copy the page and save it with Notepad, Notepad++ or similar text editor and use "save as" and name it **keys.pot**.

**Comment by PinoyLifeCraft** [comment]
w3w thank the reason why i ask you the step 3 because i get error :3
i copy all the text in that page and paste it to the empty notepad and save it as keys.pot
but after i edit it with poedit bruhh error encounter :disappointed: 
hehe thanks !

**Comment by PinoyLifeCraft** [comment]
i edit it already and save it to my plugin/uSkyBlock folder is that right?

**Comment by dutchy1001** [comment]
you save it to \plugins\uSkyBlock\i18n folder. 
The **i18n** folder needs to be created. After creation place the **[language code].po** file there

**Comment by dutchy1001** [comment]
After you translated your file, reopen it with notepad++ and post it through pastebin with a link here. I can then check if the file is OK (meaning, the right format only as I probably do not understand your language :smile: ).

**Comment by PinoyLifeCraft** [comment]
Thanks it works!
![yeah](https://cloud.githubusercontent.com/assets/13610530/13024019/cd1a83e4-d24b-11e5-9d30-24d5b0696575.png)
Here are my unfinished work !
![2016-02-13_08 17 51](https://cloud.githubusercontent.com/assets/13610530/13024034/08303f50-d24c-11e5-9e91-4e0e0bdb7b70.png)
Hehe for honestly i will not translate it to Filipino i will just make my own custom message :laughing:

**Comment by dutchy1001** [comment]
ok glad you got it to work.
I presume I can close this issue now you know how to use the translation/editing messages works.

**Comment by PinoyLifeCraft** [comment]
Hehe thank you very much you help me Good bye to this Issue :P
