### ISSUE TITLE
Exception thrown during refresh

### ISSUE THREAD

**Issue by PinoyLifeCraft** [rlf/uSkyBlock#661]
What is happening to my skyblock?
  ----->   http://pastebin.com/sihYuGdC

**Comment by dutchy1001** [comment]
each bug report should have the output of the command /usb version.

**Comment by PinoyLifeCraft** [comment]
Name: uSkyBlock
 Version: 2.5.7
 Description: Ultimate SkyBlock v2.5.7-03f5db-391
 Language: tl (tl)
 ------------------------------
 Server: CraftBukkit git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
 ------------------------------
 Vault 1.5.6-b49 (1.5.6-b49)
 ------------------------------
 WorldEdit 6.1;no_git_id (6.1;no_git_id)
 ------------------------------
 WorldGuard 6.1 (6.1)
 ------------------------------
 Multiverse-Core 2.5-b711 (2.5-b711)
 ------------------------------
 Multiverse-Portals 2.5-b726 (2.5-b726)
 ------------------------------

**Comment by dutchy1001** [comment]
Is the error happening when using the default English (en) language file?
If you post the tl language file through pastebin I can check the format and if error free add it to the plugin.

**Comment by PinoyLifeCraft** [comment]
Wait i turn my lang. to en just give me a few days to experiment it :pray:  Please!

**Comment by dutchy1001** [comment]
no problem, take as long you need :)

**Comment by PinoyLifeCraft** [comment]
I receive the error when that player join i think :smiley: so!
the name of that player is delighten
Plugin Permission : (GM) Group Manager
Player Prefix : "&4&lA&4bandoned &3&lV.I.P &7: "

**Comment by dutchy1001** [comment]
I assume this has been a glitch due to previous language settings. If it happens again plz make sure to see if console is free of errors, if not post them plz.

Closing this for now. If needed we can reopen this again.
