### ISSUE TITLE
Handle special UUIDs for Non-Player objects on modded servers

### ISSUE THREAD

**Issue by ProsperCraft** [rlf/uSkyBlock#662]
Modded skyblock - com.rwtema.extrautils.block.BlockSpikeDiamond

http://pastebin.com/FhK2qy69   - Console spam

Version -  uSkyBlock (2.5.3-bukkit-1.7.9)

In modded skyblock(Project Ozone pack in the curse launcher) there are three blocks that kill mobs when they touch them and do it in a way that they get the loot that the player would get if they had killed it, they are the gold spike, iron spike and diamond spike.

http://ftbwiki.org/Iron_Spike

Are you able to add it to the things that are allowed to bypass protections?

**Comment by rlf** [comment]
Accepting and renaming the issue.

PlayerLogic should be able to handle the special UUID "c1fc3ace-e6b2-37ed-a575-03e0d777d7f1", which means "invalid offlineplayer-name".
In other words, it should return a dummy-playerinfo, that has no island, and thus will never be trusted, banned or anything on any islands, enabling the grief-prevention to handle mobdamage etc. on modded servers.

**Comment by ProsperCraft** [comment]
Thank you, you are awesome!

**Comment by rlf** [comment]
Ready in v2.6.4

**Comment by dutchy1001** [comment]
@ProsperCraft 
It would be nice if you can test this as you requested it. 
I don't have a modded server.
Thx in advanced.

**Comment by ProsperCraft** [comment]
Uploading now.

**Comment by ProsperCraft** [comment]
2.6.4 doesn't seem to work with 1.7.10 commands will not work, when you type a command it just shows you "/island [restart/sethome/info/level/lock/unlock/top/party]

regardless of what you type.

Almost all modded servers are still running 1.7.10 as the mods are still porting to 1.8.9.

**Comment by dutchy1001** [comment]
I'm sorry I wasn't aware this is still on 1.7.10 versions (I think we both, rlf and me, missed this).
The version v2.6.4 is for 1.9 servers and will not work properly on 1.7.x servers (as you found out the hard way).
I'm not sure if rlf will work on the older v2.5.3 version but that is something will tell you himself.

**Comment by rlf** [comment]
Well, I could give a 1.7.9 port a final stab... though... I'd rather not :(

**Comment by ProsperCraft** [comment]
Skyblock is going to get very popular in a few weeks because FTB is releasing FTB Infinity Evolved skyblock.

**Comment by dutchy1001** [comment]
any link to this?

**Comment by ProsperCraft** [comment]
They will use a map and server owners like myself will use your plugin to provide players with a playable multiplayer experience with protections and automated skyblock generation.

**Comment by dutchy1001** [comment]
Then it's up to rlf as he is our main developer.

**Comment by dutchy1001** [comment]
as support for 1.7.x has been cancelled this issue can be closed.
