### ISSUE TITLE
User is not able to change biome type on island.

### ISSUE THREAD

**Issue by Ranger1x** [rlf/uSkyBlock#664]
Hello, the users on my server are not able to change the biome type.  I have made sure that they have all the permissions that they need to fulfill changing the biome type.  Any help would be greatly appreciated.

**Comment by dutchy1001** [comment]
First off, post the output of /usb version. 
Second, what perms do you give the players

**Comment by Ranger1x** [comment]
I tried doing /usb version.  All it gave me is this.  I can not even access the GUI.
![screen shot 2016-02-15 at 9 14 32 am](https://cloud.githubusercontent.com/assets/16735417/13052459/94efa240-d3c4-11e5-9174-a324acfe0c22.png)

**Comment by dutchy1001** [comment]
then you need to manual give me those, or post a startup log through pastebin.

**Comment by Ranger1x** [comment]
[2016-01-02-1.log.gz](https://github.com/rlf/uSkyBlock/files/131186/2016-01-02-1.log.gz)

**Comment by dutchy1001** [comment]
I need a more up to date log this one is 2 weeks old. Also plz use [pastebin](http://pastebin.com/) to post logs. 
This log doesn't load the uskyblock plugin nor it's depended plugins

**Comment by Ranger1x** [comment]
http://pastebin.com/EJVtsDKu

**Comment by dutchy1001** [comment]
There are a lot of issue's in your log which should be taken care of first. This will then eliminate other plugins to cause trouble. 

- Couldn't load server icon 
   - this should be a png from 64 x 64
- Ambiguous plugin name `EssentialsChat' 
  - meaning there are 2 the same file, delete 1
- Error occurred while enabling EssentialsSpawn v2.13.1
   - Wrong version comapare to the other Essentials plugins. Use all the version sets from [here](http://ci.drtshock.net/job/essentialsx/)
- Multiverse_Spawn
   - might conflict with Essentials-Spawn, either have 1 or the other, both might clash (I'll stick with Essentials if I was you)

You are using Essentials plugins from 2 different sources, you should stick with 1 source and use all add-ons from that then. Use the link above to get all Essentials from 1 source.

I would suggest to update the uSkyblock to version v2.5.7 or our github release v2.6.1.
If you use the bukkit page I can also suggest to use the latest dev builds for WorldEdit, WorldGuard and Multiverse. All links can be found on this page [here](http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/installation/). All dev builds links are save to use, I use them myself.

When this is all fixed and updated see if you still have the problems. If so, report back with a startup log.
If all working plz also report back the good news so we can close this issue.
