### ISSUE TITLE
Any public void resetIsland()

### ISSUE THREAD

**Issue by Banbeucmas** [rlf/uSkyBlock#665]
Is there anyway to reset island using method?, there should be lol *Since i checked the API

**Comment by dutchy1001** [comment]
Not sure what you mean here. There are several commands that can be used to reset an island
* User command 
 * **/is restart** or **/is reset**
 * **/is makeleader [_orginal owner_] [_new owner_]**
   * changes the owner but player still need to leave with command(**/is leave**) 
* admin command 
 * **/usb island remove [_player_]**
   * removes a player from island so he needs to create a new island (you can register a new owner to this island with **/usb island register [_player_]**)
 * **/usb island delete [_player_]**
   * deletes the island and the location is added to the orphan.yml for re-use for a new player.
 * **/usb is makeleader [_orginal owner_] [_new owner_]**
   * changes the owner but player still need to leave with command(**/is leave**) 

If this isn't what you meant then you have to wait till R4zorax is back next week.

**Comment by Banbeucmas** [comment]
Well, i need that for my plugin so...

**Comment by rlf** [comment]
Curious @Banbeucmas what are you trying to accomplish from your plugin?

**Comment by Banbeucmas** [comment]
Like this 
my server have a custom class system plugin 
so when a player choosing a new class it will reset their island
if the player is not the leader of that island it will make them to leave the island

i am tired of using /is restart twice in my command 
and plus some of my plugin *in the feature, i am abandoned it* will need the islandreset() method to make it do the job

I know that the config can turn the /is restart twice thingy but some of my plugin will be public so it wont be so powerfull when we need to restart the island twice like that

**Comment by dutchy1001** [comment]
Dont think this went any further in development from banBeucmas, if so then we can reopen this.
