### ISSUE TITLE
Player does not respawn at Essentials's Spawn after death.

### ISSUE THREAD

**Issue by Victhetiger** [rlf/uSkyBlock#666]
Hi,

I have a small issue with the latest version of both spigot and the plugin, they respawn in the my Island world's 0,0 coordinate. I do not want that, I want them to respawn in the Spawn world.

Sincerely,
Victhetiger

**Comment by dutchy1001** [comment]
set in the config ```sendToSpawn: false``` to **true**

Make sure you got EssentialsSpawn or another plugin with the **/spawn** command instaled

**Comment by Victhetiger** [comment]
Does /usb reload reset the config? Because it was set to true until I reloaded the plugin.

**Comment by dutchy1001** [comment]
yes /usb reload reloads the config, but if you can restart the server that is always better (but that count for most plugins)

**Comment by Victhetiger** [comment]
Alright, I'll reply to this thread once I'll be able too.

**Comment by Victhetiger** [comment]
That worked succesfully, thank you for the quick support.

**Comment by dutchy1001** [comment]
no probs
closing issue
