### ISSUE TITLE
NullPointerException after creating an island

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#668]
After a player created an island, these errors started spamming the console (version info included):

http://pastebin.com/raw/mazMYt4w

There's about 30,000 lines of those errors.

**Comment by rlf** [comment]
Caused by the specific versions of TitleManager and AWE.
Needs investigation.

**Comment by dutchy1001** [comment]
I have also notest that when creating/restarting an island while using AWE (using the "we-snapshot-3409" version included in the premium v3.2.3) it will keep spamming messages until restart of the server.
See pastebin for 1 of those logs [here](http://pastebin.com/SYAKPVHc)

**Comment by rlf** [comment]
That pastebin sounds like a dev-build for AWE... at least it spams quite a lot - perhaps a config issue with AWE?

**Comment by dutchy1001** [comment]
yes, it's a dev build added with the 2.3.2 version to be compatible with WE  dev build 3409. I'm aware this is more an AWE issue then for us. But as you mentioned Tittlemanager and AWE it might help to know that AWE isn't perfect here and can be the cause of other issue's.

**Comment by rlf** [comment]
Is it a Bungee server @BlackBeltPanda ? And is it running in offline or online mode?

**Comment by BlackBeltPanda** [comment]
Bungee server. Bungee proxy's online, skyblock server's offline.

**Comment by BlackBeltPanda** [comment]
This seems to be fixed. =)
