### ISSUE TITLE
Can't remove default schematics from restart GUI

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#669]
> Name: uSkyBlock
Version: 2.5.0-SNAPSHOT
Description: Ultimate SkyBlock v2.6.1-11-g7391843-739184-dev
Language: en (en)
------------------------------
Server: CraftBukkit git-PaperSpigot-428 (MC: 1.8.8)
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.1-SNAPSHOT;3394-9a65bdb7 (ENABLED)
WorldGuard 6.1.1-SNAPSHOT.1629-0fcd42f (ENABLED)
AsyncWorldEdit 3.2.2 (ENABLED)
Multiverse-Core 2.5-b693 (ENABLED)
Multiverse-NetherPortals 2.5-b702 (ENABLED)
------------------------------

The default schematics, "default" and "SkySMP", reappear in the uSkyBlock folder after being deleted. I stopped the server, removed the schematics, and started the server again and they re-appeared. Since I don't use those schematics it's a bit confusing for my players when they want to restart with my default island schematic called "normal". For now, I've added them to the config in island-schemes to give them a required permission node that my players don't have. This prevents them from being used but still causes some confusion when players mistake "default" for "normal".

**Comment by dutchy1001** [comment]
There is a fix for this implemented already. 
Due to the fact that when ever you restart the server the configs will be checked and when found different then the original it will reset it to that. This means whenever you delete the default island, it will be re-added on restart or reload as it is then missing from the config.
You need to add this fix to your config.yml as followed:
```
# this will ignore a the changes from updating
merge-ignore:
  - 'island-schemes'
```
The default islands still might appear in the schematics folder but should not show up any more in the GUI.
You can place this on the top of the config or just above the island section.
If it doesn't work let me know.

PS. I'm away till Saturday.

**Comment by BlackBeltPanda** [comment]
Thanks for responding =)

The problem isn't that they end up in "island-schemes" but that users are seeing them in the restart GUI even when they're not in the "island-schemes" section. Since I can't delete them from the schematics folder, I had to add them to "island-schemes" with a permission node that players don't have to prevent them from using those schematics. However, I can't seem to prevent them from displaying in the GUI completely.

**Comment by dutchy1001** [comment]
What if you set the "displayItem" to air?

**Comment by BlackBeltPanda** [comment]
If I set it to "AIR", it remains set as a grass block in the GUI after a server restart.

**Comment by rlf** [comment]
Should be addressed in #651 Closing this for now.

**Comment by YellowShmello** [comment]
Even though it's been awhile since this was made, I have the same problem. I researched through several threads but couldn't come up with a clear answer on removing default islands. If I could get a specific answer to this, I would really appreciate it. Thank you.

**Comment by rlf** [comment]
A rather obvious necro.
You could just read the ```config.yml```
Specifically this line: https://github.com/rlf/uSkyBlock/blob/master/uSkyBlock-Core/src/main/resources/config.yml#L255
