### ISSUE TITLE
New method on island-level (request) Integer

### ISSUE THREAD

**Issue by Darkool** [rlf/uSkyBlock#670]
Hi, most of plugins use your api to show island level(Featherboard, Leader Heads, etc). By the moment all plugins get a double value, It's possible use skyblock source code to change island level value to integer? where Is the file that we need to change, thanks.

**Comment by rlf** [comment]
Yes. But why would you want that?
You can simply display it as an integer instead of as a double?

If you have a concrete need/example where you need it as an integer, I might be able to help you.

**Comment by dutchy1001** [comment]
No further input made here.

If there is a concrete example then we can reopen this or a new issue cane be made.
