### ISSUE TITLE
Portals in the skyworld not working

### ISSUE THREAD

**Issue by kalaxal** [rlf/uSkyBlock#671]
Name: uSkyBlock
Version: 2.5.3-bukkit-1.7.9
Description: Ultimate SkyBlock v2.5.3-bukkit-1.7.9-da7f04-383
Language: en (en)
Server: KCauldron 1.7.10-1517.167 (MC: 1.7.10)
Name: Vault (ENABLED)
Version: 1.5.6-b49
Name: WorldEdit (ENABLED)
Version: 6.1;no_git_id
Name: WorldGuard (ENABLED)
Version: 6.1

We are running the new 2.4 version of Skyfactory

We are running a server and for some reason in the skyworld only nether portals do not work, They will not light at all. We also have an issue with End Cake people can eat it like candy and that should not work. These all work in all other dimensions.

**Comment by SgtLegoTown** [comment]
i know there are some problemen supporting KCauldron did you try to use Multiverse-Core or Multiverse portals that the portal will not  be activated i cant image that that is course`d by uskyblock. i tryied to reproduce this since dutchy isnt available i get many problems but i can activate the portals

**Comment by kalaxal** [comment]
The reason I suggest it is uSkyBlock is because the portals work in the main world and the last millennium I am looking for other options but I need something that players can make themselves. I can probably get someone access if they can help.

**Comment by SgtLegoTown** [comment]
are there other plugins u use that can couse it becouse uskyblock shouldnt and so far i can  see cant even block portals from be lighted ..

**Comment by SgtLegoTown** [comment]
i was wondering u use Vault 1.5.6 isnt it that 1.4.1 is the version needed for 1.7.x ?
and also missing the Multiverse-core / multiverse nether Portals in your list

**Comment by kalaxal** [comment]
Good catch on Vault I changed that but I still can't light portals in the skyworld. As for the plugin list that is just what usb version gave me here is a list of all plugins on the server http://puu.sh/nf0Yu/c93064fb15.png and the all load and seem to work as far as I can see

**Comment by SgtLegoTown** [comment]
did you add the skyworld in the multiverse worlds.yml ?

**Comment by SgtLegoTown** [comment]
i did some more research also check : essentials protect, under protect is general physics/behaviour medications section. portal-creation can be changed from true to false.

**Comment by rlf** [comment]
We do not meddle with portal creation or lightning.

Most likely this is caused by some WorldGuard incompatibilities or other plugins (i.e. PvP plugins) blocking the use of flint and steel.

**Comment by kalaxal** [comment]
Yes skyworld is in the mv config and portals are on, the setting for antigreif portals are on. I have been searching debugging this for over a week now. I have checked flint and steel and many other things none of these helped and as I said in the other worlds portals work and I have made sure that the region flags are the same. 

I did test by creating a new world and portals don't light there properly either. I did find out though that it does seem to be related to multierse because when I was finaly able to set a selection to a portal and light it it did create but I am having issues with where it outputs you but i am still testing. I would like to keep this topic open for now if you all do not mind. In case someone here might have any ideas.

Also is MultiVerse required for this plugin it looks like it is but just want to check

**Comment by SgtLegoTown** [comment]
Required dependencies are:
•WorldEdit v6.xx (get it here, or click here for Dev builds) 
•WorldGuard v6.xx (get it here, or click here for Dev builds) 
•Vault v1.5.x (get it here)

•Multiverse-Core (versions above v2.5) (get it here, or click here for Dev builds)


Highly recommended dependencies are (needed for the nether versions): 
•Multiverse-Portals (versions above v2.5) (get it here, or click here for Dev builds) 
•Multiverse-NetherPortals (versions above v2.5) (get it here, or click here for Dev builds) 

Soft dependencies are:
•Chest Commands GUI (get it here) 

from the bucket page

**Comment by kalaxal** [comment]
Yes I read that but I see the space and I wondered if I missed something
