### ISSUE TITLE
Challenges cooldown before they can be redone.

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#673]
A request, made on the bukkit page, for challenges cooldown before they can be redone. 
Not like the "ResetinHours" we already have for the "general" group/challenge to be reset to default "needed" items but simular as the E.G. the restart cooldown or biome-change cooldown we already have.
Adding a cooldown can also limit the abuse for easy challenges.

**Comment by rlf** [comment]
We already have quite some confusion reg. the meaning of the cooldown.
I think adding yet another might only enhance that confusion, but hey, let's see what happens.
