### ISSUE TITLE
Top 10 and Ranking when using reload

### ISSUE THREAD

**Issue by PinoyLifeCraft** [rlf/uSkyBlock#674]
Hellow owner :laughing: 
When im doing /is top it's work perfectly !!!
![2016-02-21_18 48 36](https://cloud.githubusercontent.com/assets/13610530/13216190/d23849ac-d9b6-11e5-95f7-45d4b45a53c5.png)
And when im doing /is plus clicking my SkyBlock Level is working perfectly !!!
![2016-02-21_18 53 32](https://cloud.githubusercontent.com/assets/13610530/13216243/14ae32ba-d9b7-11e5-9459-0f8284175356.png)
But when i Reload the uSkyBlock
![2016-02-21_18 55 25](https://cloud.githubusercontent.com/assets/13610530/13216291/6833a2a8-d9b7-11e5-8171-10586b5b65cd.png)

**Comment by PinoyLifeCraft** [comment]
And my Close Issue Enter and Exit Message is still not working!
![2016-02-21_19 00 29](https://cloud.githubusercontent.com/assets/13610530/13216414/138b23c4-d9b8-11e5-8981-3e8d032fa363.png)

**Comment by PinoyLifeCraft** [comment]
I told her to give her account to test! - Maintenance :blush:

**Comment by dutchy1001** [comment]
can you post the output from "/usb version" as I can keep up with everybody's use of versions.

It depends on what reload time you have set for the topten to regenerate in the config, if you reload and wait a few minutes it probalbly fix itself.
```
    # [integer] The time in minutes for refreshing/recalculating the score for players on their island
    # set to 0 to disabled
    autoRefreshScore: 15
```
As soon the other players (HANCYs, Marey, Legendary) have done the command "/is level" it will correct the top 10 list aswell (but for their name only then).

When a issue is closed you can still reply or make a message there, keep 1 issue in 1 post plz.

**Comment by PinoyLifeCraft** [comment]
![1](https://cloud.githubusercontent.com/assets/13610530/13247454/286cf11e-da76-11e5-87fb-7769c3c15da7.png)
And thanks for that Config
Plus sorry !!!
Must i have to make an Issue to the Biome Problems?

**Comment by rlf** [comment]
Seems likely, that the `/usb reload` will mess with the internal caching of the top-score.

Needs some investigation (and perhaps some code-changes).

**Comment by PinoyLifeCraft** [comment]
Still happening!
This is my Config
![a](https://cloud.githubusercontent.com/assets/13610530/13286040/28fbe988-db5b-11e5-8b56-39cd784eae7e.png)

**Comment by rlf** [comment]
Ohh wow! So it didn't magically disappear?? What a let down.

It might have a chance of stopping, once this issue has been solved/adressed/investigated.... alas, that time has not yet come

**Comment by PinoyLifeCraft** [comment]
So what should i do?

**Comment by dutchy1001** [comment]
Without an update supplied by us there is nothing you can do then wait.

**Comment by rlf** [comment]
Ok, did some more investigation.

It is correct, that the `/is level` command will incorrectly show, that you are ranked number 1 after a reload.
This should, however, be changed the first time the top-ten is refreshed (I.e. a call to `/is top`, or the `autoRefreshScore` is run).

**Comment by PinoyLifeCraft** [comment]
Ok i will wait for new Version i hope Enter and Exit message will solve
until now i don't have no idea ! :disappointed:

**Comment by dutchy1001** [comment]
If this issue is still happening with the new release of v2.6.4 then let us know. For the meantime i will close this.
