### ISSUE TITLE
[Suggestion] Send players to spawn instead of 0,0 or throw an error

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#675]
When my staff try to teleport to a non-existing island using "/usb goto", it sends them to 0,0 in the skyblock world. Since my spawn is in a separate world, they end up at the 0,0-island and sometimes mistake it for the island they were trying to get to. It also seems to happen to regular players when using "/is warp" when the island they're trying to warp to doesn't have a warp set or doesn't exist. I suggest either sending them to spawn in those cases or just throwing an error to the player.

**Comment by rlf** [comment]
That should be what happens, if you have set `sendToSpawn` to true in the `config.yml`.

**Comment by BlackBeltPanda** [comment]
I have "sendToSpawn" set to true and use EssentialsSpawn. Sending to spawn seems to function properly on island restarts but in the cases I listed above players are sent to the 0,0 island.

**Comment by dutchy1001** [comment]
This happens to me too, think we talked about it a while back but got forgotten in time with all the other features that have been added.

**Comment by rlf** [comment]
Odds are, it's bugs then, caused by the plugin finding a "null-location" (i.e. no island), and reverting to 0,0 as island location.

It shouldn't send the players anywhere then, but tell them an error message.

So, let's try to compile a full list:
```
/usb goto <name>
/is warp <name>
```

**Comment by dutchy1001** [comment]
I have only notest this with ```/usb goto```, but I will try and see if ```/is warp``` is having the same issue tomorrow.

**Comment by rlf** [comment]
Part of v2.6.2 (for 1.9)

**Comment by BlackBeltPanda** [comment]
Still getting sent to 0,0 for players that don't have a warp. Looking at the island .yml file for them, it lists their warp location at 0,0,0.

**Comment by dutchy1001** [comment]
I tried to reproduce it but when there is no warp set it tells me that
![2016-03-05_17 15 36](https://cloud.githubusercontent.com/assets/5569980/13549074/2b800282-e2f6-11e5-9c02-72a6ccb83199.png)

Ps.I use the en_GB language supplied from within the plugin.

I suspect it might be a glitch from when warp was set and players logged out before it was safed to file, but that is just guessing.

**Comment by BlackBeltPanda** [comment]
warpActive is set to true in the same island.yml file where the warp location is set to 0,0,0. Seems either the warp was activated and the location wasn't saved or the location somehow reset at some point.

**Comment by dutchy1001** [comment]
if the player deactivates the warp, then reset the location of the warp(the hopper item) and then activate the warp, is it then reset to the right location??

**Comment by dutchy1001** [comment]
Does this still occur on your server?
If so, is this only happening for players without an island?

Tests so far give me only the message that a player doesn't have an island with _/is warp [name]_ or _/usb goto [name]_.

**Comment by BlackBeltPanda** [comment]
Still happens, mostly in the case of not using proper case for usernames; i.e. - "/is w player1" instead of "/is w PlaYer1".
It did happen the other day with proper case, though. The player who owned the island had to use "/is setwarp" again for players to be properly teleported there. Otherwise, they were teleported to the island at coords 0,0.
Haven't tested with the latest pre-releases.

**Comment by dutchy1001** [comment]
maybe an extra "playername" check for the right spelling/upper-lowercase but that is upto rlf to see

**Comment by dutchy1001** [comment]
This can still happen when the "player".yml file has the wrong value. There is nothing we can do about that then manual going through the files and correct them. 
This however shouldn't occur anymore with newer files (a restart of the island should fix this then).
