### ISSUE TITLE
[Suggestion] Ability to specify spawn point without external plugin

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#678]
Quick suggestion: Would love to see the ability to specify the spawnpoint (world, coordinates, and direction) in the config or a command through USB. Right now I use EssentalsSpawn specifically for uSkyBlock but otherwise have no need for the plugin.

Alternatively, using Multiverse's "firstspawnworld" and spawn point would work in my case, though I'm sure not all USB servers use Multiverse. Not a big deal but I've been wanting to cut down on the number of plugins I use (currently at 75) to make it easier to hunt down bugs and figured I'd just throw this suggestion out there. =)

**Comment by rlf** [comment]
We simply delegate "sendToSpawn" to the `/spawn` command, so you can simply overrule that with the bukkit way of adding command-aliases.

I.e. to `/mvtp world` or `/tppos x y z` if you like.

**Comment by BlackBeltPanda** [comment]
Somehow I always forget about the Bukkit aliases. XD
Thanks for the suggestion. =)

**Comment by rlf** [comment]
Closing this for now - since it's possible to do what the title asks, just not inside uSkyBlock.
