### ISSUE TITLE
Can't change language - Current Biome

### ISSUE THREAD

**Issue by PinoyLifeCraft** [rlf/uSkyBlock#680]
I cannot change the Current Biome Even i change it!
![2016-02-26_00 02 59](https://cloud.githubusercontent.com/assets/13610530/13351796/b4fd2218-dce5-11e5-9e17-de0f31b49c84.png)
I'm using uSkyBlock :
![2016-02-26_00 05 22](https://cloud.githubusercontent.com/assets/13610530/13351814/cf8f3ed6-dce5-11e5-9419-7c70d1aebcaf.png)
Here is it! ->
![a](https://cloud.githubusercontent.com/assets/13610530/13351964/bb2ea58e-dce6-11e5-855e-af9a7cf580fd.png)

**Comment by PinoyLifeCraft** [comment]
Sorry Wrong Image
![2016-02-26_00 13 01](https://cloud.githubusercontent.com/assets/13610530/13352193/26f02bfc-dce8-11e5-9660-8ea9f5844b9d.png)

**Comment by rlf** [comment]
Not sure I get what the problem is?

What is it you can't change?
The text "Current Biome"?
The actual biome?
The biome shown in the GUI?
The name of the biome?

**Comment by dutchy1001** [comment]
Working as expected  for me

![2016-02-26_13 47 09](https://cloud.githubusercontent.com/assets/5569980/13353923/8b01d2c0-dc8f-11e5-9f2b-63380d71202d.png)

**Comment by PinoyLifeCraft** [comment]
Just what like dutchy1001 did.
&7Current Biome : &a{0}
But it's not working?
This is what i mean
§7Current Biome : §a{0}

**Comment by dutchy1001** [comment]
can you post the tl.po file plz (through pastebin)

**Comment by PinoyLifeCraft** [comment]
[i18n.zip](https://github.com/rlf/uSkyBlock/files/149686/i18n.zip)

**Comment by dutchy1001** [comment]
When I put your file in my test server it works fine (no need to keep the .mo file in the uSkyblock\i18n folder), no hassle what so ever. 
When ever you change something in a uSkyblock file you need to reload the plugin with "**/usb reload**" or **restart** the server (I always **reload** twice, just to be sure).
After some investigation I also found that when you do the command "**/usb wg update**" it will then update the region your in for that player (you need to have OP).

**Comment by PinoyLifeCraft** [comment]
But it generate in it self i don not do that. -.-
Yes.... i do that and always -.- **/usb reload** i will not restart my server because some players are playing .. i don't want them to disturb! :smiley: 
Will thanks for **/usb wg update** :smile:

**Comment by dutchy1001** [comment]
You should translate the file from a different map and then copy paste the file into the server. To delete the .mo file wont hurt as PoEdit will recreate the file when needed.

If a restart is needed for the server to have the changes take effect then that's what you should do. Loyal players will understand this.

From my point this issue is solved and working as it should.
