### ISSUE TITLE
[Suggestion] Island and Party talk toggle

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#682]
This is a suggestion from my server's players. The ability to toggle the island talk channel by typing "/it" with no message, so that all future messages are sent via island talk until it's toggled off with "/it" again. Same for party talk.

**Comment by dutchy1001** [comment]
I'll support this suggestion, I think I've said this a while back already but with many things going on forgot about it.

**Comment by rlf** [comment]
dutchy1001 suggested it back when we made it, but I just didn't want to mess too much with the "chat-events".

**Comment by BlackBeltPanda** [comment]
Seems to be working well. =)
