### ISSUE TITLE
Island Warp + Island Creation?

### ISSUE THREAD

**Issue by RickyDeCoite** [rlf/uSkyBlock#683]
uSkyBlock - 2.4.7
Vault - 1.5.6
WorldEdit - 6.1.1 (3394)
WorldGuard - 6.1.1 (1623)

We had a player with the ability to set an island warp, join an island, setup the warp and then leave the island and setup a new warp. The island that player left now has a warp, and the island he just made now has a warp.

At first I thought it was tied to the Island Owner (eg. /is warp RickyDeCoite). Recently found out if the Island Warp is set, any island members name can be used to get to the island. I left the Island, but the warp remained active.

Adding on to this issue with something I found out while trying to troubleshoot this issue, I left my island, after making one of my party members the leader, I went to spawn to make a new Island. It tells me that it is looking for a location closer to spawn, and that it found a spot and is clearing it up for me. I waited for several minutes. (6 minutes the first time, 10 the second time.)
This is what I get:
https://gyazo.com/3d4b50427e7b09ee9ba32477ee79d09b
https://gyazo.com/8ee0f6c4c59e28825e46798a9650837a

This was also sent out, but might not be related to my two issues:
https://gyazo.com/58fd3854275975ff7f77963ba631395f

Reason I'm not running anything over 2.4.7 is the modification to protected regions shrinking by one block. Which while I know why it was done, I have a couple hundred islands that then have a block fall out of protection, I will have it changed soon.

**Comment by rlf** [comment]
Please provide the FULL output of `/usb version`, and possibly update your version of uSkyBlock to a more recent version and let us know if the problem is still a problem.

I recognize the issue with the "fallout", but if your distance > protectionRange in your config.yml, you could just increase protectionRange with 2 (making the new regions encompas the old).
