### ISSUE TITLE
Checking if player has island

### ISSUE THREAD

**Issue by Banbeucmas** [rlf/uSkyBlock#684]
Well, proplem tbh
I know you guys got the island info on to the api but can we add some boolean for checking the player info for the island (player have island or not)

**Comment by rlf** [comment]
Part of v2.6.2, see http://rlf.github.io/uSkyBlock/apidocs/index.html

**Comment by UnioDex** [comment]
Is this issue solved? I want to check player has island. Is this possible with 2.7.2?

**Comment by Lmmb74** [comment]
It has not been added a boolean to check if a player is member in an island, but there are actually 2 booleans to check if it is banned from an island or it is a leader. But what you need is possible with the method getMembers() which returns a string, that way you can check if a player name is contained in that string.

**Comment by UnioDex** [comment]
I handled with getIslandInfo(). It gives null if there is no island.

**Comment by Lmmb74** [comment]
I have mistaken your doubt sry xD.

**Comment by Lmmb74** [comment]
Idk why I thought the question was check if player is member in certain island

**Comment by UnioDex** [comment]
No problem

**Comment by dutchy1001** [comment]
to check if a player has an island can be done by the command /usb goto [playername].
I know this is probably not the answer your looking for but atleast you can see this ingame. 
If the player has an island it will tp you to there, if no island it will message in the chat.
