### ISSUE TITLE
Maven Repository Seems Broken

### ISSUE THREAD

**Issue by xiurobert** [rlf/uSkyBlock#685]
I am unable to use the GitHub Raw maven repository for uSkyBlock. Could you please check why?

**Comment by rlf** [comment]
Could you share your configuration? I use it quite often, and it still works for me (not for the latest API, but everything else seems to work).

**Comment by xiurobert** [comment]
I actually killed off the custom plugin, but here's the snippet of the pom

    <repository>
        <id>uSkyblock-ghraw-repo</id>
        <url>https://raw.githubusercontent.com/rlf/uSkyBlock/mvn-repo/</url>
        <snapshots>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
         </snapshots>
    </repository>

Apparently IntelliJ shows it as an error connecting

**Comment by rlf** [comment]
I know, but I do not intend to host anything, if I can avoid it :)

I updated the description here:
https://github.com/rlf/uSkyBlock/wiki/uSkyBlock-API

Please re-test.

**Comment by xiurobert** [comment]
It's now working, thanks.
