### ISSUE TITLE
Squids don't spawn anymore

### ISSUE THREAD

**Issue by corschdi** [rlf/uSkyBlock#686]
In the latest releases, squids don't spawn anymore. This is most likely due to to Squid.class not being a subclass of Creature.class. Therefore, LimitLogic makes squids be categorized CreatureType.UNKNOWN and getMax() always returns 0 for that CreatureType.

**Comment by rlf** [comment]
Sounds likely. If they moved the placement of Squids in the class hierarchy, the spawn-limits need changing.

**Comment by rlf** [comment]
Will be testable in v2.6.4

**Comment by dutchy1001** [comment]
squids spawn again in v2.6.4

**Comment by i9hdkill** [comment]
squids and guardians are spawning again, slimes are still missing regarding to our users.

**Comment by dutchy1001** [comment]
slimes are depending on a chunk, that is a hit and miss if they spawn natural. 
There is a way to get them to spawn (regardless the chunk) with the right "moon" and right height to get them spawn without a slime chunk.

**Comment by corschdi** [comment]
Squids are working in v2.6.4 indeed, just tested it. Slimes however are a direct subclass of LivingEntity (not Monster) and therefore have the same problem. No slime spawning here for me in v2.6.4.

**Comment by rlf** [comment]
Any more mobs we have missed? Might as well put them together :)

**Comment by rlf** [comment]
Bat (Ambient), Ghast (Flying) and EnderDragon (Complex).

**Comment by dutchy1001** [comment]
Just tried to test this to make slimes spawn at level 60 and in swampland (and light level lower then 7) but so far no slime spawned.

**Comment by rlf** [comment]
Slimes are tricky.

Either only on y=39 or below within a slime-chunk (check your world-seed against google).

Or in swampland in low light on a full moon.

I usually go for the Y=39 approach...

**Comment by i9hdkill** [comment]
Slimes are definetely not spawning anymore since the uskyblock 1.9 update. (Our server is still 1.8)
A skyblocker that has more than 1000 hours on his skyblock island told and showed me that.

**Comment by Adam4CZ** [comment]
Hi, I've problem in USB 1.9.
If it's spawn-limit true, slimes not spawning, but if it's false, it's spawning normally.

**Comment by hunter688** [comment]
Looks like latest commits fix issue with spawning slimes. Tested with custom build from git.

**Comment by SgtLegoTown** [comment]
i' am testing the latest version as we speak as far as I have tested with the git version all looks fine I will try a fresh server to test it again ..

**Comment by i9hdkill** [comment]
Does this fix not placable armor stands too? Posting this here, as this might be related.
` Name: uSkyBlock
[17:11:30 INFO]: Version: 2.6.4
[17:11:30 INFO]: Description: Ultimate SkyBlock v2.6.4-bc02bd-403
[17:11:30 INFO]: Language: de (de)
[17:11:30 INFO]: ------------------------------
[17:11:30 INFO]: Server: CraftBukkit git-Spigot-db6de12-3f3c65f (MC: 1.8.8)
[17:11:30 INFO]: ------------------------------
[17:11:30 INFO]: Vault 1.5.6-b49 (ENABLED)
[17:11:30 INFO]: WorldEdit 6.1.1-SNAPSHOT;3399-b19cd9be (ENABLED)
[17:11:30 INFO]: WorldGuard 6.1.1-SNAPSHOT.1628-e28b236 (ENABLED)
[17:11:30 INFO]: AsyncWorldEdit 3.3.0 (ENABLED)
[17:11:30 INFO]: Multiverse-Core 2.5-b711 (ENABLED)
[17:11:30 INFO]: ------------------------------
`

**Comment by SgtLegoTown** [comment]
for the slimes I used (url)[http://chunkbase.com/apps/slime-finder#3615590874558682193](url)

after disabling is limits I got slimes and iron golems again also tested by disabling usb spawn are then normal when I turn off is limits with usb golem stay low what I don't mind. (but don't know if it supposed too and slimes are normally spawned. tested with 👎 
[23:53:48 INFO]: Name: uSkyBlock
[23:53:48 INFO]: Version: 2.6.8
[23:53:48 INFO]: Description: Ultimate SkyBlock v2.6.8-8cdd5b-408
[23:53:48 INFO]: Language: en (en)
[23:53:48 INFO]: ------------------------------
[23:53:48 INFO]: Server: CraftBukkit git-Spigot-5a40365-b103841 (MC: 1.9.2)
[23:53:48 INFO]: ------------------------------
[23:53:48 INFO]: Vault 1.5.6-b49 (ENABLED)
[23:53:48 INFO]: WorldEdit 6.1.1-SNAPSHOT;3487-c9f54ec (ENABLED)
[23:53:48 INFO]: WorldGuard 6.1.2-SNAPSHOT;1653-65e48d1 (ENABLED)
[23:53:48 INFO]: Multiverse-Core 2.5-b719 (ENABLED)
[23:53:48 INFO]: Multiverse-NetherPortals 2.5-b710 (ENABLED)
[23:53:48 INFO]: ------------------------------

also tested on a copy of my regulars serve with all plugins same results

hope this helps ...

**Comment by SgtLegoTown** [comment]
also tested guardian spawning primaries on 60  2 open blocks then a water bin too 41 filled with water biome deep ocean and I have guardians as soon as change the biome there where squids spawning again ... same setup as before ..

**Comment by rlf** [comment]
Am a bit puzzled, is the conclusion, that slimes DO NOT Spawn when is limits is enabled?
Are there any other mobs that seems to be affected?

**Comment by SgtLegoTown** [comment]
Squids DO spawn golems and slimes seems to disappear when limits are on

**Comment by SgtLegoTown** [comment]
with deep ocean and prismarine on the right spot guardians DO spawn with limits on and off

**Comment by rlf** [comment]
So, slimes and golems still needs some work.
I'll try to figure out why they still cause trouble.

**Comment by jdrowell** [comment]
Current snapshot spawns slimes for me as expected (was broken in 2.6.4 release). Thanks!

**Comment by donbubu** [comment]
`Name: uSkyBlock
Version: 2.6.12
Description: Ultimate SkyBlock v2.6.12-9e2d30-413
Language: de (de)
------------------------------
Server: CraftBukkit git-Spigot-8a048fe-042911f (MC: 1.9.4)
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.3;7a097ca (ENABLED)
WorldGuard 6.1.2;e38d98d with custom flags plugin. (ENABLED)
FastAsyncWorldEdit 3.5.1-a521cb9 (ENABLED)
------------------------------`

no squirts at y=50 after change from SkyBlock v2.6.4-bd1c2b-404

**Comment by i9hdkill** [comment]
They are definitely spawning in 2.6.12.
Update to 1.10.2

**Comment by dutchy1001** [comment]
If you can switch to paper spigot you can set every chunk to be a slimechunk

**Comment by i9hdkill** [comment]
I think he means squids

**Comment by donbubu** [comment]
Right, i mean squids. @i9hdkill, a squid only spawn within y=44-63 and slimes spawn under y=40.
However, some of our admins has disabled mob-spawning in WG. I delete this flag and now squids spawn, sry for this mistake.

**Comment by dutchy1001** [comment]
I presume this issue can be closed as it has been solved
