### ISSUE TITLE
Spawn eggs are empty as in not set to a type. 

### ISSUE THREAD

**Issue by kiwifrogg** [rlf/uSkyBlock#688]
1.9 has a different system for setting the spawn egg type, how does this translate in the challenges.yml 

So 1.8 the config would look like  "- 383:95:1" for 1 wolf egg, 
in 1.9 would "- 383:1 {EntityTag:{id:"wolf"} "}  work or not?

**Comment by rlf** [comment]
Currently that won't work.
But you can use the commands for rewards to give the item (or spawn it) instead.

**Comment by dutchy1001** [comment]
the right way of fixing this for now is to add 
```
          commands:
          - 'console: give {player} 383:95 1'
```
this is the an example for the "luberjack" challenge"

**Comment by rlf** [comment]
See http://minecraft.gamepedia.com/Spawn_Egg#Data_values

I would probably do:
```
commands:
  - 'console: give {playerName} minecraft:spawn_egg 1 0 {EntityTag:{id:"Wolf"}}'
```
in 1.9

**Comment by dutchy1001** [comment]
I'll redo the challenges file with your suggestion (probably more future proof then mine) some time today/tonight and create a new pull request.

**Comment by kiwifrogg** [comment]
>           commands:
          - 'console: give {player} 383:95 1'

Actually that would not work 383:95 does not exist in 1.9 any more,  all you'd receive is empty eggs(who knew they were a thing).  Rlf's way was how I did it in the end, except I used - 'op: give {player} minecraft:spawn_egg 1 0 {EntityTag:{id:"Wolf"}}'  

Hope that hasn't created a security hole.

**Comment by dutchy1001** [comment]
I found a work around/fix for the spawn eggs to be given through the config
```
          commands:
          - 'op:minecraft:give {player} spawn_egg 2 0 {EntityTag:{id:"Wolf"}}'
```
you can use **op:** or **console:** but in both cases it leaves an extra message in the chat

**Comment by rlf** [comment]
Since we have "fixed" this issue by providing viable work-arounds, I will be closing this for now.
