### ISSUE TITLE
two islands on same place

### ISSUE THREAD

**Issue by hunter688** [rlf/uSkyBlock#689]
When two and maybe more players do create new island in the same time, all islands are created on the one place. I think in the plugin is missing better prevention against concurent creating of islands. When is time between players creating islands > 10 seconds, everything is ok. Tested on 1.8.8, 1.9, with latest release, also with oldest relase for 1.8.8. I can show problem on my test server...

When examined this problem - looks like islands .yml files are created properly, but players files points to same place.

**Comment by dutchy1001** [comment]
We have tried to reproduce this issue your having and created 2 islands within seconds if not at the same time, but both players ended up on their own island with the correct players file value's.

**Comment by SgtLegoTown** [comment]
I have tried to recreate this problem with only the decencies plugins and uskyblock ofc .. with 4 players (i used multibox to get the is create at exact the same moment) exact at the same time I get 4 islands with 4 players on it do you have more information like other plugins that can interfere ? tested with 1.8.8 latest and latest 1.9

**Comment by hunter688** [comment]
`AsyncWorldEditInjector, PlayerHeads, WorldEdit, BookRules, Essentials, PlaceholderAPI, Gringotts, WorldGuard, Multiverse-Core, AsyncWorldEdit, RocketBoots, Multiverse-Inventories, EssentialsChat, PermissionsEx, Multiverse-Portals, Vault, EssentialsSpawn, BetterAlias, uSkyBlock, CreativeGates, VariableTriggers, Citizens, Shopkeepers, Quester, GlobalMarket`

**Comment by hunter688** [comment]
with only: WorldEdit, Vault, WorldGuard, uSkyBlock still problem persist...
spigot 1.9, java 1.8

**Comment by Adam4CZ** [comment]
I add files from @hunter688 's test server when we try creating island in the same time:
http://pastebin.com/r84VF58b (3 players)

**Comment by SgtLegoTown** [comment]
can you try /usb v for the version information

**Comment by Adam4CZ** [comment]
Name: uSkyBlock
Version: 2.6.2
Description: Ultimate SkyBlock v2.6.2-1407cb-401
Language: en (en)
------------------------------
Server: CraftBukkit git-Spigot-b1c1b55-dd016e7 (MC: 1.9)
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.1-SNAPSHOT;3448-de35781 (ENABLED)
WorldGuard 6.1 (ENABLED)
------------------------------

and we also test uSkyBlock 2.6.3 (latest).

**Comment by dutchy1001** [comment]
I will retest this after dinner (UK time) local with my alt account. 
Server setup will be only with the basic needed plugins and USB depended plugins. 
I will of course post the output of /usb version when the server is setup.

**Comment by hunter688** [comment]
we tested without multiverse, only necessary plugins

**Comment by dutchy1001** [comment]
Multiverse-core  is listed as a necessary plugin

**Comment by hunter688** [comment]
ok we add this plugin

**Comment by hunter688** [comment]
[19:31:00 INFO]: Name: uSkyBlock
[19:31:00 INFO]: Version: 2.6.3
[19:31:00 INFO]: Description: Ultimate SkyBlock v2.6.3-38dff5-402
[19:31:00 INFO]: Language: en (en)
[19:31:00 INFO]: ------------------------------
[19:31:00 INFO]: Server: CraftBukkit git-Spigot-b1c1b55-dd016e7 (MC: 1.9)
[19:31:00 INFO]: ------------------------------
[19:31:00 INFO]: Vault 1.5.6-b49 (ENABLED)
[19:31:00 INFO]: WorldEdit 6.1.1-SNAPSHOT;3448-de35781 (ENABLED)
[19:31:00 INFO]: WorldGuard 6.1 (ENABLED)
[19:31:00 INFO]: Multiverse-Core 2.5-b715 (ENABLED)
[19:31:00 INFO]: ------------------------------

**Comment by dutchy1001** [comment]
I have reproduced this bug whit the following plugins:

[18:33:51 INFO]: [uSkyBlock] Name: uSkyBlock
Version: 2.6.3
Description: Ultimate SkyBlock v2.6.3-38dff5-402
Language: en_GB (en_GB)
Server: CraftBukkit git-Spigot-dd155ed-23ad72b (MC: 1.9)
Vault 1.5.6-b49
WorldEdit 6.1.1-SNAPSHOT;3448-de35781
WorldGuard 6.1.2-SNAPSHOT;1652-c9b8e9f
Multiverse-Core 2.5-b716
Multiverse-Portals 2.5-b738
Multiverse-NetherPortals 2.5-b707

[Pastebin](http://pastebin.com/KQqTT19z) of my findings in the .yml files and log

Note that dutchy is executed 1 second earlier and has only 1 creation log while Stampy has 3 creation logs.
Also the position of were the log is in the YML is different which I think is odd, shouldn't they stay on the same location.

I think r4zorax will be needed for this one.

**Comment by rlf** [comment]
It's very likely that this might happen, since we have currently no strict way of "locking" an area while scanning for a suitable spot.

This will require some refactoring, but I think it's needed.

**Comment by woolwind** [comment]
how about a file lock on lastisland.yml?

**Comment by rlf** [comment]
Should be testable in v2.6.7

**Comment by rlf** [comment]
According to this post https://www.spigotmc.org/threads/uskyblock.38300/page-98#post-1711825
the problem still exist in v2.6.12

**Comment by dutchy1001** [comment]
Not sure how to test this as I haven't been able to reproduce this.

**Comment by dutchy1001** [comment]
never happened again for me
