### ISSUE TITLE
Could not pass PlayerTeleportEvent

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#692]
After a player logged in, the console was spammed with about 28,000 lines of this error: http://pastebin.com/raw/ANNRrKF4

**Comment by dutchy1001** [comment]
You only got MV-Core and  MV-NetherPortals, you might need to add MV-portals and see if that helps

**Comment by rlf** [comment]
Hmm, we have seen this before.

It seems to be caused by a concurrency bug when loading player-data of someone that needs their inventory cleared.

**Comment by rlf** [comment]
The above spamming should be fixed, but...
There might still be issues when clearing inventory for players that were offline (or off-world) when their island was cleared.

**Comment by BlackBeltPanda** [comment]
Haven't had any issues with it since the commit. =)

**Comment by rlf** [comment]
Thanks, closing for now then.
