### ISSUE TITLE
[Suggestion] Prevent Wither damage outside island

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#693]
Been having a problem recently where players will spawn in withers but the withers will fly off and eventually start attacking other players' islands, even with an island size of 304 and distance of 500. Would be great if there was a way to limit withers to the island they're spawned on.

**Comment by rlf** [comment]
Unfortunately, that is not supported, neither in Bukkit or in WorldGuard.
There is simply no events related to mobs we can use to detect when they leave a region.

But, perhaps we can come up with something along the lines of: "if a wither targets an entity on another island than where it is currently, it will despawn".

**Comment by BlackBeltPanda** [comment]
In my players' case, the withers are floating to other islands or they fire at a player and miss, causing the projectile to travel to another island. Few ways I thought up but none are perfect:

1. Add metadata to the wither when it's spawned containing the island location it was spawned on and use that to compare locations. The wither would have to be killed when the server shuts down, though, since metadata doesn't survive restarts.

2. Give the wither a custom name containing the island location, like "1600,-640 Wither". That would allow it to survive restarts but obviously doesn't look as nice.

3. It looks like withers are permissible; wonder if it'd be possible to add a permission to a wither containing the island location. Bit hacky and I'm not sure if it'd work.

**Comment by rlf** [comment]
I like option 2.
We could just change the name to be "<name of spawnee>'s Wither", and then lookup the island of the name when deciding whether the wither-damage should take effect.

That way, we could do something like:
```
  on wither-damage or wither-targetting:
    if wither-target is on another island than the owner:
      despawn wither
```
That way, there's an incentive for spawnees to handle it - and if they fail, they lose their wither.

**Comment by BlackBeltPanda** [comment]
Sounds like it'd work =)
I'd also despawn the wither in the event the player or their island no longer exists due to island restart, name change, etc.

**Comment by BlackBeltPanda** [comment]
Seems to be working well =)
