### ISSUE TITLE
Schem issues, Menu Lore Issues, and a suggestion.

### ISSUE THREAD

**Issue by SirApathy** [rlf/uSkyBlock#694]
Along with the new update of uSkyBlock(v2.6.4) I found a few issues.

**Issues:**
1. To start off, in the start menu(The first menu when you don't have an island.) the lore of the skull thats meant for accepting any invites has the lore of the default island.
2. The schems for multiple islands can be renamed and what not, but if it doesn't have the same name as before when you reload(For instance; the skySMP.schematic file.) then it'll create that file again along with the renamed file.
3. The skySMP default island doesn't have a chest in it. Not entirely sure if that was what skySMP had or not.

**Possible Features**
1. Customizable menu without using ChestCommands! You've probably heard that a million times, sorry I had to.
2. Easier to change custom menu text. Instead of using the default text to better suit the persons needs.

**Comment by dutchy1001** [comment]
**Issue's**
1. This will need to be addressed and fixed
2. You need to add ```enable: true/false``` to the skySMP section to disable the reappearing.
3. when I restart and choose the skySMP I get a chest as normal (check your schematic).

**Possible features**
1. We did, but the use of ChesrCommandGUI gives a lot of extra's you can do to menu's, implementing this gives more reason for bugs and might bloat the plugin.
2. The system we have is far more superior then a simple messages.yml text file.

**Comment by SirApathy** [comment]
**Issue's**
1. Awesome :)
2. Thank you! I had no clue that was an option aha.
3. Schematic was set by default so I'm not sure what happened to it. I redid the schem to make it work though :)

**Possible features**
1. I love using ChestCommands but I have issues while trying to use it. First issue would be, using the Challenges menu for uSkyBlock, it A. Doesn't have the same look as my menu and B. when a player clicks on the Rank blocks it takes them back to the old uSkyBlock menu(Maybe a possible way to disable some parts of the menu?). It also stops the player from getting the create an island gui when they first type the island command. Also trying to attach the /island biome command to a CC menu takes you to the uSkyBlock biome menu since CC doesn't take priority over uSkyBlock in any of uSkyBlocks secondary menus(Biome Menu, Party Menu, Island Log etc.).
2. Very true aha.

**Comment by dutchy1001** [comment]
Only the main menu can be changed atm, I will suggest a fully customizable way but that is depending on our developer.
