### ISSUE TITLE
v2.6.4

### ISSUE THREAD

**Issue by MrMurfy** [rlf/uSkyBlock#695]
I cannot download the lates version: v2.6.4. Maybe, the website is down but it says that it wwasnt the web page i was looking for. I dont know. Can you upload it, plz?
Ty :)

**Comment by dutchy1001** [comment]
there are 3 ways to get the uSkyblock file
[Spigot](https://www.spigotmc.org/resources/uskyblock.2280/) (this seems to have issue's, will look into this)
[Bukkit](http://dev.bukkit.org/bukkit-plugins/uskyblock/files/)
[Github](https://github.com/rlf/uSkyBlock/releases)

**Comment by MrMurfy** [comment]
ok, thanks!
