### ISSUE TITLE
Fake Players Cause Server to stall

### ISSUE THREAD

**Issue by Time6628** [rlf/uSkyBlock#702]
http://pastebin.com/wfqL3DVb

All fake players spam a similar error and eventually the server just stalls because the cache is full.

**Comment by dutchy1001** [comment]
What is a fake player?? 
Is that a player that uses an alternative account to gain extra items??
Could you post the output of /usb version??

Plz next time use pastebin to post log errors.

**Comment by Time6628** [comment]
A fake player is a player created by a mod. For example, killer joe from ender io or an autotomus activator from Thermal Exapansion. Fakeplayers can break/interact with blocks just as a normal player would. 
/usb version:
```
26.03 20:28:14 [Server] INFO Name: uSkyBlock
26.03 20:28:14 [Server] INFO Version: 2.5.3-bukkit-1.7.9
26.03 20:28:14 [Server] INFO Description: Ultimate SkyBlock v2.5.3-bukkit-1.7.9-da7f04-383
26.03 20:28:14 [Server] INFO Language: en (en)
26.03 20:28:14 [Server] INFO ------------------------------
26.03 20:28:14 [Server] INFO Server: Cauldron 1.7.10-1614.45 (MC: 1.7.10)
26.03 20:28:14 [Server] INFO ------------------------------
26.03 20:28:14 [Server] INFO Name: Vault (ENABLED)
26.03 20:28:14 [Server] INFO Version: 1.4.1-b436
26.03 20:28:14 [Server] INFO ------------------------------
26.03 20:28:14 [Server] INFO Name: WorldEdit (ENABLED)
26.03 20:28:14 [Server] INFO Version: 6.1;no_git_id
26.03 20:28:14 [Server] INFO ------------------------------
26.03 20:28:14 [Server] INFO Name: WorldGuard (ENABLED)
26.03 20:28:14 [Server] INFO Version: 6.1
26.03 20:28:14 [Server] INFO ------------------------------
26.03 20:28:14 [Server] INFO Name: AsyncWorldEdit (ENABLED)
26.03 20:28:14 [Server] INFO Version: 2.2.2
26.03 20:28:14 [Server] INFO ------------------------------
```

**Comment by SgtLegoTown** [comment]
and what plugin u use for fake players ?

**Comment by dutchy1001** [comment]
I always wonder why they never start off to tell their using Cauldron or KCauldron as this is the main issue 9 out of 10 times. 
I have given up on (K)Cauldron servers.

**Comment by Time6628** [comment]
Cauldron isn't the problem. It's how USB handles FakePlayers from Forge mods.

**Comment by dutchy1001** [comment]
For the 3.5% that uses Cauldron I'm not gonna spend hours to get it working on my pc. 
If this is an issue with Spigot or CraftBukkit (**were uSkyblock is coded for**) I can test it and give our developer input what to change or look at. It is then still up to our developer to do the work.

I do not agree that you think uSkyblock is the problem, only Cauldron and KCauldron  (**were uSkyblock isn't coded for**) are causing these issue's. If they updated to 1.8 or now 1.9 when it came available we probably wouldn't have these issue's.
![uskyblock_-_server_software](https://cloud.githubusercontent.com/assets/5569980/14064780/eb2a3c0c-f407-11e5-930c-40c0f891e191.jpeg)

**Comment by Time6628** [comment]
Can you just add a way to block players from being registered by usb? :/

**Comment by rlf** [comment]
Related to #662
