### ISSUE TITLE
Falling into void when teleporting to an island

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#706]
Sometimes when using "/is w <player>", "/usb goto <player>", or even "/is h", the player is teleported either inside of or underneath a block resulting in them falling into the void. Was thinking it could be due to 1.9 adding entity collision; not sure.

Version info: http://pastebin.com/raw/9dDM8C9y

**Comment by dutchy1001** [comment]
You might want to put up a message to let players reset their home location and/or warp location. This just to make sure there on top of the island. It's not a fix but worth a try to counter the issue.

**Comment by rlf** [comment]
We already teleport players to the location + (0.5, 0.1, 0.5) - to try to make them "hover" above the block, and in the center.

Not sure what more we can do - except perhaps pre-load the chunk.

**Comment by dutchy1001** [comment]
Could this be caused due to the fact that the bedrock block isn't needed anymore?

**Comment by BlackBeltPanda** [comment]
I just got reports of this happening with Essentials' "/tpa", so I think it's related to 1.9.

**Comment by rlf** [comment]
Ok, I will close it for now then - if it requires a fix from our end, we can re-open it and try to figure out how to force 1.9 to behave.
