### ISSUE TITLE
Unable to place Armor Stands in skyworld.

### ISSUE THREAD

**Issue by Deathinflames** [rlf/uSkyBlock#707]
My players reported that they are unable to place Armor Stands in the skyworld. After testing it for myself it appears that they are right. We run quite a few plugins alongside uSkyBlock so i thought it was a plugin conflict of some sort. I ran BuildTools.jar to generate the latest spigot-1.9.2.jar on a localhost, i generated the server files and shut down the server. After installing Vault, WorldGuard, WorldEdit, Spigot-Essentials, and of course uSkyBlock v2.6.5, i started the server up and opped myself then proceeded to generate a new island. To my surprise it was still occurring, when attempting to place the armor stand one is deducted from the stack but nothing physically appears in-game. I then did /spawn and was able to place one in "world". Is anyone else experiencing the same issue?

![929bbef764563ff4ba7494635fe54f35](https://cloud.githubusercontent.com/assets/6750890/14200733/395be646-f7aa-11e5-8282-ef97d59674a4.png)

**Comment by rlf** [comment]
Most likely, an armor-stand is an entity, meaning they fall into the category of "spawns" and thus is limited by the spawn-limits.

Try disabling the spawn-limits:
```
    # Limits the spawning
    spawn-limits:
      # [true/false] if true, the limits below will limit spawning
      enabled: false
```
if that resolves the issue - we need to decide how to handle armor stands.

**Comment by dutchy1001** [comment]
When spawn-limits are turned off (set to false) you are able to place an armor stand.

**Comment by rlf** [comment]
So, should armor stands be limited?
What about item-frames?
Are they "spawned" too?

**Comment by dutchy1001** [comment]
Don't think there should be a limit as it doesn't gain much, unless it has a high value in the levelConfig.yml.
Item frames can be placed as normal anyway

**Comment by Deathinflames** [comment]
Armor stands are once again able to be placed in the skyworld. Thank you very much @rlf !
