### ISSUE TITLE
Biome Changing.

### ISSUE THREAD

**Issue by Callatic** [rlf/uSkyBlock#708]
When people Biome change and then go and re log or go spawn and go back to there islands. The biome does not change.

**Comment by rlf** [comment]
Please provide the output from `/usb version`, and preferably a screen-dump or server.log (pastebin) of the output from the plugin when the user tries to change the biome.

**Comment by Callatic** [comment]
The spawn is not in the same world. If you look at the name changing issue. I provide the versions.

**Comment by dutchy1001** [comment]
We cannot keep swapping between issue's to what versions are used.
In version v2.6.5 (from the release section on github) the biome change works as expected.
