### ISSUE TITLE
overlapping islands

### ISSUE THREAD

**Issue by woolwind** [rlf/uSkyBlock#711]
This one is bad.   I have islands 96 blocks apart and 96 protection. Not to thrilled having no buffer, but I wasn't sure if making the distance further than protection would work with the nether islands. 

Anyway, player1  (Evokez and Blim) built out their island to the border. Player 2 (fantasticfuzzy) comes along and builds out to their own island border and Blim tells me part of their island became part of his. Actually the regions overlap. If you stand in the disputed territory and do /rg info it asks you which region you want to know about.

I have a notion using the admin command to fix the wg region in the nether for player2 may have had something to do with it.

http://pastebin.com/EXPtKrf9

**Comment by rlf** [comment]
`/usb version`?

**Comment by rlf** [comment]
As far as I can see, the two islands were created using different settings for protectionRange.

More specifically, the island at 192,-288 was created with a protectionRange of 128.

How that happened is a mystery.
What command did you "fix the wg region in the nether" with?

**Comment by woolwind** [comment]
/usb wg fix

ah hmmm. so I started out with 128 then deleted everything when I changed to 96 (everything was 2 test islands, I didnt think this was one of them, will have to dig out the saved files) but can well believe I missed something, like an existing wg region. If that's it, it is an easy enough fix.

**Comment by woolwind** [comment]
For what it's worth, I figured out what happened.   I'd made a typo updating the config.yml to put in the extra menus and when I reloaded, it  re-initialized the config to default. I fixed it, but fuzzy had already slid in and created his island with default settings - ie protection range 128
