### ISSUE TITLE
Can I Give To Players Larger Island Areas?

### ISSUE THREAD

**Issue by bgencacat** [rlf/uSkyBlock#716]
How can I change island's area size?

**Comment by dutchy1001** [comment]
Once you set the Island size you cant resize it. There is No Way you can have different size island for different ranks/groups.
The only way you can have bigger islands is to reset the skyworld and start fresh.

If you refer to a first time setup, the size can be set in the config with ```distance: 128```  meaning the centre of the island is 128 blocks away from the next island centre.

**Comment by bgencacat** [comment]
I think there is a mistake. Im changed to 256 and Island width still 128.
Maybe protectionRange?

**Comment by bgencacat** [comment]
n yes fress install

**Comment by dutchy1001** [comment]
yes you need to adjust "protectionRange" to. You can make a buffer between island this way but  this is up to you (keep in mind that when using the nether feature those value's need to be able to devide by 32).

If you change the ```distance/protectionRange``` after you have created your first island then that island will not change, you need to delete the world and let uSkyblock generate a new one with your new settings. When deleting the world you also need to reset the WorldGuard folder from the skyworld/skyworld_nether or the previous regions will still exist in your new skyworld.

**Comment by bgencacat** [comment]
Im deleted all of them and solve it. Thanks for help. Any way to force a player for just one schematic? For clear gui. If player has no permission, no show other islands?

**Comment by dutchy1001** [comment]
in the first schematic in the config you see a line ```enable: true```, if you add this to the SkySMP section with ```enabled: false``` it will not show up in the console. 
I don't think this can be set "per player" just in general only. 

A schematic can still show in the GUI but if you gave it a custom permission they can't use it until they get that permission.
