### ISSUE TITLE
rabbits and horses wont spawn

### ISSUE THREAD

**Issue by NBA2017** [rlf/uSkyBlock#719]
Rabbits and horses wont spawn in my skyblock server
and is ther a way that i can let admins build anywhere without giving them op?

*I mad a whole new name and got rid of caps. And if it is the biome how can i  change it? plz help.

**Comment by rlf** [comment]
Thanks for your error report NBA2017.

First off, Github issues are more to issues you find with the plugin.
For "normal support", I suggest you read and post on the various forums - here helpful people will most likely have nice and fine answers for you.

Secondly, *if* you think you have found a geniune bug, please provide the output from `/usb version`.

To answer your above questions (now that you comply with normal manners on da internet):
a) The biomes can be changed using the in-game menu (`/is`) - provided you have the proper permissions to change biome - this can be easily found in the documentation about the plugin.
b) If you read the permission section on dev.bukkit, you will find permissions that allow admins to bypass restrictions (including building).

**Comment by NBA2017** [comment]
Yes but it didnt matter on the biome from before. I would be able to spawn in a rabbit anywhere. When i do /summon Rabbit its says unable to summon object

**Comment by dutchy1001** [comment]
I just did the command /summon rabbit on our test server and is working as should, now I'm stuck with a rabbit.

**Comment by NBA2017** [comment]
http://prntscr.com/aqetn3

**Comment by NBA2017** [comment]
ooppps didnt mean to close my bad

**Comment by dutchy1001** [comment]
I use the same server version (1.9.2)

![2016-04-10_10 03 30](https://cloud.githubusercontent.com/assets/5569980/14409045/b2ea268e-ff03-11e5-8744-28a11ec29879.png)

**Comment by NBA2017** [comment]
is ther a setting in uskyblock that  may have activated on accident?

**Comment by NBA2017** [comment]
And why does it lag a chunk when someone breaks a block in the middle of a large platform?

**Comment by rlf** [comment]
It doesn't lag the chunk, but there is an issue with some clients, when they have a void beneath them.

Try installing the latest Optifine on your client, and if the lag goes away, there is your explanation.

**Comment by rlf** [comment]
This seems to be related to something else than uSkyBlock.
Closing the issue.
