### ISSUE TITLE
Player.hasIsland randomly being reset

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#722]
I've been seeing this happen a bit lately on my server. Players will login to discover that "/is h" doesn't work anymore and when staff try to use "/usb goto" or "/is w" for that player, it says they don't have an island. When I pull up their player file, "hasIsland" has been set to "false". Using "/usb island register" returns "Set players island to the bedrock nearest you." but does not affect the player's file and they're still seen as having no island. In this case, the affected player hasn't changed their username.

I've paste-binned the player and island files for the most recently affected player:

USB Version info: http://pastebin.com/raw/975kdCXD
Kissi.yml: http://pastebin.com/raw/at6N5feC
-16500,-9000.yml: http://pastebin.com/raw/fjbCzTHc
Island region info: http://pastebin.com/raw/FrTSZzUL

**Comment by BlackBeltPanda** [comment]
Update: I was able to re-register the player to the island using one of the following commands, but not sure which one actually worked. This was the command order I used:
"/usb island protect Kissi"  <- Returned "Island already protected" error
"/usb island makeleader Kissi Kissi" <- Returned "Player does not have an island" error
"/usb island transfer Kissi Kissi" <- Threw a NPE

**Comment by dutchy1001** [comment]
Wouldn't the commands ```/usb island remove Kissi``` and ```/usb island register Kissi``` not work?
Remove should clear the island name on player file and island file, register speaks for itself then.

**Comment by BlackBeltPanda** [comment]
"/usb island remove Kissi" returned "That player doesn't have an island".

**Comment by dutchy1001** [comment]
But did it let you register Kissi to that island with the ```/usb island register Kissi```?

I can understand that the remove didn't work as there was no island any more, ```register``` should update the files again, you might need to add a bedrock block if that isn't present and make sure your less then 20 blocks away from it. 
I know we changed the schematics so they don't need the bedrock any more, but for the register I believe it still needs it.

**Comment by BlackBeltPanda** [comment]
Using "/usb island register" returns "Set players island to the bedrock nearest you." but does not affect the player's file and they're still seen as having no island.
Bedrock block was present and I was standing on top of it. All my schematics still use bedrock since I haven't gotten around to updating them, yet.

**Comment by rlf** [comment]
I did some refactoring earlier, where in principle, the `hasIsland` flag should have been removed.
I just rechecked the code, and it appears, a mix/merge has gone wrong.

The `hasIsland()` method correctly doesn't rely on the `hasIsland` flag, but only validates the island position. Unfortunately, the `hasIsland` flag is used in the loading logic - so yes, this should be fixed correctly.

**Comment by BlackBeltPanda** [comment]
"/usb island addmember <player>" seems to work for re-registering the player to the island for the time being.

**Comment by BlackBeltPanda** [comment]
Seems to be working now; haven't come across this error since the update. =)
