### ISSUE TITLE
Untrust doesn't update WorldGuard region

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#725]
When someone issues "/is untrust <player>", the player is untrusted via their player file but the WorldGuard region isn't updated so they remain a region member and can therefore continue to build/break on the island.

Version info: http://pastebin.com/raw/ZmxdV66J
Island info after untrust: http://pastebin.com/raw/2UDfuqUM
Region info after untrust: http://pastebin.com/raw/dzpB1jZa
Player info after untrust: http://pastebin.com/raw/GYVHD4Ue

**Comment by rlf** [comment]
Server log?
We do not save the region explicitly (anymore), we let WG take care of that.
So what you see in the region file might not be correct (i.e. if WG hasn't written the file yet).

**Comment by rlf** [comment]
I wonder if this is tied to the case-sensitive name... worth looking into.

**Comment by BlackBeltPanda** [comment]
Just had a chance to test this some more and it is, in fact, case-sensitive. Using "/is untrust LolGxmer22" removed the player from the region.

**Comment by rlf** [comment]
Will be fixed in v2.7 (or next minor)

**Comment by dutchy1001** [comment]
This is fixed in the v2.7.0-alpha2

**Comment by dutchy1001** [comment]
this issue is fixed in the latest version (2.7)
