### ISSUE TITLE
Duplicate On /is top

### ISSUE THREAD

**Issue by Callatic** [rlf/uSkyBlock#726]
Currently I did a reset to everyone. And I then restarted the server back up and there was 2 people still on /is top but that island didnt exist. So they created a new island and there was on the /is top twice. One was original level. And one was there old island level. How do I remove first top 2 people on /is top?

**Comment by dutchy1001** [comment]
If you reset the whole skyblock server make sure all files are deleted (backup on a different location would be better, just incase) for a new start. That way there cant be anyone in the topten. 
Most will forget the WorldGuard region folder too.

**Comment by Callatic** [comment]
I did. I deleted all worldguard folder. Everything worked its just that there is still 2 people at top of /is top how do I remove them?

**Comment by dutchy1001** [comment]
If all player files, island location files and WorldGuard files for uSkyblock are deleted then there cant be anyone in the top ten. Have you tried the command ```/usb topten``` this should re-generate the list.

**Comment by Callatic** [comment]
Yes I deleted all of them when the reset happened, Then when I checked /is top there was still 2 people there but they dont have islands? It displayed there old island level before the reset. I will try /usb topten

**Comment by dutchy1001** [comment]
I'm curious, is it the ingame topten that list the 2 old island or is it a "scoreboard" that list it?

**Comment by Callatic** [comment]
Topten. The command /is top.

**Comment by dutchy1001** [comment]
The command is **/usb topten** for OP use or with the right permissions

**Comment by Callatic** [comment]
I just did that and still is like this : https://gyazo.com/66dfd5a602d3fcf19bee138972175765

**Comment by Callatic** [comment]
See the two top ones. They need to be removed.

**Comment by dutchy1001** [comment]
can you post the output of ```/usb version```

**Comment by Callatic** [comment]
I sure can.

**Comment by rlf** [comment]
The  top 10 is kept in memory only, so a server restart should ensure it will be recalculated.

It is calculated based on the islands, so if you deleted all island.yml-files from the islands folder, and did a server restart, there should be no duplicates.

**Comment by dutchy1001** [comment]
No further input, considered a glitch as I never could reproduce this
