### ISSUE TITLE
Island party bug, player cannot...

### ISSUE THREAD

**Issue by MrFiliper** [rlf/uSkyBlock#728]
I founf a bug, island leader wants change player permission, but permission doesn´t change. This bug appears only a few players (1 of 500 players).

Name: uSkyBlock
Version: 2.5.0-SNAPSHOT
Language: cs (cs)
-------------------------------
Server: CraftBukkit git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
 ------------------------------
 Název: Vault (ENABLED)
 Verze: 1.5.6-b49
 ------------------------------
 Název: WorldEdit (ENABLED)
Verze: 6.1;no_git_id
------------------------------
 Název: WorldGuard (ENABLED)
 Verze: 6.1
 ------------------------------
Název: AsyncWorldEdit (ENABLED)
 Verze: 2.2.2
 ------------------------------

**Comment by dutchy1001** [comment]
update to v2.6.4 from bukkit or spigot or v2.6.7 from Github

**Comment by rlf** [comment]
Can you provide any info about the players it occurs?
I.e. what are the playernames in question? 
Do they contain special characters? Special CaSeS?

**Comment by MrFiliper** [comment]
In this time player Vinntentou12321, player config: http://pastebin.com/nszzQS5F

Here is island config, where Vinntentou12321 live: http://pastebin.com/d5EssK4n

Leader of island, cant change player permission. I. e. canChangeBiome: false to true.

**Comment by dutchy1001** [comment]
The biome is one of the exceptions that needs permissions per **biome** or **biome.*** or they will not work. If a member doesnt have the permission (of any of the options) in their rank (but the island owner does) usb wont allow to change that for that player in the party GUi

**Comment by MrFiliper** [comment]
But, leader of island can´t change kick permission of member Vinntentou12321, too. There also needs extra permission?

**Comment by dutchy1001** [comment]
Does Vinntentou12321 have the kick permission in his rank??

**Comment by MrFiliper** [comment]
Yes.

**Comment by dutchy1001** [comment]
After some testing with V2.6.8 only the "setwarp" is not working as it should for the party members. All other options you can give to a Party member work as should be.
Yet again I think this is a v2.5.0 bug and is fixed in later versions.
