### ISSUE TITLE
AsyncPlayerChatEvent NullPointerException

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#729]
USB Version: http://pastebin.com/raw/5AnfEEv3

Just switched from DeluxeChat to ChatControl Pro for chat formatting and started getting spammed with errors every time a player entered a message in chat.

This is the entire error: http://pastebin.com/raw/QSdduxXH

**Comment by rlf** [comment]
Do you have any placeholders defined in the format?

**Comment by BlackBeltPanda** [comment]
Yes, but it also throws the error when I disable the placeholder.
I'm using Clip's PlaceholderAPI's "{uskyblock_island_level}" with ChatControl Pro's interactive (json) chat formatting.

**Comment by rlf** [comment]
Do you have chat-placeholders enabled in the uSkyBlock `config.yml`?
If yes, which ones?

**Comment by BlackBeltPanda** [comment]
Yes, "chatplaceholder" and "servercommandplaceholder".

**Comment by rlf** [comment]
If you are using Clip's PlaceholderAPI's, you probably want to disable those (since they are our native ones, and they are not 100% tested...)

**Comment by rlf** [comment]
But, it would be interesting to figure out where the bug comes from, could you please provide the command or format of the chat-message?

**Comment by BlackBeltPanda** [comment]
Disabling those seems to have fixed it. =)

This is the format as defined in ChatControl Pro's chat.yml file: http://pastebin.com/raw/n8sti8Nk
This is the result of hovering over a player's username: https://i.gyazo.com/fd5f160173a1814c241849d0b07b64cd.png

**Comment by rlf** [comment]
Ye, we left the placeholder code, even though it didn't work as we wanted it to.
I'll take a stab at it.

**Comment by BlackBeltPanda** [comment]
Haven't seen this error since the commit. =)
