### ISSUE TITLE
When you delete inactive Islands Privat in their place remains

### ISSUE THREAD

**Issue by DeltaVetal26** [rlf/uSkyBlock#731]
Good day! Errors in the text do not pay attention, because I write through the translator:D I'm from Russia) the Problem is as follows: when the enter /USB to 30 purge, the Islands are removed, private but in their place remains. As I understand it, the plugin does not remove them into the regions.in yml (this is worldguard 6.1). Then, if the new at this point there is an island, the owner may not build there.. are There any workarounds for this issue? We just have SkyBlock with high tech mods, and lately there have set up such a lot of Islands with plants that the server was the worst run, so you need to clean it from the inactive Islands. Thanks in advance for the answer! - Kcauldron s 201 1.7.10 build 2.5.3 USkyBlock, WorldEdit/worldguard is 6.1

**Comment by dutchy1001** [comment]
I'm sorry but KCaldron is not supported as it gives to many issue's we cant check.

Я сожалею, но KCauldron не поддерживается, поскольку это дает многим вопросам, мы не можем проверить.

**Comment by DeltaVetal26** [comment]
And on another core (spigot/craftbukkit) such problems should not be?

**Comment by dutchy1001** [comment]
indeed, and you can then use Minecraft1.9.2 with all then new stuff

**Comment by DeltaVetal26** [comment]
Well, thank you) will Try it today, while do not close the ticket please:)

**Comment by dutchy1001** [comment]
you can join the test server (uskyblock.redirectme.net) and see, you can also then see our integration with Ultimate Skygrid server.

Ticket can be closed and we can still send messages here.

**Comment by DeltaVetal26** [comment]
Okey)

**Comment by DeltaVetal26** [comment]
I have a question. When you write /purge usb Islands (blocks) removes? Or only the file and Privat? P. s yesterday updated. Privat removes now, but the island itself (blocks) does not remove

**Comment by dutchy1001** [comment]
the islands stay till the area is reused by a new player. When a new player creates an island then the area will be cleared, not before then.
