### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Melowelei** [rlf/uSkyBlock#735]
-How the Shematics need to be ?
-How can i put uSkyBlock in french ?

**Comment by dutchy1001** [comment]
You can make any island you like aslong it contains 1 chest. In older versions we requiered a bedrock but that has been deleted for versions after v2.6.x.
Read this page (http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/localization/) to see how to translate the plugin into French. If you translate it in French and share it with us we can add this to the plugin.

**Comment by Melowelei** [comment]
U say : and place the [country].po in there
But where is the [country].po ?
Or where i can download it and place it in the folder " i18n " ?

**Comment by rlf** [comment]
> Read this page (http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/localization/) to see how to translate the plugin into French

**Comment by Melowelei** [comment]
Soo i need to create an file in my folder i18n and create [french].po ?

**Comment by dutchy1001** [comment]
correct, all is well explained on that page how to do it and were to get the (free) software from

**Comment by Melowelei** [comment]
When i click in fr.po i go here : https://raw.githubusercontent.com/rlf/uSkyBlock/master/uSkyBlock-Core/src/main/po/fr.po
But where i need to copy paste this text ?

**Comment by dutchy1001** [comment]
that file is already made by someone and can be set in the uSkyblock with the command **/usb lang fr**.
If you need to alter that file copy it to your desktop and use the suggested programs to adjust it.

**Comment by Melowelei** [comment]
Thx, u solved my problem ;')

**Comment by dutchy1001** [comment]
np closing the issue

**Comment by Melowelei** [comment]
Hi, i need to delete the basic shematic ? " uSkyBlockNether.shematic "

**Comment by dutchy1001** [comment]
you cant delete the "uSkyBlockNether.shematic" as the plugin will keep adding this to the folder on reload/restart.
I presume you want a custom island for your nether. You can either rename your custom island to the same name as the default (overwriting the file when pasting it into the folder) or, change the schematic name in the config at the nether settings to your custom island.

**Comment by rlf** [comment]
Actually, there are the following ways to "override" the nether-schematic.

* Name the schematic the same as the "overworld" schematic, but append with `Nether` (i.e. `defaultNether.schematic` or `skySMPNether.schematic`)
* Provide your own schematic (ending with Nether) and configure it in `config.yml` under `nether.schematicName` (but without the extension), i.e.:
```yml
nether:
  schematicName: myNether
```
Will load the `schematics/myNether.schematic` schematic when creating nether-islands.

Note: If you do not name it with `Nether` in the end, players will be able to chose it when creating new islands (i.e. as an overworld schematic) - and that will most likely mess things up (i.e. most likely no chest).

As dutchy1001 correctly states, removing the default one will not work, since it will be re-loaded next time your server restarts.

**Comment by Melowelei** [comment]
I worked all this : https://github.com/rlf/uSkyBlock/wiki/Nether-and-uSkyBlock
But my nether is not fuul air with portal, is an normal nether.
Why ?

**Comment by dutchy1001** [comment]
That page is outdated since we added the nether feature. The nether should be generated by the plugin itself, unfortunately there has been a bug in some versions. If you want a nether generating use the latest version on [Github](https://github.com/rlf/uSkyBlock/releases/tag/v2.6.8) this does have an other bug that resets a chunk to much on creating and restarting, but should be OK for the beginning islands to start with. We are hoping to have a fix for this bug soon.

**Comment by Melowelei** [comment]
Nether is correctly generated with /mv tp skyworld_nether, but how player can be tp in this world with her portal nether in her island ?

**Comment by dutchy1001** [comment]
Do you use the plugin Multiverse-NetherPortals and Multiverse-Portals??

**Comment by Melowelei** [comment]
Name: uSkyBlock
Version: 2.6.8
Description : Ultimate SkyBloc v2.6.8-8cdd5b-408
Language: fr (fr)
---------------------
Server: CraftBukkit git-Spigot-0359393-9cd1111 (MC: 1.8.8)
---------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1;no_git_id (ENABLED)
WorldGuarde 6.1 (ENABLED)
Multiverse-Core 2.5-b699 (ENABLED)
Multiverse-Portals 2.5-b725 (ENABLED)
---------------------

I don't use Multiverse-NetherPortals.

**Comment by dutchy1001** [comment]
that is the reason the portals are not working properly then. Use the links on our [bukkitdev](http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/installation/) page for the latest releases or dev builds.
I recommend the dev builds of any MV plugin as well WE and WG

**Comment by Melowelei** [comment]
I need to update my plugins MV WE and WG

**Comment by Melowelei** [comment]
to the latest version ?

**Comment by dutchy1001** [comment]
If you join the test server (uskyblock.redirectme.net) and do the command **/usb version** you see what we use ourselves.

**Comment by Melowelei** [comment]
Im in 1.8 and im not prenium

**Comment by Melowelei** [comment]
I juste take dev build of Mv ?

**Comment by dutchy1001** [comment]
MV-Core build 722
MV-Nether Portals build 712 and
MV-Portlas build 746 
All from 3 May

**Comment by Melowelei** [comment]
I put this in my server and i say u if it's ok

**Comment by dutchy1001** [comment]
those should work fine indeed

**Comment by Melowelei** [comment]
Soo, the problem was just version of my plugins ?

**Comment by dutchy1001** [comment]
and missing the MV-NetherPortals plugin

**Comment by Melowelei** [comment]
Hey ! it work !
But the island start on the top top of the nether, that can be modified with the shematics right ?
How can i modificate the shematics ?

**Comment by SgtLegoTown** [comment]
do you have a nether portal floating under the roof or a island on the roof ?

**Comment by Melowelei** [comment]
I have nether portal floating under the roof, but juste past in the roof.

**Comment by Melowelei** [comment]
I want to have the nether portal at the mid of Roof and lava, how can i do that ?
( Or upload some right shematic with my island )

**Comment by SgtLegoTown** [comment]
try to restart your island and then go to the nether again ...

**Comment by Melowelei** [comment]
Yes i have it, but i spawn under the roof and island is below, but if u jump u die ..

**Comment by Melowelei** [comment]
Like that : http://www.noelshack.com/2016-19-1462914078-2016-05-10-22-58-38.png

**Comment by dutchy1001** [comment]
you might need to delete your island with the command **/usb island delete [name]**, then create a new island.

**Comment by Melowelei** [comment]
It's ok, for the shematics that i want to modificate, i need to take my island with world edit but don't do //expand vert ?
And it will be on the middle and not under the roof right ?

**Comment by dutchy1001** [comment]
when creating your custom island you only need the area that covers that island, nothing more. The smaller the schematic is the better, extra air doent need to be copied for this (if that makes any sense).

**Comment by Melowelei** [comment]
Hi, why i only respawn on the world " Skyworld " when i die and never and the world set with mv in the config " Respaw world " ?

**Comment by SgtLegoTown** [comment]
sendToSpawn: true / false in the usb config

there you can decide where to send your players

**Comment by Melowelei** [comment]
With     sendToSpawn: true, he didn't go in the /spawn

**Comment by dutchy1001** [comment]
do you have a plugin, like EssentialsSpawn, on your server?? If not that is needed.

**Comment by Melowelei** [comment]
I have EssentialsSpawn
And plugin for the /setspawn and /spawn

**Comment by dutchy1001** [comment]
have you restarted the server since you changed the config?

**Comment by Melowelei** [comment]
Yes

**Comment by SgtLegoTown** [comment]
you also set the /mvsetspawn for the multiverse multiworld spawn ?

**Comment by Melowelei** [comment]
Yes

**Comment by dutchy1001** [comment]
use **_/setspawn_** (_that is the essentials command_) on the main world you want the players to spawn after they die. This works correct on my sever.

**Comment by Melowelei** [comment]
It work, i forget the '' in my mv config.
Like this    respawnWorld: 'nameWorld'
and not like this    respawnWorld: NameWorld

Thx for ur help, im realy soory :/

**Comment by dutchy1001** [comment]
> And plugin for the /setspawn and /spawn

what plugin you use for that then??
The way you say this you tel me believe that you got an other plugin that controles your /spawn commands.

**Comment by dutchy1001** [comment]
we leave the MV settings on default and dont mess with it, if left alone EssentialsSpawn does it's job as it should.
