### ISSUE TITLE
custom set biome

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#737]
Is it possible to add a config option to set the default biome?

**Comment by rlf** [comment]
Sure is! :D

**Comment by supertin** [comment]
I managed to work around this for now by changing the static biome name in SkyBlockChunkGenerator.java... But long term it would helpful to have this feature still so I don't need to manually build any new versions.

Have you looked into it yet? I'm starting to get a bit of an understanding on this plugin how it works, so I might be able to have a go at it if you haven't even thought about it yet - I just don't think my coding standards will live up to yours :wink:

**Comment by SgtLegoTown** [comment]
it will be taken into next release see the note of rtl : 

""rlf added this to the next minor release milestone 16 days ago ""

I hope this information helps you
