### ISSUE TITLE
can't build due to AWE  maven repo unavail

### ISSUE THREAD

**Issue by woolwind** [rlf/uSkyBlock#740]
[ERROR] Failed to execute goal on project uSkyBlock-AWE330: Could not resolve dependencies for project uSkyBlock:uSkyBlock-AWE330:jar:2.6.0-SNAPSHOT: Failure to find org.primesoft.asyncworldedit:AsyncWorldEdit-API:jar:1.1.0 in https://raw.github.com/SBPrime/AsyncWorldEdit-Premium/maven-artifact/ 

nosing around, it sounds like this was made private

**Comment by SgtLegoTown** [comment]
I just did a fresh git clone and a mvn fresh install with as result:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] po-utils ........................................... SUCCESS [  6.769 s]
[INFO] bukkit-utils ....................................... SUCCESS [  2.020 s]
[INFO] uSkyBlock-API ...................................... SUCCESS [  0.748 s]
[INFO] Ultimate Skyblock .................................. SUCCESS [  0.122 s]
[INFO] uSkyBlock-Core ..................................... SUCCESS [ 21.044 s]
[INFO] uSkyBlock-AWE211 ................................... SUCCESS [  0.726 s]
[INFO] uSkyBlock-AWE311 ................................... SUCCESS [  0.406 s]
[INFO] uSkyBlock-AWE321 ................................... SUCCESS [  0.454 s]
[INFO] uSkyBlock-Plugin ................................... SUCCESS [  4.578 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.136 s
[INFO] Finished at: 2016-05-16T23:39:20+02:00
[INFO] Final Memory: 47M/320M
[INFO] ------------------------------------------------------------------------

Gebruiker@GEBRUIK-A2ND33R MINGW64 ~/uSkyBlock (master)

**Comment by woolwind** [comment]
why isn't it building AWE3.3.0?

[INFO] po-utils ........................................... SUCCESS [  1.537 s]
[INFO] bukkit-utils ....................................... SUCCESS [  0.643 s]
[INFO] uSkyBlock-API ...................................... SUCCESS [  0.882 s]
[INFO] Ultimate Skyblock .................................. SUCCESS [  0.036 s]
[INFO] uSkyBlock-Core ..................................... SUCCESS [  6.070 s]
[INFO] uSkyBlock-AWE211 ................................... SUCCESS [  0.101 s]
[INFO] uSkyBlock-AWE311 ................................... SUCCESS [  0.021 s]
[INFO] uSkyBlock-AWE321 ................................... SUCCESS [  0.023 s]
[INFO] uSkyBlock-AWE330 ................................... FAILURE [  0.013 s]
[INFO] uSkyBlock-Plugin ................................... SKIPPED

**Comment by SgtLegoTown** [comment]
I just did a fresh clone of git clone )uskyblock link)

then I complied trough Gitbash if it stays a problem it gives me a successful build 

Gebruiker@GEBRUIK-A2ND33R MINGW64 ~/uSkyBlock (master)
$ mvn clean install

I did remove all old stuff first probably the 330 dir is still in your work space so remove
the uskyblock dir and do a fresh clone request

**Comment by SgtLegoTown** [comment]
your correct i' am wrong I had a old version (wrong dir i used I got  the 2.50 version) the 2.6.0 version gives the error my apologies ..

**Comment by SgtLegoTown** [comment]
I do think this is more r4z his territory I will try to see if I can figure it out ..

**Comment by SgtLegoTown** [comment]
tried source code from till 2.6.8 all same results awe in not reachable

**Comment by woolwind** [comment]
yah.  alas, I think my pull request isn't quite right but since I can't complete a build I can't validate it :-p

**Comment by rlf** [comment]
Ye, it seems SBPrime has yet again just fckd us without regard to anyone depending on him.

He moved the API to a separate repo.
https://github.com/SBPrime/AsyncWorldEdit-Premium/commit/e69e311a007def72dd8c9c530f5be6b906e1410f

Need to adjust the repo references in the pom.xml files to point to the new path.

**Comment by dutchy1001** [comment]
Think rlf has adjusted the depending repo so this can be closed
