### ISSUE TITLE
b

### ISSUE THREAD

**Issue by Melowelei** [rlf/uSkyBlock#743]
b

**Comment by SgtLegoTown** [comment]
usb.schematic.[schematic-name] 

A player with this permission will use the given "schematic" when creating a new island. The schematic must be in the uSkyBlock/schematics folder. Do not include the .schematic extension in the permission name 

you can find this on the bucket page : 

http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/commands-and-permissions/

**Comment by dutchy1001** [comment]
If you had a look at the config you would find the "island-schemes" section were islands can be added with all the needed value's and permissions. By default the "default" island has the same permission as  what a player needs to create an island (usb.island.create). 
As you probably have added your own custom island but failed to change or even add this to the config your players will get the message " You do not have permission for this schematic".

To fix this, look at the config and copy/paste the default island-scheme. Rename default to your own custom name and add/change the value's as you like. Reload (/usb reload) the plugin and if all is set right it should work.

**Comment by Melowelei** [comment]
Hi, thx.
But how can i remove en the /is GUI when the player don't have island all shematics excepte my schematics?
And why he can't place lava in her island ?!

**Comment by SgtLegoTown** [comment]
let me guess you have essentials and lava is a protected item .. try the essentials config there is a excellent explanation do I need to google that also ? for you ?

**Comment by Melowelei** [comment]
It is that ?
  # General physics/behavior modifications.
  prevent:
    lava-flow: false

**Comment by dutchy1001** [comment]
the option to show or not show is in the _island-schemes_ section
```yml
    # optional, default true (true enabled in GUI, false disabled in GUI)
    enabled: true
```

**Comment by Melowelei** [comment]
The skySMP stay, but the default is removed.
I don't watn this skySMP too

**Comment by dutchy1001** [comment]
then add
```yml
    enabled: false
```

When it says in the explanation ```# optional, default true ``` it means if this is not added to the island settings in the config it will automatic be set to **true**, meaning it will show.

**Comment by Melowelei** [comment]
Like this : 
  skySMP:
    permission: usb.schematic.skysmp
    description: The original SkySMP island
    displayItem: GRASS
    extraItems: OBSIDIAN:14 FLINT_AND_STEEL:1
    enabled: false

?

**Comment by Melowelei** [comment]
Yes is like this, 
Thx bro u can close this isue

**Comment by dutchy1001** [comment]
original post deleted by OP.
closed
