### ISSUE TITLE
" No Chest Found "

### ISSUE THREAD

**Issue by Melowelei** [rlf/uSkyBlock#748]
Hi,
I work /is create and then : 
Ur island is ready, wait ... 
and then nothing, why ?
Im waiting like 10-15Mins..

**Comment by Melowelei** [comment]
No chest, but a chest is here. I don't know why he say that..

**Comment by dutchy1001** [comment]
I'm sorry but your not explaining yourself very well. Start with posting the **/usb version** and through [pastebin](http://pastebin.com/) the logs if they have any errors.

**Comment by SgtLegoTown** [comment]
what us the error you get and pls give us the information requested same as last time ..

**Comment by Melowelei** [comment]
More info ?
He is searching an coffre, but he don't found, and in my schematics he is an chest.

**Comment by dutchy1001** [comment]
Now I lost it, you need to use a better translator as this doesn't make sense. 

As said post the **/usb version** output first. Maybe a picture of the island your trying to use too.

**Comment by Melowelei** [comment]
Hi,
This is my island schematics : 
![gfv](https://cloud.githubusercontent.com/assets/18491206/15410719/9d664d24-1e1b-11e6-9706-2f3bf64a2099.PNG
And this is my /usb version : 
![gtfrcd](https://cloud.githubusercontent.com/assets/18491206/15410728/a6679c52-1e1b-11e6-8dc8-237581989442.PNG)

**Comment by supertin** [comment]
Could you post a copy of the actual .schematic file you are using?

**Comment by Melowelei** [comment]
How can i upload this file here ?

**Comment by dutchy1001** [comment]
try this site [here](https://mega.nz/)

**Comment by Melowelei** [comment]
can't

**Comment by Melowelei** [comment]
Here is my schematics : https://mega.nz/#!NRpxVTrS

**Comment by supertin** [comment]
Decryption key?

**Comment by Melowelei** [comment]
Where did i get it ?

**Comment by supertin** [comment]
I assume it would have asked you to enter one when you uploaded the file.

**Comment by Melowelei** [comment]
https://mega.nz/#!9MwBwAgZ here i think u don't need one

**Comment by Melowelei** [comment]
Decryption key : yRKslDwrULCuYtXXMvOwdA

**Comment by supertin** [comment]
Still not working. Maybe try another file sharing site?

**Comment by SgtLegoTown** [comment]
in stead of sending schematics maybe smart to see where your bedrock is and 1 empty chest ? 
and did you make the schematic with awe or fawe and now pasting it normal ? you made the schematic or is it downloaded .. ?

**Comment by Melowelei** [comment]
http://www.sendbox.fr/1420875cc52d2941/SkyBlockStarting.schematic

**Comment by Melowelei** [comment]
I made it, u said me in other issue, in my version don't need to put 1 Bedrock.

**Comment by SgtLegoTown** [comment]
bed rock is handy to put in when ever you want to change owner as a admin ..

**Comment by dutchy1001** [comment]
in v2.6.8 there is no need for a bedrock. Just wondering, did you use normal chest or a trapped chest??

**Comment by Melowelei** [comment]
Normal Chest

**Comment by SgtLegoTown** [comment]
where is the single empty chest I get inside the island and don't see a empty chest

**Comment by Melowelei** [comment]
What ? an chest is IN my island ?

**Comment by SgtLegoTown** [comment]
there is a emptu space in your island when I test this schematic ill end up there

**Comment by Melowelei** [comment]
He can't be like that ?

**Comment by dutchy1001** [comment]
when you saved the schematic you didnt stand on the island but was floating in mid air, redo the schematic save of the island standing in front the chest might be better.

**Comment by Melowelei** [comment]
And why animals on island is not saved on the schematics ?

**Comment by SgtLegoTown** [comment]
by biome spawning on grass land also has to do with the size of your island

**Comment by Melowelei** [comment]
When i put the new schematics, /usb reload and i test it ?

**Comment by SgtLegoTown** [comment]
I have redone your schematic and tested on my test server and it works when done what dutchy1001 says http://www.uskyblock.net/downloads/uskytestis.schematic

**Comment by Melowelei** [comment]
Yes, he work now !

**Comment by Melowelei** [comment]
Can u delete the link or replace by  " (Private Link) " ?

**Comment by SgtLegoTown** [comment]
I deleted the schematic I have no use for it

**Comment by Melowelei** [comment]
Yes but in the world we can have some bastard guy, so if u can delete ur link please x)

**Comment by SgtLegoTown** [comment]
the link doesn't work ????

**Comment by dutchy1001** [comment]
posts with your link has been deleted.

**Comment by SgtLegoTown** [comment]
maybe better to not self post link with download codes too then more ppl are reading this ..

**Comment by Melowelei** [comment]
ppl can understand with link or not x)

**Comment by Melowelei** [comment]
This is my shematics ? : 
 SgtLegoTown commented 8 minutes ago

I have redone your schematic and tested on my test server and it works when done what dutchy1001 says http://www.uskyblock.net/downloads/uskytestis.schematic

**Comment by SgtLegoTown** [comment]
since the problem is solved all downloads are removed on my side I think I can go do other thing glad it works now

**Comment by SgtLegoTown** [comment]
since the problem is solved I close the topic as solved
