### ISSUE TITLE
Challenge resetInHours overflows above 596 hours

### ISSUE THREAD

**Issue by supertin** [rlf/uSkyBlock#749]
In challenges.yml, setting resetInHours to 596 hours works perfectly. 597 hours breaks.
Java max int converts to approx 596.52 hours if you store milliseconds. I think this is not a coincidence :smile:

While 596 hours looks like a big number, it's only 24 days. I had great plans to make some of my bigger rewarding tasks reset their requirements at 30 or even 60 days.

There is no warning or error when this happens either, and no mention of a limit in the default challenges.yml, which has caused me to spend many nights over the last 2 weeks trying to figure out why some of my repeat challenges were going strange.

I tried to find where an int is getting used, but couldn't see anything.

**Comment by rlf** [comment]
Most likely in the yml storing/reading.

Sounds like a bug.

**Comment by supertin** [comment]
Any chance of a build with the changes made?
I'd been building the plugin just fine, but now Maven's complaining about not being able to download stuff from krinsoft.net, which I gather is Vault having an old broken reference. And I don't understand Maven enough to work around it.

**Comment by SgtLegoTown** [comment]
what error you get I only see 👍 
\Challenge.java:[190,53] error: possible loss of precision
after if I read the topic I have a high chance that r4z is working on this issue

so can you make a pastebin of the error you get ?

**Comment by rlf** [comment]
Tagged a release https://github.com/rlf/uSkyBlock/releases/tag/v2.6.9
Should be ready within 10-20 minutes (once Travis-CI is done building it - unless it fails with the Vault dependency too ofc.)

**Comment by supertin** [comment]
Build failed. Same error sgtlegotown mentioned. I'm no expert but line 190 is very similar to 187, except without the brackets. Would that do it? 

Also, my build attempts didn't even get that far. The krinsoft fails were actual ERROR lines, not warnings for me.

**Comment by woolwind** [comment]
I get this compile error with the current source code:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project uSkyBlock-Core: Compilation failure
[ERROR] /Users/lizr/git/uSkyBlock/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/challenge/Challenge.java:[190,53] error: incompatible types: possible lossy conversion from long to int

**Comment by supertin** [comment]
I think we can mark this one as solved.... The 2.6.9 build is letting me to huge values (87,600,000 hours works now, which is about ten thousand years).
Thanks everyone :smile:

**Comment by dutchy1001** [comment]
thanks for letting us know, I will close this issue.
