### ISSUE TITLE
Island Party Not working

### ISSUE THREAD

**Issue by ItsShadowFang** [rlf/uSkyBlock#754]
Hi there,

The party system is not working at all, Every island a player makes says it is full and when you hover over the island group in the gui it says 1/0 members. Please see the screenshot.
![minecraft 1 8 2016-05-26 15 35 31](https://cloud.githubusercontent.com/assets/12955896/15578396/33a3a502-2358-11e6-87e6-d94a43ea7500.png)
I have given them the permissions
- usb.island.*
- usb.party.*
- usb.extra.partysize
However none of these have seemed to help. This is my config for uSkyBlock
http://pastebin.com/YqTW6XDC

I hope you can help

**Comment by SgtLegoTown** [comment]
can you bast a /usb v for additional information pls

**Comment by ItsShadowFang** [comment]
![minecraft 1 8 2016-05-26 17 45 31](https://cloud.githubusercontent.com/assets/12955896/15582592/ae178bd0-2369-11e6-9a03-c872f20e99ba.png)

**Comment by SgtLegoTown** [comment]
- usb.party.create
    - usb.party.join
    - usb.party.kick
    - usb.party.leave
    - usb.party.talk

are the permissions I use
and copied your config and works well no errors 

![2016-05-26_18 44 50](https://cloud.githubusercontent.com/assets/15387810/15582726/b5c2673e-2372-11e6-9123-0b6886ba24cb.png)

**Comment by SgtLegoTown** [comment]
usb.extra.partysize However none of these have seemed to help I just saw that you know that is a custom permission you have to set up ?
Custom Permissions

There are 2 custom made permissions you can add yourself.
 The first one can be added in the "extraPermissions:"section and are build up as followed:

    extraPermissions:
      smallbonus: '4:16 320:5'          #<---gives these items extra in the chest at start or restart
      GiveItYourOwnName: '50:16 327:1'  #<---gives these items extra in the chest at start or restart

The permissions that are used here would then look like 
•usb.smallbonus 
•usb.GiveItYourOwnName

 The second one can be added to the "maxPartyPermissions:" section and is build up as followed:

  party:
    maxPartyPermissions:
      usb:
        extra:
          partysize1: 5           #<---gives a max of 5 players on your island
         GiveItYourOwnNameX: 123  #<---gives a max of 123 players on your island

The permissions that are used here would then look like 
•usb.extra.partysize1 
•usb.extra.GiveItYourOwnNameX

In both cases you can add as many permissions as you like or need, but make sure they all have their unique name.

this explanation can be found on 👍

http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/commands-and-permissions/

**Comment by rlf** [comment]
@ItsShadowFang Could you please provide the FULL output of `/usb version` - we need the first lines as well to see what version you are experiencing the issue on.

**Comment by SgtLegoTown** [comment]
second test with release 2.6.4

[20:45:17 INFO]: Name: uSkyBlock
[20:45:17 INFO]: Version: 2.6.4
[20:45:17 INFO]: Description: Ultimate SkyBlock v2.6.4-bd1c2b-404
[20:45:17 INFO]: Language: en (en)
[20:45:17 INFO]: ------------------------------
[20:45:17 INFO]: Server: Paper git-Paper-756 (MC: 1.9.4)
[20:45:17 INFO]: ------------------------------
[20:45:17 INFO]: Vault 1.5.6-b49 (ENABLED)
[20:45:17 INFO]: WorldEdit 6.1.3-SNAPSHOT;3547-fd0e400 (ENABLED)
[20:45:17 INFO]: WorldGuard 6.1.2-SNAPSHOT;1660-15a9c50 (ENABLED)
[20:45:17 INFO]: Multiverse-Core 2.5.0-SNAPSHOT-b722 (ENABLED)
[20:45:17 INFO]: Multiverse-Portals 2.5.0-SNAPSHOT-b746 (ENABLED)
[20:45:17 INFO]: Multiverse-NetherPortals 2.5.0-SNAPSHOT-b712 (ENABLED)


result with 
![2016-05-26_20 44 11](https://cloud.githubusercontent.com/assets/15387810/15586112/f5d048cc-2382-11e6-890a-0cce4385e088.png)
your pasted config :/is

**Comment by ItsShadowFang** [comment]
I have just tried it with your suggestions and again it's not working. I added the party extra permission when I had made the custom one and that still didn't work.

I have all of these permissions currently and again not working. I tried it on 2.6.4 and 2.6.8
    - usb.party.create
    - usb.party.join
    - usb.party.kick
    - usb.party.leave
    - usb.party.talk
    - usb.lock
    - usb.island.*

![minecraft 1 8 2016-05-26 22 51 48](https://cloud.githubusercontent.com/assets/12955896/15591390/c579f0e4-2394-11e6-8d7f-d544f93c605b.png)
![minecraft 1 8 2016-05-26 22 52 08](https://cloud.githubusercontent.com/assets/12955896/15591389/c5779d4e-2394-11e6-8c4d-370b489ef8ac.png)

**Comment by SgtLegoTown** [comment]
just out of curiosity since I see u use a hacked client you also modded the server ?

and what permission system you use ?

**Comment by ItsShadowFang** [comment]
I only use the hacked client to take control of my accounts to make it easier to switch them.
The server is standard spigot. I am currently using Pex

**Comment by SgtLegoTown** [comment]
have you tried with a normal client and thought about other party plugins because I did 6 test now with the by you provided information and cant find any usb issue tbh an not any report with those setup have the same so look what is different like other plugins modifications .. etc

**Comment by ItsShadowFang** [comment]
Just tried it with a normal client and still the same issue
I have no idea what is causing it, It's really annoying because people can't share islands at all. I even deleted everything and started again from scratch but it's still happenning.

I have no idea why. It's not the party it's the sharing Islands I need.

I tried removing my config and trying it with a fresh config and everything works completely fine. so I believe it is something wrong with my config

**Comment by SgtLegoTown** [comment]
can you five me your server information so I can see the plugins u use sounds more like a conflict ..

**Comment by ItsShadowFang** [comment]
oooh I think I've found what the issue was. Where I have added my own Schematics, I had not specified the max party size there. I added it to the bottom and it seems to be working for now

`  Easy:
    enabled: true
    index: 2
    permission: usb.island.create
    description: This island is for the people that like skyblock but hate starting off, so we have decided to give you a little head start! =)
    displayItem: GRASS
    maxPartySize: 8`

**Comment by SgtLegoTown** [comment]
so with the default island it worked ? it where the customs only not working glad its solved if there is anything else let us know. since it solved I will close the topic
