### ISSUE TITLE
IslandCommand

### ISSUE THREAD

**Issue by Victhetiger** [rlf/uSkyBlock#759]
I was wondering if there was any way to lower the impact from running /island command on my server.

http://prntscr.com/bca5s9

Sincerely,
Victhetiger

**Comment by SgtLegoTown** [comment]
just out of curiosity what's the out put of your /usb version 
and how much ram you have available for your server ? 
how many plugins do you run
with how many players ?
pls provide some basic information pls

**Comment by rlf** [comment]
The island command is the primary command.
We need much more info for this to make any sense.
Could you please share the full timings report?

**Comment by Victhetiger** [comment]
My mistake, I'll get those information right now.

  Output: 
  RAM: 6GB

**Comment by Victhetiger** [comment]
Here you go: https://timings.aikar.co/v2/?id=8ef31fbf97a04b02a66efb17759dcfbc

**Comment by rlf** [comment]
There is nothing wrong (IMO) with those timings.
They are as can be expected, and not alarming at all.

What exactly do you feel is taking too long time? We've put alot of effort into getting the plugin to be as performant as possible - though some things cannot be avoided - i.e. when doing island-score-calculations and similar.

**Comment by Victhetiger** [comment]
I'm not too familiar with how timings are calculated and how ticks generally work, although, when there's red it usually means it's a bad thing.

It could also be on my side, this CPU isn't one of those 4th Generations Intels but I guess it's fine as is. 

I was mainly asking this to know if there was some performance tweaks within the plugin.

**Comment by Victhetiger** [comment]
Instead of opening a new issue, I had a quick question: Does the plugin support FastAWE? https://www.spigotmc.org/resources/free-fast-async-worldedit-voxelsniper-%CE%B2eta.13932/

**Comment by SgtLegoTown** [comment]
I have tested with Fawe it does works it doesn't hook like awe and has some bugs not related to USB like flowing water will be pasted as not loting water for the rest it works but for this bugs you best can go to the maker of Fawe 
It does works Next too USB for so far I could test  with 2.6.4 and 2.6.9

**Comment by Victhetiger** [comment]
Thank you very much. To make it work do I have to simple enable AWE support in the USB config?

**Comment by SgtLegoTown** [comment]
No pls disable awe in your config since it cause the issue's you hade and Fawe and Awe are to different plugins with a look-alike name ...  so nothing to do with the awe setting ..

**Comment by Victhetiger** [comment]
Alright, thank you :+1:

**Comment by Victhetiger** [comment]
It seems like your plugin is having problems with FAWE or something like it. https://github.com/boy0001/FastAsyncWorldedit/issues/143 and https://timings.aikar.co/v2/?id=3d51a5696f2a482a9098dd8b3f9291bd. If you read the main post you"ll see my issue.

**Comment by Victhetiger** [comment]
If this can't be fixed within today I'll uninstall FAWE since USkyblock doesn't seem completely compatible with it. Tomorrow is advertising day and I need it to be stable.

**Comment by Victhetiger** [comment]
The incompatibility as been fixed by FAWE's author.

**Comment by boy0001** [comment]
(fawe dev)
Some recommendations:
 - Don't create thousands of EditSessions and then not use them

Also if FAWE is present you can use the EditSession and such in an async runnable.

**Comment by SgtLegoTown** [comment]
what's not compatible I have it running from its release .. on my server ? some fact please ...

**Comment by rlf** [comment]
@boy0001 We currently have no FAWE integration, but if you have some suggestions as to how to improve our WE integration, I'd be happy to hear them!

It's been a real pain to find a way to get it to just perform decently, esp. when "clearing" islands that are not chunk-aligned, without getting servers to lag.

@Victhetiger Performing profiling (as you are effectively doing using the `/timings` spigot command), you should generally time a larger period of time, to get sensible values.
Your reports are very short, meaning the statistical data at your disposal is very small, again, giving you huge percentage-calculations for commands that are inheritantly "heavy".

The first post you made indicated some "red-numbers" - but if you drill-down, they stem from Chunk-Loading, something USB will facilitate, but cannot really do anything with reg. performance.

Generally speaking, we try to never use more than 50% of a tick (25 ms), when doing performance heavy stuff on the server-thread, but sometimes we cannot avoid this (i.e. chunk-loading and WE-pasting).

If you want some realistic timing-reports, activate it, use the plugin for 5-10 minutes, and do the paste.

If we have red numbers, esp. with high "counts", we have performance issues.

**Comment by boy0001** [comment]
@rlf
You load the schematic from disk each time an island is reset (i.e. the run() method in WEPasteSchematic). You should be doing this async.

You could reuse the same EditSession each time a chunk is regenerated/set the blocks for a region, and flush the queue etc. when it is all done. 

If you want, also add a check to see if FastAsyncWorldEdit is installed, in which case you can run all the WorldEdit code from an async bukkit runnable.

**Comment by rlf** [comment]
Well, we tried that (the wait till end with flush), but then we got server lag when calling flush.

Currently we break up all the WE actions we can break up (clearing a region primarily, or regen), into smaller regions, so we can flush each "operation", and get WE to correctly place torches etc. when doing "non-chunk-aligned" resetting.

When we re-used the session, all the operations were postponed till the flush, leading to server-lag when we called flush.

We can, how-ever, probably re-use the EditSession object, and then call flush multiple times, that might improve performance, or, as you state, make a FAWE integration.

Our previous experience with this approach for AWE was not successful though. It still caused server-lag, and it was still blamed on our plugin.

**Comment by rlf** [comment]
Does FAWE support "plugins" executing commands (i.e. can we get a programmatic FawePlayer?) - because we need this for our plugin. We do not want to do the WE operations as a user - since users will not neccesarily have WE permissions. We want to either do it as Console, or as a Plugin.

We also need (would like to), get an indication back (event, callable, callback, what-ever), when the "job" we queue has been successfully completed (so we can port the player back to the newly created/cleared island).

Is this possible in any sensible way using FAWE?

**Comment by Victhetiger** [comment]
@rlf Thank you, but as I wanted to reply to the thread as quick as I could I cut down on the time of the timings. Next time I post an issue I'll be sure to post a full timings report.

**Comment by Victhetiger** [comment]
URGENT: I do not know what's wrong when creating an island but it does this: http://prntscr.com/bd6em6

**Comment by Victhetiger** [comment]
Everything is broken, people get islands on other's islands and there's nothing in the chests.

**Comment by Talabrek** [comment]
I just started using FAWE on my server over a week ago and I haven't noticed any problems running it and uSkyBlock together. The speed and performance are amazing compared to standard WE or AWE...Gigantic islands copy in seconds with no noticeable performance hit. It would be nice if we could integrate it with uSkyBlock.

**Comment by boy0001** [comment]
@rlf
FAWE modifies WorldEdit to make it faster / thread safe. It has some additional functionality, but for what you want (pasting a schematic) you will still just be dealing with the same WorldEdit API. The only difference is you will be doing it all from another thread so it won't impact server performance at all. 

It isn't like AWE where you need to use some custom `ThreadSafeEditSession`, with FAWE the normal EditSession is made thread safe, along with other default WorldEdit classes. 

```Java
new BukkitRunnable() {
    @Override
    public void run() {
        // Something like this I think:
        // Note: If the schematic is a constant, load it during startup instead of each island reset
        SchematicFormat.getFormat(file).load(file).paste(editSession, position, false, true);
        editSession.flushQueue();
        callback.run();
    }
}.runTaskAsynchronously(plugin);
```

See also:
https://github.com/boy0001/FastAsyncWorldedit/wiki/API

**Comment by rlf** [comment]
Sounds great. I will take a look at it then, if it's just testing to see if FAWE is present, and do the thing on Async, it should be a piece of cake to add.
All though we won't be able to send "progress-updates" back to the user, if it's as fast as Tala says, it shouldn't be needed.

**Comment by rlf** [comment]
Added new issue, since this will most likely be closed soon due to misconfiguration ;-)
