### ISSUE TITLE
Player Loses Island Upon /usb restart

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#762]
I haven't updated skyblock for awhile, so I decided to start new. This was a clean install. I am using USB version 2.6.10. If I create an island and do /usb reload, the server will then say that I don't own an island and force me to make a new one. This happens everytime the command /usb reload is done. In the "islands" folder, the islands are remembered, but in the "players" folder, ownership of the island is forgotten. What this leads to is a bunch of skyblock islands that you can't delete but that nobody can really get to.

**Comment by SgtLegoTown** [comment]
I can confirm this same happens with a server restart .. r4z is aware of it and looking in too it

**Comment by TheMattVid** [comment]
Will I be able to use this plugin without worrying that everyone will have to create a new island after every restart? If not, that's a major issue.

**Comment by TheMattVid** [comment]
It would seem that the solution to this problem would be to update the player's yml file immediately upon island creation. It doesn't do it for some reason.

**Comment by dutchy1001** [comment]
V2.6.10 is a pre-release and can still have bugs. These versions are not meant to be used in a production server yet.
We are aware of the issue you mentioned above as SgtlegoTown already said.

**Comment by rlf** [comment]
Ready for test on next release (v2.6.11)

**Comment by dutchy1001** [comment]
This is fixed in v2.6.12, let us know if you come to the same conclusion.

**Comment by i9hdkill** [comment]
Bug seems to be fixed in 2.6.12.
Waiting for @TheMattVid to confirm

**Comment by TheMattVid** [comment]
Confirmed
