### ISSUE TITLE
[Suggestion] Schematic Handicap Level

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#763]
Would be awesome to be able to specify a handicap level for certain schematics to add/remove island levels.
For example, schematic A could have a handicap of 100, giving that island an extra 100 island levels.
Schematic B could have a handicap of -50, giving that island 50 less levels.

This could be extremely useful for balancing island levels between varying schematics, giving players the ability to use cooler islands without having an unfair advantage.

**Comment by rlf** [comment]
This should be doable. Since it's just a simple offset added to the actual island-score.

**Comment by dutchy1001** [comment]
Tested a dev version with this feature added
3 the same islands (the default usb island):

**island 1:**
Multiplier 0
extra level points 0
default level 1.91

**island 2:**
Multiplier 0.5
extra level points 40
island level 40.95 _= 40 from extra level points + multiplier 0.5 x 1.91 = 0.95_

**island 3:**
multiplier 0.9
extra level points 100
island level 101.72 _= 100 from extra level points + multiplier 0.9 x 1.91 =1.72_

Think we got an awesome new feature here

**Comment by BlackBeltPanda** [comment]
Nice =D
Does it cap the minimum level at 0 or will it go into the negatives if the offset is negatively too large?

**Comment by Talabrek** [comment]
I like this idea. How about expanding on this and also adding mod commands to set, add to, and subtract from the offset and multiplier for each island after it is created?

This way bonus island levels could be given out as a reward for completing challenges, voting, etc.

**Comment by dutchy1001** [comment]
I didn't test with negative value's as it was getting late. I will do this later today and let you guys know.

**Comment by dutchy1001** [comment]
Just tested this with negative value's which work just aswell.

**Comment by rlf** [comment]
a) Not capped (meaning you might get a negative score).
b) I see your point - BUT, then we need to store the values on the island - which might be ok, might not... not sure...

We could make them accumulatitive or additive.

I.e. the schematic has a multiplier + offset, but so can the island.

So say schem A has m=0.9, o=-100, and the island has m=1.1 and o=50, then the score will be
```
  (additive)
  score = blockScore*0.9*1.1 - 100 + 50
or
  (accumulative)
  score = (blockScore*0.9 - 100)*1.1 + 50
```
Depending on how we decide to go...

**Comment by rlf** [comment]
Ok, I added a scoreMultiplier and a scoreOffset to the IslandInfo as well.

Usage is not for the faint-hearted though, and requires some permissions in the `usb.admin.set` and `usb.admin.get`.

To read the score, do:
```
/usb island get R4zorax scoreMultiplier
```
To set the multiplier (and offset) do something along these lines:
```
/usb island set R4zorax scoreMultiplier 1.1
/usb island set R4zorax scoreOffset -50
```
If used in challenges rewards (see https://github.com/rlf/uSkyBlock/wiki/commands-in-config), do something along these lines:
```
  reward:
    commands:
      - console:usb island set {player} scoreMultiplier 1.1
      - console:usb island set {player} scoreOffset 42
```
***Note:*** The score will only be adjusted once it's completely calculated, meaning the `activate-at` config param in `config.yml` will be used on the un-adjusted score.
