### ISSUE TITLE
Player hangs in the air

### ISSUE THREAD

**Issue by VENT0** [rlf/uSkyBlock#765]
Hi everyone. When a player creates his own island sometimes happens a bug - player hangs in the air and he cant move. It happens often when player restart his island. But at the same time other players can create and restart their islands. My server is KCauldron 1.7.10. Plugin version uSkyblock v2.5.3 for Bukkit 1.7.9.

Thanks in advance.

**Comment by SgtLegoTown** [comment]
I cant help you with this one. 
kcauldron isn't supported any more due the many differences and many problems

**Comment by VENT0** [comment]
Ok, thanks. One another question, plugin v2.6.4 will work on 1.7.10 correctly?

**Comment by SgtLegoTown** [comment]
no version uSkyblock v2.5.3 for Bukkit 1.7.9 is special for bucket 1,7.9  version 2.6.4 is up tp 1.9

you can see all the version and downloads on : 

http://dev.bukkit.org/bukkit-plugins/uskyblock/files/
