### ISSUE TITLE
Schematic problem

### ISSUE THREAD

**Issue by jesseke55** [rlf/uSkyBlock#770]
_Please paste the output from `/usb version` below_
[11:33:35 INFO]: Name: uSkyBlock
[11:33:35 INFO]: Version: 2.6.12
[11:33:35 INFO]: Description: Ultimate SkyBlock v2.6.12-9e2d30-413
[11:33:35 INFO]: Language: en (en)
[11:33:35 INFO]: ------------------------------
[11:33:35 INFO]: Server: CraftBukkit git-Spigot-3ccadba-fb568fd (MC: 1.10)
[11:33:35 INFO]: ------------------------------
[11:33:35 INFO]: Vault 1.5.6-b49 (ENABLED)
[11:33:35 INFO]: WorldEdit 6.1.3-SNAPSHOT;3558-5a42a8d (ENABLED)
[11:33:35 INFO]: WorldGuard 6.1.2;e38d98d (ENABLED)
[11:33:35 INFO]: Multiverse-Core 2.5.0-SNAPSHOT-b722 (ENABLED)
[11:33:35 INFO]: ------------------------------

version goes here
2.6.12

_What steps will reproduce the problem?_
1. Restarts
2. config reset
3. full config reset

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: http://pastebin.com/nrtumnis

I am just trying to create multiple schematics but it doesn`t do anything (After multiple restarts)

**Comment by Azoraqua** [comment]
@jesseke55 Are the schematics valid and placed in the schematics folder? Also did you register them in the configuration file? 

**Example:** [Click here.](http://hastebin.com/uxevaxoger.vbs)

**Comment by jesseke55** [comment]
@Azoraqua Config format: http://i.imgur.com/EebKoAH.png

**Comment by Azoraqua** [comment]
@jesseke55 Is there any more data about it? As of my seeing, the config isn't valid, I believe.

**Comment by jesseke55** [comment]
@Azoraqua config: http://pastebin.com/dzsdWyYT

**Comment by Azoraqua** [comment]
@jesseke55 I believe, but I am not sure, you need to add an index and "enabled: true" to each schematic.

**Comment by jesseke55** [comment]
According to dutchy1001 on spigot: http://i.imgur.com/CsY3V4M.png

**Comment by Azoraqua** [comment]
@jesseke55 That's true indeed, if you have done that, did it solve it?

**Comment by jesseke55** [comment]
Yes its solved but somehow I want to use a item like CREEPER_EGG it gives me a barrier item in the is reset GUI

**Comment by Azoraqua** [comment]
@jesseke55 Use MONSTER_EGG, with data value 50.
If it's supported to use data values, if not @rlf Please add data values to such materials.

**Comment by jesseke55** [comment]
@Azoraqua It returns a different egg http://i.imgur.com/ilDOuYr.png

**Comment by Azoraqua** [comment]
@jesseke55 Maybe the Hex value 32? Look here: http://minecraft.gamepedia.com/Data_values/Entity_IDs

**Comment by jesseke55** [comment]
@Azoraqua Tried to use MONSTER_EGG with hex 32 and also 50:32

http://i.imgur.com/S8fjINY.png

**Comment by Azoraqua** [comment]
@jesseke55 Whoops.. MONSTER_EGG means according to the Wiki the monster stone bricks?
Try SPAWN_EGG:50.

**Comment by jesseke55** [comment]
@Azoraqua 'SPAWN_EGG:50' returns a barrier.

**Comment by Azoraqua** [comment]
@jesseke55 Possibly `383:50`? I believe the id of SPAWN_EGG is replaced to barrier.

**Comment by jesseke55** [comment]
According to http://minecraft-ids.grahamedgecombe.com/ not and '383:50' returns barrier too..

**Comment by Azoraqua** [comment]
@jesseke55 Strange... 383:50 is the id of Creeper Spawn egg.. Maybe it has to be the durability which needs to be set to 50?

**Comment by jesseke55** [comment]
@Azoraqua The plugin works with this method: ID:AMOUNT

**Comment by jesseke55** [comment]
Whilst its a easteregg I made it just to MONSTER_EGG so thanks for your help!
