### ISSUE TITLE
getIslandLocation of API

### ISSUE THREAD

**Issue by jesseke55** [rlf/uSkyBlock#773]
I and @Azoraqua are struggling with getting getIslandLocation working for the API when we need it we are getting teleported beside the island and not on the island

**Comment by jesseke55** [comment]
`package com.breachuniverse.skyblock;

import com.breachuniverse.skyblock.commands.*;
import com.breachuniverse.skyblock.events.Click;
import com.breachuniverse.skyblock.events.Move;
import com.breachuniverse.skyblock.events.Quit;
import com.breachuniverse.skyblock.schedulers.autoSave;
import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerMoveEvent;
import org.bukkit.plugin.Plugin;
import org.bukkit.plugin.java.JavaPlugin;
import us.talabrek.ultimateskyblock.api.IslandInfo;
import us.talabrek.ultimateskyblock.api.uSkyBlockAPI;

/**
 * Created by Jesse on 14-6-2016.
 */
public class Main extends JavaPlugin implements Listener{


    private static Plugin plugin;
    private static uSkyBlockAPI skyBlockAPI;
    public static uSkyBlockAPI getSkyBlockAPI() {
        return skyBlockAPI;
    }
    public static Plugin getPlugin(){
        return plugin;
    }

    public void onEnable(){
        plugin=this;
        initConfig();
        if (getServer().getPluginManager().getPlugin("uSkyBlock") instanceof uSkyBlockAPI) {
            skyBlockAPI = (uSkyBlockAPI) getServer().getPluginManager().getPlugin("uSkyBlock");
            getLogger().info("uSkyBlock hooked.");
        }
        if (skyBlockAPI == null) {
            getLogger().severe("uSkyBlock is not installed or enabled!");
            getLogger().severe("Disabling " + getDescription().getName());

            Bukkit.getPluginManager().disablePlugin(this);
            return;
        }
        getServer().getPluginManager().registerEvents(this,this);
        getServer().getPluginManager().registerEvents(new Click(), this);
       // getServer().getPluginManager().registerEvents(new Join(), this);
        getServer().getPluginManager().registerEvents(new Move(), this);
        getServer().getPluginManager().registerEvents(new Quit(), this);
        autoSave.AutoSave();
        getCommand("admin").setExecutor(new Admin());
        getCommand("clearinventory").setExecutor(new ClearInventory());
        getCommand("enderchest").setExecutor(new Enderchest());
        getCommand("fly").setExecutor(new Fly());
        getCommand("warp").setExecutor(new Warp());
        getCommand("workbench").setExecutor(new Workbench());

        getCommand("gamemode").setExecutor(new Gamemode());
        getCommand("gm").setExecutor(new Gamemode());
        getCommand("gmc").setExecutor(new Gamemode());
        getCommand("gm1").setExecutor(new Gamemode());
        getCommand("gm0").setExecutor(new Gamemode());
        getCommand("gms").setExecutor(new Gamemode());
        getCommand("gma").setExecutor(new Gamemode());
        getCommand("gm2").setExecutor(new Gamemode());
        getCommand("gmsp").setExecutor(new Gamemode());
        getCommand("gm3").setExecutor(new Gamemode());





    }
    public void onDisable(){
        plugin=null;
        skyBlockAPI = null;
    }
    private void initConfig(){
        getConfig().addDefault("Prefix", "&7[&eBreach&bSkyblock&7] &r");
        getConfig().addDefault("Menus.Warp.Name", "&aWarp Menu, &ePick a item");
        getConfig().addDefault("Menus.Warp.lore", "&2Click to teleport.");
        getConfig().addDefault("Menus.Warp.Island", "&1Open your /is menu");
        getConfig().addDefault("Menus.Warp.Shop", "&cOpen a shop inventory");
        getConfig().addDefault("Menus.Warp.Spawn", "&aSpawn");
        getConfig().addDefault("Menus.Warp.Cobblegen.Name", "&6Cobblestone generator");
        getConfig().addDefault("Menus.Warp.Cobblegen.World", "spawn");
        getConfig().addDefault("Menus.Warp.Cobblegen.X", 55);
        getConfig().addDefault("Menus.Warp.Cobblegen.Y", 5);
        getConfig().addDefault("Menus.Warp.Cobblegen.Z", 5);
        getConfig().addDefault("Menus.Warp.Cobblegen.Pitch", 4);
        getConfig().addDefault("Menus.Warp.Cobblegen.Yaw", 44);
        getConfig().addDefault("AutoSave.Interval", 5);



        getConfig().options().copyDefaults(true);
        saveConfig();


    }















































    @EventHandler(priority = EventPriority.HIGHEST)
    public void onMove(PlayerMoveEvent e) {
        Player p = e.getPlayer();
        final IslandInfo info = Main.getSkyBlockAPI().getIslandInfo(p);

        if (p.hasPermission("breachuniverse.skyblock.donator") && p.getLocation().getY() <= 0) {
            Bukkit.broadcastMessage("Player fall is hit");
            p.setNoDamageTicks(20 * 8);
            p.teleport(info.getIslandLocation());
            p.sendMessage(ChatColor.GREEN + "We teleported you back to your island! :)");
        p.setNoDamageTicks(20 * 8);
        }
    }











}
`
There is the code

**Comment by rlf** [comment]
Do you use custom schematics? Or the default island.

The island location is the center of the island region, the schematic is pasted relative to this, so if the schematic is created with an offset, the island-locaiton will not be on the island.

**Comment by Azoraqua** [comment]
Here is the graphical explanation: [Click here for screenshot](http://i.imgur.com/oJKp0j9.png)

- The blue wool represents the home/spawnpoint of the Island.
- The red wool represents the point I got teleported to (by using **IslandInfo#getIslandLocation()**). 

And also yes, custom ones, as seen on the background.

**Comment by jesseke55** [comment]
@rlf But the problem is we are getting teleported outside the island though.

**Comment by Azoraqua** [comment]
@rlf @jesseke55 Pretty much anywhere except the actual spawnpoint.

**Comment by jesseke55** [comment]
Yea..

**Comment by rlf** [comment]
The problem is you are not really listening to what I'm telling you.
But, hey (grumpy old man), I'll try again:

Every island is assigned a region, this region is centered around the `islandLocation` which is placed in a grid using the `distance` defined in the `config.yml`.
The size of the region is determined using the `protectionRange` from the `config.yml`.

Once the region has been establised, the island-schematic chosen is pasted to the `islandLocation`.
Note: This means, that depending on the ***origin*** of the schematic, the island might not be at the island-location at all.
Once this is done, an area of 15 blocks from the `islandLocation` is searched for a chest - which will define the `islandHome`.

The location you get from the API is the `islandLocation`.

The API currently does not expose the `islandHome` - since no such thing really exist (it's an `islandHome` per player).
