### ISSUE TITLE
ProtectionRange island

### ISSUE THREAD

**Issue by Alibabaand40voleur** [rlf/uSkyBlock#779]
_Please paste the output from `/usb version` below_
![popo](https://cloud.githubusercontent.com/assets/18491206/16177852/7c908490-3638-11e6-8dfc-2453ae0b8414.PNG)

version goes here
2.6.8

_What steps will reproduce the problem?_
1. Install uSkyBlock in your server
2. Put     protectionRange: 480 in your config
3. Create island
4. moov out the island
5. Protection island is like ~100 and not 480.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

**Comment by dutchy1001** [comment]
what is the **distance** set too?

**Comment by rlf** [comment]
`distance` has to be 50 or greater, and should be divisible

**Comment by Alibabaand40voleur** [comment]
Distance set to 10000

**Comment by Alibabaand40voleur** [comment]
16*625 = 10 000
10000/16 = 625

**Comment by dutchy1001** [comment]
I dont think you understand the settings

**Comment by Alibabaand40voleur** [comment]
W

**Comment by Alibabaand40voleur** [comment]
Why ?

**Comment by Alibabaand40voleur** [comment]
I just want my island protected at ~500 blocs
And the island distance at 10 000 blocs

**Comment by dutchy1001** [comment]
distance 10000 and protectionRange 480...
You have a wasted space all around your island of 9520 block yet the next island is has also a space of 9520 block, meaning in between islands is a gap of 19040 block were no one can do anything.

**Comment by dutchy1001** [comment]
in words that is nineteen thousand and forty blocks

**Comment by Alibabaand40voleur** [comment]
And ?
I just want my player get her island 500x500 max

And in the world the space in all island is 10 000 blocs

**Comment by dutchy1001** [comment]
to create a region of 10000 is way to heavy on a server, unless you have 1028GB of ram.
Lets get serious and use value's that are more exceptable, if not then stop wasting my time.

**Comment by Alibabaand40voleur** [comment]
I

**Comment by Alibabaand40voleur** [comment]
im just asking, how can i setup protection 500x500,
If u want i can put 1000 distance
...

**Comment by BlackBeltPanda** [comment]
@Alibabaand40voleur Try something like distance at 640 and protection range at 480 and see if that helps.
