### ISSUE TITLE
The nether is not working

### ISSUE THREAD

**Issue by ridalarry** [rlf/uSkyBlock#781]
_Please paste the output from `/usb version` below_
```
19.06 13:34:35 [Server] INFO Name: uSkyBlock 
19.06 13:34:35 [Server] INFO Version: 2.6.12 
19.06 13:34:35 [Server] INFO Description: Ultimate SkyBlock v2.6.12-9e2d30-413 
19.06 13:34:35 [Server] INFO Language: en (en)
19.06 12:45:31 [Server] INFO ------------------------------ 
19.06 12:45:31 [Server] INFO Server: CraftBukkit git-Spigot-4af49dc-23da8b0 (MC: 1.9.4) 
19.06 12:45:31 [Server] INFO ------------------------------ 
19.06 12:45:31 [Server] INFO Vault 1.5.6-b49 (ENABLED) 
19.06 12:45:31 [Server] INFO WorldEdit 6.1.3-SNAPSHOT;3557-ac1b4f7 (ENABLED) 
19.06 12:45:31 [Server] INFO WorldGuard 6.1.2-SNAPSHOT;1664-5bd2125 (ENABLED) 
19.06 12:45:31 [Server] INFO FastAsyncWorldEdit 3.5.1-9bf2d2b (ENABLED) 
19.06 12:45:31 [Server] INFO Multiverse-Core 2.5.0-SNAPSHOT-b722 (ENABLED) 
19.06 12:45:31 [Server] INFO ------------------------------
```

_What steps will reproduce the problem?_
1. move inside a nether portal would not teleport you to the nether

**Comment by dutchy1001** [comment]
what are the value's from **distance** and **protectionRange** in the config?

**Comment by ridalarry** [comment]
128 for both

**Comment by dutchy1001** [comment]
I also just notest you have only party posted the output of **/usb version**, what usb version you use?

**Comment by ridalarry** [comment]
2.6.12

**Comment by dutchy1001** [comment]
Is this a new setup or an update from a previous version?
I just setup a basic test server and it creates both world and nether-world "strait out the box" on first run.
Created my island and a portal which gave me excess to the nether and my nether island.

**Comment by ridalarry** [comment]
its new and the world is created, but no teleportation I even tried to update to the pre release and the issue still exist

**Comment by ridalarry** [comment]
This is my current plugin list https://gyazo.com/75934b946d5c6e46d0960ac0ecbac556 and the issue still exist on 2.6.14

**Comment by dutchy1001** [comment]
And then the brains start working.
To be able  to use the portals to go to the nether you need the Multiverse-portal and Multiverse-NetherPortals plugin adding to your list.
Both links can be found on this page [here](http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/installation/)

**Comment by ridalarry** [comment]
That fixed it but there is a new issue, it does for some island teleport the players when they use the portals they get to dropped under the island to void and die from normal world to nether and from nether to normal world and telling the players "No Access! You are trying to teleport to the roof of the NETHER, that is not allowed."

**Comment by rlf** [comment]
That is an issue in MV-NP, where they don't take the difference in y-coordinates into account.

You can either ask players to build the portal below y=120ish, or get a fixed version of the MV-NetherPortals.

**Comment by ridalarry** [comment]
where can I find that version? I am using the latest dev build

**Comment by dutchy1001** [comment]
if you tell us version numbers then we can compare as "i use the latest" doesnt mean anything

**Comment by ridalarry** [comment]
https://ci.onarandombox.com/job/Multiverse-NetherPortals/

**Comment by dutchy1001** [comment]
same version as I use for the nether portals. Do you use every dev build or only both the portals one?

**Comment by ridalarry** [comment]
I am not sure of multiverse-core version i will check it now

**Comment by dutchy1001** [comment]
either use all dev versions or release version, mixing them isn't the best way.

**Comment by ridalarry** [comment]
https://ci.onarandombox.com/job/Multiverse-core/722/
https://ci.onarandombox.com/job/Multiverse-Portals/746
https://ci.onarandombox.com/job/Multiverse-netherportals/712

**Comment by ridalarry** [comment]
all of them are dev version and uskyblock version 2.6.14

**Comment by dutchy1001** [comment]
then it should be fine as I use the same set.
Players might need to restart their island, but not sure. 
Does it happen to all players?

**Comment by ridalarry** [comment]
some of them as far as I know

**Comment by ridalarry** [comment]
some islands not players

**Comment by dutchy1001** [comment]
let a player that has the issue restart their island and see if that fixes it.
If not do the command **/usb island delete [player]**, this deletes them from the island and should reset their files. Aftr that they need to create a new island.

**Comment by ridalarry** [comment]
I dont think the island i know of will do it because they are the 2nd top island after spawn

**Comment by dutchy1001** [comment]
do they get the island in the nether?

**Comment by rlf** [comment]
Set:
```
    # Whether or not portalling to the nether roof should be blocked.
    nether-roof: false
```
Then we won't disallow portalling to the roof - but... that will only solve half the problem (since they will be above their nether-island).

Since they are portaling above the nether, I would guess they do not have a nether-island (with a valid portal).

**Comment by ridalarry** [comment]
they have an island and that will teleport them to the roof which will be even worse

**Comment by ridalarry** [comment]
this is a video from it https://www.youtube.com/watch?v=AcCpAJWYYcw&feature=youtu.be

**Comment by dutchy1001** [comment]
The nether you use is that generated by uSkyblock or did you add this world yourself?

When your going back to the overworld you spawn outside the island, this might be caused as the scale is set wrong(happens mostly when generating your own nether).
Check in MV-Core Worlds.yml if the scale is set to `scale: '1.0'` default is set to 8.0

It's a known bug that if toy are entering a portal in GM1 that it can bug, as you could see in your vid. When your in GM 0 it did let you enter the nether.

**Comment by ridalarry** [comment]
It was generated by itself but I will check

**Comment by ridalarry** [comment]
the scale is 1.0 should I change it to 8.0?

**Comment by dutchy1001** [comment]
no 1.0 is right

**Comment by ridalarry** [comment]
then what could be the cause?

**Comment by dutchy1001** [comment]
It could be a glitch but that is just guessing. Removing both portals (overworld and nether) of this player and creating a new portal,  on a different location on the island, might be worth a try.

**Comment by ridalarry** [comment]
mc.supernovams.net and do /server skyblock

**Comment by dutchy1001** [comment]
nobody there to help out to make a portal.

**Comment by ridalarry** [comment]
I will be on now

**Comment by ridalarry** [comment]
And actually this bug also happened to another to players, Just in case if I wasnt on I will give your account full access to /gamemode /usb and /is

**Comment by dutchy1001** [comment]
not been able to do multiple commands like /GM1 after leaving the nether to save myself and see were I end up is way to annoying. 
Something is not set right with the portal settings or scale. The scale to be checked is the skyworld_nether in MV-Core, not sure which you checked before but plz check again. 

Nether looks fine as you do get the default island.

**Comment by ridalarry** [comment]
I will show you some of the islands and I can send you the configs in pastebin

**Comment by ridalarry** [comment]
MV-Portal config http://pastebin.com/LCGAjz8L
MV-Core worlds http://pastebin.com/nWnEvZkW

**Comment by ridalarry** [comment]
Ok I have found the bug it was related to AAC I fixed it by disabling all the "teleport" options just in case if anyone has the same issue. @dutchy1001 thank you so much for your help.

**Comment by dutchy1001** [comment]
Glad it's sorted and thx for the nice review on our spigot site.

To answer your question why we dont go premium, and I think I can speak for both R4zorax and myself, its a hobby we like to do for the community.

However, we have setup a donation site if ppl like to help us to help others.
You can see that site [here](https://www.justgiving.com/fundraising/uSkyblock)
