### ISSUE TITLE
Support signs for completing challenges

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#782]
It would be nice to have a feature inspired by the chest-shop plugins.

Say I place a sign on a chest with the following text:
```
[usb]
cobblestonegenerator
```
Then I want USB to replace it with something along:
```
[cobblestonegenerator]
Req: 66 cobble
```
And a color indicating whether the chest holds enough items for the challenge.

If the player clicks on the sign, I want the plugin to:
* Check if the player is allowed to access the chest
* Check if the player has room in his inventory for the items required
* If yes, complete the challenge

The above requires the `challengeSharing` to be `island` - otherwise the requirements would differ from player to player.

**Comment by dutchy1001** [comment]
Tested on the latest dev build v2.7.AlphaX and working.
A very nice feature if I may say so :+1:

**Comment by rlf** [comment]
It will match after "best-case"; so you can just type in `cobblestone`

**Comment by dutchy1001** [comment]
Double chests work in v2.7.2.
Completing as many challenges in 1 interaction (issue #623  ) is not.
This issue can be closed and further comments about the 1 click interaction should be posted in the other issue mentioned above.
