### ISSUE TITLE
EPIC PLUGIN But no animals or mobs are spawning I tried using spawners spawn eggs not working plz plz help me

### ISSUE THREAD

**Issue by TimeyKappa** [rlf/uSkyBlock#784]
_Please paste the output from `/usb version` below_
```
paste it here please (replace this text)
```

_What steps will reproduce the problem?_
1.
2.
3.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

**Comment by dutchy1001** [comment]
plz make proper bug report, just a header is not the way
