### ISSUE TITLE
Adding Vietnamese language for the plugin [vi_VN localization]

### ISSUE THREAD

**Issue by Banbeucmas** [rlf/uSkyBlock#787]
Here it goes, done, i would like you guys to add vi_VN.po as one of the main language files, since it is too difficult to spread this comes along with the how to localize (Vietnamese most of them are noob on plugins)

https://www.dropbox.com/s/qxwstwv38lbrv5u/vi_VN.po?dl=0

**Comment by dutchy1001** [comment]
I'll add this as soon I got time. It will be ready in the next release

**Comment by dutchy1001** [comment]
you can download the version included with vi_VN [here](https://github.com/rlf/uSkyBlock/releases/tag/v2.6.15)
