### ISSUE TITLE
Nether issue

### ISSUE THREAD

**Issue by Alibabaand40voleur** [rlf/uSkyBlock#789]
_Please paste the output from `/usb version` below_

![capture](https://cloud.githubusercontent.com/assets/18491206/16359627/5ab7e6ce-3b3d-11e6-8636-e561b6b4c5c9.PNG)

_What steps will reproduce the problem?_ Chunk régéne & Hard lag nether
1. Use /is create
2. Go in your /is home
3. Create a nether portal
4. Go to the nether
5. U can now mining your Nether island
6. Now u know
7. Some block spawn, i think chunk regene
8. U can see too : hard lag when chunk load

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

**Comment by dutchy1001** [comment]
Change the lava level in the config to:
```
lava_level: 7
```
you might need to restart the netherworld for this.

**Comment by Alibabaand40voleur** [comment]
How can i restart this NetherWorld ?

**Comment by Alibabaand40voleur** [comment]
I put Lava_Level to 7.
This will stop restoring blocks & Lags when chunk load ?

**Comment by dutchy1001** [comment]
The restoring blocks is a feature called terraforming (if I understand you correct) and can be configured or turned off in the config.

If lava level is set to 7 you might need to delete (read backup) the skyworld_nether and generate a new one, restarting the islands will not reset the lava level.

Also if your still using the same distance levels (as mentioned in a previous post) then that will not help either with the nether lag.

**Comment by Alibabaand40voleur** [comment]
I have :   lava-level: 32
If i fix it to   lava-level: 5 it will work i think no ?

**Comment by Alibabaand40voleur** [comment]
In your server, is fixed to 7 ? And u don't have lag ?

**Comment by dutchy1001** [comment]
Default mc nether lava-level is set to 7 as far I know, so I wouldn't recommend 5.

Our public test server doesn't have lag that we can see, also the test server isn't populated much.

**Comment by Alibabaand40voleur** [comment]
Thanks for ur help !
