### ISSUE TITLE
Nether régéne 

### ISSUE THREAD

**Issue by Alibabaand40voleur** [rlf/uSkyBlock#791]
_Please paste the output from `/usb version` below_

![capture](https://cloud.githubusercontent.com/assets/18491206/16361590/7d45c2da-3b95-11e6-93b8-7dc4ca0e8527.PNG)

_What steps will reproduce the problem?_
1. Régén ur nether :
2. /mv delete skyworld_nether
3. /mvconfirm
4. /mv create skyworld_nether nether
5. Now u can see the nether is complely normal
6. How can i change that to the skynether ?

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

**Comment by dutchy1001** [comment]
plz post your config through pastebin

**Comment by Alibabaand40voleur** [comment]
http://pastebin.com/mYH4w1qn

**Comment by dutchy1001** [comment]
What you want?? 

1. a nether with islands and protection as in the overworld

2. a default Minecraft nether were players can walk around and break/build

**Comment by Alibabaand40voleur** [comment]
1. a nether with islands and protection as in the overworld

**Comment by dutchy1001** [comment]
in that case you need to delete both worlds skyworld and skyworld_nether. Make the **distance** and **protectionRange** so that the value's are chunk aligned (meaning, they need to be able to be divided by 32)

**Comment by Alibabaand40voleur** [comment]
I removed my Skyworld_nether, i need to remove my skyworld to U_u ?

**Comment by Alibabaand40voleur** [comment]
I can't remove my skyworld to, all island of my player is here ..
I juste want a new skyworld_nether with island etc.

**Comment by dutchy1001** [comment]
it is not possible with the distance and protectionRange value's you got.
The skyworld_nether will automatic be generated if the distance and protectionRange settings are chunk aligned.

**Comment by Alibabaand40voleur** [comment]
If i setup like that :


   # [integer] The number of blocks between islands.
    distance: 3200
 
    # [integer] The size of the protective region for each island. Can't be higher than 'distance'
    # and MUST be divisible by 32 if you intend to use nether.
    protectionRange: 320


He will be ok ?

**Comment by dutchy1001** [comment]
**Distance** also need to be divisible by 32.
After your worlds are created (the first time) you **cant** reset distance and protectionRange to different value's as this will cause problems sooner or later. Your only option is a complete restart of both worlds.

**Comment by Alibabaand40voleur** [comment]
And how can i see what was the distance the first time ?

**Comment by dutchy1001** [comment]
When first time starting the server with uSkyblock there are no island, this is the only time you can change the value's. After the first island is created by you or a player you cant reset the value's. There is nothing further I can do about this.

**Comment by Alibabaand40voleur** [comment]
If i put the 
 distance: 3200 and protectionRange: 320 to the value in first time created the island, he can be ok ?

**Comment by Alibabaand40voleur** [comment]
We can solve that is sûre, but i don't know how :'(

**Comment by dutchy1001** [comment]
those value's should be valid, but you need to restart both worlds if you dont want any problems later on. 
Files need to be deleted from both uskyblock folder (folders player and island, file "lastIslandConfig") and from WorldGuard/worlds/skyworld and skyworld_nether.

**Comment by Alibabaand40voleur** [comment]
I can't restart my skyworld :/ Or all my player will need to restart all her skyblock..

**Comment by Alibabaand40voleur** [comment]
What kind of probleme can i have later ?

**Comment by dutchy1001** [comment]
You will run onto overlapping islands, islands on top of other islands. 

You either restart or continue the way it is without the nether, you have no other option.

**Comment by Alibabaand40voleur** [comment]
And i i take the backup of my skyworld_nether map he can be ok ?

**Comment by dutchy1001** [comment]
only a new setup will work, no old world
