### ISSUE TITLE
vi_VN.po

### ISSUE THREAD

**Issue by Banbeucmas** [rlf/uSkyBlock#794]
Just the proplem:
Version: v2.6.15
Seem like language havent changed into Vietnamese when updated vi_VN in the config.yml

I might need to have a stable version of the plugin goes with the language files

**Comment by dutchy1001** [comment]
use the command ingame **/usb lang vi_VN**

**Comment by rlf** [comment]
There seems to be an error in the .po file.

```
>usb lang vi_VN
[13:41:59 WARN]: Nether DISABLED, since islands cannot be chunk-aligned!
[13:41:59 INFO]: [uSkyBlock] 3 schematics loaded.
[13:41:59 INFO]: Unable to load translations from i18n.zip!vi_VN.po: java.io.IOException: Malformed po, did not expect '
msgstr ºcºlB?n kh¶ng th? thay ??i ?i?m d?ch chuy?n"' at line 2148
```
Dutchy, can you re-test it in POEdit?
And perhaps add the author (if he wants to) to the headers?

**Comment by Banbeucmas** [comment]
Ok add me in the author: Banbeucmas
Email: Banbeucams@gmail.com
Pretty sure this still occur even when i tried to make the custom way of localization in the stable version of uSkyblock at bukkit

**Comment by dutchy1001** [comment]
When using PoEdit it gave me a few issue's to save the file. Not all errors given were important but a few were missing some quotation/speech marks (**"**). An other issue was that there was a space to much (not sure this could cause a problem but fixed anyway).
Some translations didnt have the **{0}** or **{1}** but those weren't a necessity to be used (PoEdit gave them as an error). 
While using IntelliJ IDEA some more issue's were found, mainly some more missing quotation/speech marks (**"**) which I have fixed too.

A new pull request is made after posting this message.

**Comment by Banbeucmas** [comment]
This translation were made by the CraftVN team (Actually, 2 of us, as me, including inph99), 70% of the translation were made by inph99, I am not sure what does the translation were wrong. We have a forum but you could contact him though email craftvn2016@gmail.com if you want :D

**Comment by dutchy1001** [comment]
As I have fixed the main issue's (as there was no translation needed for that) we don't need to contact your partner in crime :smiley: 
All of the errors are as far I can see just typing mistakes, this can happen when you don't use the (recommended) [PoEdit](https://poedit.net/) program (it's free to use) or similar software.

**Comment by Banbeucmas** [comment]
*Self-talking* :"Tí thím chết với anh"
Ah ok, so the proplem would solve faster than i expected to be XD

**Comment by dutchy1001** [comment]
Add this to a folder called **i18n** (if not present in the uskyblock folder create it) then in game you can do **/usb lang vi_VN**

**Comment by dutchy1001** [comment]
Ok after some issue's getting the file added to the plugin I think I finally got it sorted. 
If or when it needs updating due to new lines added in the future I will only allow and add the file when the proper software has been used (E.G. PoEdit). PoEdit validates the file to make sure it wont cause any issue's with the GetText system we use in uSkyblock.
The pre-release (Vietnamese added - take 2) present at the time of writing this post will still have some issue's and I don't recommend to download this, wait for "Take 3"

**Comment by Banbeucmas** [comment]
Ah, that's great, i would hope that the .po would stable now

**Comment by rlf** [comment]
https://github.com/rlf/uSkyBlock/releases/tag/v2.6.17

**Comment by Banbeucmas** [comment]
Worked as expected

**Comment by dutchy1001** [comment]
thx for the feedback.
Closing as this issue is solved.
