### ISSUE TITLE
Island Problem

### ISSUE THREAD

**Issue by Jakeepoo32** [rlf/uSkyBlock#799]
_Please paste the output from `/usb version` below_
```
I can't, ill tell you why.
```
![2016-06-27_19 45 22](https://cloud.githubusercontent.com/assets/20176423/16400358/1f69c79a-3ca0-11e6-925f-306f9b2824e9.png)

_What steps will reproduce the problem?_
1. When I do /island (or anything after that, like /is, or /island top, /island party, etc...) It shows up with "/island [restart/sethome/info/level/lock/unlock/top/party]
2. When I do /usb (or anything after that, like /usb version, etc...) It says "/usb for more info"
3.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

**Comment by Victhetiger** [comment]
Read the bottom: http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/bug-report/

**Comment by dutchy1001** [comment]
As Victhetiger already pointed you too, you are missing  or have a wrong depended.
When the command **/usb version** isn't working you have to do this manual or post the startup log.

**Comment by rlf** [comment]
Perhaps we should move all our dependencies to softdepend, and then show em...

**Comment by dutchy1001** [comment]
Shouldn't we better keep them as hard depended but maybe a better system to broadcast what is missing??

**Comment by rlf** [comment]
Not possible. hard depend means we won't get enabled/loaded.
Softdepend it is possible, since we can check em our selves during enable.
