### ISSUE TITLE
Allow for optional challenges instead of pure rank-leeway

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#8]
Current version support a general config parameter for rank-leeway, that allows players to start on the next rank, once only N challenges are missing in the previous rank.

I propose having an override on the single challenges, allowing to progress without certain challenges (optional challenges), or perhaps only one of 3 or similar

**Comment by dutchy1001** [comment]
adding a new challenge to the config using tha last section and witout any other challenge completed still let me complete my added challenge. 
Fixed

**Comment by dutchy1001** [comment]
no problems/errors found since my last test
