### ISSUE TITLE
Challenge Help

### ISSUE THREAD

**Issue by Alibabaand40voleur** [rlf/uSkyBlock#800]
_Please paste the output from `/usb version` below_

![capture](https://cloud.githubusercontent.com/assets/18491206/16418377/d3af56c6-3d49-11e6-8a86-00eee2b88ee5.PNG)

What i need ? : 

When u creat 2 challenge like this : 

  ChallengeGroup9:
    name: '&aEnder'
    displayItem: '120'
    resetInHours: 1
    requires:
      rankLeeway: 0
      challenges:
      - End
    challenges:
      End:
        name: '&aAccès End'
        description: Récolter les ressources pour récupérer des pièces pour le portail de l'end.
        type: onPlayer
        requiredItems: 381:32 368:32 410:32 409:32 49:16
        repeatable: true
        displayItem: 368
        takeItems: true
        reward:
          text: Morceau de portail de l'end
          items:
          - '120:1'
          currency: 80
          xp: 80
        repeatReward:
          text: Morceau de portail de l'end
          items:
          - '120:1'
          currency: 40
          xp: 40

If he complete this, he will be can do the next groupchallenge, the   ChallengeGroup10.
But me, i want the guy need to complete x12 the challenge groupe9 so the :     
challenges:
      End:

And then he completed x12, he can go to the ChallengeGroup10.

Is it possible ? Thx

**Comment by Alibabaand40voleur** [comment]
requiredItems: 122

Ender_egg is not supported by uSkyBlock ?
When i put 122, u can complete the challenge how many time u want, all time.
And my challenge is like this : 

![bugchall](https://cloud.githubusercontent.com/assets/18491206/16419416/ec2e1efe-3d4d-11e6-8a18-90049fd3fdcc.PNG)

**Comment by rlf** [comment]
To answer the questions:
a) No, it's not possible to give out certain rewards after completing a challenge X times.
b) Yes, we support most blocks, since we use the Bukkit API for accessing materials and blocks.
c) I have no idea what the challenge says, since you have it displayed in French - but my guess would be, that you either have `takeItems: false`, the format of `requiredItems` is `<itemid>[:subtype]:<amount>' - so in your case, it should be `requiredItems: '122:1'`

**Comment by Alibabaand40voleur** [comment]
This is my challenge : 

      EnderDragon:
        name: '&aLenderdragon'
        description: Tuer l'ender dragon et récupérer son oeuf.
        type: onPlayer
        requiredItems: 122:1
        repeatable: true
        displayItem: 122
        takeItems: true
        reward:
          text: 4 Diamants, 2 Emeraude, 1 Larmes de ghast
          items:
          - '264:4'
          - '388:2'
          - '370:1'
          currency: 80
          xp: 80
        repeatReward:
          text: 3 Diamants, 2 Emeraude, 1 Larmes de ghast
          items:
          - '264:3'
          - '388:2'
          - '370:1'
          currency: 40
          xp: 40

And the 122:1 didnt work

**Comment by dutchy1001** [comment]
Just tested this and ```'122:1'``` does work

**Comment by Alibabaand40voleur** [comment]
Can i block the challenge by some permission ?

**Comment by Alibabaand40voleur** [comment]
permission of my plugin world guard, in the groupe " groupe.ender "

**Comment by dutchy1001** [comment]
you **can't** block challenges with a permission.
