### ISSUE TITLE
request for pvp toggle in GUI

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#805]
as title already sais, a request made by Cyborg20005 on the bukkit forum for a pvp toggle.
As we already have this option in the config, is it possible to make this for the players?

**Comment by rlf** [comment]
The config.toggle changes the pvp flag for `__global__`, making it per region shouldn't be too hard, but the implications might be.... dire.

I.e. should we warn ppl warping to an island with pvp enabled?

**Comment by dutchy1001** [comment]
A special PVP message would be nice so players know what their up against if they joij/warp to an island

**Comment by rlf** [comment]
To be clear - this will only be able to be introduced, when pvp is ENABLED in the main config (in the global region).
