### ISSUE TITLE
"Visitors cant drop items!" when falling into the void.

### ISSUE THREAD

**Issue by SirApathy** [rlf/uSkyBlock#806]
_Please paste the output from `/usb version` below_
v2.6.12

_What steps will reproduce the problem?_
1. Teleport to your island.
2. Have the setting enabled for not dropping items on others islands.
3. Fall into void and die.
4. Recieve Message.

(I know it's a small issue but I'm sure it's just a minor error you'd want perfected. And sorry I didn't include any of the other plugins versions, I know this is just a small issue with USB.)

**Comment by dutchy1001** [comment]
I have reproduced this but as you already said it's a very minor issue what will not impact the game play. 
Thx for letting us know.

**Comment by rlf** [comment]
Changed it, we now don't tell players they can't drop, but we let them keep their inventory if they do.

**Comment by dutchy1001** [comment]
this has been fixed in the next update.
