### ISSUE TITLE
Thowing eggs

### ISSUE THREAD

**Issue by MrFiliper** [rlf/uSkyBlock#808]
_Please paste the output from `/usb version` below_
```
�Name: �uSkyBlock�
�Version: �2.6.12�
�Description: �Ultimate SkyBlock v2.6.12-9e2d30-413�
�Language: �cs (cs)�
�------------------------------�
�Server: �CraftBukkit git-Spigot-c3e4052-1953f52 (MC: 1.10)�
�------------------------------�
��Vault �1.5.6-b49 �(�ENABLED�)�
��WorldEdit �6.1.3;7a097ca �(�ENABLED�)�
��WorldGuard �6.1.2;e38d98d �(�ENABLED�)�
��AsyncWorldEdit �2.2.2 �(�ENABLED�)�
��Multiverse-Core �2.5-b717 �(�ENABLED�)�
��Multiverse-NetherPortals �2.5-b675 �(�ENABLED�)�
�------------------------------�
```

_What steps will reproduce the problem?_
1. Go to other player island (/tpa, /is warp)
2. Get eggs (chicken eggs) and thow it.

Player can thow chicken eggs in other players. But monster eggs not. Can you add this protection to chicken eggs?

**Comment by dutchy1001** [comment]
never knew monsters lay eggs you can trow

**Comment by Victhetiger** [comment]
You can't throw them, he meant that if you go on someone else's island you can't right click the ground to spawn the monsters.

I also have this issue, I have one island with a few hundred chickens because people wanted to prank their friends.

**Comment by rlf** [comment]
Is it the throwing, or the spawning of chickens you want blocked?
Because throwing should be allowed (imo), with snowballs and bows.

**Comment by Victhetiger** [comment]
Spawning chickens blocked, in my case.

**Comment by dutchy1001** [comment]
You can still trow eggs but (as explained by rlf) they won't hatch anymore.

**Comment by MrFiliper** [comment]
You can throw eggs, but chicken won´t spawn. Thanks. It works now.
