### ISSUE TITLE
[Suggestion] Island Creation Automatically

### ISSUE THREAD

**Issue by Victhetiger** [rlf/uSkyBlock#809]
I've been using 2 separate portals for new players to get an island and for players with an island to go back home.

I was wondering if their could be an **option** for people without an island to get an island created if they ran /is home

This would make everything better because everyone would spawn at the same place.

**Comment by rlf** [comment]
Not sure I get why that would make everything better?

Currently, everybody can simply do `/is` to get our main-menu, which will lead to all the possible features for their current state.

**Comment by Victhetiger** [comment]
Well, yes. But you can't open menus while inside a portal block. It would make everything better for my own use of it.

**Comment by rlf** [comment]
Not sure how creating the island on `/is h` will help you there m8?

We could introduce a `/is auto` - inspired by the various plot-plugins, that would either do `/is create default` or `/is home` depending on the existence of islands, but it would sort of violate the whole "select a schematic for your island" approach.

**Comment by dutchy1001** [comment]
When inside a portal block you cant do anything anyway, that is just default MC.
To add features for your own benefit of it is not very "community" orientated in my opinion.

**Comment by Victhetiger** [comment]
Indeed it isn't very community oriented but could be used by many as I've seen many many servers using 1 portal to create/go home although they were using ASkyblock.

/is auto would be amazing!

**Comment by rlf** [comment]
So you have a portal, that executes a command?
And only one island schematic for ppl to chose?

**Comment by dutchy1001** [comment]
did I hear you swearing there now?????
lol

**Comment by rlf** [comment]
Well auto is easy, and I get the need to make stuff easy.

**Comment by Victhetiger** [comment]
Yes, only one schematic named island.schematic.

**Comment by dutchy1001** [comment]
the command /is auto works very well. If you don't have an island it will create one, if you have an island it will send you home.

**Comment by dutchy1001** [comment]
@Victhetiger 
As this is done special for you I would like you to have a look at this page [here](https://www.justgiving.com/fundraising/uSkyblock). Not for us but for the bigger community.

**Comment by Victhetiger** [comment]
Works perfectly fine! Thank you very much for adding this :heart: As for the donation, I'll try to gather up some funds to make a big one.
