### ISSUE TITLE
Could not pass event EntityDamageEvent

### ISSUE THREAD

**Issue by VENT0** [rlf/uSkyBlock#811]
_Name: uSkyBlock
Version: 2.5.3-bukkit-1.7.9
Description: Ultimate SkyBlock v2.5.3-bukkit-1.7.9-da7f04-383
Language: en (en)
Server: Spigot 1.7.10 R0.1-1649
Name: Vault (ENABLED)
Version: 1.5.6-b49
Name: WorldEdit (ENABLED)
Version: 6.1;no_git_id
Name: WorldGuard (ENABLED)
Version: 6.1_

EDIT:
next time plz use the pastebin link that is provided
http://pastebin.com/jCh2GmXm

_What steps will reproduce the problem?_
It happens spontaneously when people play. And it happens rare.

**Comment by dutchy1001** [comment]
you need the Vault v1.41 for your server (get it [here](http://dev.bukkit.org/bukkit-plugins/vault/files/47-vault-1-4-1/)) or update the server

**Comment by VENT0** [comment]
Thank you very much. Everything works well.

**Comment by VENT0** [comment]
I have installed Vault 1.41 but this problem remained. Any ideas how to solve this problems?

**Comment by dutchy1001** [comment]
Your on a very old build (even for a 1.7.10 server that is) that isn't supported anymore. Maybe google Yive's Mirror to find an more updated 1.7.10 version is an option. Not sure it helps but you never know.

**Comment by VENT0** [comment]
Ok, one more question: will uSkyblock v2.6.4 work stable on Minecraft 1.7.10 ?

**Comment by dutchy1001** [comment]
The version of uSkyblock you have will not work on Minecraft 1.8 and higher due to code changes from Mojang.
2.5.3-bukkit-1.7.9 is the latest you can use for a 1.7.x server.

**Comment by VENT0** [comment]
Ok. Thank you very much. You can close the issue.
