### ISSUE TITLE
Default member names.

### ISSUE THREAD

**Issue by JimmyFires** [rlf/uSkyBlock#814]
I downloaded the essentialsex chat plugin and was changing ranks for default members , mods, and admins.... Default members always start with the title Uskyblock which I didnt set it to.... Someone please help me.

**Comment by JimmyFires** [comment]
I set the default name to rookie and it still shows uskyblock

**Comment by dutchy1001** [comment]
This is nothing to do with uSkyblock but more with EssentialsX. As I dont use EssentialsX chat addon I cant help you here. But I presume you need to look at the settings in the main Essentials config chat section.
