### ISSUE TITLE
[Suggestion] Join Island and Leave Island commands

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#816]
In addition to the Restart Island "extra-commands" config option, options to specify commands to execute when a player joins an island or leaves an island would be very useful. Could be used to do things like give the player a kit when they join, remove permission nodes when they leave, warp them somewhere, run custom commands made via plugins or Skript, etc., etc.

**Comment by rlf** [comment]
Good suggestion. WIll add

**Comment by BlackBeltPanda** [comment]
Working great =)
