### ISSUE TITLE
UDID Update is not working on 2.7.1

### ISSUE THREAD

**Issue by ItsShadowFang** [rlf/uSkyBlock#817]
_Please paste the output from `/usb version` below_
```
07.07 18:24:38 [Server] INFO ------------------------------
07.07 18:24:38 [Server] INFO Multiverse-NetherPortals 2.5.0-SNAPSHOT-b712 (ENABLED)
07.07 18:24:38 [Server] INFO Multiverse-Core 2.5.0-SNAPSHOT-b722 (ENABLED)
07.07 18:24:38 [Server] INFO WorldGuard 6.1.2;e38d98d (ENABLED)
07.07 18:24:38 [Server] INFO WorldEdit 6.1.3-SNAPSHOT;3547-fd0e400 (ENABLED)
07.07 18:24:38 [Server] INFO Vault 1.5.6-b49 (ENABLED)
07.07 18:24:38 [Server] INFO ------------------------------
07.07 18:24:38 [Server] INFO Server: CraftBukkit git-Spigot-0359393-9cd1111 (MC: 1.8.8)
07.07 18:24:38 [Server] INFO ------------------------------
07.07 18:24:38 [Server] INFO Language: en (en)
07.07 18:24:38 [Server] INFO Description: Ultimate SkyBlock v2.6.12-9e2d30-413
07.07 18:24:38 [Server] INFO Version: 2.6.12 #### I am using the 2.7.1 version when the issue happens ####
07.07 18:24:38 [Server] INFO Name: uSkyBlock
```
_What steps will reproduce the problem?_
1. Whenever I start the server using the 2.7.1 USB version I get this error happen and it does not update the UDIDs. Also USkyBlock is completely unusable and I cannot even do /usb version, which is why I had to downgrade again to post the information above

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: http://pastebin.com/GEy4k90G

**Comment by dutchy1001** [comment]
try using the latest DEV builds of WE and WG
WE [here](http://builds.enginehub.org/job/worldedit?branch=master
WG [here](http://builds.enginehub.org/job/worldguard?branch=master)

**Comment by rlf** [comment]
Seems it's the 2.7.1 that isn't compatible with MC 1.8.8.
I'll see if we can make a compatible release.

**Comment by dutchy1001** [comment]
v2.7.1 had bugs, v2.7.2 seems to have it fixed as no more complains have been made.
Closing this.
