### ISSUE TITLE
Better default-challenges

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#821]
We've previously given the `challenges.yml` an overhaul.

I think it's about time we did it again.

Things to consider:
- Don't require ALL challenges in each rank complete before moving on, but rather make a nice "progression". I.e. Farmer II should depend on all the farmer challenges, but not on the nether rank.
- Make a "tree" of challenges, i.e. utilitize the `requiredChallenges` on challenge basis and use the `lockedDisplayItem` to visualize the tree.
- Adjust the rewards (i.e. giving a bow and arrows to the user after they most likely have a mob-farm seems just plain provocative).

I'll whip up a rough suggestion - but any input is valued.

**Comment by BlackBeltPanda** [comment]
Something I like to do that's useful for servers with shops is to have an on-island challenge to unlock future repeatable challenges. For example, with a challenge that requires carrots:
- First challenge requires X amount of carrot crops on the island one-time. Unlocks the second challenge.
- Second challenge requires X amount of carrots to be turned in and is repeatable.

This helps prevent restarting an island and simply buying all the required items from the shop to spam-complete challenges.

**Comment by rlf** [comment]
Good suggestions @BlackBeltPanda .
Will try to somehow weave that into the re-design.

**Comment by rlf** [comment]
I get the reasoning behind this requirement, but since dirt is inheritently hard to come by on uSkyBlock, it seems a rather harsh requirement for players to have farms of a certain size early on in the game.
Which would be required if we said, that they must first build a farm of say 32 carrots, before opening the repeatable of 64 carrots. Perhaps not for carrots, but if wheat, melons, pumpkin should have the same "design", it wouldn't match the "play-style" of a skyblock.

**Comment by BlackBeltPanda** [comment]
Could just require one, at least makes them grow something.

**Comment by rlf** [comment]
What about losing the ranks? I.e. still having them (for grouping challenges), but just not show them in the UI? That way, we would get 5 more slots per page, and if we instead introduced "slotIndex" (or something similar) to the challenges, we could allow for more versatile challenge-layouts (i.e. having a rank/group shown vertical instead of horizontal).

**Comment by rlf** [comment]
And, actually, what you need, is more like a challenge that is mixed between `onIsland` and `onPlayer`.
Having an `onIsland` for first completion, and `onPlayer` for subsequent.

Would actually be pretty simple to introduce the concept of "repeatable" for onIsland, and just assume that the repeat is `onPlayer` instead.

**Comment by BlackBeltPanda** [comment]
I like the slotIndex idea, would definitely make the challenge GUI more versatile. =)

**Comment by dutchy1001** [comment]
Many challenges have been adjusted or added to the plugin. As this will be an ongoing quest and adjusted when needed we can close this.
