### ISSUE TITLE
Compatibility with Deluxechat placeholders

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#824]
Can we add placeholders that are compatible with DeluxeChat?
Currently it is only possible through MvDWPlaceHoldersAPI and a **paid** plugin of the same developer.
If we can skip the "middleman" it would make it for both plugins (usb and DeluxChat) more accessible to more server owners that have a low budget but still like to use the placeholders we supply.

**Comment by rlf** [comment]
See https://github.com/extendedclip/DeluxeChatPlaceholderAPI/blob/master/src/me/clip/placeholdertest/PlaceholderTestPlugin.java

**Comment by dutchy1001** [comment]
Placeholders are now working with DeluxeChat. A full list will be posted later

**Comment by aycgit** [comment]
This one can also be closed :/ is it possible i could get permission to help with all the issues reported here?

**Comment by dutchy1001** [comment]
You can clone the repository and submit pull requests, our main dev will then have a look and if he thinks it will benefit the plugin he will then accept it or deny it.

**Comment by rlf** [comment]
All help is welcome aycgit, but we've had quite many... lessons learned, regarding trusting ppl too soon.
So, feel free to comment on stuff, and fix it, and make a pull request.
If you do it in a manner that doesn't break too much, you will eventually get direct access.
