### ISSUE TITLE
Review the plugin.yml esp. reg. default permissions

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#825]
_Please paste the output from `/usb version` below_
```
v2.7.2+
```

The `plugin.yml` has not been updated with the same speed that we refactored the permission nodes, we need to make sure it correctly contains sensible default values for the various groups.

**Comment by aycgit** [comment]
Suggestion: keep issue section clean, this is fixed in 2.7.2 so it can be closed :)
Love minimodding and helping devs :+1:

**Comment by dutchy1001** [comment]
The new plugin.yml does work fine, this will be closed now.
