### ISSUE TITLE
Villager dispawn

### ISSUE THREAD

**Issue by Alibabaand40voleur** [rlf/uSkyBlock#826]
_Please paste the output from `/usb version` below_
![capture](https://cloud.githubusercontent.com/assets/18491206/16852421/57bf9b54-4a08-11e6-9fe0-fa25f74906ec.PNG)

_What steps will reproduce the problem?_
1.Put villager in your island
2.Wait
3.He will dispawn

**Comment by rlf** [comment]
99% sure this is not caused by uSkyBlock, since we NEVER despawn anything. We DO how-ever block spawning, if the limits has been reached. But that is an entirely different case.

**Comment by Alibabaand40voleur** [comment]
Okay, thank you I'll keep searching
