### ISSUE TITLE
Island Level placeholder stopped working in FeatherBoard after update to 2.7.1

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#827]
_Please paste the output from `/usb version` below_
```
 Name: uSkyBlock
 Version: 2.7.1
 Description: Ultimate SkyBlock v2.7.1-47aaa9-425
 Language: en (en)
   State: d=500, r=152, i=1,844, p=10,854, n=false, awe=true
 ------------------------------
 Server: Paper git-Paper-806 (MC: 1.10.2)
 ------------------------------
 Vault 1.5.6-b49 (ENABLED)
 WorldEdit 6.1.3;7a097ca (ENABLED)
 WorldGuard 6.1.2;e38d98d (ENABLED)
 AsyncWorldEdit 3.3.12 (ENABLED)
 Multiverse-Core 2.5-b719 (ENABLED)
 Multiverse-NetherPortals 2.5-b710 (ENABLED)
 ------------------------------

```

After updating to 2.7.1 from 2.6.12, the placeholder in FeatherBoard for island levels no longer seems to work.
Originally the placeholder I used was "{uskyblock_level}", but I've also tried "{usb_island_level}".
Not sure if this is a FeatherBoard issue or a uSkyBlock issue.

**Comment by BlackBeltPanda** [comment]
Seems the issue was related to this one: https://github.com/rlf/uSkyBlock/issues/828
The "{uskyblock_level}" placeholder works but sometimes fails when those errors appear.

**Comment by dutchy1001** [comment]
Not sure if changes have been made in that version but you can try to use
- %uskyblock_island_level%
- %placeholderapi_uskyblock_island_level%

We have added in a later version the compatibility with Clip's [PlaceHolderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/), this then results in that you don't need the use of MaximvdW's paid plugins to make placeholders work (MaximvdW is also still supported).

**Comment by rlf** [comment]
Hmm, the stacktrace is concerning, but has nothing (directly) to do with the placeholders - ChatControl might have decided to blacklist uskyblock after that trove of exceptions though.

**Comment by dutchy1001** [comment]
think the placeholders will be fixed with the dev version we use internally.

**Comment by BlackBeltPanda** [comment]
Been getting this several times with random players.

**Comment by BlackBeltPanda** [comment]
I think it's fixed, haven't had any issues with it.
