### ISSUE TITLE
Add polarbears

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#830]
_Please paste the output from `/usb version` below_

```
2.7.2
```

We need polar-bears!!!

Please add the Iceplains Biome to the plugin

**Comment by aycgit** [comment]
https://github.com/rlf/uSkyBlock/blob/7bc5536018e6e76a1bd97f29685023608dc2aa90/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/island/BiomeCommand.java Ez edit to add iceplains

**Comment by dutchy1001** [comment]
I'm not sure what your trying to get at, but we do know how to code (well rlf does, lol) and were to add it

**Comment by rlf** [comment]
@aycgit you are more than welcome to fix issues, just make a fork, fix it, make a pull request, and include a comment with a reference to the issue.

**Comment by dutchy1001** [comment]
should work now
