### ISSUE TITLE
USkyblock gui and perms

### ISSUE THREAD

**Issue by hyperionowner** [rlf/uSkyBlock#833]
Hello, so users do /is and it opens up a gui saying accept rules, they click and it does nothing.. also users can build on islands that they are not a member of?

**Comment by dutchy1001** [comment]
If you filled in the standard form when clicking on the "new issue" button then we could have an idea were the issue comes from.
What you referring too is decades old as far I know. Try updating.

**Comment by dutchy1001** [comment]
no further commets made, closing this
