### ISSUE TITLE
Can't place saplings on dirt

### ISSUE THREAD

**Issue by JustAquaTV** [rlf/uSkyBlock#834]
Hi, my uSkyBlock version is 2.7.2.
I am having an issue with placing saplings on dirt, it simply won't let you and i'm wondering if you can change it so you can.

**Comment by dutchy1001** [comment]
I've just tested this on our server but saplings can be placed on dirt without any problem.
I presume this is caused by something else then uSkyblock

**Comment by rlf** [comment]
If you have GriefPrevention installed, it might be causing this.
It has a setting disallowing growing trees on "one layer of dirt".

Disable the feature `LimitSkyTrees` in the config.

If you don't have GriefPrevention, odds are it's another (but similar) plugin that is limiting you from growing tress.

One thing is sure, it's not uSkyBlock.
