### ISSUE TITLE
Cant load plugin v2.7.2

### ISSUE THREAD

**Issue by xkxksk1234** [rlf/uSkyBlock#835]
_Please paste the output from `/usb version` below_
``` 
2.7.2
```  

_What steps will reproduce the problem?_
1. cant plugin enable

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin 
http://pastebin.com/D1TDA3R1

**Comment by dutchy1001** [comment]
plz have the full output of **/usb version** or a startup log if this doesn't work.

**Comment by xkxksk1234** [comment]
can't load plugin

**Comment by dutchy1001** [comment]
cant help with no info

**Comment by dutchy1001** [comment]
new post is made, closing this

**Comment by rlf** [comment]
We require Java 8, you are running Java 7.
