### ISSUE TITLE
 InventoryMoveItemEvent Error

### ISSUE THREAD

**Issue by xkxksk1234** [rlf/uSkyBlock#836]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.7.1
Description: Ultimate SkyBlock v2.7.1-47aaa9-425
Language: korean (korean)
State: d=200, r=75, i=549, p=723, n=false, awe=false
------------------------------
Server: CraftBukkit git-Spigot-e000104-4cb3258 (MC: 1.9.2)
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.3;7a097ca (ENABLED)
WorldGuard 6.1 (ENABLED)
Multiverse-Core 2.5-b716 (ENABLED)
------------------------------
```

_What steps will reproduce the problem?_
Sorry I'm not good english. So i can't understand this question.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: http://pastebin.com/pHGz65My

**Comment by dutchy1001** [comment]
use v2.7.2  
the 2.7.1 has bugs in it for servers running 1.8 or 1.9 servers.
You also can update Worldguard, use the links provides on this page, [click here](http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/installation/).
