### ISSUE TITLE
10 Blocs challenge

### ISSUE THREAD

**Issue by Alibabaand40voleur** [rlf/uSkyBlock#838]
_Please paste the output from `/usb version` below_

![capture](https://cloud.githubusercontent.com/assets/18491206/17151614/8cf1d81c-5374-11e6-8f33-2cb7dcd02d37.PNG)

_What steps will reproduce the problem?_
1.Create challenge with OnIsland
2.
![challenge block](https://cloud.githubusercontent.com/assets/18491206/17151643/a18393c4-5374-11e6-9d18-df57511d1139.PNG)

I want to Up the " 10 Blocks " How can i please ?

**Comment by dutchy1001** [comment]
add to the challenge settings:
```

#        # To override the default radius when using onIsland, uncommend the "radius: " and fill in your own value.
        radius: 20
```
This will "up" it for you with 10 block to 20 (defaukt is 10), ofcourse you can add a higher number too.

**Comment by dutchy1001** [comment]
not an issue but config setting, closing now
