### ISSUE TITLE
CacheLoader returned null for key

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#840]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.7.2
Description: Ultimate SkyBlock v2.7.2-45f756-430
Language: en (en)
State: d=500, r=152, i=2,107, p=11,111, n=false, awe=true
Server: Paper git-Paper-819 (MC: 1.10.2)
State: online=false, bungee=true
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.3;7a097ca (ENABLED)
WorldGuard 6.1.2;e38d98d (ENABLED)
AsyncWorldEdit 3.4.0 (ENABLED)
Multiverse-Core 2.5-b719 (ENABLED)
Multiverse-NetherPortals 2.5-b710 (ENABLED)
------------------------------
```

Been getting these errors quite a bit recently with seemingly random players. They seem to happen out of the blue: http://pastebin.com/raw/5qQPqsA4

**Comment by dutchy1001** [comment]
It looks to me that the lookup of the UUID failed, maybe the mojang server is offline at that point. 
Not sure if there is a backup solution from mojang that can be added.
But that is just a guess from me.

**Comment by rlf** [comment]
Can you share the entry for the above UUID in your `uuid2name.yml` file? (warning, will be quite large).

**Comment by BlackBeltPanda** [comment]
Haven't seen the error since the commit; seems to be fixed. =)
