### ISSUE TITLE
Challenges are repeatable infinitely if they are containing "commands"

### ISSUE THREAD

**Issue by i9hdkill** [rlf/uSkyBlock#842]
_Please paste the output from `/usb version` below

usb version
[16:18:45 INFO](------------------------------): Name: uSkyBlock
[16:18:45 INFO](------------------------------): Version: 2.7.2
[16:18:45 INFO](------------------------------): Description: Ultimate SkyBlock v2.7.2-45f756-430
[16:18:45 INFO](------------------------------): Language: de (de)
[16:18:45 INFO](------------------------------):   State: d=110, r=50, i=18.390, p=34.693, n=false, awe=false
[16:18:45 INFO](------------------------------): Server: CraftBukkit git-Spigot-90f61bc-83a9dbd (MC: 1.10.2)
[16:18:45 INFO](------------------------------):   State: online=false, bungee=true

[16:18:45 INFO](------------------------------): Vault 1.5.6-b49 (ENABLED)
[16:18:45 INFO](------------------------------): WorldEdit 6.1.3-SNAPSHOT;3558-5a42a8d (ENABLED)
[16:18:45 INFO](------------------------------): WorldGuard 6.1.3-SNAPSHOT;1670-4ab38e5 (ENABLED)
[16:18:45 INFO](------------------------------): Multiverse-Core 2.5-b719 (ENABLED)

[16:18:46 INFO]: [BuycraftX] Fetching all due players...
[16:18:48 INFO]: [BuycraftX] Fetched due players (66 found).

What steps will reproduce the problem?
1. Use /c
2.click novice builder
3. You can use it as often as you want with getting the rewards

error on click:
http://pastebin.com/MpdhAvXH

Our challenges:
http://pastebin.com/wXsPLDbn

**Comment by dutchy1001** [comment]
I cant reproduce this on our test server. Is this the only challenge that does this?

The challenges are getting a total overhaul in the next coming weeks, #821

**Comment by rlf** [comment]
Sounds like a bug in the de translation.
Make sure the challenge-menu related translations are translated identically.

**Comment by dutchy1001** [comment]
never thought of that

**Comment by i9hdkill** [comment]
rlf, that was my first thought, but I changed the language with /usb lang en, error is still there

**Comment by dutchy1001** [comment]
you might need to restart the server in that case

**Comment by BlackBeltPanda** [comment]
I just had this problem yesterday with one of my challenges.
Challenge: http://pastebin.com/raw/707u8VUp

One of my staff members accidentally reset that challenge for a player and the player was then able to complete it repeatedly.

Version info:
```
Name: uSkyBlock
Version: 2.7.2
Description: Ultimate SkyBlock v2.7.2-45f756-430
Language: en (en)
State: d=500, r=152, i=2,107, p=11,111, n=false, awe=true
Server: Paper git-Paper-819 (MC: 1.10.2)
State: online=false, bungee=true
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.3;7a097ca (ENABLED)
WorldGuard 6.1.2;e38d98d (ENABLED)
AsyncWorldEdit 3.4.0 (ENABLED)
Multiverse-Core 2.5-b719 (ENABLED)
Multiverse-NetherPortals 2.5-b710 (ENABLED)
------------------------------
```

**Comment by i9hdkill** [comment]
The level 100 challenge is not affected

**Comment by i9hdkill** [comment]
Fixed it by removing
commands:
          - op:effect {party} regeneration

**Comment by dutchy1001** [comment]
have you tested this with other challenges with commands too?

**Comment by rlf** [comment]
Actually. I was wrong then, it's not the `de` translation, it's the fact that some of the members has not been correctly converted (I fear), since they result in `null` when the UUID is used to get a player object.

**Comment by rlf** [comment]
Do you have multiple challenges with the same displayname?

**Comment by rlf** [comment]
Can't reproduce this, need some more info.

Is it only when using the `{party}` tag? Is it only when a non-leader completes a non-repeatable island challenge?

**Comment by i9hdkill** [comment]
challengeSharing: island
The leader completed the challenge.
The issue was a invalid player on the island.
Island file:
http://pastebin.com/d4s0KVKF

The current uuid converter fails hard, I just got why.

On my island you can see two "HexagonMC" members.
Normally, just one should be there:
12af1a97-36df-4bb6-b6ba-03205d0a867e

Because the converter takes the names from uuidtonames, he got two uuids for the HexagonMC account.
In the past another member had the name HexagonMC and was online on our server.
After logging out, he never came back online. He is now stored in nametouuid.

Some months later, I changed the name from my secondary account to HexagonMC.
That uuis/name is also in thge uuidtoname.

The converter took both uuids and added it to the island.

In the end I had one "null" player on my island. (saw it via /is party)

**Comment by rlf** [comment]
Ok, so this seems to be a configuration issue, since I take it this will not occur in the future, it's a combination of historical (incorrect) data (the double members), and the conversion from name to UUID.

It is (however), interesting how a similar case will be handled in the future.

**Comment by i9hdkill** [comment]
I would suggest requesting all uuids from the mojang api, takes longer, but is safe.

**Comment by rlf** [comment]
The reason we use the uuid2name first, is to have a cache of the UUID and names, since Mojang throttles access to it's servers (max. 600 requests per 10 minutes).

But yes, any exceptions occurring from the commands should not abort the completion.

**Comment by i9hdkill** [comment]
Oh yeah, I mean just skipping the uuid2name when doing the one-time convert from names to uuids. Doesn't help people that are alrdy facing this issue, but at leats prevents it for people that will update to 2.7.x in the future.

**Comment by rlf** [comment]
I'd rather try to fix the bug, where multiple entries in uuid2name can occur for the same name.

**Comment by i9hdkill** [comment]
Thanks, will test later the day.
Will these changes fix this error aswell?
http://pastebin.com/v6w7nATq

**Comment by rlf** [comment]
Yes, it should.

**Comment by dutchy1001** [comment]
no further comments, presume this is fixed
