### ISSUE TITLE
Allow multiple biomes on the same island

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#843]
_Please paste the output from `/usb version` below_

```
2.7.2
```

We currently allow certain players to change the biome of the complete island.
But. We could change this to be "per-chunk", and then per default use the biome-permissions more strictly as a challenge reward.

Say, once you gather enough slime to deliver 64 slimes, you could get the permission to the swamp biome, and then use it in a specific area of your island (controlling where slimes spawn).

Then once you get the animal farm, you could get the `usb.biome.plains` permission, and again, you could designate an area of your island to that biome.

Also, completing the fisher-man challenge could give you access to the `usb.biome.deep_ocean` permission node, allowing you to farm Guardians etc.

**Comment by dutchy1001** [comment]
confirmed working
closing
