### ISSUE TITLE
Bypass permission for locked islands not working

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#845]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.7.2
Description: Ultimate SkyBlock v2.7.2-45f756-430
Language: en (en)
State: d=500, r=152, i=2,107, p=11,111, n=false, awe=true
Server: Paper git-Paper-819 (MC: 1.10.2)
State: online=false, bungee=true
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.3;7a097ca (ENABLED)
WorldGuard 6.1.2;e38d98d (ENABLED)
AsyncWorldEdit 3.4.0 (ENABLED)
Multiverse-Core 2.5-b719 (ENABLED)
Multiverse-NetherPortals 2.5-b710 (ENABLED)
------------------------------
```

_What steps will reproduce the problem?_
1. Apply "usb.mod.bypassprotection" permission
2. Teleport to a locked island

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* screenshot: https://i.gyazo.com/5d7e235706dacc14e82c029e885a9a24.png
* island .yml: http://pastebin.com/raw/JwDjY86i

**Comment by rlf** [comment]
When you write "Teleport to a locked island", how are you teleporting?
`/usb goto <name>`?

**Comment by rlf** [comment]
NVM, found the bug. Accepted

**Comment by dutchy1001** [comment]
don't you need the WorldGuard permissions for this to work?

-         - worldguard.region.bypass.skyworld
-         - worldguard.region.bypass.skyworld_nether

**Comment by BlackBeltPanda** [comment]
Working now, thank you! =D
