### ISSUE TITLE
Entities protection bug?

### ISSUE THREAD

**Issue by donbubu** [rlf/uSkyBlock#847]
_Please paste the output from `/usb version` below_

```
 Name: uSkyBlock
 Version: 2.7.2
 Description: Ultimate SkyBlock v2.7.2-45f756-430
 Language: de (de)
   State: d=110, r=52, i=187, p=806, n=false, awe=false
 Server: CraftBukkit git-Spigot-8a048fe-042911f (MC: 1.9.4)
   State: online=false, bungee=true
 ------------------------------
 Vault 1.5.6-b49 (ENABLED)
 WorldEdit 6.1.3;7a097ca (ENABLED)
 WorldGuard 6.1.2;e38d98d with custom flags plugin. (ENABLED)
 ------------------------------
```

We have a default nether without Nether-block. In config, nether = false.
The players on our server tell me, that they can't damage some entites in nether and end (blaze, wither skeleton, enderman).
Magma-slimes, Ghast and Shulker works.
On skyblock world all entites works.

**Comment by rlf** [comment]
Does the region where this occur have a world-guard region?
If yes, what is it called?

**Comment by rlf** [comment]
You were right, we are to blame.
Fix pushed, and will be part of v2.7.3

**Comment by donbubu** [comment]
ok, thank. First i think it was worldguard an check any config at this point, but there is only the global region. than i checked the uskyblock config and set the terraform for nether to false. than i check all uskyblock permissions and find nothing and than i post it here.

**Comment by dutchy1001** [comment]
Has this been retested and confirmed fixed??
Plz some input of the OP

**Comment by donbubu** [comment]
hi :)
Yes, all entities in nether works, a big thanks on the devs :)
