### ISSUE TITLE
Built-in skyblock shop

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#848]
Most servers seems to be using some sort of server-shop to go along with uSkyBlock.

We support customizing the main-menu, say to introduce ChestCommandGUI or similar.

But, since it seems the game-play is best with an in-game shop, allowing players to convert in-game currency, or XP to items (saplings, buckets, lava, water), perhaps we should consider adding support for our own?

Not sure this is a good idea, since there are already so many nice plugins out there, but I've just lost my bucket too many darn times - and I think a lot of other players feel the same.

Any comments?

**Comment by supertin** [comment]
If it allows for **simple to use** server->player sales, then it'd be awesome.
I've come across a lot of shop plugins that aren't instantly clear how to use, or that require typing commands. These simply don't work well for younger kids.

Personally, I'm currently using SignShop2 in conjunction with Holographic Displays (for floating items) to sell items to players. Very simple to use, but a little time consuming to set up. But it does look awesome. And you can embed the items into glass blocks too :+1: 
To give you an idea of what I've done:
![Uploading 2016-08-07_20.04.49.png…]()
![2016-08-07_20 05 32](https://cloud.githubusercontent.com/assets/11795789/17461754/5f91d8b2-5cda-11e6-874d-feab2d3faa40.png)

**Comment by rlf** [comment]
Ye, I've seen a ton of those, but we need it to be an "in-game GUI" (i.e. inventory), since we cannot control the spawn/shop-area.

I will see what can be done....

**Comment by supertin** [comment]
I think I might have left my main point out (posting late at night, half asleep).... My main concern is **simplicity**. If players need to enter commands, read too much, or have to work out how the GUI works, it won't work for casual players.

Some more thoughts, now that I'm awake:
* Some admins will want to allow players to sell off their junk. Some will only want to let players buy things. Use permissions to control who can buy and who can sell?
* Specific items may need to be set as buy only or sell only. For example, cobble might be OK to sell to lazy players, but you normally aren't going to want players making any money by AFK farming it and selling it back.
* "Tax" or "Shop margin" - items sold by the shop should be higher priced than what the player gets for selling to the shop. Global option as a percentage, but allow individual items to have a different rate if required.
* Allow for multiple "shops" to be created. Have a GUI like the island schematic selection where you choose which shop you want to browse, and admins can set up different "types" of shops. Like a food shop, a tool shop, etc.

**Comment by rlf** [comment]
Made a Spigot Forum post asking for suggestions: https://www.spigotmc.org/threads/good-free-shop-gui-plugin.170974

**Comment by rlf** [comment]
Closing this, since servers can easily integrate their own shop-setup (and often do).
