### ISSUE TITLE
/is restart, /is create GUI

### ISSUE THREAD

**Issue by OMGYES** [rlf/uSkyBlock#851]
Name: uSkyBlock
Version: 2.5.7
Description: Ultimate SkyBlock v2.5.7-03f5db-391
Language: en (en)

Server: CraftBukkit git-Spigot-db6de12-18fbb24 (MC: 1.8.8)

Vault 1.5.6-b49 (1.5.6-b49)

WorldEdit 6.1.3;7a097ca (6.1.3;7a097ca)

WorldGuard 6.1.2;e38d98d (6.1.2;e38d98d)

Multiverse-Core 2.5-b711 (2.5-b711)

Multiverse-Portals 2.5-b735 (2.5-b735)

I need this really bad.... An option in the config were you can disable or enable the schematic gui on /is create and /is restart. Because I only use 1 schematic, and it's getting annoying to click on the icon when there's only 1 schematic... If I had 2 schematics, you should need a GUI but I have one!

Please just add an option to enable or disable those 2 gui's or at least the restart gui :P

**Comment by dutchy1001** [comment]
your turn to test this now mac

**Comment by OMGYES** [comment]
Does this mean I need to download a new version?

**Comment by dutchy1001** [comment]
yes

**Comment by rlf** [comment]
Well, TBH it's not completely "disableable", since we still have the "main-UI" - but at least it won't list the schemes.

If you need to change the wording of one of the menu-items, that is doable too - See https://github.com/rlf/uSkyBlock/wiki/Translations

**Comment by OMGYES** [comment]
I'm really sorry for not responding, I had some issues. I'm greatful for this update, but.... how do I download it?

**Comment by dutchy1001** [comment]
Maybe try [here](https://github.com/rlf/uSkyBlock/releases)

**Comment by dutchy1001** [comment]
this is added and working
