### ISSUE TITLE
Lag Spikes when searching up player info

### ISSUE THREAD

**Issue by iaxedu** [rlf/uSkyBlock#857]
Results from USB version:/usb v
http://i.imgur.com/oJyOI2E.png

^ Important my server is cracked but it doesn't detect it. Server is behind a BungeeCord. The offline detection does not work when you put it behind a BungeeCord.

Anyhow my issue is lagspikes from getting player info as can be seen here: http://hastebin.com/tewemekizi.avrasm

Might be caused since the server thinks we're online mode?

**Comment by rlf** [comment]
Might be, not sure why you are not simply using offline mode?

Our online detection code is two-fold:
a) It checks the server.properties
b) It checks the result of looking up the UUID of `R4zorax`.

We mitigate the lag-spikes by populating the uuid2name.yml UUID cache, and if that is "wrong", it will not be performant.

**Comment by iaxedu** [comment]
Well I've added R4zorax to the cache just now with the offline UUID but it still returns true when checking if the server offline mode or not. This is being spammed atm: http://i.imgur.com/VD7JOQO.png

**Comment by iaxedu** [comment]
Is there a reason why the FilePlayerDB.java uses synchronized threads? Currently running a version of my own without that which has solved my issues.

**Comment by rlf** [comment]
Good luck then - you will get some annoying concurrency issues later, stemming from the non-thread-safe way YmlConfiguration is saved.

It's hard to get any sensible bearings in your screendumps of a performance report, it would be helpful if you can share something along the lines of what `/timings report` generate for spigot or paper.

**Comment by rlf** [comment]
Try the above fix out - that should have a more narrow use of synchronization - and should work without the concurrentmodificationexception thrown from YmlConfig on save.

**Comment by rlf** [comment]
Note: It will still not peform, during initialization, but once the caches has been loaded - it should be much more performant.

**Comment by dutchy1001** [comment]
performance has been increased with the later versions
Closing this for now
