### ISSUE TITLE
Nether portals spawn outside nether-region

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#86]
@woolwind
I have this problem in both 2.0 for 1.7.10 and the current dev release for 1.8  - nether portals on islands open on the bedrock above the nether. 
I followed instructions:

/mv create skyworld_nether NETHER.
/mv tp skyworld_nether
/mvm set scale 1.0

creating portals much lower than island level fixes it, but of course players will normally do it somewhere near default height.

any clues?

**Comment by dutchy1001** [comment]
this was fixed with the custom version of the mv netherportal plugin
