### ISSUE TITLE
Re-introduce i18n keys from bukkit-utils

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#861]
When we moved po-utils and bukkit-utils to seperate repositories, we lost the i18n scanning of the source-files.

Find a way to still maintain those keys in keys.pot

**Comment by rlf** [comment]
Requires the use of:
```
git clone --recursive
```
But `bukkit-utils` is now a git-submodule to `uSkyBlock´ (I bet the build-server don't like it).

**Comment by dutchy1001** [comment]
so far working as should
closing
