### ISSUE TITLE
Player skulls in levelConfig.yml will not change.

### ISSUE THREAD

**Issue by SirApathy** [rlf/uSkyBlock#868]
_Please paste the output from `/usb version` below_
uSkyBlock: v2.7.2 (v2.7.2-45f756-430)
Not sure if others are necessary since it's a uSkyBlock bug I believe.

_What steps will reproduce the problem?_
1. Go in levelConfig.yml
2. Try to change ANY values for player skulls
3. Reload config in game, players skulls still count as 10 island levels no matter what values you put.

Every time you place a skull, no matter what the amount of levels it has is set to, no matter what amount you set it to in blocklimits, and no matter what your pointsPerLevel is set to, skulls always count as 10 levels.

**Comment by dutchy1001** [comment]
What ID do you use for the skulls?

**Comment by SirApathy** [comment]
In the levelConfig.yml I set 2 different ways and I've tried a bunch of varients. To my understanding, a skull is ID 397, so in config i tried 397: (value), 397/0: (value) 397/1-5: (value), and none of them work no matter what value I put in value portion. My pointsperlevel is set to 100 (1000 was default like you said).

**Comment by dutchy1001** [comment]
Skull ID = 144:1>5, I know this is confusing as there in the ID list twice. You probably have the ID 144 already set.

As I use the latest dev build ([v2.7.3alpha](https://github.com/rlf/uSkyBlock/releases/tag/v2.7.3-alpha5)) this is not happening, plz check the config if the message is disabled.

There is already an issue created for the party size here #867

**Comment by SirApathy** [comment]
Ahhh alright aha thank you very much Dutchy! The ID 144 worked perfectly and I did miss the worldguard strings for leave and enter messages. I swear I've been in the config hundreds of times but for some reason it feels like it updated itself, my mistake aha.

I'm unable to test using the possible fix from the post #867 but I'm sure it will work now, thank you again. Issues have been resolved.
