### ISSUE TITLE
Deleted island spaces are not reused

### ISSUE THREAD

**Issue by Quisalas** [rlf/uSkyBlock#876]
Just installed usb last night on the server and everything's perfect except that I can't figure out how to get it to reuse empty island spots.  I can force this by placing a bedrock into an island plot and then registering it to a player and then having them restart that island, but when someone uses the /is create (or the gui) to make a new one, it skips over the empty slots to the first never-used plot.

I have tried clearing orphans (there are none listed) and I also tried purging (which said it removed players, islands, and challenges but did not actually seem to remove any of those).  I also removed the yml files that had been created for the now-deleted islands, but it just recreated the files for the empty ones when the next island was created.

Is there a command I'm missing or is reusing empty plots not enabled?

Thanks!
~Quisalas, mcmetaverse.com

_Please paste the output from `/usb version` below_

```
Name: uSkyBlock
Version: 2.7.2
Description: Ultimate Skyblock v2.7.2-45f756-430
Language: en (en)
  State: d=128 r=64 i=14 p=7 n=true awe=true
Server: CraftBukkit git-Spigot-078e2f8-7f9fbe5 (MC:1.10.2)
  State: online=true bungee=false

Vault: 1.5.3-b37 (Enabled)
WorldEdit: 6.1.3;7a097ca (Enabled)
WorldGuard: 6.0.0-beta-05.1569- (Enabled)
AsyncWorldEdit 3.4.0 (Enabled)
Multiverse-Core 2.5-b717 (Enabled)
Multiverse-Portals 2.4-b548 (Wrong-Version)
Multiverse-NetherPortals 2.5-b675 (Enabled)
```

_What steps will reproduce the problem?_
1. Delete an island
2. Create a new island
3. Island is not created in the now-empty space

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
- server-log: link-to-pastebin

**Comment by rlf** [comment]
Sounds like you used `/usb flush` and not `/usb purge`...

**Comment by Quisalas** [comment]
The initial command used was /usb island delete playername.  And I tried both purge and flush last night.  Purge before flush, but I think you're right and flush was the one that gave that response.

**Comment by dutchy1001** [comment]
I have recently used the _/usb purge 14_  (14 days) command and all islands that qualified for this purge were listed in the _orphan.yml_.
After this I deleted a players island which was added to the orphan.yml aswell.
I do use v2.7.3alpha but as far I know there has been a few small changes to the purge since v2.7.2.

**Comment by Quisalas** [comment]
This issue is still not resolved.  Any recommendations on how to enable these island spaces to be repopulated?

**Comment by dutchy1001** [comment]
After the first time it failed the locations will probably not being used anymore as the  player files have been deleted/reset. 
The only way to re-add them then is to add them to the orphan.yml is manual.

The easiest way to do this is with the help of [Dynmap](https://www.spigotmc.org/resources/dynmap.274/)  and the [WorldGuard expansion](http://mikeprimm.com/dynmap/builds/Dynmap-WorldGuard/) so you get an online map to see were and what is available for re-use, see my own example [here](http://uskyblock.redirectme.net:8123/). 
After I made a screen shot I edited it in paint like this [here](http://i.imgur.com/D9UA6j5.png) just to make it easier for myself.
The orphan file will look like this then
```
orphans:
- XXX,ZZZ <--only for show, not showing in the file
- -256,512
- 256,-512
- 256,512
```
You do need to check the island folder for the locations you add. If you add a location you have to delete the XXX,ZZZ.yml file.

I hope this helps

**Comment by rlf** [comment]
A new purge should detect the falsely non-deleted island files, I think...

**Comment by dutchy1001** [comment]
no further issues found with deleting islands
