### ISSUE TITLE
Untranslateable variables

### ISSUE THREAD

**Issue by UnioDex** [rlf/uSkyBlock#878]
Hello, i am trying to translate uSkyBlock. But somethings are not translateable. When i write /is help i found at least 3 and I marked them:

http://prnt.sc/ck1403

Also item names are not translateable. They are seems in challenge rewards, requirements.

**Comment by rlf** [comment]
The top and bottom one is part of #861 - the middle one is the one dutchy mentions.

**Comment by rlf** [comment]
Sorry, was too fast. Challenge-names are taken from the challenges.yml file - i.e. they are fully "server-owner customizable", meaning we cannot translate them.
If your server-owner provide a language-based challenges.yml (i.e. `challenges_da.yml`) it will be used for that language.

**Comment by UnioDex** [comment]
I have no problems with challenge-names. I updated my .po file with keys.pot and "teleports you to your island (or create one)" problem is solved. The others are not too important but it is required for giving a promise to player server is 100% localizated.

You said item names taking from Minecraft and change my client language. My language was not English already. Also i tried change language from my client to Turkish, Danish, French. But item names were still English. 

P.S.: My version is still 2.7.2

**Comment by UnioDex** [comment]
Also there is more untranslateable places:
When write /is party to change players permissions. Permissions are not translateable. Descriptions are but not permission titles.

http://prntscr.com/ck5qhr
http://prntscr.com/ck5quq
http://prntscr.com/ck5qyh

**Comment by rlf** [comment]
* http://prntscr.com/ck5qhr (Toggle Island Lock, Change Biome, etc. - true (bug)
* http://prntscr.com/ck5quq - is translated here: https://github.com/rlf/uSkyBlock/blob/master/uSkyBlock-Core/src/main/po/keys.pot#L1970

**Comment by UnioDex** [comment]
I already translated that string "Permission". But it isn't changed.

**Comment by rlf** [comment]
> I already translated that string "Permission". But it isn't changed.

Not sure how to respond to that, so just going to say: "Na haa!!!"

**Comment by dutchy1001** [comment]
The part that is translated is in the GUI itself (Example : XXPermissionXX), Unio probably means the popup/hovertext  were the [_player name_] _permission_ isn't translated .....yet 

![2016-09-21_11 21 21](https://cloud.githubusercontent.com/assets/5569980/18707390/c54c7f6e-7fed-11e6-96e2-c9c0701589dd.png)

**Comment by UnioDex** [comment]
Yes i am talking about dutchy101's example. Not GUI title, item title.

**Comment by rlf** [comment]
got it! Thx

**Comment by UnioDex** [comment]
I found one more untranslateable sentence:
Invite sent to "player" when send invite a player.

**Comment by dutchy1001** [comment]
we probably will find more or when new code is added.
closing for now
