### ISSUE TITLE
Update usb version?

### ISSUE THREAD

**Issue by coco0325** [rlf/uSkyBlock#879]
_Please paste the output from `/usb version` below_
Multiverse-Portals 2.5-b725 (ENABLED)
Multiverse-Core 2.5.0-SNAPSHOT-b722 (ENABLED)
WorldGuard 6.1.2;e38d98d (ENABLED)
 WorldEdit 6.1.3;7a097ca (ENABLED)
Vault 1.5.5-b47 (ENABLED)
 ------------------------------
 Server: CraftBukkit git-Spigot-34287db-43ab266 (MC: 1.10.2)
 ------------------------------
Language: zh_tw (zh_TW)
Description: Ultimate SkyBlock v2.6.12-9e2d30-413
 Version: 2.6.12
 Name: uSkyBlock

_What steps will reproduce the problem?_
1.Can I update my usb to 2.7.2? It is Compatibility? or not?
2.
3.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

**Comment by dutchy1001** [comment]
yes v2.7.2 is compatible with the previous one.
You should update your Vault to version v1.5.6 as it has a few bug fixes.

**Comment by coco0325** [comment]
So I just change my jar?

**Comment by dutchy1001** [comment]
yes

**Comment by coco0325** [comment]
thank you!

**Comment by coco0325** [comment]
Need to reset my config?

**Comment by dutchy1001** [comment]
no, you should be good to go.

**Comment by coco0325** [comment]
OK!
