### ISSUE TITLE
REQ: General spawn instead of island spawn.

### ISSUE THREAD

**Issue by UnioDex** [rlf/uSkyBlock#886]
Hello,

My spawn is in another world and i want teleport player my spawn when they are quitting island or etc. Can you do this please?

**Comment by dutchy1001** [comment]
There is an option in the config that determent were they will teleport to when using the command **_/spawn_**.
```
  extras:
    # [true/false] If true, return players that don't have an island (this includes players removed from a party while offline), to the server spawn when they login.
    # NOTE: Requires EssentialsSpawn or another plugin with the "/spawn" command
    sendToSpawn: false
```

Set this to true and make sure you have a spawn plugin like EssentialsSpawn (or similar).

**Comment by UnioDex** [comment]
Thanks
