### ISSUE TITLE
Topten timeout not working (or etc.)

### ISSUE THREAD

**Issue by UnioDex** [rlf/uSkyBlock#888]
When everytime i use /is top command it is waiting too long. I think it is updating the list everytime. But i set in config topTenTimeout: 60

Info: my topten list is 1572 page. There is 475k user maybe it can be related with this.
Note: It is only happening with OP accounts. Normal users have no problem with that.

**Comment by rlf** [comment]
If you are OP, it will always recalculate the top ten.

There is a permission system allowing you to get "a fresh top 10", instead of the cached one.

Try doing it as a normal user.
