### ISSUE TITLE
When Ever my certain players go to there islands go to there islands it crashes and nether dosn't work

### ISSUE THREAD

**Issue by SGTPlays** [rlf/uSkyBlock#889]
_Please paste the output from `/usb version` below_
```2.7.7

```
2.7.7
_What steps will reproduce the problem?_
1.The Certain players going to there islands
2.Nether is enabled but you cant light nether portals
3.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

**Comment by dutchy1001** [comment]
Not following the guide to post an issue is subject to be closed.
I'll check tomorrow again for the right info we need or I will close it.
