### ISSUE TITLE
Nether Disabled

### ISSUE THREAD

**Issue by laRoux87** [rlf/uSkyBlock#892]
_Please paste the output from `/usb version` below_
```

28.09 18:47:12 [Server] INFO ------------------------------
28.09 18:47:12 [Server] INFO Multiverse-NetherPortals 2.5.0-SNAPSHOT-b712 (ENABLED)
28.09 18:47:12 [Server] INFO Multiverse-Core 2.5-b719 (ENABLED)
28.09 18:47:12 [Server] INFO WorldGuard 6.1.1-SNAPSHOT.1629-0fcd42f (ENABLED)
28.09 18:47:12 [Server] INFO WorldEdit 6.1.1-SNAPSHOT;3394-9a65bdb7 (ENABLED)
28.09 18:47:12 [Server] INFO Vault 1.5.6-b49 (ENABLED)
28.09 18:47:12 [Server] INFO ------------------------------
28.09 18:47:12 [Server] INFO State: online=true, bungee=false
28.09 18:47:12 [Server] INFO Server: CraftBukkit git-Spigot-570526c-75a8885 (MC: 1.10.2)
28.09 18:47:12 [Server] INFO State: d=110, r=55, i=13, p=13, n=false, awe=false
28.09 18:47:12 [Server] INFO Language: en (en)
28.09 18:47:12 [Server] INFO Description: Ultimate SkyBlock v2.7.2-45f756-430
28.09 18:47:12 [Server] INFO Version: 2.7.2
28.09 18:47:12 [Server] INFO Name: uSkyBlock
```

_What steps will reproduce the problem?_
1. Error below pops up in start up

I'm sorry if this is something silly! I've used uSkyblock for awhile now and LOVE how easy it has been to set up, but have never run into this issue. Your help is very much appreciated!

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
WARN Nether DISABLED, since islands cannot be chunk-aligned!

**Comment by dutchy1001** [comment]
It seems you have updated your server from a much older version (which is not a problem) but our nether feature we added is depending on those factors (be able to be divided by 32) to work properly.

Your "distance" and "protectionRange" settings in the config can not be divided by 32 (distance is 110/32= 3.4, this must be a full number only). To be able to use our new nether feature this is a requirement. However you can create an "normal" nether with Multiverse and call it skyworld_nether.

 With having 13 island on your server I would recommend to make a fresh start and use the newer default value's.
The new default "distance" and "protectionRange" is 128. Altering the config to the new default without resetting the world will bring many problems.

If you decide to make a fresh start then backup/delete the uskyblock folder and (sky)worlds and let the plugin create the new files. This will then automatic set it to the new default value's. You can alter, after the first server start the config to your liking. When your config is set you can then let your players create islands.

**Comment by laRoux87** [comment]
Everything seems to be working now! Thank you so much for your quick response - I really appreciate it!
