### ISSUE TITLE
skygrid fails to work,

### ISSUE THREAD

**Issue by AcesGamingUK** [rlf/uSkyBlock#893]
_Please paste the output from `/usb version` below_

```
"/usb version did not work in console or server so used version uSkyBlock"
29.09 17:31:03 [Server] INFO uSkyBlock version 2.7.2
29.09 17:31:03 [Server] INFO Ultimate SkyBlock v2.7.2-45f756-430
29.09 17:31:03 [Server] INFO Author: Talabrek, R4zorax and others
```

_What steps will reproduce the problem?_
1. starting server

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
- server-log: http://hastebin.com/cenijupine.md

**Comment by dutchy1001** [comment]
Could you post the uSkyblock config plz?
Also the uskygrid version is out of date, try this version from [here](https://dev.bukkit.org/bukkit-plugins/ultimate-skygrid/files/19-ultimate-sky-gridv-0-2-31/)

It seems that there is something not set right in the config, have you followed the guide provided [here](https://github.com/rlf/uSkyBlock/wiki/SkyGrid)??

**Comment by AcesGamingUK** [comment]
thanks for latest version
yes i followed those exact instructions

`# The language used in the plugin (en is default).
language: en
options:
  general:

    # [integer] The max number of players allowed in a single party. (including the leader)
    maxPartySize: 4

    # [integer] The time in seconds before a player can use the /island info command again. (note: cooldowns are reset when the plugin is reloaded)
    cooldownInfo: 20

    # [integer] The time in seconds before a player can use the /island restart command again.
    cooldownRestart: 30

    # [integer] The time in seconds before a player can use the /island biome command again.
    biomeChange: 180

    # [string] The default biome assigned to new islands
    defaultBiome: OCEAN

    # [integer] The number of milliseconds between the same notification is sent to the player.
    # This is used when events are triggered heavily - i.e. item-pickup-prevention, damage-prevention etc.
    maxSpam: 2000

    # [string] The name of the skyblock world, will be automatically generated if it doesn't exist.
    worldName: skyworld

    # [integer] Area around 0,0 where islands will not be created to protect spawn.
    spawnSize: 0
  island:

    # [integer] The y-coordinate (height) where islands are spawned.
    height: 65

    # [integer] The number of blocks between islands.
    distance: 400

    # [integer] The size of the protective region for each island. Can't be higher than 'distance'
    # and MUST be divisible by 32 if you intend to use nether.
    protectionRange: 128

    # [filename] The schematic to use for island generation.
    # Put your schematic in the 'uSkyBlock/schematics' folder, you don't need to add the '.schematic' part below.
    schematicName: mini

    # [true/false] If true, remove all hostile mobs when a player teleports back to their island.
    removeCreaturesByTeleport: false

    # [item list] The list of items to place in the chest when a player starts a new island. ITEM_ID:HOW_MANY.
    # default is 2 ice, 1 watermelon, 1 cactus, 1 lava bucket, 1 red & brown mushroom, 1 pumpkin seed, 1 sugar cane, 1 sign.
    chestItems: ''

    # [true/false] If true, add extra items to a chest when a player starts a new island. (for donors and special players)
    addExtraItems: false

    # [integer] The delay in seconds before teleporting to an island. Affects /is home, /is warp, /is spawn
    islandTeleportDelay: 2

    # Allow PvP on the island
    allowPvP: deny

    #[true/false] Allow players to completely lock their islands so non-party members can't enter. (locking still requires permission usb.lock)
    allowIslandLock: true

    # [true/false] If true, use island levels/ranks (/island info) - may have a slight impact on performance
    # Set to false if you have performance issues
    useIslandLevel: false

    # [true/false] Whether or not /is top should be available.
    useTopTen: true

    # [integer] The time in minutes for how often the top-ten list will be re-generated when doing /is top
    topTenTimeout: 20

    # [integer] The time in minutes for refreshing/recalculating the score for players on their island
    # set to 0 to disabled
    autoRefreshScore: 0

    # [true/false] Whether or not to include island-members on the top-ten scoreboard
    topTenShowMembers: true

    # [true/false] Whether or not to try and fix flat-land issues when players join the server
    # Note: will make the PlayerJoin event take longer.
    fixFlatland: false

    # The format used in /islandtalk chat messages
    chat-format: '&9SKY &r{DISPLAYNAME} &f>&d {MESSAGE}'

    # How many entries to remember in the island-log
    log-size: 10

    # Limits the spawning
    spawn-limits:

      # [true/false] if true, the limits below will limit spawning
      enabled: true

      # how many animals can be spawned within an island
      animals: 48

      # how many monsters can be spawned on an island
      monsters: 50

      # how many villagers can be spawned on an island
      villagers: 16

      # how many snowmen and iron-golems can be spawned on an island
      golems: 5

    # [permission] The name of the permissions to check if extra items are added to the chest, you can change these or add more
    # Only checked if 'addExtraItems' is set to true.
    # [permission:item list] The list of extra items to add to the chest, will only be added if the player has the permission. ITEM_ID:HOW_MANY
    # When granting the permission, prefix it with "usb." so the full permission to add would be usb.smallbonus
    extraPermissions:
      smallbonus: 4:16 320:5
      mediumbonus: 50:16 327:1
      largebonus: 3:5 12:5
      giantbonus: 2:1 110:1
      extremebonus: 352:8 263:4
      donorbonus: 261:1 262:32 272:1
  extras:

    # [true/false] If true, return players that don't have an island (this includes players removed from a party while offline), to the server spawn when they login.
    # NOTE: Requires EssentialsSpawn or another plugin with the "/spawn" command
    sendToSpawn: true

    # [true/false] If true, a player can right-click on a block of obsidian on their island while holding an empty bucket to remove the obsidian and fill the bucket with lava. This is useful for people that accidently
    # turn their lava into obsidian with a bad cobblestone generator design. Will only work on the player's island and if there are no other obsidian blocks nearby (so can't be used on portals).
    obsidianToLava: true

  # Contains flags for enabling PROTECTION of various mechanics.
  protection:

    # Whether or not, items dropped on the ground should be limited to party-members.
    item-drops: true

    # If true, only creepers targeting party-members will explode
    creepers: true

    # If true, Withers will be limited to harming island-members/island blocks.
    withers: true

    # Whether or not the plugin will try to protect the player from accidentally extinguishing lava
    protect-lava: true

    # Whether or not portalling to the nether roof should be blocked.
    nether-roof: true

    # Generally protections against griefers
    # If the flag is true, it generally means the protection is active
    # (meaning the action is blocked)
    visitors:

      # Protect visitors from trampling your crop
      trampling: true

      # Protect against visitors attacked animals
      kill-animals: true

      # Protect against visitors attacking monsters
      kill-monsters: true

      # Protect from shearing
      shearing: true

      # Protect from begin bombarded with eggs that hatch
      hatching: true

      # Protect from villager-trading
      villager-trading: true

      # Whether or not visitors are protected from fall damage
      fall: true

      # Whether or not visitors are protected from fire damage (incl. lava)
      fire-damage: true

      # Whether or not visitors should be allowed to drop items
      item-drops: true

      # Warns online members when a player visits the island.
      warn-on-warp: true

      # Whether or not to actively block banned players from entering an island (by walking/flying).
      block-banned-entry: true

      # Whether or not visitors can use portals (default: false)
      use-portals: false
  party:

    # The number of ms before an invite timeouts (1000 ms per second)
    invite-timeout: 600

    # The format used in /partytalk chat messages
    chat-format: '&9PARTY &r{DISPLAYNAME} &f>&b {MESSAGE}'

    # Extra commands to execute when players join an island
    join-commands:
    - op:playsound block.enderchest.open block @p

    # Extra commands to execute when players leave an island
    leave-commands:
    - op:playsound block.enderchest.close block @p

  # This section provide some performance tweaking configs
  advanced:

    # If true, display-name is looked up (might be performance intensive).
    useDisplayNames: false

    # [number] The threshold for purging islands.
    # any island with a level above this, is spared.
    purgeLevel: 10

    # [seconds] The number of seconds for confirming a command by
    # re-executing it (/is leave, /is restart).
    confirmTimeout: 10
    chunk-generator: com.gmail.labuff.shane.UltimateSkyGrid.UltimateSkyGridGenerator

  # Section about restarting your island (or accepting an invite).
  restart:

    # Clears the player's inventory on island create/restart
    clearInventory: true

    # Clears the player's armor on island create/restart
    clearArmor: true

    # Clears the player's enderchest on island create/restart
    clearEnderChest: true

    # [ms] The number of ms to wait, before porting the player back
    # on /is restart or /is create (default: 1000)
    teleportDelay: 20

    # [true/false] Whether or not the player should be auto teleported to the island when it's ready
    teleportWhenReady: true

    # list of commands to execute after island-creation
    # i.e.
    # - me Jumps with &ajoy
    extra-commands: []

# List of selections for /is create and /is restart
# the nodes under island-schemes must match the schematic-names from the schematics folder.
island-schemes:

  # name of the schematic
  default:

    # permission needed to use island
    permission: usb.island.create

    # small discription of the island
    description: The default uSkyBlock island

    # item to display in the GUI
    displayItem: SAPLING

    # optional, default true (true enabled in GUI, false disabled in GUI)
    enabled: true

    # optional, must be listed in ascending order
    index: 2

    # optional extra's that can be given per island
    extraItems: ''
    maxPartySize: 4
    animals: 48
    monsters: 50
    villagers: 16
    golems: 5
  skySMP:
    permission: usb.schematic.skysmp
    description: The original SkySMP island
    displayItem: GRASS
    extraItems: OBSIDIAN:14 FLINT_AND_STEEL:1

    # Only get 90% of the normal score
    scoreMultiply: 0.9

    # But start with an offset of 40
    scoreOffset: 40
confirmation:

  # [true/false] Whether to require confirmation (i.e. repeating the command twice).
  is leave: true

  # [true/false] Whether to require confirmation (i.e. repeating the command twice).
  is restart: true
asyncworldedit:

  # Supports disabling the detection of AWE
  enabled: true

  # Show progress to the user every 5 seconds
  progressEveryMs: 5000

  # Or 20pct (what-ever comes first)
  progressEveryPct: 20
  watchDog:

    # The maximum time to wait for AWE paste to complete (2m, 3m20s, etc.)
    timeout: 5m

    # The number of ms between each heartbeat
    heartBeatMs: 2000
worldguard:
  entry-message: true
  exit-message: true
nether:
  enabled: true
  schematicName: netherMini
  terraform-enabled: false
  chunk-generator: com.gmail.labuff.shane.UltimateSkyGrid.UltimateSkyGridGenerator
  spawn-chances.enabled: false

  # The distance to search for valid terra-form location.
  terraform-distance: 7
  height: 75
  lava_level: 7
  activate-at:
    level: 100

  # The probability of forming blocks
  terraform:
    NETHERRACK:
    - '{p=0.7}NETHERRACK'
    - '{p=0.15}NETHERRACK'
    - '{p=0.05}QUARTZ_ORE'
    - '{p=0.05}SOUL_SAND'
    QUARTZ_ORE:
    - '{p=0.50}QUARTZ_ORE'
    - '{p=0.10}QUARTZ_ORE'
    SOUL_SAND:
    - '{p=0.70}SOUL_SAND'
    - '{p=0.10}SOUL_SAND'
    GRAVEL:
    - '{p=0.60}GRAVEL'
    - '{p=0.10}GRAVEL'
    - '{p=0.05}SOUL_SAND'
    GLOWSTONE:
    - '{p=0.85}GLOWSTONE'
    - '{p=0.15}GLOWSTONE'

  # Weights that is applied to the above terraform chances depending on the tool used
  terraform-weight:
    WOOD: 1.1
    STONE: 1.0
    IRON: 0.9
    GOLD: 0
    DIAMOND: 0.5

  # The chances of changing a pigzombie when spawned on a netherbrick
  spawn-chances:
    enabled: false
    wither: 0.2
    skeleton: 0.1
    blaze: 0.2

tool-menu:
  enabled: true
  tool: SAPLING
  commands:
    CHEST: island
    BEDROCK: island spawn
    WORKBENCH: challenges

# Placeholders - enable these to get placeholder substitution
# usb_version
# usb_island_level, usb_island_level_int
# usb_island_rank, usb_island_partysize_max, usb_island_partysize
# usb_island_leader, usb_island_bans, usb_island_members, usb_island_trustees
# usb_island_biome, usb_island_schematic
# usb_island_location, usb_island_location_x, usb_island_location_y, usb_island_location_z
# usb_island_golems_max, usb_island_monsters_max, usb_island_animals_max, usb_island_villagers_max,
# usb_island_golems, usb_island_monsters, usb_island_animals, usb_island_villagers
placeholder:

  # Hooks directly into DeluxeChatPlaceholderAPI
  deluxechatplaceholderapi: false

  # Hooks into MVdWPlaceholderAPI
  mvdwplaceholderapi: false

  # uSkyBlock native placeholders for chat messages and format
  chatplaceholder: false

  # uSkyBlock native placeholders for server-commands
  servercommandplaceholder: false

# DO NOT TOUCH THE FIELDS BELOW
version: 55
`

**Comment by dutchy1001** [comment]
hmm I thought you would use pastebin to post this, looks a bit out of shape now

but I'll get around it, just next time plz use pastebin

**Comment by AcesGamingUK** [comment]
sorry i didnt realise, updated link

**Comment by dutchy1001** [comment]
Did you change the setting in the USKYGRID config too??

Setting up a local server with your config, and see what happens.

**Comment by AcesGamingUK** [comment]
yes i changed what was in the guide,

https://pastebin.com/JEkar0a7

**Comment by AcesGamingUK** [comment]
if it helps.


Plugins (17): AsyncWorldEditInjector, AsyncWorldEdit, UltimateSkyGrid, VoidWorld, ViaVersion, Vault, ViaBackwards, ProtocolLib, Multiverse-Core, WorldEdit, Essentials, BossShop, Multiverse-Portals, EssentialsSpawn, WorldGuard, uSkyBlock, Multiverse-NetherPortals

all pluginf listed are latest versions

CraftBukkit version git-Spigot-e0e1771-5e5cf84 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT

**Comment by dutchy1001** [comment]
I've tested the config and had to alter some lines regarding the "island-schemes" setup (i probably need to update the wiki for this too).
I changed the world name to **_gridworld_** so you easy can see if it's generated correct.
Last but not least, the **distance** was set to _400_ and the **protectionRange** to _128_, as players can jump through the world (unless the island area is locked from the usb command) there is no point in a buffer area, keep them the same is my recommendation (config is now set to 400 for both).

The updated config an be copied from [here](http://pastebin.com/pfBFjQXx)

**Comment by AcesGamingUK** [comment]
thanks, will try it now

**Comment by AcesGamingUK** [comment]
still getting the "Exception generating new chunk" error

it creates the world files, however it still doesnt link to multiverse and there is no access to it

https://pastebin.com/KrnMErjA

**Comment by dutchy1001** [comment]
Could you try with this version [here](https://github.com/rlf/uSkyBlock/releases/tag/v2.7.3-alpha7)?

WorldEdit dev build update [here](http://builds.enginehub.org/job/worldedit/9404/download/worldedit-bukkit-6.1.5-SNAPSHOT-dist.jar)
WorldGuard dev build update [here](http://builds.enginehub.org/job/worldguard/9392/download/worldguard-legacy-6.1.3-SNAPSHOT-dist.jar)

**Comment by dutchy1001** [comment]
Also start with the minimal plugins needed
_VoidWorld, ViaVersion, ViaBackwards, BossShop_ are not needed

**Comment by AcesGamingUK** [comment]
here is the full log from fresh files

first start works fine, 
after following the guide the issue arises

https://pastebin.com/GP1S7pYA

**Comment by AcesGamingUK** [comment]
i redid the whole server
added minimal plugins
edited the files 
and same result

https://pastebin.com/UiMkFXMS

**Comment by dutchy1001** [comment]
Hmm weird as I cant find or reproduce this.

I made a copy of a very basic server I tested this with.
Get it [here](https://mega.nz/#!7h10iTob!qq88vTuvH40BL8z8pQqH-jlPbhLNDIehDd7WM3W95Gg) (this link will be removed in the next 12 hours).
I do use paper_spigot instead of spigot but that should not make a difference.
Double click the "**paper launcher**" to start the server (you might need to alter the _server.properties_ for your own pc).
let me know if this works for you.

**Comment by rlf** [comment]
Seems we (by accident?) added a hard dependency on Vault.
Make sure you have the latest Vault in your plugins as well, and a Vault-enabled permission plugin.

**Comment by AcesGamingUK** [comment]
> Seems we (by accident?) added a hard dependency on Vault.
Make sure you have the latest Vault in your plugins as well, and a Vault-enabled permission plugin

latest vault and pex are used, as for using paper_spigot i will give it a try now,

**Comment by dutchy1001** [comment]
plz dont use a bogus site for files like this, go to the [source](https://ci.destroystokyo.com/job/PaperSpigot/) and you see that it's updated to the latest MC versions.

**Comment by AcesGamingUK** [comment]
@dutchy1001 we have always used that site for our servers

**Comment by dutchy1001** [comment]
If you look on that site, you see that the first download doesn't have a version number. That should be an uptodate version (1.10) then.

Besides this, did the you download the file I mentioned earlier?

**Comment by AcesGamingUK** [comment]
i did.

tried with paper and same result
http://hastebin.com/ujabakagem.vbs

**Comment by dutchy1001** [comment]
but you didnt start the server at your local machine?
And if, did it had any errors?

**Comment by AcesGamingUK** [comment]
i dont run it on my local machine

**Comment by dutchy1001** [comment]
Well that is 1 way to see if a server runs properly and a lot faster then keep waiting for a slow host

**Comment by AcesGamingUK** [comment]
the host is fine, its my pc and connection thats slow

**Comment by rlf** [comment]
the UltimateSkyGrid generators are really not (directly) our responsibility - but, I can point you in a direction of what might be wrong.

The UltimateSkyGridGenerator requires the world-height to be 0-255 (in normal) and 0-127 in nether.

Reg. Vault version, this:
```
29.09 21:41:29 [Server] INFO [uSkyBlock] Enabling uSkyBlock v2.7.3-alpha7
29.09 21:41:30 [Server] INFO No plugins/uSkyBlock/config.yml found, it will be created
29.09 21:41:30 [Server] ERROR Error occurred while enabling uSkyBlock v2.7.3-alpha7 (Is it up to date?)
29.09 21:41:30 [Server] INFO java.lang.NoClassDefFoundError: net/milkbowl/vault/permission/Permission
29.09 21:41:30 [Server] INFO at us.talabrek.ultimateskyblock.handler.VaultHandler.setupPermissions(VaultHandler.java:39) ~[?:?]
29.09 21:41:30 [Server] INFO at us.talabrek.ultimateskyblock.uSkyBlock.reloadConfigs(uSkyBlock.java:987) ~[?:?]
29.09 21:41:30 [Server] INFO at us.talabrek.ultimateskyblock.uSkyBlock.onEnable(uSkyBlock.java:212) ~[?:?]
```
Indicates the Vault you have installed, is not compatible with the one we require.

And this:
```
30.09 17:14:24 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 12
30.09 17:14:24 [Server] INFO at com.gmail.labuff.shane.UltimateSkyGrid.UltimateSkyGridGenerator.setBlock(UltimateSkyGridGenerator.java:26) ~[?:?]
30.09 17:14:24 [Server] INFO at com.gmail.labuff.shane.UltimateSkyGrid.UltimateSkyGridGenerator.generateBlockSections(UltimateSkyGridGenerator.java:74) ~[?:?]
30.09 17:14:24 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:105) ~[patched_1.10.2.jar:git-Paper-881]
30.09 17:14:24 [Server] INFO at co.aikar.timings.TimedChunkGenerator.getOrCreateChunk(TimedChunkGenerator.java:93) ~[patched_1.10.2.jar:git-Paper-881]
30.09 17:14:24 [Server] INFO at net.minecraft.server.v1_10_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:181) ~[patched_1.10.2.jar:git-Paper-881]
30.09 17:14:24 [Server] INFO ... 16 more
```
indicates that the height of the world is higher than what the generator supports
(see https://github.com/rlf/UltimateSkyGrid/blob/master/src/main/java/com/gmail/labuff/shane/UltimateSkyGrid/UltimateSkyGridGenerator.java#L26)

**Comment by AcesGamingUK** [comment]
loaded the file to server, (the ,jar was corrupt so had to download a new one)

seems to load without errors.
but i havn't ran through the setup  [setup]https://github.com/rlf/uSkyBlock/wiki/SkyGrid

@rlf what vault would i need as i have latest version

**Comment by dutchy1001** [comment]
V1.5.6 is the latest Vault

**Comment by AcesGamingUK** [comment]
@rlf > Indicates the Vault you have installed, is not compatible with the one we require.
`
30.09 19:59:24 [Server] INFO Vault version 1.5.6-b49
30.09 19:59:24 [Server] INFO Vault is a Permissions & Economy API to allow plugins to more easily hook into these systems without needing to hook each individual system themselves.
30.09 19:59:24 [Server] INFO Website: http://dev.bukkit.org/server-mods/vault/
30.09 19:59:24 [Server] INFO Authors: cereal, Sleaker and mung3r`

i have latest so what is reccomended?

also could you comfirm the compatabality with this version of spigot
`30.09 20:01:01 [Server] INFO This server is running CraftBukkit version git-Spigot-e0e1771-5e5cf84 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)`

[Spigot link](https://www.dropbox.com/s/w734cqxfyw6kb37/spigot1.10.jar?dl=0)

**Comment by dutchy1001** [comment]
If you got the latest Vault then that should be fine. As you said before you had a corrupt jar file, maybe replace the Vault incase it's corrupt too

**Comment by dutchy1001** [comment]
If you downloaded the file I mentioned before then you should have all the right plugins/depended plugins that work as they should.

**Comment by AcesGamingUK** [comment]
@dutchy1001 the corrupt jar i was refering to was the paperspigot jar that was in the server zip you sent me.

and yas it works on paper-spigot but not spigot for some reason

**Comment by dutchy1001** [comment]
The paper-spigot file is working fine on my pc, no corruption there. Must be something going wrong in the transfer I suppose.

I compiled a fresh spigot 1.10.2 and this file also does **not** give me an error (see log [here](http://pastebin.com/BjMgYrkr))

**Comment by dutchy1001** [comment]
due to inactivity i will close this issue
