### ISSUE TITLE
OPs don't lose hunger on their island, permission doesn't work.

### ISSUE THREAD

**Issue by MrProtagonist** [rlf/uSkyBlock#895]
_Please paste the output from `/usb version` below_

Version: 2.7.2
Description: Ultimate SkyBlock v2.7.2-45f756-430
Language: en (en)
State: d=128, r=64, i=45, p=41, n=true, awe=true
Server: CraftBukkit git-Spigot-078e2f8-7f9fbe5 (MC: 1.10.2)
State: online=true, bungee=false
------------------------------
Vault 1.5.3-b37 (ENABLED)
WorldEdit 6.1.3;7a097ca (ENABLED)
WorldGuard 6.0.0-beta-05.1569- (ENABLED)
AsyncWorldEdit 3.4.0 (ENABLED)
Multiverse-Core 2.5-b717 (ENABLED)
Multiverse-Portals 2.4-b548 (WRONG-VERSION)
Multiverse-NetherPortals 2.5-b675 (ENABLED)
```

_What steps will reproduce the problem?_
1. Install uSkyblock & configure
2. Create an island as an OP.
3. You will not lose hunger, but only on your island. Giving the -usb.extra.* (or .hunger,2,3,4, any combination etc.) does not prevent this. This permission is not found in the Github wiki page, but the old one.

Non-OPs lose hunger both on their own and other people's islands. OPs only lose health on other people's islands.

Any assistance appreciated.

**Comment by dutchy1001** [comment]
Not sure about the OP's not loosing hunger but looking at you output from /usb version you have a wrong Multiverse-Portal plugin. Vault can(should) be updated to 1.5.6 and WorldGuard is way out of date too.
See this page [here](https://dev.bukkit.org/bukkit-plugins/uskyblock/pages/installation/), with all the latests links to the depended plugins (including dev builds)

**Comment by rlf** [comment]
Most likely OP has perks with `hungerReduction`, you can check them out by doing `/usb perk player <playername>` and `/usb perk list`).

**Comment by MrProtagonist** [comment]
Thanks for the follow up.

Multiverse and vault are both working fine (im actually using a custom currency in place of regular money, thanks for custom commands on challenge completion =] ). The whole plugin works great actually. 

When I list the permissions with your command (/usb perk player), it shows that hungerReduction is 1.0 on OPs.

When I try to negate all of the "extra" permissions found on the permissions page (-usb.extra.*), or the individual hunger perks found in older documentation, nothing works. They still don't lose hunger, and it is still 1.0. I did look at [the line of code this pertains to](https://github.com/rlf/uSkyBlock/blob/master/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/player/PerkLogic.java#L185) and it uses the permissions listed on the old bukkit page (not in github wiki btw). However, negating these specific permissions or any encompassing them doesn't seem to affect what I see in /usb perk player.

I've also tried removing admin permissions, donor permissions, everything I can think of. [At this line in the code](https://github.com/rlf/uSkyBlock/blob/b5b4f9b00a0c6a905431af9208076d3f4eb1144b/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/player/PerkLogic.java#L62), it appears that it checks the config for a value. Is there something I can add to the config file that may fix this issue?

Thanks for all the help, and great plugin!

**Comment by dutchy1001** [comment]
I have found some issue's according to the extra perks.permissions and will look further into this when my time permits it.

As for your Multiverse working properly
```Multiverse-Portals 2.4-b548 (WRONG-VERSION)```
the tag _(WRONG-VERSION)_ should say enough
Don't mix versions 2.4 and 2.5

**Comment by MrProtagonist** [comment]
Great, thanks for looking into it. Please notify me in this thread when the patched version is available.

**Comment by dutchy1001** [comment]
The plugin.yml updated fixed for me the hunger issue (and a few more things I found). As OP I lost hunger now on a players island and on my own.

I'm not sure when a new (alpha) release will be released.

**Comment by MrProtagonist** [comment]
Fantastic news, i'll keep an eye out for it. Thanks for the hard work on this.
