### ISSUE TITLE
Feature Request: Limit entity per island

### ISSUE THREAD

**Issue by UnioDex** [rlf/uSkyBlock#901]
Spigot has a chronic hopper idle lag issue. Also entity's are making lag too. So i want to limit hoppers, chests, banners, item frames or any other entity per island. Limiting entities, villagers will help to reduce lag.

**Comment by dutchy1001** [comment]
Maybe try using Paper-Spigot and see if the lag is less (i use it too).
See [here](https://paper.readthedocs.io/en/paper-1.10/) the webiste

**Comment by UnioDex** [comment]
I already using PaperSpigot. Limiting entities is a good solution for fresh start servers.

**Comment by rlf** [comment]
We already have a limit on spawning entities - but not for hoppers, chests, banners or item-frames.
There already exists a lot of other plugins that enable you to limit that sort of stuff.
