### ISSUE TITLE
Can't remove skySMP/default from the island GUI

### ISSUE THREAD

**Issue by DevinNL** [rlf/uSkyBlock#902]
Name: uSkyBlock
Version: 2.7.2
Description: Ultimate SkyBlock v2.7.2-45f756-430
Language: en (en)
State: d=251, r=64, i=11, p=10, n=true, awe=false
Server: CraftBukkit git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
State: online=false, bungee=true
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1;no_git_id (ENABLED)
WorldGuard 6.1 (ENABLED)
Multiverse-Core 2.5-b699 (ENABLED)
Multiverse-Portals 2.5-b733 (ENABLED)
Multiverse-NetherPortals 2.5-b702 (ENABLED)
------------------------------

As the title describes I can't remove/don't know how to remove the skySMP and default from the island creation GUI and the island reset GUI... I tried to remove skySMP from the config and I tried to delete the schematic, but I just can't get it to work...

**Comment by dutchy1001** [comment]
In the default island listed above the SkySMP settings in the config you will see the node
```
Enable: true
```
add this to the SkySMP but set it then to false and the SkySMP will not show in your GUI anymore.

All tags used in the default island can be used on any added custom (or existing) island. If there not present it will take the default setting.

**Comment by dutchy1001** [comment]
no further input to say it's fixed or not.
Closing for now

**Comment by DevinNL** [comment]
Still doesn't work.. This is my config: http://pastebin.com/XjeFH8sV

**Comment by dutchy1001** [comment]
Delete (read backup) your config and let the plugin regenerate a new file. After that is done add the "enable: false" to the SkySMP after the "displayItem"node and change the other settings you had in your previous config.
(probable cause is you used an older version of the config file)

Your distance is set to "251" this will cause our Nether feature to be disabled as it cant be divided my 32. As your nether setting in the config is still on "true" I presume you would like this option to be enabled. If you dont want to make use of our Nether feature then the distance setting is fine but set the Nether option in the config to false. If you want a "normal" nether this setting has to be false.

You have set your protectionRange to 128, meaning your players can only build in a radius of 64 blocks to each side. This means with the distance set to 251 that there is a gap around the islands of 123 blocks. So between each island there is an unused gap of 123+123=246 blocks (IMHO a bit of wasted space).
