### ISSUE TITLE
Problem with uSkyBlock

### ISSUE THREAD

**Issue by N3zp0w3r** [rlf/uSkyBlock#906]
[0;37;22mName: [0;36;1muSkyBlock[m
 [0;37;22mVersion: [0;36;1m2.7.2[m
 [0;37;22mDescription: [0;36;1mUltimate SkyBlock v2.7.2-45f756-430[m
 [0;37;22mLanguage: [0;36;1men (en)[m
[0;34;1m  State: d=128, r=64, i=3, p=4, n=true, awe=false[m
[0;37;22mServer: [0;33;1mCraftBukkit git-Spigot-eb87f2b-ee6d0fa (MC: 1.8)[m
[0;34;1m  State: online=false, bungee=false[m
1. When players join in my server, they're supposed to write /is create.
2. After that, a gui appears and there are 2 islands. By the default i've changed the schematic, but the issue is there that i can't delete SkySMP from the Gui or whatever.
3. For example, if i try to delete it from the schematics folder and i reload, it appears again. Can't figure it out, where's the issue am i doing something wrong?
* server-log: http://pastebin.com/WyWMbtXT

**Comment by dutchy1001** [comment]
add the node
```
enable: false
```
to the SkySMP settings (as is shown in the "default" (but there it's set to true)

**Comment by N3zp0w3r** [comment]
Thanks!

**Comment by dutchy1001** [comment]
I've edited the main config so both island in the "island-schemes" are now having all default nodes.

This can be closed I presume, if not post it here again.
