### ISSUE TITLE
error during rank generation player db issue

### ISSUE THREAD

**Issue by i9hdkill** [rlf/uSkyBlock#909]
Getting these errors quite often since 2.7:
http://pastebin.com/Q6UtMgkB
I think they are caused by the uuid2name file in any way.

Usky Debug:
[06:01:22] [Server thread/INFO]: [uSkyBlock] Hooked into Vault Economy
[06:01:22] [Server thread/INFO]: [uSkyBlock] Hooked into Vault Permissions
[06:01:22] [Server thread/INFO]: [uSkyBlock] §7Name: §buSkyBlock
§7Version: §b2.7.0-SNAPSHOT
§7Description: §bUltimate SkyBlock v2.7.3-alpha7-12-gdce376d-dce376-dev
§7Language: §bde (de)
§9  State: d=110, r=50, i=19.934, p=36.074, n=false, awe=false
§7Server: §eCraftBukkit git-Spigot-90f61bc-83a9dbd (MC: 1.10.2)
§9  State: online=true, bungee=true
§7------------------------------
§7§dVault §f1.5.6-b49 §7(N/A§7)
§7§dWorldEdit §f6.1.3-SNAPSHOT;3558-5a42a8d §7(N/A§7)
§7§dWorldGuard §f6.1.3-SNAPSHOT;1670-4ab38e5 §7(N/A§7)
§7§dMultiverse-Core §f2.5-b719 §7(N/A§7)
§7------------------------------

**Comment by i9hdkill** [comment]
Some players are not even able to open the /is menu due to this
http://pastebin.com/N0tbCLT4

**Comment by i9hdkill** [comment]
This issue occurs if the uuid.yml is missing (deleted/renamed by the plugin)

**Comment by rlf** [comment]
We are aware of this issue, and it seems to be resolved by deleting (backup?) the `name2uuid.yml` file

**Comment by i9hdkill** [comment]
Tried that, (stopped server, deleted the file, started the server)
At least three players still have this problem.
If one of the players executing /is:
http://pastebin.com/7ks24dck

**Comment by rlf** [comment]
`§bUltimate SkyBlock v2.7.3-alpha7-12-gdce376d-dce376-dev` indicates this is a custom build - the error you are referring to, shouldv'e been corrected on the official release.

Could you please retest the issue on an official release?

**Comment by i9hdkill** [comment]
It's built from the latest source. No build-errors

**Comment by rlf** [comment]
Could you please retest the issue on an official release?

**Comment by i9hdkill** [comment]
Yes, if you are so kind and release a new alpha with the latest changes.
Don't really want to switch back to an older release.

**Comment by i9hdkill** [comment]
Does happen with an official release build aswell:
http://pastebin.com/5u3zJqtq
