### ISSUE TITLE
WorldGuard usage with WGCustomFlags

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#91]
I often use the following:
a) Limit player and mob trampling of crops - it's an easy way to grief an island with active warp.
b) Use WGCustomFlags and WGDropFlags with `allow-pickup: deny`, so players from other island don't run around and pickup things on the ground (trampled crops, dropped apples, saplings etc.).
c) AnimalProtect - To ensure animals aren't attacked by other players.

If we could somehow integrate all this, it would make for a better experience.
If not, then we'll just keep the nice guides by Dutchy.

**Comment by dutchy1001** [comment]
fixed as far I know
