### ISSUE TITLE
Errors when interacting after 10 minutes of being online or added to the island

### ISSUE THREAD

**Issue by i9hdkill** [rlf/uSkyBlock#910]
How to reproduce:
Add a player to your island. Everything is fine, he can interact, pick up items etc.
After roughly 10 minutes, he is no longer able to pick up items etc.
Removing him from the island and readding him fixes it for 10 minutes.

Debug paste:
[06:01:22] [Server thread/INFO]: [uSkyBlock] Hooked into Vault Economy
[06:01:22] [Server thread/INFO]: [uSkyBlock] Hooked into Vault Permissions
[06:01:22] [Server thread/INFO]: [uSkyBlock] §7Name: §buSkyBlock
§7Version: §b2.7.0-SNAPSHOT
§7Description: §bUltimate SkyBlock v2.7.3-alpha7-12-gdce376d-dce376-dev
§7Language: §bde (de)
§9 State: d=110, r=50, i=19.934, p=36.074, n=false, awe=false
§7Server: §eCraftBukkit git-Spigot-90f61bc-83a9dbd (MC: 1.10.2)
§9 State: online=true, bungee=true
§7------------------------------
§7§dVault §f1.5.6-b49 §7(N/A§7)
§7§dWorldEdit §f6.1.3-SNAPSHOT;3558-5a42a8d §7(N/A§7)
§7§dWorldGuard §f6.1.3-SNAPSHOT;1670-4ab38e5 §7(N/A§7)
§7§dMultiverse-Core §f2.5-b719 §7(N/A§7)
§7------------------------------

These errors might be related
Like this:
http://pastebin.com/KU4FepRm
or this:
http://pastebin.com/T0YJL2TP

**Comment by rlf** [comment]
Seems related to #898
