### ISSUE TITLE
Placeholder support?

### ISSUE THREAD

**Issue by OMGYES** [rlf/uSkyBlock#912]
**Output:** http://prntscr.com/cvulm5

I was wondering if you guys could allow placeholders? :o 

We use the main gui a lot and we both know you can add more icons to it, such as click me for spawn or warp to shop. I wanted to display your money, playtime and other placeholders but I found out it doesn't support placeholders lol

Not sure if it is possible but it is cool and worth a try, right?
I do understand if you wont do this because it might be a lot of work!

Greets,
The annoying guy

**Comment by dutchy1001** [comment]
This is possible through the use of [ChestCommandGUI](https://dev.bukkit.org/bukkit-plugins/chest-commands/) plugin. 
As you already said you know how to add extra items to the main GUI, you can link those to ChestCommandGUI which then can display balance and a lot of other things.

**Comment by OMGYES** [comment]
Are you sure? I use the uskyblock config to add lores and icons. I typed a placeholder in that config file and it didn't display anything...

**Comment by OMGYES** [comment]
holysmokes you're right. sorry, want me to remove this if it is possible

**Comment by OMGYES** [comment]
Wait, placeholders don't work

**Comment by OMGYES** [comment]
Chestcommands doesn't support placeholders...... But it's the only GUI that works with uSB

**Comment by Lmmb74** [comment]
Why don't you use DeluxeMenus? It's is able to use conditions, placeholders, and many utils for GUIs

**Comment by OMGYES** [comment]
It doesn't support uSkyblock. When you run a command from uskyblock it opens the uskyblock GUI. Chestcommands doesn't

**Comment by Lmmb74** [comment]
But can't you make DeluxeMenus execute a uSB command and viceversa?

**Comment by OMGYES** [comment]
When I click on the icon from DeluxeMenus the command is: /is h [which teleports you to your island but also appears the usb GUI]

When I click on the icon from ChestCommands: /is h [teleports me to my island without showing the usb GUI]

**Comment by OMGYES** [comment]
Fixed it myself. Just downloaded everything. I use AnimatedMenu's now.

**Comment by OMGYES** [comment]
nope didn't work either, thought it did but nopers

**Comment by dutchy1001** [comment]
I thinkI  have understood the issue wrong, but I dont think placeholders can be used in the GUI's.

**Comment by OMGYES** [comment]
It might be a glitch from uSkyblock? When I use a sign or GUI plugin to run the command /is home it appears the island GUI. Chestcommands does not but it has no placeholders ;(
