### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by PretoAlbino** [rlf/uSkyBlock#920]
http://prntscr.com/d0lubj - Version

Everytime this appears in my console (modded server).

Server-log: http://pastebin.com/W05wBpCr

**Comment by dutchy1001** [comment]
I'm sorry but Cauldron is not supported (atleast not by me)
If any other who reads this post feel free to answer.

**Comment by PretoAlbino** [comment]
There's a big problem, I see various servers using this plugin in a SkyFactory modpack, is a great idea to make a support for Cauldron(Thermos)

**Comment by rlf** [comment]
Duplicate, fixed in issue #840 - but no 1.7.9 release has been made in ages

**Comment by dutchy1001** [comment]
due to no more input I will close this
