### ISSUE TITLE
Commands doesn't works

### ISSUE THREAD

**Issue by Leomixer17** [rlf/uSkyBlock#921]
Skyblock commands do nothing.
Console log: http://pastebin.com/b8DzT5n5
Server version: paperclip 1.10.2
uSkyBlock version: 1.7.2

**Comment by dutchy1001** [comment]
Follow the form when creating a issue, it's there for a reason.

**Comment by Leomixer17** [comment]
Full log: http://pastebin.com/NitYdVQB

**Comment by Leomixer17** [comment]
Solved, was Multiverse-Core that wasn't updated

**Comment by dutchy1001** [comment]
Your using an old Multiverse-Core. 
Use this site [here](Multiverse-Core 2.4-b527 (N/A)) (their official Jenkings page) for updated versions. Also good idea to use MV-Portals and MV-NetherPortals addons.

**Comment by dutchy1001** [comment]
Clicked on same time I guess, Glad you found it
