### ISSUE TITLE
Error when trying to enter the nether

### ISSUE THREAD

**Issue by DevinNL** [rlf/uSkyBlock#923]
Name: uSkyBlock
Version: 2.7.2
Description: Ultimate SkyBlock v2.7.2-45f756-430
Language: en (en)
State: d=128, r=64, i=2, p=2, n=true, awe=false
Server: CraftBukkit git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)
State: online=false, bungee=false
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1;no_git_id (ENABLED)
WorldGuard 6.1 (ENABLED)
Multiverse-Core 2.5-b717 (ENABLED)
------------------------------

When I try to go to the nether it prints the messages shown in the pastebin.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: http://pastebin.com/vBuGXHwm

**Comment by dutchy1001** [comment]
Your missing Multiverse-Portals and Multiverse-NetherPortals

**Comment by DevinNL** [comment]
That fixed the problem that I was having, but it created a new one.
Everytime I try to go to the nether it gives me this message: http://prntscr.com/d299by

**Comment by dutchy1001** [comment]
you might need to try and restart your island

**Comment by DevinNL** [comment]
Still not working...

**Comment by dutchy1001** [comment]
You might need to restart the worlds (reset) and start with 2 new worlds. You can delete the "player" and "island" folders and the LastIslandConfig.yml from the main uSkyblock folder (also dont forget to reset the worldguard files) and restart the server. this then should reset it all (incase you have already a spawm island in the skyworld made).

**Comment by DevinNL** [comment]
This still doesn't fix it....
And I came across another problem, when my players die they spawn on a random bedrockblock on in the middle of nowhere... (X=0,Z=0)

**Comment by DevinNL** [comment]
I fixed the problem with the bedrockblock, but I still can't seem to fix the nether.. Here is a pastebin of my config, in case you need it: http://pastebin.com/xq8jVrT5

**Comment by dutchy1001** [comment]
the bedrock block is correct, if spawn is not set to the "sever" spawn you will go there. The bedrock block prevents you from keep falling in the void. Also you can use it to start making a spawn island there if you dont use a schematic to paste in.

have you tried totally deleteing the worlds and the uskyblock folder form the plugins? When deleting these files also delete them from WG folder and the Multiverse world.yml (as always, make a backup before deleting from the server).

I also notest that your We and WG could be updated to newer versions (not sure this could help but you never know)

**Comment by DevinNL** [comment]
I deleted the WG skyblockworld and skyblockworld_nether folder.
I deleted the wolrd.yml in multiverse-core
I deleted the worlds skyblockworld and skyblockworld_nether from the server
I deleted the "player" and "island" folders and the LastIslandConfig.yml from the main uSkyblock folder.

Still not working, I sill have the error that its trying to teleport ontop of the nether...

**Comment by dutchy1001** [comment]
Can you repost the output of /usb version or startup log and your server address so I can join and see if there is anything else that causes this.

**Comment by DevinNL** [comment]
Name: uSkyBlock
Version: 2.7.2
Description: Ultimate SkyBlock v2.7.2-45f756-430
Language: en (en)
State: d=128, r=64, i=1, p=1, n=true, awe=false
Server: CraftBukkit git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)
State: online=false, bungee=false
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1;no_git_id (ENABLED)
WorldGuard 6.1 (ENABLED)
Multiverse-Core 2.5-b717 (ENABLED)
Multiverse-Portals 2.4-b548 (WRONG-VERSION)
Multiverse-NetherPortals 2.4-b530 (WRONG-VERSION)
------------------------------

pastebin startup log: http://pastebin.com/43Cjmuvy

**Comment by dutchy1001** [comment]
You might see the issue were it goes wrong now as it's in very big writing

Get all the latest versions from [here](https://ci.onarandombox.com/view/Multiverse/) for multiverse

**Comment by DevinNL** [comment]
Thank you for sending me the multiverse jenkins page, 
The problem is fixed!
The only thing left for me to ask now is: Why does the nether portal not spawn in the place where the nether portal frame is placed?

**Comment by dutchy1001** [comment]
If you create a nether portal it should teleport you to your nether island which has a portal build already. 

How is the nether created? by you or by the plugin?

**Comment by DevinNL** [comment]
By the plugin

**Comment by dutchy1001** [comment]
When going through a portal does it bring you to your nether island?

**Comment by DevinNL** [comment]
Yes, but it doesn't spawn the portal in the pre-made frame made by the plugin

**Comment by dutchy1001** [comment]
is it allowed in the nether to create portals? This can be set in the Multiverse-core settings (world.yml)

**Comment by DevinNL** [comment]
You mean this?
`portalForm: ALL`

**Comment by dutchy1001** [comment]
That is set OK.
Something else is then blocking the creation of a portal. But you have no problem to create one on your island??

**Comment by DevinNL** [comment]
No

**Comment by dutchy1001** [comment]
Can you send a full startup log through pastebin plz?

**Comment by DevinNL** [comment]
http://pastebin.com/1g0U0YuJ

**Comment by dutchy1001** [comment]
Hmm there is lots wrong in your setup and many "Ambiguous" plugins which means 2 or more of the same plugin. When updating a plugin you need to remove the older version. 

Due to that there are so many errors it's not surprisingly that there are things not working.
Either disable plugins that causes errors (move them to backup folder for the time being) on your server or update/fix them, this all helps towards running the server smooth and less prone to lag or problems.

Start with a basic setup and see if that fixes the portal issue, after that you can always add the other plugins back to the server. When you add then a plugin and the portal stops working you know what causes the probllem.
