### ISSUE TITLE
Challenge reset problem

### ISSUE THREAD

**Issue by UnioDex** [rlf/uSkyBlock#928]
When player leave their islands their challenges are not resetting. Challenges only reset on restart (or create). But if they are leave their island and join another existing island their challenges stay same.

**Comment by dutchy1001** [comment]
There is a config option in the challenges config
```
# [true/false] If false, challenges are not reset on island creation (or restart)
resetChallengesOnCreate: true
```
I just tested this and when set to true it will reset the challenges.

Also there is a command _/usb challenges [player] resetall_ which will reset all players challenges.

**Comment by UnioDex** [comment]
Yes i set true too. Then can you add an option that reset challenges on leave or kick too?

**Comment by rlf** [comment]
Challenges are reset when you create (or join) a new island, not when you leave it.
