### ISSUE TITLE
Error and getting spammed in console

### ISSUE THREAD

**Issue by Koomplo** [rlf/uSkyBlock#932]
http://pastebin.com/ddYPJASR

^ I'm getting this error in console, this are spamming every 0.1s 
Everyday I need to delete 15-30GB of Logs because of that...
How I can resolve ?

USB Version: http://image.prntscr.com/image/0eb42072479944e6b922dc291fbebfa4.png

**Comment by dutchy1001** [comment]
I'm sorry but we don't support Cauldron. 
If you browse through our closed issue's you might find an answer.

**Comment by BlackBeltPanda** [comment]
Quoting rlf > Duplicate, fixed in issue #840 - but no 1.7.9 release has been made in ages
