### ISSUE TITLE
USB won't load in 1.11 server

### ISSUE THREAD

**Issue by wesley27** [rlf/uSkyBlock#935]
_Please paste the output from `/usb version` below_
2.7.2

_What steps will reproduce the problem?_
loading USB in MC 1.11

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
http://pastebin.com/Nx2MBuf1

Hey guys, the plugin won't load in my 1.11 server

**Comment by rlf** [comment]
I think @dutchy1001 has a work-around - it's due to the `VillagerGolem` in your `challenges.yml` file - it has been renamed in 1.11.

Not sure what the correct naming is, but ducthy1001 will know.

**Comment by dutchy1001** [comment]
I have updated the challenges file from VillagerGolem:1 to IRON_GOLEM:1. you can do this manual or wait till we release a new version.

**Comment by wesley27** [comment]
Thanks :)
