### ISSUE TITLE
Teleports are cancelled only by the mouse movement

### ISSUE THREAD

**Issue by Leomixer17** [rlf/uSkyBlock#937]
_Please paste the output from `/usb version` below_
26.11 20:54:07 [Server] INFO Name: uSkyBlock
26.11 20:54:07 [Server] INFO Version: 2.7.2
26.11 20:54:07 [Server] INFO Description: Ultimate SkyBlock v2.7.2-45f756-430
26.11 20:54:07 [Server] INFO Language: it (it)
26.11 20:54:07 [Server] INFO State: d=256, r=112, i=1, p=1, n=true, awe=true
26.11 20:54:07 [Server] INFO Server: Paper git-Paper-899 (MC: 1.10.2)
26.11 20:54:07 [Server] INFO State: online=false, bungee=true
26.11 20:54:07 [Server] INFO ------------------------------
26.11 20:54:07 [Server] INFO Vault 1.5.6-b49 (ENABLED)
26.11 20:54:07 [Server] INFO WorldEdit 6.1.3;7a097ca (ENABLED)
26.11 20:54:07 [Server] INFO WorldGuard 6.1.2;e38d98d (ENABLED)
26.11 20:54:07 [Server] INFO FastAsyncWorldEdit 16.10.17-04164b9-345-9.8.0 (ENABLED)
26.11 20:54:07 [Server] INFO Multiverse-Core 2.5.0-SNAPSHOT-b725 (ENABLED)
26.11 20:54:07 [Server] INFO Multiverse-NetherPortals 2.5.0-SNAPSHOT-b712 (ENABLED)
26.11 20:54:07 [Server] INFO ------------------------------

_What steps will reproduce the problem?_
1. Do /is spawn or another uSkyBlock's teleport command without delay bypass permission
2. Move the mouse before the teleport
3. The teleport is cancelled

**Comment by dutchy1001** [comment]
I thought this was sorted but cant tell if it was in v2.7.2. I can confirm that in [v2.7.3 alpha13](https://github.com/rlf/uSkyBlock/releases/tag/v2.7.3-alpha13) this is fixed.

I can also confirm that in that version your translation has been added 😃

**Comment by Leomixer17** [comment]
Thank you
