### ISSUE TITLE
party permission 

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#940]
_Please paste the output from `/usb version` below_

![image](https://cloud.githubusercontent.com/assets/5569980/20817670/fbe217da-b820-11e6-9b79-042e264ef6ce.png)

_What steps will reproduce the problem?_
1. Invite player to island
2. Try to change member permissions after invite accepted.
3.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* No error in console.

[Gif](https://embed.gyazo.com/d586affe88098cd98de482accd96b660.gif)
Adding .gif files wont work here but shows player added to the member GUI with name but not the right head. When clicking the members head it defaults back to owner permission GUI.

Post made on behave of Disorbs (aka Cruz in the gif file)

**Comment by Disorbs** [comment]
any news on this i really need a fix for this as well as random players getting added to islands that they shouldnt be a part of.

**Comment by BlackBeltPanda** [comment]
This one's been fixed for quite some time, now. =)
