### ISSUE TITLE
PlayerInteractEvent Console spam every second

### ISSUE THREAD

**Issue by Disorbs** [rlf/uSkyBlock#941]
_Please paste the output from `/usb version` below_
https://i.gyazo.com/d704bc5ad0c42fe8821791ba57850f57.png

_What steps will reproduce the problem?_
1. randomly happens constantly and sometimes it stops then it starts again spamming every second
2. not sure if it happens when a certain player goes to their island or when trusting someone.
3. --- I noticed it happens when you Left click the air at some islands? ----

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: http://pastebin.com/wEfvbWn5

**Comment by Disorbs** [comment]
So it happens on Islands that have wrong uuids that have been trusted like below
Part of the file i removed that made it work again without the constant console spam error
but to do this to every island will take quite a long time.
`trust:
  list:
  - 8aa7b6e4-acd6-3cf0-897b-6d1ce58027c2
`

**Comment by Muspah** [comment]
Going to close this issue for now, please reopen if the problem still persists in newer versions :)
