### ISSUE TITLE
1.11 Wither Entity deprecation 

### ISSUE THREAD

**Issue by asleeponduty** [rlf/uSkyBlock#943]
NetherTerraformEvents.java line 265 is deprecated and no longer works on v1.11.

This proposed fix is not backwards compatible
FROM
                    // Spawn Wither.
                    Skeleton mob = (Skeleton) e.getLocation().getWorld().spawnEntity(e.getLocation(), EntityType.SKELETON);
                    mob.setSkeletonType(Skeleton.SkeletonType.WITHER);
                    mob.getEquipment().setItemInHand(new ItemStack(Material.STONE_SWORD, 1));
TO
WitherSkeleton mob = (WitherSkeleton) e.getLocation().getWorld().spawnEntity(e.getLocation(), EntityType.WITHER_SKELETON);

**Comment by Lmmb74** [comment]
Since you know that it is not backwards compatible, why don't you create a second class that will only be called in versions 1.11+? This would be easier than using reflection :P

**Comment by asleeponduty** [comment]
I will when I have time - just wanted to raise awareness of the issue before I started :)

**Comment by rlf** [comment]
Do you have a pending pull-request for this? Or should I look into it?

**Comment by Narimm** [comment]
Its a pretty basic fix (I could have done something more pretty) but this should work for now...it calls the version and looks for the major version

**Comment by asleeponduty** [comment]
Thanks guys! I haven't had access to anything but my work laptop for some time. Lacking a dev environment hurts. 

Expect to see more from me in the future.

**Comment by dutchy1001** [comment]
Wither skeletons are spawning again with the latest (alpha14) dev release. 👍

**Comment by rlf** [comment]
Unfortunately, the MC 1.8 build failed - so we need to tweak the "fix" to support 1.8 (and add 1.11 to the build profiles).

**Comment by dutchy1001** [comment]
I didnt test on 1.8.8 but so far on 1.11.2 it's going fine

**Comment by rlf** [comment]
Fixed: https://github.com/rlf/uSkyBlock/releases/tag/v2.7.3-alpha15
Has jars in all the major versions - meaning at least it compiles in those :)
Have you tested it on both 1.11 and 1.10?

**Comment by dutchy1001** [comment]
tested wither skeletons in a 1.10.2 server and they appear as it should.

Both 1.10.2 and 1.11.2 are now working with alpha 15

**Comment by Narimm** [comment]
I am not asleeponDuty...that would be quite dangerous :)
