### ISSUE TITLE
Uskyblock and multiverse-core compatibility issues?

### ISSUE THREAD

**Issue by meaortan** [rlf/uSkyBlock#947]
_Please paste the output from `/usb version` below_
```
2.7.2
```

_What steps will reproduce the problem?_
1. Starting the server with usb, pex, worldedit, vault, mv-core, worldguard

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin 

At first i thought maybe it was an issue on my server but a server running only the specified plugins produced the same result, which is when i install uskyblock with multiverse installed it flat out refuses to work but mv does and when mv is removed usb works fine. Idk which dev to go to so im starting here, im totally at a loss. Server is running bukkit 1.11 also but tested on 1.8 and got the same result.

**Comment by dutchy1001** [comment]
not a fulll output of the commnad **/usb version**

**Comment by meaortan** [comment]
edited with full /usb version

**Comment by dutchy1001** [comment]
Multiverse-Core and Multiverse-Portal are depended plugins so they HAVE to be added before it works properly.

**Comment by meaortan** [comment]
I cant give you a new /usb version output because as i said before the plugin doesnt work when multiverse is loaded too. Usb is recognized and its green in /pl but any /usb or /is command wont give any output. Thats why im here.

**Comment by dutchy1001** [comment]
Ok then as alternative load it with MV and post the log (through pastebin) so we can see where it goes wrong.

**Comment by meaortan** [comment]
Im new to multiverse what log do you need me to get?

**Comment by dutchy1001** [comment]
just a full server log from starting the server till it's finished loading.

(I'm out a few hours from now)

**Comment by meaortan** [comment]
http://pastebin.com/uUX4p1gq theres a full log from start

**Comment by dutchy1001** [comment]
As expected, your multiverse is out of date. 
Use the links on our [bukkit](https://dev.bukkit.org/projects/uskyblock/pages/installation) pages for normal releases or dev builds (I use dev builds myself with no problems)

**Comment by meaortan** [comment]
Ah thank you! That was it. I wasnt sure if dev builds were stable to use.

**Comment by dutchy1001** [comment]
[begin rant]
Even besides that, you still had a major outdated MV plugin. It has been clearly mentioned to use versions above 2.5 and still all MV issue's are from server owners/adminstrators that have not been updating their servers properly (same count for WE and WG).
{end rant]
