### ISSUE TITLE
Islands aren't centered?

### ISSUE THREAD

**Issue by xDeathBunnyx** [rlf/uSkyBlock#949]
_Please paste the output from `/usb version` below_
```
Current version is 2.7.2
https://gyazo.com/941bf2cb04eccfbd271a1806473ccd7e
```

_What steps will reproduce the problem?_

Going through the config file I see that the default protection range is 128, so I change it to 151 and restart the server. It worked. The new island range is 151 blocks, but when I counted the blocks from each side of the bedrock I noticed the island isn't centered. I'm using the default schematic, going South I can place 76 blocks from the bedrock, going North I can only place 73 blocks, West I can place 75 blocks, and East i can place 74 blocks. why cant I place 75 blocks in each direction from the bedrock? Is it a problem on my end? or is it because with the new update the middle of an island is 4 blocks rather then 1?

**Comment by dutchy1001** [comment]
Basically this is not an issue but an OCD problem.
Why it's not exactly in the middle I cant tell you, but whenever you have an island with an uneven width and an even distance value it will never be in the middle. When you have an island with an even width then there isnt an exact middle of the island. However you look at it there will always be something not exact centred. 
I rather have an even distance set so they fit nice around my spawn island. When on an island ypou really wont see that 1 side is shorther then the other

**Comment by xDeathBunnyx** [comment]
oh ok. I've never had that problem with the other versions of this plugin. I guess I'll have to deal with it.

**Comment by rlf** [comment]
It's introduced to allow us to create island-regions that are chunk-aligned (16 blocks) - since 16 blocks are an even number, we cannot totally center an island, since the center block would require the same radii in all directions, making it impossible to align to chunk.

Rejected.
