### ISSUE TITLE
custom nether Schem issues

### ISSUE THREAD

**Issue by AcesGamingUK** [rlf/uSkyBlock#950]
_Please paste the output from `/usb version` below_
```
13.12 15:18:52 [Server] INFO Name: uSkyBlock
13.12 15:18:52 [Server] INFO Version: 2.7.2
13.12 15:18:52 [Server] INFO Description: Ultimate SkyBlock v2.7.2-45f756-430
13.12 15:18:52 [Server] INFO Language: en (en)
13.12 15:18:52 [Server] INFO State: d=400, r=64, i=122, p=128, n=true, awe=true
13.12 15:18:52 [Server] INFO Server: CraftBukkit git-Spigot-078e2f8-9ff3d7f (MC: 1.10.2)
13.12 15:18:52 [Server] INFO State: online=false, bungee=true
13.12 15:18:52 [Server] INFO ------------------------------
13.12 15:18:52 [Server] INFO Vault 1.6.6-b65 (ENABLED)
13.12 15:18:52 [Server] INFO WorldEdit 6.1.3;7a097ca (ENABLED)
13.12 15:18:52 [Server] INFO WorldGuard 6.1.2;e38d98d (ENABLED)
13.12 15:18:52 [Server] INFO AsyncWorldEdit 3.4.7 (ENABLED)
13.12 15:18:52 [Server] INFO Multiverse-Core 2.5-b717 (ENABLED)
13.12 15:18:52 [Server] INFO Multiverse-NetherPortals 2.5-b675 (ENABLED)
```

_What steps will reproduce the problem?_
We Have Used a custom nether Schematic, however, we have two issues,
1. the nether side portal spawns attached to the ceiling of the nether instead of the schematic
2. the spawners in the schematic load a pig spawners and not the entity they were assigned

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin 

Thanks in advance

**Comment by rlf** [comment]
Hi.

First of, it sounds like a WorldEdit issue.
1. Is the portal "turned on" in the schematic? (if you paste it using WE, will it show portal-frames - the purple ones).
2. Is the scaling correctly set to 1 between overworld and nether?
3. Is the pig-spawner correct when loading/pasting using WorldEdit?

**Comment by AcesGamingUK** [comment]
1 yes
2 i can't see haw to check that sorry
3 yes they are pig instead of the actual mob

**Comment by dutchy1001** [comment]
you can check the scaling in the Multiverse_core worlds.yml.
Look for skyworld_nether (if you left the default settings) and you should see the scaling there.
