### ISSUE TITLE
Riding in other worlds not permitted

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#951]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.7.3-alpha12
Description: Ultimate SkyBlock v2.7.3-alpha12-4d9c77-447
Language: en_GB (en_GB)
State: d=256, r=128, i=6, p=7, n=true, awe=true
Server: Paper git-Paper-963 (MC: 1.11)
State: online=true, bungee=true
Vault 1.5.6-b49 
WorldEdit 6.1.6-SNAPSHOT;3654-9c32ba3 
WorldGuard 6.2.1-SNAPSHOT;1695-6e56763 
FastAsyncWorldEdit 16.12.13-1b07dba-432-9.19.12 
Multiverse-Core 2.5.0-SNAPSHOT-b725 
Multiverse-Portals 2.5.0-SNAPSHOT-b748 
Multiverse-NetherPortals 2.5.0-SNAPSHOT-b714
```

_What steps will reproduce the problem?_
1. go to an other world the the skyworld
2. make a boat and place in water
3. message in yellow "Riding is only allowed on your own island!"

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin 
No log needed for this issue

_Note:_ 
This can be bypassed with the _**usb.mod.bypassprotection**_ But should not be needed to give out for non skyblock worlds

**Comment by rlf** [comment]
Work-around: Disable `vehicle-enter` check (set it to `true`) in `config.yml`.

**Comment by dutchy1001** [comment]
Tested this with the setting `vehicle-enter: true` but didn't sovle the issue. Still in the survival world the same message appears and you wont be able to get into the boat.

**Comment by dutchy1001** [comment]
For the use of chairs you need to set the `vehicle-enter: true` in the config or it will produce the same message as for the boat previously.
