### ISSUE TITLE
Terraforming Not Working on Any Island but My Own

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#956]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.7.2
Description: Ultimate SkyBlock v2.7.2-45f756-430
Language: en (en)
State: d=128, r=64, i=515, p=688, n=true, awe=false
Server: CraftBukkit git-Spigot-4af49dc-23da8b0 (MC: 1.9.4)
State: online=false, bungee=true
------------------------------
Vault 1.5.3-b37 (ENABLED)
WorldEdit 6.1.3;7a097ca (ENABLED)
WorldGuard 6.1.2;e38d98d (ENABLED)
Multiverse-Core 2.5.0-SNAPSHOT-b725 (ENABLED)
Multiverse-NetherPortals 2.5.0-SNAPSHOT-b714 (ENABLED)
------------------------------
```

_What steps will reproduce the problem?_
I am not sure. I tested my island and I could terraform by breaking netherrack. I deopped myself and set myself to the default rank and I could still terraform. I cannot terraform on any other nether island and neither can the members of those islands. I believe this problem arose when I updated from 1.8 to 1.9 a few months ago. Not quite sure what is preventing terraforming from working on any other islands.

**Comment by rlf** [comment]
Terra-forming should only "work" on your own island.
And only when the blocks are broken using an appropriate tool.

**Comment by TheMattVid** [comment]
I understand that, but the important part is terraforming is not working for anyone else on their own nether islands. They break netherrack with any pickaxe, all they get is the netherrack back. Nothing new spawns for any user. I've watched multiple users try this and can confirm that it isn't working for them. I would like to know what I may have possibly misconfigured so I can fix it.

**Comment by dutchy1001** [comment]
First thing to do then is to post the config so we can see what has been configured wrong.
You can set different blocks to spawn in the config to allow all sorts of blocks. 

By default netherrack is 85%, 5%soul sand and 5% quartz ore so getting different blocks will take some time (and luck). You can add as many blocks types as you want.

**Comment by TheMattVid** [comment]
Here is the config file:

http://pastebin.com/U3ZKsREK

**Comment by dutchy1001** [comment]
You have the default terraforming setting as I do.
Just tried on my own island, Deopped and as normal player, but the terraforming just works as it should.
Using MC 1.11.2 and USB alpha15. Nothing has been adjusted for a while on this system so it should be the same for the version you use (2.7.2)

**Comment by TheMattVid** [comment]
Yes, that's what I am getting at. Something during an update perhaps "bugged" or "corrupted" other people's nether islands, and I cannot figure out for the life of me why they are unable to use terraforming on their own islands. I will further test this to see if newly generated islands have terraforming working.

**Comment by rlf** [comment]
Might be due to a misconfigured/created nether world.

If the scaling isn't 1 - their islands won't be correctly detected - i.e. the plugin won't think they are mining on their own island.

Try out the `/usb region` command to check the boundaries.

**Comment by TheMattVid** [comment]
I did some digging. It does seem like a valid possibility, since my island, which is near the center of the nether, seems to be the only one working of the players who have tried it out. I checked the multiverse worlds file and all scaling seems to be set to 1.0. The entering and leaving messages are all properly aligned with each of the nether islands. ```/usb region show``` also shows a border around the island with the proper owner.

**Comment by TheMattVid** [comment]
I just did some testing and terraforming worked for another player. The island was made a long time ago. However, this was the first time he went to the nether on his island. Terraforming seems to be broken for anyone who had already visited their island prior to updating my server to 1.9.

**Comment by TheMattVid** [comment]
Ok, after some more testing, it actually works and there were false reports. One player had it not working before apparently and it works now. Another player didn't have it working because he was using a gold pick. I tested it myself, and the gold pickaxe does not work. So I can confirm that terraforming isn't broken for me, but gold is.

**Comment by TheMattVid** [comment]
Closing because I just realized gold is at 0 in the config file, so everything is functioning as expected.
