### ISSUE TITLE
Limit request for restarting island

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#959]
Is it possible to make a limit on the amount of times an island can be restarted?
This is to avoid abuse when multiple players join 1 island and take on turns to create a new island to benefit the resources.
A permission like _usb.island.reset.X_ where X is the value that can be reset is an option or/and a reset command that can be done by an moderator or admin would help for legit players to restart

**Comment by supertin** [comment]
Normal players learn from their mistakes, so a sliding restart timer might work for everyone....

First restart requires the island to be 1 hour old.
Then multiply the restart timer by the number of restarts +1, so second restart requires 2 hours, then 4, then 8. This way the restart abuse becomes uneconomical exponentially.

You could have that written in the config in the same style as extra items in challenges. eg "60;*2" for 60 minutes, multiply by 2 each time.

**Comment by rlf** [comment]
I like the non-linear incremental cooldown, but it should probably diminish over time.

Meaning, if I have played on the server for a long time, and I don't get a sapling on my 7 th iteration of island, I shouldn't be punished the same, as one that has restarted the island 7 times in an hour.

**Comment by supertin** [comment]
Oh yeah. For sure. That'd be annoying.
Maybe factor in challenge completions or something that indicates actual island participation?

**Comment by rlf** [comment]
Usually "simple is better", and the more factors we take into the equation, the more complex it becomes.

Currently we have a fixed cooldown of `restart` (aka `create`), i.e. only factor is time `t` (in seconds).
Your original proposal introduced the number of restarts (an integer, `n`), challenge completions `cc` could be used, but also mis-used.

Not sure what the right mix of simplicity and flexibility is, but perhaps your original proposal, with an additional timeout to reset the `n` (sort of like we have with the challenges).

**Comment by dutchy1001** [comment]
I just suggested a simple value addition besides the timed restart to be added.

**Comment by Disorbs** [comment]
max-resets: 2 #use permission usb.island.reset.x to allow more resets


would be cool in the config.

**Comment by BlackBeltPanda** [comment]
There's also #700

**Comment by rlf** [comment]
Nice necro @BlackBeltPanda - I agree, 2 issues call for re-prioritization!

**Comment by dutchy1001** [comment]
my memory doesn't go back that far (I only got 256mb left after the holidays)

**Comment by BlackBeltPanda** [comment]
I only remembered because I wrote it. XD
Was reading this and thinking "Hm... This sounds familiar.."  XD
