### ISSUE TITLE
uSkyblock & Multiverse issue need help!

### ISSUE THREAD

**Issue by Jamplifier** [rlf/uSkyBlock#960]
https://i.gyazo.com/a128782cabe4ada8f23de57ab3a9c5ed.png
uskyblock and multiverse error no skyblock commands work anymore.

**Comment by rlf** [comment]
Please supply the full output of `/usb version`.

**Comment by dutchy1001** [comment]
Also a proper log and not a srceen shot will be better

**Comment by Jamplifier** [comment]
http://pastebin.com/MfcGeC8S
That is the log ^
/usb version doesnt even work, no skyblock related commands process. This only happened when I installed multiverse.

**Comment by dutchy1001** [comment]
If the command of **/usb version** doesnt work a full (meaning from start till server is loaded) log would give us answers we need to know.

**Comment by Jamplifier** [comment]
Full startup log:
http://pastebin.com/ffjDNBUw

**Comment by dutchy1001** [comment]
I think you should read the "installation" page again and see what depended plugins and their versions are needed.
Read it [here](https://dev.bukkit.org/projects/uskyblock/pages/installation) or [here](https://github.com/rlf/uSkyBlock/wiki/Installation)

**Comment by Jamplifier** [comment]
^ fixed ty
