### ISSUE TITLE
Spawn limits not working (villagers & pigs tested)

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#962]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.7.3-alpha16
Description: Ultimate SkyBlock v2.7.3-alpha16-08f268-451
Language: en_GB (en_GB)
State: d=256, r=128, i=23, p=26, n=true, awe=true
Server: Paper git-Paper-1020 (MC: 1.11.2)
State: online=true, bungee=true

Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.7-SNAPSHOT;3662-a8d04c2 (ENABLED)
WorldGuard 6.2.1-SNAPSHOT;1698-c0f3171 (ENABLED)
FastAsyncWorldEdit 17.01.02-8c94489-484-9.26.7 (ENABLED)
Multiverse-Core 2.5.0-SNAPSHOT-b725 (ENABLED)
Multiverse-Portals 2.5.0-SNAPSHOT-b748 (ENABLED)
Multiverse-NetherPortals 2.5.0-SNAPSHOT-b714 (ENABLED)

```

_What steps will reproduce the problem?_
1. limit is set as default (16 villagers)
2. You can spawn more then 16 villagers (unlimited)
3. This happens also with v2.7.2 and MC 1.11.2

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin 
There is no error in the log

**Comment by rlf** [comment]
Are you testing as a non-OPed user? Since OPs can spawn unlimited

**Comment by dutchy1001** [comment]
I used alt Stampy as normal player, but will retest later
