### ISSUE TITLE
/usb island protectall takes too much time

### ISSUE THREAD

**Issue by UnioDex** [rlf/uSkyBlock#964]
Hi. In my old uSkyBlock server (custom 2.0.1 RC.39) islands are not protecting with WorldGuard. Now im updated to latest version but /usb island protectall takes too much time. I have 149k islands and 88k islands has protected in 24 hours. I still have a lot of islands to protect. So i have an idea to reduce the time.  Only newer islands are important to protect. Older players usually created the island and never join the game again. So, can you add an argument to this command like time-in-days. For example "/usb island protectall 30" command will protect only active islands that joined the game in last 30 days. The opposite of the purge command. Purge command perform inactive islands but this will only perform active islands. 

I hope i can tell what i think with that English xD

**Comment by dutchy1001** [comment]
I dont think there are many servers that will update from v2.0,1 (and special not a "custom" version as they were never supported). Therefor newer servers will not have this protection issue as those servers will have the protection already in place for their island.

**Comment by UnioDex** [comment]
But it wont change the fact that protectall takes too much time. It will also help some server owners that deleted WorldGuard folder accidentally or some technical issues.

**Comment by dutchy1001** [comment]
Your trying to update from a "custom 2.0.1 version" to version 2.7.2 (or a newer dev build) you are asking for major issue's. The gap between those versions is way to big with so many changes made over the last 2.5 years.
Between your "custom 2.0.1" and our latest v2.7.3 alpha16  are atleast 280 releases made, you cant expect this to go smooth then.
As you said you have 149k island, this takes such a massive amount of disk space up that any program will struggle to go through this quick. I bet from the 149K less than 15% are atm active islands which would make a purge of the other 85% a way better idea then protecting islands that are never used anyway. 
It wont reduce the world size but it will free up spaces it wont have to look at and will re-use those spaces, for new players, which then prevent the world to get any bigger.

**Comment by UnioDex** [comment]
You are right but i don't want help for the update process, i can't. It was my fault that I never made updates. I only want a little extension to a command that only protect active islands.

**Comment by UnioDex** [comment]
I'm telling for information;
There is no problem with updating. I made purge and removed 110k island. Now everything seems cool.

**Comment by dutchy1001** [comment]
wasn't far off then with 85% abandoned lol. 
All should now have protection too
