### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by Twonox** [rlf/uSkyBlock#965]
Sometimes, when my players do `/is` or `/is h`, my server crash _(in the logs, there is always these command which are executed before the crash)_.

Error log before crash:
https://hastebin.com/qeqiluvoya.vbs

Version:
https://hastebin.com/cequkogele.vbs

**Comment by dutchy1001** [comment]
You didn't follow the template we request for bug reports.

Nothing indicated there that this has to do with uSkyblock.

**Comment by Twonox** [comment]
It's due to USkyBlock.

> [13:13:19] [Server thread/INFO]: GTAfan44 issued server command: /is home
> [13:13:19] [Server thread/ERROR]: Encountered an unexpected exception
> java.util.ConcurrentModificationException
> 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_111]
> 	at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_111]
> 	at net.minecraft.server.v1_8_R3.EntityTracker.updatePlayers(EntityTracker.java:175) ~[Spigot-stb188.jar:git-Spigot-21fe707-e1ebe52]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:803) ~[Spigot-stb188.jar:git-Spigot-21fe707-e1ebe52]
> 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) ~[Spigot-stb188.jar:git-Spigot-21fe707-e1ebe52]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) ~[Spigot-stb188.jar:git-Spigot-21fe707-e1ebe52]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-stb188.jar:git-Spigot-21fe707-e1ebe52]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
> [13:13:19] [Server thread/ERROR]: This crash report has been saved to: /home/minecraft/multicraft/servers/server1/./crash-reports/crash-2017-01-22_13.13.19-server.txt
> [13:13:19] [Server thread/INFO]: Stopping server
> 
> 
> [13:22:53] [Server thread/INFO]: GTAfan44 issued server command: /is home
> [13:22:53] [Server thread/ERROR]: Encountered an unexpected exception
> java.util.ConcurrentModificationException
> 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_111]
> 	at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_111]
> 	at net.minecraft.server.v1_8_R3.EntityTracker.updatePlayers(EntityTracker.java:175) ~[Spigot-stb188.jar:git-Spigot-21fe707-e1ebe52]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:803) ~[Spigot-stb188.jar:git-Spigot-21fe707-e1ebe52]
> 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) ~[Spigot-stb188.jar:git-Spigot-21fe707-e1ebe52]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) ~[Spigot-stb188.jar:git-Spigot-21fe707-e1ebe52]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-stb188.jar:git-Spigot-21fe707-e1ebe52]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
> [13:22:53] [Server thread/ERROR]: This crash report has been saved to: /home/minecraft/multicraft/servers/server1/./crash-reports/crash-2017-01-22_13.22.53-server.txt
> [13:22:53] [Server thread/INFO]: Stopping server

**Comment by dutchy1001** [comment]
yet again you didnt follow the template with the info we need to help.

**Comment by Twonox** [comment]
What other info you need ?

**Comment by dutchy1001** [comment]
When you open a new issue it ask for some details, without that we cant help as we are deended on that info to determent what can cause the error.

**Comment by Twonox** [comment]
All of these info are here...
You have the commands which does the crash, the error log and the versions.

**Comment by dutchy1001** [comment]
It's OK if you don't want to post the output of /usb version.

**Comment by Twonox** [comment]
Hmm... there is already the output of /usb version
I added it 2 seconds before your first comment, possible you didn't see.

**Comment by dutchy1001** [comment]
When editing a message you dont get notification, and with the page open you cant see that then. When asked you should have posted it in a new message and it would have been a lot clearer.

As of your issue, I still cant see this is caused by uSkyblock, yes the command is triggering this but something else is making the crash.
What is the last thing you updated before this was hapening?

**Comment by Twonox** [comment]
This issue happen since a long time, I report it only today.
I tried to reproduce the crash, executing /is and /is home, but it was not successful :/

**Comment by dutchy1001** [comment]
with other words there is no issue now anymore?

**Comment by Twonox** [comment]
Nope, only when /is or /is home are executed.

**Comment by dutchy1001** [comment]
Are you using the latest 1.8.8 build?(update to 1.11.2 would be benficial)

**Comment by Twonox** [comment]
Yes, I use latest 1.8.8 build and I wont use 1.11.2

**Comment by dutchy1001** [comment]
OK of topic maybe but what reason is there not to update?

Try a dev build of USB [alpha16](https://github.com/rlf/uSkyBlock/releases/download/v2.7.3-alpha16/uSkyBlock-bukkit1.8.jar), link will download the 1.8 version.
If that doesnt help I dunno. Any of the mentioned code in your error/crash log is not in our code, hense the reason I dont think it's caused by USB

**Comment by Twonox** [comment]
I will test this build, thanks.
Would you a full crash report ?

**Comment by dutchy1001** [comment]
If a crash happens yes post full log through hastebin or pastebin plz

**Comment by Twonox** [comment]
https://hastebin.com/xejejiyure.sm

Is there any changes to do in the config files with alpha16 ?

**Comment by dutchy1001** [comment]
You shouldn't have to alter your config when updating to alpha16.
The log you posted is a client crash, I need a (full) server log instead.

A client crash is something we cant do anything about only thing I can suggest is to redownload that version from Mojang.

**Comment by Twonox** [comment]
When I did `/usb goto GTAFan44` (_this is the player who has executed `/is home` before the last crash)_, the server get crash like other times.
But now, I can do `/usb goto GTAFan44` without causing a crash.
So, this can't be a world corruption.

**Comment by dutchy1001** [comment]
you still have USB 2.7.2 in your server  (according to the client crash log) so the update to alpha16 wasnt correct done.

**Comment by Twonox** [comment]
Yes, now I updated to alpha16. I just wanted to do more test before updating.

**Comment by Twonox** [comment]
I will tell you if a crash happen again (with alpha16)

**Comment by Twonox** [comment]
It happen again :/

**Comment by dutchy1001** [comment]
I've setup a quick 1.8.8 test server and can not reproduce this with the default plugins only, I suggest you do the same at home then add each plugin till the error occurs.
This is probably the only way to find out which plugin is causing this issue.

**Comment by Twonox** [comment]
It not happen always... Just for one of 50 players.
I can't reproduce it when I want.

**Comment by dutchy1001** [comment]
But it always happen to/with GTAfan44?

**Comment by Twonox** [comment]
It seems that happen always.
I will do my test with him.

**Comment by dutchy1001** [comment]
Also check if he has a modified client

**Comment by Twonox** [comment]
Sometimes, when I do `/usb goto GTafan44` the server crash and I use normal 1.8.8 version.
Can't be caused by the player client.

**Comment by rlf** [comment]
Sounds like it's related to some of the other UUID issues, when players have mixed-case playernames.
