### ISSUE TITLE
Brown Sheep map to Orange

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#966]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.7.3-alpha16
Description: Ultimate SkyBlock v2.7.3-alpha16-08f268-451
Language: en (en)
State: d=500, r=152, i=1,924, p=12,929, n=false, awe=true
Server: Paper git-Paper-1032 (MC: 1.11.2)
State: online=true, bungee=true
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.7-SNAPSHOT;3674-9f24f84 (ENABLED)
WorldGuard 6.1.2;e38d98d (ENABLED)
FastAsyncWorldEdit 17.01.15-812c12f-505-10.3.0 (ENABLED)
Multiverse-Core 2.5-b719 (ENABLED)
Multiverse-NetherPortals 2.5-b710 (ENABLED)
------------------------------
```

_What steps will reproduce the problem?_
1. Create a challenge that requires brown sheep
2. Attempt to complete it without the brown sheep
3. Notice the challenge states you're missing an orange sheep

**Comment by rlf** [comment]
There is no color code for writing in brown text, hence we mapped it to orange (the closest one).
Not sure how to fix this?

**Comment by BlackBeltPanda** [comment]
Might have to have a separate color map for wool, carpets, sheep, etc. for their data values. Though dyes, through Mojang's infinite wisdom, are opposite. >.<
