### ISSUE TITLE
Random Players are Added to Random Islands

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#969]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.7.3-alpha16
Description: Ultimate SkyBlock v2.7.3-alpha16-08f268-451
Language: en (en)
State: d=500, r=152, i=1,971, p=12,975, n=false, awe=true
Server: Paper git-Paper-1032 (MC: 1.11.2)
State: online=true, bungee=true
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.7-SNAPSHOT;3674-9f24f84 (ENABLED)
WorldGuard 6.1.2;e38d98d (ENABLED)
FastAsyncWorldEdit 17.01.15-812c12f-505-10.3.0 (ENABLED)
Multiverse-Core 2.5-b719 (ENABLED)
Multiverse-NetherPortals 2.5-b710 (ENABLED)
------------------------------
```

_Description of the problem:_
I've had a few reports lately of players showing up on other players' island members lists. I was chalking it up to players simply forgetting they added someone or not removing them properly until it happened to a couple of my staff members simultaneously. It seems that players will randomly appear in random players' members lists, even if the player appearing in the list already owns an island. Removing them with "/is remove <player>" or "/usb island remove <player>" doesn't seem to work in some cases, but other times "/is remove <player>" does work. If I add them with "/usb island addmember <player>", I can then remove them with "/usb island remove <player>" but have to re-register them to their original island afterwards.

It gets really strange after that. When a player on an affected island tries to change permissions for ANY other player, it instead opens the permissions menu for the player that was randomly added to the island. If they then change any permissions, the player gets re-added to the island.

I wish I had more info or errors to post, but that's all I've got. =(

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* Affected island file 1: http://pastebin.com/raw/S5qnWNmb
* Affected island file 2: http://pastebin.com/raw/rfLBDisZ
* Player file for player appearing in the members list: http://pastebin.com/raw/0W2E82uU

**Comment by BlackBeltPanda** [comment]
Some pictures, because those are always nice:
Island info before: https://cdn.discordapp.com/attachments/85493600086921216/275034931145736202/Screenshot_30.png
Permissions GUI showing only one member, siddey10: https://cdn.discordapp.com/attachments/85493600086921216/275034974200004619/Screenshot_31.png
Permissions edit GUI showing, even though siddey10 was clicked, Cams1234's permissions: https://cdn.discordapp.com/attachments/85493600086921216/275035015560167425/Screenshot_32.png

Seems "Cams1234"'s permissions are showing up for everybody who attempts to open the Permissions edit GUI, now. >.<

**Comment by UnioDex** [comment]
alpha16 is not safe i think. My players losing their islands.

**Comment by Joapple** [comment]
This happens to me as well, but i managed that every time a player will open the member's permission to change them, it will be me, as head-admin it's less bad, because others was losing their island access that way, even if i lose my island it's not a bad thing yet..

**Comment by BlackBeltPanda** [comment]
I can confirm that attempting to remove the extra user from your island removes the user from their own island, instead.

**Comment by Joapple** [comment]
What i did to fix a broken island that way, 
purged the island he should really belongs to:
Ex: I'm owner of my island
i'm part of BlackBeltPanda island (Examplehere)
i purge my island, then register me again
It should update BlackBeltPanda's island, not sure though, but it worked once for me

**Comment by BlackBeltPanda** [comment]
I'll give that a shot next time I see it happen, thanks. =)

**Comment by BlackBeltPanda** [comment]
Not sure if it helps, but I grabbed the player and island files for one of the players that was randomly showing up on other players' islands.
Player file: http://pastebin.com/raw/fGYCyT5U
Island file: http://pastebin.com/raw/airMPaCn

**Comment by Joapple** [comment]
And if you click to edit the permission, it will add that player to your island while it shouldn't

**Comment by rlf** [comment]
Thanks @BlackBeltPanda  - I will try to get some time to look in to it this weekend.

**Comment by Joapple** [comment]
Check @Talabrek fork he did a temp fix to cancel being added to random island

**Comment by rlf** [comment]
Thanks! I just merged his changes in.

Hope it helps

**Comment by rlf** [comment]
The fixes I got from Talabrek doesn't seem to fix this. But I think I have an idea what is going wrong - and if I'm correct, it only happens when multiple players access the permission menu at the same time (i.e. we have info leaking between players).

**Comment by BlackBeltPanda** [comment]
It definitely happens for me with only one player accessing the menu at a time.

**Comment by Joapple** [comment]
When me and tala tried it, it was on a test server with only 1 player opening the /is menu

**Comment by BlackBeltPanda** [comment]
I reported it immediately after I noticed it happening for the first time. I'm not sure if it was happening at all before that; I've noticed players don't like to report bugs to my staff or me, lol.

**Comment by Joapple** [comment]
I think it happened when we switched to 1.11, i don't recall that bug in 1.10, same here @BlackBeltPanda Players find that bug funny, i found it out when one of our player loss access to his island, he was on 4 island on the is top >.> The fixes Talabrek did just prevent them to be added to the island, it doesn't fix the bug, just prevent mess that we'll have to fix later

**Comment by rlf** [comment]
I think I have an idea then. About when they released 1.11, they changed the ability to load player-skins - most likely connected to the way we identify the skulls in that piece of UI. I will see if I can find a work-around, the fix from Talabrek at least stops the permission UI of accidentially adding wrong players to an island.

**Comment by Joapple** [comment]
Any news on that? My players keep asking me how to edit members permission, but with the fix Talabrek did, it doesn't completely fix it, it only prevent wrong members to be added to the island.

**Comment by rlf** [comment]
Looking at it to day...

**Comment by BlackBeltPanda** [comment]
This seems to have been fixed; haven't received any more reports of it happening. =)
