### ISSUE TITLE
Players Cannot place blocks

### ISSUE THREAD

**Issue by DarkNova101** [rlf/uSkyBlock#972]
_Please paste the output from `/usb version` below_
```
http://prntscr.com/e28lc8

```

_What steps will reproduce the problem?_
1. Make an island, break a block cannot replace.
2. Go back to your island, cannot place blocks.
3. Tried on another account no prevail.
 
_Extra Info_
1. You can place blocks if opped.
2. I have tried changing the World Guard Region Flags for the island and __Global__, nothing happens.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

(Not following the template will result in closing the issue.)

**Comment by dutchy1001** [comment]
This is a permission issue, check the Essentials build/break permissions.

**Comment by DarkNova101** [comment]
Ok thanks, ill look at that.

**Comment by DarkNova101** [comment]
Do you know what perm node? I did essentials.build and it didn't work.

**Comment by dutchy1001** [comment]
If they have _essentials.build_ then they should be able to build and break. 
Is there any other plugin that could interfere with build/break??

**Comment by DarkNova101** [comment]
I am not sure.

**Comment by dutchy1001** [comment]
can you as OP build and break?

**Comment by DarkNova101** [comment]
Yes. When you aren't opped you can only break not place

**Comment by DarkNova101** [comment]
If this helps we use group manager

**Comment by dutchy1001** [comment]
I havent used GM for a while.
Could you post the perm file (through [pastebin](http://pastebin.com/) plz) and a list of your plugins?

**Comment by DarkNova101** [comment]
It will be a few mins but I will do that

**Comment by DarkNova101** [comment]
Nvm e figured it out, it was something with skript

**Comment by dutchy1001** [comment]
Thx for letting us know.
