### ISSUE TITLE
[Suggestion] Delete all entities when deleting island

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#976]
When using plugins that provide things like holograms via invisible armor stands or other entities, restarting an island usually results in holograms being left behind. Often times, since the block associated with it is removed, the hologram is then impossible for the player to remove without staff intervention. Removing all the entities from an island when it's deleted would remedy that and should improve compatibility with several plugins. =)

**Comment by rlf** [comment]
Not a bad suggestion, but not guaranteed to work either. But it should be doable.
Accepting this as a feature request.

**Comment by BlackBeltPanda** [comment]
Working with one caveat, which I created a pull request for. Closing. =)
