### ISSUE TITLE
Wiki is editable

### ISSUE THREAD

**Issue by Bloodrayne1995** [rlf/uSkyBlock#977]
Hello,

this isn`t an error of uSkyBlock. 
I noticed that ur wiki is editable for everyone. 
I tested it on [https://github.com/rlf/uSkyBlock/wiki/Nether-and-uSkyBlock](url)

I didn`t want to edit it. It was a conincidence.

Greetings
Bloodrayne1995

**Comment by dutchy1001** [comment]
It seems all wiki's are open on all repo's not sure this is a bug from github. 
Not sure what to do about it then making a backup from all pages.

**Comment by Bloodrayne1995** [comment]
Hi,

wow, ur right. I could create a wiki for NuVotifier.
I make a ticket by Github.

**Comment by rlf** [comment]
It's a feature of a wiki - that it's "community driven". I assume. I don't mind, if you fix misspellings, or elaborate on stuff, it's only for the better (IMO).

If you go destructive - the internet will know - and github supports history, so undoing other peoples destructive havoc is relatively simple.

**Comment by Bloodrayne1995** [comment]
Hi,

I got an explanation from Github Staff:

Hi Marcel,

im noticed that i could edit wiki pages of every open repositories.
I testet it on https://github.com/rlf/uSkyBlock and on https://github.com/NuVotifier/NuVotifier/wiki.
In both cases I could edit the wiki pages or create a wiki.
I don`t know if this a normal behaviour. Can you please tell me?

Thanks for writing in! This is normal behavior. By default, only collaborators on your repository can make changes to wikis, but you can configure this to be enabled for all users on public repositories.

https://help.github.com/articles/changing-access-permissions-for-wikis/

If you'd like more information about GitHub Wiki's, this article should help:

https://help.github.com/articles/about-github-wikis/

I hope this clears things up, but please let me know if you have any additional questions!

All the best,
Nick
@nickcannariato
GitHub Support

Just for your information

**Comment by dutchy1001** [comment]
thx for letting us know
