### ISSUE TITLE
Challenge: hanginggardens about "VINES"

### ISSUE THREAD

**Issue by Typhome** [rlf/uSkyBlock#978]
Our skyblock server players noticed that there's issue about this challenge.
Default config (challenges.yml):
`- VINES:256`
It shows as Barrier block but it's impossible to obtain barrier block.
It should be:
`- VINE:256`
And then it shows as Vine which means that this challenge now doable.

https://github.com/rlf/uSkyBlock/blob/master/uSkyBlock-Core/src/main/resources/challenges.yml#L1174

Version 2.7.3 alpha 16

**Comment by rlf** [comment]
@dutchy1001 can you check if this is something that changed between MC versions? I.e. if it's a simple change of the `challenges.yml` file, or we need to do some stuff to stay backwards compatible?

**Comment by dutchy1001** [comment]
Don't think any has changed, block name is "vine" and not "vines" id 106
