### ISSUE TITLE
How to make a polish language?

### ISSUE THREAD

**Issue by MagnetiQ** [rlf/uSkyBlock#980]
Hello, i have a question!

How to change language this plugin to polish?

**Comment by dutchy1001** [comment]
read this page here
[Localization](https://dev.bukkit.org/projects/uskyblock/pages/localization)

**Comment by MagnetiQ** [comment]
Thank You! :D


2017-02-12 13:12 GMT+01:00 dutchy1001 <notifications@github.com>:
