### ISSUE TITLE
Update 2.7.2 cause freezes ?

### ISSUE THREAD

**Issue by Bakalexis** [rlf/uSkyBlock#982]
```
Name: uSkyBlock
Version: 2.7.2
Description: Ultimate SkyBlock v2.7.2-45f756-430
Language: fr (fr)
State: d=160, r=80, i=34▒698, p=86▒197, n=false, awe=false
Server: CraftBukkit git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)
 State: online=false, bungee=true
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1;no_git_id (ENABLED)
WorldGuard 6.0.0-beta-04.1544- (ENABLED)
AsyncWorldEdit 2.3.2 (ENABLED)
Multiverse-Core 2.5-b699 (ENABLED)
```
_What steps will reproduce the problem?_
X I recently updated the plugin uSkyblock from 2.6.4 to 2.7.2, and there was no problems before, but now there is some random little freeze for no apparent reasons, I only changed this plugin, can somebody answer me about this ?

**Comment by rlf** [comment]
Could you please share (using pastebin) your `config.yml` for `uSkyBlock`?

**Comment by Bakalexis** [comment]
If I could help you : http://pastebin.com/EwXkZSGe

**Comment by rlf** [comment]
Ok, first off, it's a rather old release you "upgraded" to, it was released over a half year ago.
My bet is, that you have some sort of "top 10" display going, which will invoke the `island topten` or similar every X minutes (perhaps even as console). Back in v2.7.2 - we would re-calculate the ranks when the top command was executed as OP or console, meaning that sort of "scoreboards" would give a periodic performance impact.

It's my best bet, given that your issue report is very vague in terms of reproducible error description.

**Comment by Bakalexis** [comment]
I tried to disable the island topten, i'll tell you in a few days if the situation is better.

**Comment by Bakalexis** [comment]
Finally, the problem was the RelfectionUtil class was making 50000 errors/sec with a "usb debug FINEST" level, I upgraded to 2.7.3alpha23 and it now works perfectly.
