### ISSUE TITLE
suggestion reset limit

### ISSUE THREAD

**Issue by Diclo** [rlf/uSkyBlock#983]
Version: 2.7.3-alpha16
Description: Ultimate SkyBlock v2.7.3-alpha16-08f268-451
Language: es (es)
State: d=256, r=64, i=81, p=203, n=false, awe=false
Server: CraftBukkit git-Spigot-b32c8f8-4d3bf20 (MC: 1.11.2)
State: online=true, bungee=true
[10:38:00 INFO]: ------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.5;4651611 (ENABLED)
WorldGuard 6.1.3-SNAPSHOT;c904242 (ENABLED)
AsyncWorldEdit 2.3.2 (ENABLED)
Multiverse-Core 2.5.0-SNAPSHOT-b725 (ENABLED)
Multiverse-NetherPortals 2.5.0-SNAPSHOT-b714 (ENABLED)

Good as a suggestion, it would be nice to have a limiter or island reset counter.

**Comment by BlackBeltPanda** [comment]
Something like #700 ?

**Comment by rlf** [comment]
You are fast @BlackBeltPanda ... and yes, I acknowledge you are not alone in wishing something like that :D
