### ISSUE TITLE
NPE while trying to create island

### ISSUE THREAD

**Issue by mikroskeem** [rlf/uSkyBlock#988]
`/usb version` output:
https://paste.nightsnack.cf/raw/culumazewe

_What steps will reproduce the problem?_
1. Install [uSkyBlock](https://github.com/rlf/uSkyBlock/releases/tag/v2.7.3-alpha20), FAWE etc. and don't configure anything
2. Let worlds generate
3. Try to create island for yourself

[Stack trace](https://paste.nightsnack.cf/raw/owubatetuv)

**Comment by dutchy1001** [comment]
Multiverse is missing, add and test again.

**Comment by mikroskeem** [comment]
`Multiverse-Core 2.5.0-SNAPSHOT-b725 (ENABLED)`

Nothing changed.

**Comment by mikroskeem** [comment]
Hint: [this](https://github.com/rlf/uSkyBlock/blob/master/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/WorldEditHandler.java#L332) throws NPE. Maybe reflection above that line fails?

**Comment by dutchy1001** [comment]
I'm not the coder I only do support,Your Stack trace is empty so I cant see what it does.

**Comment by mikroskeem** [comment]
Whops, my bad. Link fixed

**Comment by dutchy1001** [comment]
Stack trace seems to refer to WorldEdit, try updating to [build 3380](http://builds.enginehub.org/job/worldedit?branch=master) or build 3381. I use myself 3380

**Comment by rlf** [comment]
Ye, I fixed this only locally, and you tested it Dutchy, but I forgot to deliver it...
My bad

**Comment by dutchy1001** [comment]
thx for the heads up, can you release this in an Alpha or beta?

**Comment by i9hdkill** [comment]
Same with 1.11.2 and WE 3652
https://pastebin.com/HgHd8eZa
http://prntscr.com/eg3bkn

**Comment by dutchy1001** [comment]
[alpha21](https://github.com/rlf/uSkyBlock/releases/tag/v2.7.3-alpha21) should fix this

**Comment by i9hdkill** [comment]
Yep, thanks!
