### ISSUE TITLE
Permissions wont work?

### ISSUE THREAD

**Issue by Braidon7676** [rlf/uSkyBlock#989]
http://pastebin.com/UZeCq1Ts

Literally no matter what i do permissions wont work and theres no error codes, Now they cant even kill mobs on there island they cant invite or kick members, Ive tried everythingg :( im running a 1.8.8 bukkit server

**Comment by dutchy1001** [comment]
have you tried to read the installation page?

By the look of how you posted you did not follow the template either

**Comment by Braidon7676** [comment]
Im missing the multiverse plugins although im running a standalone server i will add these tonight, It shouldnt of intereferred with island invite and create commands but i will try it out tonight! :) also it is giving everyone second islands now out of the blue /is home stopped working it kept there islands and they can build on them but there not set as there main island for some reason

**Comment by Braidon7676** [comment]
And when people join coop islands it keeps there old island

**Comment by Braidon7676** [comment]
We deleted and restarted everything and still having the same problems

**Comment by dutchy1001** [comment]
post a full log file from startup thought pastebin.com

**Comment by Braidon7676** [comment]
http://pastebin.com/kJT4aekM     --start up log
http://pastebin.com/QC33bJRg    -- when I do usb versions

**Comment by dutchy1001** [comment]
What permissions are not working?

**Comment by Braidon7676** [comment]
All of them, for example they cant kick or invite members to there islands, If they make an island then leave to join a friend its keeping there old island, it didnt delete the whole other world theres random chunks of land under neath instead of void ( thede may be cleared as more islands are created ) but im using PermissionsEX and no on can invite, sometimes they cant kill mobs on there island either

**Comment by dutchy1001** [comment]
Can you post the pex file with your permissions?

**Comment by Braidon7676** [comment]
okay so I got the permissions working now its just if you create an island then leave to join a friends island it deletes your island but keeps your like permissions there, so like if you fly through it it still says entering so and so's island but theres no actual island there. will that fix itself when someone else makes an island and it will take that spot?

**Comment by dutchy1001** [comment]
That is correct, it will be reset when a new island is created on that location. Just check the "orphan.yml" if that location is added for re-use.

**Comment by rlf** [comment]
Wrong commit ^ not related to this one...
