### ISSUE TITLE
Please add new Custom Events in the API . Player Create Island event , Player restart island event , and Player leave island event

### ISSUE THREAD

**Issue by solarfavor** [rlf/uSkyBlock#990]
The API seem not enough for developers like meh . Plz add author

**Comment by rlf** [comment]
Wording as "seems" doesn't fully convey the needs you have.

Could you please provide some example of what you intend to use these events for - so we can properly design them.

**Comment by UnioDex** [comment]
Your request is already exist. 

You can use RestartIslandEvent for Create Island and Restart Island.
Also you can use MemberLeftEvent for Player Leave Island event.

**Comment by solarfavor** [comment]
Sorry didnt see it in the docs . Tks for your help then
