### ISSUE TITLE
Abandoned Island Purging Hits Active Players

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#992]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.7.3-alpha16
Description: Ultimate SkyBlock v2.7.3-alpha16-08f268-451
Language: en (en)
State: d=500, r=152, i=2,347, p=13,356, n=false, awe=true
Server: Paper git-Paper-1062 (MC: 1.11.2)
State: online=true, bungee=true
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.7-SNAPSHOT;3674-9f24f84 (ENABLED)
WorldGuard 6.1.2;e38d98d (ENABLED)
FastAsyncWorldEdit 17.03.04-9e9339b-534-10.10.1 (ENABLED)
Multiverse-Core 2.5-b719 (ENABLED)
Multiverse-NetherPortals 2.5-b710 (ENABLED)
------------------------------
```

_What steps will reproduce the problem?_
1. Set the purgeLevel in the config to something really high, like "100000".
2. Run "/usb purge DAYS"
3. Notice that it removes all islands for all offline players instead of only players that haven't logged in within the last X days.

**Comment by BlackBeltPanda** [comment]
I tested this more on a local copy of my server and it seems to completely ignore players' last-played time unless they're online when the command is run.

**Comment by rlf** [comment]
Most likely yes, we need to handle the `null` defensively.
