### ISSUE TITLE
Alpha 22 - "/it" doesn't recognize there are other players on the island

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#997]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.7.3-alpha22
Description: Ultimate SkyBlock v2.7.3-alpha22-9687ae-457
Language: en_GB (en_GB)
State: d=500, r=152, i=2,383, p=13,389, n=false, awe=true
Server: Paper git-Paper-1062 (MC: 1.11.2)
State: online=true, bungee=true
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.7-SNAPSHOT;3674-9f24f84 (ENABLED)
WorldGuard 6.1.2;e38d98d (ENABLED)
FastAsyncWorldEdit 17.03.04-9e9339b-534-10.10.1 (ENABLED)
Multiverse-Core 2.5-b719 (ENABLED)
Multiverse-NetherPortals 2.5-b710 (ENABLED)
------------------------------
```

_What steps will reproduce the problem?_
1. Use "/it test" on an island with other players
2. You get the error, "You are talking to yourself" or similar. No errors in console.

**Comment by dutchy1001** [comment]
This is a joke build in. As there are no other party members online it will give this (and I think 3 other messages) as reply.

**Comment by BlackBeltPanda** [comment]
I mean, after updating to Alpha 22, it's not recognizing that there are other players on the island. So they get that error even when there's other players there to receive it.

**Comment by BlackBeltPanda** [comment]
False alarm. The players reporting the issue, and the island I test on, was orphaned.
